### ISSUE TITLE
Invoicing pricing

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#1020]
A couple of left over issues from #696 

- [ ]  Total on service charges doesn't update immediately after putting amount and tax in on modal

**Comment by andreievg** [comment]
@roxy-dao i remember you mentioning that something doesn't quite update immediately when changing currency, and noticed this issue might be similar and might have the same fix ? (in that case maybe can be closed if/when fixed through currency work)

**Comment by roxy-dao** [comment]
Oh this one is different... it doesn't even register the change in service charge... the api call being a bit slow when updating is an overall issue and not just for updating currency...

**Comment by roxy-dao** [comment]
Closing cause doesn't seem to be an issue anymore...
