### ISSUE TITLE
CC invoice type sequence

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#1145]
This was discovered while re testing this issue: https://github.com/openmsupply/open-msupply/issues/990
Seemed like a different priority/scope so ended up making a new issue, I think Chris summarised it quite nicely:

In testing the solution, a new bug was reported - if you initialise on omSupply a store that has use of customer credits in the earlier apps, then when you start making outbound shipments omSupply will have no idea what serial numbers are already used as ci and cc share the same sequence. Then on central server, you'll be able to see duplicates of serial numbers when looking across all ci and cc for the store.

Setting priority as `low`, this is not required for immediate deployments/milestones

**Comment by roxy-dao** [comment]
Is this still an issue now that we've implemented CC?

**Comment by andreievg** [comment]
@roxy-dao I think we would still see duplicates on central server when looking across all `ci` and `cc` for the store (if the store was moved to omSupply and had cc transactions). But i am not sure if it's a problem ¯\_(ツ)_/¯, i am ok with this issue being closed

**Comment by roxy-dao** [comment]
Will close issue for now and can reopen if it does become an issue
