### ISSUE TITLE
Correct fields for Patient endpoint

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#116]
Just thought we should clarify exactly which fields from "Name" we want to include in the "patient" endpoint.

We currently have:

![Screen Shot 2022-06-10 at 2 03 24 PM](https://user-images.githubusercontent.com/5456533/172975541-e86106fd-3bef-4163-8057-f028ade26e1e.png)

@mark-prins has suggested "createdDateTime" and possibly "chargeCode", so let's get an agreement (with some input from people more knowledgable about mSupply?) on what exactly should be included.

I kind of think there's no real downside to including more, so maybe we should just include all fields except the ones that inform the type (cos we know it'll be a patient), e.g. "type", "isDonor", "isCustomer", etc.

**Comment by clemens-msupply** [comment]
We don't need it for programs right now so lets defer this a little while.

**Comment by andreievg** [comment]
I am wondering if we can close this issue ?  Maybe when we get a chance to improve prescription UI was can revisit this ?

Please feel free to re-open if you think it's important enough to stay
