### ISSUE TITLE
Invoice totals 0 for stores which migrate from mSupply 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#1166]
Stores which have been migrated from mSupply to omSupply have inconsistency in the data resulting in some invoices having an invoice total of 0 even though the invoice lines for those invoices have cost/sell prices on them.

**Comment by Chris-Petty** [comment]
I haven't looked too deep but I believe the problem comes about from these fields:

![image](https://user-images.githubusercontent.com/7684221/217989049-4624f278-f79b-4ecc-8b32-fc4ad09f1356.png)

I presume they're used for the invoice total. If an invoice was made on mSupply mobile or desktop, all these fields will be 0. Either in translation or at least on initialising the site, it should try populate these denormalised fields I figure.

**Comment by DhanyaHerath** [comment]
**Triage:** Will be good to do, but will be higher priority once we are converting a specific site from mSupply (we can prioritise based on the datafile we are converting because there'll be many translation errors (likely))

**Comment by nisha-dangol** [comment]
Just dropping [this issue here](https://github.com/msupply-foundation/open-msupply/issues/2728); could be similar or related? @roxy-dao @mark-prins

**Comment by mark-prins** [comment]
Thanks @nisha-dangol  - I think not directly related, but even if they aren't it's good to have them grouped together (same area of the code)

**Comment by clemens-msupply** [comment]
Could you please provide a datafile with the problem? I can't reproduce it. The sell_price/cost_price get correctly translated here.

**Comment by roxy-dao** [comment]
> Could you please provide a datafile with the problem? I can't reproduce it. The sell_price/cost_price get correctly translated here.

Just checked with the datafile I have on right now. Seems to be translating correctly, but will keep an eye out.

**Comment by clemens-msupply** [comment]
I tried with another data file where om_ field where not set and it all seemed to work ok... Can you still reproduce it?

**Comment by roxy-dao** [comment]
> I tried with another data file where om_ field where not set and it all seemed to work ok... Can you still reproduce it?

Okiie. Nah, don't think. Will close and re-open if it becomes an issue. Thanks Clemens.
