### ISSUE TITLE
Reports: be able to bundled report arguments in the report

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#1313]
Currently, if a report needs some custom arguments, the arguments need to be uploaded along with the report to the central server.

This could be cumbersome for report designer, e.g. you need to upload three instead of one report related files to the central server, i.e. `report.json`, `argument-schema.json` and `argument-ui-schema.json`.

Alternatively, we could bundle the argument schemas into the `report.json` file. When uploading the report.json to the central server, the central server could then search for argument schemas in the bundle and autopopulate the `form_schema` table.

**Comment by roxy-dao** [comment]
Done during reports bundling (:
