### ISSUE TITLE
When adding items in internal order, the quantity numpad should probably appear after you select an item

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#1328]
## What went wrong? 😲
 
When adding an extra item to the list of items already included in the master list it is very difficult to choose one as the num pad appears before I chose my item and does not seem to be linked to anything because if you type something nothing happens. So the numpad just feel like a bit in the way. 

https://drive.google.com/file/d/1ajrp7CuBo0QcjK8qEADGuP9pxsTOOQ9F/view?usp=share_link
  
## Expected behaviour 🤔
I think the num pad should only appear when an item is chosen by the user. However it is not a big thing and for now it seems to be consistent throughout omSupply.

## How to Reproduce 🔨

Steps to reproduce the behaviour:
on omSupply
1. Go to Replenishment > Internal order
2. Press add from Master list. Add quantities to some items
3. Press the "Add an item" button at the bottom
4. See error. The numpad for the quantities appear straight away. Try to type something and nothing happens until you click in the field for filtering items
5. Try to scroll down. the list get send back at the top of the list when you scroll down a certain point
6. logout from omSupply and login again. Retry again and you will be able to scroll down without the list being send back to the top.

## Your environment 🌱
 - Version [e.g. 1.1.5]
 - Platform [e.g. tablet]

**Comment by DhanyaHerath** [comment]
@alainsussol would it be possible to add a video of this one please (can be a google drive folder linked here)? Sounds frustrating!

**Comment by andreievg** [comment]
Can use vysor to capture screen

**Comment by alainsussol** [comment]
@DhanyaHerath @andreievg I am about to recreate all the issues deleted because of client information screenshots or videos. I had a video for this one I think, I will use that time to add it to a protected google drive folder.

**Comment by alainsussol** [comment]
@DhanyaHerath @andreievg 
Well unfortunately I don't find my video and I cannot recreate the problem. After I logout and login in again the problem was not happening anymore. I will close this and reopen it if it happens again...

However at the same I think it would better if the quantity num pad would appear only when I have selected my new item. If you think it is possible, I can edit this issue and remove the part about the scrolling taking me at the top continuously and open another issue if it happens again...What do you think ?

**Comment by DhanyaHerath** [comment]
@alainsussol Yes please, I think that sounds good!

**Comment by roxy-dao** [comment]
Also, when you click `Add Item` and go to the Item list... numpad shows up instead of normal keypad

**Comment by roxy-dao** [comment]
Normal text pad seems to be appearing for me now when I add item to Internal Order and only changes to num pad once an item has been selected. Can someone else confirm this?

**Comment by mark-prins** [comment]
can confirm - same thing happens for me. thanks Roxy
