### ISSUE TITLE
How do we indicate "required" properties in forms?

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#1343]
It's common convention to denote required form fields via an asterisk or some other small marker, like so:

![Image](https://user-images.githubusercontent.com/5456533/224853140-8bacb87c-4328-4c9a-a304-88ad27603b78.png)

Currently we don't indicate required fields at all until validation (on submission). Just wondering if this is something we want, or are we happy with the current UI?

I can see it would be annoying if the majority of fields were required, but it could be useful in JSON Forms to let the user know before submission what they need to fill.

If the answer is "yes, this would be useful", then we should probably have a brief discussion about the best way to implement it in both native forms and JSONForms. 

(Material UI reference: https://mui.com/base/react-form-control/#basics)

**Comment by roxy-dao** [comment]
I think it would be useful, btw the link you provided is to project board XD

**Comment by CarlosNZ** [comment]
> btw the link you provided is to project board XD

Oops 😳 -- fixed now

**Comment by roxy-dao** [comment]
Mentioned in #513

**Comment by clemens-msupply** [comment]
Currently, we mark error fields with red error boxes (including "required" field not provided)
