### ISSUE TITLE
Programs: encounters list view -  add list filters and ability to create new encounters from this page

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#1344]
## Is your feature request related to a problem? Please describe 👀

It's frustrating that there is no kind of filters in the encounters list view. Ideally you should be able to filter the list by: 

- patient last name
- patient IDs 
- program
- date
- status

It is also frustrating that you cannot create an encounter from this page. 

## Describe the solution you'd like 🎁

Implement filters

Add a "New Encounter" button that would open a modal where you would first select a patient, and then a encounter form. 

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

N/A

### Moneyworks Jobcode 🧰

PG23THDVD

**Comment by andreievg** [comment]
related: https://github.com/openmsupply/open-msupply/issues/1342

**Comment by roxy-dao** [comment]
Filter by date before, after or equal to? 🤔

**Comment by richardmoizeau** [comment]
> Filter by date before, after or equal to? 🤔

Yes, don't see how you could do it otherwise... 🤔

Could also be date ranges, that's probably more useful ? 

<img width="202" alt="Screen Shot 2023-03-29 at 1 58 30 PM" src="https://user-images.githubusercontent.com/74992958/228399437-70ecab3d-524a-4b1e-ad7b-c879195866ac.png">

**Comment by roxy-dao** [comment]
Needs discussion on UI and implementation

**Comment by DhanyaHerath** [comment]
**Anisha says:** use design for filters from coldchain designs, use material ui component for date ranges

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Have programs set up
- [x] Enrol a few patients into some programs
- [x] Add encounter for those patients
- [x] Go to encounter
- [x] Test filters
