### ISSUE TITLE
Fix mSupply when customer invoice store is active on central

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#1396]
## What went wrong? 😲

Supplier Invoice is generated on central rather then on remote when customer invoice is created on central server active store for omSupply remote site store. This happens even when omSupply site has already been synced (and central store knows it's omSupply site). Also duplicate invoice lines have stock line from original invoice lines, those stocklines don't exist on remote site and invoice lines fail to integrate due to FK constraint (we handle this for foreign invoice lines, but not for owned invoice lines)

## Expected behaviour 🤔

Not sure weather this should be handles on mSupply or omSupply

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Try to do a stock transfer (customer invoice) from central site active store to remote omSupply active site store, you'll see outbound shipment, with -1 serial and no lines, and there would be error log, see comments in this PR: https://github.com/openmsupply/open-msupply/pull/1389#pullrequestreview-1349543612

**Comment by andreievg** [comment]
Related: https://github.com/openmsupply/open-msupply/issues/1396

**Comment by andreievg** [comment]
I think mSupply should be doing this, otherwise we would have fork in logic of how transfers are handled between mSupply and omSupply (i.e. when origin = remote mSupply site then omSupply creates transfer, and when origin = central mSupply site then mSupply does the transfer)

**Comment by roxy-dao** [comment]
Probably fixed in https://github.com/msupply-foundation/msupply/issues/12729
