### ISSUE TITLE
Can send internal orders without lines

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#1400]
## What went wrong? 😲
 
Can we do that ?

Customer on omSupply
![image](https://user-images.githubusercontent.com/11624516/226782378-01340c59-2e12-4b90-a45e-48471f4a5741.png)

Supplier on Mobile
![image](https://user-images.githubusercontent.com/11624516/226782728-29b4e1f1-8ae2-4c45-b9c6-e120886b86d9.png)

## Expected behaviour 🤔
I am not sure what is the expected behaviour is but I cannot see the point of letting somebody send a internal requisition that asks for nothing :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:
on omSupply
1. Go to 'Replenishment > Internal orders'
2. Click on 'New Order'
3. Don't add any lines and click 'Confirm sent'
4. See error. It has sent the internal order. The supplier receives an empty customer requisitions. 

## Your environment 🌱
 - Version [e.g. 1.1.6, mobile 8.0.8]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by roxy-dao** [comment]
This happens for outbound shipment and inbound shipment too...

**Comment by nisha-dangol** [comment]
## Testing
 Tested in v1.6.0-rc3 exe

### Tests
- [x] Create any invoice/requisition
- [x] See that the status confirmation button is disabled
- [x] Disable confirmation buttons if no lines for:
    - [x] Outbound Shipment
    - [x] Inbound Shipment
    - [x] Internal Order
    - [x] Prescriptions
