### ISSUE TITLE
Invoice lines sorting

### ISSUE THREAD

**Issue by bijaySussol** [msupply-foundation/open-msupply#1402]
## What went wrong? 😲

In need of lines sorting functionality exposed so that when in need to print the forms, We get a much control over the sorting instance by item name, Originally idea came through that.

## Expected behaviour 🤔

Same sorting as invoice to Invoice lines as well.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Print the outbound / Inbound invoice
   5. Printed details comes out randomly 

## Your environment 🌱
 - Version [e.g. 1.2.6]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by bijaySussol** [comment]
@andreievg : 
I can take this and start working on it, if no objection.

**Comment by andreievg** [comment]
duplicate: https://github.com/openmsupply/open-msupply/issues/2276

**Comment by raviSussol** [comment]
Opening as per https://github.com/msupply-foundation/open-msupply/pull/2342#pullrequestreview-1721558995.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe.
Report doesn't print now. Looks like there is problem with the json file, so @raviSussol to fix https://github.com/msupply-foundation/open-msupply-reports/issues/53
