### ISSUE TITLE
Patient links

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#1423]
Be able to derive a connection map or knowledge graph for connected patients. 
For example, record patient relations to other patients that have a certain condition.

Other examples:
- Patient 1 with infection 1 is the brother of Patient 2 who also has infection 1.
or
- Patient 1 (HIV) lives with Patient 2 (TB) 
- Analyze the spread of an infection over multiple patients

**Comment by DhanyaHerath** [comment]
Oh! Also this one, do you count the patient contact work as completing this, or more to go?

**Comment by DhanyaHerath** [comment]
> Oh! Also this one, do you count the patient contact work as completing this, or more to go?

Hi @clemens-msupply would you be able to check this issue please? :)

**Comment by clemens-msupply** [comment]
No, this hasn't been addressed yet and is not planned right now. But something to keep on our wish-list.

**Comment by clemens-msupply** [comment]
This was just an idea floating around, closing till it comes up again
