### ISSUE TITLE
Refactor four number input components into a single one

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#1440]
As mentioned in the discussion [here](https://github.com/openmsupply/open-msupply/pull/1433#discussion_r1151118288), there are four different number input components, which are almost the same:

![Screenshot 2023-03-29 at 11 33 29 AM](https://user-images.githubusercontent.com/5456533/228381680-a32b2afd-6059-4308-b64c-290972d352bf.png)

And they were not actually consistent -- the "PositiveNumberInput" is supposed to only accept numbers 1 and above, but was actually allowing `0` if you set `min = 0` (but not anything *less* than zero), making it practically indistinguishable from the "NonNegativeNumberInput" when used this way.

This is all very confusing, and [it was suggested](https://github.com/openmsupply/open-msupply/pull/1433#discussion_r1151118288) that it would be better to just have a single component and specify the range using `min` and `max` props if we need to restrict it.

The only other difference is "Integer" or "Decimal", but that also could easily be distinguished with a prop.

**Comment by CarlosNZ** [comment]
Sound reasonable, @mark-prins ?

**Comment by mark-prins** [comment]
It does - thanks. props would be good. The only case I can think of where the specific input is especially useful is as the component `Cell` prop on `Column` - it's tricky to pass in props ( I did add CellProps at one point, but it isn't in there now.. )

Not such an issue though, we have concrete instances of the various types of cell number components already.

**Comment by CarlosNZ** [comment]
![Screenshot 2023-03-29 at 2 12 43 PM](https://user-images.githubusercontent.com/5456533/228401004-825f5214-a613-45b1-9171-fd00f06ed610.png)

Yeah, good point. We can leave these different cell types as distinct components. However, they each use a different one of the aforementioned Number components, so we can just change them to all use the generic one and pass different min/max props to it for each of these cell components.

**Comment by CarlosNZ** [comment]
Further considerations when doing this:

- > it might make sense to have a prop which allows the undefined value. In which case the onChange event becomes easier to use as it will always return a valid number: [Comment](https://github.com/openmsupply/open-msupply/pull/1433#pullrequestreview-1362137995)
- We should make sure we get `develop` successfully merged into the feature branch before doing this, as we'll want the changes on both, and it'll get messy if we do one and not the other.

**Comment by CarlosNZ** [comment]
Bit of follow-up: I've done the first part of this in #2381 --have extended the main "NumericTextInput" with 3 additional props which allow it to contain all the functionality of the other Number inputs.

So all that remains to do here is remove the other three, then refactor wherever they're used to just use the single remaining one.

**Comment by CarlosNZ** [comment]
Quick update, just want to confirm that we agree on the following config for Numeric input:

- single numeric input, default is "Positive Integer" (min 1)
- additional optional props:
  - `allowNegative` (boolean)
  - `min` (overrides `allowNegative` if conflicting)
  - `max`
  - `precision` -- a number that specifies the number of decimal places of precision to allow. Obviously default is just `0`, hence integer only

I'll also include a fix for #2491
