### ISSUE TITLE
Inbound Shipment/stocktake: cannot remove a batch (stock line) if I mistakenly add one

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#1560]
## What went wrong? 😲
 

I added a second batch by mistake to an **Inbound Shipment** and I could not remove it and system would not let me click on OK until I enter data for that second batch

![Screen Shot 2023-04-18 at 11 26 41 AM](https://user-images.githubusercontent.com/74992958/232631920-4aaa4fb5-5d9c-48b7-9b36-75b010df094a.png)

**Stocktake**: system lets me proceed and add an empty stock line to the stocktake (unless I uncheck the "Count this line" box)

![Screen Shot 2023-04-18 at 11 35 07 AM](https://user-images.githubusercontent.com/74992958/232632858-2f1c254b-df99-4a26-a86d-0761c37b792c.png)

![Screen Shot 2023-04-18 at 11 35 31 AM](https://user-images.githubusercontent.com/74992958/232632882-a65e7aae-a015-4916-a89e-8327c5438727.png)

## Expected behaviour 🤔

- [ ] For inbound shipment: I should be able to remove the batch (or stock) line or the system should ignore if stock line has no data and let me proceed anyway (without creating extra empty lines in the shipment)

- [ ] For stocktake: I should be able to remove the batch (or stock) line or the system should ignore if stock line has no data and let me proceed anyway (without creating extra empty lines in the shipment)

## How to Reproduce 🔨

Replenishment > Inbound Shipments > Inb. Ship Detailed View > Add Item > Add Batch > try to remove batch 
Inventory > Stocktakes > Stocktakes detailed view > Add Item > Add Batch > try to remove batch line

## Your environment 🌱
 - Version: 1.1.11
 - Platform: remote server

**Comment by roxy-dao** [comment]
Closed in favour of #2492
