### ISSUE TITLE
Day to be enterable for expiry date

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#1611]
## Is your feature request related to a problem? Please describe 👀

@richardmoizeau noticed that `day` is not enterable for expiry date

## Describe the solution you'd like 🎁

Allow 'day' to be entered in expiry (only month and year are currently enterable). Still keep the helper calendar to be just month and year (as it is in mSupply

### Describe alternatives you've considered 💭

Keeping as is, @GaryWilletts mentioned that not all expiry dates are end of month

**Comment by roxy-dao** [comment]
Medicine packaging only has a MM/YYYY expiry on them... do we need day to be entered? 🤔

**Comment by richardmoizeau** [comment]
we can leave the date picker the way it is

day is last day of the month by default but can be manually change to another day by user (similar to what exists in mSupply Desktop)

**Comment by DhanyaHerath** [comment]
Date needed for expiry for vaccines generally

**Comment by mark-prins** [comment]
a significant number of items (estimated 20%) have expiry that isn't the end of the month. Also when anything has been reconstituted, unfrozen or opened etc.. the expiry is based on the day this is done.

we also need to display the day/month/year of the date wherever we display the expiry date.

**Comment by roxy-dao** [comment]
Closed in #4303

**Comment by marthakeezy** [comment]
Just tested on V2.1.0-RC6, and the date is enterable, is saved, and seems to be functioning. Build test passed ✅
