### ISSUE TITLE
Soft deletes for master list 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#1614]
## Is your feature request related to a problem? Please describe 👀
Transferred from #1584 
Currently, central server allows master lists to be deleted if the master list is not linked to any stores. i.e., If a user removes the master list from all stores, it could result in an error.

### Central Changes
- Master lists shouldn't be deleted from central as program uses master list as a FK, and it will cause errors if a master list with a program is deleted
- Have a `is_active` boolean to toggle if the master list is active or not instead of deleting (central can use this to hide master lists for places that require master list deletions)
### Remote Changes
- Add is_active field to master list and filter by this field wherever applicable
- Add is_active field to program table

### Additional context 💌
- Needs issue in mSupply as well

**Comment by DhanyaHerath** [comment]
Blocker: Waiting for mSupply side to come first

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe
- Unlinked the master-list to current oms-store and deleted it in Central Server and synced
- Back in oms, the master-list doesn't show anymore which looks correct to me - PASS!
