### ISSUE TITLE
Disable actions if invoice/requisition is uneditable 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#1633]
## What went wrong? 😲
![Screenshot 2023-04-28 at 12 18 40 PM](https://user-images.githubusercontent.com/61820074/235017631-c5450710-8799-4b6a-a5dd-1139a3198e04.png)

## Expected behaviour 🤔
Note: This is behaviour is blocked in backend. 
Disable actions if invoice/requisition is uneditable (see stocktake for example), maybe also disable the checkboxes too? 

## How to Reproduce 🔨
- Make invoice/requisition uneditable by changing status
- See that you can still select `Delete lines` in actions

**Comment by marthakeezy** [comment]
Tested in `V2.3.0-RC1`

Checked a requisition that's been finalised, the action is disabled -> build test passed, moving to Done

![Image](https://github.com/user-attachments/assets/aeaf7877-becd-4c77-92ad-a90c45c56d46)
