### ISSUE TITLE
suppliers/customer list: add the "house" icon to the names using mSupply

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#1641]
## Describe the solution you'd like 🎁

Distribution > Customers > Customers list view
Replenishment > Suppliers > Suppliers list view 

<img width="1428" alt="Screen Shot 2023-04-30 at 3 01 42 PM" src="https://user-images.githubusercontent.com/74992958/235333442-922e6123-9fd3-4788-abb7-11c9a6f253ae.png">

Similar to when creating a new shipment: 

<img width="585" alt="Screen Shot 2023-04-30 at 3 01 55 PM" src="https://user-images.githubusercontent.com/74992958/235333452-bfc2963d-bd27-43b6-bff3-a1c34ece4de9.png">

### Moneyworks Jobcode 🧰

???

**Comment by santoshkhanal12** [comment]
Tested on` v1.6.00`

# 🧪 How has/should this change been tested? 
- [x] Go to Supplier or Customer list
- [x] See icon added to stores that use mSupply
![Screenshot 2024-01-22 at 12 50 05](https://github.com/msupply-foundation/open-msupply/assets/117138852/54659d8f-f9d4-49b0-ae79-581d79b9cd8f)
![Screenshot 2024-01-22 at 12 50 30](https://github.com/msupply-foundation/open-msupply/assets/117138852/d6c70245-a11c-446f-8f37-82852c79d5d5)

**Comment by richardmoizeau** [comment]
Hi Santosh, would be good to see how it looks like in a list where you have store and customers.

**Comment by santoshkhanal12** [comment]
> Hi Santosh, would be good to see how it looks like in a list where you have store and customers.

@richardmoizeau In case of stores and customer it will show like:
![Screenshot 2024-01-22 at 13 56 13](https://github.com/msupply-foundation/open-msupply/assets/117138852/993ab8cb-1a1b-4972-97a8-33dcdfa38207)
For mSupply Customers/Suppliers: No Home icon
For mSupply Stores: Home Icon
