### ISSUE TITLE
Dashboard text wrapping

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#1684]
## What went wrong? 😲
 
If your screen is a little small, or you run the desktop version, you might see this:

<img width="1047" alt="Screenshot 2023-05-03 at 4 56 35 PM" src="https://user-images.githubusercontent.com/9192912/236338019-b5d49785-341a-4345-8bc0-09839199a110.png">

## Expected behaviour 🤔
The dashboard should look pretty.

## Your environment 🌱
 - Version: 1.1.11
 - Platform: all

**Comment by AnushaUp** [comment]
It looks like this in the latest version `v1.6.00-rc2`
![Screenshot 2024-01-18 at 1 43 25 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/9dd0bd0f-1970-4226-985e-138181eec5eb)
