### ISSUE TITLE
The internal order Hide items over the minimum toggle button hides also lines that equals the minimum

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#1710]
## What went wrong? 😲
 
I am not sure if this is true for all lines that strictly have stock equal to the minimum MOS but it certainly hides those that have 0 stock and a CMM of 0 which technically, I think, should be the minimum.

![hide items over minimum](https://user-images.githubusercontent.com/11624516/236713457-e9999056-83e4-4f06-ad66-e3b054fdc0fc.gif)

## Expected behaviour 🤔
I feel these should be shown because they are technically not over the the minimum. It is  debatable though. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order using a master list/program
2. You will probably have a couple of lines of 0 stock which have also a CMM of 0 
3. Toggle the button to "Hide the lines over the minimum"

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [windows desktop]

**Comment by AnushaUp** [comment]
# 🧪 How has/should this change been tested? 
Tested in omSupply `V2.0.00` and mSupply `V7.15.00dev7`
- [ ] Have some items that have 0 stock and 0 average monthly consumption or create some
- [ ] Create an `Internal Order`
- [ ] Use the `Hide stock over minimum` button
- [ ] Items should show
