### ISSUE TITLE
Filter "View stock" list by Master List & Location

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#1727]
at the moment, you can only filter by item code or item name

<img width="1496" alt="Screenshot 2023-05-09 at 8 15 52 PM" src="https://user-images.githubusercontent.com/74992958/237036683-03d68df1-428f-4b33-8ce0-61ac8622e673.png">

**Comment by mark-prins** [comment]
a simpler alternative is to enable sorting on the location column.
for the location filter we may need to implement the UI design for filter that Manu created, which would make this a more complex issue to resolve than it would appear

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe

- [x] Go to Stock
- [ ] Test filters
Expiry filter seems fine to me.
Problem with location filter: #3040
