### ISSUE TITLE
[User Training Feedback] when adding item (multiple transaction), sometimes code and name overlap

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#1764]
## What went wrong? 😲
 

<img width="1017" alt="Screenshot 2023-05-14 at 7 49 59 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/d2a92bb2-37b7-47ff-bc70-7c41d8980692">

<img width="989" alt="Screenshot 2023-05-14 at 7 52 29 PM" src="https://github.com/openmsupply/open-msupply/assets/74992958/ed333019-331b-4943-aceb-362d2dc0e572">

## Expected behaviour 🤔

should not overlap 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

item code: A3MINICLEAN01 

## Your environment 🌱

 - Version: 1.1.12
 - Platform:
   - [ ] browser (chrome, Explorer)
   - [ ] desktop (macOS)

**Comment by DhanyaHerath** [comment]
Hey @fergie-nz! If you're working on this, I've changed the milestone to be a 1.5 patch so that we can get it to South Sudan if possible. Would you be able to change your branch to be based off `main` to match please?

**Comment by nisha-dangol** [comment]
- Tested in v1.6.2 exe
Moving to Done, as it looks good
<img width="975" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/fc3838fc-6cab-4f15-9c67-b722c7183425">
