### ISSUE TITLE
Error message for users who are blocked - after 3 failed attempts to login

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#1770]
## When users try to login 3 times with the wrong password they are blocked and cannot login.

Currently omSupply doesn't create an error message saying "account is blocked". 
It keeps returning "wrong username or login". 

## Describe the solution you'd like 🎁

On mSupply mobile there's already an error message - we can replicate that:

![Screenshot_20230515_121934_mSupply Mobile](https://github.com/openmsupply/open-msupply/assets/132425096/c7bf2615-d0a8-402f-9e07-5aa9f6ba7036)

### Describe alternatives you've considered 💭

Any error message mentioning "user blocked" should be enough for users to know the login attempt failed and they cannot login until lockout period expires.

### Additional context 💌

We suspect users in Timor keep being locked out but they wouldn't know as there's no message displayed at the moment.
This change should improve UX.

### Moneyworks Jobcode 🧰

TBC

**Comment by roxy-dao** [comment]
central doesn't seem to return a specific error message for this, so hard to differentiate between failing to authenticate and being locked on... might need central change 🤔

**Comment by Chris-Petty** [comment]
Mobile uses `sync/v3/user` for user authentication. That API returns this extra message. Unfortunately `api/v4/login` does not, it only returns `Failed to authenticate`. Providing different messages would be a mSupply desktop request. If someone is going in there I'll push again for a couple more requests:

- Only lock the user out for 1 or 2 minutes. 60 minutes is ridiculous. Someone can fight me over it.
- The message should include how much time is left.
- Add a code "user_login_timeout"
- Include number of seconds under `timeoutRemaining`

JS example:
```jsx
const error = {
  error: `User timed out due to too many bad login in attempts. Time out remaining: ${timeoutRemaining}s`,
  error_code: "user_log_timeout",
  timeoutRemaining: timeoutRemaining
}
```

That is only if adding the extra fields doesn't break omSupply, dashboard, and remote authorisation app logins. If so maybe an optional header adding versioning to `api/v4/login`.

**Comment by andreievg** [comment]
Thank you for the detailed explanation @regotaina (mSuppy mobile example is also very helpful).

@Chris-Petty although I agree that the changes you've suggested are good, but I would go with the `must have` change here (letting use know that it's a timeout issue). I think mSupply issue should suggest doing the other changes only if they are trivial.  

> That is only if adding the extra properties doesn't break omSupply, dashboard, and remote authorisation app logins. If so maybe an optional header adding versioning to api/v4/login.

I think adding fields should always be safe, I would keep 'Failed to authenticate' in error field, and add code, message, and data, for a little bit more consistency with other api. Data to have have timeoutRemaining

**Comment by clemens-msupply** [comment]
> * Include number of seconds under `timeoutRemaining`.

or better the unix timestamp of when the user gets unblocked? e.g. `timeoutExpiry`

**Comment by Chris-Petty** [comment]
> > * Include number of seconds under `timeoutRemaining`.
> 
> or better the unix timestamp of when the user gets unblocked? e.g. `timeoutExpiry`

Wouldn't that be susceptible to timezone differences messing up it up? I see the server stating precisely how long it's going to timeout the client as eliminating any chance misinterpretation between the the machines.

**Comment by clemens-msupply** [comment]
> Wouldn't that be susceptible to timezone differences messing up it up? Hmm on second thoughts no, but still computer clocks actually being right haha. I see the server stating precisely how long it's going to timeout the client as eliminating any chance misinterpretation between the the machines.

One issue is the timeoutRemaining doesn't take into account how long the request took. However, don't think this is a real problem and as you said if the clocks are different you would have similar problems when using timeoutExpiry.

Using `timeoutRemaining` the UI would have to calculate `timeoutExpiry` itself just when getting the response. Found it nicer if `timeoutExpiry` would come straight from the server. But giving it another thought I don't have any really reasons against or for it , so just a matter of taste.

**Comment by AnushaUp** [comment]
Tested in `omSupply V1.7` with `mSupply V12`
