### ISSUE TITLE
Sync timout while importing data

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#1786]
When new records are created during the sync, the sync UI times out:

![Image](https://user-images.githubusercontent.com/88299195/238494569-197610f4-0b2b-4303-ae21-df9ea8cde62e.png)

Sync is working though, so maybe just a better error/info message...

This can be observed while importing data, e.g. programs data, and watching the sync progress in the UI.

**Comment by andreievg** [comment]
So this error is not critical, basically we wait for central server to integrate records that were pushed. And there is some arbitrary timeout for that, if it's reached then we just show that error, nothing bad actually happened. Not sure what the actual error should be, or if we should extend the push timeout to quite a longer period ? I think the later might be the way to go

**Comment by clemens-msupply** [comment]
> So this error is not critical, basically we wait for central server to integrate records that were pushed. And there is some arbitrary timeout for that, if it's reached then we just show that error, nothing bad actually happened. Not sure what the actual error should be, or if we should extend the push timeout to quite a longer period ? I think the later might be the way to go

Or maybe just ignore this specific error and keep checking for updates...
