### ISSUE TITLE
Patient biometrics

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#1815]
Feature request:

Identify patient using biometric information such as fingerprint or face recognition.

This would require to associate a patient with a number of identifiers. (This can also be useful if there are more patient ids than we currently support)

**Comment by DhanyaHerath** [comment]
Out of scope for now

**Comment by DhanyaHerath** [comment]
This is just very out of scope I think, let's close for now?

**Comment by clemens-msupply** [comment]
Yes agree, it recently poped up again though. Having a way to attach some 3rd party biometric information to a patient should relatively easy though. With patient merge, it should also be quite easy to then find and merge duplicates :)
