### ISSUE TITLE
[Deployment Feedback] View Stock - sorting per dates seem to sort months only

### ISSUE THREAD

**Issue by Pauline-mSupply** [msupply-foundation/open-msupply#1820]
## What went wrong? 😲

In **View stock**, a user wanted to find expired stock (oldest expiry dates in stock) in this case 03/2023. 
They sorted the column Expiry date BUT the stocklines expiring in 03/2023 were at row 10 or 11 in the list. At row 1 was a stockline expiring in 01/2024. 
So it seems that sorting the column only sorts months but doesn't take in consideration years. I could not check but this issue may be present in other areas where sorting per dates is enabled. It is confusing because a user will trust the sorting process and not double check that the 1st line is actually the oldest expiry date. 

## Expected behaviour 🤔

When sorting expiry dates column per date, the oldest date should appear first in the list.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add different stocklines with various expiry dates including expired dates in a stocktake
2. Click on View stock
3. Sort the column expiry dates per dates

## Your environment 🌱

 - Version: Open mSupply v1.1.13 (version before May 22nd)
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [X] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)
 
@richardmoizeau

**Comment by roxy-dao** [comment]
You can sort the dates by descending or ascending order... Can you try pressing the expiry sort again to see if the order is closest to farthest?

**Comment by Pauline-mSupply** [comment]
Nice try @roxy-dao but we did that and It's neither. It's all mixed up the only thing that seems to be sorting are months because they are in ascending order such as : 
01/2025
02/2025
03/2023
03/2024
04/2024
etc

I could take a screenshot tomorrow if it helps

**Comment by Pauline-mSupply** [comment]
@roxy-dao : I had another look today and actually, I didn't give you the full information. When a user chooses to create a stocktake from a masterlist OR from "items with stock", the list appears in blue. It is when the list is still blue that sorting per date doesn't work.

**Comment by mark-prins** [comment]
to clarify: the issue states that the 'View stock' list is not sorting correctly; the problem is with the detail view of a stocktake. The `view stock` menu item is working fine.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Have items with an various expiry dates (note: make some have the same month but different year)
- [x] Go into any of the above sections and try to sort by expiry date.
- [x] Dates should sort correctly now
