### ISSUE TITLE
JSON Forms -- additional components

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#183]
Just thought we should start making a list of UI elements we might need to create custom versions of for JSON forms. Once we're confident we have all cases covered, we can remove the "materialRenderers" from `useJsonForms` as they're currently there as a fallback.

Don't think these are a high priority, but it'd be good to have a reference list when we need it.

So far I've thought of:
- Number input
- Text Area
- Vertical Layout / Horizontal Layout -- the defaults are fine, but I don't really like the way they don't center elements within the grid, and I'm sure there's other layout improvements we could make. Will have more ideas once we have a better implementation overall

**Comment by clemens-msupply** [comment]
@CarlosNZ I think this can be closed?
