### ISSUE TITLE
Confirmation for logout button

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#1834]
Currently, it's too easy to accidentally press the logout button and to get logged out. For example, on Mobile the logout button is right next to your thumb (depending on how you hold the tablet).

Suggested solution: have a confirmation step for the logout.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 apk

### Tests
- [x] Login
- [x] Click logout
- [x] See confirmation modal
- [x] Confirm will logout, cancel will do nothing

**Comment by nisha-dangol** [comment]
The [back button (from home/dashboard) page](https://github.com/msupply-foundation/open-msupply/issues/2611#issuecomment-1980643437) breaks it in v1.7.0-rc1. Wanna address it? @fergie-nz ?
