### ISSUE TITLE
Quantity field does not get deleted completely with normal keyboard backspace in mobile tablet

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#1870]
## What went wrong? 😲
Quantity field does not delete the last letter value. Be it in shipment or requisition window, the value can be fully updated when selected, otherwise deleting (using backspace in mobile keyboard) does not really delete the value till the last letter.

## Expected behaviour 🤔
Backspace should work normally; it should delete whole values (not retain the last letter as well)

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to any transaction window like shipment or requisition
2. Choose any item line
3. At first, the value is highlighted/selected; so it can be changed
4. Hit backspace in mobile keyboard and see the error: it won't delete it all!

## Your environment 🌱
 - Version: v1.1.13 apk
 - Platform:
   - [x] android (tablet)
  
## Screenshots/Recordings
https://github.com/openmsupply/open-msupply/assets/59193490/742a6fac-0531-484c-be86-c365a1d06194

**Comment by raviSussol** [comment]
Checked on the v1.4.0. Seemed to be fixed.

**Comment by nisha-dangol** [comment]
> Checked on the v1.4.0. Seemed to be fixed.

Rechecked in v1.4.00 exe and apk. This doesn't look fixed in Inbound Shipment and Stocktakes lines.

https://github.com/openmsupply/open-msupply/assets/59193490/615e67af-db38-4081-9dc5-0feeeafc512b

**Comment by roxy-dao** [comment]
Closed as dup

**Comment by nisha-dangol** [comment]
will be tested in #2491
