### ISSUE TITLE
Report graphql queries and backwards compatibility

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2000]
A placeholder to record this conversation: https://github.com/openmsupply/open-msupply/pull/1979#discussion_r1261858646

An outcome of this issue would be a strategy to deal with potential changes to graphql api that may affect report. (for now we should not make any breaking changes to query API).

Back of an envelop solutions could include:

* API versioning in reports and outside of reports, with translators
* Some sort of test (a bit hard in sync system with different remote server versions)

### Suggested solution

Manifest file to include `min` omSupply version, allow multiple reports with the same name (can't put in just report json since report arguments can change), add `om_` field for version in mSupply. See epic for easy of deployment and testing

**Comment by andreievg** [comment]
There seems to be a break in standard report, as mentioned in telegram chat.

Looks like it happened because default query was changed, and if query is not specified, default query is used (and the template 

I see this as a very high impacts area (a lot of effort to fix and a lot of disruption to users workflow) with medium likely hood, so very high risk. 

Would propose we add tests for standard reports and add for consideration in triage

**Comment by andreievg** [comment]
I think this needs to be looked at by Ruru team during report work

**Comment by mark-prins** [comment]
Note that the breaking change was to the default graphQL queries, if we bundle gql with the report then we don't repeat that particular issue. there is potential to introduce a breaking change to the graphQL schema - that could well break other parts of the app too though.

**Comment by andreievg** [comment]
>  that could well break other parts of the app too though.

Our codegen would tell us, but yes there is a potential to break other parts of the `system` as a whole (integrations)

**Comment by roxy-dao** [comment]
Already done in epic #4800
