### ISSUE TITLE
omSupply Central Server Transition

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2062]
# Central Server Background

We use classic mSupply central server for 
* Configurations (store, items, master lists, etc..)
* Synchronisation (central sync hub for remote site, transfer of records between sites, backup, etc..)

When omSupply development started, we decided that it was much faster to use existing mSupply central server rather then implement new omSupply central server. This option offered other benefits, like being able to use mSupply and omSupply in the same system.

# Motivation

1. We are planning to replace mSupply central server with omSupply central server at some stage
2. New configuration UI needs to be added to mSupply for new omSupply only features (this would need to be done twice when omSupply is implemented), i.e. document/program configurations, multi pack units, asset module config.
3. New omSupply only supervisor (all store) mode features may need to be added to mSupply, i.e. global program/document reports, global asset and cold chain performance dashboard/reports ?

Although our existing strategy is to do `3` in Graphana dashboard, having these indicators directly in omSupply adds an option that may be more desirable in some use cases.

# Proposal

omSupply site can act as `central configuration` and `central data hub` for a subset of <ins>new record</ins> types. It would run in parallel with exiting mSupply remote server. omSupply remote sites would sync with both mSupply and then omSupply central server

Some research was done in [this trello card](https://trello.com/c/AJk8pLkh/26-omsupply-central-parallel) (the card and the issue will be updated with details)

<ins>new record</ins> types: It should be possible to transition to old records too, but this brings it's own challenges, for now focus of this issue is for new record types. 

# Examples

### Mutli Unit Configurations

Multi unit configuration UI can be added to omSupply central, and will sync to omSupply remote sites.

### All store mode <a href="#all-store-mode" id="all-store-mode"></a>

Any mSupply instance can access data for all stores via central omSupply API. When data for all stores needs to be accessed, it can be routed to central omSupply API rather then using current remote omSupply server. Non active store data can only be accessed when there is internet connection.

This option would require more consideration (i.e. front end consumable API of central server needs to be backwards compatible)

# Challenges

* All data needs to be present in omSupply central to make decisions about "shared" (patient related) record type routing (i.e. all name_store_joins). For new central data or new remote data this should not be a problem, since routing is pretty simple.

**Comment by lache-melvin** [comment]
Closed by #2818

**Comment by marthakeezy** [comment]
Tested by the whole team in V2.0.0 Release testing and is working fine 3 releases later, moving to Done ✅
