### ISSUE TITLE
Remote patient search UI tweaks

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2068]
When creating a new patient and the patient exist at a different site, the user can select to fetch the patient from the remote site. After the patient has been fetched this dialog is shown:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/833baffa-2d96-4aac-9f98-217021e81802)

After clicking ok the screen goes back to the list of patients. I find this confusing and accidentally created a new patient instead of selecting the patient that just has been fetched.

- [ ] After fetching a patient from a different site, go straight to the patient detail view.
- [ ] Revise wording to match new behaviour, e.g in the line of "retrieve and select patient":
![image](https://github.com/openmsupply/open-msupply/assets/88299195/03082874-94ea-48a8-b026-557ce7ac995d)
- [ ] After the patient has been fetched the patient list needs to be invalidated, e.g. it still shows the "remote" icon in the patient search list instead of the "home" icon (at least sometimes). Furthermore, the main patient list is not refreshed.

**Comment by clemens-msupply** [comment]
This should be fixed together with: https://github.com/msupply-foundation/open-msupply/issues/3412

**Comment by roxy-dao** [comment]
Fixed in #5000
