### ISSUE TITLE
Programs: Contact Tracing - Multiple Issues

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2103]
## General

- [x] `Contact Traces` is not correct and should be replaced by `Contact Tracing`
- [x] remove 'Contact Traces' from the Dispensary Sub-menu

## Adding a new contact

- [x] Once you click on "Add Contact" button, user can choose the program for which he wants to create a new contact
- [ ] ~we should not use the "Encounter" interface for this process since contact data are not related to a specific encounter. It is basically a list of contacts that can be updated at any time. My recommendation would be to go for a form (similar to the form used for adding a program)~

### Section 1: Family / Partner Information

- [x] Contact Age: 
- [x] Contact Gender: Male, Female, Transgender
- [x] Contact Phone
- [x] Contact Email address
- [x] Contact Known HIV+: Yes, No, Unknown
- [x] Contact ART Status: Yes, No, Not Applicable (Note: only if `Contact Known HIV+` = `Yes`)
- [x] Clinic Confirmed KP: Yes, No
- [x] Relationship: Spouse, Children, Parent, People who inject drugs
- [x] Disqualified from PNS: Yes, No
- [x] Index Referred Post-GBV: Yes, No, Not Done
- [x] Preferred PNS Approach: Contract, Dual, Provider, Client, Other (note: should be inactive if `Disqualified from PNS` = `Yes`)

### Section 2: `Tracking Outcome`

- [x] Partner Contacted: Yes or No
- [x] Partner Consented (for testing): Yes or No (Note: only if `Partner Contacted` = `Yes`)
- [x] Partner Tested: Yes or No (Note: only if `Partner Consented` = `Yes`)

### Section 3: `Testing Outcome` 

**This section should only be displayed if `Partner Tested:` = `Yes`**

- [x] Partner Serial No: 

the purpose of this field is to link the contact to an HIV Testing encounter. If we want to reproduce what is done in the HPDB, it should a drop down with all HIV Testing encounter and user is supposed to find the encounter where the contact has been tested. I expect this to be quite challenging from a development point of view (@clemens-msupply ?) As a possible alternative, we could have a free text field to enter the serial number of the HIV Testing Encounter

![Screenshot 2023-08-17 at 11 56 02 AM](https://github.com/openmsupply/open-msupply/assets/74992958/79829710-5346-4997-8ba5-9c8f35b192e2)

- [x] HIV Testing Date: if we can link the contact record to the hiv testing encounter, then this should be automatically populated with the date of the encounter. if not, then user can select a date manually
- [x] Partner Test Result: if we can link the contact record to the HIV testing encounter, then this should be automatically populated with the testing encounter values. If not, user can select a value manually from a drop down (Positive, Negative or Inconclusive)

### Section 4: `Link to Treatment`

**This section should only be displayed if `Partner Test Result` = `Positive`**

- [ ] Contact ART enrolled: Yes, No
- [x] Enrolment ID: HIV C&T Enrolment ID (ex: KAM0001)

### Section 5: `Post PNS IPV Screening`

- [x] Contact IPV post PNS: Yes, No

## View Contacts for a patient

Context: 
![Screenshot 2023-08-17 at 12 17 56 PM](https://github.com/openmsupply/open-msupply/assets/74992958/0c77c55f-2bf3-4df7-85ef-b455c4715122)

Table layout for the list of contacts: 

| Program | Created/Added on | First Name  | Last Name  | Age  | Gender  | Contacted ? | 
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
| HIV Care & Treatment | 18/02/2023 | | | 23 | Female | No |
| HIV Care & Treatment | 23/02/2023 | | | 46 | Male | Yes |
| HIV Care & Treatment | 23/02/2023 | | | 67 | Male | No |

Note: first name and last name are not captured for HIV program but they could be useful for other programs (eg. Tuberculosis)

**Comment by clemens-msupply** [comment]
> we should not use the "Encounter" interface for this process since contact data are not related to a specific encounter. It is basically a list of contacts that can be updated at any time. My recommendation would be to go for a form (similar to the form used for adding a program)

We would need to link a contact to an existing patient though, doing this in a modal might be a bit tricky, e.g. patient serach modal on top of modal? For this reason I when with detail page for each contact trace. That's what you mean, right? (contact traces are not linked to an encounter)

**Comment by richardmoizeau** [comment]
> > we should not use the "Encounter" interface for this process since contact data are not related to a specific encounter. It is basically a list of contacts that can be updated at any time. My recommendation would be to go for a form (similar to the form used for adding a program)
> 
> We would need to link a contact to an existing patient though, doing this in a modal might be a bit tricky, e.g. patient serach modal on top of modal? For this reason I when with detail page for each contact trace. That's what you mean, right? (contact traces are not linked to an encounter)

What I meant is that we don't want to use the "encounter" view/window to register a new contact, a single form would do the trick. I said a modal but I guess it could be something else. When you add a program to a patient (with a modal), the program is automatically linked to the patient, so I assume it would be the same if you add a contact to a patient. No need for a modal on top of modal: if I want to add one or several contacts to a patient I: 

1. look up the "index" patient
3. I can see existing contacts for the patients by clicking on the "Contact Tracing" tab
4. I click on "Add Contact" button. The "New Contact" modal opens. 
5. In the "New Contact" modal, I enter the details for the contact (see above specs) and click on Save when I'm done

**Comment by richardmoizeau** [comment]
Adding new requirements: since you may be adding multiple "contacts" at once, you should be able to click an "OK & Next" button to immediate record a new contact.

**Comment by clemens-msupply** [comment]
> Enrolment ID: HIV C&T Enrolment ID (ex: KAM0001)

We can use this:
https://github.com/openmsupply/open-msupply/issues/1840

However, I think we should link the patient them probably to the contact in the Contact Tracing UI and then just automatically display the enrolment id of the linked patient... But this might be for another issue.

**Comment by clemens-msupply** [comment]
@richardmoizeau regarding the `contacted ` column there is currently a "Contact Tracing" status which can have the value "Pending" OR "Done". However, this needs to be reworked... Was wondering if we put `contacted` into the status. Or remove the status all together?

For example, like: status could be "Pending" | "Contacted" | "LTFU"

**Comment by richardmoizeau** [comment]
> @richardmoizeau regarding the `contacted ` column there is currently a "Contact Tracing" status which can have the value "Pending" OR "Done". However, this needs to be reworked... Was wondering if we put `contacted` into the status. Or remove the status all together?
> 
> For example, like: status could be "Pending" | "Contacted" | "LTFU"

Let's keep it simple with: `Contacted` and `Not Contacted` based on the value entered in the field `Partner Contacted:` (Section 2: Tracking Outcome). Technicaly, column header should be: "Contacted ?" and `Yes` or `No` as value

**Comment by richardmoizeau** [comment]
> > Enrolment ID: HIV C&T Enrolment ID (ex: KAM0001)
> 
> We can use this: #1840
> 
> However, I think we should link the patient them probably to the contact in the Contact Tracing UI and then just automatically display the enrolment id of the linked patient... But this might be for another issue.

Since this field does not exist in the current HPDB, let's keep it as a manual entry

**Comment by richardmoizeau** [comment]
> Let's keep it simple with: `Contacted` and `Not Contacted` based on the value entered in the field `Partner Contacted:` (Section 2: Tracking Outcome). Technicaly, column header should be: "Contacted ?" and `Yes` or `No` as value

even more simple, let's remove the "Status" column from the contact view

**Comment by richardmoizeau** [comment]
> ### Section 1: Family / Partner Information

I forgot one field located in above section entitled `ICFPT Serial No` - user can manually enter the ICFPT Serial Number (from the paper register).

**Comment by richardmoizeau** [comment]
> * [ ]  Partner Serial No:

This is the same data as the `HTC Serial No.` field from the HIV Testing encounter form. 

This when the contact is coming to the clinic, do a test following the contact tracing test

**Comment by DhanyaHerath** [comment]
This looks like it's done now, can it be closed @clemens-msupply?
