### ISSUE TITLE
make the "Covid 19 Vaccination History" programme an encounter type of the HIV Care & Treatment programme

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2108]
Since recording C19 vaccination data is only meant for HIV patients, there is no need to have a separate program for Covid 19. In order not to have too many programs, we could add a new encounter type as part of the HIV Care & Treatment programme. 

- [x] Change section's logo to a vaccine logo ? Example: 

<img width="261" alt="Screenshot 2023-08-18 at 11 42 43 AM" src="https://github.com/openmsupply/open-msupply/assets/74992958/5001414e-9d3f-4bc9-b3d3-86f7b6d18016">

### Section 1: `COVID-19 Vaccination Services`

- [x] `Visit Date`: already captured in the encounter's headers
- [x] `Was client offered COVID-19 Vaccination ?`: check/tick box (true or false)
- [x] `Has client declined COVID-19 Vaccination ?`: check/tick box (true or false)
- [x] `If declined, reason given:`: free text

### Section 2: `COVID-19 Vaccination Event`

Note: this section should only be displayed if `Was client offered COVID-19 Vaccination ?` = `Yes`

- [x] `Vaccination Date`: date picker
- [x] `Manufacturer`: dropdown menu (Moderna, Pfizer, Astra-Zeneca, Sinovac, Johnson & Johnson, Other
- [x] `Comments`

## Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
@richardmoizeau do you know why visit date differs from vaccination date?

**Comment by richardmoizeau** [comment]
we should ask the local team but my guess is that you can come for a visit and not get vaccinated ? This way you need to record the visit date but not the vaccination date ? Apart from this, I assume visit date = vaccination date

**Comment by mark-prins** [comment]
@richardmoizeau we already have an `injection` icon. Is that ok to use rather than adding a new icon?

<img width="175" alt="image" src="https://github.com/openmsupply/open-msupply/assets/9192912/1de88465-c7ae-4829-bab2-75c6138b59d8">

**Comment by richardmoizeau** [comment]
> @richardmoizeau we already have an `injection` icon. Is that ok to use rather than adding a new icon?
> 
> <img alt="image" width="175" src="https://user-images.githubusercontent.com/9192912/262832655-1de88465-c7ae-4829-bab2-75c6138b59d8.png">

Sure I was not aware we had a "vaccine" icon already.

**Comment by richardmoizeau** [comment]
Missing the `Comments` section in the `Covid-19 Vaccination Event`: 

![Screenshot 2023-09-18 at 4 08 24 PM](https://github.com/openmsupply/open-msupply/assets/74992958/f485ecfb-6616-4f83-9817-23f529ffefb2)

I just wanted to test it and now I think we should just have 1 bubble what do you think @clemens-msupply ?

**Comment by DhanyaHerath** [comment]
Can this be closed now @clemens-msupply?
