### ISSUE TITLE
Breadcrumb refactor

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2118]
A breadcrumb can currently have some urlParts and a suffix. The urlParts are taken from the current browser location while the suffix can be set be a component to add another Breadcrumb or other component.  In some places this is currently used to add an additional breadcrumb + another "label" component, i.e. its not only one suffix.

Find way to make this a bit nicer, e.g.:
- have another `appendBreadcrumb` method
- OR accept multiple suffixes in a `setSuffixes` method

For more details please see the original discussion: https://github.com/openmsupply/open-msupply/pull/2085#discussion_r1295291575

**Comment by mark-prins** [comment]
Adding refinement after the raising of #4226. A refactor should resolve both issues.

**Comment by lache-melvin** [comment]
Closed by #4326

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.1.0-rc6`


- [ ] Go to programs > immunisation program > [detail] > [vaccine course detail]
- [x] Both the program and vaccine course names are in the breadcrumb
- [ ] Go to coldchain > equipment > [detail view] and refresh the page
- [x] Breadcrumb shows asset name, not ID
- [ ] Go to view stock > [detail view]
- [ ] Click on log tab, then back to detail tab
- [x] Breadcrumb still shows item name, not ID
- [x] General click around of pages, breadcrumb looks right 😅
