### ISSUE TITLE
When the stock-line details are changed, they should be updated in trans lines as well?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2161]
## What went wrong? 😲
 
When the stock-line details are changed, they should be updated in trans lines as well?

## Expected behaviour 🤔
When the stock-line details are changed, they should be updated in trans lines as well?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a stock line. Remember the batch details, let's say its expiry_date is 02/2024 (yet to expire)
2. Now add it in a outbound shipment, don't ship it yet
3. Now go back to View stock window and edit the batch details, let's say change the expiry_date to 02/2020 (expired)
4. Now go back to that outbound shipment
5. See error: the same previous batch details are showing; which doesn't even exist actually
6. Ship/Finalise it and sync
7. Check in the receiving store
8. You'll see the 02/2024 batch is received not the updated expired (02/2020) ones. Is this even expected at all?

## Your environment 🌱

 - Version: v1.3.00 exe
 - Platform:
   - browser (extra points if you tell us which one)
   - server (windows)

**Comment by roxy-dao** [comment]
Close in favour of #3703
