### ISSUE TITLE
Central server timeout reached when syncing multiple oms sites with large data

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2196]
## What went wrong? 😲
When tried to sync multiple instances of oms (mobile and desktop) with thousands of lines in stocktakes in each, it almost causes the server to slow down resulting in very slow sync in oms-sites as well.

## Expected behaviour 🤔
Since such thousands of lines in stocktakes may not be implemented in realtime, IDK the expected behavior here, but I definitely don't expect my system to crash because of slowness. The main question here could be 'Do we wanna address this slowness issue?'

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get multiple instances of oms running
2. In my test, I created an stocktake entry with thousands of lines.
3. See first error: how long it takes to proceed that request. Try deleting/editing lines, you'll see the system almost hang. See recordings:[ Recording1](https://recordit.co/u6kPypEH6h) [Recording2](https://recordit.co/vB0N9XHmll)
4. Make sure both desktop and mobile oms is syncing at the same time.

5. See the timeout message in browser:
<img width="1024" alt="server-timeout-msg" src="https://github.com/openmsupply/open-msupply/assets/59193490/b7d118bb-a26c-4fd1-a138-fa6a7e0fe7e8">
6. See another slowness error in mobile:  
 

https://github.com/openmsupply/open-msupply/assets/59193490/c234f2b3-230c-46b9-a42d-a202e8604e61

7. In mobile recording, it looks way more slow. **Is this even ideal, more than 10 mins to sync?**

## Your environment 🌱

 - Version: v1.3.00
 - Platform:
   - android (tablet): Galaxy Tab A(2016); Android: 8.1.0
   - browser (Google Chrome)
   - server (windows)

**Comment by clemens-msupply** [comment]
Possibly dublicate of https://github.com/openmsupply/open-msupply/issues/1786

**Comment by roxy-dao** [comment]
Is this still an issue with 1786 fix?

**Comment by clemens-msupply** [comment]
It was still an issue for me:
https://github.com/msupply-foundation/open-msupply/pull/2860#issuecomment-1918128649

but the way I reproduced it might be an edge case...

**Comment by andreievg** [comment]
Sounds like a central server issue, we can't really do that much about it, lets see if this persists and re-appears, closing for now.
