### ISSUE TITLE
Use descriptive app-name http header in sync

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2197]
## Is your feature request related to a problem? Please describe 👀

https://github.com/openmsupply/open-msupply/blob/e975f02a0bff30d58b7a8fdc295b469618472eeb/server/service/src/sync/api/core.rs#L34-L38

Here Open mSupply just sends an app-name "remote_server". On the mSupply Central Server, this would show as "remote_server" as the app name when viewing sites:
![image](https://github.com/openmsupply/open-msupply/assets/7684221/59dabe75-14f1-4f73-bc93-24a800096f85)
(Pretend "Desktop" says "remote_server". Yes other things are vaguely reporting themselves too 😉). 

Also looks better in dashboard widgets describing sites.

## Describe the solution you'd like 🎁

- If it's Open mSupply running on a PC, regardless of OS, report "Open mSupply Desktop".
- If it's Open mSupply running on a tablet, regardless of OS, report "Open mSupply Mobile".
- I assume we can do something static at build time for the different platforms?

### Describe alternatives you've considered 💭

-  Reporting OS as well. Dunno if that helps, or if it should be in the same header as app-name. I believe there are probably more official headers that should be used, such as browsers using `USER-AGENT`: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0`. API would have to change for this anyway, so meh!
- Trying to capture something about the running context... is it a remote server on android with 5 client devices? Seems like probably over cooking it though.

### Additional context 💌

Will be good for support database.

### Moneyworks Jobcode 🧰

?

**Comment by nisha-dangol** [comment]
Have already seen this in 1.6 - PASS!
- [x] Initialise on PC
- [x] See Open mSupply Desktop in central -> synchronisation
- [x] Initialise on Android
- [x] See Open mSupply Mobile
