### ISSUE TITLE
Report: from submenu to Home Menu ?

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2256]
## Is your feature request related to a problem? Please describe 👀

a submenu `Report` has been solely implemented in the main menu `Dispensary` for the HIV/TB module work. 

![Screenshot 2023-09-20 at 10 09 12 AM](https://github.com/openmsupply/open-msupply/assets/74992958/95ddf905-67f4-4d89-a12c-f2ae29d716b7)

However, system will eventually enable reports for all functional areas (Distribution, Replenishment, Cold Chain, Inventory Management) so not sure we want to add a "Report" submenu for each main menus ?

## Describe the solution you'd like 🎁

Reports should be its own main menu (or home menu)

### Describe alternatives you've considered 💭

Have one submenu "Reports" 

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by DhanyaHerath** [comment]
Triage: let's do this as part of a full reports refresh

**Comment by andreievg** [comment]
Closing this issue, in https://github.com/msupply-foundation/open-msupply/issues/3880, there is a task `Dispensary/Program reports to be displayed in the main report list`
