### ISSUE TITLE
Add Location filter 

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2274]
## Is your feature request related to a problem? Please describe 👀

Need to have a "Search Location" filter as warehouses can have lots of locations and if you want to do editing or find a particular location etc it is difficult without the search bar.

![Screenshot 2023-09-25 at 11 16 31 AM](https://github.com/openmsupply/open-msupply/assets/143057869/956eabaf-1e75-4430-a50b-f662598a923d)

mSupply has a search location filter
![Screenshot 2023-09-25 at 11 21 16 AM](https://github.com/openmsupply/open-msupply/assets/143057869/89ede491-1793-43ee-b83b-979f05c0b490)

## Describe the solution you'd like 🎁

Location filter

### Describe alternatives you've considered 💭

No

**Comment by DhanyaHerath** [comment]
**Triage:** Yes, agreed - and we should update other areas when the searching functionality design is finalised for coldchain

**Comment by santoshkhanal12** [comment]
Tested on `v1.6.00`

# 🧪 How has/should this change been tested? 
- [x] Go to `Location`
- [x] Test filters

@roxy-dao @mark-prins I have found a bug on filters. The filter doesn't retains all the filter when the backspace key is pressed

 https://github.com/msupply-foundation/open-msupply/issues/2822

**Comment by roxy-dao** [comment]
> #2822

That would be a new feature (: 

We haven't implemented retaining of filters yet...
