### ISSUE TITLE
Stocktake report not sorting correctly

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2276]
## What went wrong? 😲
Stocktake report has no sorting level? Generated report list is random?(unsure but unable to see any pattern in the report like alphabetically or numerically etc)
![Screenshot 2023-09-25 at 1 07 07 PM](https://github.com/openmsupply/open-msupply/assets/143057869/4e223510-4d5e-4b5d-a56f-93e65dd73137)

## Expected behaviour 🤔
For report to generate based on how the list in omsupply is arranged (if possible)

https://github.com/openmsupply/open-msupply/assets/143057869/52bbb2ce-3e5b-4105-93b7-cfb3ab1492ef

Otherwise, if the report can be sorted by location (1st), then item name alphabetically (2nd) as this makes stocktaking easier to perform. 
(Note would also need the same to be on omSupply - will make a seperate request about Location column in the stocktake list)

## How to Reproduce 🔨
No

Steps to reproduce the behaviour:

## Your environment 🌱
v 1.3 Desktop

**Comment by andreievg** [comment]
I don't think we can sort by both location and then by item yet (actually it's not in mSupply), but yeah agree that printer report should reflect the sort on the page

**Comment by louisaw123** [comment]
> I don't think we can sort by both location and then by item yet (actually it's not in mSupply), but yeah agree that printer report should reflect the sort on the page


Thankyou, hmm yes one of the genius here has cracked the code to putting both sorting levels on msupply so it can do location then item next... and it can also let you customise to choose whatever you want sorted at each level for however many column headers you want :)

<img width="909" alt="Screenshot 2023-10-17 at 8 51 21 PM" src="https://github.com/openmsupply/open-msupply/assets/143057869/88352046-ab34-4459-8bbb-9078b7671dfb">

**Comment by andreievg** [comment]
Ohh, that's great, I didn't realise this can be done.

There is a PR already for this issue, but I think it's just for reflecting sort on page to sort when printing, I think we may need to break this into two issues, once that PR is merged.
