### ISSUE TITLE
Configuration option for database path

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2290]
## Is your feature request related to a problem? Please describe 👀

The request was made to be able to specify the path of the sqlite database, if sqlite is being used.

In mSupply currently, a common configuration is to have the datafile on a separate drive, to allow separation from the program files, enable simpler backup configuration and to have the data stored on a drive separate to the OS, which in theory allows for faster access.

## Describe the solution you'd like 🎁
Add an optional configuration setting to the `yaml` files, so specify the path of the database. This will be ignored if postgreSQL is being used.

If set, the SQLite file is loaded from the path, if not the current setting is used: which is the path of the executing binary.

Perhaps you'd like to do #817 at the same time?

**Comment by CarlosNZ** [comment]
Just wondering if we should just incorporate a path into the existing "database_name" field?

So instead of `database_name: "omsupply-database"`, you could put `database_name: "/my-volume/path/to/db/omsupply-database"` to specify a path.

**Comment by mark-prins** [comment]
that would only work for sqlite - we need an actual db name for postgres.
Given that the settings are the same for all db back ends, we need a db name and a path

**Comment by CarlosNZ** [comment]
Okay, based on this discussion and #817, suggested solution is to mostly leave it how it is (config-wise), except:

- add a new (optional) field called `database_location` (with path to db directory, only valid for sqlite)
- auto-append `.sqlite` to filename if we're using SQLite AND if the `database_name` doesn't already have `.sqlite` in it

Sound okay?

**Comment by mark-prins** [comment]
Sounds great thanks! - though I would prefer `database_path` over `_location` because path is what rust is using for file paths, and it sounds more like a folder / directory to me.

**Comment by CarlosNZ** [comment]
> though I would prefer `database_path` over `_location` because path is what rust is using for file paths, and it sounds more like a folder / directory to me.

To me "path" implies a path to a specific file, whereas "location" suggests "the place where the file is". 🤷‍♂️


FWIW, I probably wont' get to this for another couple of days, so if anyone else want to grab it in the meantime, feel free.
