### ISSUE TITLE
[Multi Unit Item] Add configuration UI

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2309]
Epic: #2078 

Add configuration UI for central server configuration of multi unit items.

Add, edit and deactivate unit variant for an item

**Comment by andreievg** [comment]
As per discussion in the standup on Tuesday, a new tab in catalog->item should work.

![Screenshot 2023-11-15 at 4 47 00 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/812c6da5-7e27-4662-9185-f86eb02d00ed)

In this new tab we would have a table and add button. Clicking on a row and add button would allow you to edit/add new variant.

Columns:

Short name, Long name, Pack size.

Pack size should be unique for item (can't have the same pack size with different variants).

Should invalidate pack variant cache after edits (so it's refetched for other areas in UI).

Editing should be restricted to (both in front end and graphql permissions):
![Screenshot 2023-11-15 at 4 56 29 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/b8b6152b-9469-42a0-8423-6f382b70788d)

This would have a follow up issue, to be created:

* Restrict editing of pack variants for omSupply central server only (would still be visible though), this is to be done in service and graphql permissions
* Soft deleting

**Comment by marthakeezy** [comment]
Tested as a part of Epic in V2.0.0 release, moving to Done ✅
