### ISSUE TITLE
[Multi Unit Item] Store user selection in App data

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2313]
Epic: #2078 

- [x] Currently user selected variant is only stored in page state, it should be stored in app data for user/store.
- [x] Should also place 'useInitUnitStore' in the right place (see comment in `useInitUnitStore`).
- ~Also relocate to common: https://github.com/openmsupply/open-msupply/pull/2209#discussion_r1325325370~
- [ ] Make sure that default pack size functionality still work in internal orders, as per https://github.com/openmsupply/open-msupply/pull/2273#discussion_r1345595587

SQL to init some units:
```sql
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-one', 'E43D125F51DE4355AE1233DA449ED08A', 'tab', 'tablet', 1);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-ten', 'E43D125F51DE4355AE1233DA449ED08A', 'blist of 10 tabs', 'blister of 10 tablets', 10);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-50', 'E43D125F51DE4355AE1233DA449ED08A', 'box of 5 blist', 'box of 5 blist', 50);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('ace-one', '179D364578D343C8BC45930C16A1D61C', 'tab', 'tablet', 1);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('ace-ten', '179D364578D343C8BC45930C16A1D61C', 'blist of 10 tab', 'blister of 10 tablets', 10);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('ace-twenty', '179D364578D343C8BC45930C16A1D61C', 'blist of 20 tab', 'blist of 20 tab', 20);
```

**Comment by clemens-msupply** [comment]
> Also relocate to common: https://github.com/openmsupply/open-msupply/pull/2209#discussion_r1325325370

Does this refer to `getPackUnitEntryCell`? this is fine in system isn't it? @mark-prins

**Comment by mark-prins** [comment]
> Does this refer to `getPackUnitEntryCell`? 

Yes - the component itself

> this is fine in system isn't it? @mark-prins

It was my expectation that this cell would be used by a number of packages, and if that's true, then I'd move to `common`, as per the other custom cell types.

**Comment by clemens-msupply** [comment]
As I understood it `common` would only contain functionality that is not omSupply specific and `system` contains other common components used for other omSupply packages.

For example, `initialisationStatus` or auth api should actually be in `system` because these APIs are omSupply specific and would not be usable in the `notify` or `hsh` frontend.

`getPackUnitEntryCell` has some references to mSupply items and other omSupply specific things. We could refactor a generic Unit component that could be used outside of omSupply but don't think this is what we want to do?

**Comment by clemens-msupply** [comment]
@mark-prins and @andreievg: for the "Relocate to common" point, I think it good to keep it in `system`? Also see previous comment.

**Comment by marthakeezy** [comment]
Tested as a part of Epic in V2.0.0 release, moving to Done ✅
