### ISSUE TITLE
add "Relationship" column to help with contact identification (when not yet linked to a registered patient)

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2329]
## Describe the solution you'd like 🎁

Add a "Relationship" Column to the patient's contact list: 

![Screenshot 2023-10-03 at 12 41 58 PM](https://github.com/openmsupply/open-msupply/assets/74992958/0a998fe8-cd19-4624-9c8c-5a9615584657)

### Additional context 💌

![Screenshot 2023-10-03 at 12 43 46 PM](https://github.com/openmsupply/open-msupply/assets/74992958/4f2945bf-cc83-45db-8edb-cbabc9ad602d)

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
TODOs:
- [ ] Add a standard `relationship: string` field to the main contact_trace schema (schema repo)
- [ ] For the index testing schema move the relation field out of the extension (overiding the default `relationship: string`
- [ ] Repository: Add relation ship column to contact_trace table
- [ ] Graphql: expose new column

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Add a contact to patient
- [x] Edit relationship
- [x] Go back to patient view -> contact tracing
- [x] See update 
I'm seeing short forms for the relationship added, instead of the full detail there. Is this expected? @roxy-dao 
<img width="1116" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/1dce3643-ab63-4e49-944e-b07a779eb868">

**Comment by roxy-dao** [comment]
> Tested in v1.6.2 exe
> 
> * [x]  Add a contact to patient
> * [x]  Edit relationship
> * [x]  Go back to patient view -> contact tracing
> * [x]  See update
>   I'm seeing short forms for the relationship added, instead of the full detail there, which looks like expected from [Let Autocomplete use the same show option as the Select component #2437](https://github.com/msupply-foundation/open-msupply/pull/2437)
> 
> <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/59193490/306907420-1dce3643-ab63-4e49-944e-b07a779eb868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2Mjg4MjksIm5iZiI6MTcwODYyODUyOSwicGF0aCI6Ii81OTE5MzQ5MC8zMDY5MDc0MjAtMWRjZTM2NDMtYWI2My00ZTQ5LTk0NGUtYjA3YTc3OWViODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE5MDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDI2OWMwNmExZTA0MTdhYjNlOTM0NjQyNThiZWUzOTI3MjlhZGFjZGE2NDUxODliZjBhMWZiYWY0ZGM4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXqELJ2NHlKjW93OwDnBFt1B7lq_BfkGKctxYlgJAVM">

Yes, it's supposed to show the short form for the relationship (:
