### ISSUE TITLE
Implement filters

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2355]
## Is your feature request related to a problem? Please describe 👀

When the new filter functionality is available ( see #2282 ), implement the filters for the areas which have multiple filter options available, or should have multiple filter options available:

- [ ] #2269 
- [x] #2274 
- [x] #1344 
- [x] #2213
- [x] #1727

### Moneyworks Jobcode 🧰

`PG23OMD` ?

**Comment by roxy-dao** [comment]
Blocked until cold chain feature branch is merged to develop

**Comment by roxy-dao** [comment]
Only one issue left. Will close this and bring the issue into the sprint.

**Comment by santoshkhanal12** [comment]
@mark-prins @roxy-dao While pressing 's' in filters, it opens up the View stocks window: https://github.com/msupply-foundation/open-msupply/issues/2788

**Comment by nisha-dangol** [comment]
Moving to Done, as part of [v1.6 Release Test](https://docs.google.com/spreadsheets/d/1MGW4v2BoaYLToUKTTglBrsrkBBQl-d079rtEeDhqXsk/edit#gid=915349711).

Bugs found so far with filters:
- [Location filter doesn't work when entering more than one character](https://github.com/msupply-foundation/open-msupply/issues/3040)
- [The transgender options do not appear in filter view for patients](https://github.com/msupply-foundation/open-msupply/issues/3072)
