### ISSUE TITLE
Carry customer reference field through from requisition to outbound shipment 

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2389]
## Is your feature request related to a problem? Please describe 👀
It would be nice for the customer reference field value to flow through from the customer requisition through to the outbound shipment - as @louisaw123 said, it "just seems like something that will be easily missed by the user cos they typed it in during the requisition then when the create shipment opens u would think its already there and not look in that spot again"

## Describe the solution you'd like 🎁
Could it flow through?

**Comment by marthakeezy** [comment]
V2.3.0 is out so moving to Done ✅
