### ISSUE TITLE
Shipment status not immediately updating when order process is changed

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2395]
## What went wrong? 😲
 

Shipment status is not immediately updated when the order process is changed within the same site.
First time round I shipped off my order from store A to store B and then I spent 5 minutes looking for the order and it was not there and then it appeared and in the shipped status.

Second time round I tried to record it (start from 54 seconds) - and it appears as "picked" until I select "sync" and then it updates to shipped. Although that was probably a coincidence because I had pressed synch quite a few times for the first order i did and even logged out and logged back in and there was no order. Did not try the refresh button however. 

https://github.com/openmsupply/open-msupply/assets/143057869/d32170d2-0d69-4439-8313-a2374cd942df

## Expected behaviour 🤔
Order is up to date without pressing sync?

## How to Reproduce 🔨

Not sure... tried it again just now and it was okay.  I did do a hard refresh before i tried it 3rd time though.. nick says it could have cleared some sort of conflicting data.

## Your environment 🌱
mac - v 1.4.00

**Comment by DhanyaHerath** [comment]
Similar to this old issue?
https://github.com/openmsupply/open-msupply/issues/2292

**Comment by roxy-dao** [comment]
Can't seem to reproduce this 😢

**Comment by mark-prins** [comment]
Unable to reproduce - tried the same scenario, both clicking 'Change status to Shipped' directly and clicking each status in turn, as per the video.
Verified that no sync happened in between - and in each case, the status was `Shipped` in the receiving store 🤷

**Comment by nisha-dangol** [comment]
Checked in v1.6.0 in sync system with two remote-active sites
As long as it was syncing, the status also seemed to sync properly. Issue not replicable - moving to Done!
