### ISSUE TITLE
Aggregate cold chain chart data

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2404]
## Tasks

- [x] #2494
- [x] #2575
- [x] #2574
- [x] #2581
- [x] #2648 

## Is your feature request related to a problem? Please describe 👀

Coming from [this comment](https://github.com/openmsupply/open-msupply/pull/2396#discussion_r1372956407)
The chart is currently fetching logs and then reducing the datapoints to a pre-defined maximum (currently 30).
It takes the start datetime from the first log (though this will come from the filter / data range set on the f/e) and the end datetime (ditto) and then calculates the duration between each datapoint.

For each sensor, an array is returned which gives the average temperature of all log entries which are for the sensor and within the time period.

If there are any breaches for that sensor within the period, then the first one is returned - the rationale being that there isn't space on the chart to display more than one breach icon, and given the periods we're talking about, it's likely that a single breach would be ongoing, i.e. unlikely to have multiple.

Additionally, the breach config data needs to be returned. If the aggregation is done on the server, then this also needs to be done on the server:

```typescript
  const breachConfig = {
    cold: Array.from({
      length: numOfDataPoints,
    }).map((_, i) => ({
      date: new Date(fromDate + periodDuration * i),
      temperature: 2,
    })),
    hot: Array.from({
      length: numOfDataPoints,
    }).map((_, i) => ({
      date: new Date(fromDate + periodDuration * i),
      temperature: 8,
    })),
  };
```

The API method would need to accept a start datetime and end datetime and support the current filter options for the temperature logs. Might be helpful to also take an Option for the max number of datapoints, defaulting to `30`

The return types could be:

```
sensor_node {
  id
  name
  location_name
  logs [
    date
    sensor_id
    temperature
    breach [
      id
      acknowledged
      end_datetime
      start_datetime
      type
    ]
  ]
}

breach_config {
  date
  temperature
}

```

With the query like
```
query temperatureChartData(
  $filter: TemperatureLogFilterInput
  $storeId: String!
  $max_data_points: Int
) {
  temperatureLogs(
    filter: $filter
    storeId: $storeId
    maxDataPoints: $maxDataPoints
  ) {
    ... on TemperatureChartDataConnector {
      sensors {
        id
        name
        location_name
        logs {
          date
          sensorId
          temperature
          breach {
            id
            acknowledged
            endDatetime
            startDatetime
            type
          }
        }
      }
      breachConfigs {
        cold {
          temperature
          datetime
        }        
        hot {
          temperature
          datetime
        }        
      }
    }
  }
}
```

**Comment by roxy-dao** [comment]
Closing since all issues for this seem to be done.
