### ISSUE TITLE
Unify programs and coldchain time component

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2415]
## Is your feature request related to a problem? Please describe 👀
Coldchain and programs currently use different time components. 

## Describe the solution you'd like 🎁
Unify them if possible.

### Describe alternatives you've considered 💭
Just leave it 🤷🏻

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Create an Encounter
- [x] See the date time change in modal

Hi @roxy-dao. There seems to be a bug in this time selection modal; any time I choose is always discarded and it only enters the current time while date looks correct! Issue submitted: #3052
