### ISSUE TITLE
Location removal

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2426]
## Is your feature request related to a problem? Please describe 👀
Coming from [this comment](https://github.com/openmsupply/open-msupply/pull/2419#discussion_r1380669188)
Update the API and f/e support to allow for removal of assigned locations. Currently, if you have a location assigned to a stock line, you cannot un-assign the location, only assign a different location.

## Describe the solution you'd like 🎁
Follow the example of Sensors which allow for specifying a Nullable Option in the api

**Comment by mark-prins** [comment]
Tested in develop and the removal is working. Must have checked in the feature branch 🤷

**Comment by nisha-dangol** [comment]
In v1.6.2,
Remove location is available and working for
- [x] Stock lines
- [x] Repacks
- [ ] Sensors - need to check!
