### ISSUE TITLE
Remove "tab" specifc code from the `common`  `useUrlQuery` method

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2431]
In https://github.com/openmsupply/open-msupply/pull/2412 there was a change to reset the tab url queries when changing a tab.

In `packages/common/src/hooks/useUrlQuery/useUrlQuery.ts` there is a block:

```ts
     else if (key === 'tab') {
        newQueryObject[key] = String(value);
        Object.entries(newQueryObject).forEach(([k, v]) => {
          if (v !== value) delete newQueryObject[k];
        });
      } 
```

However, as a `common` hook it shouldn't really make assumptions about application specific conventions about how tabs are handled but just manage the query params.

Possible options:
1) Remove this code and handle the url reset when changing a tab, e.g. where `<TabContext value={currentTab}>` is used
2) Remember which tab had which url queries params (this functionality was also needed for the patient programs tabs where currently the query params are lost when changing tabs)
  For example, we could have a new hook that persist the tab url params in a `zustand` store or in the local storage.

Note, why is resetting the url params working for the patient tabs?

**Comment by roxy-dao** [comment]
What do you mean by `Note, why is resetting the url params working for the patient tabs?`? Do you mean the sort URL query? It would be because of this block of code in DetailTabs.tsx... 

```js
    const query: UrlQueryObject = sort
      ? { tab, sort: sort.key, dir: sort.dir }
      : { tab };
```

**Comment by clemens-msupply** [comment]
Yes I wasn't sure why it isn't a problem for the patient tabs...
