### ISSUE TITLE
Cold chain : timezones in dates

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2438]
## What went wrong? 😲
 
There is a timezone problem with cold chain date data.
The dates shown on the chart are in local time, but if you want to filter, you need to specify dates in GMT

https://github.com/openmsupply/open-msupply/assets/74992958/055fad52-7247-422d-b32d-33227478b10e

## Expected behaviour 🤔
All dates should be in local time, while store in the database as GMT

**Comment by roxy-dao** [comment]
#2429 dup?
