### ISSUE TITLE
Clear selection shouldn't show if there is only one pack size

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2455]
## What went wrong? 😲
 
This can happen:
<img width="560" alt="Screenshot 2023-11-06 at 9 18 50 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/e0523535-e806-40e0-9339-9455f1c425c9">

And it makes no sense to clear something, when there's only one thing.

## Expected behaviour 🤔
Don't show the 'Clear selection' option when there's only one thing in the list.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Use the pack size demo data provided by Andrei
2. Or create a single pack size for an item

**Comment by marthakeezy** [comment]
Tested in V2.3.0, no option showing :) Moving to Done ✅
