### ISSUE TITLE
Benchmark Server

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2458]
Placeholder issue for performance test

**Comment by jmbrunskill** [comment]
[k6](https://k6.io/) could be a useful tool for this.

I was planning to use it in Health Supply Hub
https://github.com/msupply-foundation/health-supply-hub/issues/236

It allows you to write javascript and test whole workflows (like login, add a requistion, etc)
Combines load testing with workflow validation, which feels like a good place to get to eventually.

**Comment by andreievg** [comment]
Suggestions were to use ApacheBench, https://github.com/hatoo/oha, link to HSH issue: https://github.com/msupply-foundation/health-supply-hub/issues/236.

Also would be good to have comparison between mSupply and open mSupply, https://docs.msupply.org.nz/web_interface:rest_api?s[]=api

Would need realistic data set.

Would be good to create a grapqhl to show on our website:

![2023-11-09 12 28 54](https://github.com/msupply-foundation/open-msupply/assets/26194949/857e6420-18db-4c5b-832d-dee6d08a93ed)

@craigdrown can you please suggest a priority (how soon you want this on the website)

**Comment by mark-prins** [comment]
I've created tests using K6 and benchmarked against OG mSupply REST API

**Comment by mark-prins** [comment]
I've spent long enough on this I think.
Here's how the mSupply vs omSupply comparison looks - with a ramping up increase of virtual users from 0 to 250 over a test duration of 30s. 

The plot maps the average request duration against time, with the number of virtual users increasing over time. 

![Screenshot 2023-11-23 at 2 56 16 PM](https://github.com/msupply-foundation/open-msupply/assets/9192912/8338fdef-b2f5-4be4-a430-4a75b5f15f81)

**Comment by jmbrunskill** [comment]
Looks great @mark-prins, did you save any code anywhere to repeat this? What request did you run?

**Comment by mark-prins** [comment]
The basics are in [this repo](https://github.com/mark-prins/omsupply-loadtest)
It a pair of simple scripts, and I ran them with results logged to .csv files which I imported to a postgres database, extracted results from that, copied into excel and generated the charts.

Needless to say, there's plenty of scope for improvement!
