### ISSUE TITLE
Boolean Filter

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2464]
## Is your feature request related to a problem? Please describe 👀
As per https://github.com/msupply-foundation/open-msupply/issues/2382#issuecomment-1800369533

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Go to temperature breach (for unacknowledged) or location (for onHold)
- [x] Use filters mentioned above

Hi @roxy-dao . I see that the `unacknowledge` boolean shows the unacknowledged ones, but when it's OFF, shouldn't it show only acknowledged ones now? It shows all (both acknowledged & unacknowledged ones). [This is expected](https://recordit.co/cvK4JI0UR4)?
