### ISSUE TITLE
Service items don't show when distributing unless they have a item.code of "service"

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2467]
## What went wrong? 😲
 
Service items that should be visible in a store don't show up unless they have an item.code of 'service'. They show up in the masterlist tab, but not in the Catalogue tab or available to distribute. 

## Expected behaviour 🤔
I should be able to issue a service item and I thiiink I should see it in the Catalogue page. It shouldn't show in the Stock page

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. on mSupply central, create a service item (you may have to turn on the preference to use service items in the Preferences > Misc tab) 
2. Add the new item to a masterlist to make it visible in your omSupply store
3. See that you can't see it anywhere other than the Masterlists tab 

## Your environment 🌱

 - Version: 1.4.0
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one) Chrome, demo server 
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment]
@roxy-dao @anildahalsussol  you may have additional detail to add :)

**Comment by nisha-dangol** [comment]
Moving to Done! Issue submitted: #3128
