### ISSUE TITLE
Rename omSupply -> Open mSupply

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2471]
## What went wrong? 😲

Last I heard the memo was to rename `"omSupply"` to `"Open mSupply"` as "omSupply" is a bit of an internal shorthand and not our product's name. Therefore, installer/uninstaller should probably make the change.

![Screenshot 2023-11-10 at 12 28 17](https://github.com/msupply-foundation/open-msupply/assets/7684221/f46df749-fcd7-43ab-887a-12fea88e5844)

Also (ignore I've uninstalled haha) the installation directory:

![Screenshot 2023-11-10 at 12 28 42](https://github.com/msupply-foundation/open-msupply/assets/7684221/145c0569-bcb8-43ab-aa1a-bcb093f5c7e7)

(tangentially, should configuration be cleaned up by the uninstaller? IDK what convention is for what files to leave behind but I generally don't like apps that leave rubbish behind!)

## Your environment 🌱

 - Version: 1.5.0-RC3
 - Platform: All windows installers/uninstallers

**Comment by nisha-dangol** [comment]
Tested in v1.6.0-rc3 exe

I do see the word `Open mSuppply` in place of `omsupply`. So, looks like a PASS to me!
<img width="553" alt="oms2" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/960369a5-352f-413b-98bf-0d5748246031">
<img width="552" alt="oms3" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/80154fa0-adbe-4414-a521-8531f3583c98">
<img width="552" alt="oms4" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/bf00fab5-709a-43e9-a698-a2bab7968731">
<img width="556" alt="oms5" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/eef2682d-4828-413e-a760-89fc271c2be7">
<img width="549" alt="oms1" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/9b9efd81-dbc5-45c9-bbda-73bdefa658e8">
<img width="154" alt="oms-shortcut" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/06611721-7522-480c-825c-01624b7ad624">

As for the server upgrade from 1.5.4 to 1.6, it takes the previous location (`omsupply Server`); which is correct technically. So, I'll PASS this!
<img width="553" alt="oms server upgrade" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/83b3a10f-2f09-49e7-b890-0d556fe7fb84">
