### ISSUE TITLE
Login timer: Problem with "getLastRequestTime" after refresh

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#2476]
Okay, so I've figured out what's happening with the inactivity detector and why we sometimes get logged out even when active.

It's very odd -- turns out the `getLastRequestTime()` method called in `useRefreshToken` is getting a stale value (i.e. it's not being updated). But here's the weird part -- it _only_ starts behaving like this after a page refresh.

E.g. after normal login, the `getLastRequestTime()` result is the same as the value stored in the GqlContext, and they increase as expected on new requests:
![Screenshot 2023-11-14 at 2 55 13 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/2d0cf4dd-c384-4606-9fbd-4025bc341012)
![Screenshot 2023-11-14 at 2 55 25 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/4ee2b6f4-0a11-4ed8-909f-f0ceaa13a50f)

However, after a page refresh, the `getLastRequestTime()` value never increases any more, even though the actual value in GqlContext is being set from new requests as expected:
![Screenshot 2023-11-14 at 2 55 58 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/c5590404-6c5d-42f3-88ad-26f2965ce199)
![Screenshot 2023-11-14 at 2 56 07 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/8bba2e0d-f97d-4f4e-a1f9-426c12246ab3)

So this explains why we often get logged out -- the last request time doesn't update, and eventually is older than the 1-hour timeout, and so the refreshToken method doesn't run when it's supposed to.

Not 100% sure what's going on, but it seems to be something to do with the `createGql` method called in the `GqlProvider` -- it's creating a *new* instance of `GQLClient` every time it's called, but it probably should be only be using a single instance -- the one created when the app loads (as it's outside the hooks). Casual testing suggests that I can fix it by replacing:

```ts
  const [{ client }, setApi] = useState<{
    client: GQLClient;
  }>(() => createGql(url, skipRequest));
```

with 
```ts
 const [{ client }, setApi] = useState<{
    client: GQLClient;
  }>({ client: new GQLClient(url, { credentials: 'include' }, skipRequest) });
```

And then not using the "createGql" function at all (since we don't want multiple). This *seems* to solve at least that problem, although I'm not sure what else it might be breaking.

**Comment by mark-prins** [comment]
thanks! I was meaning to make this issue too
