### ISSUE TITLE
Item -> Master List tab shows all master lists

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2488]
## What went wrong? 😲
Item detail view master list tab shows all master lists.

## Expected behaviour 🤔
Should only show the master lists that are associated with the item.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
oh dear 🙄

**Comment by santoshkhanal12** [comment]
Tested on `v1.6.00`

# 🧪 How has/should this change been tested? 
- [x] Have more than one `master list`
- [x] Have items in one while not in the other
- [x] Go to item -> master list tab for each item
- [x] See that the master lists associated with each item is loaded 
![Screenshot 2024-01-22 at 13 27 09](https://github.com/msupply-foundation/open-msupply/assets/117138852/597f7db9-89ed-464a-afd6-a9702ddee3e4)
