### ISSUE TITLE
Desktop: WSOD

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2489]
## What went wrong? 😲
 
I've cleared local data and restarted the desktop app and get a white screen of death

<img width="1227" alt="Screenshot 2023-11-16 at 11 33 51 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/98d22d49-8688-4b6b-b9a8-b45598c222f9">

Closing the app and starting again, it works as expected

## Expected behaviour 🤔
Should load normally

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. I've added a 'clear data' menu option to enable testing
2. Doing that and restarting shows the white screen

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
due to running `app.relaunch()` without this it works ok.

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe
Help>Clear data will throw alert to confirm clearing data, which on confirming closes the app. On re-opening, it looks fine. I don't see any white screen of death there. Moving to Done!
