### ISSUE TITLE
Confirmation modal icon

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2497]
## Is your feature request related to a problem? Please describe 👀

<img width="443" alt="Screenshot 2023-11-17 at 10 16 20 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/f1f41103-b04e-475d-9aae-b8965c32a515">

The confirmation modal is asking a question, but with a default icon of 'info'

## Describe the solution you'd like 🎁

It would make more sense to have an icon of a question?

<img width="433" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/d642d346-7597-4be2-9ab0-aa1107e73b11">

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe

Moving to Done as I see the `?` icon in all the confirmation modals except for the below ones:
<img width="636" alt="Screenshot 2023-11-17 at 11 29 16 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/1218f2de-45ec-431d-9162-2a601750df2d">

<img width="576" alt="Screenshot 2023-11-17 at 11 24 16 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/1b65b09b-8823-4c24-a083-c53679c1614c">
