### ISSUE TITLE
Log Viewer: UI changes part I

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2499]
## Is your feature request related to a problem? Please describe 👀
Branching this from #1891 to make that issue more achievable.

This follows on from [this PR comment](https://github.com/openmsupply/open-msupply/pull/1260#pullrequestreview-1325274759) and is related to #1277 & #1890

This is what we'd like to have in the desktop and web versions:
- Have the log viewer functionality available for all platforms of omSupply
- Copy the log data to clipboard
- Select the log to view

## Describe the solution you'd like 🎁
Have the log viewer functionality available for all types of omSupply
- [ ] Use the (now available) API to fetch logs for web & desktop
- [ ] Add the ability to select which log to view (the API provides a list of available logs)
- [ ] Ability to save the log as a file (desktop), and
- [ ] Download the file (web)
- [ ] Copy to clipboard(?) for web & desktop

### Moneyworks Jobcode 🧰

`PG23OMD`

**Comment by fergie-nz** [comment]
I'm realising now that I don't know the difference between web and desktop. Are they different modes of omsupply?

**Comment by fergie-nz** [comment]
Oh Is this for when we are using electron?

> I'm realising now that I don't know the difference between web and desktop. Are they different modes of omsupply?

**Comment by mark-prins** [comment]
yep - we have a native version for windows & macOS which is packaged with electron. 
It's a bundled version of the web app which, because of the electron framework, can access some OS features too, such as the barcode scanner (via USB). for the log viewer, it's essentially the same as the web version. We have the option of opening a 'file save' dialog directly I guess for saving log files, which may be nicer than using the web download option
