### ISSUE TITLE
Android: not retaining previous connection

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2500]
## What went wrong? 😲
 
Android is always trying to run locally - if I connect to a server on my network, I'd like it to remember that connection and automatically reconnect to the server next time I start the app.

## Expected behaviour 🤔
Reconnect to the previous server on start up.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Start android after clearing data
2. Connect to a local server
3. Close and reopen the app

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe

On clearing cache in Android, I can connect to the previous server I connected before - this looks fine to me.
And, on clearing data, it clears all the data, meaning it'll start like it was installed for the first time, showing the option to act either as Server or Client mode, which also looks fine to me. 
Moving to Done!
