### ISSUE TITLE
Apply pack variants to Stocktake 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2503]
## Is your feature request related to a problem? Please describe 👀
- Stocktake is missing pack variants control. 

## Describe the solution you'd like 🎁
Want something similar to what inbound shipment is doing.

### Moneyworks Jobcode 🧰
OMS:NEST

**Comment by marthakeezy** [comment]
Tested as a part of #2078, moving to Done ✅
