### ISSUE TITLE
Patient list loading issues

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2504]
There are a couple of issues related to the patient list:
- [x] Pagination is not working: the full list of patient is always loaded
- [x] The patient document data is not needed (?) and can be removed to reduce the amount of loaded data
- [x] The patient list is loaded twice with slightly different parameters:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/63671e75-c396-4ccd-9aba-d8f0fa036349)
And with different query params:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/0b1da2e8-91c2-4727-840a-531cd1896cc0)

- [ ] The remote server seems to use quite a lot of cpu when loading the full patient list (sqlite). Profile what is happening and how it can be improved. (This can be moved into another issues)

**Comment by roxy-dao** [comment]
- Pagination seems to work for me... totalCount is used in the Patient Search component in Prescriptions to tell the user to narrow their search.... 
![Screenshot 2023-11-20 at 21 46 00](https://github.com/msupply-foundation/open-msupply/assets/61820074/65413c5e-7406-4d12-9f05-8ba2bdebe50c)
- Patient document is used in quite a few places....
- Not sure how to test CPU since I can't install desktop...

**Comment by clemens-msupply** [comment]
No pagination is not working for me :)

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/e9f676a8-0848-48cc-94fe-967d77c9bfd7)

Here Chris is number 21:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/38a56d98-d51a-4b18-8519-85874588990f)

So the offset is taken into account but not the limit.

I don't think we need the patient document data for the patient (?). So you could define a lighter patient row graphql object for the patient list...

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Check if pagination is working correctly
- [x] Patient list view should load a little faster - looks good to me
- [x] Check that searches still work (can find one in program enrolment -> mother field) - search works but selection of searched results has bug: #3051
