### ISSUE TITLE
Could highlight the expired stocks at the top when clicking on Expiring stock in dashboard

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2507]
## What went wrong 😲
One of the requests from South Sudan OMS training: they wanted to see the expired stocks highlighted (like in red) whenever they click on the `Expiring stock` in dashboard. 
I think the least we could do is sort the View stock with expired stocks showing at the top by default (rather than in the bottom like currently), or even better if you wanna go for highlighting expired lines in red!

## How To Reproduce ⬇️
Steps to reproduce the behaviour:
1. Get some stocks with expired batches (and some yet to expire ones as well)
2. Click on Dashboard on the oms landing page
3. Under Inventory Mgmt, click on `Expiring stock`
4. See error: you'll see list of stocks with sorted with Expiry, but the expired ones are showing at last. Better to have them on the top (or even better to highlight them in red or so)

## Expected behaviour 🤔
Better to show expired stocks on the top by default (or even better to highlight them in red or so)

## Screenshots 📸
<img width="1102" alt="expiring stock showing at last" src="https://github.com/msupply-foundation/msupply/assets/59193490/636e47ee-cd50-45cc-bdb0-bab8e6c68853">

## Your environment 🌱

 - Version: 1.4, 1.5
 - Platform:
   - [x] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by roxy-dao** [comment]
An expired stock filter has been recently implemented for the `View Stock` page and clicking on `Expired Stock` on dashboard redirects to `View Stock` with this filter on, is that enough?

**Comment by roxy-dao** [comment]
Built in 1.5.0.
