### ISSUE TITLE
Update Fridge-tag button label

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2508]
## What went wrong? 😲
Couple of issues with the current button label: 

1. We're not using the correct Berlinger marketing formatting
2. The button also serves for importing from Q-tags too...

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/73394034-7879-471b-95ee-c915f3cbdc65)

## Expected behaviour 🤔

Open to discussion but I think either of the following would be better: 

1. Update to `Import Fridge-tag` and include an info hover-over explaining to the user that they can also import Q-tags
2. Update to `Import USB sensor logs`

I think 1. is probably preferable because we get to blatantly advertise the ability of the system to interoperate with Berlinger Fridge-tags

Whatever we do, we need to at least update to use the correct Berlinger marketing formatting (`Fridge-tag`)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open the sensor page under Cold chain menu

## Your environment 🌱
 - Version: 1.5.00
 - Platform: Demo server
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by mark-prins** [comment]
Just update the translation for `button.import-fridge-tag` - can use the translation server for that

**Comment by adamdewey** [comment]
Translation has been updated

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/7cabdc79-ff25-4c3b-8403-7a6fcb439e8f)
