### ISSUE TITLE
Avoid document JSONForms edits without user interaction

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2510]
Some JSON Forms controls are adding empty objects or arrays when displaying some data, e.g. on patient details page for imported patients.
We previously tried to avoid this in the controls, but this proved to be harder than expected.

Alternatively:

- [ ] When comparing if data has been edited, treat `{}` and `[]` to be equal to `undefined`
- [ ] When saving a document don't add `{}` and `[]` if they weren't present previously

Problem can be seen when creating a new HIV care encounter and then navigating to the Physical Examination section.

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.6.2 exe

- [x] Create a new HIV care encounter. Navigate to the different bubbles, the save button should stay disabled.
- [x] In the same encounter modify some value and revert -> save button should revert to disabled.
- [x] Navigate to patient detail view and do similar test, i.e. reverted edits should not leave the save button enabled

Looking good so far, moving to Done!
