### ISSUE TITLE
Missing progres indication when saving an patient/encounter/enrolment

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2512]
When saving a document takes a longer time there is no indication that something is happening.

For example, make the save button spinning:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/7b67661d-c52e-4f00-80a9-8112934aaeef)

**Comment by fergie-nz** [comment]
I have a progress indicator/rotating wheel on buttons when saving program forms. I wonder if it is a specific case where this isn't showing?

I haven't been able to recreate

**Comment by fergie-nz** [comment]
@clemens-msupply this is the one I was struggling to recreate FYI

**Comment by clemens-msupply** [comment]
Had a quick look for patients the `isSaving` flag is used but not for encounter, enrolments and contact tracing...

```ts
const { JsonForm, saveData, isSaving, isDirty, validationError } =  useJsonForms()
```

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Go to any of the above areas
- [x] Fill out form and save
- [x] See spinny indication if data takes a while to save
Tried creating some entries; some long ones and saved. There was spinner loading, so I call it a PASS!
