### ISSUE TITLE
Count Spinner Control needs an option to unset the value

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2513]
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/fa773a9a-ab74-48b3-8d3c-1e24d636d17d)

When setting and deleting the value in the spinner the value is not fully unset. This causes a validation to fail.

For example, if the blood pressure field has been accidentally touched but the the blood pressure has not been measured the clinician is forced to enter a made up value in order to continue.

**Comment by roxy-dao** [comment]
> Tested in v1.6.2 exe
> 
> * [x]  Have programs set up (make sure to have latest program updates)
> * [x]  Add encounter to patient
> * [x]  Go to physical exam
> * [x]  Enter different values into blood pressure
> 
> Right now, it seems that systolic and diastolic values need either both values entered or none to show as valid. This can mean the values can be zero as well! Is this expected? @roxy-dao

We currently have the min and max for both at 0 and 999... should probably ask @clemens-msupply

**Comment by clemens-msupply** [comment]
Don't think 0 makes sense but neither make other very low values like 1, 2, 3... I would just leave it to the clinician who enters the data to validate it. [0...999] is just a coarse check.
