### ISSUE TITLE
Patient list view: have some default filter auto selected

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2514]
Its quite common to search a patient by name or id. It would be nice to have these common fields auto selected so that they don't have to be manually selected in the filter drop down.

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/be6e75bd-1732-44ce-9c56-8c4519d3b4fb)

**Comment by mark-prins** [comment]
If the parameter is added to the query with a blank value the filter will show e.g.

`https://demo-open.msupply.org/dispensary/patients?sort=code&firstName=`

will show the `firstName` filter, with an empty value. Perhaps just change the menu link, to add in the required query parts?

**Comment by santoshkhanal12** [comment]
Tested on `v1.6.00`

# 🧪 How has/should this change been tested? 
- [ ] Go to patients list view
- [ ] See default filters

@clemens-msupply @roxy-dao 
The default filter works fine. But found another bug that when you press 's' in the patient filter, it opens up the view stock window


https://github.com/msupply-foundation/open-msupply/assets/117138852/ff1b6d65-fa91-45b5-925f-13fb7cc13b4e

Issue has been created here: https://github.com/msupply-foundation/open-msupply/issues/2788
