### ISSUE TITLE
Rename patient patient id filter name

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2516]
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/d8f106dc-8091-4019-9070-9b743ee3fd99)

This filter searches by patient code, code2 and programEnrolmentId.

- [ ] rename filter to "Patient ID"

**Comment by santoshkhanal12** [comment]
Tested on` v1.6.00`

# 🧪 How has/should this change been tested? 
- Go to patient
- Click filters
- See rename

![Screenshot 2024-01-24 at 16 16 58](https://github.com/msupply-foundation/open-msupply/assets/117138852/613cd460-658e-4451-a18b-c955b52c7408)
