### ISSUE TITLE
Requisition columns: 'Remaining' is confusing people

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2523]
## What went wrong? 😲
 
There is some confusion of the intention of 'Remaining' on a customer requisition.
The column shows the quantity to supply less the quantity which has been added to outbound shipments already. And has been called `Remaining` which is shorthand for `Remaining to supply`

The column details are:
- **label**
  - `label.remaining-to-supply`
  - Remaining
- **description**
  - `description.remaining-to-supply`
  - The quantity remaining to be supplied, which is the Supply quantity less the quantity of this item on any linked Outbound Shipment

Here's how it works in practice:

https://github.com/msupply-foundation/open-msupply/assets/9192912/3ca6f35d-4149-4260-9a1b-ba3416f7ed84

As a possible reworking of the tooltip, here's Louisa's version in her docs: `the remaining quantity to supply to the customer which will be re-calculated after a shipment has been created`

The addition of the 're-calculation' is helpful, however I think the 'remaining quantity to supply' is slightly less clear and it removes the explanation of the quantity on outbound shipments.

There's a question of whether the columns is actually useful and if the use-case of a partially filled order is realistic. Advice so far is that it is very uncommon and the column is unlikely to be useful. However, columns can be hidden by the user.

Currently in mSupply the columns are 
- Customer requested
- Already issued
- Remaining to supply
- Supply this invoice

![telegram-cloud-photo-size-1-5109393503523286405-x](https://github.com/msupply-foundation/open-msupply/assets/9192912/fadf3ac5-4312-4ae0-9cb7-214dc4943a95)

Note that this gets even messier when the authorisation process is used - "What's left to supply from what quantity the authorisers approved"
We do have an 'approved quantity' shown in this case however. It's just that there is no calculation made to show a subtraction of issued against approved.

## Expected behaviour 🤔
To be defined.

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.0.00`
- [ ] `Store A` sends `Internal Order` to `Store B`
- [ ] Go to `Store B` -> `Requisition`
- [ ] First only partially supply the order and create shipments for that amount
- [ ] Go back to `Requisition` window and supply more without creating shipment
- [ ] See the different totals under `Supply`, `Issued` and `Remaining`.
- [ ] Also hover over `Issued` and `Remaining` tooltips to see if new descriptions are clearer

**Comment by AnushaUp** [comment]
@mark-prins @roxy-dao I still see error in this part 

https://github.com/msupply-foundation/open-msupply/assets/115983430/0ebb636a-294e-4525-a886-2af50158ac5b

**Comment by roxy-dao** [comment]
Is your error related to the issued quantity not changing? If you hover over the tooltip for issued it says "Quantity already issued in shipments". You have to create a shipment with the item first

**Comment by AnushaUp** [comment]
Hi @roxy-dao here my confusion was with the remaining column. Its not showing the correct value
![Screenshot_20240516_104321_Open mSupply](https://github.com/msupply-foundation/open-msupply/assets/115983430/dab37d52-c022-4da2-b9c8-b458738a9c6c)
In this image if the requested quantity is 50 and issued quantity is 10 then why its showing 0?🤷‍♀️

**Comment by roxy-dao** [comment]
Remaining is how much you want to supply - how much is in shipments. So 0 is correct.
