### ISSUE TITLE
Android version not running when no network available

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2526]
## What went wrong? 😲
 

"The tablet is working with WiFi or internet but not working in local host.
..while choosing server to e don’t have localhost as option at all when we connect to WiFi, 
and then we turned off WiFi and choose local host as server but it crashed"

To be investigated.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Turn off wifi
2. From the login screen, click on the server list (pencil icon)
3. Select localhost
4. Boom!

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
Checked in v1.6.2 exe

Moving to Done as I can login when wifi is OFF as well; it preserves the previous connection, and no crashes - PASS!
