### ISSUE TITLE
Android portrait view: Dashboard text wrapping

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2529]
## What went wrong? 😲
Probably missed a few commits while cherry-picking... seems to work normally 
![photo_2023-11-23 01 15 24](https://github.com/msupply-foundation/open-msupply/assets/61820074/5149c3d4-0300-4f61-9da8-1d10bc2d0814)

## Expected behaviour 🤔
The dashboard should look pretty~

## Your environment 🌱

 - Version: 1.5.2
 - Platform:
   - android (tablet)

**Comment by roxy-dao** [comment]
Seems to work... commits missed while cherry picking

**Comment by CouldBeFree** [comment]
I want to work on this issue, but i can't pass the initialize step.
What Central server URL should be provided?

**Comment by mark-prins** [comment]
have manually recreated the commits into v1.5.03
