### ISSUE TITLE
Name merging: store

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2558]
## Is your feature request related to a problem? Please describe 👀

We need to replace all FKs to `name.id` with FKs to `name_link.id` instead, to allow easy merge management.

## Describe the solution you'd like 🎁

Base: [feature/merging](https://github.com/msupply-foundation/open-msupply/tree/feature/merging)
Using the PR for [name_link + invoice](https://github.com/msupply-foundation/open-msupply/issues/2452) as a guide:
- [x] Add `store.name_link_id` and migrate with `store.name_link_id = store.name_id`
- [x] Remove `store.name_id`
- [x] Update any views that relied on relations of `store.name_id`
- [x] Update `store` at the repository layer to return related `name` records based on `store.name_link_id` rather than `store.name_id`

### Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by roxy-dao** [comment]
name_id for store will never change so don't need to alter to name_link_id

**Comment by Chris-Petty** [comment]
Hmmm that's fair! Merging names that relate to a store would be pretty bork. Occasionally we'd get requests to merge stores though that's pretty sketchy as well so we probably won't support it (if really determined to do it, just disable the old store and stocktake it's stock into the "kept" store).

**Comment by clemens-msupply** [comment]
I just noticed it in the code and got confused that it hasn't been done. I will sneak in a comment in my next PR...

**Comment by roxy-dao** [comment]
Reopening since this has become relevant (:
