### ISSUE TITLE
Server URL shows as 127.0.0.1

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2564]
## What went wrong? 😲
 
On @adamdewey's tablet, the sync screen show the server as `127.0.0.1`
![telegram-cloud-photo-size-1-5114232179319221171-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/184dd982-0dd3-4081-b4e4-4fbf3ee09c55)

I also once saw it display like this, but it resolved after restarting the tablet:
![telegram-cloud-photo-size-1-5125291024321719661-y](https://github.com/msupply-foundation/open-msupply/assets/9192912/cb85bc74-db37-421c-ab8f-3c48589f52cb)

Unsure if this is running in client or server mode.

## Expected behaviour 🤔
The server should be resolving the address to an public IP.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 1.5.02 (tablet server)
 - Platform:
   - [X] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by adamdewey** [comment]
Running in server mode :)

**Comment by mark-prins** [comment]
retested using `develop` branch and that's working correctly. The issue is just on the v1.5.02 branch
