### ISSUE TITLE
Shortcuts for "OK" and "OK & Next" buttons

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2572]
## Is your feature request related to a problem? Please describe 👀

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/abbaefef-ec3f-45f2-9172-51f6f6bd7acd)

When entering stock takes on a PC, I want to do fast data entry. Part of that is quickly pressing "OK & Next" with a shortcut, so I can save changes on this row and begin editing the next row without my hands leaving the keyboard... also in development it makes spamming in data a bit easier 😁. 

Not sure if bug or request, but same same. Allegedly some modals might already have this but I checked outbound shipment and NADA!

## Describe the solution you'd like 🎁

Should be a shortcut for OK & Next, OK and Cancel. I suggest:

- "Enter" for OK & Next
- "ctrl + enter" for OK
- "esc" Seems to already cancel modals 🙂 

Are their any modals that only have "OK", No "OK & Next"? In those cases the shortcut for OK can be "enter"

### Additional context 💌

Not sure what the desired behaviour should be... but when I press `cmd+k` to get the shortcuts menu it pops up behind the modal so I can't really see the options though I doubt it gives options for the modal context, but for the page behind the modal.

Tangent because I think it'd be neat: I noticed that the "add batch" button has a (+) to indicate the shortcut. But, doing that for all buttons will obviously look a bit ugly. It'd be COOL if you could press and hold a button combo (say "alt+ctrl") that either changes each label to include the shortcut combination OR a little tool tip 😃.

### Your environment 🌱

 - Version: dev 1.6.0 MacOS Firefox dev edition

**Comment by marthakeezy** [comment]
Just tested in V1.7.0, works as expected :) The shortcuts only work if you are 'located' in one of the fields and not in an overall modal, e.g. if you are not entering in any of the fields, the shortcuts won't work. Checked-in with Laché and this is expected behaviour so test is PASSED :) ✅
