### ISSUE TITLE
Fridge tag carry over - front end

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2592]
## Is your feature request related to a problem? Please describe 👀

Consolidating the front end issues in #2423, since these are small items to address:

- [x] Better way to display errors and success, and stop user being able to refresh the page and re-upload, when upload is in progress (see todo in [this file](https://github.com/openmsupply/open-msupply/blob/ace39473bee622bf6d71d99bf59e71e505122b6d/client/packages/coldchain/src/Sensor/ListView/AppBarButtons.tsx))
- [x] Is the button in the right place ? (No - move to logs section and add prompt for user to add location on first import)
- [x] Add some subtext to button to explain that user can also import Q-tag logs
- [x] Restrict upload input to .txt
- [x] Use different icon for button:  https://github.com/openmsupply/open-msupply/pull/2422#discussion_r1381051855 which suggests the [upload](https://feathericons.com/?query=upload) from feather

**Comment by AnushaUp** [comment]
Tested in omSupply `V1.6.2`
- [ ] Better way to display errors and success, and stop user being able to refresh the page and re-upload, when upload is in progress

**Comment by AnushaUp** [comment]
Hello @mark-prins ! Can you confirm this one?

**Comment by mark-prins** [comment]
Hi @AnushaUp - do you mean
- when importing a fridge tag file
- if you reload the page while an upload is in progress
- the data is still imported

that's what it looks like in the recording. Are you asking - should that happen?

There's no specification / requirement around what should happen(!) so it's a bit unknown. We haven't coded for the site to behave in a particular way.
I think if the user reloads when the import is in progress then the result will depend on the browser and we don't have much control. All we can do is prompt the user as we do. if they then chose to reload.. 🤷

**Comment by AnushaUp** [comment]
Hi! @mark-prins sorry my question was not clear. Yeah, I was asking about the behaviour when reloading the page in the middle of the importing. It was actually imported in mine. Thanks
I will move this to done.
