### ISSUE TITLE
Sensor back end - link temperature logs to breaches

### ISSUE THREAD

**Issue by adrianwb** [msupply-foundation/open-msupply#2594]
## Is your feature request related to a problem? Please describe 👀

Part of #2423 - currently there is a breach type column for temperature logs but it is not populated when sensor data is imported

## Describe the solution you'd like 🎁

If the temperature log is part of a consecutive breach, then link it to that; otherwise if it is part of a cumulative breach, link it to that - see https://github.com/msupply-foundation/open-msupply/pull/2383#issuecomment-1787689587

The most flexible way to do this is via a function which takes the breach parameters and links any matching temperature logs to that breach (i.e. temperature out of range and between the start/end timestamps):
- if it's a consecutive breach, then process all temperature logs in the time range
- if it's a cumulative breach, only process temperature logs in the time range which aren't already associated with a consecutive breach 

### Additional context 💌

This is consistent with what happens in desktop mSupply.

The front end already has the breach type column, but that may need updated to show the data?

**Comment by andreievg** [comment]
Thanks @adrianwb for making this issue, I agree with your proposed solution

> if it's a cumulative breach, only process temperature logs in the time range which aren't already associated with a consecutive breach

I wonder if we need to think about a join table at some point ? (maybe as carry over issue) 

You've previously mentioned that we can deduce breach <-> log association on the go, which I also think is possible, but it seems like it would be hard to scale ?

**Comment by mark-prins** [comment]
> Any preferences from the UI side @mark-prins?

The above sounds fine - and should fit in with what we have currently wrt breach display thanks
