### ISSUE TITLE
Cannot cancel the window while choosing supplier name when creating internal order

### ISSUE THREAD

**Issue by anildahalsussol** [msupply-foundation/open-msupply#2608]
## What went wrong? 😲
 
On the tablet when we want to create a new order it shows a window to choose a supplier. If I did not find the name or if I want to cancel there is no way to do that. And every time we have to end up with creating dummy internal orders with the wrong supplier names. Which will cause many mistakes and internal orders to pile up on the list.
But on a desktop, you can close it by clicking outside the window.

## Expected behaviour 🤔
Should be able to close the window.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. In tablet to replenishment.
2. Create order.
3. Now you get the window with the supplier list.
4. Here you cannot close the window until you choose at least one supplier.

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] Android (tablet)

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Go to Replenishment
- [x] Choose Internal Orders
- [x] Create new
- [x] Clicking outside (or tapping on table) to close the modal
