### ISSUE TITLE
**URGENT** No item name appearing on tablet when selecting on an item from a list

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2614]
## What went wrong? 😲
Item name does not appear when you create a stocktake and the list generates, and then you select on the item. See video:

https://github.com/msupply-foundation/open-msupply/assets/143057869/796ca04d-4025-44c6-bf55-35577b0cde51

Also happens with other methods of opening items such as opening an outbound shipment and then selecting on the order, and clicking on the item in the order - this is empty.

 
See vid

## Expected behaviour 🤔
Item name should appear after you select on the item in the lists

## How to Reproduce 🔨
See vid

Steps to reproduce the behaviour:
1. Create stocktake
2. Open up a masterlist of your stocktake 
3. Select on the item

This is also similar for outbound shipment - select the item that is already in an outbound shipment order, the name will not appear.

## Your environment 🌱
v1.5 on android tablet samsung

**Comment by mark-prins** [comment]
tested on web and unable to repro.

**Comment by mark-prins** [comment]
tested on android and unable to replicate. This is on v1.6 - but I'm not aware of any changes that would affect this area.

Stocktake:

https://github.com/msupply-foundation/open-msupply/assets/9192912/75d9a395-5365-4a19-b805-5955addd6d3b

Outbound:

https://github.com/msupply-foundation/open-msupply/assets/9192912/bcaca1d3-a9e6-4830-87ac-2981d605285e

**Comment by andreievg** [comment]
Managed to replicate, if you have more then 500 items visible and say 501st is in the stocktake (501st based on sort by name), further summary here: https://github.com/msupply-foundation/open-msupply-internal/issues/38

**Comment by mark-prins** [comment]
Nice work @andreievg! makes perfect sense now that you point it out.. we've had something like this previously.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe with datafile containing ~500 items, and can't replicate the original issue (where item name doesn't appear). So, moving to Done!
