### ISSUE TITLE
Sync and expose custom data on Name

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2618]
Sync, integrate and expose custom data on Name via API

@guatemartin needs this for SAGE integration extension work

### Job code

DJIEXSAGE

**Comment by mark-prins** [comment]
PR merged

**Comment by nisha-dangol** [comment]
Hi @andreievg,
Question regarding the test cases here: should I expect that the custom-data entered(on server) for the name(facility) should appear in the openmsupply UI as well?
