### ISSUE TITLE
Cold chain notifications

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2627]
## Is your feature request related to a problem? Please describe 👀

The notification panel is currently showing breaches. We discussed earlier whether to display breaches or excursions in this panel, and whether to show the latest only, if you could scroll through all the available and whether you can acknowledge or dismiss notifications. 

Prior to a full release of cold chain functionality, we'd like to consolidate some of those requests and tidy up the current implementation.

Changes to make:

- Breaches can be acknowledged in Open mSupply, and a comment must be supplied when acknowledging #2679
- When uploading logs from a Fridge-Tag, do not import if there are no logs in the file ( this is a check to prevent breach-only loggers; if we don't have temperature logs for a device then our current model breaks) #2680
- Display excursions in the notification area, along with the most recent breach. An excursion disappears when the temperature is within the operating range #2459 #2677
- Display the number of breaches and excursions in the notification area #2677
- Show breach comments in the breaches table #2678

Nice to have:
- Configuration for excursions, which allows definition of temperature and time limits which apply

This comes from a recent discussion, the key outcomes of which were:

- We are keeping the concept of Breaches and Excursions as distinct items
- Breach signifies the user needs to check things are ok with the Stock
- Excursion signifies the user needs to check things are ok with the Cool Storage Device
- Breach configurations will not be done in Open mSupply, we just accept what the devices send us
- But ideally we will have an Excursion configuration in Open mSupply so that a duration can be set (to stop excursions triggering for just opening the fridge door)
- Breaches will need to be acknowledged in Open mSupply and a comment recorded
- Excursions will not need to be acknowledged, they will disappear once the excursion resolves
- We will not support devices that do not send us temperature logs (i.e. we will only support Fridge-tag 2L, UL and Q-tags)
- If we do have excursion configuration in Open mSupply, then the behaviour of notify will differ, though we can manually craft queries for notify which mimic the oms behaviour. Decided that having Open mSupply operate in the ideal way has benefits which outweigh the problems of having the behaviour differ.

### Additional context 💌

Recent discussion: https://docs.google.com/document/d/1tu6ZZQK0QXuKCHfgJfRFjEjbwuJrYj5RAB16NvC-Xkc/edit

**Comment by adamdewey** [comment]
@mark-prins - for the comments we capture during the acknowledgment step, can we display them in a column in the Breaches tab of the Monitoring page?
