### ISSUE TITLE
Location sort function

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2633]
## Is your feature request related to a problem? Please describe 👀
![Screenshot 2023-12-14 at 2 52 54 PM](https://github.com/msupply-foundation/open-msupply/assets/143057869/fd02108b-6cfe-4373-a0ba-3d87868d7343)

Can the location have a sort arrow too please :) Trying to sort items based on location but unable to do this. 

## Describe the solution you'd like 🎁
Sort button similar to the name / expiry / code which sorts items in order.

### Additional context 💌

Trying to figure out what items have been added to a particular location so that we can remove these items so that the location can be removed. Bit tedious to scroll through all the pages looking for items assigned to that location. Probably other use cases for a location sort button too.

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe
- [x] Have stock in different locations
- [x] Go to View Stock
- [x] Sort by location (code)
