### ISSUE TITLE
location should be location code in stocktake and anywhere else that shows location

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#2641]
## Is your feature request related to a problem? Please describe 👀

currently location shows full location name such as when doing a stocktake. users dont want to see the full location name because they can go into location to view full name. the shelves are also labelled with the location code (not full location name) so finding something is easier when looking for the code. 

<img width="1250" alt="Screenshot 2023-12-14 at 6 44 55 PM" src="https://github.com/msupply-foundation/open-msupply/assets/143057869/868a04ae-469d-4c4f-8c70-f52a066ac30e">

old msupply  also uses location code not the full name

## Describe the solution you'd like 🎁

see scrfeenshot

**Comment by nisha-dangol** [comment]
Testing in v1.6.2 exe
- [x] Check that the following usages of location have been changed to display the location code:
    - [x] Inbound Shipment
    - [x] Inbound Shipment Edit
    - [x] Outbound Shipment
    - [x] Outbound ShipmentEdit
    - [x] Stocktake
    - [x] Stocktake edit
    - [ ] Temperature Breach
    - [ ] Temperature Log
    - [ ] Sensor
    - [ ] Prescriptions
    - [ ] PrescriptionLineEdit

**Comment by nisha-dangol** [comment]
Hey @mark-prins , I see the location being showed as [multiple] when issuing items (having no location assigned) in prescription. Submitted issue here: #3029

**Comment by mark-prins** [comment]
Thanks @nisha-dangol - I've seen that and keep intending to make an issue and haven't yet.. thanks!
