### ISSUE TITLE
Allow to enter decimal in issue quantity for Requisitions

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2663]
## What went wrong? 😲
 
In OG mSupply, we can issue stocks in decimal. Maybe we'll soon need the same feature in oms as well, since ordering (internal order) is allowed in both units and packs. In case oms receives a requisition (in units), then it'll be difficult to complete that request in a single shipment since currently, there's neither any feature to supply in units nor decimal values allowed in issue quantity. 
## Expected behaviour 🤔
Maybe simply allow decimal entry in issue quantity like the OG mSupply? 
(or you wanna add units/packs toggle like the one in IO window?)

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. First of all, turn the `pack to one` pref OFF for all the stores you're playing/testing with (for ease)
2. To replicate this specific issue, have a setup with both desktop and oms stores
3. From desktop, issue some units (by placing decimal values in CI) to oms-store so that oms-store now has decimal valued pack sizes, sth like this below:
<img width="1231" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/0ea5cd17-80b3-4c7b-b426-24e0ada84dc3">

4. Also make internal order to oms-store in such a way decimal value have to be entered from oms-side (see above recording for reference)
5. After sync, in oms-store, try to fulfill that request
6. See error: you simply can't fulfill that request in a single transaction! [A reference to what I mean in this step is below recording: here, allocating simply doesn't work! At some point, I saw the system crash as well in this step, but not crashing every single time]

https://github.com/msupply-foundation/open-msupply/assets/59193490/5ca24dea-c968-49e6-a268-308983e30a77

## Additional Information [need to investigate]
Also, throghout this, I've come across some random crashings while trying to access Internal Order (in the same oms-site where decimal pack Qty were introduced after above steps) and one also while processing the requisition (in received reqistions>Supply requested>Create outbound shipment>crash!) 

**Note**: This additional one is not replicable every single time with same steps, so will need to investigate further

## Your environment 🌱

 - Version: v1.5.4; v2.0.0-rc5 exe with mSupply v7-14-01
 - Platform: server exe + browser(chrome)
   - browser (extra points if you tell us which one)

**Comment by DhanyaHerath** [comment]
triage: can this be addressed by pack variants?

**Comment by roxy-dao** [comment]
Can add to this epic #3705 and decide how to handle this

**Comment by clemens-msupply** [comment]
Just to clarify:
- in the requisition you requested a quantity of 9. 
- on stock you have 1.2 packs with a packSize of 10
- to fullfil the requisition you have to ship 1 pack of 10 (instead of the requested 9)

Is this correct?

@mark-prins is this the expected behaviour?

**Comment by nisha-dangol** [comment]
> Just to clarify:
> 
> * in the requisition you requested a quantity of 9.
> * on stock you have 1.2 packs with a packSize of 10
> * to fullfil the requisition you have to ship 1 pack of 10 (instead of the requested 9)
> 
> Is this correct?
>
Yup, there's no way to fulfill requisition with the exact number of units requested; it's always more or less especially when the requested quan is in units instead of packs

> @mark-prins is this the expected behaviour?
>
I'll let @mark-prins define the expected-behavior around these kind of scenarios

**Comment by roxy-dao** [comment]
Closed in #4359

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.1.0`


- [ ] Create an Internal Order
- [ ] Add a line that has a default pack size other than 1
- [ ] Try order in decimal
