### ISSUE TITLE
Can we auto-confirm requisition after the shipment has been created from the requistion?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2667]
## What went wrong? 😲
 
Currently, on getting a new requisition, there's no way to differentiate the requisitions which are new (unprocessed) or which have associated shipments already.

I think this can be confusing for the users (at least, for the first time users who are using/understanding the order flow: Internal Order>>Requisition>>Shipment) 

## Expected behaviour 🤔
Maybe it'll be good to have three statuses (like the OG mSupply):
sg - for newly received requisitions (or the ones where NO related shipment line has been made)
cn - once the outbound shipment has been created from the requisition
fn - User can finalise it. No any changes can be made afterwards

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get multiple requisitions (by creating IO from other stores)
2. Fulfill some requisitions: supply requested and create outbound shipment (either finalise it or not) while leave the other requisitions without supplying (literally do nothing for some).
3. Go back to the Requisitions List
4. See error: it is kinda difficult to know which were fulfilled and which are remaining from that list. [You'll have to manually open the requisition and click `Create shipment` to know which orders are in the process of being fulfilled/acknowledged]
At times of multiple requisitions, I think this can be quite frustrating?
Worst case: User can get confused and end up finalizing the wrong requisition (then, again another order may have to be processed from the customer/requester)

## Agreed solution
Rather than add a third status value, and automatically set the shipment to that status, display that a shipment has been created.

To do this:
* add a filter to the requisition api for `Shipment created` ( open to alternative naming suggestions ): boolean, indicates whether any shipment has been created for this requisition
* add the `Shipments` property ( again, open to naming suggestions ) which gives the number of shipments created for this requisition
* add a column to the requisition list view which shows the number of shipments

## Your environment 🌱

 - Version: v1.5.4
 - Platform:
   - browser (extra points if you tell us which one)

**Comment by mark-prins** [comment]
Currently showing the shipment in the more info panel:

<img width="1249" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/7ff2488e-9768-48c5-a852-6bcc836f3e58">

Suggestion: to add the number of shipments which have been created.

* add a filter for 'a shipment has been created' 
* add a column to the requisition list for the number of shipments

**Comment by regotaina** [comment]
Tested in RC5
Desktop app

# 🧪 Testing



- [ ] Have some response requisitions
- [ ] Have at least one with shipment/s created and one without
- [ ] Add the `Shipment Created` filter
- [ ] Toggle on and off to see requisitions that have shipments created
- [ ] Also make sure `Shipments` count in column is correct.
