### ISSUE TITLE
Showing wrong toast/snack when deleting lines in SI, that was modified in stocktake previously

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2669]
## What went wrong? 😲
 
Showing wrong toast/snack when deleting lines in SI, that was modified in stocktake previously

## Expected behaviour 🤔
If the toast/snack says `1 Line deleted` then delete that line as well? 
If the line should not be deleted, then show corresponding toast/snack like `Line should not be deleted` ?

I'm not sure of expected behavior here: if the line should be deleted or not: somewhat similar to issue/question in mSupply as well:  https://github.com/msupply-foundation/msupply/issues/14097 ?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a manual inbound with any item
2. Confirm delivered (this will create a stock line for the item)
3. Create a stocktake with said item and change stock (change counted packs)
4. Go back to the manual inbound invoice that was created and try to delete line
5. See error: there should be some snacks/toast message that it can't be deleted I think! 
But for me, it's showing that `Line's deleted` toast message but the line is not deleted though! [See recording](https://recordit.co/SWJcMTiLJf) for reference!
 
## Your environment 🌱

 - Version: v1.5.4
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by fergie-nz** [comment]
Hi @nisha-dangol ,

I'm struggling to recreate this issue - I'm getting the right error when I try to delete the line.

Are you still able to recreate this issue?

https://github.com/msupply-foundation/open-msupply/assets/90807420/dd7e6bf6-1fdd-4c71-9b6c-badb8d986b2e

**Comment by nisha-dangol** [comment]
> Hi @nisha-dangol ,
> 
> I'm struggling to recreate this issue - I'm getting the right error when I try to delete the line.
> 
> Are you still able to recreate this issue?
> 
Hi @fergie-nz , I can still recreate this issue in 1.6 as well.
PLease refer to [this recording for reference](https://recordit.co/61DL5W18gm) for detailed steps.
