### ISSUE TITLE
Implement notification changes

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2677]
## Is your feature request related to a problem? Please describe 👀
Following on from #2459 - the notification query needs to be made available and then used by the front end.
From the epic:

* _Display excursions in the notification area, along with the most recent breach. An excursion disappears when the temperature is within the operating range_
* _Display the number of breaches and excursions in the notification area_

**Comment by AnushaUp** [comment]
@mark-prins the breach notifications are shown as per the expectation and the excursion part can be test when the admin area is completed so that all the functionality can be tested together as per discussion.
