### ISSUE TITLE
Ability to acknowledge breaches

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2679]
## Is your feature request related to a problem? Please describe 👀
Coming from #2627 

- Breaches can be acknowledged in Open mSupply
- A comment must be supplied when acknowledging

### Additional context 💌

Trello: https://trello.com/c/c2tb7hZF/131-epic-acknowledge-temperature-breach-alerts-omsupply-ui

**Comment by AnushaUp** [comment]
Tested in `omSupply1.6.2` , `mSupply V12-12-6` and  `CCA 0-5-6` 

The Breaches can be acknowledged but the next breach wont appear in the omsSupply after the acknowledgement
![Screenshot_20240228_162348_Open mSupply](https://github.com/msupply-foundation/open-msupply/assets/115983430/e617063b-64a8-459f-9e05-a627b1078945)
