### ISSUE TITLE
Do not import if there are no logs in the file

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2680]
## Is your feature request related to a problem? Please describe 👀
Coming from #2627 

_When uploading logs from a Fridge-Tag, do not import if there are no logs in the file ( this is a check to prevent breach-only loggers; if we don't have temperature logs for a device then our current model breaks)_

**Comment by mark-prins** [comment]
closing - already handled:

<img width="499" alt="Screenshot 2024-01-09 at 2 26 19 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/04272470-f9ea-429f-9dff-208ff525702c">

**Comment by AnushaUp** [comment]
Tested and passed. The alert appeared.
