### ISSUE TITLE
Cold chain: Temperature logs synced to central server are incompatible with existing Dashboard and Notify

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2686]
## What went wrong? 😲

Temperature logs display on a remote server with the correct time zone, but after being synced to the central server they are displaying with an incorrect time zone (think perhaps no time zone is being applied)

Temperature logs on Cold Chain App: 

<img width="1279" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/19318937/04be4ede-cbf5-4697-8580-87a543cb987d">

Temperature logs on Open mSupply remote server: 

![telegram-cloud-photo-size-1-4965322029624569065-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/2bdfe337-7233-4713-861d-399d3b9a1fd1)

Temperature logs on central server: 

![telegram-cloud-photo-size-1-4965322029624569062-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/98837a90-3ef0-4739-a584-b505e2126f81)

![telegram-cloud-photo-size-1-4965322029624569063-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/e71ba923-c34f-4bba-9546-d5b21c7f7d7f)

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/40f11e6e-a2c0-4a57-82c0-6a93b714b6ff)

## Expected behaviour 🤔

Time zone should be preserved from CCA through to central server. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set up CCA tablet with a time zone other than UTC
2. Set up Open mSupply tablet with the same time zone
3. Set up central server with same time zone (Windows and Postgres DB)
4. Sync data from CCA tablet to Open mSupply tablet
5. Sync data from Open mSupply tablet to central server
6. Observe time zone not preserved

## Your environment 🌱
 - CCA Version: 0.5.6
 - Open mSupply version: 1.5.03
 - mSupply version: V7-09-05
 - Postgres version: 13

Trello: https://trello.com/c/AjKVZuTh/242-temperature-logs-coming-across-from-oms-to-central-server-with-incorrect-timezone

**Comment by andreievg** [comment]
There is om_datetime field, which should be a UTC timestamp string, we should be using that in dashboards etc.. There are quite a few layers to the cake, cca -> omsupply -> msupply -> dashboard, and on top of that msupply stores date and time separately, and in it's own 4d format that's hard to truly understand.

**Comment by adamdewey** [comment]
Thanks @andreievg - yeah we probably need to make sure that anything that uses those Open mSupply temperature datetimes are working correctly - off the top of my head: 

- Dashboards
- Notify
- Temperature tables in mSupply Desktop
- Breach alerts in mSupply Desktop

Although I think the last 2 are edge cases as hopefully we won't have to support hybrid Open mSupply / mSupply Desktop systems for too long

**Comment by adamdewey** [comment]
Have updated Dashboards to apply correct timezone: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/227ece49-3f0a-49f0-8658-27e4dbff6b50)

**Comment by adamdewey** [comment]
@jmbrunskill - Notify will need to be updated to be able to cater for both CCA > mSupply Desktop and CCA > Open mSupply > mSupply Desktop. 

How should we approach that?

**Comment by jmbrunskill** [comment]
> @jmbrunskill - Notify will need to be updated to be able to cater for both CCA > mSupply Desktop and CCA > Open mSupply > mSupply Desktop.
> 
> How should we approach that?

It should probably use the om_datetime if available, once that field exists is it set for every record? Or only on records from open-mSupply? I've created a ticket in notify for this https://github.com/msupply-foundation/notify/issues/282

**Comment by andreievg** [comment]
triage: Preference for mSupply to also populate that field when cold chain app sync the data to it. And then updated Dashboards/Notify to reflect this. I think this would be a more reliable and aligned solution going forward.

TODO:

Create issue in mSupply for this + Dashboard, update existing servers.
Close this issue
