### ISSUE TITLE
Cold chain: Change graph to display 24 hours from current time backwards

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2700]
## Is your feature request related to a problem? Please describe 👀

The cold chain graph is now displaying 24 hours 🥳 

But it seems to be from the end of the day backwards. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/b969347b-75b2-41f6-aa4f-88dd742da15c)

It would be more useful if we could display from the current time backwards

This would maximise the data the user could see and also give them an indication of whether they're receiving recent data or not

## Describe the solution you'd like 🎁

Display 24 hours from current time backwards.

**Comment by roxy-dao** [comment]
Closed in #2706

**Comment by marthakeezy** [comment]
Tested in v1.6.02 - the graph displays 24 hours from the current time backwards, not from the end of the day :) Test is passed! ✅
