### ISSUE TITLE
Cold chain: Can't read breach comments

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2703]
## What went wrong? 😲

It's not possible for users to read the breach comments as the column is too small (on a tablet anyway)

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/662ad210-f47f-4741-9a77-2f730229a8fb)

## Expected behaviour 🤔

Users should be able to review comments to see what has been written for a breach

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Produce a breach
2. Acknowledge it in Open mSupply and add a comment
3. View the comment in the Breaches tab

## Your environment 🌱

 - Version: 1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Closed in #2719

**Comment by marthakeezy** [comment]
@roxy-dao @mark-prins just noticed during testing the text goes beyond the text box, when typing in long strings

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/c97aec6a-9638-4583-a1a8-29bf93add043)

**Comment by roxy-dao** [comment]
> Just found this (only happens with one string, not when there are multiple words with spaces in-between). I marked the issue as passed, but probably something to just be aware of rather than fix :)
> 
> ![image](https://private-user-images.githubusercontent.com/153777484/307660318-c97aec6a-9638-4583-a1a8-29bf93add043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NzI3MzMsIm5iZiI6MTcwODk3MjQzMywicGF0aCI6Ii8xNTM3Nzc0ODQvMzA3NjYwMzE4LWM5N2FlYzZhLTk2MzgtNDU4My1hMWE4LTI5YmY5M2FkZDA0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxODMzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGMwOGU2OGVmNTVlYWRhNGI2NDQ1ODc0MThlZGZiNWZlZWI2MzY2NzYxMDRjZDkwZTBkNzY4NTM1NDZiYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZWIBxzGHj1_UEEkaq9CJnwmmDQhuYk7lS_rR2izUFgY)

Thanks Maria~ Have made an issue for this, will probably be low urgency (: https://github.com/msupply-foundation/open-msupply/issues/3076

**Comment by marthakeezy** [comment]
Thanks @roxy-dao! :)
