### ISSUE TITLE
Cold chain: Breaches acknowledged in CCA bypass breach acknowledgement workflow in Open mSupply

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2704]
## What went wrong? 😲

In Open mSupply the users must enter a comment before acknowledging a breach. 
This means there is a record for other users to understand what happened and what action was taken. 

However there is a way to bypass this: by acknowledging the breaches on CCA which causes breaches to be marked as acknowledged in Open mSupply, but without a comment. 

This bypasses the workflow that we want to enforce - i.e. that users need to add a comment to explain why they acknowledged the breach. 

## Expected behaviour 🤔

Breaches acknowledged in CCA should only affect CCA. 
The breach should still need to be acknowledged in Open mSupply, and a comment added as normal. 

Perhaps a clarification would be to change the terminology in CCA to 'clearing' the breach visual alert, rather than acknowledging it? 

I did muse about adding the ability to add a comment in CCA, but there would be no way to enforce the capturing of which user entered the comment. 

Additionally it wouldn't be possible for sensors such as Fridge-tags or others, so I think we should disregard this option. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Produce a breach with CCA
2. Note that the breach appears as unacknowledged in Open mSupply
3. Acknowledge the breach in CCA
4. Note that the breach appears as acknowledged in Open mSupply (without a comment)

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Closed in #2738
