### ISSUE TITLE
Cold chain: Show 'Unacknowledged breach' toggle by default

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2707]
The Unacknowledged breach toggle is useful!

But at the moment the user has to go into the filters and show it before they can use it, which is a little tedious. 

Could we make it show by default?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/8df998ec-d45e-47ae-a38f-5dad33b06f2c)

## Describe the solution you'd like 🎁

Always show Unacknowledged breach toggle

**Comment by roxy-dao** [comment]
Closed in #2721

**Comment by marthakeezy** [comment]
Tested on v1.6.02 - the toggle is shown by default without having to go into filters. Test passed ✅
