### ISSUE TITLE
Cold chain: Graph does not represent temperature data accurately - max / min temperature data points not shown

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2708]
## What went wrong? 😲

Due to data averaging the graph does not accurately reflect the temperature history of the sensors. 

For example here you can see that there has been a breach, but the graph doesn't show the line ever crossing the 8 °C threshold: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/474907f3-b84d-4e5e-971a-4e8c0c32ff27)

You also lose some detail with the data smoothing. 

## Expected behaviour 🤔

Ideally no averaging would be applied and all data points would be shown. 

For example as demonstrated by the Grafana graph of the same data here: 

<img width="1263" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/19318937/32d0d1c5-8104-4a98-8dcb-62686f973d15">

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Compare Open mSupply graphs with Grafana graphs

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by adamdewey** [comment]
If the concern is due to performance perhaps we could show all data points for any time period less than 24 hours?

And for longer periods is there any way we could make sure we always show the maximum and minimum data points for every max and min curve?

**Comment by roxy-dao** [comment]
Closed in #2741

**Comment by marthakeezy** [comment]
Hi team, 

Just testing this issue - this is what my omSupply graph looks like: 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/061ac5a8-84f5-400a-bc62-7dc32c809e89)

And this is my Grafana graph:

<img width="1441" alt="Screenshot 2024-02-27 at 12 09 22 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/f4f52049-560b-46c4-b13e-00cb5ea01c4b">

They look quite different - can anyone confirm I am on the right track with testing?

**Comment by marthakeezy** [comment]
This is for a date range of 1 week - still looks pretty different to me!

![photo_2024-02-27 12 38 34](https://github.com/msupply-foundation/open-msupply/assets/153777484/cc905a0d-e7e3-4e77-88f0-3806531fbc34)

![photo_2024-02-27 12 38 36](https://github.com/msupply-foundation/open-msupply/assets/153777484/435bcb31-f377-4748-8e9c-f9ac58ff2920)

**Comment by adamdewey** [comment]
@marthakeezy - what is the breach threshold in CCA for these graphs?

I can understand that Open mSupply needs to do some averaging for performance reasons, but we should be showing the maximum points of any breaches, even after averaging. 

But my guess here is that this is all one big breach, which is why only the first peak is showing?

Side note: seems a bit dodgy that 2 breach icons are being displayed...

**Comment by marthakeezy** [comment]
@adamdewey I think 2 breach icons are there because there is one for each sensor, hence they are together? 

It's a bit tricky to remember the breach temperature sorry! Because I changed it since, but it would have been somewhere around 20 degrees for both sensors. Is there a way to find what the breach temperature was set to before the changes? Maybe some sort of logs?

**Comment by adamdewey** [comment]
@marthakeezy - ah, the breach icons are a bit confusing because I don't see matching peaks on the green line in Grafana. 

For the breach threshold, I don't think there are any logs unfortunately, but if it was around 20 C then it looks like both sensors would be constantly breaching which is why there is only 1 breach icon shown for each line. 

If the threshold was around 25 C I would have expected to see more defined peaks and a breach icon for each peak

**Comment by marthakeezy** [comment]
Spoke to Adam - need more time to test, setting up a testing environment where I can see 2 distinct temperature breaches :) Watch this space!

**Comment by marthakeezy** [comment]
A couple things I noticed when testing, related to the above:

1. F3 sensor has dropped down below 8 degrees to the normal temperature window, however on the graph it's still showing as breaching

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/7ade8fac-45ed-4fe3-ad78-4675b460c902)

<img width="1441" alt="Screenshot 2024-03-06 at 11 30 41 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/943d463d-7fcf-48f0-be10-673f8f0d7ad7">

2. Next -> produced a cold breach, F3 sensor dropped below the minimum temperature, CCA & Grafana are showing a breach, but not OMS

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/b0636c22-967f-48a4-81ae-84c340b55658)

<img width="1451" alt="Screenshot 2024-03-06 at 12 51 50 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/05ea10c2-334e-4df8-860a-534b2701f6c4">

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/97e04fc3-383b-4354-ab8a-29fc28c1344f)

3. For the sensor at the top, I imitated **hot breach -> cold breach -> hot breach**. For the sensor at the bottom, I imitated **cold breach -> hot breach -> cold breach**. 

I noticed the icons have not changed? E.g. 25 degrees is showing as cold breach and 7 degrees is showing hot breach (even though this one is actually within the 2-8 degrees window of normal temperature)

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/c5881593-6707-4025-b608-9b22cd7f8a01)

@mark-prins @adamdewey let me know if I am on the right track with testing this one? 🙏🙏

**Comment by adamdewey** [comment]
Hey @marthakeezy - I think you are on the right track. 

> F3 sensor has dropped down below 8 degrees to the normal temperature window, however on the graph it's still showing as breaching

Those breach icons should remain there even if the temperature returns to normal - to indicate at which point the breach occurred in the past. 

However it's weird that OMS is showing values over 25 C when Grafana doesn't show anything over ~ 23 C

Also the fact it's showing 2 breach icons is incorrect - but that should be in a separate issue. 

> Next -> produced a cold breach, F3 sensor dropped below the minimum temperature, CCA & Grafana are showing a breach, but not OMS

This seems to be a bug - it should show an icon for the high breach and an icon for the cold breach. 

But that should also be in a separate issue. 

> I noticed the icons have not changed? E.g. 25 degrees is showing as cold breach and 7 degrees is showing hot breach (even though this one is actually within the 2-8 degrees window of normal temperature)

As discusses, this has been raised in [#297](https://github.com/msupply-foundation/msupply-cold-chain/issues/297)

To keep things less complicated, I think this issue should be concerned with the shape of the graph matching as closely as possible to reality, whilst also allowing for necessary compromises due to tablet performance capabilities. 

Everything else should be raised in separate issues :)

**Comment by marthakeezy** [comment]
Thanks @adamdewey! Sorry, I think I got sidetracked with all the other issues I have noticed :')

If we are only talking about the graph shapes for the issue above, would you say they are matching to the satisfactory level? I am a bit concerned with the point #1 from my previous comment, and as you noticed as well: 

* Grafana is showing ~ 27 degrees for F3 sensor and ~ 29 degrees for the EE sensor
* OMS is showing ~ 25 degrees for F3 sensor and ~20 degrees for the EE sensor

The #2 set of screenshots I included seems to be more accurate.

**Comment by adamdewey** [comment]
@marthakeezy - yeah I think there's something funky with #1, like you say, think it's worth more attention and either re-opening this issue or raising a similar one?

**Comment by mark-prins** [comment]
It would be useful to compare the log and breach tables against what is in CCA or grafana.
We need to determine if the data is correct in omSupply and the chart is displaying incorrectly.
