### ISSUE TITLE
Database error not reporting correctly

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2710]
## What went wrong? 😲
 
I've tried to test an android version and get this prompt when I login:

![Screenshot 2024-01-15 at 11 52 10 AM](https://github.com/msupply-foundation/open-msupply/assets/9192912/3bfb9275-19c7-4ea1-9fa8-bf47f9d9dccb)

However the problem isn't an authentication error, but a database error, as you can see on the RHS.
This is because the prior version deployed (1.6.00) was a develop version which has the same version number as the new, therefore no migration is done. A column has been added though, resulting in a data problem which requires re-initialisation.

This won't be a problem in production, but is misleading and frustrating for the dev environment. Could we tell users upfront that it is a fundamental problem which requires reinitialisation?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install a version, configure and login
2. Make a database change, creating a migration, but keeping the version the same
3. Deploy and try to login to the new version

_or_

1. Delete a column in your database and login
2. See error

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
Have seen this when upgrading to v1.7-rc1 to v1.7-rc2 as well.
<img width="1183" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/81c5fe34-dc8d-4cab-9b2c-d3c7f98033ea">
