### ISSUE TITLE
Cold chain: Multiple breach icons displayed for a single breach

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2711]
## What went wrong? 😲

Multiple breach icons are sometimes shown on the graph for a singular breach event: 

https://github.com/msupply-foundation/open-msupply/assets/19318937/57983462-bce1-460d-b6f9-1513e18af407

## Expected behaviour 🤔

Only 1 breach icon should be shown for a single breach event - at the point where the breach starts. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Take datafile from vaccine demo server
2. Open data on a tablet (not sure if reproducible on desktop?)

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Closed in #2741

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe

Unlike the original, I see that there is only single breach icon showing for a single breach; so simply not replicable anymore; so moving to Done!
