### ISSUE TITLE
Cold chain: Touching screen causes date filters to reset

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2712]
## What went wrong? 😲

Touching the screen removes any date filters - meaning you can't touch breach icons to show more details. 

https://github.com/msupply-foundation/open-msupply/assets/19318937/cb662294-cf26-40a4-bf36-6af3eb28e341

## Expected behaviour 🤔

Date filters shouldn't change unless user changes them deliberately. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Select a date filter
2. Touch anywhere on graph

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
that's when the date input has focus - given that the input has a value prior, I think it should retain the value.

**Comment by roxy-dao** [comment]
Closed in #2723

**Comment by marthakeezy** [comment]
Tested on v1.6.02 - passed!

Clicked around after setting the from and to dates - the dates have remained selected. PASSED ✅

https://github.com/msupply-foundation/open-msupply/assets/153777484/ea64f85d-6678-47ec-b1c8-ac259f41818a
