### ISSUE TITLE
Cold chain: Can't select both 'From' and 'To' dates in date filter

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2713]
## What went wrong? 😲

You can only select either a 'From' date or a 'To' date, not both: 

https://github.com/msupply-foundation/open-msupply/assets/19318937/7528f5e6-c0f3-444c-9576-22a136161dc0

## Expected behaviour 🤔

User is able to select a date range by selecting both From and To dates

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open Cold Chain graph
2. Select a From date
3. Select a To date

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Closed in #2723

**Comment by marthakeezy** [comment]
Tested in v1.6.02 - test is passed. 

Checked Chart & Log tabs, clicked out of date & time picker and the dates remained entered. PASS ✅
