### ISSUE TITLE
Cold chain: Unable to import fridge tag data on Android

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2715]
## What went wrong? 😲
 
If you try to import on android this fails with the following message:

![Screenshot 2024-01-15 at 1 04 26 PM](https://github.com/msupply-foundation/open-msupply/assets/9192912/99c8aee9-81ef-4cd9-ba9c-c8e4b04ab37f)

## Expected behaviour 🤔
Should be able to import

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Monitoring
2. Click on Import
3. Try to import a file

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by jmbrunskill** [comment]
Adam and I are not able to replicate this. Potentially fixed by this? https://github.com/msupply-foundation/open-msupply/commit/00c708402dbf9f2b044f8ee0ca43620bf0ddca81
