### ISSUE TITLE
Cold chain: Rename 'Temperature' column in Breach tab

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2716]
## Is your feature request related to a problem? Please describe 👀

It's not immediately obvious that the `Temperature` column is showing the maximum / minimum temperature experienced during a breach. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/8b25577d-1a33-425a-92ea-d037b6ec0f57)

## Describe the solution you'd like 🎁

To make it clearer we could rename the column to `Max / min` or  `Max / min °C`

It should be obvious from the `°C` in the data values that the column is showing temperature so I don't think we need it explicitly in the title.

**Comment by adamdewey** [comment]
While we're in the area, could we add a space between the value and the unit - e.g. `7.1 °C` rather than `7.1°C`

**Comment by roxy-dao** [comment]
Closed in #2722

**Comment by adamdewey** [comment]
@mark-prins @roxy-dao - ooh, sorry, my bad - I sent the wrong screenshot!

Meant to update the temperature in the Breaches tab, not the log tab - d'oh! 🙈

**Comment by roxy-dao** [comment]
Closed in #2755

**Comment by AnushaUp** [comment]
@mark-prins @roxy-dao I updated the omsupply from 1.6.00 to 1.6.00-rc3 and got this error in the `Breaches` tab while login and the page was not appearing as well like in the video below:

https://github.com/msupply-foundation/open-msupply/assets/115983430/958d5988-66e6-4f68-8faf-919e056bebe4


![Screenshot 2024-01-22 at 3 43 16 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/b5df43bd-cb8e-47ec-ab69-e67871156aba)

**Comment by mark-prins** [comment]
Hi @AnushaUp - this is due to the way we have created the database migrations unfortunately!
We migrate from the last main version to the current version.. but both v1.6.00-RC2 and v1.6.00-RC3 are considered version `1.6.00` as far as the database migration is concerned.

that means, if we make a database change between RC versions, then your database doesn't get updated.
you will need to delete the omSupply database and re-sync with mSupply unfortunately.

**Comment by AnushaUp** [comment]
# 🧪 How has/should this change been tested? 
Tested in omsupply `v1.6.00-RC3` and mSupply version v7-12-00beta21

- [ ]  the log list should show `temperature` 
- [ ]  the breach list should show `max / min` along with a description

**Comment by AnushaUp** [comment]
The log list showing temperature:
![Screenshot 2024-01-23 at 2 15 28 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/7f8874dc-9d76-4047-9a34-9f17578217ca)

The breach list showing max/min column:
![Screenshot 2024-01-23 at 2 17 28 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/27b1e8fd-41ae-4504-813b-af7a5095086b)
@mark-prins there should be description as well?🧐

**Comment by mark-prins** [comment]
the little i icon next to the heading (Max / Min) has a tooltip with the description 

when you hover over it you should see:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/732a1d23-7e1d-4977-9dc5-d8e08e980748)

**Comment by AnushaUp** [comment]
Well then we can move then issue to done. Working as expected.👍
