### ISSUE TITLE
Cold chain: Change sensor type to 'mSupply RTMD'

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2717]
## Is your feature request related to a problem? Please describe 👀

The product that is registered with WHO PQS is our own RTMD, so it would be good to update the Sensor type here to say `mSupply RTMD`: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/7bce937a-9005-4c62-9be6-ccd10e1b574c)

**Comment by roxy-dao** [comment]
Merged in #2726

**Comment by AnushaUp** [comment]
@mark-prins Here got value in the sensor type 
![Screenshot_20240130_171134_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/115983430/f4ed253d-8324-47ab-a4d3-e17d55ebdff9)

Do I need to expect anything in the sensor details window?
![Screenshot_20240130_172624_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/115983430/66066e28-ee0f-41c0-ab65-f050df55ef74)

**Comment by mark-prins** [comment]
Oh! we didn't add the type to the detail window! I'll make an issue - thanks
