### ISSUE TITLE
Cold chain: Handle acknowledgement of ongoing breaches

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2718]
## Is your feature request related to a problem? Please describe 👀

Currently we allow the user to acknowledge ongoing breaches. This is in stark contrast to CCA where we don't allow the user to acknowledge until the breach has resolved. 

## Describe the solution you'd like 🎁

My initial reaction was to do the same in Open mSupply but after some more thought I realised this could be annoying for the user if a sensor or fridge is broken - the alert and notification bar could be there for a long time. 

One suggestion is that we add a 'Snooze' functionality to allow the user to snooze ongoing breaches for a period of time.

I think it would probably require the user to enter a comment each time they snoozed though..

**Comment by roxy-dao** [comment]
Closed in #2724

**Comment by AnushaUp** [comment]
Tested and Passed👍
