### ISSUE TITLE
Cold chain: Sometimes graph missing sections

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2720]
## What went wrong? 😲

Unsure of the rhyme or reason for this, couldn't see a pattern. 

But sometimes the graph is missing sections: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/dce1faac-21b6-4e0b-927d-926abc08d514)

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/3fd258ae-5d43-405c-b3e8-2ffbba6d7cf8)

Will see if I can find a pattern

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Unsure?

## Your environment 🌱

 - Version: V1.6.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
@adamdewey is this on demo server, or on your local machine ? It would be hard to replicate without database, any chance you can get the database, or at least the 4d data file with this data synced ? (can do an internal repo issue and link to this one if you need to share datafile)

**Comment by adamdewey** [comment]
@andreievg - yeah it's on my tablet, which is a remote site for the vaccine demo server. 

There is a copy of the datafile here though: https://drive.google.com/drive/folders/1W0GhxySd2lVRjQ3X-uwPUdDYVsoDDKJv

**Comment by andreievg** [comment]
@fergie-nz do you mind looking at this one ?

I would try to replicate this one first, by syncing the data from central 4d file then:
* Try to replicate as shown in screenshots
* See if any temperature logs are actually missing
* Try to replicate with sqlite browser by commenting out here and [pasting query in sqlite](https://github.com/msupply-foundation/open-msupply/blob/ec2c29408a8aabc9c329d56d1874c98197545f98/server/repository/src/db_diesel/temperature_chart/temperature_chart.rs#L46) (if that's ok, then follow up the stack to see where problem occurs)

**Comment by mark-prins** [comment]
In the examples - there are temperature log entries missing for those time periods. 
I think the chart is displaying correctly in this case, and if we smooth over the gap then we are obscuring a data issue which the user should be aware of.

**Comment by adamdewey** [comment]
I agree, the graph is displaying correctly - but for whatever reason there is some data missing from the Open mSupply logs. 

Sometimes this corresponds with missing data in CCA, but sometimes not. 

Looks like a multi-layered issue!

**Comment by fergie-nz** [comment]
I haven't been able to replicate - but I believe if there is an issue, it lies either in CCA, or between CCA and mSupply rather than in omSupply.

**Comment by adamdewey** [comment]
@fergie-nz - I think there is 1 issue between the sensors and CCA (some logs are not saved to CCA) and 1 issue between CCA and omSupply (some logs appear to be lost in sync)

**Comment by jmbrunskill** [comment]
@mark-prins @adamdewey  for now I'm adding some server logs if there are any errors encountered accepting data from the Cold Chain App. So hopefully if there is a bug with the formatting or integration from CCA -> OMS, we'll have something to follow up on in the logs.

**Comment by adamdewey** [comment]
Nice @marthakeezy - could you show the temperature logs too for a comparison?

**Comment by marthakeezy** [comment]
Sure - for example, here the graph drops out at 05:09 for one of the sensors but all records are present

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/68bac51a-58a5-471b-8982-bfcc6a5e1609)

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/9432652b-dfc9-46fe-acdf-c7b4ac7d487f)

But interestingly enough, for this case the sensor did drop out (why?) and the chart therefore is not showing any records

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/6a22efe4-3b64-4b4d-8515-a1ce690045c2)

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/769ed68a-0146-4a82-addf-fd42d47d4923)

Also I noticed that when one sensor drops out, another starts up again? If we look at the gaps, it's almost like when one starts, another finishes

**Comment by adamdewey** [comment]
Yeah weird - possibly a rendering issue? 

@jmbrunskill @mark-prins @fergie-nz - seems there's still an issue, would you prefer to re-open this issue or raise a new one?
