### ISSUE TITLE
Mobile migration supplier invoice in outbound shipments, serial number 0

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2728]
## What went wrong? 😲
 
Converting mobile site (with existing trasaction to oms-stores) to oms-site has some serious bugs right now: the SI type is changing to CI type in below instance

## Expected behaviour 🤔
Type of invoice should never change like that

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Have a sync setup with multiple sites: mobile and oms.
2. Create some transactions between mobile and oms (create some CI and SI) and sync. [I created some transaction to two different oms-sites]
![Screenshot_20240115_125956_mSupply Mobile](https://github.com/msupply-foundation/open-msupply/assets/59193490/09c10c16-d5cd-41ef-95ac-9980d5c0eb52)
![Screenshot_20240115_130007_mSupply Mobile](https://github.com/msupply-foundation/open-msupply/assets/59193490/600eecdb-1294-45c7-938e-e3cba38af4d3)

In mobile, you may see [this similar error](https://github.com/msupply-foundation/msupply/issues/14090#issuecomment-1874916589) of Invoice No. 0 (I noticed SI inv. No. 0 in mine)
4. Now on cloud, reset hardware ID and password for that mobile-site so we'll switch it to oms.
5. In tablet (or desktop), initialise as oms site
6. Login and check the shipments list
![Screenshot_20240115_130151_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/59193490/3af60691-5d89-440d-b334-0b3ffd1f9214)
![Screenshot_20240115_130145_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/59193490/26654fdc-cfe6-4f75-a88f-1c1ca985a12d)

7. See error: notice that SI (inv 0) is now showing up in Outbound Shipment (CI) list - HUGE BUG! 
wonder this will be the same in other instances as well - need to investigate!

## Your environment 🌱

 - Version: v1.5.03; mSupply Server: v7-12-beta11, mobile: v8.6.5
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by Chris-Petty** [comment]
@nisha-dangol it's on our backlog to support migration for mSupply desktop and mobile sites to open mSupply, but work hasn't started on it yet so just a heads up this likely won't be touched until then.

Can you clarify what was done on step 2? For the supplier invoice, did you create an outbound shipment in OMS to the mSupply Mobile site? If the invoice on mSupply mobile got allocated serial number `0` by mSupply mobile, then that's a bug with mSupply mobile.

**Comment by nisha-dangol** [comment]
> Can you clarify what was done on step 2? For the supplier invoice, did you create an outbound shipment in OMS to the mSupply Mobile site? If the invoice on mSupply mobile got allocated serial number `0` by mSupply mobile, then that's a bug with mSupply mobile.
>
For step2, 
I created one CI (from mobile) to the oms-store:
![Screenshot_20240115_125956_mSupply Mobile](https://github.com/msupply-foundation/open-msupply/assets/59193490/09c10c16-d5cd-41ef-95ac-9980d5c0eb52)

And, two SI's: one for the oms-store and one was just for a name/facility from the mobile-store:
![Screenshot_20240115_130007_mSupply Mobile](https://github.com/msupply-foundation/open-msupply/assets/59193490/600eecdb-1294-45c7-938e-e3cba38af4d3)

**Comment by Chris-Petty** [comment]
Right so for the supplier invoice that has invoice number `0`, you made an outbound shipment in OMS logged into Piplup Water Store to the store used on mobile? And synced mobile? Weeeeird because the central server generates the transfer (i.e. the SI) for mobile and should assign `-1`, which mobile will allocate a proper number once it's synced it. So either mobile accidentally assigned `0` somehow, or the central server sent through `0` instead of `-1`.

I think there has been a similar issue with mobile before where the `number` table hasn't been populated correctly. 

HA I only just registered/understood the part where the SI is showing under outbound shipments, you're right that's cray haha. I'm not sure if there is a way but are you able to share the database from your test OMS?

**Comment by nisha-dangol** [comment]
> Right so for the supplier invoice that has invoice number `0`, you made an outbound shipment in OMS logged into Piplup Water Store to the store used on mobile? And synced mobile? Weeeeird because the central server generates the transfer (i.e. the SI) for mobile and should assign `-1`, which mobile will allocate a proper number once it's synced it. So either mobile accidentally assigned `0` somehow, or the central server sent through `0` instead of `-1`.
> 
Yup. 
FYI,  I also tried creating 2 CI from oms-store to mobile-store. One got ID 0 and other go ID 1 in the SI in the mobile-store.
![Screenshot_20240116_125143_mSupply Mobile](https://github.com/msupply-foundation/open-msupply/assets/59193490/3d85681d-9759-4583-aefc-042bee7d28db)

And that mobile-store SI's No: 0 & 1, after converted to oms now shows both as CI(outbound shipment):
![Screenshot_20240116_125209_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/59193490/9cfd12bc-bb6e-41ac-82f2-858bbb9b98c0)
![Screenshot_20240116_125159_openmsupply-client](https://github.com/msupply-foundation/open-msupply/assets/59193490/af289ccc-bec2-4f89-b283-1435d4f65f3a)
<br><br>
> I think there has been a similar issue with mobile before where the `number` table hasn't been populated correctly.
> 
> HA I only just registered/understood the part where the SI is showing under outbound shipments, you're right that's cray haha. I'm not sure if there is a way but are you able to share the database from your test OMS?
>
[Here's the datafile](https://www.dropbox.com/scl/fi/lv6aozo0ovtdxprj1fkev/2728-piplup-water-oms-store-open-msupply-database-shm.zip?rlkey=0mpij20zg143q510p3jun5995&dl=0) of that Piplup oms-store!
