### ISSUE TITLE
Move merging migrations to 1.7

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2733]
## Is your feature request related to a problem? Please describe 👀
Move merging migrations to 1.7. Should be done after every issue for merge has been completed.

### Moneyworks Jobcode 🧰
OMS:MERGE

**Comment by Chris-Petty** [comment]
pls revert this commit where I removed indexing from 1.06 migration and double check drop/create indexes e4de7353c761bb836288f808a6750bc26e9ae182

**Comment by Chris-Petty** [comment]
Closed in #2792
