### ISSUE TITLE
Server upgrade fails

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2737]
## What went wrong? 😲
 
With the issue #2471 coming in, the upgrade process of open mSupply server has an issue.
The existing server is detected, and the upgrade runs successfully. However, the new version is installed into the folder `Open mSupply Server` and the configuration and logs remain in the previous installation folder (in my case, 'omSupply Server').

As a result, the service does not start but enters an endless starting state.

## Expected behaviour 🤔
I would expect the current folder to be used. 
Please retest this scenario too:

* Install an earlier version into a non-standard folder
* Upgrade

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install a previous version
2. Upgrade to v1.6.00-rc1

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by nisha-dangol** [comment]
Noticed the same. I had a server running in v1.5.4. On upgrading with v1.6.0.rc1, saw the same: service never started; only kept showing `Starting`

**Comment by AnushaUp** [comment]
# 🧪 Testing 
Tested in latest `v1.6.00-rec3` upgraded from `v 1.5.04`

- [ ] Install a previous version into a non-standard folder. 
- [ ] Install this version: you should see the upgrade process and it will detect the current folder

**Comment by roxy-dao** [comment]
Closed in #2764
