### ISSUE TITLE
Master list taking time to open if there are 5K + items

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#2742]
## What went wrong? 😲
 
In omSupply tablet it taking time to open master list and showing blank page as in given recordings below. Found while testing [THIS issue](https://github.com/msupply-foundation/open-msupply/issues/2158) 

https://github.com/msupply-foundation/open-msupply/assets/115983430/a04b1b05-a2e8-4de4-b013-f9ecea3dcbe4

## Expected behaviour 🤔

If there's pagination like we have in the item list, It would be way more faster and won't appear the blank screen.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make a master list with 5K items
2. Sync in omSupply site on tablet
3. Click on the master list

## Your environment 🌱

 - Version: 
   - android (tablet) -> omSupply version - `V1.6.00`
   - server (windows) -> mSupply version - `V7-12-00-Beta17`
 - Platform:
   - android (tablet) -> Android version - `13`

**Comment by regotaina** [comment]
PASSED THE TEST 💯 
# 🧪 How has/should this change been tested? 
- [x] Have a datafile with more than maybe 50 items in a master list? 
- [x] Go to the master list
- [x] See new pagination
- [x] Other areas that use master list should still function the same (e.g. The count in `Create Stocktake with Master List` button)
