### ISSUE TITLE
Application crashes when stocktake is made with master-list of more than 5k records of item list

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#2743]
## What went wrong? 😲
 
When we try to create stocktake from the master-list of items with more then 5K item list then the application crashes as shown from the recording below:

https://github.com/msupply-foundation/open-msupply/assets/115983430/b60ab2be-ef85-425a-b3be-7c7d783a66f0

Found while testing [THIS](https://github.com/msupply-foundation/open-msupply/issues/2158)
## Expected behaviour 🤔

It may take time but shouldn't crash

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Goto stocktake 
2. Choose from the master-list with more then 5K items
3. See error

## Your environment 🌱

 - Version: 
   - android (tablet) -> omSupply version - `V1.6.00`
   - server (windows) -> mSupply version - `V7-12-00-Beta17`
 - Platform:
   - android (tablet) -> Android version - `13`

**Comment by andreievg** [comment]
We've added pagination to stocktake, i think it's solved for now
