### ISSUE TITLE
Name merging: invoice.name_id translator get actual name.id

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2745]
## Is your feature request related to a problem? Please describe 👀

name merging needs to make sure that when records with FK field `name_link_id` or similar sync, they correctly send the `name_id` of the linked name as `name_id`, not `name_link_id` as `name_id`. e.g.

https://github.com/msupply-foundation/open-msupply/blob/e4de7353c761bb836288f808a6750bc26e9ae182/server/service/src/sync/translations/invoice.rs#L289

The `name_id` here is actually `name_link_id` value from the sql `invoice` table. `InvoiceRepository` does `inner join` shenanigans to get the related `item_id`.

## Describe the solution you'd like 🎁

Simplest solution is to use the domain repositories rather than the DB row repositories. e.g.

https://github.com/msupply-foundation/open-msupply/blob/e4de7353c761bb836288f808a6750bc26e9ae182/server/service/src/sync/translations/invoice.rs#L279-L280

Should use `InvoiceRepository` instead and required changes around that.

If that can't be used, it's OK to get it from `NameLinkRepository`.

### Describe alternatives you've considered 💭

Eventually we will actually rename `name_id` to `name_link_id` properly which will make this much clearer.

### Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by roxy-dao** [comment]
Closed in #2753
