### ISSUE TITLE
Name merging: name_store_join.name_id translator get actual name.id

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2749]
## Is your feature request related to a problem? Please describe 👀

name merging needs to make sure that when records with FK field `name_link_id` or similar sync, they correctly send the `name_id` of the linked name as `name_id`, not `name_link_id` as `name_id`. e.g.

See #2745.

## Describe the solution you'd like 🎁

See #2745.

### Describe alternatives you've considered 💭

Eventually we will actually rename `name_id` to `name_link_id` properly which will make this much clearer.

### Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by roxy-dao** [comment]
Closed in #2756
