### ISSUE TITLE
Name merging: stock_line.supplier_id translator get actual name.id

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2750]
## Is your feature request related to a problem? Please describe 👀

name merging needs to make sure that when records with FK field `name_link_id` or similar sync, they correctly send the `name_id` of the linked name as `name_id`, not `name_link_id` as `name_id`. e.g.

See #2745.

## Describe the solution you'd like 🎁

See #2745.

### Describe alternatives you've considered 💭

Eventually we will actually rename `name_id` to `name_link_id` properly which will make this much clearer.

### Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by roxy-dao** [comment]
Closed in #2766

**Comment by Chris-Petty** [comment]
@roxy-dao if you could, can you please link the PR to the issue in github too? 
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/ce2598ce-70a1-4208-a262-8d26662291bd)

It's easier to do manually from the PR as it filters issues by repository. From the issue it makes you select the repo first for some reason.

That said if you want EXTRA fun, the linkage happens automatically for the base branch, but not all other branches. If you'd like to automate it generally, you could setup a github action that does it. [We have one for mSupply desktop](https://github.com/msupply-foundation/msupply/blob/master/.github/workflows/pr-issue-label-sync.yml) that you could copy. God iterating on yaml scripts is a pain though, hopefully you don't have to change much or at all. I guess first - @msupply-foundation/open-msupply-devs  any objection if issue labels automatically get copied to PRs?

**Comment by Chris-Petty** [comment]
... Worth a new issue if you want to do it. Speaking of which, if taking on the curse of developing scripts within yaml, it'd be really handy to have an action that automatically adds closed issues to the "Testers" project board. Github has an arbitrary limit of 5 automations of that fashion but I don't see why we could use a custom action.
