### ISSUE TITLE
Ability to export sqlite database on Android

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2751]
## Is your feature request related to a problem? Please describe 👀

For issues raised in production, it would be much easier (and less time consuming) for problem replication, if we were able to run the database snapshot locally in our dev environment

## Describe the solution you'd like 🎁

A way to export sqlite database for Open mSupply Mobile.

**Encryption ?**

Yes if possible, can specify password when zipping ?

**How to access this export on remote sites ?**

Maybe good to consult with support team @npendergrast @kahn-msupply. Would it be relatively simple to download data from any particular accessible folder with MDM ?

### Describe alternatives you've considered 💭

In production cannot access app data folder, so can't think of alternatives

### Additional context 💌

There is identical issue in: https://github.com/msupply-foundation/msupply-cold-chain/issues/285, I think same technique applies for both

**Comment by npendergrast** [comment]
Hi @andreievg, we haven't actually transferred files off devices directly with meMDM before, and there is no remote command to do this from a folder, as far as we are aware (or that I can see in their docs). However, @kahn-msupply and I are investigating possible config options to use file transfer from the device remote control feature (which will still be slightly cumbersome and maybe not suitable for a poor internet situation). We will ask meMDM if they have any other options for file transfer, and if not we could look at another app like dropbox for android

**Comment by nisha-dangol** [comment]
Hi @jmbrunskill ,
The download seems to work for desktop (mine is sqlite in both desktop & android), but fails for android apk. Issue submitted: #3172
