### ISSUE TITLE
Cold chain: Stuck state with dates in cold chain monitoring

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#2757]
## What went wrong? 😲

Clicking on the date (rather than the date picker), then clicking elsewhere on the screen will cause the 'to' date to be null.
There are some other ways to cause the date to become null, but this one is the easiest.

When the 'to' date is null, the app will get stuck in loading and fail to render. Refreshing the page does not fix this. The absent closing date is kept in the URL. While loading, the user is also unable to change the selected dates back.

The only way to fix is to manually delete the url date range and then refresh, or by accessing a different route via the lefthand side app bar and then navigating back.

https://github.com/msupply-foundation/open-msupply/assets/90807420/b4b72ae5-a749-4131-aa67-2f6045015588

## Expected behaviour 🤔
Shouldn't freeze in loading state when no end date is selected

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Open omSupply with coldchain. 
Deselect the to date.

**Comment by DhanyaHerath** [comment]
triage: @mark-prins thinks this is fixed, might need re-checking

**Comment by mark-prins** [comment]
bumping up priority as this is due to an infinite re-render

**Comment by AnushaUp** [comment]
Its nice having this alert if no value. Moving this to done. 👍
![Screenshot 2024-02-29 at 4 14 40 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/06444ac7-83f7-4edc-beb9-4c3f5a7ef74f)
