### ISSUE TITLE
Merging: use proper link name instead of just renaming the column

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2759]
## Is your feature request related to a problem? Please describe 👀
After the first merge of the `feature/merging` branch column renames should be removed, e.g:

```rust
    #[column_name = "name_link_id"]
    pub name_id: String,
```

The reason is that all query method exped a `name_id` but with the current code we use a `name_link_id`. Thus a query would fail for merged names/items.

Same changes should be applied for item_id/item_link_id

## Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by Chris-Petty** [comment]
I think I'll close this and make issues for all the other areas so we can track/split better
