### ISSUE TITLE
Cold chain: Breach notification bar does not appear until user logs out and back in

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2762]
## What went wrong? 😲

The breach notification bar is not appearing until the user forces some kind of refresh by e.g. logging out and back in 

https://github.com/msupply-foundation/open-msupply/assets/19318937/c716c6be-481f-48c7-9d12-d0bcd0e5e1e5

Also noticed that excursions didn't appear either: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/6a069205-6b4f-4e53-bc74-3d9d5ec7a5fa)

## Expected behaviour 🤔

Notification bar should appear as soon as a breach or excursion occurs. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Log into Open mSupply
2. Produce a breach on CCA
3. Observe Open mSupply

## Your environment 🌱

 - Version: V1.6.00-rc2 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
The excursions require config to be created - there is no default config, and the UI has not been done for creating config ( #2761 ). I had a default configuration in, but took it out. it's a bit messy having it in and the intention was to get the admin configuration finished.

For the breaches - the video isn't loading 😞

**Comment by adamdewey** [comment]
Aha! Ok that makes sense for excursions! 

Hmm, weird the video doesn't work - seems to be ok for me 🤔 

I'll think of another way to send it

**Comment by mark-prins** [comment]
update: refreshed this page and video showing.
will install on android and check breach notification. incidentally, refreshing the page should get the breach notification showing too.. tricky on android tho

**Comment by AnushaUp** [comment]
The breach notification was updated without logout and log in. **_PASSED_**

**Comment by adamdewey** [comment]
Hey @AnushaUp - that's ok if it's not instant, but will it appear if you leave the screen untouched? Or do you have to take some action for it to refresh?

**Comment by AnushaUp** [comment]
@adamdewey I actually touched the screen few times but didn't logout.

**Comment by adamdewey** [comment]
@AnushaUp - ah yeah ok great, I'd be keen to find out if it appears ok without the user doing anything if you get a chance sometime!

**Comment by AnushaUp** [comment]
@adamdewey Just done checking and the notification bar is updated by itself. But what if the multiple sensor are connected and breaches going on in both of them? Should the notification be updated for both of them?

**Comment by adamdewey** [comment]
@AnushaUp - that's great to hear. 

For multiple breaches I think it's ok if it doesn't update in real-time - the user will go to investigate the first breach and hopefully would check the other fridges at the same time. 

The main thing would be for the notification bar to remain there even if the first breach is acknowledged but the second one is not yet acknowledged.
