### ISSUE TITLE
Cold chain: Sensor filter not working for Log tab

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2763]
## What went wrong? 😲

For some reason the sensor filter has stopped working in the Log tab. 

https://github.com/msupply-foundation/open-msupply/assets/19318937/7483a993-bdef-44c6-a38d-1f11481717ad

Still seems to work ok in the Graph tab.

## Expected behaviour 🤔

Sensor filter should filter on sensor name. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open Log tab
2. Filter by sensor name

## Your environment 🌱

 - Version: V1.6.00-rc2
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Also, type filter in `Log` also seems to have stopped working

**Comment by mark-prins** [comment]
Grabbing this one too.. it's a clear bug. going into 1.6.00

**Comment by marthakeezy** [comment]
Tested on 1.6.02 - test is passed!

Entered the sensor's name under Chart - it's working as expected. Switched to the Log tab - tested both sensor names - working as expected. Test is PASSED! ✅

Uploading Screen Recording 2024-02-21 at 11.52.51 AM.mov…
