### ISSUE TITLE
Combine DatePickerInput and DateTimePickerInput

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2774]
## Is your feature request related to a problem? Please describe 👀
Break off from #2382

**Comment by nisha-dangol** [comment]
Tested in v1.6.2 exe

- [x] Make sure the picker for date is still working for filters - checked in Coldchain section: looks good
- [x] The others changes can be tested with programs - For programs, noticed such bug in encounter view: #3052
