### ISSUE TITLE
Internal Order - Select a line to delete, but error message comes up 'Please select a line to delete'

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#2776]
## What went wrong? 😲

When trying to delete internal orders with status. 'Draft' after selecting the line and pressing 'Delete' the error message comes on the left corner : 'Please select a line to delete'.

However the row is already selected.

https://github.com/msupply-foundation/open-msupply/assets/132425096/fdb8e069-14c4-47d4-9d70-7a5083dfd6c1

## Expected behaviour 🤔

Delete the draft Internal Order as soon as the button 'Delete lines' is pressed.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Internal Orders'
2. Click on any order with status = 'Draft'
3. Select the line and click on the option ' Delete lines'

## Your environment 🌱

Open mSupply Demo server https://demo-oms.msupply.org/r
 - Version: 1.6.00
 - Platform:
   - [ ] android (tablet)
   - [x] browser (Chrome)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by regotaina** [comment]
OBS: it's possible to delete using the button on the bottom right corner, within the Internal Order.

<img width="1356" alt="Screenshot 2024-01-19 at 1 35 59 PM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/1a1a21c7-9642-4cee-a8f5-7978f84cf356">

**Comment by DhanyaHerath** [comment]
I can reproduce this on the demo server @fergie-nz! Is it not behaving the same for you locally?

**Comment by nisha-dangol** [comment]
Tested in v1.7.0-rc1

## Tests
- [x] Go to 'Internal Orders'
- [x] Select any order/s with status = 'Draft'
- [x] Select dropdown > ' Delete lines'
- [x] See delete confirmation modal, select Ok
- [x] Line is deleted
