### ISSUE TITLE
Android app crashes when there is no network

### ISSUE THREAD

**Issue by kahn-msupply** [msupply-foundation/open-msupply#2784]
## What went wrong? 😲

Open mSupply for Android crashes if there is no network e.g not connected to Wifi or Wifi is turned off.

## Expected behaviour 🤔

Talking with Mark, we should have a notification for this:

_Alert the user that running in server mode with no network that Open mSupply isn't going to work because you need to connect to a mSupply instance to get set up - and the app will work once initial setup is complete._

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Turn off Wifi or disconnect from Wifi
2. Clear cache / data for Open mSupply on Android tablet
3. Start Open mSupply and click server
4. See Open mSupply crashes - back to home page

Note: Bug message appears after app crashes a couple of times

## Your environment 🌱

 - Version: v1.6
 - Platform: Android
 
## Screenhots

https://github.com/msupply-foundation/open-msupply/assets/132425100/c5ad3041-389c-40fb-93c0-7c9b2d9a13dd

![photo_2024-01-22_13-28-25](https://github.com/msupply-foundation/open-msupply/assets/132425100/a1142690-9d8e-45b3-89e1-7d46251be7ba)

**Comment by nisha-dangol** [comment]
Tested as part of #2867
