### ISSUE TITLE
 Requisitions: how to prevent users from finalising requisition when trying to create shipment

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#2787]
## Is your feature request related to a problem? Please describe 👀

Most people wants to click on `Confirm Finalised` once they're done supplying stock cause it feels like the next logical step. However, they are finalising the requisition that is no longer editable once finalised. 

Note: even during the Cambodia Demo, our demoer choose to do that so that does not only apply to end-users :-)

## Describe the solution you'd like 🎁

- Since the user seems to want to click on the `Status` button to create a shipment, suggestion would to have a "Create Shipment" button instead. 
- By clicking on `Create Shipment`, same behaviour as the former `Create Shipment` button (top right corner) that can be removed (or moved I guess) but well no need for 2 buttons. 
- In the background (as in not in the UI), requisition status would change from `new` to `confirmed` (see notes for alternatives). 
- if requisition partially supplied, the create button should still appear as the next default "Status". The Finalised status can still be present in the DDL 
- optional: when requisition is fully supplied, then the status "Finalised" is suggested as the next logical status. 

Notes: 
- if we have to keep the format: `Confirm  [Status]` then not sure if this would work (@mark-prins ?). Suggestion: Confirm supplied ? Confirm Processed ? Confirm Confirmed (NO!) ? None of the suggestion is as good as "Create Shipment" unfortunately. 

### Describe alternatives you've considered 💭

Move the `create shipment` button next to the `Confirm Finalised` button (right or left, personal preference for left) so that user can see both options of what to do with their requisitions. Once is shipment is created against the requisition, status can change to `Supplied`, `Processed` or `Confirmed` (NO!  NO! NO!)

### Additional context 💌

![Screenshot 2024-01-22 at 5 37 28 PM](https://github.com/msupply-foundation/open-msupply/assets/74992958/b03fece0-575f-4521-a8e6-2aef6df91eee)

### Moneyworks Jobcode 🧰

@DhanyaHerath ?

**Comment by richardmoizeau** [comment]
> Can we add this to alternative solutions: **1** -> a simple message when trying to finalise, that order is not fully supplied yet. **2** -> not sure, requires more thought, maybe a way to combine requisition and outbound shipment (like it's done in mobile, which i think works very well, it also implies combining requisition and inbound shipment)
> 
> >

Don't like 1, would prefer to solve it in the existing UI. I would need a bit more details about 2 to see if that's a good thing. What's wrong about the suggested options ? Any technical challenge ? Just to feed my thinking, not trying to push back. 

> What is done supplying stock ? Invoice created with placeholder lines, all quantity has been shipped, all quantity has been picked, some quantity has been picked etc .. ? Btw I remember a country with a workflow where shipment with placeholder lines = supply in requisition was enough to indicate that requisition should be finalised

All quantity has been shipped (sorry for the vague terminology).

**Comment by CarlosNZ** [comment]
We already have fairly substantial warnings for this. This banner shows up on the header of the requisition to begin with:

![Screenshot 2024-02-09 at 9 27 51 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/f5f420bf-5be5-4633-9e74-6872c302b191)

> Can we add this to alternative solutions: 1 -> a simple message when trying to finalise, that order is not fully supplied yet. 

This is already what happens:

![Screenshot 2024-02-09 at 9 27 56 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/aba822c1-4378-4c98-b3c8-604e8cf7f717)

Also, I'd be in favour of automatically finalising the requisition when the shipment is done (and all quantities are met). To me, going *back* to the requisition after sending the shipment seems like an awkward thing to remember to do and I can imagine would get forgotten a lot.

It'd be good to tie this logic together a bit more to minimise the number of steps the user has to remember to do in this process.

I'd be in favour of changing the "Confirm finalised" button to "Create shipment" (but with "Confirm finalised" still available in drop-down). Then when you click "Create shipment", if supplying the whole quantity, the shipment loads but *not* in a new tab. And once you send the shipment, if all quantity is supplied, the original requisition gets automatically finalised so you never have to remember to visit it again.

(And if full quantity *not* supplied, then maybe you get an alert after sending the shipment that some items in requisition remain un-sent?)

Anyway, this probably needs further discussion as it seems there's lots of possible ways forward, happy to do that next week when we're all in the office?

**Comment by andreievg** [comment]
@richardmoizeau 

> What's wrong about the suggested options ? 

I was just trying to see what the minimum we can do to do a targeted fix. I was questioning the main 'reason' for the problem, especially since our own users are not sure about the process, and there is already a warning.

> Any technical challenge ?

It does make it a bit more involved, but not too much extra. And i am not against your suggested solution, just wanted to add an alternative

> Anyway, this probably needs further discussion as it seems there's lots of possible ways forward, happy to do that next week when we're all in the office?

I agree about a meeting for next week

**Comment by mark-prins** [comment]
My recollection is that we decided to move the button

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply desktop `v2.1.0-IA-test-2`


- [ ] Open a response / customer / distribution Requisition
- [ ] try the button
