### ISSUE TITLE
Improve integration speed (sqlite)

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2790]
From https://www.sqlite.org/faq.html#q19:

>Actually, SQLite will easily do 50,000 or more [INSERT](https://www.sqlite.org/lang_insert.html) statements per second on an average desktop computer. But it will only do a few dozen transactions per second. Transaction speed is limited by the rotational speed of your disk drive. A transaction normally requires two complete rotations of the disk platter, which on a 7200RPM disk drive limits you to about 60 transactions per second.

Initially we integrate every record in a transaction to be able to catch errors for a particular record and then continue with the integration. But I don't believe this is true anymore so we don't need to have every record in a transaction.

I experimented with the following changes, batching up integration records into transactions. Integrating coldchain records is much faster. However, there seems to be an independent issue integrating many documents...

`let start_nested_transaction = false;` in `IntegrationRecords::integrate()` and:

```rust
pub(crate) fn translate_and_integrate_sync_records(
        &self,
        sync_records: Vec<SyncBufferRow>,
        translators: &Vec<Box<dyn SyncTranslation>>,
        mut logger: Option<&mut SyncLogger>,
    ) -> Result<TranslationAndIntegrationResults, RepositoryError> {
        let step_progress = SyncStepProgress::Integrate;
        let mut result = TranslationAndIntegrationResults::new();

        // Record initial progress (will be set as total progress)
        let total_to_integrate = sync_records.len();

        // Helper to make below logic less verbose
        let mut record_progress = |progress: usize| -> Result<(), RepositoryError> {
            match logger.as_mut() {
                None => Ok(()),
                Some(logger) => logger
                    .progress(step_progress.clone(), usize_to_u64(progress))
                    .map_err(SyncLoggerError::to_repository_error),
            }
        };

        let mut integration_batch = Vec::<IntegrationRecords>::new();
        for (number_of_records_integrated, sync_record) in sync_records.into_iter().enumerate() {
            let translation_result = match self.translate_sync_record(&sync_record, &translators) {
                Ok(translation_result) => translation_result,
                // Record error in sync buffer and in result, continue to next sync_record
                Err(translation_error) => {
                    self.sync_buffer
                        .record_integration_error(&sync_record, &translation_error)?;
                    result.insert_error(&sync_record.table_name);
                    warn!(
                        "{:?} {:?} {:?}",
                        translation_error, sync_record.record_id, sync_record.table_name
                    );
                    // Next sync_record
                    continue;
                }
            };

            let integration_records = match translation_result {
                Some(integration_records) => integration_records,
                // Record translator not found error in sync buffer and in result, continue to next sync_record
                None => {
                    let error = anyhow::anyhow!("Translator for record not found");
                    self.sync_buffer
                        .record_integration_error(&sync_record, &error)?;
                    result.insert_error(&sync_record.table_name);
                    warn!(
                        "{:?} {:?} {:?}",
                        error, sync_record.record_id, sync_record.table_name
                    );
                    // Next sync_record
                    continue;
                }
            };

            integration_batch.push(integration_records);
            if integration_batch.len() >= 500
                || number_of_records_integrated + 1 == total_to_integrate
            {
                self.connection
                    .transaction_sync(|connection| {
                        for integration_records in &integration_batch {
                            // Integrate
                            let integration_result = integration_records.integrate(connection);
                            match integration_result {
                                Ok(_) => {
                                    self.sync_buffer
                                        .record_successful_integration(&sync_record)?;
                                    result.insert_success(&sync_record.table_name)
                                }
                                // Record database_error in sync buffer and in result
                                Err(database_error) => {
                                    let error = anyhow::anyhow!("{:?}", database_error);
                                    self.sync_buffer
                                        .record_integration_error(&sync_record, &error)?;
                                    result.insert_error(&sync_record.table_name);
                                    warn!(
                                        "{:?} {:?} {:?}",
                                        error, sync_record.record_id, sync_record.table_name
                                    );
                                }
                            }
                        }

                        // round down to closest step size
                        record_progress(
                            (total_to_integrate - number_of_records_integrated - 1)
                                / PROGRESS_STEP_LEN
                                * PROGRESS_STEP_LEN,
                        )?;

                        Ok(())
                    })
                    .map_err(|e: TransactionError<RepositoryError>| e.to_inner_error())?;

                integration_batch.clear();
            }
        }
        assert!(integration_batch.is_empty());

        // Record final progress
        record_progress(0)?;

        Ok(result)
    }
```

TODO:
- [ ] Remove start_nested_transaction (?)
- [ ] Benchmarking and testing for sqlite and postgres

**Comment by andreievg** [comment]
Hi i think it could be a bit simpler:

From memory, in sqlite a transaction won't be aborted when there is an error, but in postgres it would be. Thus we added inner transaction. But inner and outer transaction was too slow for initialisation, so we completely remove transaction.

I think for initialisation we can just have transaction for sqlite. And only do inner transaction for postgres. Both can be controlled with !cfg() macro btw, and this would keep the impact to minimum (complexity wise). 

I did a test, and yeah super slow for transaction in sqlite, but very little different in postgres. Here is a branch to validate the above:

https://github.com/msupply-foundation/open-msupply/compare/develop...develop(Checking-transactions-in-database)

**Comment by clemens-msupply** [comment]
thanks for the benchmark!

Do you remember if nested tx were slow for sqlite or for postgres? or both?

**Comment by andreievg** [comment]
> Do you remember if nested tx were slow for sqlite or for postgres? or both?

I am pretty sure it was postgres, here is another one: https://github.com/msupply-foundation/open-msupply/compare/develop(Checking-transactions-in-database)...develop(Checking-transactions-in-database)(Nested-transaction)

Very small difference for sqlite. From 8 to 13 seconds ( + 5 seconds) for postgres (didn't check how it scales though, but i guess that answers if it was sqlite or postgres that was slow for nested tx)

**Comment by clemens-msupply** [comment]
Another problem I noticed is that we report the progress by writing and reading the progress into the DB. However, if we do everything in a transaction we don't see any progress till we finished the main transaction. Wonder if we should track the integration progress in memory instead...

**Comment by clemens-msupply** [comment]
Waiting for integration to finish, so time to write down some more thoughts ;)

@Chris-Petty had the idea to split the integration process into multiple transactions, e.g. integrate all names, then all stores, etc.
Think this could also solve the progress reporting problem as described above because the UI has a change to query the progress between integration steps...

However, we would have to take care for records like invoices and invoice_lines, e.g. if we have two transactions for them the user might temporarily see a finalized invoice without any lines! So this would require some extra logic... (or we ignore it? or trigger a UI refresh after sync?).

For some records like sensor data it could even be nice to be able to integrate them into multiple batches. But maybe this could be done if this becomes a problem, i.e. if syncing sensor data blocks the UI.

**Comment by Chris-Petty** [comment]
For invoices and lines my wacky thought additionally was doing a transaction for each invoice. Buttt hard to know that relationship in the sync_buffer unless central server `sync_out` included a parent ID, so that sync_buffer could have it too.

**Comment by clemens-msupply** [comment]
Yes we could find invoice with matching lines and then batch them up, that would probably be ideal. Question is how complex we want to go? probably good to do some benchmarking before going down to this level. Having lots of lots of invoices to integrate might not be that common?

**Comment by andreievg** [comment]
> Waiting for integration to finish, so time to write down some more thoughts ;)

haha

>  However, if we do everything in a transaction we don't see any progress till we finished the main transaction. 

I thought we can do it in separate connection, but realised in sqlite only one writer at a time right ?

> @Chris-Petty had the idea to split the integration process into multiple transactions, e.g. integrate all names, then all stores, etc.

Hmmm i wonder what we are trying to solve here, is the the integration progress ? If it's so then it can be solved by caching sync log row  https://github.com/msupply-foundation/open-msupply/compare/develop...develop(Cache-sync-log) (haven't checked but should work ¯\_(ツ)_/¯) 

So the integration speed should only be a problem during initialisation right ? (unless we are adding store to a site, which becomes another problem, since database would be locked)

During initialisation UI would be blocked any way ?

So I propose we go with the (https://github.com/msupply-foundation/open-msupply/issues/2790#issuecomment-1922772371). + the sync log caching above  

Also propose we up the priority to get this into 2.0 ?

**Comment by clemens-msupply** [comment]
> So the integration speed should only be a problem during initialisation right ? (unless we are adding store to a site, which becomes another problem, since database would be locked)

Yes, initialization is probably the main slowdown right now.

Think having a cached progress record in memory should solve the main problem. I.e. we can wrap the initial integration into a transaction (sqlite) and still get progress updates during initialization.

This issue is still on my list so if nobody beat met to it, I plan to have a look at some point...

> During initialisation UI would be blocked any way ?

Yes think this would be the next step to look into. If it becomes a problem, e.g. too many "db locked" errors, we could try to split the integration into multiple transactions, giving other requests the change to access the DB (just sqlite).

**Comment by andreievg** [comment]
When this is fixed, we need to check datafile that Mark G tried to sync and make sure that the problem he experienced with slowness of initialisation is addressed enough
