### ISSUE TITLE
Rename Android app from openmsupply-client to Open mSupply

### ISSUE THREAD

**Issue by kahn-msupply** [msupply-foundation/open-msupply#2793]
## Describe the solution you'd like 🎁

Request to see if we can update the name of the Android app to be something like Open mSupply - currently it shows as openmsupply-client. Would look more user friendly, and we can't change this from MeMDM.

### Additional context 💌

![Screenshot 2024-01-23 at 1 58 32 PM](https://github.com/msupply-foundation/open-msupply/assets/132425100/48e1f0ab-118b-4bb5-8591-c86cbce917fa)

![photo_2024-01-23_14-00-02](https://github.com/msupply-foundation/open-msupply/assets/132425100/255e9f08-6975-4aa0-853c-d35ce279558e)

**Comment by nisha-dangol** [comment]
Moving to Done as I already see the app name as Open mSupply in Android.
