### ISSUE TITLE
Cannot send the stocks to oms site having packsize in decimal form mSupply

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#2797]
## What went wrong? 😲

Cannot send the stocks to oms site having packsize in decimal form mSupply

![Screenshot 2024-01-23 at 15 39 30](https://github.com/msupply-foundation/open-msupply/assets/117138852/9891a3d5-97c8-4a03-9337-997c8b54000f)

## Expected behaviour 🤔

The lines having decimal packsize should sync to OMS

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Sync Setup between OMS and mSupply
2. Send stocks having decimal packsize from mSupply to open mSupply by CI
3. Confirm the CI
4. Sync
5. Open the OMS store
6. Look for Inbound shipments
7. And open up the Inbound Shipment
8. See the lines are not synced (BUG)

Video Reference:

https://github.com/msupply-foundation/open-msupply/assets/117138852/020d22b8-6835-4e90-83ea-83a57be529c0

## Your environment 🌱

 - Version: 
 - Platform:
   - browser (extra points if you tell us which one)
   - desktop (windows)

**Comment by roxy-dao** [comment]
Related #2817

**Comment by ujwalSussol** [comment]
I am not seeing the need to have have `packsize` as decimal points ....   we should perhaps restrict this so that it is compatible with openmSupply.

**Comment by roxy-dao** [comment]
Closing in favour of #2663
