### ISSUE TITLE
v1.6.00 Release Documentation

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2802]
## Is your feature request related to a problem? Please describe 👀
Update the docs for [v1.6.00](https://github.com/msupply-foundation/open-msupply/releases/tag/v1.6.00)

* [x] Plugin framework. Mention that front end plugins are possible and direct to internal docs
* **Filters**
  * [x] View stock ( can now filter by master list and location )
  * [x] Location ( can filter location name and on hold )
  * [x] Enrolment ( patient last name, program name, start date time range, status )
  * [x] Temperature breach
  * [x] Temperature log
  * [x] Patients
  * [x] Outbound shipment
  * [x] Requisitions
  * [x] Inbound shipment
  * [x] Internal orders
* [x] Dashboard links : update screenshots
* [x] Logout confirmation
* [x] Log viewer on desktop
* [x] Cold chain UI updates? screenshots?
* [x] Sync page screenshots
* [x] Language support? do we mention this? If so, add Russian.

**Comment by nisha-dangol** [comment]
Have created [a doc here](https://docs.google.com/spreadsheets/d/1MGW4v2BoaYLToUKTTglBrsrkBBQl-d079rtEeDhqXsk/edit#gid=915349711) to track the v1.6 issues tested so far
