### ISSUE TITLE
GraphQL codegen generates unrunnable code

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2812]
## What went wrong? 😲
 
Some changes to the operations.graphql files have resulted in 
* code that cannot run
* code that fails our linting pre-commit

**/client/packages/invoices/src/OutboundShipment/api/operations.graphql**

The fragment import path is incorrect

```
import { StockOutLineFragmentDoc } from '../../../../../../packages/invoices/src/StockOut/operations.generated';
```

**/client/packages/invoices/src/Prescriptions/api/operations.graphql**

The fragment import path is incorrect

```
import { StockOutLineFragmentDoc } from '../../../../../../packages/invoices/src/StockOut/operations.generated';
```

**/client/packages/invoices/src/StockOut/operations.generated.ts**

This operations file only has fragments; graphql codegen doesn't cope with this, and adds the `defaultWrapper` function which isn't used and fails linting.

**client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts**

The fragment import path is incorrect

```
import { NameRowFragmentDoc } from '../../../../../../packages/system/src/Name/api/operations.generated';
```

**client/packages/system/src/Stock/api/operations.generated.ts**

The fragment import path is incorrect

```
import { LocationRowFragmentDoc } from '../../../../../../packages/system/src/Location/api/operations.generated';
```

## Expected behaviour 🤔
Running `yarn generate` should generate good code.

I've been unable to force the fragment imports to work correctly when importing from another file.
The closest I've got is to set the `importAllFragmentsFrom` prop (ref: [near-operations-file-preset docs](https://the-guild.dev/graphql/codegen/plugins/presets/near-operation-file-preset)) and move _all_ fragments into a single file.

This file would then also require a dummy query in it, so that the linting passes.

Other references:
* [graphql-code-generator source](https://github.com/dotansimha/graphql-code-generator/tree/master)
* [Fragment import issue](https://github.com/dotansimha/graphql-code-generator/issues/4307)
* GraphQL code generator [typescript reference](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run `yarn generate`

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by Chris-Petty** [comment]
![image](https://github.com/user-attachments/assets/8ef7a14e-e9f3-4289-bd7b-80c7370c60e5)
👀

**Comment by lache-melvin** [comment]
Yeah, it still happens from time to time @Chris-Petty 😢 Usually comes right if you delete the file and run a clean generate?

**Comment by Chris-Petty** [comment]
> Yeah, it still happens from time to time @Chris-Petty 😢 Usually comes right if you delete the file and run a clean generate?

Did so after the second attempt!
