### ISSUE TITLE
Review f/e bundle size

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2813]
## What went wrong? 😲
 
What's up with the bundle size? It was much lower than this. Has something blown the size out?

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/035c4a0a-4530-40d4-92a8-a0490a967ddb)

## Expected behaviour 🤔
A more reasonable size than 8MB. At the least some confidence that all of that is required.

**Comment by DhanyaHerath** [comment]
do alongside/after https://github.com/msupply-foundation/open-msupply/issues/2814?

**Comment by roxy-dao** [comment]
Dup of #1957

**Comment by mark-prins** [comment]
oh, forgot about that. nice find!
This issue was an observation that the size has blown out - the original issue is to make further improvements. this issue could be a comment on that one, though the intention is slightly different so I think ok to keep the two

**Comment by mark-prins** [comment]
Found the offending commit! #2568 One that I had done..
