### ISSUE TITLE
Location filter doesn't retains all list when Backspace is pressed 

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#2822]
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply/assets/117138852/b8a3c682-4abd-465b-9178-aeac56d9e053

![Screenshot 2024-01-24 at 15 32 12](https://github.com/msupply-foundation/open-msupply/assets/117138852/30bfba7a-16d0-4eec-89e3-0c5f2b7dd0e4)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open mSupply
2. Go to Inventory ->Locations
3. Search for existing location by name so only one location would get filtered
4. Now press long backsapce key so that all the search field clears up
5. All the locations would not pop-up on the field (BUG)

## Your environment 🌱
<v1.6>
 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by mark-prins** [comment]
I agree with you @santoshkhanal12 - there is a bug here.
I've got 15 locations. If I filter name by `row` then I get 3. when I backspace, the filter is cleared but the URL still has `r` in it, and so the list only shows 10 locations

https://github.com/msupply-foundation/open-msupply/assets/9192912/3e3ba99e-4dbf-4cf6-9d2e-93147b326fc5

**Comment by roxy-dao** [comment]
Closed in #2824

**Comment by nisha-dangol** [comment]
Moving to Done as can't replicate the original issue anyways, in v1.6.2 exe
