### ISSUE TITLE
UI issue: Check box and Symbol overlapped

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#2823]
## What went wrong? 😲
UI issue: Check box and Symbol overlapped

![Screenshot 2024-01-24 at 17 08 45](https://github.com/msupply-foundation/open-msupply/assets/117138852/a2b3becc-6c4f-4087-9042-b1039e12f63f)

## Expected behaviour 🤔

No overlapping of the text and symbol

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. OMS
2. Create internal Order form mSupply to OMS site
3. See the customer requisition on. the remote site
4. See the list
5. See the symbol and checkbox overlapped in top side of the window (BUG)

## Your environment 🌱
v1.600
 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by roxy-dao** [comment]
Requisitions has no vertical scroll 😅

**Comment by CarlosNZ** [comment]
I'm not seeing this on my system:
![Screenshot 2024-02-12 at 11 19 00 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/4f6ea813-ba59-423f-8582-3e98eb5b4cb7)

Anyone else seen it? Was this in the browser, or Electron app?

**Comment by roxy-dao** [comment]
> I'm not seeing this on my system: ![Screenshot 2024-02-12 at 11 19 00 AM](https://private-user-images.githubusercontent.com/5456533/303950990-4f6ea813-ba59-423f-8582-3e98eb5b4cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTA3NzIsIm5iZiI6MTcwNzY5MDQ3MiwicGF0aCI6Ii81NDU2NTMzLzMwMzk1MDk5MC00ZjZlYTgxMy1iYTU5LTQyM2YtODU4Mi0zZTk4ZWI1YjRjYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMjIyNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQyZmIxNWI4Y2ZhZTVjMDk3NGJkMzUyYmViOGIyODZlZDljODRmNDhlZjRiODY2ZGMzZGY5ZDFlYzBkNzkwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Soe17m0XDKhujW5SJs7_87Eu-sa13-5zriggDrpOO_o)
> 
> Anyone else seen it? Was this in the browser, or Electron app?

Are you looking at Requisitions? It's only happening in Requisitions because there's no vertical scroll as I mentioned above. Example from demo.
![Screenshot 2024-02-12 at 11 28 18](https://github.com/msupply-foundation/open-msupply/assets/61820074/fcc3cbcc-236a-4c85-82cf-a9d69e5ca992)

**Comment by CarlosNZ** [comment]
> Are you looking at Requisitions? It's only happening in Requisitions because there's no vertical scroll as I mentioned above. Example from demo.

Ah, weird, I can see it in Chrome, but it's fine in Firefox (more often the other way round). 

What do you mean about the vertical scroll? I get the vertical scroll when it's needed (i.e. list too long for the viewport), which is the same on all tables.

![Screenshot 2024-02-12 at 11 38 46 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/502ccca8-a43d-44da-b57e-550844153196)
