### ISSUE TITLE
Schedule next appointment after current appointment has been marked as visited

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2855]
Its a common workflow to schedule the next encounter after the current visit has been saved with status "Visited". Moreover, the latest encounter might contain information about when the next encounter is due to be scheduled. For example, if the previous encounter contains an "end of supply" date the next encounter should be scheduled using the date.

- [x] #2856
- [x] #2857

**Comment by roxy-dao** [comment]
Can this be closed since both issues linked to this is completed?
