### ISSUE TITLE
Make scheduling a follow-up encounter easier

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#2856]
## Solution 1:

When an encounter is the latest of its kind, e.g. HIVCareEncounter, and the status is "Visited" show a "Schedule Encounter" button:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/0cc6930c-b0fd-4882-94ca-f551dfee1dec)

Clicking this button opens the "create encounter" modal having the encounter type pre-set.

## Solution 2:
When marking an encounter as "Visited" should we actually go back to the patient's encounter list view instead of staying on the encounter? Then we could just autoselect the "Add encounter" selection button (or add something more obvious?):

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/bad21400-2418-4a76-9f1c-11d5cde962bc)

@richardmoizeau or @anisha-msupply any better idea, preferences, etc?

**Comment by richardmoizeau** [comment]
I'll let @anisha-msupply decide :-)

**Comment by richardmoizeau** [comment]
Have asked @anisha-msupply to check and let you know today. Thanks @clemens-msupply
