### ISSUE TITLE
Inbound Shipment: notification box always refers to status 'New', even when transaction has other status

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#2859]
## What went wrong? 😲

This came as a support question on the Solomon Islands chat on Telegram.

The notification box says ' changing status from 'NEW'  ' even when the status is 'Delivered' or 'Verified'. 

![telegram-cloud-photo-size-1-5026052098390863030-y](https://github.com/msupply-foundation/open-msupply/assets/132425096/e73b6495-8e0c-47ad-84f8-5259cc8d566a)

I also tested on the demo server:

![telegram-cloud-photo-size-1-5026052098390863031-y](https://github.com/msupply-foundation/open-msupply/assets/132425096/27b66e2f-babf-44dc-9c7d-405169cc8f95)

## Expected behaviour 🤔

The notification box should refer to whatever status is being changed from and to. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inbound Shipment'
2. Create a new shipment
3. Add at least 1 item and click on 'Confirm delivered'
4. Click on 'Confirm Verified' 
5. The notification box will appear - See error

## Your environment 🌱

 - Version: 1.6.0
 - Platform:
   - [x] android (tablet)
   - [x] browser (Chrome)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment]
The message is correct and in itself it doesn't require changing.
Could you please split the translation string out though and add a condition to the code:

Currently:
`messages.confirm-inbound-status-as`: `Confirm status as $t({{status}})?\nNote: changing from 'New' will remove any lines with zero quantity.`

Change to this:

`Confirm status as $t({{status}})?`

 and add a new key:

`\nChanging from 'New' will remove any lines with zero quantity.`

which is only shown to the user if the current status is `NEW`

**Comment by nisha-dangol** [comment]
Tested in v1.7.0-rc1 exe

### Tests
- [x] Go to 'Inbound Shipment'
- [x] Create a new shipment
- [x] Add at least 1 item and click on 'Confirm delivered'
- [x] TEST: See the "Note: changing from 'New'..." text
- [x] Click on 'Confirm Verified'
- [x] TEST: Only see the "Confirm status as Verified" message
