### ISSUE TITLE
Add sensor type to detail modal

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2861]
## Is your feature request related to a problem? Please describe 👀
Coming from [this comment](https://github.com/msupply-foundation/open-msupply/issues/2717#issuecomment-1916670765)
It was noticed that we have the type in the list view, but then don't show it in the detail view.

## Describe the solution you'd like 🎁
Please add it in.

### Moneyworks Jobcode 🧰

`OMS:COLC`

**Comment by AnushaUp** [comment]
# Testing
Tested in `omSupply V1.7.00`
- [ ] Open sensor detail modal.
- [ ] See that sensor type is not available.
