### ISSUE TITLE
Android: issues running offline after initialisation

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2867]
## What went wrong? 😲
 

The changes in #2482 and then in #2622 have resulted in some issues when working on android offline:

Turn off Wifi and the store can't be accessed (if Open mSupply is open)
Turn off Wifi and Open mSupply does not open (if the app has been closed in task manager)

![telegram-cloud-photo-size-1-5030555698018233796-y](https://github.com/msupply-foundation/open-msupply/assets/9192912/b6f2663c-12cc-42b4-8a87-012524626c43)

![telegram-cloud-photo-size-1-5030555698018233797-y](https://github.com/msupply-foundation/open-msupply/assets/9192912/18fedb1f-903c-4ddc-a3cd-a0376783498b)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Enable wifi and connect to a network
2. Initialise tablet in server mode
3. Disable wifi

## Your environment 🌱

 - Version: 
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by nisha-dangol** [comment]
## Testing
Tested in v1.6.2 apk

### One
- [x] enable network
- [x] start the app and select server mode
- [x] initialise the tablet
- [x] login
- [x] disable network
- [x] try to do something

### Two
- [x] Close the app
- [x] disable the network
- [x] open the app
