### ISSUE TITLE
Ensure Android works with latest rust

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2883]

**Comment by clemens-msupply** [comment]
Work with NDK:  26.1.10909125 and Rust 1.75.0 on Linux (update NDK_HOME and best delete old ndk version to make sure you use the correct  version)

**Comment by clemens-msupply** [comment]
I also create a branch which removed the openssl depenencies:

2883-android-remove-openssl

This was a problem on mac as well...
