### ISSUE TITLE
CI server tests failing: No space left on device

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#2900]
## What went wrong? 😲
 

Server tests are failing to build in CI due to the following error:

![Screenshot 2024-02-07 at 3 02 43 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/2a9e2cb1-4828-4e0c-826d-d6eb5f3c9b3a)

Probably need to clear some cache?

## Expected behaviour 🤔

CI tests have enough space to run... and hopefully pass 😅 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open a PR
2. See server-tests workflow fail with above error

## Agreed solution
Implement a test runner locally using an on-premise machine. The exact details of this are up to the implementer!

## Your environment 🌱

- CI

**Comment by andreievg** [comment]
Andrei, [8/02/2024 at 12:30:58 PM]:
at some point we would exceed the limits of free github action runners

either with target directory being too big or with tests having too many databases (btw cargo builds a binary for each test)

For now we can break up tests by package/crate, I think, in it's own action. I think it's worth exploring hosting our own runners though

Or finding a paid solution, one that's kind to non for profits maybe

**Comment by Chris-Petty** [comment]
We do have a m2 mac mini here that I suspect is mostly idle, part of the intent was to set it up as an action runner 😃. I did wonder the other day if it's significant s a security vector we have to be wary of though - running arbitrary code on a computer on our company network? Maybe the github actions runtime has a tight container for it?

**Comment by clemens-msupply** [comment]
Haven't looked at it at all but I saw this "Incremental Rust builds in CI" headline earlier this week: https://earthly.dev/rust

**Comment by andreievg** [comment]
Investigate using our own running, maybe create one in our cloud provider

**Comment by lache-melvin** [comment]
Self hosted seems to have resolved this, closing 🙏
