### ISSUE TITLE
Cannot allocate expiry message not clear enough

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#2917]
## What went wrong? 😲
People think you can't allocate expired lines because the message isn't clear enough. (Request from Mark G)

## Expected behaviour 🤔
Change `Some stock lines are expired and cannot be allocated` to `Some stock lines are expired and cannot be auto-allocated` wherever relevant

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version:

**Comment by CarlosNZ** [comment]
Or perhaps: "Some stock lines are expired and will not be auto-allocated"?

Because they *could* be if we wanted to.

**Comment by nisha-dangol** [comment]
Tested in v1.7.0-rc2 exe
I do see the change as below:
<img width="984" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/3bac563d-f1ce-439d-8b1b-b60d7db96b63">

Also, good to notice/see that expired stocks aren't allowed to issue (unless the user forcefully/manually decides to)
<img width="980" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/9d601eed-bfcc-4b3a-8fb2-254aee23bd60">
