### ISSUE TITLE
Returns -- supplier returns detail view

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#2920]
This is the page that loads after the items have been selected from the initial modal

(Similar to "Outbound shipment" UI)

Use mock API response

Broken out into further issues:
- [x] https://github.com/msupply-foundation/open-msupply/issues/3010
- [x] https://github.com/msupply-foundation/open-msupply/issues/3011
- [x] https://github.com/msupply-foundation/open-msupply/issues/3012
- [x] https://github.com/msupply-foundation/open-msupply/issues/3013
- [x] isDisabled hook
- [x] groupByItem functionality, including lines hook (lines also needed by StatusChangeButton)
- [x] enable delete mutation
- [x] Log tab

**Comment by lache-melvin** [comment]
Capturing quickly as still to do here!

- [ ] isDisabled hook
- [ ] groupByItem functionality, including lines hook (lines also needed by StatusChangeButton)

**Comment by lache-melvin** [comment]
Completed across other PRs
