### ISSUE TITLE
DateInputHandler called repeatedly for all patients in list - rendering issue

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#2923]
## What went wrong? 😲
Date input handler is being called for all patients in a list.

## Expected behaviour 🤔
Only call input handler when required.
In this case when modal is opened for a specific patient, or the detail view of that patient is rendered.

## How to Reproduce 🔨
Check out branch: [#2923](https://github.com/msupply-foundation/open-msupply/tree/%232923-dateInputHandler-called-repeatedly)
Go to patient list
See console logs of dateInputHandler called when not yet needed.

**Comment by DhanyaHerath** [comment]
@clemens-msupply to check
fyi @fergie-nz it wasn't closed yet :)

**Comment by roxy-dao** [comment]
Closing since doesn't seem to be an issue anymore
