### ISSUE TITLE
Testing: Patient Programs module test

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2925]
## Details
There are [way too many issues](https://github.com/msupply-foundation/open-msupply/issues?q=is%3Aissue%20is%3Aclosed%20label%3Aprograms%20project%3Amsupply-foundation%2F32) closed for `programs` in Testers Board, which will be moved to `Done` after this issue/test is complete which will cover general programs module testing following the [Programs user-guide/doc](https://docs.google.com/document/d/1-ePAWcv2hFvaF9iSzlWylrpjs8LWDk7DoRN9Z5RLBgU/edit#heading=h.wtl5tfuhum8e)!

**Note**: The test cases/results will be mentioned below in comments as the testing progresses.

## Additional
https://trello.com/c/H9LVWQSj/200-programs-general-testing

## Your environment 🌱

 - Version: v1.6.2
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by nisha-dangol** [comment]
# Open mSupply Patient Programs
## Patient Registration
- [ ] Go to the “Patients” menu and click the “New Patient” button in the right top corner.

### Entering of basic patient information such as name or date of birth
- [ ] A patient window open with the following fields
   - [ ] National ID (NID)
   - [ ] NUIC
   - [ ] First Name
   - [ ] Last Name
   - [ ] DoB
   - [ ] Gender
   - [ ] Address
   - [ ] Phone
- [ ] The National ID number needs to be equal to 10 character long (there is no sign of checking for duplicates)

### Search for existing similar patients to avoid duplicated patient entries
- [ ] The `Ok&Next` button gets enabled only after you enter values in either First or Last name
- [ ] If any existing patient matches the info as entered while creating, it should up in the `Search results` 
- [ ] For patients found that belong to homestore(logged-in store), see the home icon
- [ ] For patients found that belong to other store(other than logged-in store), see the download icon
   - [ ] On downloading the patient, it'll ask to fetch patient details from the server

### Entering full patient information and finalising the patient
- [ ] In case of no any existing patients found, opt to `Ok&Next` to proceed
- [ ] Only after mandatory fields (NID, NUIC, name, DoB) are entered, the `Create` button is enabled which lets us save the patient


## Patient List
- [ ] Click on each column header to test the sorting
   - [ ] Sorting is ascendent or descendent.
- [ ] Test the filter fields
   - [ ] Search by First name - Find patients that have the string combination you put in their first name
   - [ ] Search by Last name - Find patients that have the string combination you put in their last name
   - [ ] Search by id - Find patients that have the string combination you put in the National ID or NUIC 
   - [ ] Try multiple fields search, each value you put in a field should combine to reduce your selection     
 - [ ] Double click on a patient to see it's information
     - [ ] You should see it's information
         - [ ] It would not work for patient you have not created and doesn't have documents created (Patient data, Encounter or Program). For example a patient coming from the cloud server.
     - [ ] You are able to edit the patient details.
     - [ ] When clicking Ok the details are saved.


## Patient Details View
- [ ] Selecting a patient from the patient list will open the patient details view
- [ ] There are four tabs:
   - [ ] “Details” shows the general patient information 
   - [ ] “Programs” shows a list of program enrolments for the selected patient
   - [ ] “Encounters” shows a list of encounters for the selected patient
   - [ ] "Contact tracing" shows a list of 

## Patient Program Enrolment
- [ ] To enrol a patient into a program select the “Add Program” button in the top right corner of the patient details view.
- [ ] This will open a dialog with a list of available patient programs
- [ ] Already enrolled programs are greyed out and can’t be selected
- [ ] To enrol a patient into a program select the desired program from the list
- [ ] This opens the program enrolment document where program specific information can be entered
Note: The content of the program enrolment document is program specific, i.e., depends on the schema you loaded while running the FC code during setup

## Patient Program Encounters
- [ ] Only after a patient is enrolled in a program, an encounter for this program can be created
- [ ] To do so select “Add Encounter” through the drop-down menu in the right top corner
- [ ] This will open a dialog to create an encounter
- [ ] First, the type of encounter needs to be selected, i.e. which program enrolment the encounter is associated with.
- [ ] Secondly, the encounter date must be selected.
- [ ] The encounter date can be in the past, e.g. for entering finished encounter, or in the future, e.g. to schedule an encounter (aka appointment).
- [ ] Once an encounter is created, the full encounter document will open to enter encounter details
- [ ] Every encounter has an encounter header where common encounter details can be updated, e.g. the clinician who handles the encounter or the encounter status
Note: The content of the encounter document is program specific and depends on the schema contents at the time of setup.

### Encounter Details
- [ ] An encounter can have three statuses:
- “Pending” (depending on the current date this could mean the encounter is scheduled, or the encounter has been missed)
- “Visited”
- “Cancelled”
- [ ] The “More” button in the right top of the encounter detail view opens a column with additional encounter information such as a summary of previous encounters and the option to add an encounter note
- [ ] Beside the Status, there is delete ico to delete the encounter


### Example: PNG HIV Program/Encounter8
In this test-suite, details for the PNG specific HIV programs and encounters are given: [the contents can vary for different programs/encounters]
For this, there are currently two HIV programs available: 
a. HIV Testing Program
- [ ] When enrolling the patient to HIV Testing Program, it will opt you to enter Enrolment date as expected
- [ ] Additionally, there's also option to add patient notes if wanted
- [ ] After enrolling to program, you can now create an encounter for this through the drop-down menu in the right top corner
- [ ] On creating new encounter, there is additional fied to add notes and save
- [ ] The HIV Testing & Counselling encounter is divided into the following sections:
   - [ ] General
   - [ ] Risk Behaviour
   - [ ] Other Services Received
   - [ ] Informed Consent
   - [ ] HIV Testing

b. HIV Care & Treatment
- [ ] When enrolling the patient to HIV Care & Treatment, it will opt you to enter Enrolment date as expected
- [ ] Additionally, there are also other fields like Program ID, which you can generate and add patient status history and other fields related to the HIV factors, like test types, risk groups, mother details, treatment supporter, referral details and patient notes
- [ ] After enrolling to program, you can now create an encounter for this through the drop-down menu in the right top corner
- [ ] On creating new encounter, there is additional fied to add notes and save
- [ ] The HIV Care & Treatment is divided into the following sections:
   - [ ] Visit Type
   - [ ] Physical Exam
   - [ ] ARV/Medication
   - [ ] Pregnancy
   - [ ] GBV
   - [ ] Viral Load
   - [ ] Biochemistry
   - [ ] Haematology
   - [ ] Tuberculosis
   - [ ] Index Testing
   - [ ] HCV/CrAg
   - [ ] Risk Behavior
   - [ ] Referrals

### Contact tracing
- [ ] Contact tracing is available for HIV programs
- [ ] To do so, select “Add Contact” through the drop-down menu in the right top corner in patients detail window
- [ ] This will open a dialog to choose type of contact, in this case, HIV Partner Testing, and click OK
- [ ] Contact tracing for HIV Partner Testing includes the following:
   - [ ] Index Client Information
   - [ ] Family/Partner Information
   - [ ] Tracking Outcome
   - [ ] Post PNS IPV Screening
- [ ] On the top right is the button to Link to patient
- [ ] Clicking the button will open a dialog where you can search for patient using firstname, lastname & ID
- [ ] The search filter works
- [ ] Clicking OK links the selected patient, and it appears as highlighted in the Linked Patient window.
- [ ] After linking, there is also button to unlink the patient

**Comment by nisha-dangol** [comment]
Testing in v1.6.2 exe with mSupply v7-13-00-beta1:
Currently, there's problem in setup of Document Registry Config:
1. On running footrunner code, the log shows as below: (while the om document registry does look populated)
<img width="1287" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/33663251-c807-4607-9f0e-b993990c693c">
And, on trying to create new patient or viewing patient at all, the oms crashes. 
<img width="937" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/be4cb603-1266-485c-b30f-e67c12833e16">
Link to recording: https://recordit.co/5Vkeojc60V
<br><br>
2. On trying to manually add the schemas to om document registry as per [the config.json file](https://github.com/msupply-foundation/programschemas/blob/main/png/schemas/config.json) here, patient can't be created, showing list of errors. 
<img width="1352" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/74f0de3a-1217-463c-99da-7a2a8fbc532c">
Link to Recording: https://recordit.co/aBHsdi7Fma

**Comment by roxy-dao** [comment]
Is this testing done?

**Comment by nisha-dangol** [comment]
> Is this testing done?

Yes, this was done in v1.6.x. The test scripts have been copied to [wiki](https://github.com/msupply-foundation/open-msupply/wiki/Test:-Patient-Programs) already; will close this as Done!
