### ISSUE TITLE
Android doesn't show fridge tag files in file picker from USB Storage

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#2938]
## What went wrong? 😲
 

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/50d63c3e-db8b-435e-b3c8-11f535759605)
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/3d41b73d-89f9-4858-b39b-442988a76daa)

## Expected behaviour 🤔

Datafiles should show when selecting the usb storage device for a Fridge Tag

## How to Reproduce 🔨

Steps to reproduce the behaviour:

I used a fridge tag 2L

1. Connect fridge tag to tablet
2. Wait for screen to process and say `usb`
3. Check in file browser to see if a `.txt` file exists in the USB Storage area
4. Click Import Fridge-tag from  Cold chain -> Monitoring
5. Choose usb storage device

## Your environment 🌱

 - Version: 1.6.00
 - Platform:
   - android (tablet)

**Comment by lache-melvin** [comment]
@jmbrunskill I can't reproduce this, file is appearing fine at least on Samsung tablet... have you seen this issue recently?

**Comment by jmbrunskill** [comment]
Was a weird one, might have just been my tablet? I'll test again...

**Comment by jmbrunskill** [comment]
Retested this morning, and it's working.
Has been an OS upgrade since this happened, possibly an OS bug?
Closing...
