### ISSUE TITLE
Refactor item filter in stocktake_line and stock_line queries

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2939]
## Is your feature request related to a problem? Please describe 👀
Coming from [this comment](https://github.com/msupply-foundation/open-msupply/pull/2927#discussion_r1488774530)

The stocktake_line and stock_line queries are making use of another fn `apply_item_filter` which could be bundled in with the `create_filtered_query`.

**Comment by andreievg** [comment]
Refinement, works as it is. If bug then fix
