### ISSUE TITLE
App won't start after upgrading to 1.7 (develop) - migration errors

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#2941]
## What went wrong? 😲
 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run DB migrations

Caused by:
    0: Error during migration (1.7.0)
    1: "UNKNOWN" ("\"\\\"database disk image is malformed\\\"\"")', /Users/jamesbrunskill/open-msupply/server/server/src/lib.rs:77:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected behaviour 🤔
Open-mSupply should start!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Initialise your sqlite database from the main branch v1.6.02
2. Switch to develop
3. `cargo run`

## Your environment 🌱

 - Version: 1.7
 - Platform:
   - [ x ] android (tablet)
   - [ x ] desktop (macOS)

**Comment by clemens-msupply** [comment]
Some migration have in added to 1.6 migration after the 1.6.0 branch has been released:

```bash
git difftool -d --tool=kdiff3 v1.6.00:server/repository/src/migrations..develop:server/repository/src/migrations
```

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/92eedae2-bd23-4777-b1b8-5885414331b0)

Main offender is adding a column to the synclog.
