### ISSUE TITLE
Display user friendly errors on login failures

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2945]
## Is your feature request related to a problem? Please describe 👀

There have been a few complaints about the unfriendly messaging that can happen when you login and initialise. 
An example:

![telegram-cloud-photo-size-1-5035418318256844280-x](https://github.com/msupply-foundation/open-msupply/assets/9192912/c001499f-5951-4de5-aa64-496ef0b35294)

Also, the request was made: _"Can we make this button show the error messages?"_

Second reported error:

![telegram-cloud-photo-size-1-5069329911147244978-y](https://github.com/msupply-foundation/open-msupply/assets/9192912/0e23db02-0235-46ca-adf7-f0c13773560c)

## Describe the solution you'd like 🎁
- [ ] For known errors, provide a helpful message describing the error and a suggested solution.
- [ ] On the login screen, find a way to display the error that doesn't require pressing a very small info icon
- [ ] Change the message 'Sync API version is not compatible'

The errors above might be:
- the server URL or port is incorrect
- the server is offline
- you have a network issue, such as an incorrectly configured firewall
- the port you have configured mSupply to run on is the same as the port used by open mSupply

There could also be various network issues which show up on that screen:
- your SIM card has run out of credit
- you are not connected to the WIFI
- mobile data is not turned on

We cannot show all possible resolution options, so best to just summarise: "Check the server URL" or something like that and "Check your network connection" if you get a network error.

The port issue is along the lines of 'Unexpected response from the server: check that this URL is for the central server" 🤷

**Comment by jmbrunskill** [comment]
I'd suggest we keep a good method to see the underlying error for debugging, especially on android where we can't easily see the api requests in console.

**Comment by DhanyaHerath** [comment]
Note from @Chris-Petty to add detail: error if your user does not have log in rights to the store on your site

**Comment by DhanyaHerath** [comment]
Related?
https://github.com/msupply-foundation/open-msupply/issues/745

**Comment by mark-prins** [comment]
Additional, slightly related request. Could you please change the error message here:
![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/9888f74f-c7d3-433e-8b28-2063b0165cc4)

Please change to 
"The mSupply Central Server needs to be upgraded to a newer version before you can connect- please contact support@msupply.org.nz” or something like that

**Comment by Chris-Petty** [comment]
I think fixing this sooner rather than later would be really good - sync is an essential thing that commonly needs frustrating fighting get going...

**Comment by mark-prins** [comment]
also this: 
<img width="424" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/039d7eaf-faef-472d-97d1-f8714c865a18">

**Comment by andreievg** [comment]
Would this also include being able to easily pop the error up on mobile ?

**Comment by andreievg** [comment]
Assigning to team Ruru, mainly to make sure that the error can be easily seen on mobile, since it's been requested by support, testers etc..

**Comment by andreievg** [comment]
> cool thanks - was going to pick this one up this morning after trying to work through a central server config issue with someone on a tablet. the Ux on a tablet isn't great..

@mark-prins, i am not trying to hog this one, just wanted to make sure this one is done. Please feel free to re-assign to self if you get time to do this before one of Ruru's assigns them

**Comment by AnushaUp** [comment]
# 🧪 Testing
Open_mSupply desktop and mobile `v2.1.0-IA-test-2`


- [ ] Stop your server, and try to log in
  - [ ] You should see the `Unable to connect to server` error, and the hint on hover
- [ ] In mSupply (Special > Synchronisation > site setting for your oms central server) clear the OMS central server URL/set it to some fun garbage
  - [ ] You should see the `v6 central server not configured` error, and the hint on hover
- [ ] In mSupply (Admin > Edit users > Your user > Login rights) Remove `can login` rights for your user for any of the stores on your current site
  - [ ] You should see the `Unable to log in` error, and the hint on hover
- [ ] Make sync versions incompatible (either switch to older mSupply version, or just increase the number [here](https://github.com/msupply-foundation/open-msupply/blob/af04575a272cfbb44ed4cb9ba8b91e486e033f4f/server/service/src/sync/settings.rs#L4) and restart the server
  - [ ] You should see the `Sync API version is not compatible` error, and the extra detail in the hint on hover
- [ ] Honestly not sure how to trigger the unknown error, I just was changing code to return something random?
  - [ ] You should see the `The server has returned an error` message
- [ ] On any error that has a tooltip (i.e. if the info icon is there) - the tooltip pops up on hover over anywhere on the error message
  - [ ] Test this on a tablet! Is it easier to press?

**Comment by AnushaUp** [comment]
> [ ] Honestly not sure how to trigger the unknown error, I just was changing code to return something random?
> * [ ]  You should see the `The server has returned an error` message

Tried disconnecting the user and the server from the remote site but couldn't recreate this issue. Moving this issue to done and will come back later if such error is seen.
