### ISSUE TITLE
Upload photo / supporting documents for asset item

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2981]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/e4262d63-5597-4fd7-9d62-81ff95e7c92e)

## Describe the solution you'd like 🎁
No additional details in the requirements. 
Thoughts: 
* a file size limit for documents and photos
* limit the types of documents and photos which can be uploaded

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by fergie-nz** [comment]
Might need discussion on how to manage sync of photos
