### ISSUE TITLE
Import assets from a spreadsheet

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2982]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

Following on from the initial list view #2973, implement the **Import** button which will

* open a dialog where you can drag n drop a file, or
* open a file selector
* from here, it's guesswork : the requirements say only 'Import the new/updated asset register / CCE Inventory'
* there is a 'review' and 'import' step, so perhaps display the imported list in the second step?
* and the results success / fail (?) on the last step?

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/03e77e1d-caa0-41e7-8884-bb7cb0f552f4)

## Describe the solution you'd like 🎁

Description: to create / edit Asset Register / CCE Inventory
1. Export the asset register / CCE Inventory to add new assets / CCE or to update existing records
2. Import the new/updated asset register / CCE Inventory

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by fergie-nz** [comment]
@richardmoizeau would you be willing to offer some clarity on the functionality we want to have out of this issue?

We are wondering about uploading from a CSV file, and if so the option to use (papaparse)[https://www.npmjs.com/package/papaparse] or (sheetJS)[https://www.npmjs.com/package/xlsx]. papaparse is much smaller, however can only parse (and not generate).

There are also some possible issues with using a spreadsheet template to upload - if the users don't have the right spreadsheet, we won't be able to read what is being uploaded.

**Comment by mark-prins** [comment]
hm. sheetjs hasn't been updated for 2 years, and there's only 1 collaborator. 
I've used [exceljs](https://www.npmjs.com/package/exceljs) before and like that, but I see that it's huge (251kb compressed)

I would use papaparse - we do need to generate excel, but I expect that will be a backend process and we won't need a front end library for it.

**Comment by richardmoizeau** [comment]
> @richardmoizeau would you be willing to offer some clarity on the functionality we want to have out of this issue?
> 
> We are wondering about uploading from a CSV file, and if so the option to use [papaparse](https://www.npmjs.com/package/papaparse) or [sheetJS](https://www.npmjs.com/package/xlsx). papaparse is much smaller, however can only parse (and not generate).
> 
> There are also some possible issues with using a spreadsheet template to upload - if the users don't have the right spreadsheet, we won't be able to read what is being uploaded.

This sounds a bit too technical for me but let me try something: 

- follow @mark-prins advice and use whatever software/solution we're confortable with. I know @jmbrunskill have worked on something similar (uploading data using an excel template) for HSH but I imagine you're already talked to him ? 
- in mSupply OG, you have the possibility to upload data (items, items with stock, names, etc...). What is nice, is that system will provide the right template for importing. So users would have to use it and follow instructions on our public doc. 
- I'm curious to know what you ended up deciding ? Upload the catalogue or the register ? both at the same time ? Specifications doc did not make that call. We can chat about it tomorrow (March 15th).

**Comment by adamdewey** [comment]
> I'm curious to know what you ended up deciding ? Upload the catalogue or the register ? 

I think for CCEI the register would be a lot bigger than the catalogue so would be save the end user a lot more manual entry?

**Comment by craigdrown** [comment]
I'd be pretty keen for you to be only handling import on the back end using 
https://github.com/MathNya/umya-spreadsheet 
It reads/writes Excel (else you need 2 libs) and the back end will be read/writing anyhow to to reports to Excel (reading as it will (eventually) need to fill in Excel templates, not just generate new Excel

**Comment by richardmoizeau** [comment]
> I'd be pretty keen for you to be only handling import on the back end using https://github.com/MathNya/umya-spreadsheet It reads/writes Excel (else you need 2 libs) and the back end will be read/writing anyhow to to reports to Excel (reading as it will (eventually) need to fill in Excel templates, not just generate new Excel

As long as users (system admins at minima) can do it on their own that all good !

**Comment by adamdewey** [comment]
Just a note that we should probably export to tsv/csv so users don't need Excel installed to read the output?

So should we handle the same format for import too?

**Comment by jmbrunskill** [comment]
> I'd be pretty keen for you to be only handling import on the back end using https://github.com/MathNya/umya-spreadsheet It reads/writes Excel (else you need 2 libs) and the back end will be read/writing anyhow to to reports to Excel (reading as it will (eventually) need to fill in Excel templates, not just generate new Excel

@craigdrown we have an existing pattern for csv import from health supply hub that doesn't require any new dependencies.
Are you able to clarify your reasoning for why you think we should do parsing in the backend? It will require significantly more work, so we'd like to understand what value you see. Using the frontend we're able to use all the same graphql requests and validations used for manually creating an asset, as well as providing a good mechanism to communicate any errors to the user without the use of a temporary table or similar. 

If the requirement was to do a transaction rollback on error or introducing excel libraries then I'd see more value, but as Adam points out, not all users will have access to an Excel license.

**Comment by craigdrown** [comment]
> Just a note that we should probably export to tsv/csv so users don't need Excel installed to read the output?
> 
> So should we handle the same format for import too?

@adamdewey  @jmbrunskill  I consider CSV export naff ;-)
You lose all formatting, have trouble with text being interpreted as dates etc etc. There is Libreoffice, WPS Office, OpenOffice, Numbers etc - no shortage of free Excel readers. More in next comment.

**Comment by jmbrunskill** [comment]
After discussing with Craig, we've agreed to implement a CSV import for now, but added an issue in the backlog for an excel based import version. This probably requires some new patterns in the backend and design for how to make a re-usable components in the rust code.
