### ISSUE TITLE
Asset: QR code scanning

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2983]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/2fa52ed4-13be-4020-aee7-79a5d069ff5f)

Description: to look up an individual asset scanning a QR code
1. Navigation: Asset Register: List View > Scan QR Code button
Navigation: CCE Inventory: List View > Scan QR Code button
2. User clicks on the Scan QR code button
3. For mobile device: system opens the camera 
4. If a matching record is found in the registry, user is redirected to the Asset Register: Detailed View of the asset / CCE Inventory: Detailed View of the CCE
5. If no matching record is found, a popup window: “Asset not found” / “CCE not found”

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by adamdewey** [comment]
What's the user story behind this?

Is it that we will provide a way to print QR stickers that would be attached to the asset and then later scanned to identify?

**Comment by mark-prins** [comment]
I've added the detail from the requirements doc, which doesn't answer your question. 
What you have is what I understood the intention is though

**Comment by adamdewey** [comment]
Cool thanks Mark!
