### ISSUE TITLE
Prescription on android: first item added doesn't show immediately

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2996]
## What went wrong? 😲
 

Sometimes after adding the first item to the prescription and pressing ok the added item does not display (it has stock). If I then press add item again  and cancel out, the item I added previously now displays

Some additional information:
- only happens for the first item added
- doesn't happen every time. For Jess, once it starts happening it happens every time. For me, it happened once and after refreshing the page, didn't happen until I closed the app and reopened.
- there is stock available for the item
- this is only for new prescriptions
- the issue quantity has been set before clicking ok

## Expected behaviour 🤔
Should display the newly added line

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new prescription
2. Add an item which has valid stock available (i.e. not expired or on hold, nor is the assigned location on hold)
3. Enter an issue quantity
4. Click OK

Further information:

`upsertPrescription` is made and returns successfully.
`prescriptionByNumber` is then called after the render and has this:

```
            "lines": {
                "__typename": "InvoiceLineConnector",
                "nodes": [],
                "totalCount": 0
            },
```

even though the line was upserted successfully.
The test scenario is a datafile with 50k patients, and the patient loading is _very_ slow.

https://github.com/msupply-foundation/open-msupply/assets/9192912/ebd8a93a-46d5-4680-9e65-ccc7951eac32

https://github.com/msupply-foundation/open-msupply/assets/9192912/df2fc9ea-da06-4b3c-8be1-965ac0db30f2

https://github.com/msupply-foundation/open-msupply/assets/9192912/7c5337cf-259f-48d5-a923-62d82d00e10a

## Your environment 🌱

- Version: 1.6.02
- mSupply version: ???
- Platform:
  - [x] android (tablet)
  - [ ] browser (extra points if you tell us which one)
  - [ ] desktop (windows)
  - [ ] desktop (macOS)
  - [ ] server (windows)
- Database type: 
  - [ ] PostgreSQL
  - [ ] SQLite3

**Comment by roxy-dao** [comment]
Closed in #3003
