### ISSUE TITLE
Testing: Coldchain module test

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3006]
## Details 🤔

This issue was developed with the intention of covering every issue that had been raised for this module as well as to test whether all of the features that are typically functioning according to docs . 
Documentation: [oms coldchain
](https://docs.msupply.foundation/docs/coldchain/introduction/)

## Your environment 🌱

- Version:` 1.7.00`
- mSupply version: V7.12
- Platform:
   - [x] android (tablet)
   - [x] browser (remote login
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)
## Coldchain modules
  - [ ] Introduction
  - [ ] Monitoring
  - [ ] Notifications
  - [ ] Sensors

**Comment by AnushaUp** [comment]
# Open mSupply cold chain module
## Setup
- [ ] User permission
  - [ ] In the Vaccines section turn on `view sensor details` and `edit sensor location`
  - [ ] The user should be default user to the store in which the temperature data will be saved
- [ ] Cold chain app integration
  - [ ] To configure the integration only need to sync data to a server. The server can be instance of Open mSupply or mSupply
  - [ ] Here we are connection through the omSupply 
  - [ ] The user permission should be given in the omSupply tab.
     
![Screenshot 2024-02-16 at 4 31 54 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/89c53e15-215d-4463-8fcf-b4fbdcb16777)

**Comment by marthakeezy** [comment]
### **Cold Chain App**

Settings -> Options
- [ ] **Sensor**
  - [ ] **Available Sensors** - it should show the sensors connected to the CCA
    - [ ] You should be able to click into the sensor to see specific settings
    - [ ] Blink should trigger the blink in the sensor
    - [ ] Remove should trigger the window asking you to confirm the removal -> subsequently remove the sensor
    - [ ] Sensor name should be editable
    - [ ] Log interval should be editable, between 1 minute and 60 minutes. You should be able to drag the selector as well as enter the digits manually. 
  - [ ] **Options** - default interval should be editable, between 1 minute and 60 minutes. You should be able to drag the selector as well as enter the digits manually. 
  - [ ] **Found Sensors** - available sensors will be displayed, they should be clickable for you to connect to them.

**Comment by AnushaUp** [comment]
## Monitoring
- [ ] This section should have 3 views:
 - [ ] In chart view there should be summary of data from all sensors which are connected.
 - [ ] The Breaches tab shows the list of all recorded breaches
 - [ ] The log tab records and view all the temperature logs

**Comment by AnushaUp** [comment]
## Notifications
### Breaches
- [ ] If the following conditions have all been met, then a notification bar should appear on all pages
  - [ ] The vaccine module has been enabled for the current store
  - [ ] The currently logged in user has permission to view temperature logs
  - [ ] One or more sensors have recorded a temperature breach
  - [ ] One or more of those breaches has not been acknowledged

**Comment by marthakeezy** [comment]
### Exporting Logs

Under the Sensor Detail area, you will see an Export button. The button should be clickable -> to export the logs, you must type in the username you logged into Cold Chain with. Please check it has the following information: 

**General**

- [ ] Timezone – as set for the tablet
- [ ] Device – tablet name from which the file was exported
- [ ] Sensor name – descriptor for the sensor (or MAC address if the sensor is unnamed)
- [ ] Exported by – name of the person exporting/emailing the data
- [ ] Comment – any notes entered by the user in the export or email window

**Last Programmed**

- [ ] Logging interval – number of minutes between logs
- [ ] Logging start – begin date and time for the logs on this sensor
- [ ] Programmed on – date that the above settings were last changed for the sensor

**Breach Configurations**

- [ ] Breach type – Continuous (Single Exposure) or Cumulative
- [ ] Direction – Min (for temperatures below range) or Max (for temperatures above range)
- [ ] Temperature – temperature limit set for the breach
- [ ] Number of minutes – duration set for the breach
- [ ] Breach name – descriptor given to each breach

**Statistics**

- [ ] Max temperature – highest temperature recorded by the sensor
- [ ] Min temperature – lowest temperature recorded by the sensor
- [ ] Number of continuous breaches – number of single exposure breaches (either hot or cold)

**Breaches**

- [ ] Breach type – can be either continuous (single exposure) or cumulative
- [ ] Breach name – descriptor for the breach
- [ ] Start of breach – date and time
- [ ] End of breach – date and time
- [ ] Exposure duration – length of breach in minutes
- [ ] Min temperature – lowest value during the breach
- [ ] Max temperature – highest value during the breach

**Logs**

- [ ] Timestamp – date and time
- [ ] Temperature – recorded temperature in degrees Celsius
- [ ] Is cumulative breach – if yes, column will display either hot or cold depending on direction of breach
- [ ] Is continuous breach – if yes, column will display either hot or cold depending on direction of breach
- [ ] Logging interval – the interval between temperature logs in minutes

**Comment by marthakeezy** [comment]
### **Epics** 

**Epic #1**
As a healthcare worker, I want to have one tablet showing Cold Chain next to my fridge, and one tablet that I use for my omSupply daily use, so that the temperature data is always visible when people walk past the fridge. And I can do my daily tasks on the omSupply tablet without disrupting the Cold Chain tablet by the fridge. 

_User Story_: as a healthcare worker, I want to see the data from the Cold Chain tablet by the fridge appearing in omSupply. 
_Testing_: then you can specify the criteria, you can check the exact same data in CCA is appearing in omSupply. 

**Epic #2**
As a healthcare worker, I want to use one tablet for both Cold Chain and omSupply, so that I save costs on hardware. 

_User Story_: as a healthcare worker, I want to see the data from the Cold Chain App is appearing in omSupply app. 
_Testing_: then you can specify the criteria, you can check the exact same data in CCA is appearing in omSupply.

**Comment by AnushaUp** [comment]
# mSupply cold chain module
Tested in `mSupplyV7-12-05` and `omSupply V1.7`
## Setup
- [ ] User permission
  - [ ] In the Vaccines section turn on `view sensor details` and `edit sensor location`
  - [ ] The user should be default user to the store in which the temperature data will be saved
- [ ] Cold chain app integration
  - [ ] To configure the integration only need to sync data to a server. The server can be instance of Open mSupply or mSupply
  - [ ] Here we are connection through the omSupply 
  - [ ] The user permission should be given in the omSupply tab.
     
![Screenshot 2024-02-16 at 4 31 54 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/89c53e15-215d-4463-8fcf-b4fbdcb16777)

**Comment by AnushaUp** [comment]
Tested in `mSupplyV7-12-08` and `omSupply V1.7`
## Sensor
### Viewing Sensors
- [ ] Choose Cold chain > Sensors in the navigation panel.
  - [ ] You should be able to see a group of sensors which are imported to that particular store
<img width="1245" alt="Screenshot 2024-03-06 at 6 04 31 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/6fec3a3d-c7b0-46af-87c3-28f4f8eb20b7">

  - [ ] You should be able to edit only the location of the sensors
  <img width="595" alt="Screenshot 2024-03-06 at 6 08 44 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/96e52950-a8e7-42df-b2ad-850787607438">

  - [ ] The currently logged in user has permission to view temperature logs

**Comment by marthakeezy** [comment]
Cold Chain is tested here:
