### ISSUE TITLE
mSupply Desktop Migration

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3025]
## Is your feature request related to a problem? Please describe 👀

We need to be able to confidently migrate sites on our legacy apps to Open mSupply. This epic focuses on mSupply Desktop migrations, which will be a subset of the issues impacting mSupply Desktop migration to Open mSupply.

## Describe the solution you'd like 🎁

Note we are focusing on core functionality and not customisations, though these should be documented privately if they arise. We will maintain a spreadsheet of feature parity which can be found on the drive.

1. We create issues that arise from attempting to migrate an example of mobile data that is wide reaching
2. Label them "Migrate Existing Desktop" and "Team Tauhou"
3. Add them to this epic in the section below.

## Sub Issues

- [ ] ~#608~
- [x] #894 
- [x] #1166 
- [ ] #1323 
- [x] #1396 
- [x] #2663 
- [x] #3598
- [x] #2760 
- [x] #3018
- [x] #3609
- [x] #3611
- [x] #3607 
- [x] #3620
- [x] #4000
- [x] #4013

## Moneyworks Jobcode 🧰

OMS:MIGRT

**Comment by roxy-dao** [comment]
Closing as completed in V2.1.0 (for now...)

**Comment by marthakeezy** [comment]
Tested as a part of release testing for V2.1.0, moving to Done ✅
