### ISSUE TITLE
Why does the location show as [multiple] in prescription when we try to issue items having no location?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3029]
## What went wrong? 😲
 
Why does the location show as [multiple] in prescription when we try to issue items having no location?

## Expected behaviour 🤔
Should be consistent with other window like inbound; if no location, show blank instead of confusing words like [multiple]

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get some item stocks, but assign no location
2. Get that item into the prescription
3. See error: the location columns shows [multiple] as if there are multiple locations. 
<img width="1064" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/9c592295-84de-443e-83da-baf72d21fc12">
4.I've also seen this sometimes in stocktake window, especially when `Group by item` is ON.

## Your environment 🌱

- Version: v1.6.2
- mSupply version: v713-00-beta3
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
This should probably be "low" but it upsets me an unreasonable amount.

**Comment by roxy-dao** [comment]
Closed in #3260
Wouldn't lemme link 🤷🏻
