### ISSUE TITLE
Cold Chain - Battery Level on Berlinger tags message: 'Not configured'/ 'undefined'

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3030]
## Is your feature request related to a problem? Please describe 👀

For the end user it can be confusing to read [Not configured] on the main page, but when clicking on the monitor itself, it says 'undefined'. Unless they know it won't be captured, they can think there's an error to be fixed.

@adamdewey agrees it would be nice to show the same message to have uniformity, otherwise it can be confusing.

Monitors menu:
<img width="1489" alt="Screenshot 2024-02-21 at 9 15 40 AM" src="https://github.com/msupply-foundation/msupply-cold-chain/assets/132425096/5ff54e64-cae1-4004-9afa-05232aa31cb8">

Clicking on the monitor itself:
<img width="586" alt="Screenshot 2024-02-21 at 9 19 56 AM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/8fbca12b-d711-4fd9-99c5-3d0d0273758f">

## Describe the solution you'd like 🎁

The message can be "Not available" on both pages. or "Not configurable". 

### Describe alternatives you've considered 💭

Open to other ideas.

### Additional context 💌

Are we considering getting this data later on? Or it's just not on the roadmap?
I imagine the different message may be a result from the API response.

**Comment by adamdewey** [comment]
Thanks @regotaina 

I think perhaps the wording `Not available` would be better?

**Comment by adamdewey** [comment]
Or, actually, to save screen real estate - maybe we should just use a hypen `-` ?

**Comment by mark-prins** [comment]
maybe the same time as #3055

**Comment by marthakeezy** [comment]
Tested the above - the battery level is now displayed as '-', when looking at the list of sensors available and when looking at a specific sensor. Test passed ✅
