### ISSUE TITLE
Unit test errors

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3031]
## What went wrong? 😲
 
In the develop branch these tests are failing:

* sync::test::pull_and_push::test_sync_pull_and_push
* sync::translations::barcode::tests::test_barcode_translation

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Version: 
- mSupply version: 
- Platform:
  - [ ] android (tablet)
  - [ ] browser (extra points if you tell us which one)
  - [ ] desktop (windows)
  - [ ] desktop (macOS)
  - [ ] server (windows)
- Database type: 
  - [ ] PostgreSQL
  - [ ] SQLite3

**Comment by roxy-dao** [comment]
and postgres
``` linking with `cc` failed.
ld: library 'pq' not found 
```
