### ISSUE TITLE
Cold Chain: Some breaches don't have a Max/Min temperature attached to it 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3033]
## What went wrong? 😲

We noticed some of the temperature breaches don't have a max/min temperature attached to it on the 'Monitoring' screen:

<img width="1363" alt="Screenshot 2024-02-21 at 10 04 23 AM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/bc9b7bd5-e8db-43d0-b398-53be8ae1909b">

Maria and Adam noticed there was data on the cold chain app, but for some reason it was not brought across oms.

## Expected behaviour 🤔

All breaches should have a min/max temperature associated with.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Cold chain'
2. Click on 'Monitoring' > breaches
3. See column 'Max/min' empty for some breaches

## Your environment 🌱

- Version: 1.6.02
- mSupply version: v7.12.01
- Platform:
  - browser (extra points if you tell us which one)

**Comment by regotaina** [comment]
@marthakeezy do you have more screenshots from your set up? Please share if you have any cases like this one

**Comment by marthakeezy** [comment]
@regotaina I haven't seen this bug before yesterday, but will pop some screenshots in this thread if I notice anything!

**Comment by adamdewey** [comment]
Actually unsure if the temperature logs are correctly tagged in CCA - would be good to verify that

**Comment by Chris-Petty** [comment]
@adamdewey what do you mean tagged? As in including the temperature value?

Vibing normal until concrete it's OMS? Though that assumes investigation has some sorta priority in CCA...

**Comment by adamdewey** [comment]
@Chris-Petty - eek, my bad, I think that comment is meant for another issue where the breach icons weren't being displayed properly! Will remove..

**Comment by adamdewey** [comment]
And yah, I would say 'Normal' 👍

**Comment by roxy-dao** [comment]
Is it still happening?

**Comment by roxy-dao** [comment]
Looks like the temperature logs are missing for these breaches.

**Comment by jmbrunskill** [comment]
Assigning to 2.1 as we don't have repro steps.

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC6, had my sensor connected and logging breaches through the last week, and the error seems to be resolved. Will reopen if see again, otherwise Pass for now ✅
