### ISSUE TITLE
Location filter is for location name, but the code is shown in the list view

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3040]
## What went wrong? 😲
 
When you try to use the location filter and type in more than one character, you will see that the filter doesn't work

## Expected behaviour 🤔
Filter should work properly

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have some location with codes like example `s111` (multiple characters)
2. Go to view stocks and choose the location filter
3. Type `s` (only one character) , it works!
4. Type 's1` (multiple characters) - see Error: it doesn't filter correctly

## Your environment 🌱

- Version: v1.6.2
- mSupply version: v713-beta1
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by roxy-dao** [comment]
Oh that's because it's currently searching by location name 😆

**Comment by mark-prins** [comment]
the column should be changed to show the name - it's currently confusing having the filter operate on the name but the column shows the code!

In this example the filter for `ro` returns the location of `Storage room 2`

![Screenshot 2024-02-22 at 8 38 24 AM](https://github.com/msupply-foundation/open-msupply/assets/9192912/ac951063-5f2a-48c2-9ed4-865a52911d67)

which looks weird in the stock view:

![Screenshot 2024-02-22 at 8 37 42 AM](https://github.com/msupply-foundation/open-msupply/assets/9192912/ee0a1879-8f29-4a08-92c2-8da7b2fe6b41)

**Comment by Chris-Petty** [comment]
I heart says "High" but I don't want to be too dramatic. Probably doesn't need to be patched... if I was a user I'd want it patched though 🙃.

**Comment by nisha-dangol** [comment]
Tested in v1.7.7-rc2 exe

### Tests
- [x] Test location filters and enter codes
- [x] Lists should filter location by code correctly
