### ISSUE TITLE
v1.7.0

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3044]
# Key Aims

- Item, Name and Prescriber Merging
~~- Multi unit items~~: Moved to 2.0
~~- Supplier/Customer Returns~~: Moved to 2.0
- Currency

## Deadlines (in NZT)

Date started: Feb 12, 2024
PR deadline: Friday Mar 1, 2024
PRs merged: Wednesday Mar 6, 2024
Release: ~~Wednesday Mar 20, 2024~~ ~~Wednesday Mar 27, 2024~~ Wednesday April 3, 2024

**Comment by roxy-dao** [comment]
Release delayed until 27th to match OG

**Comment by roxy-dao** [comment]
Delayed until April 3rd
