### ISSUE TITLE
Stocktake: lines not showing changes

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3048]
## What went wrong? 😲
 
When editing a stocktake line the changes do not show until you refresh the page, or navigate away and come back to the stocktake detail view again.

https://github.com/msupply-foundation/open-msupply/assets/9192912/36663ce5-9eed-4e4b-98e5-39a3cfc12a54

## Expected behaviour 🤔
Updates should show immediately
 
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to the detail page of a stocktake
2. make a change to a line
3. See error

## Your environment 🌱

- Version: 
- mSupply version: 
- Platform:
  - [ ] android (tablet)
  - [ ] browser (extra points if you tell us which one)
  - [ ] desktop (windows)
  - [ ] desktop (macOS)
  - [ ] server (windows)
- Database type: 
  - [ ] PostgreSQL
  - [ ] SQLite3

**Comment by nisha-dangol** [comment]
Looks good in v2.1; moving to Done.
