### ISSUE TITLE
Unsetting height doesn't save at all

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3050]
## What went wrong? 😲
From here: https://github.com/msupply-foundation/open-msupply/pull/2520#issuecomment-1958960229
## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Do the minimum for programs-setup; or simply use PNG Demo data; that has programs-setup configured properly
2. Create a new patient or use any existing
3. Enrol it to a program like HIV Care & Treatment
4. Now add an encounter, like HIV Care (we need one which will require height details)
5. Add a height value and save the whole encounter window
6. Open the same encounter, this time unset the height value - I simply backspaced the value
7. Since Save button is disabled, try adding notes or changing status until Save button is enabled, and then Save
8. Reopen the same encounter and check the height value now
9. See error: it hasn't updated at all; it's still the same first value

## Your environment 🌱

- Version: v1.6.2
- mSupply version: v713-00-beta3
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
@nisha-dangol does it work if you set another value rather than empty?

**Comment by nisha-dangol** [comment]
> @nisha-dangol does it work if you set another value rather than empty?
>
The problem is that as per [this PR](https://github.com/msupply-foundation/open-msupply/pull/2520#issue-2003273860), the height value saved in an encounter should be consistent with the other encounter created for that same patient; meaning: if I set height `4.1` in 1st encounter and change it to height `4.3` in 2nd encounter, height should remain the last-changed-value (i.e., `4.3`) for all encounters
Here's the details and [here's the video reference](https://recordit.co/ioptblyatR) to the bug!
