### ISSUE TITLE
Doesn't select the searched entry from list in program enrolment form

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3051]
## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Get programs-setup datafile like PNG Demo
2. Have some patients with common starting letters like eg: Mimi Chan, Mimi Dan, etc
3. Create new patient and enrol it into a program like HIV Care & Treatment
4. Now in the enrolment form, in Mother field, put few characters in first name such that both previous names appear in search option, eg: put Mimi in first name and see both `Mimi Chan` and `Mimi Dan` appear in the list
5. Make sure to select the second one: `Mimi Dan`
6. See error: it automatically selects the first one : `Mimi Chan`

## Expected behaviour 🤔
It should select the one we select; not take the first entry by default! 

## Screenshot/Recording
https://recordit.co/S4MBEPHXbN

## Additional Context
Found while testing #1840 

## Your environment 🌱

- Version: 1.6.2
- mSupply version: 713-00-beta3
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
High based on customer soon to expand usage and this seems like a component state bug that might not just affect here.
