### ISSUE TITLE
Cannot choose the time correctly in date-time picker

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3052]
## What went wrong? 😲
No matter what time we select, it automatically changes to the current system time

## Expected behaviour 🤔
The value we select should be prioritised?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to patient window and create an encounter
2. While choosing the visit date, select some past date and choose any random timing
3. See error: the time automatically changes back to current system time while the date is the one we selected. I think both date & time should be the one we select

## Screenshots
https://recordit.co/Wrxvw85XW2

## Additional
Found while testing #2415 

## Your environment 🌱

- Version: v1.6.2
- mSupply version: 713-00-beta3 
- Platform:
  - [ ] android (tablet)
  - [x] browser (extra points if you tell us which one)
  - [ ] desktop (windows)
  - [ ] desktop (macOS)
  - [x] server (windows)
- Database type: 
  - [ ] PostgreSQL
  - [x] SQLite3

**Comment by roxy-dao** [comment]
> Doing high priority as it may affect multiple areas? Plus time specificity is important and this bug would be pretty frustrating!
> 
> @roxy-dao looks like you touched this inputs most recently, might be best placed to take this on?

Think only programs is using time, but will double check.

**Comment by nisha-dangol** [comment]
> Think only programs is using time, but will double check.
>
Yeah, I noticed this for programs-module only. Choosing date-time looked fine in Coldchain

**Comment by Chris-Petty** [comment]
@clemens-msupply is programs likely to expand/be trained on before 20th of March (which is when 1.7 should be released)? If not then doesn't need a patch.

**Comment by clemens-msupply** [comment]
I hopefully will be. However, since only dates are used this issue should not be a major problem.

**Comment by clemens-msupply** [comment]
Is this test server outdated? the DateInputPicker in the encounter creation modal doesn't show a time anymore... Still a bug though.

**Comment by nisha-dangol** [comment]
@roxy-dao so this is now expected to not see the time-picker (like we used to in v1.6.2) while picking dates in v1.7?

**Comment by roxy-dao** [comment]
> @roxy-dao so this is now expected to not see the time-picker (like we used to in v1.6.2) while picking dates in encounter-creation in v1.7?

@clemens-msupply mentioned that it had changed to date only, but will wait for him to confirm tomorrow
