### ISSUE TITLE
Cold Chain: Sensors information should include a degree symbol

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3055]
## Is your feature request related to a problem? Please describe 👀

When logging into omSupply and navigating to Cold Chain -> Sensors, we can see a column called 'Last Reading' with the latest temperature information, and it includes a Celsius symbol. However, when clicking on a specific sensor to get more information, 'Last Reading' line only displays the numbers and not the Celsius symbol. 

## Describe the solution you'd like 🎁

The formatting of the readings should be consistent, so the 'Last Reading' when expanded should have the same degree symbol as when you first see the entry. 

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

![screenshot-1708653648676](https://github.com/msupply-foundation/open-msupply/assets/153777484/bb63d520-353d-4ab8-b15d-7745a00c606d)

[
![screenshot-1708653697883](https://github.com/msupply-foundation/open-msupply/assets/153777484/89746d52-4422-4211-8d1c-c4e9f3b32747)
](url)

### Moneyworks Jobcode 🧰

**Comment by adamdewey** [comment]
While we're in the area, should we add a space between the number and ° symbol too?

It's a pretty close run thing, so I guess just as long as we're consistent everywhere?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/c8d86d99-1e43-4102-97a9-db01bf8082c0)

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/7506a7ea-7e75-4317-b495-0890aae55980)

**Comment by CarlosNZ** [comment]
> While we're in the area, should we add a space between the number and ° symbol too?
> 
> It's a pretty close run thing, so I guess just as long as we're consistent everywhere?

Hmmm, I thought the space between number and degree symbol would be a definite no-no, but apparently it's prescribed by some style guides and not others: https://en.wikipedia.org/wiki/Degree_symbol#Typography

My personal preference is "20° C", but yes, consistency is more important. I would suggest we always defer to the JS `Intl.NumberFormat` function for formatting units -- that way we'll at least always have consistency (and it will show correctly in each language!)

In this case, for English, it gives: "29°C" (no spaces) :)

**Comment by mark-prins** [comment]
thanks @CarlosNZ - I thought the space was a no no too!
my preference is for the ° symbol to be next to the number without a space.. but am happy to run with whatever

**Comment by marthakeezy** [comment]
Unrelated question: I noticed some inconsistencies with capitalisation too - are some industry standards, but not others?

For example, on the screenshot above, we have the following sentences where both words are capitalised: 

- Sensor Details
- Serial Number

But not Sensor name or Battery Level? What's the logic behind this? 🤔

**Comment by adamdewey** [comment]
Bah you non-scientists, SI units are supposed to have a space between the number and symbol 😁

https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-7-rules-and-style-conventions-expressing-values

**Comment by adamdewey** [comment]
> Unrelated question: I noticed some inconsistencies with capitalisation too - are some industry standards, but not others?
> 
> For example, on the screenshot above, we have the following sentences where both words are capitalised:
> 
> * Sensor Details
> * Serial Number
> 
> But not Sensor name or Battery Level? What's the logic behind this? 🤔

For this, it seems the general rule is that `Title Case` is more formal and `Sentence case` is easier to read. 

So we should probably go for Sentence case if we're going for readability?

**Comment by marthakeezy** [comment]
Do you think we can add the degree symbols in CCA too? 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/ca3882b7-863c-43ce-bd16-9127e0a77880)

**Comment by adamdewey** [comment]
> Do you think we can add the degree symbols in CCA too?
> 
> ![image](https://private-user-images.githubusercontent.com/153777484/310296312-ca3882b7-863c-43ce-bd16-9127e0a77880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzgxOTEsIm5iZiI6MTcwOTY3Nzg5MSwicGF0aCI6Ii8xNTM3Nzc0ODQvMzEwMjk2MzEyLWNhMzg4MmI3LTg2M2MtNDNjZS1iZDE2LTkxMjdlMGE3Nzg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMjMxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGNmZDQ5MTgxNjg0YWUyMjQ2MTFjMTM1N2ViNWZjY2YxZmJkOWNjZTQwYWM5OTRlOGNjYmMwZDk0Yjg2MjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vzkVG6rutVysNPxY2pGCrXeslCvr-oX6jCv5XGpuG5Q)

I think there were there originally but the large numbers were too small so they were removed to allow for the numbers to be bigger. 

Perhaps there could be an indicator somewhere else in the page about the units though? 
Perhaps at the top of the screen?

**Comment by marthakeezy** [comment]
@adamdewey would there perhaps be enough space to include 29.5°, instead of the full 29.5° C? And we can include the unit somewhere else?

**Comment by roxy-dao** [comment]
Above will have to be in a new issue in the Coldchain repo (:

**Comment by adamdewey** [comment]
Have shifted convo to https://github.com/msupply-foundation/msupply-cold-chain/issues/296

**Comment by marthakeezy** [comment]
Checked the sensor information and the degree symbols are now displayed. Test passed ✅
