### ISSUE TITLE
Apply language `version` from HSH - Improve translation caching

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3064]
## The suggestion

In Health Supply Hub to improve caching of translation files, we added a language version tag, which is updated on every production build. This allows the browser to cache the translation files for longer.
Currently the files are cached for 60 minutes, which could mean the users have missing translation for up to 1 hour after an upgrade, and equally are re-downloading translation every 60minutes when there's no changes required.

## Example use case
Partial code diff
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/15402f7a-e7ca-4401-8c58-a80fdc733406)

### Why should we invest time in this?

Improving performance and bandwidth usage, although it probably only matters for client server installations.
Allows instant updates of translations when the server version changes.

### Are there any risks associated with this change?

Low risk, as this is already in place for HSH, unless there's unknown code differences between HSH & OMS

### How much effort is required?

We'll need to review code changes between HSH and OMS, but otherwise should be a copy and paste job

### Agreed Solution

TBD

**Comment by andreievg** [comment]
We believe this has been fixed in : https://github.com/msupply-foundation/open-msupply/pull/3664
