### ISSUE TITLE
Performance improvements 

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3066]
## Is your feature request related to a problem? Please describe 👀

After reviewing the site through [lighthouse](https://developers.google.com/web/tools/lighthouse/) there were some quick wins, which I've implemented in a [branch](https://github.com/msupply-foundation/open-msupply/tree/performance)

## Describe the solution you'd like 🎁
- [ ] Reduce the number of elements on the page : the example given is a refactor of the DataTable cell which reduced the stocktake detail page from 2100 to 1600 elements. Need to check if the error state would work ( I think it won't ) and replace with an error cell for the single usage of the error state
- [ ] add the viewport element and test to see what sort of impact this has
- [ ] review download size and the effect of tree shaking in webpack
- [ ] cache the static files in actix_web : the change made satisfied lighthouse, but I didn't see cached responses in the dev tools network panel and would like to test if caching is in fact working. test caching of translation files ( separate process, so I think they are ok )

### Describe alternatives you've considered 💭
A slower site? A worse score on lighthouse?

**Comment by jmbrunskill** [comment]
FYI - Here's what a did for caching in HSH https://github.com/msupply-foundation/health-supply-hub/blob/d5e59c34dee242f347cfcfac9b1af0e6caa47cc2/backend/server/src/serve_frontend.rs#L18
I also did some work to invalidate the cache here:
https://github.com/msupply-foundation/health-supply-hub/pull/762
OMS Issue for the same:
https://github.com/msupply-foundation/open-msupply/issues/2617

**Comment by mark-prins** [comment]
very nice! thanks @jmbrunskill that's better. Did you see the cached responses in the network panel? I wasn't getting them even though cache-control was set.

**Comment by jmbrunskill** [comment]
> very nice! thanks @jmbrunskill that's better. Did you see the cached responses in the network panel? I wasn't getting them even though cache-control was set.

Did you have cache disabled?
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/e570b385-5fb2-4dfd-be13-4089cc87013b)

Happy to look with you some time when we have some to look at this...

**Comment by mark-prins** [comment]
quite likely. will leave that for whoever picks up the issue to test
