### ISSUE TITLE
Performance test on basic tables

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3070]
Wasn't sure if this is a feature, bug or refactor, based on a water cooler conversation with @craigdrown.

It would be good to check the performance of base react table with the combination of existing queries in stocktake, to try and check these assumptions:

1. Is it basic React that is slow
2. Does mui slow things down ? (styled <td> with some extra components/logic)

#### Steps

Below to be tested on slow devices (browser on Lenovo tablets that we have and production Android build)

1. Make a new page with base stocktake detail view (just table though, but some columns, without checkboxes on the side though), using existing query (no API abstractions, just base tanstack, with codegen compiled TS sdk).

2. Check the stocktake page with same data file that has been performing slow in the latest deployment, record timing for page reload

3. Another stocktake detail view but using mui components, with the same check

Decide on further steps once the results are in.

I estimate this to take from half to full day of work (including set up and tests, data file sync etc..)

**Comment by andreievg** [comment]
Adding triage label again, for re-prioritisation, in light of VIP request for this to be bumped.

In the VIP request there was a mention of specific hardware, @jmbrunskill suggested it's worth procuring a set and testing with the data file for mentioned scenario

**Comment by mark-prins** [comment]
Also worth looking at these related issues before investigating, they give a bit of background:
* #3066 which improved the `DataTable` by reducing the number of react components rendered
* #2904 which was the stocktake speed (#2927 for the pagination PR)
* #2742 for master lists speed

**Comment by andreievg** [comment]
Triage, need to investigate, examine performance on Lenova tablet

**Comment by andreievg** [comment]
Added in the placeholder issue for other table refactor work
