### ISSUE TITLE
The transgender options do not appear in filter view for patients

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3072]
## What went wrong? 😲
 
The transgender options do not appear in filter view for patients

## Expected behaviour 🤔
In filter for gender, all the gender values must show?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get some patients with all types of gender (including the transgender ones)
2. Apply the gender filter
3. See error: there are no trangender options to choose from

## Your environment 🌱

- Version: v1.6.2
- mSupply version: v713
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
Low for now because I don't think anywhere is significantly using dispensing yet @DhanyaHerath ?

**Comment by clemens-msupply** [comment]
I guess we can add transgender to: `packages/system/src/Patient/ListView/Toolbar.tsx`

However, in general there are more gender types defined but some countries only want to show a subset. We would need a way to configure which gender to display. Think this is future work though... Note, this is also similar to the problem of displaying country specific labels in the patient UI, e.g. National Code or NUIC...

**Comment by roxy-dao** [comment]
Will close this for now as Clemens stated, some countries only want to show a subset. Will need to be an issue for future work to get 'customisable' filter fields for filters.
