### ISSUE TITLE
Can we have filter at top for Coldchain>monitoring so that filter values retain while switching to different tabs?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3075]
## The suggestion
Under Coldchain>Monitoring, when I select some filter like date-ranges or sensors and switch across the next tab, the previous filters get reset (which I'd like to retain, esp when I'm comparing things)

## Example use case
Place that at top retaining the selected filter values while we switch the tabs? sth like that maybe?
<img width="1413" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/e581d6a5-2c32-4a1d-a112-88c5f881ce93">

### Why should we invest time in this?
It makes it easy to search and compare honestly, and it's kinda annoying to keep setting the same filter again and again after switching to next tab within the same section!

**Comment by roxy-dao** [comment]
Closing since should have been fixed in #2752
