### ISSUE TITLE
Coldchain: Breach comment overflow

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3076]
## What went wrong? 😲
Breach comment overflows
![image](https://github.com/msupply-foundation/open-msupply/assets/61820074/f1fc948c-f6aa-4e81-9d52-d3297a1348fd)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Version: 
- mSupply version: 
- Platform:
  - android (tablet)

**Comment by adamdewey** [comment]
I wouldn't worry about this too much - the likelihood of it happening is low and the impact if it does happen is low, so the risk is very low.
