### ISSUE TITLE
Sync error persist after sync problem has been resolved

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3078]
## What went wrong? 😲

1) Cause a sync error: with an mSupply central version that only has a license for one client at a time, connect to this server while another client is using the central server

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/f307cc0f-0df6-4660-aee5-fba7208437b9)

2) Resolve the problem by restarting the central server
3) The error message stays even though sync works

**Comment by Chris-Petty** [comment]
@roxy-dao really? Login doesn't make too much sense, it's state specific to the user right? Where as sync is system state shared between all users. Shouldn't work to combine them aye!

**Comment by Chris-Petty** [comment]
Would love to make this "Severity: Medium" but strictly speaking it doesn't stop anything, just misleading user feedback right?

**Comment by roxy-dao** [comment]
> @roxy-dao really? Login doesn't make too much sense, it's state specific to the user right? Where as sync is system state shared between all users. Shouldn't work to combine them aye!

Was done in #2522 cause users kept clicking both since they weren't descriptive enough XD

**Comment by Chris-Petty** [comment]
Oh I see the buttons got combined... it was certainly confusing before UI wise. 

Why exactly is there user sync? Is it just refreshing the user permissions from central server without logging out and in? Be surprised if users understood that without being taught! Until now I'd have logged out and in lol.

**Comment by roxy-dao** [comment]
> Oh I see the buttons got combined... it was certainly confusing before UI wise.
> 
> Why exactly is there user sync? Is it just refreshing the user permissions from central server without logging out and in? Be surprised if users understood that without being taught! Until now I'd have logged out and in lol.

[🎯](https://emojipedia.org/direct-hit)

**Comment by roxy-dao** [comment]
Better error handling in #3475, so I will close this as complete (: Since this is clearly to do with the user login part of the sync button
