### ISSUE TITLE
Inbound shipments: long references not visible when status is "shipped"

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3079]
## What went wrong? 😲

1) Long references are not visible in the Inbound Shipment list view:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/e8231e5c-4853-42ca-be21-65f74b4d02a6)
2) For shipped shipments the reference is read only and you can't read long references:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/c88fd7c5-a138-4ba0-b33e-9b3c9e03d866)
(Or am I choosing an unrealistic long reference here?) 

## Expected behaviour
Have a tooltip (or something touch friendly) to see references in the list view and in the detail view.

**Comment by Chris-Petty** [comment]
What if there was an expand button that's always available that anchors a dropdown or something? https://mui.com/material-ui/material-icons/?query=expand&theme=Outlined&selected=ExpandCircleDownOutlined

**Comment by clemens-msupply** [comment]
There is also a tooltip option to enable it on click/hover:
https://mui.com/material-ui/react-tooltip/#triggers

**Comment by roxy-dao** [comment]
> What if there was an expand button that's always available that anchors a dropdown or something? https://mui.com/material-ui/material-icons/?query=expand&theme=Outlined&selected=ExpandCircleDownOutlined
> 
> Might be nice if writing long comments/messages too. Or modal? IDK!

If we do this we would need to make it consistent throughout the app...

**Comment by nisha-dangol** [comment]
Tested in v 1.7.0-rc2 exe

### Tests
- [x] Have an invoice/requisition with a long comment/reference... maybe do a transfer?
- [x] Hover over to see tooltip

I'm okay with the tooltip that shows up in the shipments list
<img width="1256" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/b8ff126a-103d-46af-9c76-a9c5db8f6ec9">

but I'd have preferred here as well, in the shipment window as well. Not a big deal, so will PASS it for now!
<img width="444" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/839fb652-26e7-46b4-8040-a7baf9c9b54c">
