### ISSUE TITLE
Currency display should be dependent on language

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3084]
## Is your feature request related to a problem? Please describe 👀
As discussed with @CarlosNZ. The currency display should be dependant on language. I.e.:
in English we would write:
$1,250.95
€1,250.95
And in French they'd write:
1 250,95$
1 250,95€
If users are using issuing in foreign currency and see a format different from their own, it could lead to confusion.

## Describe the solution you'd like 🎁
Link currency display with locale.

**Comment by craigdrown** [comment]
'ang on - if you're talking decimal separators that would be all numbers, not just currencies?
I would think separators & currencies should be kept apart?

**Comment by roxy-dao** [comment]
> 'ang on - if you're talking decimal separators that would be all numbers, not just currencies? I would think separators & currencies should be kept apart?

Yup it will work for all numbers since the NumericInput is getting the decimal and separators from currencies, but can keep it apart if that is what you prefer (:
