### ISSUE TITLE
Cold Chain: temperature graphs change every time you click in and out of 'Chart' tab

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3090]
## What went wrong? 😲
 

Every time a user clicks in and out of omSupply app, or in and out of the 'Chart' tab, the graphs change

https://github.com/msupply-foundation/open-msupply/assets/153777484/b50fa35a-df9c-4b54-a948-969101b8b8c6

## Expected behaviour 🤔

The graphs should stay consistent, as the data is not changing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to omSupply -> Cold Chain -> Monitoring
2. Click on 'Chart' tab and note the graphs
3. Switch to another app (for example, CCA), and then back to omSupply - note the change in graphs
4. Next, try and switch between different tabs - Chart -> Breaches -> Log -> then come back to Chart and note the change in graphs

## Your environment 🌱

- Version: 1.6.02
- Platform:
  - android (tablet)

**Comment by clemens-msupply** [comment]
It looks like the x-axis labels are not updated?

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc4, and the issue is fixed! Also, the new graphs look amazing, thanks team :) Build test passed! ✅
