### ISSUE TITLE
Change Outbound Shipment list default sort from "Created" to "Number"?

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3092]
## Is your feature request related to a problem? Please describe 👀
For migrated data files I am getting this kind of Outbound Shipment list where there are multiple entries with the same creation date. This can result in having the numbers out of order (50 and 51):

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/757f640d-1b63-4793-9678-b1dc0758352f)

Probably sorting by Number would result in the desired sort order? (Don't think it's easy to implement sorting by multiple columns right now; at least not on the backend...)

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.0 exe

## Tests
- [x] Go to outbound shipments
- [x] Should be sorted by number by default

## Additional tests
The closest I tried to replicate the original issue: 
- Created some CI/outbounds from OG-mSupply and modified dates & invoice-nums using record-browser to mock the pattern as in the issue
- Synced
- Migrated that OG-desktop-site to oms v2.0.0
- On v2.0.0, I see by default it's sorted by invoice-num, I call it PASS.
