### ISSUE TITLE
Invoice shows incorrect/imprecise sell price

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3093]
## What went wrong? 😲
If the actual price is < 0.01, 0.01 is shown instead of the precise value. This can be confusing. 
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/57dde73a-6545-4232-b1a3-dd40b9c34c10)

This is for migrated data.

## Expected behaviour 🤔
- [ ] Show precise value in the list 
- [ ] Show precise value in the line detail view
- [ ] The value might get to long to fit into the list column, and thus it might need some special handling...

**Comment by DhanyaHerath** [comment]
Triage: First step - can the column at least say `2dp` so it shows that it is rounded?

**Comment by Chris-Petty** [comment]
@DhanyaHerath I'm unsure about showing "2dp" everywhere:

- Not sure how well it translates so might not help?
- Pretty much every `float` column everywhere will say "Xdp" after we do the pref. Seems noisy/redundant? Already have lots of column over crowding

Perhaps if the rounded value has less dp than the true value, can tooltip full value? Would need some indication that it is the case that isn't obnoxious 😆.

**Comment by clemens-msupply** [comment]
Idea: display "< $0.01": and then have a tooltip with the precise price.

Or more fancy only use this as a fallback if the prize string is longer than a max string. For example, "$0.008" is quite short, and it can be displayed as is but "$0.000008" is displayed as "< $0.01" with tooltip.

**Comment by roxy-dao** [comment]
Closed in #3281
