### ISSUE TITLE
Pricing tab in invoice lines has a confusing column selection

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3094]
## What went wrong? 😲

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/4b9c3462-4db7-46f2-8ab2-663bbce0e765)

The calculation for cost price here isn't intuitive, because we're missing information. Reading from left to right you are lead to believe that `$0.9 * 300 = $2.70` clearly wrong. Price is per pack, and pack size in this case is 100. Users should not have to intuit that the presented column is not the one being used in the calculation and to do some head algebra to deduce the relevant fields 😁.

There is a real struggle here, as screen real estate is precious and we often want to show _a lot_ of columns. That said, I think there's room here?

## Expected behaviour 🤔

After discussing internally with several stakeholder, more columns endorsed by @Gwalior-84 
- Batch
- No. of packs
- Units per pack
- Cost price per pack
- Total (cost) price

In Mark's context sell price per pack is rarely of value. Maybe add it if not too cramp, otherwise leave off for now till requested 🙂 .

## How to Reproduce 🔨

1. View an invoice line and go to pricing tab.

## Your environment 🌱
- Version: 1.7 dev (probably 1.6 prod though)
- DB: SQLite3

**Comment by roxy-dao** [comment]
![Screenshot 2024-03-06 at 11 56 44](https://github.com/msupply-foundation/open-msupply/assets/61820074/a3966616-0270-48e6-9a4d-be0260b32060)
Calculation seems correct to me, can you test again and see if it's still happening for you? 👀

**Comment by Gwalior-84** [comment]
> Calculation seems correct to me, can you test again and see if it's still happening for you in current develop? 👀

It will only 'not' make sense if the pack size is > 1.  What is the pack size in this example?
