### ISSUE TITLE
Multiple report definitions for the same report

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3099]
There are two options to specify multiple templates:

`service/src/report/definition.rs`

On is to add another `templates` field:
```rust
/// Specifies which report definition entries are the "main" entries.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct ReportDefinitionIndex {
    pub template: Option<String>,
    pub templates: Option<Vec<String>>,
    pub header: Option<String>,
    pub footer: Option<String>,
    pub query: Option<String>,
}
```

Another option would be to support:
`template: string | string[]`

Think this should be possible to describe in serde with enums...

**Comment by andreievg** [comment]
I think we have sufficient excel export functionality for the time being, will re-create issues in the future when further requirements are raised
