### ISSUE TITLE
Filter UX enhancements

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3106]
## Is your feature request related to a problem? Please describe 👀
We've had complaints from most people when using filters for the first time. These are what I can remember:

* I've clicked the `Filters` drop down and started typing in order to select one of the items, when I hit a keyboard shortcut key (such as `i`) then I'm redirected to another page!!
* Same thing but for the enum filter type
* I want to remove an individual filter, why do I have to remove all and add them back in?

## Describe the solution you'd like 🎁

Can we replace the enum with an autocomplete and limit to available options only?
Same for the Filters menu?

In this list:

![telegram-cloud-photo-size-1-5044274214403681361-m](https://github.com/msupply-foundation/open-msupply/assets/9192912/709acbb7-d4d0-4962-9dcf-2c5da7421291)

it would work best with check boxes next to each item. So you can turn them on and off individually, rather than have to clear them all. This also allows use of an autocomplete without having to add the remove all filters option

**Comment by DhanyaHerath** [comment]
Triage: @Chris-Petty to create a new issue for how the filters return result

**Comment by Chris-Petty** [comment]
@DhanyaHerath I was probably in the room when you wrote that comment but I don't recall why or what you mean lol.

Tangentially I think notion has the greatest filters UI:

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/3874d5b9-0a97-49dc-931e-62109a924602)

**Comment by DhanyaHerath** [comment]
@Chris-Petty 
It was for the order in which filters return the result, ie. would you do "starts by" results followed by "contains" results etc

I agree re: Notion

**Comment by Chris-Petty** [comment]
@DhanyaHerath Ah! Right that was in search results I think. Will write up thanks.

**Comment by andreievg** [comment]
I think this issue needs refinement and design and probably needs to be broken down, i think the primary concern is:

> I've clicked the Filters drop down and started typing in order to select one of the items, when I hit a keyboard shortcut key (such as i) then I'm redirected to another page!!

I had this issue to and found it super annoying, it wasn't just for filters, in other areas too. I think we shouldn't have single key shortcuts that redirect you to another page (user can easily mis click entry field, and get redirected)

**Comment by andreievg** [comment]
Refinement: Not big enough to work on for the time being, there is a wider though/re-design of how filters might look anyways, closing for now
