### ISSUE TITLE
Pack Variant UI issues after merge from develop

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3110]
Notice quite a few UI issue after merging from develop: https://github.com/msupply-foundation/open-msupply/pull/3108

Some columns don't have enough width (look like they are collapsed):

* In expansions (cost)
* In Catalog item (code)

![Screenshot 2024-02-29 at 12 46 55 AM](https://github.com/msupply-foundation/open-msupply/assets/26194949/75d89f85-2e74-4b2c-a296-411f6bcae221)

Input for pack doesn't have the space it used to:

* In inbound and stocktake item edit

![Screenshot 2024-02-28 at 10 36 14 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/c85e5b1c-66c8-46b0-8bc5-2022151ccbae)

* Pack select in internal orders is not quite alligned

![Screenshot 2024-02-29 at 12 54 12 AM](https://github.com/msupply-foundation/open-msupply/assets/26194949/f24f8a6c-f4ef-4207-ade5-c5b43dc6d33c)

**Comment by andreievg** [comment]
Moving back to backload, pending stakeholder feedback and decisions on pack variant

**Comment by roxy-dao** [comment]
Closing as pack variants has been removed in favour of the new item bundling.
