### ISSUE TITLE
Unable to change sort direction in lists

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3112]
## What went wrong? 😲
 
Click on a column header to sort, click again to change the direction and nothing happens
Not on all pages though. So far has been confirmed on:

* outbound shipment list view
* requisition list view
* internal order list view 

## Expected behaviour 🤔
Should be able to change direction

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any table / list view
2. Click on column to sort
3. Click on the same column again

## Your environment 🌱

- Version: 
- mSupply version:

**Comment by DhanyaHerath** [comment]
Triage: If after investigation this requires a larger fix, we can move this to V1.8.0

**Comment by Chris-Petty** [comment]
@regotaina reports that she finds inbound shipments fine, but broken in requisitions and internal orders.

**Comment by mark-prins** [comment]
also broken in the outbound shipment list view, which is the first page I tried. All other pages tested have been ok
