### ISSUE TITLE
Merge for pack variants

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3113]
Since pack variants have item_id link, need to be able to merge them

**JOBCODE**
OMG:MERGE

**Comment by DhanyaHerath** [comment]
Note: If this isn't done that should be clearly indicated in the docs

**Comment by roxy-dao** [comment]
Moving to 2.2 milestone since pack variants have been pushed back

**Comment by roxy-dao** [comment]
Closing as pack variants has been removed in favour of the new item bundling.
