### ISSUE TITLE
Table Hide/Show columns selector not mapping selection correctly

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3125]
## What went wrong? 😲
 

https://github.com/msupply-foundation/open-msupply/assets/55115239/75994767-de48-42cc-b24d-91531dec4e55

It looks like the view is a render behind?

## Expected behaviour 🤔

The columns that I have selected in the selector are the columns I can see on the screen.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a view with a data table, which has the show/hide column feature enabled, e.g. outbound shipments
2. Uncheck a column - it will still be visible
3. Uncheck another column - now the first unselected column will hide
4. Refresh the page - all columns will be visible, even though you have some columns unchecked in the column selector

## Your environment 🌱

- Version: 1.7.0
- Platform:
  - browser (both Chrome and Firefox)

**Comment by Chris-Petty** [comment]
Bit spastic but not blocking any workflow and not in your face 100% time bad UX so severity normal it is 😅

**Comment by roxy-dao** [comment]
Cherry-picked into 1.7.0

**Comment by marthakeezy** [comment]
Just tested in V1.7.0, the filtering works fine and as expected. Build Test PASSED :) ✅

https://github.com/msupply-foundation/open-msupply/assets/153777484/3f3a4136-c9d6-4308-9ebd-8546e1658494
