### ISSUE TITLE
Should there be mandatory fields for patient creation?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3126]
## What went wrong? 😲
Currently, we can create a patient with no fields at all. 

## Expected behaviour 🤔
Don't allow if some mandatory fields are not there?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create new patient
2. GIve a name and nothing else and search
3. Just OK&Next until you land on Patient info
4. There, delete even the name you gave for search
5. See error: the Create button is still enabled (I think it should have been disabled by now)
6. Save it. And voila, you've a no-name no nothing patient
<img width="1125" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/27fd1376-0f4a-4829-b284-bb97e85ec5f1">

## Your environment 🌱

- Version: v1.6.2 exe
- mSupply version: 
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

## Additional
Noticed while testing #2925

**Comment by Chris-Petty** [comment]
Nah fields should be mandatory! Gross. Technically there is a simple work around "Don't make blank patients LOL" but I vote high because I don't want to be the one dealing with cleaning up these gosh darn no-name no nothing patients 😁

**Comment by roxy-dao** [comment]
Closed in #3244

**Comment by marthakeezy** [comment]
Hi team, 

This is still happening on RC3 on a tablet, see below

![photo_2024-04-05 10 53 26](https://github.com/msupply-foundation/open-msupply/assets/153777484/88f54a3b-59f3-40ad-bbd5-2372a002135c)

I was able to create a patient with just the name and the code, then I went in and modified it to remove the name and it allowed me to save.

**Comment by marthakeezy** [comment]
To add to this discussion - is gender a mandatory field? Because if not, there is currently no way to clear your selection, you can only choose another gender - yet, if you haven't selected any, you can still save the patient with blank gender selection. 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/172d3920-a60e-4f20-b3d0-0ec42048937b)

**Comment by clemens-msupply** [comment]
Its fixed in develop:
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/ab487f46-97e1-42bf-bf5a-efd0d1c70692)

You can clear using the X (see screenshot)
