### ISSUE TITLE
Should we be able to issue service item in oms?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3128]
## What went wrong? 😲
 
From here: #2467 . I think we should be able to include service-item in Inbound; may not be necessary in Outbound? and definitely not in Internal Order? (it's not a regular item to be ordered like that!) 

## Expected behaviour 🤔
Show service-item in shipment window as well? 

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Introduce some service items into your system
2. Open Inbound, outbound and try to add the service-item
3. See error: it doesn't show up. It should at least appear in Inbound?
4. Create an internal order and add item
5. See error: service-item appears here: it definitely shouldn't appear in this window?

## Your environment 🌱

- Version: v1.6.2 exe
- mSupply version: 

- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
@richardmoizeau @Gwalior-84 @craigdrown IDK what the workflow for service items should be. Part of me thinks they should be able to be ordered and receivable like any other item, even if rarer in use. So:

- Service items should be able to be added to inbound/outbound shipments and show in transfers etc. They are NOT added to stock. 
- Service items should be in internal orders? Perhaps unconventional? IDK! My warehouse game is weak.

Actually writing that out I have more questions... I believe a service is like "X-ray maintenance visit". Maybe it's a flat rate. Maybe it's per hr. Obviously you should invoice for services, but I'm wondering why you'd really want it anywhere EXCEPT inbound shipment... and even then calling it "inbound shipment" is pretty bizarre. "Service invoice" makes sense to me. I'd imagine having "Technician time" and "part 1" "part 2" etc. as items on such an invoice i.e. non stock items to boot.

Seems like over cooking an uncommon use case though. Limiting service items to inbound shipments and maybe outbound and making sure it actually adds the lines is probably enough.

(I clearly need to have a hoon with this functionality in mSupply and OMS...)

**Comment by Gwalior-84** [comment]
Legacy mSupply has a short section describing [Service items](https://docs.msupply.org.nz/items:adding_a_new_item#service_items).  In that example it would be on outbound shipments.

**Comment by mark-prins** [comment]
see #1323 before working on this one

**Comment by roxy-dao** [comment]
Service items are dealt with differently in Open mSupply than it is in OG, and it shouldn't be in Internal Order at all which it isn't so will close this for now until Service Charge KDD is done. Can re-open if we want it behaving differently.
