### ISSUE TITLE
LTFU status is not working

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3142]
## What went wrong? 😲
LTFU status seems to be NOT working, unless I've missed some major steps, have I? 

I call this a Normal severity; or is it high one if users expect that status in their Patient>Programs view?🤔

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Enroll a patient to HIV Care & Treatment program and create the encounter as well
2. Make the encounter date past date, sth like 2023-02-02 so that the `End of Supply` in ARV/Medication is past date like 2023-02-02
<img width="681" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/958fc919-15e0-4e0d-a324-8fdf3449e8e1">

3. Now open that patient detail
4. Switch to `Programs` tab
5. See error: the `Additional info` column is not showing any LTFU status despite it is a LTFU status (90 days after the end of supply date)
<img width="1273" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/5bd6d349-ab22-4962-9899-223e3c72827b">

## Your environment 🌱

- Version: v1.6.2 exe
- mSupply version: 
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

## Additional
Noticed while testing #2925

**Comment by Chris-Petty** [comment]
Oof, I know there are a lot of programs changes in `develop` so like the last issue I triaged, would you be able to retry this in 1.7.0-rc?

High as it just makes the program view pretty broken, though technically usable I guess...

**Comment by nisha-dangol** [comment]
> Oof, I know there are a lot of programs changes in `develop` so like the last issue I triaged, would you be able to retry this in 1.7.0-rc?
> 
> High as it just makes the program view pretty broken, though technically usable I guess...

I rechecked in v1.7-rc1 as well; still the same; the status doesn't show up!

**Comment by clemens-msupply** [comment]
You need to enter the "Quantity of pills dispensed" and then it is working here. You can say that it's a bug that it shows the end of supply though, will have a look at this now...

**Comment by clemens-msupply** [comment]
Seems to be working fine (at least "Pill count (at visit start)" or "Pill count (at visit end)" must be set to trigger the end of supply date and the LTFU status...
