### ISSUE TITLE
After fetching patient from central server, the downloaded patient should now show up in the patient list

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3143]
## What went wrong? 😲
After fetching patient from central server, the downloaded patient does not show up in the patient list

Can I call it `severity:high` since patient-search seems to be an elemental feature for dispensary?

## Expected behaviour 🤔
I expect the patient to show up in the patient list after downloading it from central server

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have at least two oms dispensary stores with patients; sth like patient1 in store1 and patient2 in store2 and sync
2. On store1, create new patient with same name of patient2 and search
3. It'll show up in search results
4. There's a download button. Download it
5. ALert will say sth like patient has been fetched, bla bla
6. Now go back to the patitent list window
7.  See error: where is that downloaded/fetched patient?

## Additional
Noticed while testing #2925 

## Your environment 🌱

- Version: v1.6.2 exe
- mSupply version: 713-00-beta11
- Platform:
  - browser (extra points if you tell us which one)
  - server (windows)
- Database type: 
  - SQLite3

**Comment by Chris-Petty** [comment]
@nisha-dangol yea I like high for this too. I am tempted by normal though as not many customers are using OMS for dispensing yet, it's pretty bare bones.

There is a chance this is fixed in v1.7.0-rc, would you mind testing if it hasn't already been fixed? I don't think there's a strong need to patch v1.6.X otherwise

**Comment by nisha-dangol** [comment]
> @nisha-dangol yea I like high for this too. I am tempted by normal though as not many customers are using OMS for dispensing yet, it's pretty bare bones.
> 
> There is a chance this is fixed in v1.7.0-rc, would you mind testing if it hasn't already been fixed? I don't think there's a strong need to patch v1.6.X otherwise
> 
> Leaving in triage till we know it still needs fixing in 1.7.

Here's an interesting result for you:
A. In datafile with patient-programs setup:
- Have two different oms-dispensary-sites (with programs setup of-course)
- Create `patient1` in `site1` and sync
- In `site2` search for that patient (and hey, you've to put whole first-name or last-name for search; for eg: `pat` doesn't work for name `patient1`)
- See error: it doesn't even show up!

B. In normal datafile (with NO programs seetup at all)
- Have two different oms-dispensary-sites
- Create `patient1` in `site1` and sync
- In `site2` search for that patient (and hey, you've to put whole first-name or last-name for search; for eg: `pat` doesn't work for name `patient1`)
- It does show up!
- Now download/fetch it
- Go back to patient list
- See error: the download/fetched patient is still not there

Either way, it's a bug! @Chris-Petty

**Comment by clemens-msupply** [comment]
I focused on case A) so far using the HP datafile:
- Create a patient `Test` in Huff and sync
- Make Slytherin a dispensary, enable programs but don't move patients
- Open Slytherin in omSupply
- Create new patient `Test` and the dialog will offer to download the existing patient
- Download patient works and the patient is no in the search result list
- The patient will now have a home symbole. When selecting the patient it will show up.

But when pressing cancel the list needs to be refreshed to show the downloaded patient, is that what you mean? I will fix this so that the patient list will get refreshed...

**Comment by nisha-dangol** [comment]
> I focused on case A) so far using the HP datafile:
> 
> * Create a patient `Test` in Huff and sync
> * Make Slytherin a dispensary, enable programs but don't move patients
> * Open Slytherin in omSupply
> * Create new patient `Test` and the dialog will offer to download the existing patient
> * Download patient works and the patient is no in the search result list
> * The patient will now have a home symbole. When selecting the patient it will show up.
> 
> But when pressing cancel the list needs to be refreshed to show the downloaded patient, is that what you mean? I will fix this so that the patient list will get refreshed...

A. In [my datafile](https://github.com/msupply-foundation/open-msupply/files/14506116/nisha-oms-database_programs-setup.zip) (with programs setup), the search simply doesn't work even when I enter the correct names and search! See [this recording for reference](http://recordit.co/DyE73OVFXI)! 

B. For non-program datafile, the search shows up the patient and when I download/fetch and search again, this time neither it shows any Home icon nor that downloaded/fetched patient is there in the patient list!

**Comment by nisha-dangol** [comment]
[Moving this here (since it seems related here)]
> There is an "!" and a retry button in the search result tab which means there central server can't be reached to search the patient. Could you please hover on it to see what it says?
> 
Ooh yes, there was this message:
<img width="799" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/71b2c8a8-47c8-441d-bb62-deeeb3133491">
@clemens-msupply But what does that message mean? like, Is it failing only for `programs` because the search seemed to work in non-programs datafile for me! 🤷
<br><br>
> Maybe this error message can be a bit more prominent?
>
Yes, I had no idea there was error message; it looked like normal `About/more info` button to me.
Maybe make it RED to look like there's an issue actually? 🤣

**Comment by clemens-msupply** [comment]
> [Moving to this issue discussion from [this-one](https://github.com/msupply-foundation/open-msupply/issues/3157#issuecomment-1981507957) (since it seems related here)]
> 
> > There is an "!" and a retry button in the search result tab which means there central server can't be reached to search the patient. Could you please hover on it to see what it says?
> 
> Ooh yes, there was this message: <img alt="image" width="799" src="https://private-user-images.githubusercontent.com/59193490/310750208-71b2c8a8-47c8-441d-bb62-deeeb3133491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDkyMTIsIm5iZiI6MTcwOTg0ODkxMiwicGF0aCI6Ii81OTE5MzQ5MC8zMTA3NTAyMDgtNzFiMmM4YTgtNDdjOC00NDFkLWJiNjItZGVlZWIzMTMzNDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIyMDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzN2U1MjZkY2VjMDEyMzExOTI4NmMzOWFjYWQwOWRlNjJjM2QyMTVhMjQ0ODVkMmQ5MzQxZmM2NGNhYjlmYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Hewu-YeIx-waJGXhEBcELZzvGpL_W01KoEM2Ak-Vmc"> @clemens-msupply But what does that message mean? like, Is it failing only for `programs` because the search seemed to work in non-programs datafile for me! 🤷

Are you sure you can reach the central from you omSupply server? (the omSupply server does the request to the central server) Do you see more information in the browser network debug console?

> > Maybe this error message can be a bit more prominent?
> 
> Yes, I had no idea there was error message; it looked like normal `About/more info` button to me. Maybe make it RED to look like there's an issue actually? 🤣

When offline its not really an error to not be able to reach central, so a bit tricky. But agree could be improved... Also don't like that the button only pops up when there was a problem this makes the UI  jump around...

**Comment by clemens-msupply** [comment]
This issue is currently blocked by: https://github.com/msupply-foundation/msupply/issues/14433

**Comment by nisha-dangol** [comment]
> > @clemens-msupply But what does that message mean? like, Is it failing only for `programs` because the search seemed to work in non-programs datafile for me! 🤷
> 
> Are you sure you can reach the central from you omSupply server? (the omSupply server does the request to the central server) Do you see more information in the browser network debug console?
> 
I re-checked; patient-search seems to be working in oms when the mSupply Cloud is in v712-09 (I can see patient returned in search window for cloud server in v712-xx) but not working for v713; so can say it's a problem for current v713(beta17)

**Comment by nisha-dangol** [comment]
Update: In mSupply v713-00-beta26, I can see the patients returned in search window (only), but the issue of patient not fetching properly and showing up afterwards in the patient list in oms still persists!

**Comment by Chris-Petty** [comment]
@clemens-msupply as 3143 was marked as fixing this, but you note there are still rough edges, can you clarify what remains to do? Or what workaround that #3217 allows?

**Comment by clemens-msupply** [comment]
> @clemens-msupply as #3217 was marked as fixing this, but you note there are still rough edges in the PR, can you clarify what remains to do? Or what workaround that #3217 allows? Is it still high priority for 1.7.00 release or can be patched?

All issues have actually been fixed in the PR (which I believe wasn't in 1.7 RC3 yet).

However, the UI could see some more improvements, e.g. no modal on top of another modal. Furthermore, there is this related issue:
https://github.com/msupply-foundation/open-msupply/issues/3412
