### ISSUE TITLE
QR code generation and printing to a label printer

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#3145]
Looks like there's a ZPL command to print a barcode...
https://gist.github.com/metafloor/773bc61480d1d05a976184d45099ef56
https://support.zebra.com/cpws/docs/zpl/BQ_Command.pdf

**Comment by mark-prins** [comment]
Can you also action this item which came up in the demo / review session:

- Change QR to use the id ( UUID ) rather than the code
