### ISSUE TITLE
UI Says invalid username or password, even if there's a server error?

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3150]
## What went wrong? 😲
 

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/6d426000-1a94-4bf2-b673-56d37fb7360d)

## Expected behaviour 🤔

Message should show something like `Server Error` or similar so the user doesn't think they've typed their password wrong and keep trying...

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Try to login to an invalid database e.g. missing a field for example

**Comment by mark-prins** [comment]
Could we add to #2945?

**Comment by clemens-msupply** [comment]
I think https://github.com/msupply-foundation/open-msupply/pull/3258 will fix this one. Please re-open if not...
