### ISSUE TITLE
Multiple encounters created when we click on OK button while creating encounter repeatedly

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3157]
## What went wrong? 😲
Multiple encounters created when we click on OK button while creating encounter repeatedly

## Expected behaviour 🤔
Create only one entry of encounter after a click on OK button and discard other continuous clicks? what if system hangs (not sure how often this can be) and you end up clicking multiple times, only to end up with multiple unnecessary entries

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Enrol a patient to a program
2. Create encounter for the patient
3. Add date and notes if any
4. Now, repeatedly click on OK button mutliple times. I clicked once, for some reason my system hanged and I ended up clicking multiple times
5. See error: the number of encounters created = no of times you clicked on that OK button

## Your environment 🌱

- Version: v1.7.0.rc1 exe
- mSupply version: v713-beta14

- Platform: browser

- Database type: sqlite

## Additional
Noticed while testing #2925

**Comment by Chris-Petty** [comment]
You, I and many other users love to spam seemingly unresponsive buttons and I'd hate to have to clean up all the duplicates! So high priority IMO.

**Comment by clemens-msupply** [comment]
You mean this one dialog?

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/f6f0cdef-9452-4116-b605-b3cf44ecbdda)

**Comment by nisha-dangol** [comment]
> You mean this dialog?
> 
> ![image](https://private-user-images.githubusercontent.com/88299195/310316886-f6f0cdef-9452-4116-b605-b3cf44ecbdda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDU2MTMsIm5iZiI6MTcwOTcwNTMxMywicGF0aCI6Ii84ODI5OTE5NS8zMTAzMTY4ODYtZjZmMGNkZWYtOTQ1Mi00MTE2LWI2MDUtYjNjZjQ0ZWNiZGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2MDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljODYzOWZmOGQ0Mzk2NmU4YWVhNjY0ZDI5ZGIyODA4Njk3YTJhZmUyMWI5ZTdlNGI2MzNkNzBiOTkzNmJkMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NR3FzvsBzST7cVlL4vzGnfpxP_6WQmaPLvaz4cNElNs)

Yeah.... Even after clicking OK, the button was still enabled, that's how I was able to click on it multiple times, leading to multiple entries of encounters!

**Comment by clemens-msupply** [comment]
There is an "!" and a retry button in the search result tab which means there central server can't be reached to search the patient. Could you please hover on it to see what it says?

Maybe this error message can be a bit more prominent?

**Comment by nisha-dangol** [comment]
> There is an "!" and a retry button in the search result tab which means there central server can't be reached to search the patient. Could you please hover on it to see what it says?
> 
Ooh yes, there was this message:
<img width="799" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/71b2c8a8-47c8-441d-bb62-deeeb3133491">
@clemens-msupply But what does that message mean? like, Is it failing only for `programs` because the search seemed to work in non-programs datafile for me! 🤷
<br><br>
> Maybe this error message can be a bit more prominent?
>
Yes, I had no idea there was error message; it looked like normal `About/more info` button to me.
Maybe make it RED to look like there's an issue actually? 🤣
