### ISSUE TITLE
Export database in android as well

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3172]
## What went wrong? 😲
 
From #2751  .You can download the database in web, but it fails in android app
May I call this `severity:high` since I feel this feature once available for desktop should be available in android as well?

## Expected behaviour 🤔
should let download in android as well

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup oms in android app
2. Go to Admin and scroll down
3. Click Download database
4. See error: it fails

## Screenshots/Recordings
https://github.com/msupply-foundation/open-msupply/assets/59193490/6defe14d-5f7e-412e-943c-8ee47c7497d4

## Your environment 🌱

- Version: v1.7.0-rc1
- mSupply version: v713-beta14

- Platform: browser

- Database type: sqlite (android uses sqlite?)

**Comment by jmbrunskill** [comment]
Thanks @nisha-dangol  can you try with this APK?
https://drive.google.com/file/d/19YluYA9nEZxRs6UnHKXm_HgEDdZpw3uS/view?usp=sharing

I think you're install had the old database name, so I'm now checking for both...

**Comment by nisha-dangol** [comment]
> I think you're install had the old database name, so I'm now checking for both...
>
Yes, @jmbrunskill, I had v1.6.2 apk installed before, over which I upgraded to v1.7 and saw that error in android
<br><br>
> Thanks @nisha-dangol can you try with this APK? https://drive.google.com/file/d/19YluYA9nEZxRs6UnHKXm_HgEDdZpw3uS/view?usp=sharing
> 
I tested using the above apk and the download now works on Android! 
Just a lilttle UI bug there: I don't like the name of the button there:
![Screenshot_20240306_122540_Open mSupply (1)](https://github.com/msupply-foundation/open-msupply/assets/59193490/1647380a-304a-4fd4-9a91-fafd19b7ace1)

**Comment by jmbrunskill** [comment]
Thanks Nisha, can you check that button name is fixed in the latest 1.7 RC? I think there might have been an issue with my build

**Comment by nisha-dangol** [comment]
> Thanks Nisha, can you check that button name is fixed in the latest 1.7 RC? I think there might have been an issue with my build

Yeah, looks good in v1.7.0-rc2 apk. PASS!
