### ISSUE TITLE
Stocktake: column labels overlap

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3173]
## What went wrong? 😲

<img width="1491" alt="Screenshot 2024-03-05 at 6 46 10 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/29044f28-f636-4578-958b-8b3ae9781591">

## Expected behaviour 🤔

No overlap :-)

## How to Reproduce 🔨

Use the language "Français (Djibouti) and do a stocktake (on laptop)

## Your environment 🌱

- Version: 1.6.03
- mSupply version: Desktop (Windows)

**Comment by richardmoizeau** [comment]
<img width="1486" alt="Screenshot 2024-03-05 at 10 51 46 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/34798675-d3e3-4f7e-8e13-d0c8d19a1893">

Another example in "Inbound Shipment": words are Emplacement (Location) & Boite (Pack)

**Comment by Chris-Petty** [comment]
This is going to be real tricky to get right with localisation.

**Comment by clemens-msupply** [comment]
Tried to add an ellipsis:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/d33eea65-09ea-4ed1-8888-4eb38949f13d)

First I thought I display the full label in a tool tip but we already have the sort helper... So not sure what to do. Can keep the ellipse and then just ignore translations that are too long? But this would only slightly be better than having the overlap...

**Comment by mark-prins** [comment]
How about changing the tooltip like this:

```
const columnLabel = column.label === '' ? '' : t(column.label);
  const tooltip = (
    <>
      {!!description && <div>{t(description)}</div>}
      {sortable ? (
        <div>
          {t('label.click-to-sort')}
          {` ${columnLabel}`}
        </div>
      ) : (
        columnLabel
      )}
    </>
  );
```

that way the tooltip says the column name in the sort hint:

<img width="302" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/cf85c47e-9567-4b99-9908-ab61cbabdaf4">


and displays the column name if there's no sort:

<img width="138" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/883fa906-3e46-4c7b-a355-4b884d773f0b">
<img width="272" alt="Screenshot 2024-03-16 at 2 55 25 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/c029a4b3-cf45-4f8a-ac38-d711c6c7ecc4">

**Comment by marthakeezy** [comment]
Just tested on V1.7.0, the column titles don't seem to be overlapping anymore, however there is still the issue of titles not displaying fully across omSupply, not only under Stocktakes. However, it is a different issue :) This one is PASSED ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/369f5001-30af-4a2f-b797-723df17b6339)
