### ISSUE TITLE
Outbound Shipment: can't see the whole batch in table

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3174]
## What went wrong? 😲

<img width="1483" alt="Screenshot 2024-03-05 at 7 00 30 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/bc87917a-26fa-4ee7-8436-66c21b6385b9">

batch number is quite a critical data to see, should always be visible entirely

## Expected behaviour 🤔

batch number is quite a critical data to see, should always be visible entirely

## How to Reproduce 🔨

Create a outbound shipment for an item with batch number that have > 4 or 5 characters. 

## Your environment 🌱

- Version: 1.6.03
- mSupply version: Desktop (Windows)

**Comment by Chris-Petty** [comment]
Code, name and batch are all kinda important and all truncated, and it'll be significantly worse on android tablets. 

No clear resolution, design probably needs review. Also doesn't technically stop any workflow so not high severity, but annoying enough to not be low.

**Comment by richardmoizeau** [comment]
problem is that when shipment is finalised, you can see the details (modal) anymore so you have no way to see the batch number you just issued or received. I would flag as quite severe.

**Comment by clemens-msupply** [comment]
@mark-prins show a tooltip? or try to detect if there is an ellipse and only then show the tooltip? (ellipse detection might be unreliable though)

**Comment by mark-prins** [comment]
I would make the column wider, and also change the cell to be the `TooltipTextCell` which would show tooltips. no need to make them conditional on text overflow

**Comment by clemens-msupply** [comment]
@mark-prins there is also this extra padding:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/5eccba4c-4508-4be8-8896-9d5b4b6d29fc)

See the Code column to see the offset compared to the header. This padding seems to be missing for the Name column. Do you think we could remove this? There is also quite a bit of padding between the column that could potentially be reduced?

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/948bc243-3760-4d47-ab3c-2c2e247ccd7a)

**Comment by mark-prins** [comment]
> there is also this extra padding

some of this is deliberate - the design had a lot of padding on tables. Could probably reduce it, at least in the header. and the padding around the numeric value is probably not intentional

**Comment by marthakeezy** [comment]
Just tested in V1.7.0 and the tooltip is appearing as expected :) Test passed ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/f1ec11b2-e510-4fe5-9c45-d4aa1dde6f98)
