### ISSUE TITLE
Stocktake: something's wrong with the pagination

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3175]
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply/assets/74992958/cb0ad123-6141-4728-bb1f-244d65a3e37d

Pagination is set for 100 or 500 lines per page but I can only see 1 or 2 lines on the table

## Expected behaviour 🤔

Should show the number of lines set for the pagination. 

## How to Reproduce 🔨

https://djibouti.msupply.org:8000/inventory/stocktakes/6657?sort=itemName&page=27
see bitwarden for access
create a stocktake for all items with stock 

## Agreed solution

Quick fix, remove group by, and add a new issue to experiment/outline group by in back end.

Make sure new issue is name ("Move group by in stocktake to back end")

## Your environment 🌱
- Version: 1.6.3
- Platform: Browser (Chrome)

**Comment by mark-prins** [comment]
The issue is that the pagination happens server side, but the 'group by item' function is client side e.g.

https://github.com/msupply-foundation/open-msupply/assets/9192912/33bfb318-6e48-4d46-b906-981c60173f20

A possible fix would be to group by item server side. what if this was a different query?

**Comment by Chris-Petty** [comment]
Hahaha I made exactly the same video as @mark-prins and then scrolled down...

I reckon fixing it server side is the easiest way to make it clearer, not sure how you'd do it without a different query. Do we have an API design process or as things come up just yolo/try following existing patterns?

**Comment by Chris-Petty** [comment]
Doesn't block any workflow, just an odd quirk...

**Comment by richardmoizeau** [comment]
does not block workflow but could mislead user to think there are only 1 or 2 items for the stocktake

**Comment by DhanyaHerath** [comment]
@Chris-Petty I'd bump up the severity here a bit - what do you think? I could see this being a support issue multiple times...

**Comment by Chris-Petty** [comment]
Maybe it'd be more obvious if there was a separate tab for separate tab for grouping by item, rather than a toggle:

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/44aa5222-b7f6-487e-8e48-3d943d5c29d9)

Either way, getting the right pagination data may be easiest as a separate backend endpoint as @mark-prins says.

**Comment by clemens-msupply** [comment]
Am I right that if there would be a third item in this Stocktake you would have to go to page 677 to see it? This would IMHO be the main issue.

Besides that, isn't handling such a Stocktake nearly impossible? For example, if I have a stockline in stock which is somewhere on page ~300 how do I find it?

But yes having a "groupedStocktakeLines" endpoint would be useful. (I don't think you can make it an option for the existing endpoint)

**Comment by Chris-Petty** [comment]
It is sort of crazy that @richardmoizeau's data appears to have at least 500 lines for a given item (pagination at 500 and using group by only rendering 1 line). So yes, if you were using pagination of 20 and an item with 500 lines in the stock take you'd have to go through ~25 pages to get to the next item. Not sure what you mean by 677 pages though.

With that said, unless our return shape is truly wild, wouldn't the "group by item" show the wrong totals for the item if it's only grouping a page of 20 lines client side, out of 500+ lines? Definitely need to do server side grouping in that case.

**Comment by andreievg** [comment]
I think if we are dealing with sorting, filtering, and pagination, we should really do it on back end. It's a bit of a refactor.

We can also remove grouping by item for now for stocktake to solve this problem ?

**Comment by Chris-Petty** [comment]
> I think if we are dealing with sorting, filtering, and pagination, we should really do it on back end. It's a bit of a refactor.
> 
> We can also remove grouping by item for now for stocktake to solve this problem ?

100% I think all should happen on backend, can't do it on frontend if paginating at all!

@richardmoizeau @mark-prins what do you think of removing `group by item` until we implement a backend solution?

**Comment by mark-prins** [comment]
If we can get the back end paginated grouping query done in v2.1, sure. I like the 'group by item' and don't want it removed indefinitely

**Comment by andreievg** [comment]
Quick fix, remove group by, and add a new issue to experiment/outline group by in back end

**Comment by roxy-dao** [comment]
> Quick fix, remove group by, and add a new issue to experiment/outline group by in back end

#4859

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Go to stocktake
- [ ] Shouldn't see the group by item toggle anymore **-PASS-**
