### ISSUE TITLE
Internal Orders (and possibly other views?): Select actions > Delete selected lines does not work

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3176]
## What went wrong? 😲

https://github.com/msupply-foundation/open-msupply/assets/74992958/1baf305a-3bc7-494c-a4b3-bdc7d41cc26c

## Expected behaviour 🤔

Should delete selected lines. 

## How to Reproduce 🔨

see video

## Your environment 🌱

- Version: 1.6.03
- Platform: Browser (Chrome)

**Comment by roxy-dao** [comment]
Should be fixed in 1.7 with #2776

**Comment by richardmoizeau** [comment]
Thanks Roxy ;)
