### ISSUE TITLE
Required currency id on invoice

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3182]
## Is your feature request related to a problem? Please describe 👀
`currency_id` is currently an optional field and should be a required field since `currency_id` on invoice saves home currency id on default.

### Describe alternatives you've considered 💭
Leaving it 🤷🏻

**Comment by Chris-Petty** [comment]
Functionally it's enforced so borderline a refactor aye?

**Comment by roxy-dao** [comment]
> Functionally it's enforced so borderline a refactor aye?

Oh I thought I put that on 😆  Thanks Chris

**Comment by clemens-msupply** [comment]
Just for my understanding, why is there always a home currency? How is this set? when creating a store? or is there a default?

**Comment by roxy-dao** [comment]
> Just for my understanding, why is there always a home currency? How is this set? when creating a store? or is there a default?

Home currency is set in OG `Currencies` window and is set to `USD` by default when OG is installed then can be changed in the currency window. @Chris-Petty told me that currency_id is always saved on invoices 👀

**Comment by Chris-Petty** [comment]
Even inventory adjustments have the default currency :) 
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/d1f8e813-bc91-43ea-afe6-8ee569b168cb)

**Comment by clemens-msupply** [comment]
so its guaranteed that a store has a currency set? I actually had the same question here: https://github.com/msupply-foundation/open-msupply/pull/3298#discussion_r1525645255

**Comment by roxy-dao** [comment]
> so its guaranteed that a store has a currency set? I actually had the same question here: [#3298 (comment)](https://github.com/msupply-foundation/open-msupply/pull/3298#discussion_r1525645255)
> 
> EDIT: I mean there can't be some old invoiced with currency_ID = NULL?

Currency is set by default as `USD` when OG is first initialised. 

```
CREATE RECORD:C68([currency:8])
[currency:8]ID:1:=UUID_generate
[currency:8]rate:2:=1
[currency:8]currency:3:="USD"
[currency:8]is_home_currency:4:=True:C214
[currency:8]is_active:6:=True:C214
SAVE RECORD:C53([currency:8])
pm_unload_record(->[currency:8])
```

Old invoices that have null currency_ID should update on migration to omSupply with default currency (as seen in PR) 👀

**Comment by clemens-msupply** [comment]
> Old invoices that have null currency_ID should update on migration to omSupply with default currency (as seen in PR) 👀

Can't see where it is set to the default currency, that why I am asking here:
https://github.com/msupply-foundation/open-msupply/pull/3298/files#r1525645255

(A test for this case would be good as well... What is 4D sending in this case? an empty string or null/undefined?)

**Comment by Chris-Petty** [comment]
> > Old invoices that have null currency_ID should update on migration to omSupply with default currency (as seen in PR) 👀
> 
> Can't see where it is set to the default currency, that why I am asking here: https://github.com/msupply-foundation/open-msupply/pull/3298/files#r1525645255
> 
> (A test for this case would be good as well... What is 4D sending in this case? an empty string or null/undefined?)

4D will definitely send an empty string
