### ISSUE TITLE
Asset location editing

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3193]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

The asset detail page has the ability to edit locations which are internal to the asset. This is a new data type, and input type with the Mui Chips / tag style interface and the ability to add locations

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/74c6b7b8-f3f5-4950-a3b1-b670b755e445)

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/45b0597a-e665-4128-870b-1836d33330b7)

## Describe the solution you'd like 🎁
We need:
- [x] Service layer for `asset_internal_location`
- [x] Query and mutations for `asset_internal_location`
- [x] A loader would be helpful, then we could return locations with the main asset query
- [x] Similarly, the `updateAsset` mutation: can we provide a list of location ids for this?
- [ ] A UI control to add and remove locations, picking from a list
- [ ] Some way (?) to add a location from this control too, and once added, add to the list for that asset

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by adamdewey** [comment]
@mark-prins @jmbrunskill - just wondering what's meant by 'new data type' here?

Are we still planning to link standard stock storage locations in the section that says `Cold storage location` ?

The summary of the chat we had in the CCEI product Telegram chat was: 

- We would use Store to track where assets are located
- We would use Location(s) to track what is located inside assets

That's still my current understanding - just wanted to check I hadn't missed anything :)

**Comment by jmbrunskill** [comment]
@adamdewey @mark-prins my intention is for the `asset_internal_location` table to just contain the link between an existing location and the asset. Because we want to allow multiple locations inside an asset, we can't just add an `internal_location_id` to the asset record, we need another table capture the links.
(It could be a json field or something, but I think this is clearer)

**Comment by adamdewey** [comment]
Ah thanks @jmbrunskill - so I understand it's a new technical data type, not a new location concept - that's all good, cheers! 😅
