### ISSUE TITLE
Warn/handle when setting all return quantities to 0

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3195]
Epic #2897 

## Is your feature request related to a problem? Please describe 👀

If you don't set any quantities to return...
![Image](https://github.com/msupply-foundation/open-msupply/assets/55115239/7d4f6167-1166-41a5-953f-a6758f2595b0)

Then you get a blank return reasons step, which isn't ideal:
![Image](https://github.com/msupply-foundation/open-msupply/assets/55115239/5addb50f-055c-4312-a070-71ef39b9094f)

But we delete lines by setting their quantities to 0, so this should be allowed!

## Describe the solution you'd like 🎁

When you click `OK & Next`, check if quantities are set. If none, show a confirmation modal? And on confirm, close the modal rather than going to the next step.

We should probably display something different based on whether we are adding vs editing (i.e. "no lines will be added" vs "all lines for this item will be deleted")

**Comment by CarlosNZ** [comment]
Closed by #3251
