### ISSUE TITLE
Won't let me enter the double-digit sell price in batch details when entering stocks

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3206]
## What went wrong? 😲
 
Won't let me enter the double-digit sell price in batch details when entering stocks

## Expected behaviour 🤔
entered value should not change automatically like that! because of this, can I call this `severity:high`

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a new stocktake
2. Add item and batch, packs info
3. Switch to Pricing tab
4. Simply click Next or (hit Tab if on desktop) to land on Pack Sell Price
5. Try to enter price of double-digit like 12 and hit Next
6. See error: it automatically changes `12` to `1.2`
7. See the same behavior in Inbound shipment as well

## Screenshots/Recordings
[This one's in](https://recordit.co/ntxiEVCnbH) desktop. In exe, both sell & cost price looks affected
[THis one's in](https://github.com/msupply-foundation/open-msupply/assets/59193490/e5e2a715-718e-4ddf-b0ad-0b1989832c5c) tablet

## Your environment 🌱

- Version: v1.7-rc1
- mSupply version: v713-beta16 

- Platform: Android, Browser

- Database type: sqlite

**Comment by CarlosNZ** [comment]
I think this is the same as this existing issue: https://github.com/msupply-foundation/open-msupply/issues/2918

**Comment by nisha-dangol** [comment]
> I think this is the same as this existing issue: #2918

oops, yes! 
I can close this, can continue in #2918
