### ISSUE TITLE
Selected tab underline doesn't move correctly with SidePanel open/close

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3213]
## What went wrong? 😲
 

Not hindering anything, just a funky lil UX moment.

Details tab is underlined: 
<img width="1048" alt="Screenshot 2024-03-07 at 11 13 55 AM" src="https://github.com/msupply-foundation/open-msupply/assets/55115239/152d8f36-244f-46e8-ae22-80b3b6679a50">

I open the side panel... the underline didn't follow the `Details` tab name 😢:
<img width="1052" alt="Screenshot 2024-03-07 at 11 14 01 AM" src="https://github.com/msupply-foundation/open-msupply/assets/55115239/ad1753a4-265a-4f72-91b3-579fa42b6365">

Close the side panel... now it moves! So it's in the wrong place AGAIN!
<img width="1040" alt="Screenshot 2024-03-07 at 11 14 05 AM" src="https://github.com/msupply-foundation/open-msupply/assets/55115239/e8972740-a476-4f05-94bc-35cf8ff3c9bb">

Without looking into it, I am slightly surprised that the tab titles move, but their underline doesn't lol. 

## Expected behaviour 🤔

Active tab remains underlined as the side panel is opened and closed.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

On a detail view (e.g. an inbound shipment), open and close the `More` side panel. See the tab underline 

## Your environment 🌱

- Version: 1.7.0

- Platform: browser (chrome)

**Comment by CarlosNZ** [comment]
We dealt with this once before: https://github.com/msupply-foundation/open-msupply/pull/969
Not sure if it's the same problem come back, or something slightly different, but the solution used in that PR would probably be what we'd need.

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc4, and the issue is fixed - checked Cold Chain and Inbound Shipments as mentioned above. Build test passed! :) ✅
