### ISSUE TITLE
v2.0.0 (Planned for 15 May) 

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3222]
# Key Aims

- Pack Variants
- Supplier/Customer Returns
- Asset (CCE) Management
- Migration pathway from mSupply Desktop and Mobile to Open mSupply

## Deadlines (in NZT)

Date started: Thur 21 March, 20204
PR deadline: Wed 17 April, 2024
PRs merged: Wed 24 April, 2024
Release: ~~Wed 8 May, 2024~~ Wed 15, 2024

**Comment by roxy-dao** [comment]
Version 2.0.0?

**Comment by Chris-Petty** [comment]
@roxy-dao yup as Andrei said at standup, probably gonna label this one 2.0.0 due the the big features introduced, particularly central server changes.

**Comment by roxy-dao** [comment]
Released on Wednesday 15th.
