### ISSUE TITLE
Encounter modal remains open and editable after deleting (further changes not saved)

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3227]
## What went wrong? 😲

Encounter modal remains open and editable after deleting (further changes not saved). This misleads users, not good UX.

## Expected behaviour 🤔

Deleting closes the modal and the encounter isn't in lists.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup programs and enrol a patient to a program as well
2. Create an encounter for the patient
3. Besides the status, there is delete icon. CLick it
4. Proceed to delete that encounter in the confirmation modal
5. See error: the supposed-to-be deleted encounter is still open and editable. You can keep editing and save, and it saves as well
6. Now go back to patient details and switch to encounter tab, only now you see that encounter is deleted and doesn't exist! I mean why let me edit any deleted entry at all?

## Your environment 🌱

- Version: v1.7.0-rc1 
- mSupply version: v713-beta16

- Platform: browser, server exe

- Database type: sqlite

**Comment by clemens-msupply** [comment]
Yes agree should be editable, i.e. disable the form. Main reason was to give the user the change to undelete it. I would say low priority though....

**Comment by Chris-Petty** [comment]
@nisha-dangol 😆 a little more tact would be kind. Bear in mind this is public, WHO could come have a looksie and find this curious.

**Comment by clemens-msupply** [comment]
I just checked when deleting the encounter you are redirected away from the encounter. So you have to press forward twice to get back to the encounter or remember the url. I could disable all the fields in the encounter when marked as deleted, but then I think it quite an edge case. I am closing this issue for now. Please feel free to reopen if you think differently.
