### ISSUE TITLE
Outbound shipment line edit modal truncating important column values, over crowded with horizontal scroll

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3242]
## What went wrong? 😲
 

We have worked really hard to get everything visible on this table without a horizontal scroll.. but now look what's happened!

<img width="1034" alt="Screenshot 2024-03-08 at 5 11 30 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/4d817a83-cf63-4bc3-8081-16ac62f965d8">

## Expected behaviour 🤔
All information should be visible. We need to rationalise what is shown and/or make the modal wider.
If that isn't enough
* tabs?
* some other affordance to show that functionality is available?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Version: 
- mSupply version: 

- Platform:

- Database type:

**Comment by andreievg** [comment]
@mark-prins I think this is the result of pack variant changes, I was wondering how do we control layout of columns in the tables ? What pattern/rules we should follow. 
Can we reduce width of some of the quantity columns ?

**Comment by Chris-Petty** [comment]
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/a0d837ca-a13b-42bb-85f4-90c4dcff1803)
Truncating some columns is pretty painful too!

**Comment by mark-prins** [comment]
I thought the pack variant columns looked about the same width, or only slightly wider - didn't make a lot of impact, methinks.

The `Pack Sell Price` is looking wider than necessary to me (was that added recently? I don't remember it being there).
If anything we need to make some columns wider, to avoid truncation, as you say @Chris-Petty.

No easy solution - though maybe making the modal wider will be enough? Hoping that we can drop a column or two as well

**Comment by andreievg** [comment]
There were quite a few conflicts in the tables, when pack variant went in, but had to resolve conflicts a few times, so could have missed this. Anyways, I wanted to point out what I think is the origin of the duplicates

**Comment by roxy-dao** [comment]
> There were quite a few conflicts in the tables, when pack variant went in, but had to resolve conflicts a few times, so could have missed this. Anyways, I wanted to point out what I think is the origin of the duplicates

I think that was my fault =[ sorry
