### ISSUE TITLE
Vertical scroll in modals breaks the rounded corners

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#3246]
Fairly minor cosmetic thing, but I noticed that we lose the rounded corners on modals when a vertical scroll bar is present:
![Image](https://github.com/msupply-foundation/open-msupply/assets/5456533/d0dbf093-8a4b-4ae0-a133-fbe9b6f37169)

For the horizontal scrollbar, it works okay as the scroll bar is inset within the window, so I wonder if it would be straightforward to do the same thing for the vertical one?

**Comment by CarlosNZ** [comment]
> @CarlosNZ why have you added triage back?

I hadn't realised I had 🤷‍♂️

Sorry, no idea what happened there. :/

**Comment by mark-prins** [comment]
there shouldn't be a vertical scroll - would be good to find out why that's come in and adjust the table height to remove the scroll. The table area is scrollable, which should remove the need for the general modal vertical scrollbar

**Comment by regotaina** [comment]
It looks good on RC3 - like Mark said, no scroll bar:

![Screenshot 2024-05-08 at 3 41 26 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/fe424386-6f78-429e-90d2-298d22f03de3)

PASSED the test! 🥇
