### ISSUE TITLE
Range error - Firefox

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3248]
## What went wrong? 😲
Went to add an item to an outbound shipment and got this error
![photo_2024-03-11 12 39 18](https://github.com/msupply-foundation/open-msupply/assets/61820074/badf11e7-2a86-49b5-8347-291f45c12ac0)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Version: 
- mSupply version: 

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
I can't reproduce this -- can you provide more specific steps to produce it?

**Comment by roxy-dao** [comment]
Oh that's weird... it's not happening anymore 👀
