### ISSUE TITLE
Reflect v6 (open-mSupply Central) sync status in UI views

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3266]
## Is your feature request related to a problem? Please describe 👀

Sync View UI, should reflect Central Server Sync some how

## Describe the solution you'd like 🎁

- [ ] Make sure the Total Records to Push is displayed correctly
- [ ] Display the total of `v6` and `v5` records to push and pull under each step

### Describe alternatives you've considered 💭
Would be nice to somehow that shows how many v6 (open-mSupply) and v5 (legacy) records are being pulled or pushed.
It would also be good if we could evaluate how to handle certain errors, say when v6 isn't available, should we show an error but carry on?

### Moneyworks Jobcode 🧰

OMSCC:AST

**Comment by mark-prins** [comment]
Similar enough to #3119 which is completed now
