### ISSUE TITLE
Cold Chain: error appears when interacting with the Monitoring Graph

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3277]
## What went wrong? 😲
 

Navigating under **Cold Chain -> Monitoring -> Chart** -> and interacting with the graph by moving the line indicating a timeline triggers an error 'Oops. Something's gone wrong. Try again'. 

https://github.com/msupply-foundation/open-msupply/assets/153777484/0b8cd844-b63d-440d-89e5-b33e1c96d6a8

## Expected behaviour 🤔

We are able to interact with the graph without running into any issues. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Monitoring -> Chart
2. Select any date period or no filters at all
3. Press on the screen -> a line indicating a point in time should appear
4. Try moving it around -> see error

## Your environment 🌱

- omSupply Version: 1.7.00

**Comment by roxy-dao** [comment]
No one is using cold chain atm, so could this be moved to Severity: Normal and milestone 1.8?

**Comment by adamdewey** [comment]
When is 1.8 due for release?

**Comment by roxy-dao** [comment]
> When is 1.8 due for release?

2.0 sorry, Wed 8 May, 2024

**Comment by adamdewey** [comment]
Thanks Roxy, think it's probably ok to leave it until then - might be a couple of clients wanting to use it soon after 2.0 though!

**Comment by regotaina** [comment]
Got the same message on Desktop :( 


Uploading Screen Recording 2024-03-20 at 3.33.24 PM.mov…

**Comment by roxy-dao** [comment]
Moving to `Hotfix` since blocks workflow

**Comment by marthakeezy** [comment]
Happening when accessing Inbound Shipments on RC3 

https://github.com/msupply-foundation/open-msupply/assets/153777484/3249e097-6e26-4dd7-bd3c-3621dbec5e4e

@roxy-dao @Chris-Petty

**Comment by AnushaUp** [comment]
Tested in openmSupply `v1.7.00-rc4` 
couldn't recreate the above issue in OMS desktop and browser. PASS
