### ISSUE TITLE
Cold Chain: graph data is inconsistent with the temperature logs

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3283]
## What went wrong? 😲
 

I was testing #2720 when I noticed the following - graph gaps are inconsistent with the temperature logs we can see in omSupply and CCA. 

**Screenshot 1:** You can see EE sensor shows graph entry from 02:07 onwards, and FF drops out that time and does not come back until 03:43

![photo_2024-03-14 11 47 50](https://github.com/msupply-foundation/open-msupply/assets/153777484/b7949622-9d7c-4473-a104-aa2888a40eac)

**Screenshot 2:** When I go to logs, EE sensor does not have any temperature readings for that time period, and FF does -> so one of the issues is that EE graph should drop out and FF graph should have data, not the other way around. 

![photo_2024-03-14 11 48 17](https://github.com/msupply-foundation/open-msupply/assets/153777484/9e88a5a9-3212-4859-bf66-6f80f3e8c0ac)

Screenshot 3: FF sensor data present in CCA

![photo_2024-03-14 11 48 44](https://github.com/msupply-foundation/open-msupply/assets/153777484/1339f99f-c7fa-40b4-9c46-abdeb0310886)

Screenshot 4: EE sensor data is not present in CCA

![photo_2024-03-14 11 48 56](https://github.com/msupply-foundation/open-msupply/assets/153777484/1c66423a-a40e-415e-9e90-af997be4af7b)

## Expected behaviour 🤔

If the sensors do not produce any temperature readings, then the graph on omSupply should show graph gaps as there will be no records present. Those gaps need to be displayed for the correct sensors and for the correct time period. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Connect 2-3 sensors to CCA -> CCA to omSupply -> omSupply to mSupply (perform a basic setup)
2. Leave the sensors running overnight, produce a few breaches (maybe one hot and one cold)
3. Examine the graph under Cold Chain -> Monitoring. 
4. If any gaps are present, cross-check with omSupply Logs and with CCA to make sure the gaps are valid
5. See error

## Your environment 🌱

- omSupply Version: 1.7.00

**Comment by andreievg** [comment]
Had a chat with @marthakeezy, there did seem to be some gaps in the CCA data, but it wasn't quite consistent with the way it is displayed. I think it's best to get the sqlite data file, and check that date range in the screenshots in more detail.

For some reason the 'download' button was greyed out when we tried to export data ¯\_(ツ)_/¯

**Comment by marthakeezy** [comment]
File sent to Andrei ^

**Comment by andreievg** [comment]
Here is the data file: https://drive.google.com/drive/u/1/folders/114gjyJ0s-GPe23PkAh-KzaRRHgUagEMX

**Comment by fergie-nz** [comment]
I think this is a result of how the data is being rendered with gaps, but is consistent with gaps in the data.

I'm seeing from the logs that the F3 sensor does have a gap in the data that corresponds to the gap in the graph with some time rounding involved:

![Image](https://github.com/msupply-foundation/open-msupply/assets/90807420/1307e524-7af3-4b2b-9dde-70607a833dd4)

(Note the times in the screenshot are UK times which are 13 hours behind NZT in March)

And the threshold for when a gap in the graph is displayed is dependent on the range selected. In this case there is a gap in the graph when an hour of data is missing.

I think we can close this unless we want to change the behaviour of when gaps appear. Maybe the appearance of gaps being a bit less sensitive so that they only show up when there are sustained gaps in data?

**Comment by mark-prins** [comment]
There's something in the chart data query causing the issue - changing the date range from `09:00` to `09:43` produces different gaps. I would like to implement #3679 and close this issue.

**Comment by marthakeezy** [comment]
Cold Chain graphs have been simplified greatly, and when monitoring them for the past 2 weeks, I could not locate any discrepancies. Produced a few hot & cold breaches on multiple sensors, left overnight, disconnected and reconnected the sensors, changed logging intervals and the data display between CCA and omSupply has been consistent. 

Will reopen the issue if I see any issues again, otherwise build test passed! :) ✅
