### ISSUE TITLE
Log types for returns

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3286]
## Is your feature request related to a problem? Please describe 👀

Inbound/outbound returns have logs saying "shipment created" etc.

![Image](https://github.com/msupply-foundation/open-msupply/assets/55115239/35891fa2-255b-49e8-ae29-149e60ca2bd7)

## Describe the solution you'd like 🎁

It should say Return created.

### Describe alternatives you've considered 💭

In the backend, the `ActivityLogType` is actually just `InvoiceCreated`, hence why this wasn't picked up yet... so I guess we either take rename that to `ShipmentCreated` and add a new `ReturnCreated`, or we change the invoice translation strings from "shipment" to something more generic? 🤷‍♀

**Comment by andreievg** [comment]
One proposal is to add ShipmentCreated and ReturnCreated, leaving InvoiceCreated (but marking as 'deprecated' in some way ?)

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply desktop `v2.1.0-IA-test-2`


- [ ] Go to the log tab of an existing return
- [ ] Logs just have `Created`/`Picked` etc, no reference to `Shipment`
- [ ] Go to the log tab of an existing shipment
- [ ] Logs just have `Created`/`Picked` etc, no reference to `Shipment`

**Comment by AnushaUp** [comment]
@lache-melvin Hi, I can see these in recent build. What is the expected behaviour here?
![Screenshot 2024-06-12 at 4 23 35 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/63f3b540-2aac-4bd0-b54e-3afff9e1f721)

**Comment by lache-melvin** [comment]
> @lache-melvin Hi, I can see these in recent build. What is the expected behaviour here?

Hi @AnushaUp - that's great, you can see the first line just says `Created` rather than `Shipment created`, and `Status changed to Delivered` rather than `Shipment delivered` 🙏
