### ISSUE TITLE
Cannot 0 stock in stocktake

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3288]
## What went wrong? 😲
The new number changes has made it impossible to 0 out stock in a stocktake.

## Expected behaviour 🤔
Should be possible to 0 stock line in a stocktake.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new stocktake
2. Add a stock line that has stock
3. Enter `0` in `Counted packs`
4. See that you cannot

## Your environment 🌱

- Version: 1.7
- mSupply version: 

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Closed by #3291

**Comment by marthakeezy** [comment]
Just tested on V1.7.0 and I was able to Create & Finalise a Stocktake with an item that initially had 300 quantity, and I changed it to 0 and was able to save the changes. Build test PASSED :) ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/81333316-bc57-4514-bd64-7256c7f0a980)
