### ISSUE TITLE
Improve integration process for incoming records in central sync

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3294]
## The suggestion

Right now after receiving a batch of records from a remote site, we put them into the standard sync buffer.
Once the `total` record count is sent, we trigger the sync process to do the translation and integration steps.

This has 2 issues.

1. It means that every push from a remote site would trigger a central server sync, this could be a lot of unnecessary load when we have a lot of site pushing records
2. There's a risk of incorrectly integrating records, for example if a batch of 20 records has been uploaded for a remote site but there's more records that need to be sent, and the normal sync process starts, it will try to integrate these 20 records, which might result in foreign key issues.

### Why should we invest time in this?

The risks explained above are significant and we don't want to have production issues in a huge sync system in future deployments.

### Are there any risks associated with this change?

If done incorrectly we could make things worse :)

### How much effort is required?

Sync changes always require significant effort and we might want to consider different design options such as a dedicated incoming records sync buffer? Global mutex on integration? Integration on sync trigger?

**Comment by clemens-msupply** [comment]
> 1. It means that every push from a remote site would trigger a central server sync, this could be a lot of unnecessary load when we have a lot of site pushing records

Currently, the sync process is run ever X minutes so it doesn't make a difference. However, if a local change would trigger a sync then it could become an issue and we could skip pulling central/remote records?

> 2. There's a risk of incorrectly integrating records, for example if a batch of 20 records has been uploaded for a remote site but there's more records that need to be sent, and the normal sync process starts, it will try to integrate these 20 records, which might result in foreign key issues.

Yes, in general, I think we should collect the push sync records in a transaction to get a consistent snapshot (what I think we are currently not doing).
However, I can't think of a use case where it would currently would fail...

**Comment by jmbrunskill** [comment]
> EDIT: is this for central omSupply? if yes please ignore this comment

Yes it is :)

Your point about doing sync buffer in a transaction is a good one, but difficult because we send data from remote in batches. We need a whole set of batches before integration (at least according to @andreievg)
I think mSupply has a site specific buffer which might help...

**Comment by andreievg** [comment]
Btw what we do with mSupply:
* When we start integrating record on central (after v5 push from remote shows nothing else more to send), we 'lock the site'. Any subsequent API request while site is locked will show status 'integrating'
* omSupply will poll and wait for integration to finish on mSupply central end, then it will resume with pulls (by the way, this has caused some issued, when it takes awhile for integration to happen)

Can we do something similar with omSupply ? Should be pretty reasonable to do integration for only a particular site by passing through site id and filtering sync buffer in integration (and only do integration of course). I think a bit more refinement would need to be done on this idea, I am keen to chat about it.

**Comment by andreievg** [comment]
Summary from meeting:

![PXL_20240404_023217707](https://github.com/msupply-foundation/open-msupply/assets/26194949/5386a18f-e340-4514-8cc3-730e634f4221)

1 - We can integrate on central by 'sync_site_id' on sync buffer
2 - During remote sync (from client perspective), can set 'sync_site_id' = null and that integration is done by filter sync_site_id = null
3 - The 'trigger' to start integration can remain as "no more records to push"
4 - We need to 'lock' the site from syncing while we do the integration, at the very least we should protect the 'Push' endpoint from receiving any more records from the site (maybe we can pull though, but I think we reduce use cases by locking both)
5 - Remote site should do some sort of polling/waiting while integration is in progress
6 - Errors to be recorded on sync_buffer, but we shouldn't lock the site from future syncing (don't roll back transaction, just like we do now I think for remote sync integration)
7 - If server crashes while half way through integration, transaction should really be rolled, and in the next sync it from that site it will be re-integrated
8 - If the site completely dies before integration happens, and has to be re-initialised, we still have the sync buffer and can force it's re-integration by setting sync_site_id = null
9 - Would be great to have an admin page at some point, where we can run and display either pre made or some arbitary queries (for things like what is waiting integration, how many records of type need to sync to a site)
10 - When we change store to a new site, or for example change asset to a new store, we can re-touch change logs to allow re-syncing of those records to a new site (the query to figure out which one's to touch should be pretty much the same as the query we do to figure out what records need to be synced to site, except with a new store id, or filtered further by table)

I think we can describe the above in REAMDE.md at some point (sync one)

Future optimisaions:

We can optimise some of the integration, by for example allowing "pushing" of the next batch of sync while integration is in progress (by recording a cursors on sync buffer for site)

Can re-start integration on startup if it was cancelled, with the similar cursor to the above.

@clemens-msupply @Chris-Petty @jmbrunskill 

I think the above summarises the things we talked about

**Comment by jmbrunskill** [comment]
Thanks @andreievg looks like a good summary to me

**Comment by andreievg** [comment]
Going to take this over to try and finish for 2.0 PR deadline

**Comment by Chris-Petty** [comment]
@andreievg something spicy to be prepared for in 2.1.0 - store merge be coming. So OMSCentral will need to handle merge messages too.

**Comment by andreievg** [comment]
> @andreievg something spicy to be prepared for in 2.1.0 - store merge be coming. So OMSCentral will need to handle merge messages too. I figure update all the store IDs for the change log to kept?

Oki @Chris-Petty, sounds like we need another issue for this. Ouch though, sounds complex

**Comment by Chris-Petty** [comment]
@andreievg yea I guess it'll have to be in the store merge epic coming soon(tm)
