### ISSUE TITLE
Cold Chain: Serial Number sort is not sorting

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3302]
## What went wrong? 😲
 

Under Cold Chain -> Sensors, if you click 'Serial Number' to try and sort the content, the sort is not working (e.g. all information stays the same). 

https://github.com/msupply-foundation/open-msupply/assets/153777484/7826400b-4ccf-4778-a6cf-0c728ad2543e

## Expected behaviour 🤔

When clicking on the title, the expected behaviour is that rows will be re-arranged according to sort (e.g. Serial Numbers will show alphabetically)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Sensors
2. Click on the arrow next to 'Serial Number' to attempt and sort
3. See error (nothing is happening)

## Your environment 🌱

- omSupply version: 1.7.00

**Comment by roxy-dao** [comment]
This has been fixed by #3112. Should be out in next RC build or release build, whichever comes first.
