### ISSUE TITLE
Non-catalogue Items

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3304]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

Have the ability to create equipment which isn't based on a catalogue item

## Describe the solution you'd like 🎁
This requires adding back the class, category and type on to the asset. When creating, you can select any category/type which is in the system. 
When creating a non-catalogue item, the asset is marked in some way ( it will have an empty asset_catalogue_item_id, is that enough? ) so that we can filter by catalogue / non-catalogue status.

The queries will need to be updated to fetch the class, category & type from the asset. Question: if the asset is based on a catalogue item, and the item is later changed, do we update the asset? I think we ignore this scenario, and just copy values from the catalogue item at time of asset creation.

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by jmbrunskill** [comment]
>I think we ignore this scenario, and just copy values from the catalogue item at time of asset creation. 

I agree :)
