### ISSUE TITLE
Configurable reasons

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3305]
Part of epic #2896 

## Is your feature request related to a problem? Please describe 👀
[Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

We'd like the ability to be able to configure status reasons. 

## Describe the solution you'd like 🎁
This means moving away from the enum and putting reasons into a table.
We then need to create a UI to add/edit/delete reasons. This will be a soft delete. 

We need to also have a way of assigning functional status values to a reason, so that the list of reasons can be filtered for a specific reason. Currently we have:

```
export const reasonsByStatus = {
  [AssetLogStatusInput.NotInUse]: [
    ReasonType.AwaitingInstallation,
    ReasonType.Stored,
    ReasonType.OffsiteForRepairs,
    ReasonType.AwaitingDecomissioning,
  ],
  [AssetLogStatusInput.Functioning]: [],
  [AssetLogStatusInput.FunctioningButNeedsAttention]: [
    ReasonType.NeedsServicing,
    ReasonType.MultipleTemperatureBreaches,
  ],
  [AssetLogStatusInput.NotFunctioning]: [
    ReasonType.NeedsSpareParts,
    ReasonType.LackOfPower,
    ReasonType.Unknown,
  ],
  [AssetLogStatusInput.Decomissioned]: [],
};
```

The reasons are editable only on the central server (is this correct?)
No language translations for the reasons - each site will be expected to enter reasons in their own language and therefore not require translating.

### Questions

- If reasons are edited, is the change reflected in any status logs which are linked? i.e. do we link by reason id?
- should we implement the mSupply `options` table? Or create a specific `asset_status_reason` table?
- Are reasons only editable on the central server?

### Moneyworks Jobcode 🧰

`OMSCC:AST`

**Comment by jmbrunskill** [comment]
Looks good to me, why not soft delete though? Wouldn't that solve the can I delete something in use? It also avoids issue with sync where you might not be using it now, but a remote site that hasn't synced could be (although that should be a very rare case)

**Comment by mark-prins** [comment]
true - does help with the 'in use' problem. I was thinking that having soft deletes might cause issues if the same reason is recreated.. but it doesn't. updated description 🙏

**Comment by fergie-nz** [comment]
Weird niche case - maybe an issue?

A user creates a reason and assign assets this reason.
The reason is then soft deleted.
A new reason is created with the same name
Other assets are assigned the new reason.
Now multiple assets are assigned the apparent same reason with different ids.

Now the user changes the reason translation / name / description but only some assets are modified.

**Comment by adamdewey** [comment]
> Weird niche case - maybe an issue?

Hmm, perhaps user shouldn't be able to delete a reason that has been used?

Maybe there needs to be an active / inactive flag for those reasons instead?
