### ISSUE TITLE
Flesh out Returns detail view side panels

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3314]
## Is your feature request related to a problem? Please describe 👀

We have a base side panel, but there's not much in it...

![Image](https://github.com/msupply-foundation/open-msupply/assets/55115239/bbceac3f-4176-4255-88ff-d3f02ca975e3)

## Describe the solution you'd like 🎁

Once we have the linked inverse return (like linkedShipment for shipments), we should include that here. 

Once we have the related shipment (if applicable) that should also be displayed here.

Add comment.

Clarify about transport details, invoice details.

**Comment by andreievg** [comment]
Just for reference there is this comment in the spec doc:

```
Once return is finalised: the clickable link to the return appears in the inbound shipment detailed panel section “Related Documents” The clickage link to the inbound shipment appears in the supplier return detailed panel section “Related Documents”
```

**Comment by andreievg** [comment]
In another PR most of this is being done, apart from payments, a separate issue for payments can be created)
