### ISSUE TITLE
Allow changing other party for manual returns

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3315]
## Is your feature request related to a problem? Please describe 👀

Currently, once you set the other party for the return, you can't edit it. However, I should be able to change the other party for manual returns.

## Describe the solution you'd like 🎁

If you generate a return from its related shipment, the current behaviour should remain. 

However, if there is no related shipment (i.e. the return was generated manually) I should be able to change who I am returning to/receiving the return from!

Therefore, this issue should probably be resolved after #3299

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/open-msupply/issues/188, related issue for inbound/outbound shipments

**Comment by roxy-dao** [comment]
Closed in #4528

**Comment by regotaina** [comment]
Testing on RC5
Desktop app

# 🧪 Testing



Outbound Return
- [ ] Create an Outbound Return in Store A to Store B
- [ ] Change status to Picked
- [ ] Go to Store B and confirm that Inbound Return has been created
- [ ] Go back to Store A's Outbound Return
- [ ] Change supplier to Store C
- [ ] Go to Store C and check that Inbound Return has been generated correctly
- [ ] Go to Store B and check that Inbound Return is no longer there

**Comment by regotaina** [comment]
@roxy-dao I cannot follow the step to change supplier, this option is disabled when status = picked:

it's greyed out, like screenshot below:

![Image](https://github.com/user-attachments/assets/1f31ef18-1072-4300-a108-63d5c222357d)

Am I missing something here?

**Comment by lache-melvin** [comment]
Hey @regotaina - this issue is actually for changing the customer/supplier for returns, rather than shipments 😅 However, I think you are getting this greyed out because you created this outbound shipment from a requisition... you should only be able to change the customer for manual shipments 🙏

**Comment by regotaina** [comment]
> Hey @regotaina - this issue is actually for changing the customer/supplier for returns, rather than shipments 😅 However, I think you are getting this greyed out because you created this outbound shipment from a requisition... you should only be able to change the customer for manual shipments 🙏

You are right, I was testing with an OS created from a requisition.
it makes a lot of sense now, thanks for explaining!

will test with a manual return, amend the steps and post the results soon

**Comment by regotaina** [comment]
PASSED the test! 🥇 @lache-melvin good news, moving this one to done
