### ISSUE TITLE
Make colour/onHold/comment editable for Outbound Return

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3316]
## Is your feature request related to a problem? Please describe 👀

Update outbound return functionality is currently very minimal, from the first thin wire implementation. 

I want to be able to update the comment, colour, and onHold status of the Outbound Return.

**Comment by andreievg** [comment]
Skip on hold for now, unless it's quite easy/fast to do

**Comment by lache-melvin** [comment]
Closed by #3369
