### ISSUE TITLE
Re-synced inbound shipment lines have no stock line once delivered

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3320]
## What went wrong? 😲

 

When a re-synced Inbound Shipment is confirmed as Delivered, new stock is introduced. However, the Inbound Shipment InvoiceLine still has `stockLine: NULL`:

![Screenshot 2024-03-18 at 5 17 53 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/0bc147b3-6674-4fb3-b56f-ecece54bb0cb)

Can confirm that the stock line is still created! Just the relationship with the invoice line is no longer being created.

I'm not sure what other issues this causes? It's needed for returns, because we return stock based on that stockLine, but we'd have until 2.0.0 to resolve that one...

## Expected behaviour 🤔

invoice_line gets stock_line_id set when the stock is introduced, so when we query the invoice line, we also get the stock line!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an inbound shipment, with lines, leave New status (or if using a transferred IS, Shipped)
2. Sync to central
3. Blow away omsupply db
4. Re initialise
5. (Can also skip above steps and just use an old IS with status <=Shipped, that you know was initialised from central)
6. Set the status to Delivered
7. Use dev tools to check the stockLine field of the invoiceLines... it's null!
8. Can check `View Stock` - the stock has been created

If you create a new IS, add lines, and set to Delivered, stock line is associated fine. Bug is only when using a re-initialised shipment.

## Your environment 🌱

- Version: 1.8
- mSupply version: 7.11.14

- Platform: Browser (chrome)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Uh oh - okay it's not always... can anyone replicate?

**Comment by roxy-dao** [comment]
Hmm, doesn't seem to be happening for me. Tried both manual inbound shipment and transferred 🤔

**Comment by lache-melvin** [comment]
Now it's the only thing that's happening for me 🥲

**Comment by lache-melvin** [comment]
Have updated the description - have determined this only affects re-initialised Inbound Shipments.

Chatted with Andrei, it's possible that this issue will be solved by #3484, will test once merged back into develop. 

Thinking is that in the syncing with central/re-initialising, the tax/currency state is different, which gets updated when we change statuses. That tax/currency change currently calls `upsert_one` for each line, which overwrites any other changes to the shipment lines - hence the assignment the stock line id gets lost. 

Once only the tax/currency fields get updated (rather than the whole line) this issue should hopefully be resolved!

**Comment by lache-melvin** [comment]
Yep resolved by #3484, closing :)
