### ISSUE TITLE
Add support for multiple output types

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3324]
A report template might be able to be compiled to HTML (including PDF), EXCEL or CSV. For example, to indicate:
- [HTML]: HTML only
- [HTML, EXCEL]: Might produce HTML or EXCEL files but no CSV, e.g. because there are multiple tables in the Excel files that don't translate to CSV
-  [HTML, EXCEL, CSV]: can produce reports in all formats

Currently, the report output type is defined in `service/src/report/definition.rs`:
```Rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct TeraTemplate {
    pub output: ReportOutputType,
    pub template: String,
}
```
Here we have a similar to https://github.com/msupply-foundation/open-msupply/issues/3099, i.e. we need to add support to support multiple output types. This can be done by either:
- change output type to the equivalent of `output: ReportOutputType | ReportOutputType[]`
- add a new outputs  field: `outputs: Vec<ReportOutputType>`

**Comment by andreievg** [comment]
I think we have sufficient excel export functionality for the time being, will re-create issues in the future when further requirements are raised
