### ISSUE TITLE
Store return reason options centrally (6h)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3343]
## Is your feature request related to a problem? Please describe 👀

We store return_reasons in omSupply DB, but not on the central server. These should be options configurable on the central server, like inventory adjustment reasons.

## Describe the solution you'd like 🎁

Add a new option type to mSupply, for return reasons. Sync this to omSupply return reasons table.

**Comment by Chris-Petty** [comment]
Huh didn't realise we were doing different tables for all "options" contexts from OG. Should make the DB schema easier to reason about I think, although each corresponding table will probably only have a few records.

**Comment by lache-melvin** [comment]
@Chris-Petty This is following what we did for inventory adjustment reasons, but I think there was a bit of a question mark about whether or not we'd prefer the broader options table?

It's nice from a filtering perspective (everything in the return reason table is definitely a return reason) but seeing as we have to sync with OG, we have to do that mapping at some point anyway 🤷‍♀

**Comment by roxy-dao** [comment]
Shouldn't this be in OG repo?

**Comment by lache-melvin** [comment]
> Shouldn't this be in OG repo?

Oh lol probably, though I think there would also be code changes in this repo for syncing - in that case do we make an issue in both?

**Comment by roxy-dao** [comment]
> > Shouldn't this be in OG repo?
> 
> Oh lol probably, though I think there would also be code changes in this repo for syncing - in that case do we make an issue in both?

Yes please~ can keep this issue and make another one in mSupply~

**Comment by lache-melvin** [comment]
Closed by #3416
