### ISSUE TITLE
Customers: V1.7.0 Testing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3344]
## Customers
- [x] In this section simply the list of visible customer is given in the omSupply store.
- [x] The list is shown  according to the visibility.
- [x] The sync is working smoothly.

**Comment by regotaina** [comment]
No problems found.

I suggested a search bar as we currently don't have one

<img width="515" alt="Screenshot 2024-03-19 at 5 00 06 PM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/b38959f0-444c-4ddf-9ca2-e7f82bed2c14">

**Comment by roxy-dao** [comment]
> No problems found.
> 
> I suggested a search bar as we currently don't have one

Note: Supplier also doesn't have a search bar (:

**Comment by roxy-dao** [comment]
> No problems found.
> 
> I suggested a search bar as we currently don't have one

#3400

Closing as no issues found
