### ISSUE TITLE
Requisitions V1.7.0

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3345]
## Requisitions
- [x] When customer create internal order in their store requisition will appear in the supplying store
- [x] To check the requisition goto Distribution> Requisition
- [x] You can view and export the requisition list to .csv file
- [x] Clicking the individual item will show you the details of particular item where supplying quantity can be adjusted
- [x] Another way to supply quantity is to click the button `Supply requested`
- [x] To create the outbound shipment, click on the `create shipment` button 
- [x] It will create shipment and all the items which are not supplied and open that shipment in a new tab
- [x] After creating such a shipment, you will see the shipment number, along with a link to view it, in the `Related documents` section of the additional details panel on the right of the screen.

**Comment by regotaina** [comment]
Quantity to be supplied cannot be erased 
[Issue here](https://github.com/msupply-foundation/open-msupply/issues/3356)

**Comment by roxy-dao** [comment]
Issues made for bugs found and testing completed.
