### ISSUE TITLE
Items: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3348]
# Items

### General

A few things to note:

1. Currently, omSupply does not have the functionality to add items, and they have to be added through mSupply and sync over. This is not included in testing. 
2. omSupply docs for Items: [here](https://docs.msupply.foundation/docs/catalogue/items/)

- [x] Choose Catalogue -> Items in the Navigation Panel. 
- [x] You will be presented with a list of Items (if you don't see any, you are probably just starting!).
### Filtering
- [x] Click on the arrow next to Code -> the codes should be sorted from smallest number to largest, and vice versa. If you have any codes starting with letters, they will come after the largest number. 
- [x] Click on arrow next to Name -> the items should be sorted alphabetically. 
- [x] Clicking on ⓘ next to SOH, AMC or MOS should display a little text box, providing explanation what abbreviations stand for. 
- [x] In the top left corner, you will see a search box. Typing in a few letters from a word should bring up results, for example if you type in 'acc', the results will include words such as 'accessory', 'vaccine' and 'accucheck'
- [x] The same concept applies to item codes - if you search by typing in 53, the following code can appear: 03_0553 as well as 53_0876. 
- [x] '_' is a wild card, which gets treated as a random number. if you type in 55_1, it can be treated as 5501, 5511, 5521, 5591 etc. 
### Item Details
- [x] You should be able to click on any item and the new window, showing detailed view, will appear. 
- [x] None of the details should be editable (at this current stage), as the products get synced from mSupply Desktop. 
- [x] When navigating from 'List' view into a specific product view, make sure the numbers shown under SOH/AMC/MOS in 'List' view match the numbers you see in a specific view. For example, if MOS is 0.5 months in List view, it should be the same in detailed view. The formatting/rounding of numbers should be consistent too. 
- [x] Master Lists tab should be clickable -> you should see the master list details. 
### Other
- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well. 

### General

A few things to note:

- [x] Choose Catalogue -> Items in the Navigation Panel. 
- [x] You will be presented with a list of Items (if you don't see any, you are probably just starting!).
### Filtering
- [x] Click on the arrow next to Code -> the codes should be sorted from smallest number to largest, and vice versa. If you have any codes starting with letters, they will come after the largest number. 
- [x] Click on arrow next to Name -> the items should be sorted alphabetically. 
- [x] Clicking and holding ⓘ next to SOH, AMC or MOS should display a little text box, providing explanation what abbreviations stand for. 
- [x] In the top left corner, you will see a search box. Typing in a few letters from a word should bring up results, for example if you type in 'acc', the results will include words such as 'accessory', 'vaccine' and 'accucheck'
- [x] The same concept applies to item codes - if you search by typing in 53, the following code can appear: 03_0553 as well as 53_0876. 
- [x] '_' is a wild card, which gets treated as a random number. if you type in 55_1, it can be treated as 5501, 5511, 5521, 5591 etc. 
### Item Details
- [x] You should be able to click on any item and the new window, showing detailed view, will appear. 
- [x] None of the details should be editable (at this current stage), as the products get synced from mSupply Desktop. 
- [x] When navigating from 'List' view into a specific product view, make sure the numbers shown under SOH/AMC/MOS in 'List' view match the numbers you see in a specific view. For example, if MOS is 0.5 months in List view, it should be the same in detailed view. The formatting/rounding of numbers should be consistent too. 
- [x] Master Lists tab should be clickable -> you should see the master list details. 
### Other
- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well.

**Comment by marthakeezy** [comment]
@roxy-dao I noticed in explanation text boxes, SOH and AMC are capitalised, but months of stock are not ^

<img width="1200" alt="Screenshot 2024-03-20 at 2 52 56 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/2046e2e5-c2fd-41f7-ae47-81acc9025deb">
<img width="1199" alt="Screenshot 2024-03-20 at 2 53 01 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/e3542aab-4a3e-4fb8-be56-8b679b617190">
<img width="1194" alt="Screenshot 2024-03-20 at 2 53 07 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/6dfbef26-6558-4ec2-8dcc-fbb034517463">

**Comment by marthakeezy** [comment]
Issues found: 

#3351 
#3353

**Comment by roxy-dao** [comment]
Issues made for bugs found and testing completed.
