### ISSUE TITLE
Master Lists: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3349]
# Master Lists

### General
- [x] Choose Catalogue -> Master Lists in the Navigation Panel.
- [x] You will be presented with a list of Master Lists (if you don't see any, you are probably just starting!).
### Filtering
- [x] Click on arrow next to Name -> the lists should be sorted alphabetically.
- [x] Click on arrow next to Description -> the lists should be sorted alphabetically. 
- [x] In the top left corner, you will see a search box. Typing in a few letters from a word should bring up results, for example if you type in 'MOS', the results will include words such as 'Moscow', 'Thermos' etc.
- [x] You cannot search by words in Description. 
### Master List Details
- [x] You should be able to click on any Master List and the new window, showing detailed view, will appear.
- [x] At the top of the page, you will see a description, if this Master List has one. You will see the list of items included in that specific Master List. 
- [x] None of the details should be editable (at this current stage), as the Master Lists get synced from mSupply Desktop.
- [x] Click on the arrow next to Code -> the codes should be sorted from smallest number to largest, and vice versa. If you have any codes starting with letters, they will come after the largest number.
- [x] Click on arrow next to Name -> the lists should be sorted alphabetically.
- [x] Click on arrow next to Unit -> the lists should be sorted alphabetically. If the unit is left blank, it will come before the first letter 'A', so all blank units will appear at the top of the page, followed by normal alphabetic order. 
### Other
- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well.
- [x] In the top right corner, you should click the 'Export' button. The expected behaviour is that the exported Excel sheet will show the Master Lists the store has visibility into. E.g. if you are seeing 2 Master Lists in omSupply, the report will also only show 2 Master Lists. Check the report to make sure other Master Lists are not visible. 

### General
- [x] Choose Catalogue -> Master Lists in the Navigation Panel.
- [x] You will be presented with a list of Master Lists (if you don't see any, you are probably just starting!).
### Filtering
- [x] Tap on arrow next to Name -> the lists should be sorted alphabetically.
- [x] Tap on arrow next to Description -> the lists should be sorted alphabetically. 
- [x] In the top left corner, you will see a search box. Typing in a few letters from a word should bring up results, for example if you type in 'MOS', the results will include words such as 'Moscow', 'Thermos' etc.
- [x] You cannot search by words in Description. 
### Master List Details
- [x] You should be able to click on any Master List and the new window, showing detailed view, will appear.
- [x] At the top of the page, you will see a description, if this Master List has one. You will see the list of items included in that specific Master List. 
- [x] None of the details should be editable (at this current stage), as the Master Lists get synced from mSupply Desktop.
- [x] Tap on the arrow next to Code -> the codes should be sorted from smallest number to largest, and vice versa. If you have any codes starting with letters, they will come after the largest number.
- [x] Tap on arrow next to Name -> the lists should be sorted alphabetically.
- [x] Tap on arrow next to Unit -> the lists should be sorted alphabetically. If the unit is left blank, it will come before the first letter 'A', so all blank units will appear at the top of the page, followed by normal alphabetic order. 
### Other
- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well.
- [x] In the top right corner, you should click the 'Export' button. It should be greyed out as Export is not currently supported in omSupply.

**Comment by marthakeezy** [comment]
Issues found: 

#336

**Comment by roxy-dao** [comment]
Issues made for bugs found and testing completed.
