### ISSUE TITLE
Code is not fully visible in omSupply -> Catalogue -> Items

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3353]
## What went wrong? 😲
 

When navigating under omSupply -> Catalogue -> Items and looking at the items' codes, some are not fully visible. There is no functionality to adjust the width of the column either, so you have to click into each individual item to see the code. 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/327e14cf-721c-40c7-af72-1f22c3dfcc35)

## Expected behaviour 🤔

Either the user is able to see the full code straight away, or there is a functionality to adjust the width of the column to minimise/maximise it if necessary. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Items
2. Scroll through the items
3. Note codes on the left-hand side -> see error

## Your environment 🌱

- Version: 1.7.00
- mSupply version: v7-13-00-Beta25

- Platform: Android Galaxy Tablet A8

- Database type: ?

**Comment by roxy-dao** [comment]
Can have tooltip and do the overall mobile fix in #3208

**Comment by marthakeezy** [comment]
Moving this to 'Not ready to test' -> since tooltip does not work on tablet yet, and the fix for desktop hasn't been released. Move back to Needs Build Testing once we have both solutions ~

**Comment by AnushaUp** [comment]
# 🧪 How has/should this change been tested? 
Tested in omSupply `V2.0.00`
- [ ] Have a really long item code
- [ ] Add the item with this really long code to an invoice
- [ ] Hover over code to see tooltip
