### ISSUE TITLE
Cannot delete "quantity to supply" - Requisitions

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3356]
## What went wrong? 😲

If I type a quantity to be supplied and erase the number, it's not deleted - seems like a similar one with Cold Chain.

## Expected behaviour 🤔

Number is deleted if user wants to re-type a new value

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Requisitions'
2. Click on any item line
3. Choose a quantity to be supplied 
4. Try to erase it using backspace or delete
5. See error

## Your environment 🌱

- Version: 1.7RC2
- mSupply version: V7.13
Android - tablet
- Platform:

**Comment by mark-prins** [comment]
Change to nullable input? would be nice to be able to reset / delete

**Comment by clemens-msupply** [comment]
I just tried it and it's working here. I believe it has been fixed in this PR which has been merged only 2 day before this issues has been created:
https://github.com/msupply-foundation/open-msupply/pull/3265
