### ISSUE TITLE
Display Settings: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3366]
# Admin

### Display Settings

- [x] Click on the field dropdown to select a Language -> click between each Language to ensure the translations are displaying properly and the layout of the page stays the same (with the exception of Arabic). 
- [x] Toggle the Custom Theme on -> a text box should appear where you can enter custom code. Save button should be enabled. 
- [x] Toggle the Custom Logo on -> an empty text box should appear where you can enter a link. Save button should be enabled. Hovering over the ⓘ symbol next to 'Custom Logo' will show a text box explaining the necessary format to upload the picture. 

### Display Settings

- [x] Click on the field dropdown to select a Language -> click between each Language to ensure the translations are displaying properly and the layout of the page stays the same (with the exception of Arabic). 
- [x] Toggle the Custom Theme on -> a text box should appear where you can enter custom code. Save button should be enabled. 
- [x] Toggle the Custom Logo on -> an empty text box should appear where you can enter a link. Save button should be enabled. Pressing on the ⓘ symbol next to 'Custom Logo' will show a text box explaining the necessary format to upload the picture.

**Comment by marthakeezy** [comment]
Issues found: 

#3387

**Comment by roxy-dao** [comment]
Issues made. Closing as complete.
