### ISSUE TITLE
Stocktakes V1.7.0 Testing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3367]
# Stocktakes

- [x] Make sure your user account has permission to do Stocktake processes like New, Edit, Delete, etc.
- [x] Open Stocktakes, a list of existing Stocktakes should come up.
- [x] Button ‘New stocktake’ should be enabled
- [x] Click the ‘New stock take’ and create a new stock take. Stock take sheet window will open and the cursor will show:
- [x] option to start from a Masterlist, with a drop down list, according to store visibility
- [x] option to start from a location, with a drop down list.
- [x] option to start from "Items with Stock", with a checkbox.
All options above should take you to the stocktake initial page with appropriate outcome. ex: if selected from Masterlist, all items form that specific Masterlist should appear.
- [x] Click on the top button “Add item" and you can search by item name or code
- [x] Click on Description and type a new description. The information should be saved.
- [x] Click on Comment and type a comment. The information should be saved.
- [x] When you double click on the item, the window for Stocktake line edit will show. All fields must be enterable except for ‘# packs’ 
- [x] 'Add batch' button should be enabled
- [x] When you add a batch, a new item line comes up
- [x] Try changing the ‘Counted packs', the change should reflect on the listbox also.
- [x] If you click on 'Expiry', a calendar window will come up. A month and year should be selected before the window closes
- [x] 'Reason' has a drop down list of reasons configured for the store
- [x] A 'Reason' must be provided before you click on 'Ok', otherwise a warning message comes up
- [x] Check the Log tab, all your changes must show in the Log list.
- [x] Upload a report from the repo. Test the ‘Print’ button. 
  
Deletion of Stocktake Item
- [x] Try to Delete line, there should be a confirmation dialog, click ‘Yes’, the line should be deleted in the list
- [x] Try to Delete line again, click ‘No’, the line should NOT be deleted in the list.
  Adding a Stocktake Item
- [x] Click ‘New line’  to add a new Item,  the Add stocktake lines window will appear. 
- [x] Add a new stock line, fill up all the field
- [x] Click ‘Add new’, the newly added item should be shown on the list.
- [x] Finalised Stocktake
- [x] Once it’s Finalised, you should not be able to edit any details.

**Comment by regotaina** [comment]
There were again no Print out available for any of the stages 

Do I need to upload those? or do we have default ones?

![Screenshot 2024-03-22 at 5 09 31 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/43308e3d-9831-43f8-a139-4b251e7b0ae5)
![Screenshot 2024-03-22 at 5 09 19 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/05d34a12-bfea-4cd0-921f-4214bb86d021)

**Comment by roxy-dao** [comment]
> There were again no Print out available for any of the stages
> 
> Do I need to upload those? or do we have default ones?

For desktop they have to be set up in desktop

**Comment by regotaina** [comment]
Uploaded a report from the repo and it looks good!!

<img width="956" alt="Screenshot 2024-03-25 at 12 35 36 PM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/247902b8-e085-4283-ba94-b8a5278a44aa">

**Comment by roxy-dao** [comment]
No issues found

**Comment by regotaina** [comment]
Print outs work, they look good
