### ISSUE TITLE
Clarifications on Returns modals

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3370]
## Expected behaviour 🤔

- [ ] Modal when creating a return from a shipment

The only editable field of the modal's table should be the quantity to return / returned quantity, all other fields are either calculated (quantity in packs available to return) or recorded in the shipment line (expiry date, batch number, etc...). 

Context: 
https://github.com/msupply-foundation/open-msupply/assets/74992958/9a507307-361b-4cee-8a89-9355f61e081c

- [ ] Modal when creating adding an item to return: 

Should follow the same logic as for other transactions, no need to repeat the item code and name in the table since information is already available at the top in the item DDL (that should save some space horizontally, potentially enough to remove the need for a stepper ? Note that stepper would probably have to be kept for creating a return from a shipment modal). 

Context:
![photo_2024-03-21 16 46 10](https://github.com/msupply-foundation/open-msupply/assets/74992958/f5218b71-27a0-41dc-a49e-7ea72bc905ea)

**Comment by andreievg** [comment]
@richardmoizeau 

> Modal when creating a return from a shipment

Sounds good for outbound return. But for inbound return, do we need to allow for location/price ? (like in inbound shipment) ? Currently we have expiry and batch editable for inbound return in this modal, we can make it non editable if of course, but is it important to make it non editable ?

> Modal when creating adding an item to return:

Sounds good for outbound return. Similar question as above for inbound returns, i think even with code and name removed, what do we do for location/price, etc .. ?

**Comment by richardmoizeau** [comment]
>Modal when creating a return from a shipment
>> Sounds good for outbound return. But for inbound return, do we need to allow for location/price ? (like in inbound shipment) ? Currently we have expiry and batch editable for inbound return in this modal, we can make it non editable if of course, but is it important to make it non editable ?
No, not important to make it non editable. 

>Modal when creating adding an item to return:
>>Sounds good for outbound return. Similar question as above for inbound returns, i think even with code and name removed, what do we do for location/price, etc .. ?
As discussed IRL, we don't handle price/location for now in manual inbound return.

**Comment by andreievg** [comment]
Closing as we out of budget, let's review when UI/UX is reviewed by stakeholders
