### ISSUE TITLE
Report table views for SQL Reports

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3384]
## Is your feature request related to a problem? Please describe 👀

Related to: https://github.com/msupply-foundation/open-msupply/issues/2853

There are a couple of problems when directly accessing the raw DB tables in the report queries:
- Database tables may change their schema over time -> reports may break
- DB tables may contain internal logic, e.g. `name_link_id`

For this reason it would be good to introduce some report database views. These views should be stable, i.e. if the underlying table changes the report view stays compatible to the existing view. Moreover, the views should resolve internal data such as `name_link_id`.

By convention, reports must only use the report DB views.

## Describe the solution you'd like 🎁

Add views for (and define the appropriate columns). These views should only contain column that are important for report. Furthermore, the views could contain joined data if appropriated.

- [x] `report_store` (include store name here?)
- [ ] `report_name` (see above)
- [x] `report_patient` (name that are patients,  include document data column?)
- [x] `report_document` (latest documents)
- [x] `report_encounter` ( include document data column?)
- [x] `report_program_enrolment` ( include document data column?)

Not immediately needed:
- [ ] `report_invoice`
- [ ] `report_item`
- [ ] `report_stock`
- [ ] `report_stocktake`

**Comment by mark-prins** [comment]
Yes, agree - this would be good to have.
