### ISSUE TITLE
`Supplier` modal in `Dashboard` when clicking a new inbound shipment doesn't show external suppliers

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3386]
## What went wrong? 😲
Supplier modal in Dashboard when clicking a new inbound shipment doesn't show external suppliers

## Expected behaviour 🤔
They should show if they are a supplier for the store!

## How to Reproduce 🔨

https://github.com/msupply-foundation/open-msupply/assets/61820074/6a4ad3a3-c04c-4750-8dbe-38f63990f767

Steps to reproduce the behaviour:

1. Add some external suppliers for store
2. Click to `New Inbound Shipment` in `Dashboard`
3. See that the external supplier isn't there but is there if you go to Inbound -> `New Shipment`

## Your environment 🌱

- Version: 
- mSupply version: 

- Platform:

- Database type:

**Comment by regotaina** [comment]
PASSED THE TEST 
# 🧪 How has/should this change been tested? 
- [x] Have external and internal suppliers for a store
- [x] Click `New inbound shipment` button on the dashboard
- [x] Should see all suppliers
