### ISSUE TITLE
Stock V1.7.0 Testing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3391]
- [x] Click on 'View stock' and a list of all stock available should come up.
- [x] Filter by Code or name, Location and expiry date by using the 'Filters' dropdown list on top. All options should work.
- [x] The 'Export' button on the right top corner should also be enabled. 
- [x] After clicking on 'Export' a new window opens up, in which we can choose where the file should be saved.
- [x] By clicking on 'cancel' the window closes and nothing happens
- [x] By clicking on 'Save' a .csv file is downloaded.
- [x] Click on any item line and a new window will prompt with more details like pack Qty, Cost Price, etc 
![Screenshot 2024-03-22 at 5 16 20 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/c3e8f39c-4b28-4b4f-a8a5-7f2712589276)
- [x] You should be able to edit the details if you have the correct permissions
- [x] If you click on 'On hold' no stock can be issued from that specific batch.
- [x] If you change any details, a warning window should come up:
![Screenshot 2024-03-22 at 5 17 50 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/a10f7ff2-7140-459e-bdbf-7ad8f794588e)
- [x] If you click 'cancel' the window should close and nothing changes.
- [x] If you click on 'Ok' the changes are saved.
- [x] The log tab should record all changes on that stock line.
- [x] At the very bottom of the screen you should eb able to change the number of rows per page.

**Comment by roxy-dao** [comment]
No issues found
