### ISSUE TITLE
Internal Order defaults to Number Pad when adding Item

### ISSUE THREAD

**Issue by kahn-msupply** [msupply-foundation/open-msupply#3393]
## What went wrong? 😲

When adding an item to an internal order, the numpad appears instead of the keyboard (maybe by design). This might confuse our clients on Andoird tablets.

Users have been clicking the Item textbox to bring up the keyboard, and adding quantity after selecting the item.

https://github.com/msupply-foundation/open-msupply/assets/132425100/5ce07edb-283b-41bc-bf59-dcfa08138e27

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Use a Samsung tablet (or even an emulator)
2. Create internal order
3. Click Add Item
4. See Numberpad appears

## Your environment 🌱

- Version: v1.7.0.0 RC1
- mSupply version: 

- Platform: Andoid Tablet - Samsung A8 10"

- Database type: SQLite3

**Comment by lache-melvin** [comment]
I cant replicate this, in emulator or on actual tablet? Though now I see the issue was created on 1.7, I'm using 2.0... maybe this has already been fixed??

**Comment by lache-melvin** [comment]
Closed by #3765

**Comment by marthakeezy** [comment]
Just tested in V2.0.0-rc4, and the correct keyboard appears when trying to add an item. Build test passed! :) ✅
