### ISSUE TITLE
Locations V1.7.0 Testing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3394]
- [x] Click on 'Locations' and a list of all locations available should come up.
- [x] Filter by name or 'on hold' by using the 'Filters' dropdown list on top. Both options should work.
- [x] The 'Export' button on the right top corner should also be enabled. 
- [x] After clicking on 'Export' a new window opens up, in which we can choose where the file should be saved.
- [x] By clicking on 'cancel' the window closes and nothing happens
- [x] By clicking on 'Save' a .csv file is downloaded with all locations.
- [x] Click on any location line and a new window will prompt for you to edit name and code
![Screenshot 2024-03-22 at 5 30 11 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/17b77112-8df4-422d-afcb-bcecbed70b11)
- [x] If you change any field and click 'cancel' no changes should be saved.
- [x] If you change any fields and click 'ok' the changes should be saved.
- [x] If you change any fields and click 'ok & next' the changes should be saved and the information from the next row should come up on the screen.
- [x] Try to Delete line, there should be a confirmation dialog, click ‘Yes’, the line should be deleted in the list
- [x] Try to Delete line again, click ‘No’, the line should NOT be deleted in the list.
Adding a location
- [x] Click ‘New location’  to add a new location. A new window will appear. 
- [x] Add a new location, fill up all the fields, click 'save'. The newly added item should be shown on the list.

**Comment by roxy-dao** [comment]
No issues found.
