### ISSUE TITLE
Patients V1.7.0 Testing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3403]
## Patient Registration
- [x] Go to the “Patients” menu and click the “New Patient” button in the right top corner.

### Entering of basic patient information such as name or date of birth
- [x] A patient window open with the following fields
   - [x] Code - 'Generate' button works
   - [x] First Name
   - [x] Last Name
   - [x] DoB
   - [x] Gender
   - [x] Address
   - [x] Phone

### Search for existing similar patients to avoid duplicated patient entries
- [x] The `Ok&Next` button gets enabled only after you enter values in either First or Last name
- [x] If any existing patient matches the info as entered while creating, it should up in the `Search results` 
- [x] For patients found that belong to homestore(logged-in store), see the home icon
- [x] For patients found that belong to other store(other than logged-in store), see the download icon
   - [ ] On downloading the patient, it'll download/fetch patient details from the server

### Entering full patient information and finalising the patient
- [x] In case of no any existing patients found, opt to `Ok&Next` to proceed
- [x] Only after mandatory fields (NID, NUIC, name, DoB) are entered, the `Create` button is enabled which lets us save the patient

## Patient List
- [x] Click on each column header to test the sorting
   - [x] Sorting is ascendent or descendent.
- [x] Test the filter fields
   - [x] Search by First name - Find patients that have the string combination you put in their first name
   - [x] Search by Last name - Find patients that have the string combination you put in their last name
   - [x] Search by id - Find patients that have the string combination you put in the National ID or NUIC 
   - [x] Try multiple fields search, each value you put in a field should combine to reduce your selection     
 - [x] Double click on a patient to see it's information
     - [x] You should see it's information
     - [x] You are able to edit the patient details.
     - [x] When clicking Ok the details are saved.

**Comment by roxy-dao** [comment]
Done~
