### ISSUE TITLE
Repack V1.7.0 Testing 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3405]
## Repack

- [x] Go on 'Inventory' and click on the box icon on the left. Icon should be clickable.
  ![Screenshot 2024-03-25 at 12 50 39 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/51941020-9fc9-4e56-887f-539f1984115b)
  
- [x] A new window should come up with repack details
 ![Screenshot 2024-03-25 at 12 51 27 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/debbe982-e2c6-44e3-afde-a1abaf7c6d59)

- [x] Click on 'New' and more fields should come up on the window:
![Screenshot 2024-03-25 at 12 52 32 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/3b1e55f5-bdb7-4f54-92c1-1c281470056d)

- [x] On the left side, 'Packs available' and 'Pack size' numbers and 'Location' should match your stock levels/details. These fields are not editable. Only 'Number of packs to repack' is editable.
- [x] On the right side, 'New number of packs' is not editable.  'New pack size' and 'New location' are editable fields.
- [x] Choose the number of packs to be repacked, same for new pack size. The field 'New number of packs' should be automatically updated following the calculation: number of packs/pack size = new number of packs
- [x] Press save. the information should be saved.

**Comment by regotaina** [comment]
Noticed that 'Number of packs to be repacked' is not a required field. I was able to save without inputting any number there.

It doesn't change the stock levels, however stays on the item history log:


https://github.com/msupply-foundation/open-msupply/assets/132425096/f05fbf21-4d52-4940-85de-e652cdb2211b

[Issue for bug created here](https://github.com/msupply-foundation/open-msupply/issues/3408)

**Comment by roxy-dao** [comment]
Issue created. Closing as done
