### ISSUE TITLE
Add 'OK', 'Back' or 'Exit' button to the Server Log window

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3417]
## Is your feature request related to a problem? Please describe 👀

When using a tablet and navigating under Admin -> Android Settings -> Server Log, a window showing the latest server log pops up. However, on a tablet there is no way to navigate out of this window. Clicking outside of the window does not close it, and the only way to get out of it is by using the tablet's back button which takes you to another part of omSupply, not the Admin page. 

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/b8eaf1b1-6c11-4723-9314-961c44dc7fb8)

For reference, this is what the Server log window looks like on Desktop -> there are a few options, including 'OK' which closes the window and allows you to browse further. 

<img width="858" alt="Screenshot 2024-03-25 at 6 05 37 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/534dfd33-4ed5-46e7-956c-0254ade15ddc">

## Describe the solution you'd like 🎁

For the tablet, there should either be the same 'OK' button, allowing to browse the Admin area further, or a little 'x' in the top right corner which allows you to close the window. 'OK' button will probably be better for continuity and to match the design of the Desktop. 

## Agreed Solution

Make sure the same buttons in desktop are displayed/available for android.

### Additional context 💌

The back button going back to dashboard is a separate issue with android https://github.com/msupply-foundation/open-msupply/issues/3209

### Moneyworks Jobcode 🧰

N/A

**Comment by marthakeezy** [comment]
This is what happens when you use the tablet's back button:

https://github.com/msupply-foundation/open-msupply/assets/153777484/30b195da-eb2f-4d53-9c60-571947dcb9bc

**Comment by mark-prins** [comment]
See also #3209 - same issue with dashboard being in the navigation stack

**Comment by roxy-dao** [comment]
Are the buttons hidden? Screenshot looks like you can scroll down on the modal

**Comment by roxy-dao** [comment]
Tested in 2.4.0-RC2 on tablet and seems fine
