### ISSUE TITLE
Synchronisation: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3421]
# Admin

### Synchronisation

- [x] Central Server URL text field should be editable.
- [x] Site name text field should be editable.
- [x] Site password text field should be editable. Clicking the eye icon will either hide or show your password. 
- [x] Interval seconds text field should be editable. 
- [x] For the time being, none of the changes can be saved unless the password is entered. If the password is not entered, the Save button is greyed out and not clickable. 

### Synchronisation

- [x] Central Server URL text field should be editable.
- [x] Site name text field should be editable.
- [x] Site password text field should be editable. Clicking the eye icon will either hide or show your password. 
- [x] Interval seconds text field should be editable. 
- [x] For the time being, none of the changes can be saved unless the password is entered. If the password is not entered, the Save button is greyed out and not clickable.

**Comment by marthakeezy** [comment]
Issues found: 

#3390 (Desktop/Tablet)

**Comment by roxy-dao** [comment]
Issues created.
