### ISSUE TITLE
Support/Android Settings: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3422]
# Admin

### Support

- [x] You can click the 'View' button next to Server Log -> a window will appear, where you can choose a log file. Depending on how big the log file is, it can be split into multiple ones -> omsupply.log will always have the most up-to-date information. You should be able to click on the dropdown field to choose a log file. 
- [x] Clicking 'Save' will download the file. 
- [x] Clicking 'Copy to Clipboard' will copy the file's contents to clipboard
- [x] Clicking 'OK' will close the window. 
- [x] Download button next to 'Download Database' should be enabled -> clicking the button will download the Database file. 
- [x] In the bottom right corner, omSupply version number should be displayed. 

### Android Settings

- [x] You can toggle the Mode between Client and Server. If you are on a Server setting, switching to Client will log you out and present you with the initial setup screen. There, you can select Available Servers -> select your home one. After that, you will need to log into omSupply. When using Client mode, you are unable to download the Database. The rest of the settings should look the same. 
- [x] If you are on a Client setting, switching to Server will not log you out, and you can continue testing as per normal. 
- [x] You can click the 'View' button next to Server Log -> a window will appear, where you can choose a log file. At the moment, there is no functionality to close the window, so you will have to use Android's back button to navigate out of this area. 
- [x] Download button next to 'Download Database' should be enabled -> clicking the button will download the Database file. 
- [x] In the bottom right corner, omSupply version number should be displayed, alongside the Site's name and the server being used. Clicking on a pen icon next to the server will allow you to switch servers.

**Comment by marthakeezy** [comment]
Issues found: 

#3414 (Desktop/Tablet)

**Comment by roxy-dao** [comment]
Issues created.
