### ISSUE TITLE
Suppliers: V1.7.0 Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3424]
# Suppliers

### General

- [x] Choose Replenishment -> Suppliers in the Navigation Panel.
- [x] You will be presented with a list of Suppliers (if you don't see any, you are probably just starting!).

### Filtering

- [x] Click on the arrow next to Code -> the codes should be sorted alphabetically, either from A-Z or from Z-A. 
- [x] Click on the arrow next to Name -> the names should be sorted alphabetically, either from A-Z or from Z-A. 

### Supplier Details

- [x] You should be able to click on any supplier and the new window, showing detailed view, will appear.
- [x] None of the details should be editable (at this current stage), as the suppliers get synced from mSupply Desktop.
- [x] The 'OK' button should be clickable.

### Other

- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well.

### General

- [x] Choose Replenishment -> Suppliers in the Navigation Panel.
- [x] You will be presented with a list of Suppliers (if you don't see any, you are probably just starting!).

### Filtering

- [x] Click on the arrow next to Code -> the codes should be sorted alphabetically, either from A-Z or from Z-A. 
- [x] Click on the arrow next to Name -> the names should be sorted alphabetically, either from A-Z or from Z-A. 

### Supplier Details

- [x] You should be able to click on any supplier and the new window, showing detailed view, will appear.
- [x] None of the details should be editable (at this current stage), as the suppliers get synced from mSupply Desktop.
- [x] The 'OK' button should be clickable.

### Other

- [x] Rows per page in the bottom right corner should be clickable - e.g. click between different options of how to display records per page. You should be able to change between pages as well.

**Comment by marthakeezy** [comment]
Issues found: 

#3425 (Desktop)

**Comment by roxy-dao** [comment]
Done~
