### ISSUE TITLE
'Website' category does not have a text box allocated under Replenishment -> Suppliers

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3426]
## What went wrong? 😲
 

When clicking on a specific supplier, a window with details appears. One of the categories you can see is 'Website' - it is the only category missing a grey-ish text box next to it, so in case there is information to display, it would be within that box

![photo_2024-03-26 10 36 31](https://github.com/msupply-foundation/open-msupply/assets/153777484/c25c036a-71f6-4c15-b8a2-f6475f1cf534)

## Expected behaviour 🤔

For consistency, I think 'Website' should have a box allocated to it too, even if the field is left empty like in other cases on the same screen. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Suppliers
2. Click on a specific Supplier to bring up a detailed view
3. Note the 'Website' category at the bottom of the screen does not have a grey text box allocated to it

## Agreed Solution 
Either: 
1. Don't show the website label and data if there is none. 
2. Indicate that no website link has been provided with `None provided`

## Your environment 🌱

- Version: 1.7.0-RC3
- mSupply version: v7-13-00-Beta25

- Platform: Windows Server 2022 Desktop

- Database type: SQLite3

**Comment by Chris-Petty** [comment]
Tangentially, I wonder if I'm the only one that's struggling with the low contrast of "greyed out grey boxes" on the white background? Maybe a different issue to raise with @anisha-msupply at some point.

**Comment by marthakeezy** [comment]
I am also wondering if the tick boxes next to Manufacturer, Donor and On Hold can be greyed out if they are not editable? As I tried clicking on them, my first instinct was they were editable

**Comment by roxy-dao** [comment]
Okay, so it was done this way because the user can click the link if the website is provided 👀 ...

**Comment by Chris-Petty** [comment]
> It was done this way because the user can click the link if the website is provided 👀 ...

Aaaaaaaaaah! Context! Thanks. Hmmm. Shoot...

**Comment by mark-prins** [comment]
could we put in some text such as 'none provided' if there is no website link?
alternatively don't show the website label and data if there is none.

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-RC4, and the issues is fixed. Build test passed! :) ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/ebe8bb09-3523-4db5-bf13-cde22511aba9)
