### ISSUE TITLE
When clicking on a specific Supplier, the module name changes to the specific supplier's name under Replenishment -> Suppliers

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3428]
## What went wrong? 😲
 

When clicking on a specific Supplier to see details, the module name changes to whatever supplier you click on. 

Screen recording of the issue is [uploaded here](https://drive.google.com/file/d/1Qbb_Ma_923yU39NkQRsJkN7kCrSuQzHm/view?usp=drive_link) :)

## Expected behaviour 🤔

It should stay as 'Suppliers' regardless of which supplier you click on. However, if it's supposed to display the supplier's name, it should change back to 'Suppliers' once you close the detailed view window. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Suppliers
2. Note the top left corner says 'Suppliers'
3. Click on a specific supplier -> note the top left corner changes to display whatever you click on. 
4. Once you close the window, it still displays the specific name

## Your environment 🌱

- Version: 1.7.0-RC3
- mSupply version: v7-13-00-Beta25

- Platform: Windows Server 2022 Desktop

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Same thing happening to customers

**Comment by mark-prins** [comment]
Funky - should be easy to fix, so I would put in the todo

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc4 (tablet) and V2.0.0-rc2 (desktop), and the issue is fixed. Build test passed! :) ✅
