### ISSUE TITLE
Repack button too small - hard to hit.

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3439]
## What went wrong? 😲

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/e27e1f26-f990-4c55-b55e-b30de9d3a271)

The button box has shrunk to the smallest size by the tiny icon. This hard to click quickly, and missing will open the line edit. I imagine this very unpleasant for android.

## Expected behaviour 🤔

Easy that can be done without discussion: the button should be nearly as tall as the row containing it, and preferably equally wide

OR 

Needs design: Perhaps it should be a button from within the regular edit modal. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Inventory
2. View stock
3. Witness the button for ants

## Your environment 🌱

- Version: 1.7.rc3 (dev env)
- firefox developer edition 125

**Comment by roxy-dao** [comment]
Can we add the info icon to this issue as well 👀 . It's so small D:

**Comment by Chris-Petty** [comment]
I agree that's a problem but I think this issue is nice and targeted! The info icon is like all over the place and making big is potentially clutters busy table header rows and what not.

Do you want to open a separate issue for it (and check it isn't already raised)?

**Comment by roxy-dao** [comment]
> I agree that's a problem but I think this issue is nice and targeted! The info icon is like all over the place and making big is potentially clutters busy table header rows and what not.
> 
> Do you want to open a separate issue for it (and check it isn't already raised)?

Don't think there's an issue for it... been spoken about a few times but that's all XD

**Comment by roxy-dao** [comment]
I found it 👀 #3208

**Comment by andreievg** [comment]
Closing as it will be resolved by: https://github.com/msupply-foundation/open-msupply/issues/3656

**Comment by mark-prins** [comment]
`Move stock line to its own page`? are you sure that's the correct issue which would close this one?
