### ISSUE TITLE
Correctly insert MERGE records into the sync_buffer

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3441]
Each sync record received from mSupply contains a record_id which is the id of the entity, e.g. invoice.id.
This record_id is used as a primary key in the sync_buffer table.
This means the sync_buffer only contains the latest update for an entity.

However, this can fail when an entity is created and then merged in the same integration step:
- the UPSERT event for the new entity is overwritten by the MERGE event (deleting the old entity and keeping the new entity)
- the entity is never created and thus can't be merged
- thus the entity is missing

Note, in the future this could also cause problems for link tables or the context table which also share entity ids across tables.

## Example to reproduce the problem
- Choose item A
- Create a new item B that is a duplicate of item A
- I merged item A into item B (keep the new item B) 

Afterwards I got, these new entries in the sync_buffer:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/29e1e8dd-91ef-4584-8270-a054e22ac2b5)

The new item  "7A51FD..." is not there and thus the merge fails! mSupply bug?

_Originally posted by @clemens-msupply in https://github.com/msupply-foundation/open-msupply/issues/3306#issuecomment-2005586684_

## Proposed Solution

Instead of upserting records in the sync_buffer, append them, i.e. keep the full list of sync records.
This requires to change the sync_buffer so that the record_id is not the primary/unique key anymore.

Furthermore, we need to make sure that received_datetime strictly increases following the order as received by mSupply. For example, an early sync record should have a smaller received_datetime.
This is needed to integrate records in the correct order.

# Future work
Clean up redundant records from the sync buffer.
For example:

|record_id|action||
|---|----|-|
|1| UPSERT|redundant|
|1|UPSERT| latest|
|2|UPSERT|redundant|
|2|UPSERT|needed by merge|
|2|MERGE|latest|
|3|UPSERT|redundant|
|3|MERGE|redundant|
|3|UPSERT|latest|

Also see https://github.com/msupply-foundation/msupply/issues/14513

**Comment by andreievg** [comment]
@Chris-Petty @clemens-msupply 

Sorry just realised that primary key constraint by record_id would need to be remove, which would require mass migration. I think I am leaning back to either option 3 (conditional add _merge at the end of record_id when upserting to sync buffer and the record type is merge), I think option 3 is the simplest ? or option 4 (record_id in sync_buffer to be {record_id}{table_name}{operation type}), what do you think ?

**Comment by clemens-msupply** [comment]
> Sorry just realised that primary key constraint by record_id would need to be remove, which would require mass migration. I think I am leaning back to either option 3 (conditional add _merge at the end of record_id when upserting to sync buffer and the record type is merge), I think option 3 is the simplest ? or option 4 (record_id in sync_buffer to be {record_id}{table_name}{operation type}), what do you think ?

Regarding "mass migration" are you concerned about migration time? i.e. copying the whole table?

3 doesn't seem possible to me because of the UNIQUE constraint. However, think option 4. is better anyway. We have to add a new record_id column though (or parse it from the primary key)

**Comment by clemens-msupply** [comment]
Here is also query I came up with to clean up redundant records:

https://www.db-fiddle.com/f/2RkfdtSf4gEkM442oCWFNr/2

This requires a new primary id though (i.e. full table rewrite) but maybe still useful. This query is probably expensive when running on the whole table so it should be called incrementally after finishing the integration querying only the latest entries.

**Comment by andreievg** [comment]
> 3 doesn't seem possible to me because of the UNIQUE constraint

I think 3 would work by appending _merge at the end of record_id ? https://github.com/msupply-foundation/open-msupply/compare/develop...develop(Append-merge-to-sync-buffer-record-id)

But yeah that would only be a hot fix if we want to get it in quick. (to be remove later)

> are you concerned about migration time? i.e. copying the whole table?

Just the amount of effort really, lots of sql (sqlite) code + tests. I think option 4 would be the more permanent fix for sure.

**Comment by andreievg** [comment]
> What if we just generate a new UUID altogether? 

Sounds good

**Comment by Chris-Petty** [comment]
1.7.00-RC4
