### ISSUE TITLE
Make the side left tray a bit more responsive?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3442]
## What went wrong? 😲
 
On Android, the menus in the left side expand on selection, but if you click it again, it doesn't shrink back, which I think would be expected behavior here and make it look more responsive

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. OPen oms
2. Navigate to left side, open let's say `Replenishment`
3. Other options under replenishment expands: Inbound Shipment, Internal Orders, Suppliers
4. Now click on same `Replenishment` again
6. See error: as a user, I'd expect it to shrink back now, but it doesn't. Here's a recording:

https://github.com/msupply-foundation/open-msupply/assets/59193490/eedcb662-c27d-4bcb-8289-1a9c72eff687

## Your environment 🌱

- Version: v1.7-rc3
- mSupply version: 

- Platform: Android, browser

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.1.0-IA-test-2`


- [ ] Open the app drawer
- [ ] Click on a section that you are not currently active on (e.g. if on Distribution > Outbound Shipment, click on Inventory)
- [ ] Inventory nav opens
- [ ] Click on Inventory again
- [ ] Inventory Nav closes
