### ISSUE TITLE
Move create_missing_master_list_and_program into a migration

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3444]
## The suggestion

On server startup we run this code everytime
```
    // CREATE MISSING MASTER LIST AND PROGRAM
    service_provider
        .general_service
        .create_missing_master_list_and_program(&service_provider)
        .unwrap();
```
This upserts 3 rows with `MISSING_PROGRAM` for `master_list`, `context` and `program`

### Why should we invest time in this?

If we move this to a migration you'll save 3 sql queries every startup, and reduce the logic in the server crate, which makes the server code easier to follow.

### Are there any risks associated with this change?

Seems like a low risk change, but we need to check if this approach was taken for a particular reason?

### How much effort is required?

Maybe 1 hour?

**Comment by jmbrunskill** [comment]
A similar approach could be taken for inserting the `system_user`

**Comment by mark-prins** [comment]
Sounds sensible to me! I'd bump up the priority list - low effort, low risk
