### ISSUE TITLE
Add stable report view tables for SQL reports

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3452]
## Is your feature request related to a problem? Please describe 👀

There are two main reasons to have special report views:
- Stable view prevents schema changes to break reports
- Removes/resolves internal columns such as `name_link_id` and `item_link_id`

These views should only contain column that are important for report. Furthermore, the views could contain joined data if appropriated.

## Describe the solution you'd like 🎁

Add views for (and define the appropriate columns):

- [ ] `report_store` (include store name here?)
- [ ] `report_name` (see above)
- [ ] `report_patient` (name that are patients,  include document data column?)
- [ ] `report_document` (latest documents)
- [ ] `report_encounter` ( include document data column?)
- [ ] `report_program_enrolment` ( include document data column?)

Not immediately needed:
- [ ] `report_invoice`
- [ ] `report_item`
- [ ] `report_stock`
- [ ] `report_stocktake`

**Comment by mark-prins** [comment]
Sounds sensible - and good to have before we go to far with the report work

**Comment by clemens-msupply** [comment]
Duplicate of https://github.com/msupply-foundation/open-msupply/issues/3384
