### ISSUE TITLE
Returns: Ok & Next doesn't follow table sorting order

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#3457]
After sorting the Detail view table for a return, when clicking on a line, the "Ok & Next" button in the modal doesn't follow the sorted order of the lines.

**Comment by mark-prins** [comment]
we've had this one before, in requisitions and shipments.. some time ago though.
it was due to there being two instances of sorted lines; the column sort acted on one, and the other was used for Ok & Next..
