### ISSUE TITLE
Every status-update in Inbound is increasing stocklines of the same item again

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3458]
## What went wrong? 😲
For stock transfer ONLY; in the received Inbound, first update status to Delivered, the items' stock gets in, now update the status to Verified, another set of same items stocklines is created.
Not replicable when creating a manual Inbound (with external supplier); only in case of stock transfer!
  
## Expected behaviour 🤔
Item line should be stocked only once on `Delivered` status,. not again in `Verified`?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure to create a CI (from mSupply desktop) or Outbound from another oms-site with item (let's say Quan 1) to your oms-site so that there is a new inbound in your oms-store
2. OPen it and change the status to `Delivered` and check stock
3. There is 1 item in the stock
4. Now go back to that INbound and this time update status to `Verified` and check stock
5. See error: there is another stock line of same value; thus same line got stocked-in twice!

## Screenshot/Recording
https://recordit.co/twyIP06Cj3

## Your environment 🌱

- Version: v1.7.0-rc3 
- mSupply version: v7-13-00

- Platform: Android, browser

- Database type: sqlite

**Comment by roxy-dao** [comment]
Closed in #3484

**Comment by nisha-dangol** [comment]
Tested in v1.7.0-rc4 exe

# Tests
- [x] Setup multiple oms sites along with msupply desktop sites and the central sync server.
- [x] Make visible of those sites' active stores among each other from the central sync server.
- [x] Create an outbound shipment against one of those remote site from an another remote site and sync.
- [x] Sync from another site and in the inbound shipment list you'll see a new inbound shipment from your supplying store.
- [x] Now process that shipment and confirm it.
- [x] Check item's stock, note it down.
- [x] Again to goto the same inbound shipment and click confirm verified and again check the stock of that item.

Can't break it more - **PASS!**
