### ISSUE TITLE
Store should be top of list of create asset module / asset detail view

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#3461]
## What went wrong? 😲
UI preference: Store selection should be first when creating new asset (On central server create asset)

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/0a0f54b3-eb39-4d70-8b4c-8dec5db0cebb)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to cold chain
2. Open create asset modal

**Comment by adamdewey** [comment]
@fergie-nz Could we also move it to the top of the Asset Detail view while we're looking at this?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/85824a81-ae5f-4aba-beee-b6e1d8d3dbfa)
