### ISSUE TITLE
Create new asset catalogue items via import spreadsheet

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3465]
## Is your feature request related to a problem? Please describe 👀

Asset managers want to be able to create new catalogue items in a `sub catalogue`.

## Describe the solution you'd like 🎁

The assets view should have an import button and a `Sub Catalogue` field added to the view.
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/7af040eb-db70-4bf2-9a1d-827e93489441)

### Acceptance Criteria

- [x] Adding catalogue items should only be possible from the central server
- [x] Able to filter/sort by `sub catalogue` name
- [x] Able to select which fields are shown in the asset list
- [x] Import should require the following fields
     - sub catalogue, code, manufacturer, model, class, category, and type
- [x] The import should validate that there are no duplicate codes
- [x] The import should validate that the same manufacturer and model doesn't already exist in the system

### Describe alternatives you've considered 💭
UI for editing asset items, which will take more time.

### Additional context 💌

To make the code simple for now if we just add a string field for `catalogue name`, and we'll only support creating new catalogue items via an import modal.

> This means that in future if we want to create asset catalogues as their own separate entities we'll need to migrate existing catalogue names into the new structure.

### Moneyworks Jobcode 🧰

OMSCC:AST

**Comment by adamdewey** [comment]
Also for this do we need to state the subcatalogue that you're importing into too?

> - [ ] Import should require the following fields
     - code, manufacturer, model, class, category, and type

**Comment by jmbrunskill** [comment]
> Also for this do we need to state the subcatalogue that you're importing into too?
> 
> > * [ ]  Import should require the following fields
> >   - code, manufacturer, model, class, category, and type

Yes good point!

**Comment by adamdewey** [comment]
I guess a danger here is that they won't be able to edit or delete any they upload incorrectly?

**Comment by adamdewey** [comment]
Also for CCE in the category `Refrigerators and freezers` we need to be able to import the volume and energy source fields added in #3474

**Comment by jmbrunskill** [comment]
> Also for CCE in the category `Refrigerators and freezers` we need to be able to import the volume and energy source fields added in #3474
I'll do this as part of #3474 as we need the properties to be added to Assets tables first.

**Comment by jmbrunskill** [comment]
> I guess a danger here is that they won't be able to edit or delete any they upload incorrectly?

I'm going to add a delete so there's an option to fix it up if you do import something incorrectly.
