### ISSUE TITLE
Code is not fully visible in omSupply -> Catalogue -> Items

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3468]
## What went wrong? 😲
 

When navigating under omSupply -> Catalogue -> Items and looking at the items' codes, some are not fully visible. There is no functionality to adjust the width of the column either, so you have to click into each individual item to see the code. 

Screenshot: https://drive.google.com/file/d/10PEJZNnBtfErMqJeHTldN5XWzVEZ1DIj/view?usp=drive_link

## Expected behaviour 🤔

Either the user is able to see the full code straight away, or there is a functionality to adjust the width of the column to minimise/maximise it if necessary. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Items
2. Scroll through the items
3. Note codes on the left-hand side -> see error

## Your environment 🌱

- Version: 1.7.00
- mSupply version: v7-13-00-Beta25

- Platform: Android Galaxy Tablet A8

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Done~

**Comment by nisha-dangol** [comment]
Looks good in v2.1: there's proper hover showing full code in Catalogue>items as well; Moving to Done
