### ISSUE TITLE
Open mSupply using 100% CPU (running multiple processes)

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3471]
## What went wrong? 😲
 

Wanted to change datafiles to keep testing and needed to clear the data in order to do that.
@npendergrast and I deleted the app data and after doing that the Desktop app crashes all the time.

It maxs out the CPU usage and open a large number of processes

![Screenshot 2024-03-28 at 10 22 20 AM](https://github.com/msupply-foundation/open-msupply/assets/132425096/3948e4c8-9f73-40d1-80bf-3d896dc2e9f9)
![Screenshot 2024-03-28 at 10 18 12 AM](https://github.com/msupply-foundation/open-msupply/assets/132425096/a1620dd7-09ab-429b-be50-76eec4b505a0)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'C:\Users\Administrator\AppData\Roaming'
2. Delete the Open mSupply folder
3. Open Desktop app
4. Try to connect to the server
5. See error

## Your environment 🌱

- Version: 1.7 RC3
- mSupply version: v7.13

- Platform: Desktop App

**Comment by regotaina** [comment]
Tried to reproduce the error by erasing the app data and simply couldn't.
Re-installed Desktop app and now I can connect to the server.

it seems normal, only 4 processes now.
![Screenshot 2024-03-28 at 2 57 03 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/8986aaba-33cb-4487-8d7d-b2f14aac152b)

**Comment by Chris-Petty** [comment]
@regotaina I'm going to close this for now if can't be reproduced
