### ISSUE TITLE
Information ⓘ symbols appear underneath the text in omSupply

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3472]
## What went wrong? 😲
 

Tainá and me spotted a few occurrences where the information symbols appear underneath the text, not next to it -> see this Google Drive: https://drive.google.com/drive/folders/1f90cVH9aqQ_dCfnWDPk0v3TpnJydb7Nu?usp=drive_link

## Expected behaviour 🤔

Information symbols should be displayed next to the text, not under it for a more consistent and sleek look

## How to Reproduce 🔨

Steps to reproduce the behaviour:

N/A

## Your environment 🌱

- Version: 1.7.00-RC3
- mSupply version: v7-13-00-Beta25

- Platform: Windows Server 2022 Desktop

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Duplicate of #3434
