### ISSUE TITLE
CCEI: Capture additional core data for subcatalogue asset templates of CCE in the category `Refrigerators and freezers`

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3474]
## Is your feature request related to a problem? Please describe 👀

We're missing some core data for the subcatalogue asset templates in the category `Refrigerators and freezers`, namely: 

- `Energy source`
- `Storage volume (+5 °C)` 
- `Storage volume (-20 °C)` 
- `Storage volume (-70 °C)` 

| Field | Format |
| ------------- | ------------- |
| `Energy source`  | enum (`Electricity`, `Solar`, `Passive`, `Kerosene`, `Gas`)  |
| `Storage volume (+5 °C)`  | number (Litres)  |
| `Storage volume (-20 °C)`  | number (Litres)  |
| `Storage volume (-70 °C)`  | number (Litres)  |

## Describe the solution you'd like 🎁

- Add them to the Asset Catalogue items / templates

**Comment by adamdewey** [comment]
Note that these fields are only applicable to assets in the category `Refrigerators and freezers` 

They wouldn't make sense for other categories (but are very important for the `Refrigerators and freezers` category!)

**Comment by mark-prins** [comment]
The plan:

* Create `asset_property` table
  * id (text)
  * link to `asset_category_id` (`asset_category.id`)
  * property name (text)
  * property type (text) relates to an enum of options
  * value_string (text)
  * value_int (int4)
  * value_float (float8)
  * value_bool (boolean)
  * text column (nullable) which has a comma separated list of allowable values
* Add migration code to insert the four properties
* Create `asset_item_property` table
  * id (text)
  * `asset_id` (text) links to `asset.id`
  * `asset_property_id` (text) links to `asset_property.id`
  * value (text)
* migration code to import energy source and volume for `refrigerators and freezers` : will need to lookup IDs and insert?
* sync the data to omcentral
