### ISSUE TITLE
Restarting server and refreshing causes User Login Error and potentially blocks user...

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3475]
## What went wrong? 😲

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/5afe6467-47eb-4582-ab64-050ab0ebdf1e)

## Expected behaviour 🤔

If we need to relogin then the system should tell us, or maybe it should just skip refreshing the User if the credentials are not available after a restart

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login to mSupply and go to the sync page
2. Restart your server
3. Refresh the page
4. Click Sync

## Your environment 🌱

- Version: 1.7.00

## Notes
> This might only affect development versions? as production server require a reloading after restart. I'd like to fix that at some point though!

**Comment by clemens-msupply** [comment]
Think we need to fix the underlying problem, i.e. to be able to fetch user permissions with the site credentials rather than with the user credentials...

However, we should make the error a warning/info saying that to update user info the user has to re-login, e.g.:

"Unable to fetch user details. Please re-login to update user details"

Also from the code comment:
```Rust
struct TokenInfo {
    token_hash: String,
    expiry_date: usize,
    // Temporarily store password in token info.
    // Will need to delete once server has implemented its own central server.
    password: String,
}
```

**Comment by andreievg** [comment]
Also me endpoint

**Comment by roxy-dao** [comment]
Agreed solution pick either one of these:
1. Log the user out and make them sign in again
2. Change the error message to a warning and make it clearer that the user that they have failed to login and should log out and sign in again

**Comment by jmbrunskill** [comment]
I vote for #2 :)

**Comment by andreievg** [comment]
I am happy with both 1 and 2, whatever is easier to implement

**Comment by regotaina** [comment]
Tested on RC3 > Desktop app. Followed the steps to reproduce:

Steps to reproduce the behaviour:

-Login to mSupply and go to the sync page
-Restart your server

after the restart I got an error message, locking me out:
![Screenshot 2024-05-08 at 3 51 03 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/8c82481c-a6c4-4c4c-950a-312667c4dc29)

I could not even sync.
Then I logged in and it was all fine.

Sounds like Solution 1. IS this what we expected @roxy-dao ? If yes, passed the test :)

**Comment by roxy-dao** [comment]
> Tested on RC3 > Desktop app. Followed the steps to reproduce:
> 
> Steps to reproduce the behaviour:
> 
> -Login to mSupply and go to the sync page -Restart your server
> 
> after the restart I got an error message, locking me out: 
> I could not even sync. Then I logged in and it was all fine.
> 
> Sounds like Solution 1. IS this what we expected @roxy-dao ? If yes, passed the test :)

Oh, maybe it acts differently in production. It's supposed to be step 2 fix as stated in PR (: 

This change is mostly for devs XD
