### ISSUE TITLE
Mismatch between reasons and functional status for assets

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3476]
## What went wrong? 😲
 

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/dd6471c6-e496-442e-96cf-e6eb4c339d98)

## Expected behaviour 🤔

Should save, or option shouldn't be available

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open an asset
2. Click Update status
3. Select `Not In Use` and `Awaiting Installation`

## Your environment 🌱

- Version:  develop

## Note:

Might be superseeded by https://github.com/msupply-foundation/open-msupply/issues/3305

**Comment by fergie-nz** [comment]
Closing as will be fixed by #3305
