### ISSUE TITLE
CCEI: Display `Cold storage volume` (per temperature range) for CCE in the category `Refrigerators and freezers`

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3480]
## Is your feature request related to a problem? Please describe 👀

#3474 captures cold storage volume per temperature range `+5 °C`,`-20 °C`,`-70 °C`

We need to display the details in the Asset Registry view for CCE in the category `Refrigerators and freezers`

Note there may be data for more than one temperature range per CCE

## Describe the solution you'd like 🎁

Something like this: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/29d8e0bd-99f2-4e49-b9f8-0077335d5f3a)

### Additional context 💌

Note, these fields are only relevant for CCE in the category `Refrigerators and freezers` and shouldn't be displayed for other categories

**Comment by mark-prins** [comment]
after discussion, this feature is not planned at this stage

**Comment by adamdewey** [comment]
@mark-prins - oh, I thought we would show the manufacturer's volume still? Or is that only shown at the Catalogue level?

**Comment by mark-prins** [comment]
yep, good catch. was about to make a new issue to display exactly this. 🙏

**Comment by mark-prins** [comment]
Implemented with #3626
