### ISSUE TITLE
OMS desktop app crashes when you enter decimal values in cost field

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3482]
## What went wrong? 😲
 

See the app got crashed after entering the decimal in cost field:

https://github.com/msupply-foundation/open-msupply/assets/117138852/c014699f-d277-437f-b20b-3a20d3f435e8

## Expected behaviour 🤔

No crashing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create Inbound shipments
2. Select the items
3. Enter Batch, quantity , packsize and other details
4. On second tab try to enter prices, cost all in decimal
5. After pressing tab press `tab`
6. See app Crash (BUG)

![Screenshot 2024-03-28 at 13 24 38](https://github.com/msupply-foundation/open-msupply/assets/117138852/b5be61f2-f1d1-4ca1-aa21-c5266b17254d)

## Your environment 🌱

- Version: 1.7.00
- mSupply version: v7.14-00-Dev3

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Fixed with #1355

**Comment by marthakeezy** [comment]
Just tested in V1.7.00 and it works :) Build test PASSED ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/6672287f-372b-4d70-bc7c-00134b661448)
