### ISSUE TITLE
The `show/hide columns` keeps on swinging on check/uncheck of the checkbox and unusual behaviour on check/uncheck of `Total` 

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3483]
## What went wrong? 😲
 
See the swinging `show/hide columns`

![Screenshot 2024-03-28 at 13 41 46](https://github.com/msupply-foundation/open-msupply/assets/117138852/5cefc1b4-9009-41e5-b01d-7e92af0c62c4)
![Screenshot 2024-03-28 at 13 42 04](https://github.com/msupply-foundation/open-msupply/assets/117138852/ffed2ef9-219f-43a9-8b6d-24bbe7653d30)
![Screenshot 2024-03-28 at 13 42 19](https://github.com/msupply-foundation/open-msupply/assets/117138852/7ac4889c-ee11-4902-b664-5f5de5b01b64)

![Screenshot 2024-03-28 at 13 41 32](https://github.com/msupply-foundation/open-msupply/assets/117138852/32fde367-e1e6-4e70-a960-ce6b0d99273e)

## Expected behaviour 🤔

The button should not swing on check/uncheck of the buttons

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. View the list of Outbound shipments and Inbound Shipments
2. Click on 3 vertical bars at the right side of the window
3. Try to check/uncheck all once
4. See the buttons gets swinging (BUG 1)
5. Log out and again log in
6. View the list of inbound shipments
7. Try to hide the `Total` column in first try
8. You cannot hide (BUG 2)

![Screenshot 2024-03-28 at 14 02 33](https://github.com/msupply-foundation/open-msupply/assets/117138852/6be87bac-095e-4f6f-9749-4803a1e8af16)

## Your environment 🌱

- Version: v1.7-00
- mSupply version: 

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Should be fixed in #3125
