### ISSUE TITLE
When creating a new stocktake with 'Items with stock' checked ON, the counted packs should be equal to the snapshot packs instead of 0

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3485]
## What went wrong? 😲
 
When creating a new stocktake with `Items with stock` checked ON, the `counted packs` should be equal to the `snapshot packs` instead of 0.
Rn, the `counted packs` is 0 by default and the difference(`snapshot packs` - `counted packs`) still says 0, which is mathematically wrong and looks buggish to me!
<img width="1252" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/f0f67f48-0224-4bd1-b45b-162e22864c01">

## Expected behaviour 🤔
When creating a new stocktake with `Items with stock` checked ON, the `counted packs` should be equal to the `snapshot packs` instead of 0.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. HAve some stocks in your oms-store
2. Create a new stocktake with the `Items with stock` checked ON and proceed
3. See first error: despite the `counted packs` 0, the difference is still 0.
4. Now let's say you wanna reduce some stocks to 0: so actually open up one of the lines.
5. Since the `counted packs` is already 0, do nothing and just click OK, it's still blue (like unchanged,).
6. Now open that line again and re-enter the value 0 (despite it's already there) and click OK; now the line's black (updated) and this the difference also updated - I call this bad UX experience!

## Your environment 🌱

- Version: `v1.7-rc3 exe`
- mSupply version: v713

- Platform: browser(chrome), server

- Database type: sqlite

## Additional
Spotted while [v1.7 release-testing](https://github.com/msupply-foundation/open-msupply/issues/3341)

**Comment by Chris-Petty** [comment]
The current situation isn't good UX I agree, and solution would be consistent with desktop so I think fair change!

Mobile got around this by basically having an "uncounted" state allowing user to skip lines as not counted (they'd get removed if they finalised the stocktake), and enter 0 if there trying to remove all the stock.

**Comment by roxy-dao** [comment]
Agreed solution: Show `uncounted`

**Comment by AnushaUp** [comment]
# 🧪 Testing
Open_mSupply_Demo `v2.1.0-IA-test-2`


- [ ] Create new stocktake for items with stock
- [ ] See Counted # packs for each line is `[uncounted]`
- [ ] Click on a line to open edit modal
- [ ] See Counted # packs for each line is empty
- [ ] Add counted packs for lines
- [ ] Once you enter counted packs, you can input as 0, but cannot go back to empty
- [ ] Click OK
- [ ] Counted packs (including 0) display correctly in the detail table

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Create a stocktake with master list or one of the filters with a few items
- [ ] Make sure `group by item` toggle is on
- [ ] Uncounted should show as `-`
