### ISSUE TITLE
Program Requisitons: v1.7.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3488]
Tested in v1.7.0-rc3 DESKTOP (BROWSER: chrome) 

# ✅Program Requisitions

## Setups
Make sure to have the below setup/configurations on CLoud Server as they're a must for the programs-based requistions to work

### A. Create a program:
- [x] Create a master-list on the Cloud with the program-items.
- [x] Make sure the `This master list is a program` is checked ON under `Program Settings`
- [x] Add a `Program tag` value and select a period.
- [x] Add types of orders (like normal or emergency)
- [x] Optional: you can add regimen values if you want as well

### B. Connecting a program to store:
- [x] Now for the store you want to enable program-requisitions, make the master-list accesible first, i.e.,
- [x] Open the store details window
- [x] Under `Master list` tab, check the master-list you created as a program
- [x] Under `General` tab, make sure to add the `Program tag` value you added above

## Creating a Program Internal Order
- [x] Click on the New Order button (top right corner): Internal Order> new order
- [x] If you have programs configured, you'll see a different modal to the usual one:
<img width="488" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/698fde06-c7de-49ba-9d55-2a2e44f3a7f9">

- [x] Here, you can select the:
   - [x] Program
   - [x] Supplier
   - [x] Order Type   
   - [x] Period
- [x] Only when you have selected all of the above, can you click Create and continue

## Program IO window
- [x] Once you create the program IO, all the items in the program will populate and you can enter/change the requested pack manually
- [x] You cannot add items, so the Add item and Add from master list buttons are disabled
- [x] As stated in the window, you cannot edit the maximum or minimum MOS on a program based Internal Order. These values are configured by the program
- [x] Clicking on `Use suggested quantities` button will auto-populate the `requested packs` as `suggested quantity` column value
- [x] I think by default, the requested pack should be the imprest quantity set on the master-list program?
- [x] After confirming the IO is sent to the supplier store

## Requisitions
The customer requisition flow is the same as usual as #3345, except that the additional columns: Program, order type and period will have the program values.
<img width="822" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/b6b8271e-2fb3-48de-9c75-2b5d1706b5cf">

**Comment by roxy-dao** [comment]
Testing completed~
