### ISSUE TITLE
Remote Authorisation: v1.7.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3489]
# Remote Authorisation
## Setup/Configuration
For a full description of this process refer to the mSupply[ Remote Authorisation](https://docs.msupply.org.nz/other_stuff:remote_authorisation) documentation.
### In Cloud Server,

**A. The Master list that is used for authorisation**

- [x] Must be the part of the program

![Screenshot 2024-04-03 at 15 40 27](https://github.com/msupply-foundation/open-msupply/assets/117138852/2532c81a-324f-4b18-b0f1-53292c7899d2)

- [x] The master list should be visible to both receiving and supplying stores

![Screenshot 2024-04-03 at 15 41 06](https://github.com/msupply-foundation/open-msupply/assets/117138852/32093197-cac0-4c2d-b5c9-79cef24f339e)

**B. Store permissions**
- [x] In the requesting store, enable the store pref `include requisitions from this store in supplier's remote authorisation process`
- [x] In the supplying store, enable the store preference `Use remote authorisation for response requisitions`

<img width="565" alt="Screenshot 2024-04-03 at 10 09 01" src="https://github.com/msupply-foundation/open-msupply/assets/117138852/9950b60a-7d17-4cac-b9d8-afd0b7a55507">

**C. User permissions**
- [x] In the requesting store, to allow the respective user to change the status of an Internal order, they require permission `Can confirm Internal Order as Sent` to be enabled at their store.
- [x] The authoriser user should have `Use web authorisation system` permission to authorise/deny the requisition

![Screenshot 2024-04-03 at 15 43 13](https://github.com/msupply-foundation/open-msupply/assets/117138852/952d8c37-48e7-403d-b1ef-12ac118355bf)
![Screenshot 2024-04-03 at 15 43 39](https://github.com/msupply-foundation/open-msupply/assets/117138852/94364b0e-6b5c-40f8-85aa-24433bbfd81f)

## Creating Internal Order
Creating IO is the usual as #3487; just a lil difference:  
- [x] When configured as above, the requesting store will see an additional column in the Internal Order list, showing the approval status.

![Screenshot 2024-04-03 at 15 46 07](https://github.com/msupply-foundation/open-msupply/assets/117138852/17e52ccc-34f5-482b-b71d-71e2b6e1aa40)

- [ ] And when viewing a specific Internal Order, there are columns showing the approved quantity, approved number of packs and a comment entered by the approver, if there is one.

## Approving internal orders
After the normal IO is created from the requested store
- [ ] Remote approval process starts at `server-URL/authorisation` (This could be sth like http://localhost:1024/authorisation)
- The authorisation process is [detailed here](https://docs.msupply.org.nz/other_stuff:remote_authorisation#authorising_using_the_web_app)!

You can send empty internal order 

![Screenshot 2024-04-03 at 15 59 43](https://github.com/msupply-foundation/open-msupply/assets/117138852/61caed3c-116d-4ee4-b93d-dc4f30bb1bc4)

The Lines and Authoriser Quantity is set as 0

![Screenshot 2024-04-03 at 15 55 35](https://github.com/msupply-foundation/open-msupply/assets/117138852/9d8ab1bd-8461-486b-9b43-0a26284333df)

## Supplier Requisition
Requisition is also pretty much the same as usual as #3345 with some differences in authorisation status
- [x] When configured as above, the supplying store will have an additional column in the requisition list view showing the approval status 
   - [x] The status is `Pending` until the requisition is authorised
   - [x] Depending on the authorisation, the status will change to either of following
      - Authorised : The comments and quantity to supply can be edited and Outbound Shipments can be created from requisitions that are authorised.
      - Denied : a requisition with this status cannot be edited further and you cannot create Outbound Shipments from it
- [x] And finally, a specific requisition will also have new columns, for the approved quantity and an approval comment, if one has been entered by the approverd

**Comment by raviSussol** [comment]
Not a blocked. All working! See https://github.com/msupply-foundation/msupply/issues/14545#issuecomment-2034029506

**Comment by santoshkhanal12** [comment]
## Approving internal orders
After the normal IO is created from the requested store
- [ ] Remote approval process starts at `server-URL/authorisation` (This could be sth like http://localhost:1024/authorisation)
- The authorisation process is [detailed here](https://docs.msupply.org.nz/other_stuff:remote_authorisation#authorising_using_the_web_app)!

You can send empty internal order. Issue is made here: 

![Screenshot 2024-04-03 at 15 59 43](https://github.com/msupply-foundation/open-msupply/assets/117138852/61caed3c-116d-4ee4-b93d-dc4f30bb1bc4)

**Comment by santoshkhanal12** [comment]
The Lines and Authoriser Quantity is set as 0. Issue is made here: 

![Screenshot 2024-04-03 at 15 55 35](https://github.com/msupply-foundation/open-msupply/assets/117138852/9d8ab1bd-8461-486b-9b43-0a26284333df)
