### ISSUE TITLE
Auto-allocated changing input if stock is expired

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3494]
## What went wrong? 😲
Had this line on an invoice that I issued with expired stock, then I went back to it, clicked on a random place in the modal and the number changes!!!

https://github.com/msupply-foundation/open-msupply/assets/61820074/5c3f8545-d5a4-473c-be83-f350707a6634

## Expected behaviour 🤔
Shouldn't change if I wanted to issue that expired stock

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have an item with 2 stock lines: One expired and one not.
2. Manually issue expired stock
3. Click `Ok` then go back to that line
4. See stock gets re-allocated to the one that isn't expired

## Your environment 🌱

- Version: 2.0.0
- mSupply version: 

- Platform:

- Database type:

**Comment by Chris-Petty** [comment]
Sure this isn't a 1.6.3 issue?

**Comment by roxy-dao** [comment]
Fixed in #3817
