### ISSUE TITLE
Add new stocktake 'filter' for expired in stocktake

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3502]
TODO fill in (as per team discussion)

Expired within days from now (3 hours contingency for refactor, input to be stricter as OR)

**Comment by CarlosNZ** [comment]
Just wanted to clarify the requirements for this one, not sure what we wanted to do for now.

### Options:
1. Add an additional selector in the "New Stocktake" modal, for "Expired items or Items that will be expiring within <X> months", where <X> is a numeric input, then load a new stocktake based on that.
2. Enhance the filtering options on the existing "Inventory" -> "View Stock" list to filter for expired/expiring items as above, and add an "Action" option to "Create new stocktake" based on the selected items.
3. Do both of the above

If we do Option 1, I'd suggest refactoring the New Stocktake modal somewhat to avoid the multiple mutually exclusionary selectors:
![Screenshot 2024-04-16 at 3 52 20 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/56a4da61-07cb-41b2-b8fb-2593b7c3e469)
There should be a single selector where you select one of "Master List", "Location", "Items with stock", and "Expiring Items", then, depending on which one you select, you get an appropriate additional selector/input.

For Option 2, the filters already allow this, but you have to manually put in appropriate dates yourself. I think we would want a bit of discussion regarding how we'd want to "enhance" these filters to select for things like "within 3 months", etc, as it needs to be well thought out, and it won't be trivial if it involves modifications/enhancements to the core Date pickers. Plus it would probably affect all implementations of the date/time filters. 

Can we briefly discuss at tomorrow (Weds) stand-up? @andreievg @lache-melvin ?

**Comment by lache-melvin** [comment]
Thanks Carl, sounds good - my feeling from our discussions is that it is best as Option 1, part of a stock take, as we're making mass changes to stock levels.  

It sounds like Inventory Adjustments are needed for those on the fly quick adjustments to a singular stock line, but we want to encourage users to adjust stock more formally where possible? 

We've also already added the `reduce lines to 0` functionality in Stocktake, which was for reducing expired items...

**Comment by andreievg** [comment]
I like option 1, but I think instead of months, it would be better days ?

About the mutual exclusion, I am not sure about the full intention here, it feel like you would want to create stocktake by master list and location and expired and in stock, but it doesn't quite make sense to create stocktake by master list and location when items with stock is not checked (I think the intention of master list when items with stock is unchecked, was to  fill the stocktake with placeholders, if item is not in stock, which make the location filter not appropriate). Would be great to chat tomorrow to try to figure out all of the use cases.
