### ISSUE TITLE
Unable to access inbound shipments

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3511]
## What went wrong? 😲
 
Breaking out an issue from #3277 
Created from [this comment](https://github.com/msupply-foundation/open-msupply/issues/3277#issuecomment-2031052084)

https://github.com/msupply-foundation/open-msupply/assets/153777484/3249e097-6e26-4dd7-bd3c-3621dbec5e4e

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inbound shipments

## Your environment 🌱

- Version: 1.7.00-RC3
- mSupply version: shouldn't matter

- Platform:
desktop only

- Database type: 
shouldn't matter

**Comment by mark-prins** [comment]
I've been unable to recreate, and there's no datafile mentioned in the issue. 
Adding blocked label as I need more detail.

**Comment by mark-prins** [comment]
oh. it's just this issue again:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/f158f501-0f8b-44e5-aed8-fdfe0fb8d843)

this is already fixed in develop, will fix in 1.7 as well.

**Comment by santoshkhanal12** [comment]
Tested on `1.7.00-RC04`

Looks it looks fine to me.


https://github.com/msupply-foundation/open-msupply/assets/117138852/a76e4ec3-c4ef-458e-899f-84ef9b01daf2
