### ISSUE TITLE
No way to go back on desktop if error

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3515]
## What went wrong? 😲
My desktop error'd and now I can't go back D: and am stuck in an endless loop of trying to press try again. This will happen if any changes breaks something, so probably not an issue if everything is functioning as it should but when it doesn't....................

https://github.com/msupply-foundation/open-msupply/assets/61820074/460a70fb-c20a-42e7-a1d0-10335fc5ca54

## Expected behaviour 🤔
Should be able to go back if the page won't load

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 1.7
- Legacy mSupply Central Server Version:

- Platform: Desktop (electron)

- Database type:

**Comment by Chris-Petty** [comment]
What kinda error though? Is this hard to reproduce? Hard to gauge severity

**Comment by roxy-dao** [comment]
Anything that breaks it really.. so like with the Number refactor the changes weren't brought to 1.7 yet... so every time we release and something breaks then it'll have the `Something went wrong page` with no way to get rid of it but to restart app!

**Comment by Chris-Petty** [comment]
Basically need a back or close button? Or be able to access menu drawer still to navigate?

**Comment by fergie-nz** [comment]
To add to this, I am seeing that our Error catcher isn't handling all thrown errors.

![Screenshot 2024-05-02 at 12 07 02](https://github.com/msupply-foundation/open-msupply/assets/90807420/d2ba1160-8864-4e5e-b072-735dc5d8f6b5)
