### ISSUE TITLE
In Inbound>More>Related documents, am I supposed to get the documents that was attached in original CI?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3524]
## What went wrong? 😲
 
In Inbound>More>Related documents, am I supposed to get the documents that was attached in original CI?

## Expected behaviour 🤔
what else is that Related documents is for otherwise?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a sync system with at least two remote sotes: one oms-store and one desktop-store
2. From desktop-store, create a CI for that oms-store. Make sure to attach document in that CI before finalising
3. Now in oms-store, see that inbound and open More sidebar
4. See error: Under `Related documents`, shouldn't there be that document from previous CI? what else is that `Related documnets` for otherwise? idk of other ways to add document in the INbound UI anywhere!

## Your environment 🌱

- Open mSupply Version: v1.7.0-rc4 exe
- Legacy mSupply Central Server Version: v714-beta3

- Platform: browser (chrome), server exe

- Database type: sqlite

## Additional
Found while [v1.7 release-testing](https://github.com/msupply-foundation/open-msupply/issues/3341)

**Comment by roxy-dao** [comment]
No because we haven't implemented this for invoices yet (:

**Comment by Chris-Petty** [comment]
Yea I was about to say 
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/1a2030b1-a2a5-4efb-b58f-b35529af0a44)

Can we just remove related documents until it's actually implemented? Other than this UI element I don't think there is any code for it...

It's unlikely to be of any value until @jmbrunskill's file sync system is established 😀. To that end the old mSupply desktop functionality for attached documents is pretty useless as it doesn't actually sync the files, just a reference to a file that indicate some computer somewhere may or may not have the file on their filesystem 🤣. And the new OMS system won't be backwards compatible.

**Comment by roxy-dao** [comment]
Related documents also show linked requisitions/shipments, so maybe just rename it?

**Comment by Chris-Petty** [comment]
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/adfe5dfa-a299-4948-b91c-78c96ec21e04)
Yaaaa I get it now haha

**Comment by nisha-dangol** [comment]
> Related documents also shows linked requisitions/shipments, so maybe just rename it?

Yes, rename it! `Related documents` clearly indicate additional documents related to invoice!

**Comment by roxy-dao** [comment]
Technically, related documents will have more stuff in the future (like document upload) but since it doesn't yet....

If we rename it then we'll have to rename it back when those things are implemented?

**Comment by mark-prins** [comment]
I wouldn't rename - as we do want to expand and have related documents as this has been longstanding request in mSupply. If we rename then we potentially confuse users, and more importantly, have to update docs twice.

Can we just close this issue?

**Comment by roxy-dao** [comment]
Yup~ can close

**Comment by Chris-Petty** [comment]
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/a7fad07a-e1f3-4469-86be-af132f34f48f)

IDK what the naming is going to be for the file sync stuff coming soon (which I presume doesn't have scope including requisitions/invoices), but when it does come to those I think there should be a clear separation of things that'll prompt a download or open a file vs things that will navigate to a different page for a related "document". _Related_ documents does read right as it is here, but is close to the old _Reference_ documents so a source of confusion. To that end in OMS maybe call "Reference Documents" -> "Attachments"?

**Comment by nisha-dangol** [comment]
> IDK what the naming is going to be for the file sync stuff coming soon (which I presume doesn't have scope including requisitions/invoices), but when it does come to those I think there should be a clear separation of things that'll prompt a download or open a file vs things that will navigate to a different page for a related "document". _Related_ documents does read right as it is here, but is close to the old _Reference_ documents so a source of confusion. To that end in OMS maybe call "Reference Documents" -> "Attachments"?

Does that mean there will be:
- Reference Documents
    - Attachments : will be additional documents that we'll be able to upload/download like in OG mSupply
    - Related Documents : which is what we already have currently; related invoices (like requisitions for outbounds)
