### ISSUE TITLE
You can confirm outbound shipments with only placeholder lines

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3527]
## What went wrong? 😲
 

Found During release testing: https://github.com/msupply-foundation/open-msupply/issues/3489#issuecomment-2034212191

Blank Internal order can be sent

![Screenshot 2024-04-03 at 15 59 43](https://github.com/msupply-foundation/open-msupply/assets/117138852/18abe97b-7879-4adb-9925-0c540353a25c)

Video Reference: 

https://github.com/msupply-foundation/open-msupply/assets/117138852/cf1eb243-ceac-4dd4-9791-81462b9e43e4

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Establish remote authorisation setup
2. Create a new internal order
3. Add items form master list
4. The Requested quantity values are 0
5. Still the `Confirm Sent` button is active (BUG)

## Your environment 🌱

- Open mSupply Version: v1.7-00-RC4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by Chris-Petty** [comment]
@santoshkhanal12 might be some dev knowledge playing for me, but this smelled like an issue outside authorisation. I can do it with 1.6.02 with just any order:

1. New blank internal order
2. Add a placeholder
3. Confirm it
4. Shouldn't be able to confirm blank orders!

https://demo-open.msupply.org/replenishment/internal-order/109?sort=itemName

I'll retest in 1.7...

**Comment by Chris-Petty** [comment]
@santoshkhanal12 I can't reproduce in dev environment on 1.7... can you double check what server version your OMS desktop is connected to? Should say at the bottom right of the login screen, or in the admin panel if you have admin permission

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/ba382a69-5fb1-4cdf-bc50-921e1cbc1864)

Just checking cause we've had issues with getting desktop connected to the right instance when testing be on LAN or Cloud server.

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply standalone `v2.1.0-IA-test-2`



- [ ] Create an `Internal Order`
- [ ] Try send without lines
- [ ] See message
- [ ] Add lines from masterlist or just add one line
- [ ] Don't put anything in for requested quantity (should be 0)
- [ ] Try to send
- [ ] See message

**Comment by AnushaUp** [comment]
![Screenshot 2024-06-06 at 3 17 13 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/61a93149-c449-46a3-8f97-93ee7155f453)
![Screenshot 2024-06-06 at 3 17 22 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/14f1f9ce-548a-4aef-abeb-73bc6678ea7c)
