### ISSUE TITLE
Translations breaking

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3531]
## What went wrong? 😲
Will update screenshots if I find more
![Screenshot 2024-04-04 at 11 11 23](https://github.com/msupply-foundation/open-msupply/assets/61820074/5ecd4fc8-7ea3-4849-8cae-d424d314e395)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: Current Development
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.0.00`


- [ ] Go to outbound or prescription
- [ ] Add line
- [ ] Hover over 2nd to last column's description
- [ ] Should show unit correctly

**Comment by AnushaUp** [comment]
Result
![Screenshot 2024-05-17 at 4 42 00 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/fc9efbc4-2932-48bc-9027-baf9db828b28)
