### ISSUE TITLE
Invoice line: Input retaining previous value and not rendering properly

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3532]
## What went wrong? 😲
I had an item and put in a number to get the warnings to show up then swapped to another item to try and get this warning to show up but modal wasn't updating. So I closed modal and clicked `Add item` again, and it still has the previous values!

UPDATE: Does seem to reload at some point if I turn away from the web app... but if I enter a new value the value debounces back to the old value 😄 and the message disappears if input no longer in focus... Is this a bug though?!
![Screenshot 2024-04-04 at 11 29 32](https://github.com/msupply-foundation/open-msupply/assets/61820074/b61c9fc7-7c20-4467-affa-826fa60cd42b)

https://github.com/msupply-foundation/open-msupply/assets/61820074/502d3b0a-dc45-422c-a017-60593ca644f7

In prescription while trying to clear value: (Also can't clear value 👀 ) 

https://github.com/msupply-foundation/open-msupply/assets/61820074/117cdae5-47a2-447b-adf4-15a4ca62922a

## Expected behaviour 🤔
Should be rendering properly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add an item with only expired stock to OS
2. Enter value in `Issue`
3. Change to an item with stock available
4. Enter value in `issue`
5. Close modal
6. Click `Add item` again
7. Add the same item as step 3
8. Enter a new value
9. See above message

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Fix state retention problem

**Comment by andreievg** [comment]
Please see comment in: https://github.com/msupply-foundation/open-msupply/issues/3736#issuecomment-2097127032

**Comment by lache-melvin** [comment]
Closed by #3817

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in omSupply `V2.0.00`


Resets issue quantity to 0 if you change items for Prescription/OS (and clears any warnings)

- [ ] Go to outbound shipment
- [ ] Click add item
- [ ] Select an item
- [ ] Enter a value in `Issue [quantity]`
- [ ] Change the item
- [ ] TEST: Issue quantity should be reset to 0
- [ ] TEST: same for prescription

Prevents allocation warnings from clearing until you make a change to an issue packs quantity

- [ ] In OS, enter a quantity to issue that results in a warning (e.g. if only pack size 10 available, and you say to issue 8)
- [ ] Click on the pack quantity input of one of the rows
- [ ] Click off that input (defocus)
- [ ] TEST: warnings still visible
- [ ] Change the value of the pack quantity input of one of the rows
- [ ] TEST: warnings now disappear
- [ ] TEST: same for prescription

Adds debouncing to prescription issue quantity input (immediate auto allocation prevented being able to clear it!)

- [ ] In prescription edit modal, enter a value in `Issue [quantity]`
- [ ] TEST: You should be able to backspace to clear the value
- [ ] In prescription, issue stock for an item where pack sizes > 1 available
- [ ] TEST: you can type a quantity which starts with 1 e.g. 10, 12, 100..
