### ISSUE TITLE
Prescriptions: Unable to erase quantity

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3536]
## What went wrong? 😲

After typing a quantity, it cannot be erased. 
Only way to get rid of the number is to select the whole field and write something on top. (Desktop app)
On tablet we cannot do that, we need to delete the whole item line.

Video available on Gdrive.

## Expected behaviour 🤔

Users should be able to erase and input a new quantity

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Prescriptions'
2. Click on 'Add Item'
3. Type a quantity
4. Now try to erase the number you input. See error

## Your environment 🌱

- Open mSupply Version: 1.7 RC4
- Legacy mSupply Central Server Version: V7.13

- Platform: Desktop app and android

**Comment by CarlosNZ** [comment]
Closed by #3747

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc5, and the number can be erased successfully. Build test passed! :) ✅
