### ISSUE TITLE
Inbound shipment item #Packs uses alphabet keyboard instead of numeric

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3538]
## What went wrong? 😲

![Screenshot_20240404-113223](https://github.com/msupply-foundation/open-msupply/assets/7684221/cdbbe4d1-5873-4d70-bc7a-5277062e163b)

## Expected behaviour 🤔

Numeric keyboard when entering numbers.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an inbound shipment
2. Add item
3. Select item
4. Focus `# Packs`
5. Alphanumeric keyboard! Should be numeric

## Your environment 🌱

- Open mSupply Version: 1.7.0-rc5 Android server mode
- Legacy mSupply Central Server Version: interpreted 7.13
- Platform: Android Lenovo-X505X

- Database type: SQLite

**Comment by roxy-dao** [comment]
Same as #3540. Can this be done at the same time?

**Comment by lache-melvin** [comment]
Closed by #3763

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc4 and the numeric keyboard pops up as expected. Build test passed! :) ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/847c2801-8ff5-4422-a8a7-b201d8e13ada)
