### ISSUE TITLE
Editing Requisition lines on Android is difficult

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3540]
## What went wrong? 😲

When focusing quantity to supply, which is default when editing a line, I cannot see the item name or code or requested quantity
![Screenshot_20240404-123732](https://github.com/msupply-foundation/open-msupply/assets/7684221/c87ebd67-fad9-4228-961a-f8bd960dc0f3)

Not intuitive how to navigate (probs 'cause I'm not familiar enough to know there are buttons hidden by keyboard), end up pressing enter on keyboard which moves focus to the comment field, and now enter just adds new lines to the comment (should we be editing the comment that came from the customer anyway?)
![Screenshot_20240404-123751](https://github.com/msupply-foundation/open-msupply/assets/7684221/b800fb59-90bb-44e3-9ade-5533fb0cc957)

## Expected behaviour 🤔

Can see relevant context when editing a line

Also like elsewhere - should be a numeric keyboard for quantity to supply

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Edit a requisition line on android.

## Your environment 🌱

- Open mSupply Version: 1.7.00-rc5 android server
- Legacy mSupply Central Server Version: interpreted v7.13

- Platform: Android Lenovo-X505X

- Database type: sqlite3

**Comment by andreievg** [comment]
I've been driving one point through, I think omSupply mobile UI/UX should be evaluated in a more strategic and overall mindset, and hot fixes by dev team may lead to
* Design discussions during PR review
* Fixes with side effect in other areas

I still hold to that point of view, but this issue seems to be quite urgent (although this has been an issue from the beginning ?)

Maybe we just make modal full screen ? (would that fix it ?)

**Comment by Chris-Petty** [comment]
100% should make sure design changes should go through PO and Designer. IMO a lot of good design comes from consistency allowing users and devs alike to rapidly learn and apply similar patterns across different contexts, so what ever happens here shouldn't be _just_ requisition line editing.

@mark-prins as PO should probably decide UX and prioritise. I'd suppose this is high priority as well, many mobile users report grief it seems. The counter point is that it's a significant UX change so taking the time to get it right in as few shots as possible is good. Maybe feature flag and beta so users can opt in and out and transition would be cool (but a new kind of overhead managing two UIs).

**Comment by Chris-Petty** [comment]
@andreievg that said, I think it should be very established now that numeric fields should have numeric keyboard!

**Comment by jmbrunskill** [comment]
> @andreievg that said, I think it should be very established now that numeric fields should have numeric keyboard!

@Chris-Petty  or @mark-prins Can one of you add this to the wiki? Ideally with a link to an example...
https://github.com/msupply-foundation/open-msupply/wiki/Code-Review-Comments---Typescript

**Comment by Chris-Petty** [comment]
I think it's a bug and that all numeric inputs by default should use numeric keyboard it shouldn't even be a choice that requires constant review, so don't see the point of adding to wiki?

**Comment by mark-prins** [comment]
the numeric input would be fixed with #3763 and the fix for the modal is in PR.
Agree, that the numeric input is a systemic change and we shouldn't require adding that to the wiki now. We do need to have a full review of site usability and behaviour on a tablet, that's in the list of things to do, just not at the top atm

**Comment by lache-melvin** [comment]
Closed by #3802

**Comment by AnushaUp** [comment]
# 🧪 Testing



- [ ] Open edit modal for a line in a response requisition on Android
- [ ] Quantity to supply should autofocus, key pad appears
- [ ] Modal should adjust in size, so you can still see item name/code/requested quantity

**Comment by AnushaUp** [comment]
@lache-melvin Here, the item name is not showing properly but other then that its working fine.
![Screenshot_20240516_162211_Open mSupply](https://github.com/msupply-foundation/open-msupply/assets/115983430/1429e47d-9952-4d7a-94cf-25ca5ebf0681)

**Comment by lache-melvin** [comment]
Thanks @AnushaUp - I think it's fine for the item name to cut off if it is long, but we should add a tooltip! Will create an issue for this 🙏
