### ISSUE TITLE
When creating shipment from requisition, it gives toast welcoming me to my store again like I just logged in

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3542]
## What went wrong? 😲

Gonna be too hard to screens shot soz and don't have screen recorder on old tablet yet!

Basically, when I press create shipment for a given requisition, it:
1. Goes to a loading page
2. Displays the outbound shipment page
3. As it does this, it shows "Welcome to X store!" Toast. But why?

## Expected behaviour 🤔

I didn't just login or change store. Don't show the toast!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create shipment for a given requisition
2. Goes to a loading page
3. Displays the outbound shipment page
4. As it does this, it shows "Welcome to X store!" Toast. But why?

## Your environment 🌱

- Open mSupply Version: 1.7.00-rc5 Android Server
- Legacy mSupply Central Server Version: interpreted 7.13

- Platform: Android Lenovo-x505x

- Database type: sqlite

**Comment by roxy-dao** [comment]
Not getting it 🤔

**Comment by Chris-Petty** [comment]
Hmm yolo close till someone does
