### ISSUE TITLE
Login Problem in omSupply site

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3544]
### Scenario 1: After encountering some sync issues:
When there's some sync problem in the oms site like this(below image) was happening in my setup. After the problem was resolve there was login problem. Even the password was right the user was not able to login and had to re-initialise the site again.
![photo_2024-04-04 1 05 52 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/22801cb2-62f5-4ff6-8dc1-cdeefc001858)

![Screenshot 2024-04-04 at 12 53 45 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/668c6129-3c2c-420e-a9a0-cab9a466809d)

https://github.com/msupply-foundation/open-msupply/assets/115983430/21b23a8b-d075-4605-8da7-b3d943c0d6a0

### Scenario 2: No prior sync-issues
- Just login and leave your desk : go n grab some coffee
- Come back to see that your session ends and prompts you to log in
- Login in with your regular credentials
- See error: the correct credentials won't work! **- and lemme tell you, this is not happening all the time; very irregular but have seen quite a number of times already recently!**
- Hard refresh your browser and this time, the same credentials works! 

## Expected behaviour 🤔

Login should be allowed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. There's no any exact steps (needs investigation)

## Your environment 🌱

- Open mSupply Version: `1.7.00rc4`
- Legacy mSupply Central Server Version: `7.13.02`

- Platform: oms desktop(windows 11) and oms server (Browser: chrome)

- Database type:

**Comment by raviSussol** [comment]
@AnushaUp It seems to me that your `https://anusha.msupply.org:2048` (i.e. mSupply web server) has ssl expired? Try replacing with valid cert first and resync from the omsupply?

**Comment by andreievg** [comment]
@AnushaUp can you please confirm, and close if your certificate was in fact expired
