### ISSUE TITLE
When creating a new patient, Internal ID is displayed until the patient is saved

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3547]
## Is your feature request related to a problem? Please describe 👀

When creating a new patient under Dispensary -> Patients, an Internal ID that is generated instantly is displayed at the top of the page, until the patient is saved. After the patient is saved, their full name is displayed instead of an Internal ID. 

![photo_2024-04-05 10 39 06](https://github.com/msupply-foundation/open-msupply/assets/153777484/27934e71-c680-4b40-83c4-a1da88d8da6c)

## Describe the solution you'd like 🎁

I think it will be more user-friendly to not display an Internal ID (as it doesn't really provide any useful information, and looks really long and clunky) - instead, there can be an empty space until the details are saved, or, as Clemens suggested, we can display 'New Patient'. 

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

N/A

### Moneyworks Jobcode 🧰

N/A

**Comment by AnushaUp** [comment]
# 🧪 Testing
Open_mSupply standalone `v2.1.0-IA-test-2`


- [ ] Be in dispensary mode
- [ ] Create a patient
- [ ] While editing patient details, see `New Patient` in the breadcrumb
- [ ] Click `Create`
- [ ] Now name appears in the breadcrumb
