### ISSUE TITLE
After patient-merge in mSupply-OG, it should reflect in patient list accordingly in oms-side as well

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3555]
## Expected behaviour 🤔
Don't show merged patient in the list after merge?

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Have a sync-setup with at least one desktop-OG-dispensary and oms-dispensary
2. In desktop-OG, create two patients: in my eg: `flareon1` & `flareon2`
3. Edit visibility so that it's visible to oms-dispensary as well and sync
4. Now in cloud, merge those two patients: I merged `flareon1` & kept `flareon2` and sync
5. In oms-dispensary, see that merged patient (`flareon1`) still appearing!
<img width="852" alt="SCR-20240405-j5m" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/5d0406a4-e388-42ee-93f1-a3b6f736385d">

6. Create a prescription and add that merged-patient (`flareon1`)
7. See error: OtherPartyDoesNotExist toast; which is technically correct, but I think better would be to not show the merged patient at all!
<img width="457" alt="SCR-20240405-j5r" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/e1684011-208d-490a-8109-cc22e8e36d62">

## Your environment 🌱

- Open mSupply Version: v1.7.0 exe
- Legacy mSupply Central Server Version: v714-dev5

- Platform: server exe, browser (chrome)

- Database type: sqlite

**Comment by Chris-Petty** [comment]
Nice find @nisha-dangol.

@clemens-msupply I think the presumption in name merge was that patients are filtered by name visibility in the current store. After merge, there should be no name visibility remaining for the "deleted" patient in the merge.

So either: 

1. merge should soft delete the name and then that is filtered out by default at the repo layer.
2. the programs patient search API should consider name visibility.
3. I'm completely off track of the bug's cause 😁

**Comment by clemens-msupply** [comment]
Also haven't reproduced it yet but sounds reasonable. The visibility is for the current store, so this is not a solution since in general we want to query all known patients. 

Another alternative is to simply delete the name_row entry in omSupply. I.e. do we ever will need the soft deleted record on the remote server? When undeleting a name this would be done on the central server right? So should we only soft delete there?

**Comment by Chris-Petty** [comment]
> Also haven't reproduced it yet but sounds reasonable. The visibility is for the current store, so this is not a solution since in general we want to query all known patients.
> 

Fair enough - soft delete seems better to me in that case

> Another alternative is to simply delete the name_row entry in omSupply. I.e. do we ever will need the soft deleted record on the remote server? When undeleting a name this would be done on the central server right? So should we only soft delete there?

Unmerging would be done on central server. In theory it could be hard deleted on remotes and server can resync the soft deleted name. But I assume that'd be more work? Be forks in logic based on being central or remote, seems easier to just make remote soft delete too right?

**Comment by clemens-msupply** [comment]
Only just seeing that a name already has a `is_deleted` column in mSupply, I guess this is for merges, right? and they always get synced as well ? So yes much easier to just integrate this column.

**Comment by Chris-Petty** [comment]
> Only just seeing that a name already has a `is_deleted` column in mSupply, I guess this is for merges, right? and they always get synced as well ? So yes much easier to just integrate this column.

Haha hmmm I don't know if there is a soft delete in mSupply, seems suss... Ah yea that's just for HL7 integration. Looks like  normal name or patient merge will literally delete the "deleted" record, while HL7 merge messages will soft delete. Bit of a mess!

That said, just doing soft delete in OMS still works out here right?

**Comment by clemens-msupply** [comment]
yes sounds good, i.e. doing the soft delete in pre-paration for omSupply central. However, we would need the remove this soft delete logic in the future because the soft deletes would come through automatically from central, wouldn't they?

Just for some more background, the reason why I was questioning soft deletes was the following case:
- have a remote checkout and receive a name MERGE record
- soft delete the name on the remote site
- resync the site with mSupply
- the soft deleted name is now gone, what raised my question of why doing it

**Comment by Chris-Petty** [comment]
Ah yea, that's true for all the soft deleted fields in OMS that are hard delete in legacy... I'm OK that it may become redundant code later on.

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.0.00-rc5`
See issue, but found this easier:
- [ ]  add a dispensary store to the central server site
- [ ] create name "a1" and "a2" on the central server
- [ ] sync and see names on the remote sites
- [ ] merge "a1" and "a2"
- [ ] sync, there should only be one name visible on the remote site now
