### ISSUE TITLE
Column hide/show not working properly

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3561]
## What went wrong? 😲
Pressing on the select box causes some hidden columns to pop back up

https://github.com/msupply-foundation/open-msupply/assets/61820074/75396ffc-9b78-45a1-b3cf-2718b7748fa5

## Expected behaviour 🤔
Columns should stay hidden.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any table
2. Hide some columns (maybe 4-5?)
3. Click on select box
4. See columns pop back up

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Yeah, basically any change to the table will cause this problem:
- changing sort order
- refreshing page
- selecting a checkbox

**Comment by AnushaUp** [comment]
@roxy-dao @lache-melvin how can this be tested in build version.

**Comment by roxy-dao** [comment]
- [ ] Click the three bars to hide columns (3-5?)
- [ ] Click on one of the select bars
- [ ] Do the hidden columns pop back up?
