### ISSUE TITLE
Add Ok & Next button to stock line modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3562]
> And also don't forget it's quite important to implement "OK & Next" button at the stock line details level. If user is filtering all his expired batch, he wants to be able to perform inventory adjustments for all of them in a row (ideally, like in OG, OK & Next would keep you on the same tab in the modal)

_Originally posted by @richardmoizeau in https://github.com/msupply-foundation/open-msupply/issues/3539#issuecomment-2041651131_

**Comment by roxy-dao** [comment]
We've changed how this view looks... so do we still need an `Ok & Next` button if we can only adjust on the stock line itself? Can this be closed?

**Comment by lache-melvin** [comment]
Ah yep, thanks Roxy will close. We also now cover off the `wants to adjust all expiring items` issue by being able to filter by expiring items and then reduce all lines to 0 in a stocktake 🙏
