### ISSUE TITLE
Item id isn't being sent to query to display master lists in Item detail view

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3563]
## What went wrong? 😲
Can't see the master lists that the item belongs to since item_id isn't being sent with the query

## Expected behaviour 🤔

Should show the master lists that the item belongs to

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Item`
2. Click on an item line
3. Click on master list tab
4. See nothing

## Your environment 🌱

- Open mSupply Version: Current development
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Do with #3563

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.0 exe

- [x] Go to items
- [x] Click on an item
- [x] Go to the Master List tab
- [x] The master list associated with the item should show up
