### ISSUE TITLE
Asterisk for stocktake reasons is always there even if field isn't required

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3567]
## What went wrong? 😲
Asterisk for stocktake reasons is always there even if field isn't required and makes me think that I should be inputting a reason even though it's disabled or doesn't apply to the line.

Doesn't affect workflow but can be very misleading >.>

## Expected behaviour 🤔

Should only show asterisk if there are inventory reasons AND if counted packs has changed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Stocktake`
2. Create a new `Stocktake`
3. Go into a line and see the asterisk

2nd way:

1. Have inventory adjustments reasons configured in central server
2. Sync reasons to OMS
3. Go to `Stocktake`
5. Create a new `Stocktake`
6. Go into a line and see the asterisk

## Your environment 🌱

- Open mSupply Version: 2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply_Demo `v2.1.0-IA-test-2`


- [ ] Have inventory adjustments reasons configured in central server
- [ ] Sync reasons to OMS
- [ ] Go to Stocktake
- [ ] Create a new Stocktake
- [ ] Click `Add item`
- [ ] Select an item
- [ ] See no reason inputs have asterisk
- [ ] Enter a different counted # packs
- [ ] Reason enables and asterisk appears

**Comment by AnushaUp** [comment]
@lache-melvin Here, while making one of the reason inactive in server, then got this.
https://github.com/msupply-foundation/open-msupply/assets/115983430/66e9ed0a-e5e7-4c81-a5b3-f856bbe69341

![Screenshot 2024-06-05 at 6 12 10 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/9a450215-93cd-4c52-8f28-0a00cefc55ed)

**Comment by lache-melvin** [comment]
Hi @AnushaUp - could you confirm for me, did you have both reasons active, then disable one, and now the reasons dropdown doesn't work? Or you had no reasons active, you set one to active, but it didn't come through? 

FYI - just syncing won't update the reasons. You'll need to log out and log in again. Maybe that was the issue?

**Comment by AnushaUp** [comment]
@lache-melvin I tried to make both the reasons in active and make a reason active again and this happened. Tried to logout and login again but same is happening as mentioned above. This may be a bug please check once. Thanks!

**Comment by AnushaUp** [comment]
@lache-melvin its little weird but its doesn't show at once we have to logout twice and it is shown.

**Comment by AnushaUp** [comment]
@lache-melvin one more question for a stocktake which have a reason already and trying to edit the stocktake line and increase the counted pack quantity after disabling all the reasons. Is this alert expected?

![Screenshot 2024-06-07 at 10 37 53 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/a1eccc77-c938-4e5f-8cb7-bbbc79879834)

**Comment by lache-melvin** [comment]
> @lache-melvin I tried to make both the reasons inactive and make a reason active again and this happened. Tried to logout and login again but same is happening as mentioned above. This may be a bug please check once. Thanks!

Thanks @AnushaUp - I had a look, and I think this is due to the caching of reasons, refreshing the page after sync should solve... but have flagged in [this issue](https://github.com/msupply-foundation/open-msupply/issues/3696)! 🙏

**Comment by AnushaUp** [comment]
Thanks @lache-melvin👍

**Comment by lache-melvin** [comment]
> @lache-melvin one more question for a stocktake which have a reason already and trying to edit the stocktake line and increase the counted pack quantity after disabling all the reasons. Is this alert expected?
> 
> ![Screenshot 2024-06-07 at 10 37 53 am](https://private-user-images.githubusercontent.com/115983430/337528060-a1eccc77-c938-4e5f-8cb7-bbbc79879834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzY4NTYsIm5iZiI6MTcxNzczNjU1NiwicGF0aCI6Ii8xMTU5ODM0MzAvMzM3NTI4MDYwLWExZWNjYzc3LWM5MzgtNGU1Zi04Y2I3LWJiYmM3OTg3OTgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwNTAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmE1YTkwMWYyNThhOGJhMzVmNzM3NDJkNzZlM2EwOTljNGYyODIxNGU4MzMxYWYyNTBkNjBiNjRjZWU4ZWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N4BNfeiSlDS5NdIVtDbophOOkLne9XZ8SEJzi9bgC2c)

This one is definitely a bug though! If you could create an issue that would be awesome 🙏
