### ISSUE TITLE
Current patient selection modal makes it seem like the store has 0 patients

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3568]
## What went wrong? 😲
Old patient selection UI when creating new prescriptions
![image](https://github.com/msupply-foundation/open-msupply/assets/61820074/1f7c5f10-44df-403f-a9f9-4537c41bfb02)

New UI
![Screenshot 2024-04-09 at 14 00 13](https://github.com/msupply-foundation/open-msupply/assets/61820074/d5e2ecb3-b561-47ef-a059-7d00ca4573f2)

## Expected behaviour 🤔
Needs a way to indicate that the user has to type something to get searches to show up. Not sure why it was removed, but the current UI makes me think that there are no patients

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Prescriptions`
2. Click on `New Prescription`
3. See patient selection modal is empty

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Isn't an issue... it does say `Search by name or code` when you first click on the modal

**Comment by regotaina** [comment]
New UI is available now on RC3. PASSED THE TEST 👍🏾 

![Screenshot 2024-05-08 at 1 58 10 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/abd2eefb-296a-4ad0-babc-1da0dbac1373)
