### ISSUE TITLE
Pagination footer scrolls away on side scroll

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3579]
## What went wrong? 😲
 

Pagination footer scrolls away on side scroll!

https://github.com/msupply-foundation/open-msupply/assets/55115239/e805363c-c363-43de-b25c-871034fa4ac8

Usually don't notice on a full big screen, as columns all fit - would be more of a problem on tablet 🙈 

## Expected behaviour 🤔

Pagination bar is sticky, no matter where in the table you scroll to.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a table view (Stock is an easy one to check, as has lots of columns)
2. Shrink your screen width so not all the columns fit on the screen
3. Scroll to the right
4. See the pagination bar disappear 😢 

## Your environment 🌱

- Open mSupply Version: 1.7
- Platform: Browser (Chrome)

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply stand alone and mobile `v2.1.0-IA-test-2.exe`
- [ ] Load a table that has more than 1 page of content and is wider than the available viewport.
- [ ] Scroll to the side, confirm that the Pagination bar stays in place and doesn't scroll with it.
