### ISSUE TITLE
Code required on patient creation but there is no indication

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3581]
## What went wrong? 😲
Code is required for patient creation but there is no indication that it is required. When I enter the first and last name of a patient in the modal and get redirected to the patient creation detail view, I am blocked from creating the patient without knowing why!

## Expected behaviour 🤔
Should have some indicator required fields and also be consistent. If code is required then it should block on both the modal and creation detail view

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Patients
2. Click on `Add Patient`
3. Enter first and last name in modal click `Ok`
4. Click `Ok` again on search window
5. See that the creation page is blocked

## Your environment 🌱

- Open mSupply Version: 2.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by regotaina** [comment]
on RC3 it's quite clear which fields are mandatory as soon as you click on the button 'new patient':
![Screenshot 2024-05-08 at 2 04 09 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/36b3c64b-04e4-4fa0-b65b-8cbd8e98c8be)

PASSED the test 👍🏾
