### ISSUE TITLE
Contact tracing: Wrong message on save

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3584]
## What went wrong? 😲
When I click `Save` when adding a contact trace, it says `Deleted successfully` in green 😆 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by nisha-dangol** [comment]
Moving to Done since I see the correct toast `Saved successfully` on saving a contact in v2.0.0 apk
