### ISSUE TITLE
Linked Patient doesn't populate patient's contact tracing tab

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3585]
## What went wrong? 😲
The information in `Contact Tracing` -> `Family/Partner Information` isn't populated with the linked patient details. 

## Expected behaviour 🤔
I expected it to auto-populate or else why would allow the user to link an existing patient? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by clemens-msupply** [comment]
If I understand you correctly, this works as intended.

The form records the contact information as reported by the patient. The patient might have wrong or incomplete information about the patient.
So it might be possible that the wrong patient is linked.
Keeping the original information allows the clinician to, for example, re-link to the correct patient.

**Comment by roxy-dao** [comment]
> If I understand you correctly, this works as intended.
> 
> The form records the contact information as reported by the patient. The patient might have wrong or incomplete information about the patient. So it might be possible that the wrong patient is linked. Keeping the original information allows the clinician to, for example, re-link to the correct patient.

But then you get nothing when you look at Patient -> Contact tracing tab... Seems very lacking. Can't they just re-link to correct patient later but still populate info?

**Comment by clemens-msupply** [comment]
But then it might display the info from the wrong patient. This form records the information the patient has given initially about the contact (might need to make this clearer as well?).

However, we could still make the linked patient information available, e.g. in a hover info box, or in the sidebar?

**Comment by roxy-dao** [comment]
Hover not obvious in tablet though =/
