### ISSUE TITLE
Return made/initiated from desktop-OG doesn't create the link under related-doc for the oms-store's inbound-return

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3592]
## What went wrong? 😲
 
From [here](https://github.com/msupply-foundation/msupply/issues/14585#issuecomment-2048898980)

## Expected behaviour 🤔
Since oms2.0 is supposed to have/show links under `Related documents` in the returns (as long as they're not manual ones), be the return from oms or OG, the link is expected!

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Sync setup with at least one desktop-OG store
2. From OG, create a return(i.e., a Sc) to oms-store and sync
3. IN oms-store, you'll receive it under Distribution>Inbound returns
4. OPen it and check related docs
5. See error: No link at all

## Your environment 🌱

- Open mSupply Version: v2.0 apk,exe - I got it from devs fyi! 
- Legacy mSupply Central Server Version: v714-00-dev10

- Platform: server exe, browser(chrome), android

- Database type: sqlite

**Comment by roxy-dao** [comment]
Doesn't for OS/IS either, so would be great if that could be fixed in this issue as well

**Comment by lache-melvin** [comment]
> Doesn't for OS/IS either, so would be great if that could be fixed in this issue as well

I can't replicate this, linked requisition is coming through fine for me with OG Outbound Shipment -> OMS Inbound Shipment 👀 If it can be replicated, can we create another issue for this?

Regarding returns, this is expected. OG Outbound Return -> OMS Inbound Return won't have related documents.

 When OG Supplier Credit (Outbound Return) is created from a Customer Invoice, the `om_original_shipment_id` on the outbound return is not populated (as this is a new omSupply field). This is the field we use to determine if there is a related document (i.e. the Outbound Shipment) when we create the transferred Inbound Return... so creating that relationship isn't possible for OG -> OMS returns.

Closing as won't implement this 🚀
