### ISSUE TITLE
SOH in requisition line is a float in OG but is an integer in OMS

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3598]
## What went wrong? 😲
In OG mSupply, requisition line's available stock on hand can be a float, but in OMS it is an integer. Will need some discussion about how to handle this. Also related to how we handle #2663 
Also suggested quantity in requisitions can be a float in OG but is an integer in OMS

## Expected behaviour 🤔
Should be able to integrate.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
@clemens-msupply Can you confirm if this was done as part of your overall packs to float change?

**Comment by clemens-msupply** [comment]
Yes thats from `develop`:

```rust
pub struct RequisitionLineRow {
    pub id: String,
    pub requisition_id: String,
    pub item_link_id: String,
    pub item_name: String,
    pub requested_quantity: f64,
    pub suggested_quantity: f64,
    pub supply_quantity: f64,
    pub available_stock_on_hand: f64,
    pub average_monthly_consumption: f64,
    pub snapshot_datetime: Option<NaiveDateTime>,
    pub approved_quantity: f64,
    pub approval_comment: Option<String>,
    pub comment: Option<String>,
}
```
