### ISSUE TITLE
Authorisation Required for Sync File Endpoints

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3601]
## What went wrong? 😲
Currently there's no login required for endpoints that allow 
- file uploads for sync files
- Downloading sync files

## Expected behaviour 🤔
Only logged in users should be able to download and upload files

(Maybe we need something more targetted? Permissions based on the table we're uploading too?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upload a file (See assets -> Documents for example)
2. Click on an uploaded document to get the link.
3. Copy link into new browser (Private Browsing Mode, or Differnet browser not logged in to OMS)
4. Should give you a permission denied error

## Proposed Solution

Could include https://github.com/msupply-foundation/open-msupply/issues/3002 to check the login cookie.
Permissions could be simply do you have a login for now...

**Comment by jmbrunskill** [comment]
Agreed Solution.

Upload, Delete, and Download endpoints for remote server should require an Auth Cookie (This would potentially allow someone with access to download or delete a file that shouldn't have access too, however this seems unlikely when not exposed via the frontend)

Upload Sync V6 (central) should receive sync settings as per other endpoints and validate these against legacy.
This will probably require a multipart form submission.

**Comment by andreievg** [comment]
@jmbrunskill I think this one was resolved ?

**Comment by jmbrunskill** [comment]
Yup, solved now thanks!
