### ISSUE TITLE
Sync buffer intergration_error: show when item was ignored

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3606]
## Is your feature request related to a problem? Please describe 👀

For example, in the MasterListNameJoinTranslation, an item is ignored if the name_id is empty:
```rust
PullTranslateResult::Ignored("Missing name_id".to_string()
```

However, the "intergration_error" says: "Translator for record not found". Think this could say: "Ignored: Missing name_id" instead?

I.e. put the Ignored message into the integration_error.

**Comment by Chris-Petty** [comment]
Removed from testers board as will not be very obvious how nor useful to manually test.

**Comment by roxy-dao** [comment]
Not sure why bot added this back to tester board, but removing again
