### ISSUE TITLE
New asset_type table clashes with existing asset_type table

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3608]
## What went wrong? 😲
 

There is already an asset_type table in mSupply. When trying to integrate this tables there is now a deserialization error in omSupply.

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/caf830b5-00a2-4b6f-b3bc-06a0d4b7241a)

## Expected behaviour 🤔

As I understand it will not be a real problem, but it would be nice to not having an error in the sync_buffer. Maybe find a new table name?

**Comment by fergie-nz** [comment]
I'm renaming to asset_catalogue_type.

I had considered renaming to "asset_set" or "asset_group", but figured it would be better to have more specificity where both tables are in context.
