### ISSUE TITLE
Error when attempting to create new asset

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#3634]
## What went wrong? 😲
Recurring status query?

Unable to create new CCE asset.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain
2. Click on Equipment
3. Click on 'New Asset' button
4. Select refrigerators, then see how status list keeps refreshing

https://github.com/msupply-foundation/open-msupply/assets/90807420/bb450f8f-f3f5-4004-840b-8a6d214af4a5

**Comment by mark-prins** [comment]
Duplicate of #3627

**Comment by roxy-dao** [comment]
Is the flashing and unable to create the asset linked? 🤔

**Comment by mark-prins** [comment]
the flashing is the same. Where is unable to create mentioned? - I didn't see it in this issue

**Comment by roxy-dao** [comment]
Oh sorry, it says Unable to create new CCE asset. <- in what went wrong and I got confused >.>

**Comment by mark-prins** [comment]
Closing as duplicate
