### ISSUE TITLE
Patient ages: display as months and days if under 1 year old

### ISSUE THREAD

**Issue by GaryWilletts** [msupply-foundation/open-msupply#3641]
## Is your feature request related to a problem? Please describe 👀

Issue raised by PLM Sierra Leone. Seems small but actually makes a big difference to users. If we don't do it and display the age as 0 then they have to work out the actual age in months and days.

## Describe the solution you'd like 🎁

If a patient's age is less than 1 year then display as "xx months, yy days". They paid to have this done in mobile (now live) and will need this in Open mSupply before they roll out to more sites (planned for Q4 2024 or Q1 2025 approximately).

### Describe alternatives you've considered 💭

Ignoring their request. If we do this they won't be able to roll out Open mSupply, they'll have to stick with mSupply mobile which will make everyone sad.

### Additional context 💌

Gary said we'd do this for free because it's small and they're good people (strategic decision will little real cost to us but lots of goodwill earned).

**Comment by CarlosNZ** [comment]
Currently, the DOB component (in JSONForms) is a bi-directional input (i.e. can edit either the DOB *or* Age fields and the other updates accordingly:
![Screenshot 2024-08-02 at 11 57 24 AM](https://github.com/user-attachments/assets/ac522b0e-0050-405c-b355-37c44b919b3f)

For the purposes of this feature, I think it would be simpler to only *display* the age in months/days when it goes below 1, rather than having a complicated three-way interconnected input.

I assume this is acceptable?

**Comment by mark-prins** [comment]
> I assume this is acceptable?

I was going to say yep - but have implemented a year / month / day entry and it didn't take long.
Quick and dirty look is

<img width="473" alt="image" src="https://github.com/user-attachments/assets/4f705e70-a802-4206-b3b4-fe2a05f7be9f">

where all three numeric inputs update the Date value and vice versa

**Comment by regotaina** [comment]
Tested on RC5

Desktop app

# 🧪 Testing

Go to a Patient, and change their date of birth to a value less than one year ago.

Still cannot see the change with a default Patient schema, according to #4536 we should update that to include the correct DOB component 

that's how it looks like: 

![telegram-cloud-photo-size-1-5057771643052600751-x](https://github.com/user-attachments/assets/ff5db4ef-2808-462a-b2c1-8a3159353867)

**Comment by CarlosNZ** [comment]
Going to re-open this issue, will fix tomorrow.

There is a default Patient schema in the codebase which is using the generic "Date" component rather than our custom DOB component. Will update that, should be a quick fix.

**Comment by CarlosNZ** [comment]
Fixed by #4645

**Comment by regotaina** [comment]
Tested on V2.2.0 Release

Passed the test, thank you @CarlosNZ !!

![Uploading Screenshot 2024-08-23 at 5.25.27 PM.png…]()
