### ISSUE TITLE
Patient search results: display in created date order

### ISSUE THREAD

**Issue by GaryWilletts** [msupply-foundation/open-msupply#3642]
## Is your feature request related to a problem? Please describe 👀

PLM in Sierra Leone paid for this to be done in mSupply mobile here https://github.com/msupply-foundation/mobile/issues/5395

We added a "Created date" column to the patient search results, default results order was newest created date at the top (but column header was clickable to reverse it if required).

The column seems very helpful in determining whether the returned patient record is the patient sitting in front of you when there are duplicate names (very common in some places).

## Describe the solution you'd like 🎁

Something like that above. Could work with a store preference, can be always on if better.

### Describe alternatives you've considered 💭

Ignoring their request. If we do this they won't be able to roll out Open mSupply, they'll have to stick with mSupply mobile which will make everyone sad.

### Additional context 💌

Gary said we'd do this for free because it's small and they're good people (strategic decision will little real cost to us but lots of goodwill earned). PLM paid to have this done in mobile (now live) and will need this in Open mSupply before they roll out to more sites (planned for Q4 2024 or Q1 2025 approximately).

**Comment by DhanyaHerath** [comment]
@GaryWilletts where is the preference? I couldn't find it: 
![image](https://github.com/msupply-foundation/open-msupply/assets/29744386/b9d07513-2d0c-4075-a58e-5d99dd589f7c)

**Comment by DhanyaHerath** [comment]
And should it be only for search results or also in the patient list?

**Comment by mark-prins** [comment]
Unable to find the preference - though I did find this:

<img width="560" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/c78b9530-6aae-4fbf-abd3-c1ecd153e528">

The [change in mobile](https://github.com/msupply-foundation/mobile/pull/5421) is to add the created date column and sort by this by default

**Comment by GaryWilletts** [comment]
@DhanyaHerath @mark-prins I stand corrected - we added the column for everyone and did away with the store preference, se per Arjun's comment here https://github.com/msupply-foundation/mobile/issues/5395#issuecomment-1880524723

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in v2.1.0-rc1


- [ ] Have some patients with different created datetimes
- [ ] Go to `Patients` page
- [ ] See that newest patients are displayed first
- [ ] Click created date sorting, should sort correctly
