### ISSUE TITLE
Move `Stock line` modal to its own page

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3656]
## The suggestion

Stock Line has had more functionality added to it and the modal is now overcrowded with tabs. 

It would be nice if clicking on a stock line will redirect the user to the stock line page instead of opening up a modal. This would also allow the repack modal to be refactored as a tab in the stock line window.

This can be done in two parts: 
1. Refactor the modal to its own page
2. Refactor `repacks` to be a tab in the `Stock line` page

### Why should we invest time in this?
Things will looks less crowded and makes everything more mobile friendly (especially when one wants to do a repack! see #3439)

### Are there any risks associated with this change?
Probably not, it's the same thing we do for `Items`, might have to re-train users but should be intuitive enough...

### How much effort is required?
Would need quite a bit of effort and maybe some UX input

**Comment by CarlosNZ** [comment]
Still waiting to merge final PR: https://github.com/msupply-foundation/open-msupply/pull/4009
