### ISSUE TITLE
GAPS: Estimating additional cold storage capacity demand for future population growth

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3663]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.  

The pain points are: 
-  There is no easy way for EPI managers to estimate the additional cold storage capacity demand needed for the country's future population growth. 

Problems to solve: 
- A way for central users to be able to define the country's expected population growth over the next 5 years
- A way to calculate the additional total cold storage needed per facility taking into account the population growth.

## Describe the solution you'd like 🎁
**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**
- [ ] B.3.1 
  - [x] Define population growth for next 5 years

**Issues**
- [x] #3844
- [x] #3848
- [x] Backend to save population & demographic data

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

### DB Design (TBC)

```mermaid
erDiagram
    demographic {
        TEXT id PK "NOT NULL"
        TEXT display_name "UNIQUE NOT NULL"
        TEXT code "UNIQUE NOT NULL"
        DOUBLE percentage "percentage of population"
        TIMESTAMP entry_datetime
        TEXT user_id FK "User who entered the data"
    }
    national_population {
        TEXT id PK "NOT NULL"
        TEXT year "UNIQUE"
        DOUBLE growth_rate
        INTEGER year_end_population
        TIMESTAMP entry_datetime
        TEXT user_id FK
    }
    population_served {
        TEXT id PK "NOT NULL"
        TEXT store_id FK "Store Table OR Facility?" 
        TEXT year
        INTEGER population
        TIMESTAMP entry_datetime
        TEXT user_id FK "User who entered the data"
    }
```

**Comment by jmbrunskill** [comment]
Completed

**Comment by AnushaUp** [comment]
Tested and Passed 👍✅
 Details [HERE](https://github.com/msupply-foundation/open-msupply/issues/4144#issue-2349756447)
