### ISSUE TITLE
Carry over from PR 3652, file sync update

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3666]
A few PRs are stacked on top of https://github.com/msupply-foundation/open-msupply/pull/3653.

Would be good to get that one merged asap to meet the PR merge deadline. 

I'll pull through any non critical comment from that PR here to be fixed in follow up PR.

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/open-msupply/pull/3653#discussion_r1576985601

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/open-msupply/pull/3653#discussion_r1577080872

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/open-msupply/pull/3653#discussion_r1577082349

**Comment by andreievg** [comment]
Should we change all form data uploads to use `file` vs `files` and renaming to file https://github.com/msupply-foundation/open-msupply/pull/3653#issuecomment-2073865758

**Comment by jmbrunskill** [comment]
> Should we change all form data uploads to use `file` vs `files` and renaming to file [#3653 (comment)](https://github.com/msupply-foundation/open-msupply/pull/3653#issuecomment-2073865758)

I think we probably should since we're expecting just 1 file.
