### ISSUE TITLE
Wrong expanding arrow for Dispensary and Cold chain nav

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3667]
## What went wrong? 😲
 

https://github.com/msupply-foundation/open-msupply/assets/55115239/00587586-186f-4725-8634-83c832a62494

## Expected behaviour 🤔

- Coldchain/dispensary sections should have `>` rather than `v` when collapsed
- I want the other sections to collapse when clicked multiple times lol

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Does bother me... but doesn't affect functionality

**Comment by marthakeezy** [comment]
Just tested on v2.0.0-rc4, and the issue has been fixed. Build test passed! :) ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/f15540ef-4a54-4f5c-820e-708c41ecca63)
