### ISSUE TITLE
Assets can fail to sync if asset catalogue item is deleted.

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3675]
## What went wrong? 😲
Assets created with a deleted asset catalogue item don't sync to central server correctly

## Expected behaviour 🤔

Asset catalogue items should be soft deleted to avoid issues with Sync

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Import a new asset catalogue item (On central server)
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/f865b943-d9d5-4586-ac64-42ad6883a1cc)

2. Sync your remote site
4. Create an asset on the remote site using the new catalogue item
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/b59e8f36-27f3-4dc7-bcf6-840c028dad37)
5. Before syncing to central, delete the catalogue item from central
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/a6c87aa0-5310-4cdf-b0eb-d0dd4d7f04b1)

6. Sync to central server
7.  Check that the asset show up in the central server

## Your environment 🌱

- Open mSupply Version: 2.0.0-RC

**Comment by Chris-Petty** [comment]
This is a good example of an issue that would benefit from an "Agreed Solution" section 😁.

I think the go to is that the catalog like much item or any other central configuration data needs to have soft delete to ensure not breaking FKs on unsynced remote sites?

**Comment by Chris-Petty** [comment]
Also @jmbrunskill don't be afraid to have a punt at assigning severity to give triaging a hint 😃 . High seem fair? I figure this is high as having data not sync is pretty bad! If not in pre-release I'd probs say hotfix.

**Comment by jmbrunskill** [comment]
> Also @jmbrunskill don't be afraid to have a punt at assigning severity to give triaging a hint 😃 . High seem fair? I figure this is high as having data not sync is pretty bad! If not in pre-release I'd probs say hotfix.

I think the chances of it happening and consequences are relatively low so wasn't sure it should be considered `High` but would be good to have it fixed before we have clients using it. As far as I know there no one about to jump on it for 2.0 so probably fix for 2.1 would be ok IMHO

**Comment by jmbrunskill** [comment]
Also kind of a quick fix, so will jump on it now for 2.0-RC
