### ISSUE TITLE
Add cli to windows build

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3677]
## Is your feature request related to a problem? Please describe 👀

I would like to run the `refresh-dates` cli command on the demo server, and would also like to have sync enabled after doing so.

## Describe the solution you'd like 🎁

* Add the cargo command to build the binaries for posgres and sqlite versions of the cli
* include the appropriate binary into the installer
* Update the refresh dates command to allow sync enabling

### Describe alternatives you've considered 💭
It might be possible to refresh the dates in 4D instead - but given the move away from the mSupply central server it would be preferable to refresh the omSupply end.

**Comment by roxy-dao** [comment]
Removing from tester board since change isn't obvious
