### ISSUE TITLE
Requisitions: v2.0.0 Release Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3688]
## Requisitions
- [x] When customer create internal order in their store requisition will appear in the supplying store
- [x] To check the requisition goto Distribution> Requisition
- [ ] You can view and export the requisition list to .csv file **- Can't export in tablet apk**
- [x] Clicking the individual item will show you the details of particular item where supplying quantity can be adjusted
- [x] Another way to supply quantity is to click the button `Supply requested`
- [x] To create the outbound shipment, click on the `create shipment` button 
- [x] It will create shipment with all the items for which supply quantity were entered and open that shipment in a new tab
- [x] Note that the lines are in blue; meaning they're just placeholder lines
- [x] Either you can select the lines and click `Allocate placeholder lines` from `Actions` or you can open the lines individually and put in the quantity manually
- [x] After creating such a shipment, you will see the shipment number, along with a link to view it, in the `Related documents` section of the additional details panel on the right of the screen.

**Comment by nisha-dangol** [comment]
Tested in v2.0.0-rc3 apk - PASS!
