### ISSUE TITLE
Returns: v2.0.0 Release Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3689]
###   View returns

- [x] Choose Distribution > Inbound Returns in the navigation panel.
- [x] View a list of past Inbound Returns 
- [x] Sort items by columns (Name, Status, Created, etc..)
- [x] Export Inbound Returns  to a .csv file
- [x] The list can display a fixed number of returns per page. On the bottom left corner, you can see how many are currently displayed on your screen.
- [x] If you have more returns than the current limit, you can navigate to the other pages by tapping on the page number or using the right of left arrows (bottom right corner).
- [x] You can also select a different number of rows to show per page using the option at the bottom right of the page.

###   Filter by Name or Status
- [x] You can filter the list of returns by customer name. Click on the filter, a new search field should appear. 
- [x] Type the name of customer in the `search by name` field (on the left, just above the headers). All the returns for this customer will appear in the list.
- [x] You can filter the list of returns by status. When you click on the filter it opens a drop down list with the 3 status (`New`, `Delivered` and `Verified`). 
- [x] Select 1 status. All the returns with the status should come up.

### Create Manually an Outbound Return
- [x] Navigate to Replenishment > Outbound returns
- [x] Click on New Return button
- [x] A new window with Suppliers name will appear. Choose a supplier from the list
- [x] You should be able to filter by name when typing a Supplier name
- [x] Once you tap or press Enter, or click on a customer, your Outbound Return is automatically created
If everything went well, you should see the name of your customer in the top left corner and the status should be NEW
- [x]  Reference field is editable. 
- [x] Add a new item by clicking on 'New Item'. A drop down list appears with items visible to this store
- [x] A new window comes up, where you can edit batch, expiry date. Both fields should be editable
- [x] If you don't input a quantity to be returned and press the button 'Next', an error message comes up on the screen.
- [x] If you insert a quantity to be returned, you can press the button 'Next' and the field 'Reason' and 'Comment' will show up. Both should be editable too. These fields are not mandatory.
- [x] After clicking 'Ok', a new line comes up on the invoice.
- [x] Select this line by clicking on the box at the right corner. Box should be clickable
- [x] After selecting a line, click on 'Actions' drop down box and 'Delete selected lines'. The selected line should disappear from the invoice. 
- [x] Add another item, with same code, but different batch. After inputting all the information (quantity to be returned, reason, etc..) click 'Ok'. Now test the toggle button called `Group by item`.
The items with same item code should be grouped on the invoice now.
- [x] On the right side you should be able to click on `More` icon
- [x] You can type a comment
- [x] You can change the colour of the Return
- [x] Edited by shows you the username of the user you're logged as
- [x] Actions: Copy to Clipboard: You can click the Copy to Clipboard button to copy the invoice details to the clipboard.
- [x] X Close button is clickable, on the top right corner of the information panel. 
- [x] Actions: Delete - You can click the Delete button to delete the return. You can only delete Inbound Returns while they are in NEW status.
- [x] If you do not delete, press 'Confirm Delivered'. Status change to `Delivered`
- [x] Press 'Confirm verified'. Status change to `Verified`. 
- [x] No more changes can be made to this transaction.

### Create Manually an Inbound Return
- [x] Navigate to Distribution > Inbound returns
- [x] Click on New Return button
- [x] A new window with Customers name will appear. Choose a customer from the list
- [x] You should be able to filter by name when typing a Customer name
- [x] Once you tap or press Enter, or click on a customer, your Inbound Return is automatically created
If everything went well, you should see the name of your customer in the top left corner and the status should be NEW
- [x] Customer Reference field is editable. Type a reference.
- [x] Add a new item by clicking on 'New Item'. A drop down list appears with items visible to this store
- [x] A new window comes up, where you can edit batch, expiry date. Both fields should be editable
- [x] If you don't input a quantity to be returned and press the button 'Next', an error message comes up on the screen.
- [x] If you insert a quantity to be returned, you can press the button 'Next' and the field 'Reason' and 'Comment' will show up. Both should be editable too. These fields are not mandatory.
- [x] After clicking 'Ok', a new line comes up on the invoice.
- [x] Select this line by clicking on the box at the right corner. Box should be clickable
- [x] After selecting a line, click on 'Actions' drop down box and 'Delete selected lines'. The selected line should disappear from the invoice. 
- [x] Add another item, with same code, but different batch. After inputting all the information (quantity to be returned, reason, etc..) click 'Ok'. Now test the toggle button called `Group by item`.
The items with same item code should be grouped on the invoice now.
- [x] On the right side you should be able to click on `More` icon
- [x] You can type a comment
- [x] You can change the colour of the Return
- [x] Edited by shows you the username of the user you're logged as
- [x] Actions: Copy to Clipboard: You can click the Copy to Clipboard button to copy the invoice details to the clipboard.
- [x] X Close button is clickable, on the top right corner of the information panel. 
- [x] Actions: Delete - You can click the Delete button to delete the return. You can only delete Inbound Returns while they are in NEW status.
- [x] If you do not delete, press 'Confirm Delivered'. Status change to `Delivered`
- [x] Press 'Confirm verified'. Status change to `Verified`. 
- [x] No more changes can be made to this transaction.

### Return from Customer Shipment

- [x] Choose Distribution > Outbound Shipment > Open the Outbound Shipment for which you would like to process the return of some or all of the stock
- [x] Make sure that status is at least SHIPPED
- [x] Select the line(s) you want to process the return of by checking the box(es) on the right of the list
- [x] Actions: select the action 'Process return of selected lines'
- [x] Insert the quantity that is being returned to your store and press 'Next step'
- [x] You should be able to select a Reason and insert a comment. These fields are not mandatory.
- [x]  After clicking 'Ok', the 'Inbound Return' is created and the item you selected is on the invoice
- [x] On the right side you should be able to click on 'More' icon
- [x] You can type a comment
- [x] You can change the colour of the Return
- [x] Edited by shows you the username of the user you're logged as
- [x] Actions: Copy to Clipboard: You can click the Copy to Clipboard button to copy the invoice details to the clipboard
- [x] X Close button is clickable, on the top right corner of the information panel. 
- [x] Actions: Delete - You can click the Delete button to delete the return. You can only delete Inbound Returns while they are in NEW status.
- [x] If you do not delete, press 'Confirm Delivered'. Status change to `Delivered`
- [x] Press 'Confirm verified'. Status change to `Verified`. 
- [x] No more changes can be made to this transaction.

### Return from Supplier Shipment

- [x] Choose Replenishment > Inbound Shipment > Open the Inbound Shipment for which you would like to process the return of some or all of the stock
- [x] Make sure that status is at least SHIPPED
- [x] Select the line(s) you want to process the return of by checking the box(es) on the right of the list
- [x] Actions: select the action 'Process return of selected lines'
- [x] Insert the quantity that is being returned to your store and press 'Next step'
- [x] You should be able to select a Reason and insert a comment. These fields are not mandatory.
- [x]  After clicking 'Ok', the 'Inbound Return' is created and the item you selected is on the invoice
- [x] On the right side you should be able to click on 'More' icon
- [x] You can type a comment
- [x] You can change the colour of the Return
- [x] Edited by shows you the username of the user you're logged as
- [x] Actions: Copy to Clipboard: You can click the Copy to Clipboard button to copy the invoice details to the clipboard
- [x] X Close button is clickable, on the top right corner of the information panel. 
- [x] Actions: Delete - You can click the Delete button to delete the return. You can only delete Inbound Returns while they are in NEW status.
- [x] If you do not delete, press 'Confirm Delivered'. Status change to `Delivered`.
- [x] Press 'Confirm verified'. Status change to `Verified`. 
- [x] No more changes can be made to this transaction.
.

**Comment by roxy-dao** [comment]
Testing finished
