### ISSUE TITLE
Large number of Push V6 records on initialisation

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3692]
## What went wrong? 😲
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/d79495ce-02c1-47f8-b8f4-fd0c41117ccf)
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Initialise a new database
2. Check how many records show under PushV6 (should be 0??)

## Your environment 🌱

- Open mSupply Version:2.0-RC

**Comment by jmbrunskill** [comment]
Suggesting High Severity as it could generate a lot of traffic if we're pushing all the records we receive back to OMS Central?

**Comment by lache-melvin** [comment]
Closed by #3720

**Comment by regotaina** [comment]
Testing while connecting a remote site for the 1st time. It looks like it's been pushed forward:
https://github.com/msupply-foundation/open-msupply/issues/3692

Is this the fix proposed? @andreievg :)

**Comment by jmbrunskill** [comment]
@regotaina this looks fine to me, the records are `pull` records coming from central server, not pushing records to central server that it just received (that was the bug).
We expect the pull records to be relatively high on initialisation.
