### ISSUE TITLE
yarn start should default to local

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3695]
## The suggestion

Current `yarn start` tries to connect your frontend to the demo server.
Suggest that we add `yarn start-remote` for this behaviour as most apps use `yarn start` point to local

### Why should we invest time in this?

Saves time and confusion for developers who connect to the wrong server.

### Are there any risks associated with this change?

Not really only affected developers

### How much effort is required?

<1 hr

**Comment by mark-prins** [comment]
I only use `yarn start-local` and hadn't even noticed 🙄 
This is the host package, and the intention:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/a7ac5939-34e6-4591-8df2-6ead5b47200f)

and then the client package does this:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/bda4520f-6189-44aa-9f80-32f3690a8472)


Just need to change to `yarn start`

**Comment by roxy-dao** [comment]
Removing from tester board since change isn't obvious
