### ISSUE TITLE
GAPS: Collecting facility data on immunization coverage (Penta-3 and Zero Dose)

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3700]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.  

The pain points are: 
-  There is no easy way for EPI managers to collect data from the facilities about their immunization coverage rates

Problems to solve: 
- A way for facilities to report on their coverage rates for various immunization metrics.

## Acceptance criteria
* [ ] Can select a value for penta-3 (high, medium, low)
* [ ] Can select a value for zero dose (high, medium, low)

## Describe the solution you'd like 🎁
For this, I'm thinking that we implement using custom fields, so there's no additional work in this issue. Just testing when complete.

**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f9e29c4d-7fff-20a8-b8e7-48a4be25368c"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.5.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | all SP facilities to provide me with information about their Penta-3 coverage (High, Medium, Low)
So that… | I can investigate whether there is any correlation with CCE infrastructure

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a5223960-7fff-85a2-69aa-a73b2d2f236e"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.6.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | all LD facilities to provide me with information about their zero dose coverage (High, Medium, Low)
So that… | I can investigate whether there is any correlation with CCE infrastructure

</div></b>

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by jmbrunskill** [comment]
@adamdewey  can you clarify what's different about Penta 3 and Zero Dose?

**Comment by adamdewey** [comment]
> @adamdewey can you clarify what's different about Penta 3 and Zero Dose?

I'm not really sure except that in one discussion with UNICEF it seemed that they expected data for Penta 3 to come from the regional (LD) levels and data for zero dose to possibly come from the national level (or the SP level, I forget which)

In any case there are likely some differences between them in how the data is collected - need to talk to UNICEF to understand in a bit more detail.

**Comment by jmbrunskill** [comment]
@mark-prins are you thinking this is just a couple of new store properties?

**Comment by mark-prins** [comment]
yup. should be fairly straightforward in that case

**Comment by adamdewey** [comment]
Yes agree, this should be as simple as considering it part of the 'survey' that facilities return to central
