### ISSUE TITLE
CCEI / IGA: GET API

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3702]
## Background Information 

Epic #2896 introduced the CCEI management module. 

UNICEF Global have requested some additional functionality in order to address countries' pain points. 

The pain points are: 
-  There's no easy way to extract data from the CCEI module for use with other systems. 

Problems to solve: 
- A way to easily extract all relevant CCEI data

## Describe the solution you'd like 🎁
**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**
- [ ] E.1.1
  - [ ] Provide an API GET request to access CCEI data

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by mark-prins** [comment]
There is already a graphQL API available to extract data from CCEI register.
