### ISSUE TITLE
Picked OS: Can no longer edit stock in invoice line if all has been issued

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3704]
## What went wrong? 😲
Stock lines disappearing from invoice line after allocating all the stock since stock leaves inventory at `Picked`, but we are still allowing the user to edit the invoice, so the user should still be able to edit the stock. 

Q. Why does OMS `picked` functionality have to match OG `cn` functionality? Why can stock not still be in inventory but just unavailable?

![Screenshot 2024-04-30 at 10 08 37](https://github.com/msupply-foundation/open-msupply/assets/61820074/3feba684-0b10-4a13-934f-b08572c31cfc)

## Expected behaviour 🤔
The user should still be able to edit the stock line!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an `Outbound Shipment` 
2. Add invoice line
3. Issue all stock from stock line
4. Change status to `Picked`
5. Go back to invoice line
6. See that stock line has disappeared

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
> Q. Why does OMS picked functionality have to match OG cn functionality? 

Sorry the full reasoning is a bit lost to me now, but at some point there was consensus on it, perhaps we need some documentation about it but we would need all stakeholder to participate, including mSupply pps. I feel like this area is being discussed all the time and perhaps needs a diagram and explanation ?

> Why can stock not still be in inventory but just unavailable?

Stock line still exists. We should display that stock line in the list. I think it's deliberately being filtered out.

**Comment by andreievg** [comment]
Btw do we have front end test for this ?

**Comment by roxy-dao** [comment]
I think should definitely be documented since it is being discussed a lot. And no, we don't have frontend tests for this.

**Comment by mark-prins** [comment]
no - the f/e tests are usually around logic and component functionality. this would be a b/e test or f/e-b/e integration test, if we had such a thing.

**Comment by andreievg** [comment]
> I think should definitely be documented since it is being discussed a lot.

https://github.com/msupply-foundation/msupply_docs/issues/32

**Comment by regotaina** [comment]
Tested on RC4
PASSED THE TEST 💯 

# 🧪 How has/should this change been tested? 

- [x] Create an `Outbound Shipment` 
- [x]  Add invoice line
- [x] Issue all stock from stock line
- [x] Change status to `Picked`
- [x] Go back to invoice line
- [x] See that stock line has disappeared
