### ISSUE TITLE
Decimal Pack Sizes

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3705]
## Is your feature request related to a problem? Please describe 👀

As decided in KDD #3619, we require supporting decimal pack sizes in all contexts to allow compatibility with Legacy mSupply migrated data. Also it is arguably a feature.

## Describe the solution you'd like 🎁

- `float` migrated in sql for all pack size fields
- Views may need redefining
- `f64` propagated through backend and gql
- Possible tweaks to frontend code.

## Sub Issues

- [x] stock_line
- [x] invoice_line (may need to do at same time as stock_line)
- [x] #3939
- [x] stock_take_line

### Moneyworks Jobcode 🧰

**OMS:MIGRT**

**Comment by Chris-Petty** [comment]
@roxy-dao @clemens-msupply what's left to do on this?

**Comment by roxy-dao** [comment]
Nothing. Closing as complete.

**Comment by nisha-dangol** [comment]
will be tested as #4141
