### ISSUE TITLE
V2.0.0 Release Testing: Open mSupply Central Server

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3722]
V2.0.0 Release Testing: Open mSupply Central Server 

## Basic Requirements

1. mSupply Server Minimum v7.14
2. The port that is that will be using for open mSupply server should be opened (i.e., configure Inbound rules for the ports you use)
3. Open mSupply Server and mSupply server should be on the same machine and running simultaneously.
4. Open mSupply central-server will need to be setup using server-exe, oms-standalone not feasible for oms-central site

## How to Setup 🔨

Steps to setup

1. Setups for mSupply CLoud Server

- [ ]  Open a msupply server and load the datafile in it.
- [ ]  Register and enable synchronisations of the datafile
- [ ] Create a new store: This stores will be store active in open mSupply Central Server
- [ ] Enable all the basic setup like: visibility of items, names, stores and login rights of the store
- [ ] Create a new site with the stores that you have created
- [ ] Now configure the site by putting the correct creditentails

![Screenshot 2024-05-01 at 12 09 09](https://github.com/msupply-foundation/open-msupply/assets/117138852/38740d99-2749-4d4a-9cb6-2bea7423a1a9)

2. Setup for open mSupply Central Server

- [ ] Download the latest version of open-msupply from: https://github.com/msupply-foundation/open-msupply/releases
- [ ] If you are setting the datafile for the first time, configure the server as follows

![Screenshot 2024-04-30 at 16 36 17](https://github.com/msupply-foundation/open-msupply/assets/117138852/92346db9-d99a-414d-9d8a-2a8293c4e97f)

- [ ] Make sure you have cert files on the location `C:\Program Files\omSupply Server-v2\app_data\certs`

### **Note: This is optional should be done only if you are trying to setup in existing datafile**

- [ ]  Go to `C:\Program Files\omSupply Server-v2\configuration` folder and open local.yml file and configure as follows

![Screenshot 2024-04-30 at 16 44 01](https://github.com/msupply-foundation/open-msupply/assets/117138852/ff5ac077-5771-4355-893a-8c25010809a1)

- [ ] Run the service and the datafile gets loaded and UI gets opens up
- [ ] mSupply and open mSupply must be synchronised

- [ ] Check the login you should have the window like this
![Screenshot 2024-04-30 at 17 22 07](https://github.com/msupply-foundation/open-msupply/assets/117138852/e17eb5d9-6d1d-4c2a-920e-0f0dd84fd327)

3.  For remote site: OMS remote site

- [ ] Take any installer form our release page: https://github.com/msupply-foundation/open-msupply/releases
- [ ] Download any (Server+desktop), Standalone or .apk version
- [ ] You will see the window, enter the details

Server URL: mSupply server URL
Site name: mSupply site name
Site password: mSupply site password

- [ ] Now click on Connect, Now you will see another window to enter the username and password
- [ ] After entering the username and password, you should be able to login to the stores
- [ ] And sync window should be seen like this:

<img width="554" alt="Screenshot 2024-04-30 at 17 23 35" src="https://github.com/msupply-foundation/open-msupply/assets/117138852/250d139b-2b67-41a6-a9bc-57978445962e">

<img width="554" alt="Screenshot 2024-04-30 at 17 23 35" src="https://github.com/msupply-foundation/open-msupply/assets/117138852/727c0457-c8bf-4a4c-91fa-2f295040d475">

## Your environment 🌱
<!-- e.g. 1.2.3 —>
- Open mSupply Version:
- Legacy mSupply Central Server Version:
<!-- e.g. android, browser (extra points if you tell us which one), desktop (windows), desktop (macOS), server (windows) —>
- Platform:
<!-- PostgreSQL or SQLite3 —>
- Database type:

**Comment by santoshkhanal12** [comment]
@roxy-dao @Chris-Petty 

I tried to setup omSupply Standalone as Open mSupply Server. I see the following errors:

1. The alert message pops up when you set local.yml file and start the service

![Screenshot 2024-05-01 at 16 16 29](https://github.com/msupply-foundation/open-msupply/assets/117138852/f9fddb61-de68-484f-bf09-bc86a89950a6)

2. After you click on OK, the service gets hanged. Neither you can stop or restart the service

Production steps

1. Open mSupply server, and add open mSupply server site and store
2. Install open mSupply Stand alone version v2-rc-02
3.

**Comment by Chris-Petty** [comment]
I'm confused, @andreievg are we normally meant to edit server yaml like this? Are we meant to use mSupply Standalone as central server?

**Comment by nisha-dangol** [comment]
@Chris-Petty FYI, those steps @santoshkhanal12 mentioned works fine when using the server exe. 
The questions are only for standalone setup.

And, yes please correct us if any of the steps above wrong or missing

**Comment by santoshkhanal12** [comment]
@andreievg @Chris-Petty 

If we can setup the open mSupply standalone as central server. We should just add the this window during installing omsupply standalone version. So we just not need to edit the `local.yaml` file.

<img width="641" alt="Screenshot 2024-05-02 at 10 29 26" src="https://github.com/msupply-foundation/open-msupply/assets/117138852/4b854db1-2bb6-4519-940a-559b3a5ea183">

**Comment by andreievg** [comment]
@Chris-Petty 

> I'm confused, @andreievg are we normally meant to edit server yaml like this? Are we meant to use mSupply Standalone as central server?

not really, most configurations should be in the installer, but can edit yaml file if needed.

@santoshkhanal12 

You can browse windows error event log for errors to get extra info about why the service is hanging.

Also if you specify sync configurations in the yaml file, they must be correct, otherwise server will not respond. I prefer not to specify sync settings in yaml file, and input them via client UI

**Comment by santoshkhanal12** [comment]
@andreievg But we cannot input the sync setting via UI in Standalone version. I think we should add sync setting UI in stand alone version.

**Comment by andreievg** [comment]
@santoshkhanal12 

> @andreievg But we cannot input the sync setting via UI in Standalone version. I think we should add sync setting UI in stand alone version as mentioned in comment: https://github.com/msupply-foundation/open-msupply/issues/3722#issuecomment-2089577634

As part of standalone version installation, sync credentials are entered, but only after installation, when that app first starts

**Comment by nisha-dangol** [comment]
> @santoshkhanal12
> 
> > @andreievg But we cannot input the sync setting via UI in Standalone version. I think we should add sync setting UI in stand alone version as mentioned in comment: [#3722 (comment)](https://github.com/msupply-foundation/open-msupply/issues/3722#issuecomment-2089577634)
> 
> As part of standalone version installation, sync credentials are entered, but only after installation, when that app first starts

I think @santoshkhanal12 meant that at the time of installation of standalone exe, we're not allowed to choose the  database-name (which has to be `central_test` for v2.0.0), database type (sqlite, postgres)and  port-number, etc which is why he's resorting to editing yaml-files manually with the standalone
![Screenshot 2024-04-30 at 16 36 17](https://github.com/msupply-foundation/open-msupply/assets/117138852/92346db9-d99a-414d-9d8a-2a8293c4e97f)

**Comment by Chris-Petty** [comment]
Why must the datafile be named "central_test". Otherwise I understand now thanks, didn't realise standalone didn't show the configuration dialog at all.

If standalone is broken for OMS central server but not the server installer with the full dialog, for now please only test with the Open mSupply Server Installer rather than standalone?

**Comment by nisha-dangol** [comment]
> Why must the datafile be named "central_test". Otherwise I understand now thanks, didn't realise standalone didn't show the configuration dialog at all.
> 
> If standalone is broken for OMS central server but not the server installer with the full dialog, for now please only test with the Open mSupply Server Installer rather than standalone?
>
Cool; we'll note that oms-central strictly needs server exe (if you don't wanna edit yaml files)

**Comment by santoshkhanal12** [comment]
As long as the Open mSupply Server need to be run on server exe, the Open mSupply Central Server works fine
