### ISSUE TITLE
Last sync attempt time follows Central Server timezone, not local computer time

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3724]
## What went wrong? 😲

On my own machine, logged on browser, after syncing, the 'Last sync attempt' time shows the Central Server timezone, not the local computer timezone.
It may create confusion among users.

![Screenshot 2024-05-01 at 12 40 03 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/6ab90635-695d-4d16-ae3a-1f35bc35b007)

Time on Central Server:

![Screenshot 2024-05-01 at 12 44 20 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/660b64c2-387b-41ea-9259-9d3f42fabbc3)

Time on my local Computer: 

<img width="185" alt="Screenshot 2024-05-01 at 12 44 40 PM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/6466cac8-561c-49d0-9bd9-a27abd659e4e">

## Expected behaviour 🤔

Time shown on the 'Lat sync attempt' matches the local time on the computer.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to the machine where your Central server is hosted and change the set time to a different timezone than your current one (for ex. +3 hours)
2. Go back to your local computer and login to browser
3. Login and sync

## Your environment 🌱

- Open mSupply Version: V2.0 RC2
- Legacy mSupply Central Server Version: V7.14

- Platform: browser

**Comment by roxy-dao** [comment]
The sync times are in local time for me. Curious if anyone else can reproduce?

**Comment by regotaina** [comment]
> The sync times are in local time for me. Curious if anyone else can reproduce?

this happened in RC2, Chris was with me at the time! I will test now in RC3

**Comment by Chris-Petty** [comment]
Can confirm definitely saw and requested this issue be opened 😁.

Interestingly https://demo-open.msupply.org/sync appears to be fine. I just went and made sure it's server timezone was +2, and sync times remained fine. @regotaina perhaps you had manually changed the actual time on the cloud server? That'd have made the differences you were seeing (i.e. changing the time and changing the timezone are different things)

**Comment by roxy-dao** [comment]
I've also tried testing demo on windows by changing region and timezone and seems to be working fine 😢

**Comment by regotaina** [comment]
For some reason it seems fixed on RC3 ! I cannot reproduce it anymore. 

1-Changed the server timezone settings to Netherlands
2- Synced. 
3- Logged on web browser on my own mac pc, synced. the time seems to follow my computer settings now.
