### ISSUE TITLE
Asset Management Module for CCE Inventory: Phase 1 -> Mobile/Desktop : v2.0.0 Release Testing 

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3725]
# Configuration
- [x] User should have permission to view and edit assets
- [x] Hide Asset navigation if user doesn't have view asset permission

# Asset Catalogue
- [x] From the menu when you open Catalogue -> Assets you can see pre-populated list of base asset items from the [WHO PQS Catalogue](https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/) (sections E003 & E004)
![Screenshot 2024-05-01 at 10 41 51 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/8194de53-7881-4a26-8c27-fdb7093acb07)
- [x] From the assets menu you should be able to see all of the assets currently in your store.
- [x] The asset list is divided into 6 columns
   - [x] Sub catalogue -> The catalogue this asset belongs to
   - [x] Code -> The code of the catalogue item which this asset belongs to
   - [x] Type -> The type of asset
   - [x] Manufacturer -> The manufacturer of your asset
   - [x] Model -> The model number of the asset
   - [x] Class -> The class of the asset. ie: Cold chain equipment
   - [x] Category -> The subcategory of the asset e.g. section E003 in the PQS catalogue which is Refrigerators and freezers
   - [x] The field and values should be populated properly and no overlapped fields
<img width="1390" alt="Screenshot 2024-05-01 at 11 00 47 am" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/c2e22a42-c6e3-4c92-9cad-8c9ce790a361">

- [x] The list should display a fixed number of assets per page which you can see bottom left corner.

<img width="191" alt="Screenshot 2024-05-01 at 11 04 57 am" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/9a9bea0d-9b68-4d48-8f4c-d1282b4a9f11">

- [x] If you have more assets than the current limit, you can navigate to the other pages by tapping on the page number or using the right of left arrows (bottom right corner).
- [x] You can also select a different number of rows to show per page using the option at the bottom right of the page.
- [x] No problem in navigating to other page and selecting number of page.

## Filter Asset Catalogue
- [x] To add a filter to the page, choose the required filter from the drop down.
- [x] Multiple filters can be combined.
- [x] The list should be appeared as filtered.
- [x] The filters should work individually

## Delete Asset Catalogue Items
- [x] Assets can be simply deleted using the toolbar action 
- [x] The assets should be removed from the list after deleting 
- [x] Deleting assets possible only in Central oms site
- [x] It should sync to remote sites

### Import
- [x] Assets Catalogue Items can be imported from a comma-separated-file (csv) file using the `Import` button
- [x] It should be visible only in the cloud central
- [ ] While importing it should always give a valid reason clearly if there's problem in importing
![Screenshot 2024-05-01 at 11 33 41 am](https://github.com/msupply-foundation/open-msupply/assets/115983430/7cf6a759-eefe-424a-8fc3-a867e0c62f49)
### Export
- [x] A list of Asset Catalogue Items can be exported as a (csv) file using the `Export` button just beside import button

### Status Reasons
- [x] When users add a new status log against a particular asset, more detail can be provided with a reason associated with the new status.
- [x] If an asset has been labeled `NON_FUNCTIONING` could be assigned a reason of `power supply broken` another status
- [x] Reason should be managed on a new page accessible from the `Manage Log Reasons` button beside the `Export` button
### Managing log reasons
- [x] On this page you should be able to create log reason with `Create log reason` button
![Screenshot 2024-05-01 at 2 32 10 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/3666b28b-d72b-4fcc-9ba3-3a19a0ccfa60)
- [x] If you click on `Create log reason` button new model will open
 <img width="496" alt="Screenshot 2024-05-01 at 2 36 14 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/96bd587c-da31-440c-9a25-03641806d52b">

- [x] You can select and delete existing reasons with the `Actions` dropdown

<img width="395" alt="Screenshot 2024-05-01 at 2 38 15 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/c15b1bb4-93b5-4189-9046-b0c0857e761b">

- [x] Filters existing reasons by status using the filter dropdown
- [x] The list should be filtered properly

<img width="548" alt="Screenshot 2024-05-01 at 2 39 27 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/6ec1b273-40f4-4ca9-9ca1-2dcb8f0c83e9">

# Cold Chain Equipment (Assets)
- [x] From the equipment menu, all assets available in a store can be viewed
 **_Issue found here_** https://github.com/msupply-foundation/open-msupply/issues/3739
- [x] From Central Server assets from All Stores are visible
- [x] The equipment list is divided into 9 columns:
   - [x] Store -> Store name in which the issue created
   - [x] Asset Number -> The asset number
   - [x] Type -> The type of asset
   - [x] Manufacturer -> The manufacturer of your asset
   - [x] Model -> The model number of the asset
   - [x] Functional Status -> The functional status of the asset ie: FUNCTIONING
   - [x] Serial Number -> The serial number of the asset
   - [x] Non-catalogue -> Designates if the asset was not created from a catalogue item (see [Catalogue > Assets](https://docs-staging.msupply.foundation/docs/catalogue/assets/))
   - [x] Notes -> Notes entered about the asset
![Screenshot 2024-04-30 at 3 39 21 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/4eb10763-119d-4c73-8641-49e571daf6ec)

## Paginate Equipment
- [x] The list display a fixed number of assets per page. 
- [x] On the bottom left corner, you can see how many assets are currently displayed on your screen.
- [x] If you have more assets than the current limit, you can navigate to the other pages by tapping on the page number or using the right of left arrows (bottom right corner).
- [x] You can also select a different number of rows to show per page using the option.
## Filter Equipment 
- [x] To add a filter to the page, you should be able to choose the required filter from the drop down. 
![Screenshot 2024-04-30 at 4 02 36 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/edfb40c4-5fdb-4a94-a852-bbe1383ced64)
- [x] Multiple filters can be combined
 **_Some new filters will be added probably_** https://github.com/msupply-foundation/open-msupply/issues/3767
- [ ] Should be able to search by **Asset number** https://github.com/msupply-foundation/open-msupply/issues/3750
- [x] The list should show the results as per the filtered
- [ ] Individual filter should also work properly
 **_Issue found on filter_** [Code filter doesn't work properly](https://github.com/msupply-foundation/open-msupply/issues/3743)
- [x] Installation date filter should work properly 
## Delete Equipment 
- [x] Assets should be able to select and delete using the toolbar action
- [x] The asset should disappear from the list once deleted
![Screenshot 2024-04-30 at 4 20 04 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/942541df-07e6-4aeb-b5ee-0eae6ab04477)

### Import
- [x] Cold chain assets can be imported from a comma-separated-value (csv) file using the `Import` button
![Screenshot 2024-04-30 at 4 25 14 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/160026de-cd24-4f5c-beef-d5fc8cc10bfd)
- [x] This should open an import modal
![Screenshot 2024-04-30 at 4 28 19 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/0ce224c3-422f-420e-b508-4bafbf240f98)
- [x] An example template (in csv format) is available in the import window
- [x] The importing file needs to be in csv format
- [x] After importing assets from a store, they should be assigned to that store
- [ ] When importing assets on the central server, an additional field of store will be required which will assign assets to their respective stores.
- [ ] Information will need to be entered in the format provided by the csv template in order for Open mSupply to be able to process and upload this data.
- [ ] A csv file can be uploaded once it has been created in the example format.
**_Issue found here_**
[Error message not showing properly while importing files](https://github.com/msupply-foundation/open-msupply/issues/3742)
### Export
- [x] A list of assets can be exported as a csv using the `Export` button.
<img width="149" alt="Screenshot 2024-04-30 at 4 52 05 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/4a67a3bc-31e8-433e-a0d8-2495d6e0589d">

## QR code scanning
- [x] This feature should be enable only if open mSupply is running on the tablet or desktop version
- [x] You will get an extra button on the menu bar which allows scanning QR codes. This is the Scan button:
<img width="653" alt="Screenshot 2024-04-30 at 4 57 21 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/d1feb2ae-16fb-43f1-978c-5d91b7900f89">

- [x] You may see this notification when you click the button:
<img width="313" alt="Screenshot 2024-04-30 at 4 56 00 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/777b0c70-b5bf-40d6-8544-783eefdfe259">

- [x] If you do,  Head over to the [Barcode Scanners](https://docs-staging.msupply.foundation/docs/administration/devices/#barcode-scanners) section of the Admin documentation and configure a scanner before continuing.
- [x] Once you have a scanner connected - you can click the Scan button and scan a QR code.
- [ ]  If a match is found when you scan, you'll be taken to the detail page for that cold chain equipment item. 
- [ ] If not, you'll see a notification telling that no match was found. 

## Create new asset
- [x] Cold chain assets can be created manually with the `New Asset` button.
- [x] Clicking this button will open the `Create Asset` modal which is shown like this:
![Screenshot 2024-04-30 at 5 05 28 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/594ff236-5cf2-4005-a8a5-4fd8c7305297)
   - [x] store field is extra for the central oms server
   - [x] the Asset Category
   - [x] the asset catalogue item the Asset will be based on: this will link information from the catalogue item ( such as manufacturer & model ) to this newly created Asset
   - [x] the Asset number
   - [x] notes about the Asset
- [ ] If the asset you are creating is not part of either the WHO PQS or General catalogue, you can use the toggle to create an asset which is not based on a catalogue item.
- [x] The asset created should be synced to the central oms server

## Managing cold chain assets
- [x] Clicking on a row in the list will show the details of that asset.
<img width="652" alt="Screenshot 2024-04-30 at 5 16 14 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/f3cb05ac-eb53-4092-9681-3e4af77dbde7">

- [x] There should be 4 tabs available to manage the asset
<img width="647" alt="Screenshot 2024-04-30 at 5 16 56 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/971bb570-4a12-485f-93ac-a0fe8ee435ce">

## Summary Tab
- [x] From the Summary tab, you can:
    - [x] edit the serial number
    - [x] assign an installation date
    - [x] assign a replacement date
    - [x] assign locations to the the asset
    **_Issue made here_** https://github.com/msupply-foundation/open-msupply/issues/3762
    - [x] Note: Multiple locations can be assigned to one asset
    - [x] Assigned location should be shown in the central server
    - [x] store can be edited in the central server only
        **_Issue found here_** https://github.com/msupply-foundation/open-msupply/issues/3674
## Status Logs
- [x] You can also view the functional status and edit the notes of the status log.
<img width="1390" alt="Screenshot 2024-04-30 at 5 21 14 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/647e657b-0b2d-47fd-80d2-fb2b74e051bf">

- [x] The `Status Logs` tab shows all of the status logs of the status logs of the asset
<img width="1395" alt="Screenshot 2024-04-30 at 5 26 08 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/d86da666-c258-4f68-8f0f-c2b558b0db07">

- [x] The `Documents` tab shows documents which have been uploaded for the asset catalogue item the asset belongs to, and the documents uploaded for this asset.
- [x] Additional documents can be uploaded for this asset.
<img width="1394" alt="Screenshot 2024-04-30 at 5 30 37 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/ae0ce4e5-a8b5-4252-b646-dc46291d3860">

- [x] Documents which are uploaded here will synchronise to the central server, though not as a part of the usual sync process. Files will only be sent when there is no other information to synchronise, which means that adding documents won't cause delays in shipments or stock showing up.
- [x] Any documents uploaded from a remote site should be available to view on the central server (after syncing)
- [x] Any document uploaded on Central Server associated with an asset on the remote site, should be available to download on the remote site.

## Log
- [x] The `Log` tab shows the activity log of this asset.
- [x] This records all user actions which have been taken for this asset using the Open mSupply system.

### Updated
- [x] Clicking on the Update Status button allows the creation of a new status log.
<img width="199" alt="Screenshot 2024-04-30 at 5 35 06 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/0782fdef-7bc5-4f92-89ac-5d00d9bb71d2">

- [x] This will open a new status log modal
<img width="1301" alt="Screenshot 2024-04-30 at 5 36 14 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/b96893fb-b742-4ec3-a280-9e2e03c3729c">

- [x] Here you can enter:
    - [x] A new functional status
    - [x] A reason for the new functional status
    - [x] Any observations or notes
- [x] Additional documents including photos can also be uploaded for this status log
<img width="783" alt="Screenshot 2024-04-30 at 5 38 06 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/30215a9f-1be1-421e-a8de-50439dcb2b18">

- [x] These documents can be viewed in the Status Logs tab
<img width="1397" alt="Screenshot 2024-04-30 at 5 39 43 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/0ede55ec-a071-4e06-a8f3-d12401d84350">

## Printing a QR code
- [x] To help identify assets, you can print a QR code label for your asset. 
- [ ] This can then be scanned (see above) to easily identify an asset in your system.
- [x] Simply click the Print QR code button and a QR code will be printed, if you have a label printer configured.
- [x] To configure a label printer, refer to the [Label Printing](https://docs-staging.msupply.foundation/docs/administration/devices/#label-printing) section of the administration pages.
- [x] The label will show the code and serial number, for example:
<img width="598" alt="Screenshot 2024-04-30 at 5 41 47 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/2504f838-74e5-4b38-9dd2-65eb3a5690e9">

**_Issue in Logout Module_** https://github.com/msupply-foundation/open-msupply/issues/3740

**Comment by adamdewey** [comment]
@nisha-dangol , @marthakeezy , @AnushaUp - I've had a quick play with the CCEI asset module and have put the things I immediately noticed in here: https://docs.google.com/document/d/1SiR9u6kFqorQPopXXxhH1wmXdTIbn1H4P1repO_8__Y/edit#heading=h.ybb99y1pg59k

If you help to convert them into GitHub issues that would be awesome :)

**Comment by AnushaUp** [comment]
> @nisha-dangol , @marthakeezy , @AnushaUp - I've had a quick play with the CCEI asset module and have put the things I immediately noticed in here: https://docs.google.com/document/d/1SiR9u6kFqorQPopXXxhH1wmXdTIbn1H4P1repO_8__Y/edit#heading=h.ybb99y1pg59k
> 
 Hi, @adamdewey I've made issues and updated in the docs.

**Comment by adamdewey** [comment]
Thanks @AnushaUp that's awesome

**Comment by AnushaUp** [comment]
> ## QR code scanning
> * [x]  This feature should be enable only if open mSupply is running on the tablet or desktop version
> * [x]  You will get an extra button on the menu bar which allows scanning QR codes. This is the Scan button:

@mark-prins @jmbrunskill what is the expected behaviour here?
In the desktop app it shows like this when scanning from the scanner even when the QR is printed from the same device
![Screenshot 2024-05-09 at 6 00 46 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/f9a8183b-235f-462e-a265-bbe51e42875f)

And from the mobile device(RC-4) it seems like its not working

https://github.com/msupply-foundation/open-msupply/assets/115983430/3243220e-cd52-4640-8246-eee9a913aea7

**Comment by nisha-dangol** [comment]
Additional notes from v2.0.0-rc5 tests:
1. I notice that status of equipments are not syncing from both remote to oms-central and vice-versa : https://github.com/msupply-foundation/open-msupply/issues/3739#issuecomment-2107132986

**Comment by nisha-dangol** [comment]
> Additional notes/issues from v2.0.0-rc5 tests:
> 
> 1. I notice that status of equipments are not syncing from both remote to oms-central and vice-versa : [Functional status not syncing from the remote site to central #3739 (comment)](https://github.com/msupply-foundation/open-msupply/issues/3739#issuecomment-2107132986)
> 2. And, when I clear data of remote-site and reinitialise again, I notice that all the statuses and status-logs from remote-site are also gone, though Logs are at least preserved
> 3. QUESTION: Should status-log sync from central to remote & vice-versa? and same question for Assets>Logs
>    I notice that status-log for remote and central are different, as there can be different entries from remote & central? the status is not even syncing for me, what should I expect of status-log to sync?
> 4. How weird does this search look to you? https://screenrec.com/share/2UbMZaidse
> 5. Could be ENHANCEMENT: Would be good to record locations of equipments?
>    Create equipments from remote-site and assign them to locations. From central-oms, those locations can appear under the locations? but uneditable of course?

1 -> ongoing investigation/discussion in #3739 
4 -> issue submitted: #3885 
5 -> issue submitted: #3886

**Comment by AnushaUp** [comment]
> [ ] If a match is found when you scan, you'll be taken to the detail page for that cold chain equipment item.

@mark-prins scanning doesn't work 

https://github.com/msupply-foundation/open-msupply/assets/115983430/667ffbde-8038-432e-a533-abc25396935f

**Comment by mark-prins** [comment]
Created #3892 to investigate the search, targeting v2.1 though as we don't have time to look right now
