### ISSUE TITLE
Returns: if there is no 'Reason' configured on mSupply, you still can type to search 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3729]
## What went wrong? 😲

- Enhancement - 

After talking to @lache-melvin about returns, we noticed the 'Reason' field is editable, which can be confusing for users as they may think a new reason can be input on that window. 
However the field is editable to enable the search only. 

We think it can be confusing for users. 

![telegram-cloud-photo-size-1-5015052128800058620-y](https://github.com/msupply-foundation/open-msupply/assets/132425096/018e3266-2ffd-48cb-a8da-68db5e1739aa)

## Proposed solution 🤔

I agree with Lache's idea: it would be a nicer user experience if the reason dropdown was disabled if there were no reasons setup in mSupply.

## Your environment 🌱

- Open mSupply Version: V2.0 RC2
- Legacy mSupply Central Server Version: V7.14.0

- Platform: Desktop app (windows)

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC6 with no reasons for return configured, and the dropdown is disabled. Build test passed ✅
