### ISSUE TITLE
Returns: 'Add a batch' button is not hidden when inputting a reason

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3730]
## What went wrong? 😲

After selecting an item to return and inputting a quantity, the system took me to select a reason/type a comment.
The 'Add a batch' button kept showing up. If we click on it, nothing seems to happen.

However if we click on 'back' button, we can see new rows were added. 
According to @roxy-dao this button should be hidden on the 'Reason' stage.

https://github.com/msupply-foundation/open-msupply/assets/132425096/247b9765-3534-4040-8045-8aa41ac9c55b

## Expected behaviour 🤔

The 'Add batch '  button should be hidden on the 'Reason' stage.

## How to Reproduce 🔨

Follow steps from video. 
Inbound Returns > New > 'Add Item' > input batch/expiry date/quantity > Click next > click on 'Add batch' button > nothing happens.

## Your environment 🌱

- Open mSupply Version: V2.0 RC2
- Legacy mSupply Central Server Version: V7.14.0

- Platform: Desktop App

**Comment by roxy-dao** [comment]
More info:
I think it should be hidden because there's no way to input how much stock you want to return in the reasons step, so makes sense to have it hidden here.
