### ISSUE TITLE
SI's are missing when their CI's were initially created in desktop, then migrated to oms and finalised later

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3734]
## What went wrong? 😲
 
SI's for receving-store are missing when their CI's from sending-store were initially created in desktop, then migrated to oms and finalised later
Additional context here: [#3699(comment)-Issue3](https://github.com/msupply-foundation/open-msupply/issues/3699#issuecomment-2088186569)

## Expected behaviour 🤔
As long as the CI/Outbound are able to get finalised, the corresponding SI should be created in the receiving store, despite migrations

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. create a storeA on 2022-12-12 and set it up as remote-active-destop-storeA as well
2. create a CI (of ‘nw’ status, and note it has to be a stock-transfer, i.e., create CI to another oms-storeB) on desktop-remote-siteA on 2023-12-12 and sync completely
3. close the desktop-siteA : we decide to switch to oms
4. On mSupply-Cloud, completely clear out the hardware ID & all for siteA, then re-initialise on oms on today’s date: 2024-05-02
5. now in oms-siteA, check that previously created CI of 'nw/sg' status
6. finalise it (In oms language, change status to Shipped) and sync
7. for the receiving-storeB, the corresponding SI is not created at all
Question: why is that SI missing? 
Note: I've checked normal shipment flow from one oms-store to another; it's fine. So problem looks only for those who have migrated from desktop.

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc2
- Legacy mSupply Central Server Version: v7-14-00

- Platform: oms-central on server exe, remote-oms on server + browser (chrome)

- Database type: sqlite

## Notes/Additional
Can I call this `severity: high`? 
..since it's likely to happen (correct me if I'm wrong here) : I mean, people do make CI’s and sometimes don’t finalise it later and leave them instead of removing lines and deleting. And when we convert such desktop-sites to oms-sites; there remains this chance where they can process those old invoices. And when they do not see the corresponding SI, it’ll get submitted as a bug.

**Comment by Chris-Petty** [comment]
@nisha-dangol sorry to hassle but to be completely precise, did you sync `oms-siteB` after step 7? On sync v5 `oms-siteB` is responsible for making the transfer records and sending them back to the central server. Just in case you only checked the central server without syncing!

**Comment by nisha-dangol** [comment]
> @nisha-dangol sorry to hassle but to be completely precise, did you sync `oms-siteB` after step 7? On sync v5 `oms-siteB` is responsible for making the transfer records and sending them back to the central server. Just in case you only checked the central server without syncing!

Yes, I did.

**Comment by clemens-msupply** [comment]
@nisha-dangol I tried to reproduce it but failed to do so:

1) I have an mSupply server running
2) mSupply client running and I created the CI to the receiving store
3) The omSupply receiver store gets the SI record with status 'sg' (not visible in the UI but in the database)
4) shutdown mSupply client and startup the omSupply client
5) ship the outgoing shipment
6) At the omSupply receiver store; the incoming shipment gets updated correctly

Could you please try again? if you still can reproduce it could you please send me the 4d datafile and the two sqlite DBs for the omSupply sites (if you use sqlite)? Maybe a very detailed description of how you are running your system would also be helpful to reproduce it (or zoom).

**Comment by nisha-dangol** [comment]
> @nisha-dangol I tried to reproduce it but failed to do so:
> Could you please try again?
>
I retried today with the latest v2.0.02; not replicable anymore - the old shipment is getting received correctly in the receiving-oms-store. 
Maybe got fixed in v2.0.02; will close it
