### ISSUE TITLE
OS: Issued lined disappears when expired in 

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3736]
## What went wrong? 😲

When issuing stock from expired stock line, after re-opening OS line edit modal, and clicking somewhere, the line will disappear

https://github.com/msupply-foundation/open-msupply/assets/26194949/9a3364a2-debc-4702-818b-8912ffdbfc8f

Video is from Kopu store on demo store: https://demo-open.msupply.org/distribution/outbound-shipment/139?sort=itemName

## Expected behaviour 🤔

Line remains unchanged when re-opening

## How to Reproduce 🔨

In OS issue some stock from expired stock line in OS line edit, press ok to exit modal, re-open modal by clicking on the line, click anywhere (even ok button) the line will disappear from view

## Your environment 🌱

V2.0 RC branch

**Comment by roxy-dao** [comment]
Related to #3532 or possibly same issue

**Comment by andreievg** [comment]
Sorry did a self triage, while looking at issues, found: https://github.com/msupply-foundation/open-msupply/issues/3532, and decided we need to fix this issue, and while fixing this issue check out: https://github.com/msupply-foundation/open-msupply/issues/3532

**Comment by lache-melvin** [comment]
Closed by #3814

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.0.00`


- [ ] Add a line to outbound shipment, issue stock from a line that the auto allocation wouldn't choose (e.g. expired)
- [ ] Click ok
- [ ] Reopen edit modal by clicking that line
- [ ] Click anywhere to shift focus away from the issue quantity input
- [ ] Your allocations don't change
