### ISSUE TITLE
Comments and reference field values don't sync in stock transfer

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3738]
## What went wrong? 😲
 
Comments and reference field values don't sync in stock transfer

## Expected behaviour 🤔
ALong with quantities, comments & references should also sync?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup at least 2 oms-stores
2. Create an outbound from one storeA to storeB with comments(eg: commentABC) and references(eg: refABC)
3. Just put status upto `picked` and sync
4. On storeB, you can already see that shipment under Inbounds with `picked` status
5. You cannot edit yet but can see the previous comments and references all
6. Now in storeA, make changes in comments (change it to sth like commentXYZ), quantities & references (change it tom sth like refXYZ) and confirm status to `shipped` now, and sync
7. In storeB, you can finally see that shipment as editable
8. See error: the old comments(commentABC) & references(refABC) are there instead of updated ones, only the quantities are updated-ones

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc2
- Legacy mSupply Central Server Version: v7-14-00

- Platform: oms-central on server exe, remote-oms on server + browser (chrome)

- Database type: sqlite

**Comment by Chris-Petty** [comment]
https://github.com/msupply-foundation/open-msupply/blob/6444ed82e6c3ea40bf6e9f6a7ed59ac98fef9df3/server/service/src/processors/transfer/shipment/update_inbound_shipment.rs#L72-L77

As far as I can tell we drop all existing lines and recreate them all with the updated values. So any changes to comments on them would be updated as far as I can tell.

https://github.com/msupply-foundation/open-msupply/blob/6444ed82e6c3ea40bf6e9f6a7ed59ac98fef9df3/server/service/src/processors/transfer/shipment/update_inbound_shipment.rs#L95-L103

For the invoice record itself though it appears we only ever update the the status, so yea the comments and what not won't change. @andreievg why is it hardcoded to updated to "shipped", surely that'd make any update to a "picked" invoice look like it's shipped regardless of actually being shipped? though I'd consider that a separate bug to the one opened here.

**Comment by andreievg** [comment]
@Chris-Petty if you follow the comment `// 6.` there is some extra explanation about it above, hopefully that's helpful. 

We can update the comment again, I think we stopped cause this required a bit of a design decision, to show reference and comment from the linked shipment somewhere other then an editable field on the new shipment

**Comment by roxy-dao** [comment]
Does this still require design? 👀

**Comment by andreievg** [comment]
In the right detail view add their comment and their reference, showing linked entity comment and reference (non editable), for lines we would need some extra design (but would be good to see how much was received, etc..)

**Comment by lache-melvin** [comment]
Closed by #4282

**Comment by nisha-dangol** [comment]
## Tests
Tested in v2.1.0-rc6
- [x] Create an outbound shipment
- [x] Add a comment/reference/transport reference/some service charge etc
- [x] Set to picked
- [x] Log in to receiving store
- [x] All the above mapped through correctly
- [x] Go back to sending store, update all those fields to something else
- [x] Set to shipped
- [x] Go back to receiving store
- [x] All your changes are reflected
