### ISSUE TITLE
Functional status not syncing from the remote site to central

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3739]
## What went wrong? 😲
As shown in the below images the status is not syncing to the central server
 
<img width="1006" alt="Screenshot 2024-05-02 at 2 31 47 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/a282e077-89f2-4197-822e-c4fee00bfd36">
<img width="1010" alt="Screenshot 2024-05-02 at 2 32 35 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/756cdbe0-26c5-420d-b531-e9a20dd62fd9">
from the desktop remote the status is not even syncing to the central server

![Screenshot 2024-05-02 at 2 28 36 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/1785b8df-b042-4925-93e8-4ed1d2d647d9)

## Expected behaviour 🤔

functional status should be synced

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login to remote site with a user who's never logged into OMS Central
2. Create an asset
3. Add a functional status for the asset
4. Sync to the central oms 
5. Login to central oms with a different user
6. See the status not updated properly on central

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: browser, mobile

- Database type:

**Comment by jmbrunskill** [comment]
@AnushaUp Any more suggestions on how I can recreate this? Works perfectly for me.

**Comment by AnushaUp** [comment]
@jmbrunskill I'm stil getting empty status for those assets which are created from remote 🤷‍♀️
![Screenshot 2024-05-06 at 1 01 33 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/f26936a2-211e-46fd-9c30-8bd216f7fe1f)

**Comment by jmbrunskill** [comment]
> [@jmbrunskill](https://github.com/jmbrunskill) I'm stil getting empty status for those assets which are created from remote sites and remote sites are mobile oms site🤷‍♀️

Hmmm can you double check the version of those tablets? And maybe send me the logs & database?

**Comment by AnushaUp** [comment]
@jmbrunskilI checked again with @nisha-dangol and its like the status is updating from the cloud only and not from the remote site.
Here's datafile cloud 
[714-oms setup.zip](https://github.com/msupply-foundation/open-msupply/files/15231281/714-oms.setup.zip)
Remote sites's database 
[openmsupply.sqlite (6).zip](https://github.com/msupply-foundation/open-msupply/files/15231310/openmsupply.sqlite.6.zip)

**Comment by jmbrunskill** [comment]
@AnushaUp I tried it with your database today, and at first it didn't seem to sync but then the statuses did show up.
Is it just a bit slow? Otherwise maybe I need to try syncing to your server to investigate more?

**Comment by nisha-dangol** [comment]
In v2.0.0-rc5 exe
- Created some Equipments from remote-site and updated status and synced:
<img width="1283" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/eb3486c5-1367-400f-a3fa-ecaeb80aeb4f">

- Checking in oms-central, that status has not synced to central-oms at all:
<img width="1430" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/d1c5d551-1c74-4e74-a664-c40b0eab076d">

**Comment by jmbrunskill** [comment]
I just tested with Anusha's server to my local on RC branch and it's working for me still. Don't know what's going on differently for you two.

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/aeb0322f-a642-454f-b705-081d7dd768b0)

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/4f028762-3e5d-494a-bfac-2d34e5233bf0)

**Comment by nisha-dangol** [comment]
Took a new datafile and setup a fresh one (including new mSupply Cloud as well); and the statuses are syncing just fine; this can be closed now? So, I'm guessing the old datafile we were using got corrupted somehow and ain't reliable anymore.

**Comment by jmbrunskill** [comment]
Closed due to corrupted database...

**Comment by jmbrunskill** [comment]
Found the cause I think...
Sync fails if the user who logged the status is not present on the central server...

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.0.00`


- [ ] OMS Central Sync server with an OMS remote site running this PR
- [ ] Login to OMS Remote with user that hasn't logged into Central
- [ ] Create an asset
- [ ] Create a status log
- [ ] Sync to Central
- [ ] Login to Central with different user
- [ ] Check that the asset and status both synced correctly.
