### ISSUE TITLE
App crash automatically after some time

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3740]
## What went wrong? 😲
 
When we leave the screen for some time (for me it was half an hour) with the cold chain > equipment list is on screen
![Screenshot 2024-05-02 at 2 09 02 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/940710e3-705f-43c1-b09b-a938689c3af6)

## Expected behaviour 🤔
It should just logout
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to coldchain > equipment list
2. Leave it for some time
3. See error

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

**Comment by andreievg** [comment]
@roxy-dao can this be pushed to 2.1 ? Seems pretty low impact and low probability ?

**Comment by roxy-dao** [comment]
> @roxy-dao can this be pushed to 2.1 ? Seems pretty low impact and low probability ?

Sure~

**Comment by adamdewey** [comment]
Not sure I would classify a crash as low impact?

**Comment by CarlosNZ** [comment]
> Not sure I would classify a crash as low impact?

I'll leave the CC list on the demo site open in another browser for today and I'll see if it can be reproduced. Could be a problem with the auto-logout?

**Comment by roxy-dao** [comment]
> > Not sure I would classify a crash as low impact?
> 
> I'll leave the CC list on the demo site open in another browser for today and I'll see if it can be reproduced. Could be a problem with the auto-logout?

It's not logging the user out tho?

**Comment by CarlosNZ** [comment]
I have reproduced this on the demo site, but not locally. Nothing useful on the console, unfortunately. It seems to correspond to the idle time-out period, but not sure yet. I'll see if it happens on any other pages.

**Comment by mark-prins** [comment]
ooh, interesting. the dashboard query is throwing an error on demo (stockCounts.expired) and then `TypeError: Cannot read properties of undefined (reading 'nodes')` 
possibly the `assets` query. I'll have a look.

**Comment by roxy-dao** [comment]
can we move this back to 2.0.0-RC4 then? 👀

**Comment by mark-prins** [comment]
Hopefully yes, will see what I can find.

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.0.0-rc5`


- [ ] Check that the site behaves as normal 🤷 
- [ ] The only reliable test was to log into the demo server and leave that on the equipment list view until timed out. last time I tried this however, there was no error

**Comment by AnushaUp** [comment]
@fergie-nz @mark-prins couldn't recreate this anymore
