### ISSUE TITLE
Cannot sort the list in equipment table

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3741]
## What went wrong? 😲
 
There's no sorting way in the CCEI module list as shown in the given teble.

<img width="994" alt="Screenshot 2024-05-02 at 3 24 37 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/f32c8c83-dd0b-4965-8914-55f85e19f1e3">

## Expected behaviour 🤔
sorting is needed for some columns
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to coldchain > equipment list
2. Try to sort in the column

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

**Comment by roxy-dao** [comment]
More info from google docs: Most crucial would be Store, Asset number and Functional status fields

**Comment by roxy-dao** [comment]
Will add functional status as a filter in this issue as well

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in mobile `v2.1.0-IA-test-2`


- [ ] Go to `Coldchain` -> `Equipment`
- [ ] Have some equipment
- [ ] Try sort by store or asset number
- [ ] Use the functional status filter
