### ISSUE TITLE
Error message not showing clearly while importing the assets

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3742]
## What went wrong? 😲
 
It doesn't show clearly what went wrong while importing the asset list. It completely ignore the date format.
![Screenshot 2024-05-02 at 3 18 12 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/05d366ac-fc63-4857-aaa0-dee38c164049)

## Expected behaviour 🤔
Should give some hint on what went wrong

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to coldchain > equipment
2. Click on import button
3. Try putting wrong date format on the file
4. Click ok
5. Doesn't let us import and doesn't show the error message properly

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

**Comment by mark-prins** [comment]
should validate the date, if one is provided in the import file.

**Comment by fergie-nz** [comment]
I think this might require some design input.

Currently when importing, and a date isn't formatted correctly, it will still import the whole asset list and ignore the date where it is invalid leaving it as null

If we include front end validation, we would block the entire input file. Would this be more desirable or add more work for user inputs if they're blocked from importing because non-required fields are not importing correctly?

I wonder if an alternative solution would be to add warnings to say date won't be parsed - but you can still import the assets (maybe just show warnings at the various lines)

**Comment by adamdewey** [comment]
Yeah I like the idea of a warning Ferg!

**Comment by AnushaUp** [comment]
# 🧪 Testing

- [ ] Open open mSupply with vaccine module
- [ ] Try importing some cold chain equipment where the date field is not a date such as this file:
- [ ] [equipment upload template_2024-04-16 (1).csv](https://github.com/msupply-foundation/open-msupply/files/15257060/equipment.upload.template_2024-04-16.1.csv)

**Comment by AnushaUp** [comment]
@fergie-nz Here I've explored some of the warnings that I've got recently.
![Screenshot 2024-05-15 at 12 13 09 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/a5eff8aa-95e0-4145-9aee-1e6999c0ec9e)
![Screenshot 2024-05-15 at 12 10 43 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/810b5615-b115-40f6-b9e3-856fe3ce7cb5)
![Screenshot 2024-05-15 at 12 01 20 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/9c4e5fd2-c892-4c3b-9133-4a4b4858f2a3)

**Comment by adamdewey** [comment]
I think we might need some more user friendly messages here?

Don't think the average user would understand what `Installation date not parsed` would mean?

Also don't think the Store error reference the Catalogue - not sure that makes sense? 

And might need some spaces in the `AssetNumberAlreadyExists` message :)

**Comment by lache-melvin** [comment]
@fergie-nz You have this as `In PR` ... can you link the PR? 🙏

**Comment by lache-melvin** [comment]
Closed by #3843
