### ISSUE TITLE
Code filter in Asset Register does not work

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3743]
## What went wrong? 😲
 
While trying to filter with the code in the coldchain > equipment list it doesn't work as expected instead it will just become unresponsive as shown in video below. 

https://github.com/msupply-foundation/open-msupply/assets/115983430/733e59c6-14a6-47f2-bf68-6a25f01641a6

## Expected behaviour 🤔
should return to the list 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to equipment list
2. Try searching something with `code` filter
3. See error

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

**Comment by mark-prins** [comment]
Unable to reproduce the error. I do get a message though, that the code cannot be filtered (this was renamed to asset number and needs updating) so I'll fix that instead.

<img width="693" alt="Screenshot 2024-05-06 at 11 40 27 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/265924c6-9751-4bd4-81cb-548306f0b484">

**Comment by marthakeezy** [comment]
Just tested using V2.0.0-rc4 - since the field was renamed to Asset Number, there is technically nothing to test, checked the functionality of the Asset Number and everything is working as expected! Build test passed :) ✅
