### ISSUE TITLE
Installation date doesn’t appear in Asset Register list view

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3744]
## What went wrong? 😲
 
There's no installation date column in the list but filter option is given there.
![Screenshot 2024-05-02 at 4 01 51 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/599a3ea5-d89d-4ba3-8012-7ec809b38ad7)

## Expected behaviour 🤔
There should be installation date cloumn shown in the list view

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to coldchain > equipment list
2. Click on 

## Your environment 🌱

- Open mSupply Version: v2.0.00-rc2
- Legacy mSupply Central Server Version: V7-14-00

- Platform: web, mobile

- Database type:

**Comment by adamdewey** [comment]
Best to add this as a hidden column if possible (i.e. not shown by default on startup) so the listview doesn't get too large

**Comment by mark-prins** [comment]
We don't have the ability to add hidden columns - and I think having it hidden does not address the issue: that you can filter by a value that you cannot see.

I would either
* (a) remove the filter, or 
* (b) add the column

preference?

**Comment by adamdewey** [comment]
In that case I would just add it on the far right as it's less important than the other columns but could still be useful for the central user or facilities with a lot of CCE?

**Comment by AnushaUp** [comment]
Tested Here https://github.com/msupply-foundation/open-msupply/issues/3725 and working fine.👍
