### ISSUE TITLE
Cannot search by Asset Number under Cold Chain -> Equipment

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3750]
## What went wrong? 😲
 

**Requested by Adam :)**

Cannot search by Asset Number under Cold Chain -> Equipment. As each entry has to have an Asset Number, it should be an option to sort and filter using them :)

<img width="1432" alt="Screenshot 2024-05-03 at 12 11 07 PM 1" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/063a7951-d6b6-497c-b518-4891de7930ff">

## Expected behaviour 🤔

This needs to be one of the filters we can use to sort through the entries

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Equipment
2. Click on 'Filters' -> notice there is no option to filter using Asset Number

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Android, Galaxy A8 Tablet

- Database type: ?

**Comment by jmbrunskill** [comment]
Related to this is trying to search by `Code` fails

![50226](https://github.com/msupply-foundation/open-msupply/assets/8287373/95019135-0fab-4fa5-8c61-3ecaf7d2df98)


Code filter should be replace by asset number filter

**Comment by mark-prins** [comment]
Fixed with #3743

**Comment by marthakeezy** [comment]
Just tested in V2.0.0-rc4, and the Asset Number can be searched by in a separate field. The search function also works as expected - build test passed! :) ✅

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/7dbbf653-b434-4eff-89d5-6d0d1b10c487)

**Comment by adamdewey** [comment]
🤔 Why is the Asset Number field on a line below the other filters?

**Comment by mark-prins** [comment]
likely just screen width, and that one is the last, so its wrapping

**Comment by adamdewey** [comment]
Oh, but it kind of looks like there _should_ be enough space?

**Comment by mark-prins** [comment]
But there isn't..
This is desktop on a wide monitor:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/e7eb4fde-35cc-47d1-aaed-b60dda727979)

and this is the desktop app, default size:

<img width="1286" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/8aaf4540-a8f3-4b9d-866c-ee6894bba45e">

and if I make the desktop app a bit wider:

<img width="1420" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/8bdd4fbb-50b7-4baf-8b37-309b744cf3a4">

**Comment by adamdewey** [comment]
aha! 

I see - it's because the Actions dropdown also shifts down a line...
