### ISSUE TITLE
Add selectors for automated testing

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3751]
## Is your feature request related to a problem? Please describe 👀
In trying to automate testing with selenium, I've found it helpful to have some properties added to components:

* login page: username input
* login page: password input
* language selector button
* language buttons

## Describe the solution you'd like 🎁
Adding a `name` or `className` to these elements would enable selection, which allows logging in and language selection.

### Describe alternatives you've considered 💭
Tried to use generic selectors; it's more accurate if these are targeted.

**Comment by AnushaUp** [comment]
Tested and PASSED✅
