### ISSUE TITLE
Open mSupply hangs when you order form Dashboard

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3757]
## What went wrong? 😲

Open mSupply hangs when you order form Dashboard

https://github.com/msupply-foundation/open-msupply/assets/117138852/e5f1ad42-c285-4046-8764-2914df865a22

![Screenshot 2024-05-03 at 13 28 01](https://github.com/msupply-foundation/open-msupply/assets/117138852/b1ba7810-023c-4812-827f-10c19d17ec46)

## Expected behaviour 🤔

1. The number should populate correctly
2. The page should load

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Click on Dashboard form the menu bar
3. Click on `Order more` option
4. Click on Any store
5. The page gets hanged (BUG)

##  Notes
Checked in v1.7.0 exe, looks fine there.

## Your environment 🌱
- Open mSupply Version: v2.00-RC2
- Legacy mSupply Central Server Version: v7-15-00-dev2, v7-14-00

- Platform: server exe, browser(brave, chrome), , omSupply Desktop, standalone

- Database type: sqlite

**Comment by regotaina** [comment]
Tested on RC4 .apk and it doesn't occur anymore.
We can order from dashboard, no problems.

PASSED THE TEST 💯
