### ISSUE TITLE
Catalogue -> Assets -> Log Reasons -> swap Reason and Status around

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3760]
## What went wrong? 😲
 

**Requested by Adam :)**

The order of the columns is not intuitive and should be swapped around :) The user is likely to think in terms of Status first, and then Reasons. 

<img width="1511" alt="Screenshot 2024-05-06 at 11 36 45 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/83e50cce-9f37-465a-a24f-28d199828f17">

## Expected behaviour 🤔

It would be good to swap the column order and to sort by the Status column so that all Reasons for each Status are grouped together

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Assets
2. Click on 'Manage Asset Log Reasons'
3. See the column order

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Windows

- Database type: ?

**Comment by Chris-Petty** [comment]
@marthakeezy as I know you've been chatting with @adamdewey, can you please get an indicative severity* and mention if Adam has requested the change - makes it much more clear cut on priority that way.

(* or priority - I am indifferent about this being a bug or enhancement, arguably depends on what the initial design was heh)

**Comment by adamdewey** [comment]
Hey @Chris-Petty - yeah, shouldn't really be marked as a bug. 

Priority should be `Nice to have`

There is a document with my indicative priorities in here: https://docs.google.com/document/d/1SiR9u6kFqorQPopXXxhH1wmXdTIbn1H4P1repO_8__Y/edit#heading=h.ybb99y1pg59k

But I'll update from `Low` to match the terminology we're using here for priority so QA (or whoever) can apply

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in V2.0.00


- [ ] Go to `Asset` page
- [ ] Click on `Manage asset reason` button
- [ ] See that columns have been swapped
