### ISSUE TITLE
Central user can select Cold Storage locations for other stores

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3762]
## What went wrong? 😲
 

**Requested by Adam :)**

Central user can select Cold Storage locations for other stores. The central user shouldn’t be able to link cold storage locations to assets for other stores. 

<img width="1062" alt="Screenshot 2024-05-06 at 11 49 26 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/4a288b68-2074-4c0d-b160-6deb1134f498">

## Expected behaviour 🤔

The central user shouldn’t be able to link cold storage locations to assets for other stores. Best thing would be to hide this field when logged in as the central server as it doesn’t make sense to be able to make the link when operating in that mode. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Equipment
2. Click on any piece of equipment
3. Notice how you can click on a dropdown and select an option for 'Cold storage location'

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Windows

- Database type: ?

**Comment by Chris-Petty** [comment]
Really don't want release with this one so gone to scary red label
