### ISSUE TITLE
CCE not showing in Sensor modal

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3764]
## What went wrong? 😲
We're now showing CCE asset number in the sensor list view but that isn't being reflected in the sensor edit modal
![Screenshot 2024-05-06 at 11 55 50](https://github.com/msupply-foundation/open-msupply/assets/61820074/c128d1b8-e2a4-4867-8f17-bbf0455f3a5d)

## Expected behaviour 🤔
Should show CCE

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have an asset configured for sensor
2. Go to `Sensor`
3. Click on the line that has the CCE
4. See `-`

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by fergie-nz** [comment]
This is working fine so closing :)

![Uploading Screenshot 2024-05-07 at 11.59.04.png…]()

**Comment by marthakeezy** [comment]
Just tested on V2.0.0-rc4, confirmed with Ferg CCE field is the Asset Number in this case so nothing to test :) Passed! ✅
