### ISSUE TITLE
Cold Chain -> Equipment -> most useful filters not shown by default

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3767]
## What went wrong? 😲
 

**Requested by Adam :)**

Cold Chain -> Equipment -> most useful filters not shown by default. The filters are most likely to be used by the central user as most facilities will only have a few CCE and should be able to see them all on 1 or 2 pages. 

<img width="1070" alt="Screenshot 2024-05-06 at 12 43 24 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/69acff3b-93cf-433d-bbc9-d25419e3af65">

## Expected behaviour 🤔

For the central user the most useful filters would be: 

- Store
- Category
- Functional status
- Asset number
- Serial number

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Equipment
2. Note which filters are displayed by default

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Windows

- Database type: sqlite

**Comment by mark-prins** [comment]
@marthakeezy - are you saying that we should not show those filters by default? I've removed the 'bug' label bc that's what it sounds like; in which case it's a change to functionality, but not a bug as nothing is broken.

@adamdewey - this is a requirements decision I think. Which filters should show by default?

**Comment by adamdewey** [comment]
@mark-prins - ah sorry, I asked Maria to raise this issue. 

The filters that would be most useful would be: 

- Store
- Category
- Functional status
- Asset number
- Serial number

But yes agree, it's more of a feature request!

**Comment by marthakeezy** [comment]
Eh sorry! Raised an incorrect type :)

**Comment by Chris-Petty** [comment]
The search box says "code" but there is no such column, I guess it's referring to "Store" column?

**Comment by adamdewey** [comment]
> The search box says "code" but there is no such column, I guess it's referring to "Store" column?

The Code is supposed to be renamed to `Asset number` - there's another issue for it somewhere..

**Comment by mark-prins** [comment]
the issue to change code to asset number is #3743

**Comment by craigdrown** [comment]
I was just about to create an issue called "Equipement list - no way to filter by Functional Status &  Date filter is a waste of space" and found this.
"Functional Status" seems the most impt filter and it doesn't exist ("As a user I want to know which equipment is broken" ;-)  )
The date filter seems to only allow finding assets created on a particular date. Can't see how that's helpful- either should be a date range filter or not exist?
Thanks!

**Comment by adamdewey** [comment]
Yes, agree - I don't think the date filter is needed at this point. 

More likely it will just be used to calculate when a CCE has reached its `End-of-life` and needs replacing - but that calculation will be done in the dashboard (for now)

Agree that functional status filter is important.

I would also like to see a way to sort the Functional Status column at some stage, in order of:

- 'Not functioning'
- 'Functioning but needs attention'
- 'Functioning' 
- 'Decommissioned'
- 'Not in use'

**Comment by marthakeezy** [comment]
Build test passed for this issue, however logged #4886 for the Actions dropdown -> moving to Done
