### ISSUE TITLE
Have to click `Ok` twice if permission is denied

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3771]
## What went wrong? 😲
If I go to a page which requires a permission that I don't have then I have to click `Ok` twice to dismiss the error

https://github.com/msupply-foundation/open-msupply/assets/61820074/53d17602-2211-4f7b-9c67-1fbb199ac050

## Expected behaviour 🤔
Should only have to press `Ok` once

## How to Reproduce 🔨

Steps to reproduce the behaviour: Easiest way to recreate is to turn off some permission and go to the page associated with that permission

## Your environment 🌱

- Open mSupply Version: V2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by Chris-Petty** [comment]
Please fill in environment details! At least OMS version 😁

**Comment by Chris-Petty** [comment]
I reckon normal priority and good to fix as basic things like OK buttons not working as expected add up quickly to annoy users

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.0

## Tests
- [x] Remove some permission (e.g. View assets)
- [x] Try to go to asset page
- [x] Should get AuthErr -> click ok
- [x] Should disappear
- [ ] Wait for timeout - I don't think I understand this step here? 
- [ ] Same as step 3 & 4

@roxy-dao If I'm on browser (chrome), I switch to a new tab and come back to the asset page again, is it expected to keep getting the alert everytime? 

https://github.com/msupply-foundation/open-msupply/assets/59193490/c4c7ae90-9839-40eb-bddd-447ec0315734

**Comment by roxy-dao** [comment]
> # Testing
> Tested in v2.0.0
> 
> ## Tests
> * [x]  Remove some permission (e.g. View assets)
> * [x]  Try to go to asset page
> * [x]  Should get AuthErr -> click ok
> * [x]  Should disappear
> * [ ]  Wait for timeout - I don't think I understand this step here?
> * [ ]  Same as step 3 & 4
> 
> @roxy-dao If I'm on browser (chrome), I switch to a new tab and come back to the asset page again, is it expected to keep getting the alert everytime?
> 
>  3771-15.05.2024_17.04.07_REC.mp4

Timeout is just if you leave your browser open for a long time then it should log you out at some point in time when your token has expired.

Yes, because you still don't have permission to go to that page (I'm assuming)

**Comment by mark-prins** [comment]
while it's annoying, I think it's good to still say that permission is denied. otherwise you have a blank page and it's not clear why there are no assets showing

**Comment by nisha-dangol** [comment]
> while it's annoying, I think it's good to still say that permission is denied. otherwise you have a blank page and it's not clear why there are no assets showing

Ok, convinced; PASS.
