### ISSUE TITLE
Internal order select supplier modal input keeps clearing

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3774]
## What went wrong? 😲
 

When accessing in browser on tablet... not really a core platform so maybe a not huge issue?

But the input keeps resetting:

https://github.com/msupply-foundation/open-msupply/assets/55115239/dff9b8dc-ee4e-4949-abc8-d42cf01daa57

## Expected behaviour 🤔

Be able to type in supplier name in supplier select modal

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Internal Orders
2. Click new order
3. Start typing supplier name
4. See issue: name keeps clearing

## Your environment 🌱

- Open mSupply Version: v2.0.0 RC 3
- Legacy mSupply Central Server Version: 7.14

- Platform: Browser on tablet

- Database type: sqlite3

**Comment by Chris-Petty** [comment]
Are you 100% sure it's only for browser on tablet and not our app? Our app is basically a browser so I'm surprised it's much different 😆. If it's app too then `severity: hotfix` and rcX milestone pls!

**Comment by lache-melvin** [comment]
Definitely only browser! 🤷‍♀️

**Comment by roxy-dao** [comment]
I think move to low priority if it is only happening on a browser on tablet and no one is using browser on tablet?

**Comment by Chris-Petty** [comment]
Done a call out to check, I think there might be one customer who exclusively uses the app via browser on tablets haha

**Comment by roxy-dao** [comment]
Movin' to 2.2 milestone since we dunno if they wanna upgrade to 2.1!

**Comment by andreievg** [comment]
Looks like re-render issue ? Worth having a quick look to understand why but not important to fix atm

**Comment by andreievg** [comment]
Been open since May !

**Comment by AnushaUp** [comment]
PASSED✅
