### ISSUE TITLE
Stocktake: not checking if 'reason' is provided when finalising stocktake (if 'reason' is configured)

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3776]
## What went wrong? 😲

@lache-melvin and I worked on this one: 

After configuring 'Reason' on mSupply server > Admin > Preferences > Options > Positive/Negative inventory adjustments

If you have already a stocktake saved with status = new, with some lines already added into it, oms allows you to Finalise the stocktake despite not providing any 'Reason' for the lines.

If you add new lines, after configuring the reasons, it will be a mandatory field. 

We suspect the system is not checking if there are any mandatory reasons provided before Finalising the stocktake. 

## Expected behaviour 🤔

Should 'Reasons' be applied retroactively? on any stocktakes saved with status = new ?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure all 'Reasons' are inactive on 'mSupply server > Admin > Preferences > Options > Positive/Negative inventory adjustments'
2. At OMS go to 'inventory' and create a new stocktake
3. Save this new stocktake but do not finalise
4. go back to 'omSupply server >Admin > Preferences > Options > Positive/Negative inventory adjustments ' and make at least 1 reason active again
5. Go back to 'OMS> stocktake' and select the stocktake you created on step 2
6. Click on any line. you will see the 'Reason' field is now mandatory. However you can press 'cancel' and it'll take you back to the stocktake
7. Finalise the stocktake. See the error.

## Your environment 🌱

- Open mSupply Version: V2.0 RC3
- Legacy mSupply Central Server Version: V7.14.0

- Platform: Android

**Comment by lache-melvin** [comment]
For dev clarity: The stocktake edit line modal (and edit line mutation) requires a reason when counted packs is different to snapshot packs, if reasons are configured.

However, if you create the stocktake line when no reasons are configured, then configure reasons, the `finalise stocktake` mutation does not validate that lines have reasons.

Seems like a fairly low possibility use case... mostly just flagging if this is a gap we care about!

**Comment by Chris-Petty** [comment]
I think stocktakes are common enough users would run into this when reasons are added. Making it retroactively mandatory does create a bit of pain - if you have a stocktake with 1000s lines now you have to potentially go fix 100s of lines if they have discrepancies. You may not know exactly what happened for each item (the user finalising may not have done the counts, may not remember for 100s of items counted). 

@mark-prins court to decide how it should work!

**Comment by mark-prins** [comment]
triage: we decided to retain the current functionality, concerned that 
* we make it difficult for users with unfinalised stocktakes who try to finalise after reasons are added
* reasons are expected to be configured before the system is being used

therefore closing the issue, will make a note to document
