### ISSUE TITLE
Generate Diesel schema macros from database 

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3777]
## The suggestion

From https://github.com/msupply-foundation/open-msupply/pull/3654#issuecomment-2095102883

Use  `diesel print-schema` to generate schemas (https://diesel.rs/guides/schema-in-depth.html)

This would have a couple of advantages:
- solve Postgres enum problem (see link above)
- ensures right order of db/macro fields
- might saves dev time

### How much effort is required?

- Extend our cli tool:
  - to be able to migrate a temp DB
  - run `diesel print-schema` and put output into correct directory
  - clean up temp DB

- Remove existing macros from code (might be a lot of work)
- Handle potential sqlite/postgres mismatches?

**Comment by Chris-Petty** [comment]
Yoooo I was working on support-db and found that the generation was pretty nice DX. Got me wondering if we could get it working cleanly for OMS. Particularly maintaining `diesel::joinable!` and `diesel::allow_tables_to_appear_in_same_query!` is tedious and easy to misdo manually. 

I still feel early on my diesel and rust journey but this is an interesting quote also (might be another issue in the refactor category):

>The dsl module should only ever be imported for single functions. You should never have use schema::users::dsl::*; at the top of a module. Code like #[derive(Insertable)] will assume that users points to the module, not the table struct.

I wonder how often it'd be very clean to import the dsl in the relevant function of repo layers. Often we have dsl at the top of a module but the docs do explicitly say not to!

**Comment by Chris-Petty** [comment]
> ### How much effort is required?
> 
>     * Extend our cli tool:
>       
>       * to be able to migrate a temp DB
>       * run `diesel print-schema` and put output into correct directory
>       * clean up temp DB
> 
>     * Remove existing macros from code (might be a lot of work)
> 
>     * Handle potential sqlite/postgres mismatches?

Is the intent here that we generate a schema file for each table? Or do we just YOLO generate one giant schema file as diesel does by default. What would be wrong with that? Compilation implications? We don't have to do any additional CLI work then, we can just run `diesel setup` to update the schema file.

Also one thing when I discussed this with @andreievg yesterday was worry about discrepancies between SQLite and Postgres generation. In particular, sqlite doesn't have `enum` support.

**Comment by clemens-msupply** [comment]
I played a bit with the diesel cli tool. We need the Postgres flavour to be able to generate the enums:
`cargo install diesel_cli --no-default-features --features postgres`

This will give use a single big file with entries like:

```rust
pub mod sql_types {
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "activity_log_type"))]
    pub struct ActivityLogType;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::ActivityLogType;

    activity_log (id) {
        id -> Text,
        #[sql_name = "type"]
        type_ -> Nullable<ActivityLogType>,
        user_id -> Nullable<Text>,
        store_id -> Nullable<Text>,
        record_id -> Nullable<Text>,
        datetime -> Timestamp,
        changed_from -> Nullable<Text>,
        changed_to -> Nullable<Text>,
    }
}
```

This file also contains all `allow_tables_to_appear_in_same_query` and `joinable` macros.

We would need to map the db type struct to the Rust enum as described here: https://github.com/adwhit/diesel-derive-enum.
I think this enum mapping should also work for sqlite but have to double-check.

The generated code contains some Postgres specific macros, e.g. `#[diesel(postgres_type(name = "activity_log_type"))]`. However, we could write our own custom script to duplicate the Postgres file and then remove the Postgres macros when using Sqlite. 

## Sqlite schema validation?
A nice to have would be a validation script that checks that the sqlite database schema matches the postgres schema. E.g. it seems like diesel assumes that the field order in the `table!` macro matches the column order in the DB and if there is mismatch you might end up reading the wrong column. Test should catch these errors, but can imagine that some tests don't cover less important columns such as "notes" or "comments" and errors might get go unnoticed there.

Idea: This validation could be done by generating the diesel macros from the Sqlite DB as well and then comparing the generated `table!` macros with the macros from Postgres. This might just work by stripping all unrelated lines from the generates files and then checking if the files match.

**Comment by Chris-Petty** [comment]
I thought the `table!` macro just needed to match the `Queryable` struct's fields order, not the DB fields order?

**Comment by clemens-msupply** [comment]
> I thought the `table!` macro just needed to match the `Queryable` struct's fields order, not the DB fields order?

Yes right, and apparently there is a `#[diesel(check_for_backend(diesel::pg::Pg)]` macro to check it, thought that would be done on default by the `#[diesel(table_name = mytable)]` macro...

**Comment by andreievg** [comment]
Refinement, we happy to close this, it's probably a good idea to do some tests in the repository layer to validate types.
