### ISSUE TITLE
Patient: V2.0.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3788]
## Patient Registration
- [x] Go to the “Patients” menu and click the “New Patient” button in the right top corner.
### Entering of basic patient information such as name or date of birth
- [x] A patient window open with the following fields
   - [x] Code - 'Generate' button works
   - [x] First Name
   - [x] Last Name
   - [x] DoB
   - [x] Gender
   - [x] Address
   - [x] Phone
### Search for existing similar patients to avoid duplicated patient entries
- [x] The `Ok&Next` button gets enabled only after you enter values in either First or Last name
- [x] If any existing patient matches the info as entered while creating, it should up in the `Search results` 
- [x] For patients found that belong to homestore(logged-in store), see the home icon
- [x] For patients found that belong to other store(other than logged-in store), see the download icon
   - [x] On downloading the patient, it'll download/fetch patient details from the server
### Entering full patient information and finalising the patient
- [x] In case of no any existing patients found, opt to `Ok&Next` to proceed
- [x] Only after mandatory fields (NID, NUIC, name, DoB) are entered, the `Create` button is enabled which lets us save the patient
## Patient List
- [x] Click on each column header to test the sorting
   - [x] Sorting is ascendent or descendent. 
- [x] Test the filter fields
   - [x] Search by First name - Find patients that have the string combination you put in their first name
   - [x] Search by Last name - Find patients that have the string combination you put in their last name
   - [x] Search by id - Find patients that have the string combination you put in the National ID or NUIC 
   - [x] Try multiple fields search, each value you put in a field should combine to reduce your selection     
 - [x] Double click on a patient to see it's information
     - [x] You should see it's information
     - [x] You are able to edit the patient details.
     - [x] When clicking Ok the details are saved.
## Merge Patient
- [x] Merging two patient should reflect in the `oms` site accordingly
- [x] That should be reflected in prescription as well

**Comment by AnushaUp** [comment]
> [x] Click on each column header to test the sorting
> * [x]  Sorting is ascendent or descendent.

Load the page completely while sorting for the first time

**Comment by AnushaUp** [comment]
@clemens-msupply @mark-prins Some questions seen in patient module are:

1. Home icon is appearing in the patient even if the patient is from another store. While searching and downloading the item the home icon appears. is this expected?
![photo_2024-05-13 3 16 12 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/f056ca66-4d4b-42ce-a558-74143ce0316c)
2. It doesn't give any alert while creating and searching for existing item and it duplicate the patient
 
https://github.com/msupply-foundation/open-msupply/assets/115983430/436faa43-48c4-4ba5-8948-e1a0fe708342


4.

**Comment by clemens-msupply** [comment]
>     1. Home icon is appearing in the patient even if the patient is from another store. While searching and downloading the item the home icon appears. is this expected?

Patient is at a site not at a store. If the patient is on the current site the home icon is shown.

>     2. It doesn't give any alert while creating and searching for existing item and it duplicate the patient
> 

Yes kind of a known issue. You have to download the patient and then select the patient. There are a couple of issues with the UI, e.g. a modal on top of another modal. But maybe an easy fix is to just download the patient and then got to the patient page for the downloaded patient.

Would also be good to have a UI that works with patient search for a prescription: https://github.com/msupply-foundation/open-msupply/issues/3412
