### ISSUE TITLE
Cold Chain -> Equipment has inconsistent formatting

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3792]
## What went wrong? 😲
 

<img width="1251" alt="Screenshot 2024-05-06 at 5 22 44 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/23ac82fa-2358-4900-bdb2-bf916fdd0bdf">

- Some content in columns seems to be aligned with the title (e.g. Type & Manufacturer start on the same level) 
- And then some content seems to be skewed to the right - like Asset Number & Model
- And Non-catalogue column title is the only one that is centre-aligned, and not left-aligned

## Expected behaviour 🤔

The formatting should be consistent - all content should start on the same level as the column title, and 'non-catalogue' column title should be left-aligned. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Equipment
2. See formatting inconsistencies

## Your environment 🌱

- Open mSupply Version: v2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Windows

- Database type: ?

**Comment by roxy-dao** [comment]
Closing in favour of #4348
