### ISSUE TITLE
Admin -> Devices Settings: V2.0.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3796]
## LABEL PRINTING

- [x] IP Address field should be editable
- [x] Port number field should be editable
- [x] Label height field should be editable
- [x] Label width field should be editable
- [x] You can then click 'Test' button to print out a test label, or click 'Save' to save the changes.

## BARCODE SCANNERS (Desktop/Web Only)
- [x] You can toggle the Scanner Type between USB Serial and USB Keyboard. If USB Serial mode is selected, you will see an option to Detect one, and connect one to omSupply. The 'Detect' button should be clickable, and a barcode should be visible for your scanner to scan. 
- [x] Note that if your Client is located on a cloud, and not locally, the barcode scanner will not be recognised - you can only connect it if both client and the barcode scanner connect locally. 
- [x] If 'USB Keyboard' option is toggled, the option to detect a barcode scanner disappears. 

**Note/Tip**: To set the barcode-scanner to USB serial mode (if you're struggling with setup), you can first try and scan below code first (then connect to your oms):
<img width="473" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/7a08e9f9-53c4-4ff1-b61c-028b01312fe1">

**Comment by marthakeezy** [comment]
Just discovered I am unable to connect to the printer on Desktop or Tablet - reopening issue

https://github.com/msupply-foundation/open-msupply/assets/153777484/a884aeeb-7d4b-48b4-b369-ab01192dab39

**Comment by marthakeezy** [comment]
@mark-prins is checking to why the label printer is not working ^

**Comment by mark-prins** [comment]
PR raised to fix the issue #3850

**Comment by marthakeezy** [comment]
Moving to 'Done' since the PR above was merged this morning so going into the next build - consulted with Mark :)

**Comment by marthakeezy** [comment]
Waiting for the issue to be fixed in the next release ^ Can test then!

**Comment by marthakeezy** [comment]
Issue fixed on RC5, moving to Done :)
