### ISSUE TITLE
External Docs - Inventory Adjustments

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3798]
## Is your feature request related to a problem? Please describe 👀

External docs are needed for 2.1.0 for inventory adjustments. We should complete these sooner rather than later so they are available for testers.

**Comment by lache-melvin** [comment]
Linked PR will be https://github.com/msupply-foundation/msupply_docs/pull/38 -- currently on hold until #3656 implemented so we only need to update screenshots once 😁

**Comment by roxy-dao** [comment]
Docs are up. Closing as done (:
