### ISSUE TITLE
Sync assets fails with duplicate asset numbers

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3800]
## What went wrong? 😲
got this error while initialising the existing site

![telegram-cloud-photo-size-5-6179037344607353836-y](https://github.com/msupply-foundation/open-msupply/assets/8287373/9ba2e18b-a221-4bee-8438-e9ed9a60b530)

This is because there's a changelog entry for an asset id that doesn't exist.
I think this is because sqlite can update an id field if doing an upsert with a unique constraint on another field.
Any unique constraint failure is considered an upsert, unlike postgres which should give a unique constraint error instead.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an asset on Site A, with asset_number `ABC`
2. Create as asset on Site B, with asset_number `ABC`
3. Sync both to central server
4. Check both assets show up on Central Server (Could be different behaviour between Postgres and SQLite)

## Your environment 🌱
- Open mSupply Version: 2.0.0-RC2

- Database type: Both?

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.0.00-rc5`
To test this you'll need to either re-initialise OMS Central server as this is a database change...

- [ ] Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] Create assets on both sites with the same asset number
- [ ] Sync both sites
- [ ] Ensure both assets are available on central
- [ ] Try re-initialising the remote sites, make sure the asset records is downloaded sucessfully on initalisation.

**Comment by AnushaUp** [comment]
@jmbrunskill couldn't recreate this issue anymore👍
