### ISSUE TITLE
Internal Order Page has misaligned "Filter Items" searchbox and "Actions" drop down

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3801]
## What went wrong? 😲

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/f446874c-806c-41cd-a4ef-8ac48e22cda3)

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/01056f87-ccde-4b1b-9b50-c381c48ced04)

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/fbfa6339-c6c4-4e78-afdf-ffff0849d917)

## Expected behaviour 🤔

Things should be aligned otherwise they look bad.

(whine: I'm gonna guess certain styles are inherited, rather than added in via composition. So things have correct padding in one context but not another...)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. view an internal order

## Your environment 🌱

- Open mSupply Version: 2.0.00 on demo-open.msupply.org (IDK what RC)

**Comment by AnushaUp** [comment]
Looks good✅
