### ISSUE TITLE
Cold chain: Rename mSupply sensor type

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3806]
## Is your feature request related to a problem? Please describe 👀

Our own sensors are currently listed as `mSupply RTMD` but GAVI pointed out to us that we're not explicitly registered under WHO PQS as an RTMD but as a User Programmable Data Logger. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/1e1486f8-402b-4f7e-b71f-ed9240ff96ff)

We offer much of the functionality of an RTMD but there are some things that we lack, such as SMS messaging etc, to strictly meet the criteria. 

## Describe the solution you'd like 🎁

To avoid misleading people it would be better if we changed the sensor type to simply `mSupply`

**Comment by roxy-dao** [comment]
Closed in #4259

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC6, and the sensor type is now showing as `mSupply`. Build test passed ✅
