### ISSUE TITLE
Login shows incorrect username or password when there's an API error

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3815]
## What went wrong? 😲
![73923](https://github.com/msupply-foundation/open-msupply/assets/8287373/3cc9977c-0aa2-43f8-9463-404941d34174)

## Expected behaviour 🤔

Should show a message something like "Error communicating with server", "Unable to login due to a server error"

"Invalid username or password" is missleading, more likely to affect devs than real uses but I think this should be fixed at some point.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Turn off your backend server
2. Try to login with correct username and password
3. See error

## Your environment 🌱

- Open mSupply Version: 2.0.0-RC2

**Comment by DhanyaHerath** [comment]
Similar to https://github.com/msupply-foundation/open-msupply/issues/2945
