### ISSUE TITLE
Syncing user causes store to swap to default store

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3823]
## What went wrong? 😲
Syncing the user will cause the store to swap to the user's default store.... happened because of https://github.com/msupply-foundation/open-msupply/pull/3749 change....

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have two stores on site (one of them being the user's default store)
2. Go to sync page
3. Sync the user
4. See the store being swapped 👀 

## Your environment 🌱

- Open mSupply Version: V2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by Chris-Petty** [comment]
@roxy-dao is this related? https://github.com/msupply-foundation/open-msupply/issues/3737

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply_Demo `v2.1.0-IA-test-2`


- [ ] Go to a store that isn't the user's default store
- [ ] Go to sync page
- [ ] Click sync
- [ ] Store shouldn't change

**Comment by AnushaUp** [comment]
Couldn't recreate the mentioned isssue👍
