### ISSUE TITLE
Footer being real cosy with nav 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3827]
## What went wrong? 😲
Noticed that the requisition and internal order footer is getting real cosy with nav 😉 ... probably the same for invoices and stocktakes as well with the onHold button hugging the nav
![Screenshot 2024-05-08 at 11 47 43](https://github.com/msupply-foundation/open-msupply/assets/61820074/881ab8e1-ad1f-45ff-afed-417499b46b30)

## Expected behaviour 🤔
Be nicely displayed.. add some padding maybe? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any of the pages mentioned above
2. See the cosiness

## Your environment 🌱

- Open mSupply Version: v2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Yeah, this seems to the same for all the footers, including the buttons for Patients:

![Screenshot 2024-05-16 at 9 48 14 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/e81c4fbd-3392-4702-b0dd-790697af7668)

**Comment by marthakeezy** [comment]
Checked `Distribution -> Requisitions`, `Replenishment -> Internal Orders` & `Dispensary -> Patients` and the footer looks fine. Build test passed ✅
