### ISSUE TITLE
Inbound Shipment delivery date is updated when verified

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3829]
## What went wrong? 😲

Looks like delivery date is updated when status is changed to verified (even if inbound is already set to delivered).
This can also cause ledger discrepancy.

## Expected behaviour 🤔

Delivery date is only set when status is changed to delivered (or when delivered status is skipped like when setting straight to verified)(

## How to Reproduce 🔨

This is a date time field, and most of UI shows date, so hard to spot, fastest way to spot is through ledger tab on stock line

Create inbound, add batch, set to delivered. 
See the date time in ledger view for that stock line
Wait a minute
Set inbound as verified
See the date time in ledger view for stock line change

This is also visible as ledger discrepancy in mSupply, writing test case here for future reference for testers

Make sure stock is 0 for the item you are doing this test with
Create inbound, add batch, set to delivered. 
Create outbound, add that batch and issue some (not all) of it.
Set outbound to shipped
Go back to inbound, set to verified.
In mSupply central, log into this store, find the item, go to ledger, then print, you should see negative stock levels as per below screenshot (this is why item should be 0 at the start, to make sure other batches don't interfere with the calculation):

![Screenshot 2024-05-07 at 9 51 43 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/dda4c025-3b91-4ed0-abcc-f75230f6fcc6)

## Your environment 🌱

- Open mSupply Version: 2.1

**Comment by andreievg** [comment]
## Suggested solution

Remove index matches of statuses, use match statements, there is quite an old branch for this: https://github.com/msupply-foundation/open-msupply/commit/c0db9ecce78a9a648e61e081c112a3ab46532c41

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in Open_mSupply `v2.1.0-IA-test-2`


- [ ] Create an inbound shipment, add a line, and set it to delivered
- [ ] In view stock, check the timestamp in the ledger tab of your newly introduced stock line
- [ ] Wait at least a minute 😅 
- [ ] Set your inbound shipment to Verified
- [ ] Check the ledger tab again - the timestamp should NOT have changed

**Comment by AnushaUp** [comment]
The timestamp is set when confirming delivered
![Screenshot 2024-06-05 at 12 47 29 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/cdc3ffff-feb0-48fe-b87d-5eb26bd43a50)
