### ISSUE TITLE
Add report_builder support to include report metadata

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3830]
## Is your feature request related to a problem? Please describe 👀

There are a couple of new requirements:
- SQL reports need a way to assign permissions to a report #3383 
- Report `context` shouldn't be needed to be added manually when uploading a report https://github.com/msupply-foundation/open-msupply-reports/issues/67
- Report versioning #3718

All these need a way to add extra data to the report, e.g. permission need the om_context name or versioning needs the report version and a unique report id.

This can be done by adding a `manifest.json` file that can contain all additional metadata. If this file is provided the file will be automatically added to the `ReportManifest::entries` map. This already will work with the existing code, i.e. the manifest.json file is just another resource. This also means the manifest is also available in the report Tera template, e.g. you could print the version by accessing `res.manifest.version`.

However, it may still be useful to handle the `manifest.json` file in a special way. For example, the report `context` option should be mandatory.

### Describe alternatives you've considered 💭
Add cli flags for all new option. But this would result in lengthy and hard to manage options

### Moneyworks Jobcode 🧰

OMS:JAN24

**Comment by Chris-Petty** [comment]
@clemens-msupply I assume doing for 2.1
