### ISSUE TITLE
Outbound shipments: Cannot erase the number of packs to be issued

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3834]
## What went wrong? 😲

After inputting a number of packs to be issued, we cannot erase the number or change it to 0.

https://github.com/msupply-foundation/open-msupply/assets/132425096/15d94c54-32dc-4070-b3d7-ee05791c12a5

It happens ons Desktop app and Android

## Expected behaviour 🤔

Number should be able to be changed to 0.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Outbound shipment'
2. Click on 'new shipment'
3. Click on 'add item' and choose an item
4. Change number of packs to be issued to any number >0
5. Try to erase this number or change it to 0.
6. See error

## Your environment 🌱

- Open mSupply Version: V2.0RC3
- Legacy mSupply Central Server Version: V7.14.0

- Platform: Desktop app.

**Comment by lache-melvin** [comment]
Closed by #3814

**Comment by nisha-dangol** [comment]
The same issue exists in inbound shipment though. Backspacing the issue quantity doesn't set the value to 0 in Inbounds. Looks addressed for Outbound only? @lache-melvin

**Comment by lache-melvin** [comment]
Ah great catch, thanks Nisha, sorry yes was only addressed for outbound shipments/prescriptions. Will reopen this issue and address 🙏

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in` omSupply v2.0.00`


- [ ] Create an Internal Order
- [ ] Add an item
- [ ] Enter a requested quantity
- [ ] TEST: you should be able to backspace the quantity to 0
- [ ] Create an inbound shipment
- [ ] Add an item
- [ ] Enter a pack quantity
- [ ] TEST: you should be able to backspace the quantity to 0
- [ ] Backspace the pack size
- [ ] TEST: it should clear
- [ ] Click off the pack size field, so it loses focus
- [ ] TEST: it should reset to 1
- [ ] Create an inbound return
- [ ] Add an item
- [ ] Backspace the pack size
- [ ] TEST: it should clear
- [ ] Click off the pack size field, so it loses focus
- [ ] TEST: it should reset to 1

**Comment by nisha-dangol** [comment]
Just noticed this issue persists for tax-field under service-charges as well: #3950
