### ISSUE TITLE
V2.1.0 (3rd July)

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3840]
# Key Aims

- IGA Gap Analysis (partial in 2.1)
- Inventory Adjustments
- ~~Backend plugins~~ (2.2)
- Migration pathway from mSupply Desktop and Mobile to Open mSupply

## Deadlines (in NZT)

Date started: Thur 16 May, 20204
PR deadline: Wed 12 June, 2024
PRs merged: Wed 19 June 2024
Release: Wed 3 July 2024

**Comment by santoshkhanal12** [comment]
Cooks island is not suitable v2.0. Issues:
1. You cannot create new patients
2. The patients list just hangs
3. Prespription’s in the data file is as old before 2020. So needs proper migration
Video Reference: https://drive.google.com/file/d/1SWd5CwPY96ru3g7ai6fi1NX1lKr3Le2T/view?usp=sharing

**Comment by roxy-dao** [comment]
Released
