### ISSUE TITLE
GAPS: Frontend Code to manage population data entry

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3844]
Part of epic #3663 

## Is your feature request related to a problem? Please describe 👀
| User story  | B.2.11 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | all facilities to provide the central EPI office with the number of people they serve in their catchment area
So that… | the central EPI office can leverage the facilities' localized knowledge to build a picture of the demographics that the immunization supply chain is catering for nationally

**Solution B.2.11**
The system will provide a mechanism for facilities to enter a figure to represent the number of people they serve. 
For facilities that are not using Open mSupply central users will be able to enter the figure on their behalf. 
All figures will be aggregated at the central level and the aggregated total will serve as the ‘General population’ figure used by the demographic groups detailed in User Story B.2.2.  **_<-- after a discussion with @jmbrunskill decided that aggregation is not actually useful except for cross-referencing purposes and so we should allow central user to specify their own `General Population` value_**

---
| User story  | B.2.14 |
| :------------- | :------------- |
As a… | National EPI manager and National PHC manager
I want… | to be able to specify the expected population growth on an annual basis, for the next 5 years
So that… | the system can show me the change in cold storage situation that this growth causes for each of the next 5 years

**Solution B.3.1**
The system will allow central users to enter a percentage value to represent estimated population growth for each of the following 5 years. 
This value will be used in conjunction with the current general population aggregate total to arrive at future estimated general population total. 
This will then make it possible to estimate the national cold storage capacity demand for each of the following 5 years. 

---

UI to manage the population and population growth for a country as part of the Gaps analysis, we need a ui which dynamically updates as population, and growth rates are updated.

For this issue, we'll simply provide the UI to enter the population data, and growth rates.
A subsequent issues will add the ability to define new indicators, and save the data.

## Describe the solution you'd like 🎁

![19670](https://github.com/msupply-foundation/open-msupply/assets/8287373/48648150-e62e-4af1-bdfe-3668628299bf)

### Acceptance Criteria

- [ ] A new page should be added to the central server navigation called` Indicators Demographics`
- [ ] The new page should only be available from the central server
- [ ] The screen should open with the current year + 5 years shown along the top
- [ ] User can enter a general population figure (This will be temporary as in future it will be automatically aggregated)
- [ ] User can enter a growth rate for each of the five years shown
- [ ] Entering a new growth rate, causes the estimated future populations to update on the screen

### Additional context 💌

Part of https://github.com/msupply-foundation/open-msupply/issues/3662 and https://github.com/msupply-foundation/open-msupply/issues/3663

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by fergie-nz** [comment]
@adamdewey I'm wondering if individual rows might need different growth rates when predicting future populations and CCE requirements.

For example consider New Zealand where there might be higher numbers of immigration so population is increasing, but number of pregnant women is decreasing. In this case their growth isn't proportional.

**Comment by jmbrunskill** [comment]
> @adamdewey I'm wondering if individual rows might need different growth rates when predicting future populations and CCE requirements.
> 
> For example consider New Zealand where there might be higher numbers of immigration so population is increasing, but number of pregnant women is decreasing. In this case their growth isn't proportional.

@adamdewey and I discussed this, we decided that we don't think they need that level of detail.

**Comment by adamdewey** [comment]
Like the thought @fergie-nz - but thinking maybe best to keep things as simple as possible for now, just so we can see if we can make the tight deadline?

We could come back to it though if the product proves successful and they want to make their modelling more accurate :)
