### ISSUE TITLE
Hovering over "select all columns" shows some graphical artifact

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3853]
## What went wrong? 😲
 

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/95529c61-fb02-4ec4-a074-be9274f186b3)

I guess this is an empty tooltip. This can probably be fixed in the tooltip component?

Seen this for
- outbound shipments
- coldchain equipment
- probably others

## Expected behaviour 🤔

Don't show the empty tooltip

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. go to table view
2. hover over checkbox

## Your environment 🌱

- Open mSupply Version: develop branch

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in omSupply `V2.0.00`
- [ ] Go to a table and hover over the selection header checkbox
- [ ] Tooltip should show
