### ISSUE TITLE
CCEI module: No details in error message when creating CCE with duplicate asset numbers

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3858]
## What went wrong? 😲
The system prevents users from creating multiple CCE with the same asset number (as expected)

However the error message is unclear: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/6e60ebe1-5680-48f7-8329-5a5dc9ee15f1)

## Expected behaviour 🤔

Explain to the user explicitly why they can't create this CCE: 

`Unable to create CCE: Asset Number already exists`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a CCE with Asset Number `1`
2. Create another CCE with Asset Number `1`

## Your environment 🌱

- Open mSupply Version: V2.0.0-RC4

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in oms `v2.0.00` and msupply `v7.4.02`


- [ ] Create an equipment with asset number = 1
- [ ] Try create another equipment with asset number = 1
- [ ] See error
