### ISSUE TITLE
GAPS: Custom fields UI

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3864]
Part of epic #3660 

## Is your feature request related to a problem? Please describe 👀
* UI to display input fields for available custom fields 
* Display existing values
* Integrating with the API to save and update

Implement as NullableInput values, so that the user can clear the value if it has been set.

---

| User story  | B.1.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to classify facilities into different 'administrative levels' (e.g. Primary, Sub-National, Lowest Distribution, Service Point etc)
So that… | I can assess the current cold storage for each administrative level

**Solution B.1.1**
The system will allow central users to categorize facilities into ‘n’ customisable administrative levels. 
Each facility will only be able to belong to one administrative level. 

---
| User story  | B.1.2 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to classify facilities into different 'facility types' (e.g. National Vaccine Store, Regional Vaccine Store, Municipal Warehouse, Referral Hospital, Maternity Clinic etc)
So that… | I can assess the current cold storage by type of facility

**Solution B.1.2**
The system will allow central users to categorize facilities into ‘n’ customisable facility types. 
Each facility will only be able to belong to one facility type.

---
| User story  | B.1.3 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to classify facilities into different 'ownership types' (e.g. Government, NGO, Private, Faith-based etc)
So that… | I can assess the current cold storage for each ownership type

**Solution B.1.3**
The system will allow central users to categorize facilities into ‘n’ customisable ownership types. 
Each facility will only be able to belong to one ownership type. 

---

| User story  | B.1.5 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | all facilities to provide the central EPI office with details of the type (electricity, solar, gas etc) and availability (No availability, < 8 hours, 8-16 hours, > 16 hours) of energy infrastructure they have access to
So that… | I have an idea of the available energy infrastructure situation

**Solution B.1.5**
The system will aggregate energy infrastructure data that has been captured by facilities to the central level. 
If the system is not distributed then all facility energy infrastructure data will be input by the central user(s).

---
| User story  | B.1.5.1 |
| :------------- | :------------- |
As a… | Health Care Worker (HCW) or warehouse worker
I want… | to be able to detail the current energy infrastructure of my facility
So that… | I can respond to the request for the collection of this data

**Solution B.1.5.1**
The system will allow facility users to indicate their current energy infrastructure by choosing each type of energy source (electricity, solar, gas, kerosene) and the availability
The options to choose from will resemble: 

- Electricity
  - No availability
  - < 8 hours
  - 8-16 hours
  - \> 16 hours
- Solar
  - No availability
  - < 8 hours
  - 8-16 hours
  - \> 16 hours
- Gas
  - TBD
- Kerosene
  - TBD

### Moneyworks Jobcode 🧰

`CCEIDEV`

**Comment by lache-melvin** [comment]
Closed by #4065
