### ISSUE TITLE
Pagination for assets is fixed in one position

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3869]
## What went wrong? 😲
 
The pagination on the catalogue > assets list is not good:

https://github.com/msupply-foundation/open-msupply/assets/9192912/fccad111-fa69-45b1-b000-77c67d5a37ec

This is also an issue on the web: 

<img width="743" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/80e84a49-3a11-4a61-9a74-470bc0915334">

## Expected behaviour 🤔
Pagination should sit nicely at the bottom

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Catalogue' > 'Assets'
2. You'll need a lot of assets, these are imported on migration though, so you should have some there.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Not fixed by #3837 ?
(I guess it's the same problem, though)

**Comment by mark-prins** [comment]
yep, fixed by #3837 - just need to merge that change into 2.0.00
strange that it happened in the first place though. can't see what had changed to make the issue appear in the first place

**Comment by nisha-dangol** [comment]
Moving to Done as the issue shown in original recording looks resolved in v2.0.0 apk
