### ISSUE TITLE
Plugins endpoint is throwing an error

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3873]
## What went wrong? 😲
 

This query, run against the demo server is giving an error:

```
query plugins {
  plugins {
    config
    name
    path
  }
}
```

Response:

```
{
    "data": null,
    "errors": [
        {
            "message": "Internal error",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "plugins"
            ]
        }
    ]
}
```

For Roxy, there is also a notistack notification shown. (I'm not seeing this on demo atm tho)

## Expected behaviour 🤔
No error would be nice.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open inspector in your browser,
2. Login to the demo site

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Triage: Part of GAPS work
