### ISSUE TITLE
You can perform transactions on disabled OMS store

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3874]
## What went wrong? 😲
 

You can perform transactions on disabled store

Video Reference: https://drive.google.com/file/d/1ObJkJAH2OFDs9KQPUZYbtcj4E8-o2k4R/view?usp=share_link

## Expected behaviour 🤔
disable store means restrict any further stock transfers to the disabled store? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. mSupply datafile having open mSupply stores
2. Make sure they are visible to msupply stores 
3. Now disable the open msupply store

![Screenshot 2024-05-13 at 17 12 41](https://github.com/msupply-foundation/open-msupply/assets/117138852/af1495be-be1b-41d2-9a1b-733d4eeef058)

4. Sync, logout and login to open mSupply Sites
5. Now make Stock transfer to mSupply stores
6. You can make stock transfer, Even if the store is disabled 
(BUG)

## Additional
Can i call this severity high? .. since the `disabled` oms-store looks very active, not disabled at all

## Your environment 🌱

- Open mSupply Version: v2-00-rc5
- Legacy mSupply Central Server Version: v7-15-00-dev5

- Platform: standalone

- Database type: SQlite

**Comment by roxy-dao** [comment]
OMS doesn't implement this function D:

**Comment by roxy-dao** [comment]
We don't currently implement this in Open mSupply, and this feature will be used any time soon. So I would say Severity: High if it does get used but Priority: Low currently

**Comment by roxy-dao** [comment]
Triage: We might forget about this option and someone might use it. Shouldn't be able to log into disabled store

**Comment by andreievg** [comment]
Team Ruru to have a look at how much is involved, if it's small fix lets just bring it through, otherwise would consider closing it as there is other ways to achieve the same result

**Comment by roxy-dao** [comment]
Closed in #4255

**Comment by nisha-dangol** [comment]
## Testing
Tested in v2.1.0-rc6

- [x] in mSupply: Disable store
- [x] Sync to OMS
- [x] See that disabled store is greyed out in Store Selector in bottom left
