### ISSUE TITLE
Setting inbound return directly to `Verified` does not introduce stock

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3877]
## What went wrong? 😲
 

Setting inbound return directly to `Verified` (i.e. skipping `Delivered`) does not introduce stock

## Expected behaviour 🤔

Stock should be introduced

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an Inbound Return
2. Add at least one line
3. Set the return straight to verified
4. Check the View Stock page
5. BUG: your stock line has not be introduced!

## Your environment 🌱

- Open mSupply Version: 2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.0 exe

- [x] Create an Inbound Return
- [x] Add at least one line
- [x] Set the return straight to verified
- [x] Check the View Stock page
- [x] TEST: your stock line is there
