### ISSUE TITLE
Unable to login to open-mSupply without default store

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3881]
## What went wrong? 😲

Setup a user with login rights but no default store, try to login.
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/a5dc0443-3d8c-4c60-a46a-c453e4062345)

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/2687fd0b-1932-4c95-a1b3-d74981bb06bd)

## Expected behaviour 🤔

If default store is required, the message should clearly show that you need a default store to login.
However, preferably, the default store shouldn't be required.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1.Create an mSupply user with no default store
2. Try to login with open-mSupply

## Your environment 🌱

- Open mSupply Version: 2.0-RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Can this be added to #2945?

**Comment by mark-prins** [comment]
The default store is required. This in `REST_Authenticate`

```
QUERY([user_store];  & ; [user_store]store_default=True)
```

and changing would require an mSupply change, which has implications that I don't want to delve into right now. We'll be changing authentication with oms central anyway.

Unfortunately, mSupply isn't giving us an indication that a default store id is required. This happens

```
	: (Records in selection([user_store])=0)  // no default store set for user
	$t_response:="This user has not been assigned a default login store. See your mSupply administrator."
```

but then at the end of the method, this happens:

```
	$tDefaultStoreID:=$t_response="Account is blocked@" ? $t_response : "Failed to authenticate"
```

so.. we would have to modify mSupply to surface this error. 
Given that the default store requirement is already in the docs, and short term until the oms central server handles authentication, I'm just going to close the issue. Sorry @jmbrunskill!
