### ISSUE TITLE
Transfer report related store pref data to omSupply

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3882]
For report we would need some extra prefs from store
## Describe the solution you'd like 🎁

Add the following prefs to store_preference tables in omSupply 

   "monthlyConsumptionLookBackPeriod": "0",
    "monthsLeadTime": "0", // possibly not needed
    "monthsOverstock": 6,
    "monthsUnderstock": 3,
    "monthsItemsExpire": 3,
    "stocktakeFrequency": 1

Show this data in preference (same as info view in shipments), under reports menu (add report menu if it doesn't exist yet).

![Screenshot 2024-07-08 at 5 31 27 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/091545de-95fd-4332-8fed-b31b42494e08)

### Moneyworks Jobcode 🧰
OMS:REPT

**Comment by jmbrunskill** [comment]
Needed for GAPS too...
We need to know `Buffer Stock` could consider some re-naming in the process?
`monthsUnderstock` servers as the expected buffer stock number right.
