### ISSUE TITLE
Search filter for Catalogue item while creating new CCE looks weird

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3885]
## What went wrong? 😲
 
Search filter for `Catalogue item` while creating new CCE looks weird

## Expected behaviour 🤔
Search filter results should return exactly the correct number of results only (exclude duplicates especially like in the recording, the number of times it duplicates increases with more attempts to search)

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Do the minimum to see the Coldchain module in your view
2. Under Coldchain>Equipment, create a new asset
3. Choose a category
4. Now type some search-term for `Catalogue item`. For eg, type `emvolio`. You'll see one result at first
5. Backspace your search-term and retype it. Retype `emvolio` again
6. See error: the same entry is duplicated there
7. Backspace that again and repeat, this time 3 duplicates and so on.

## Recordings
Video reference: https://screenrec.com/share/2UbMZaidse

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc5 exe
- Legacy mSupply Central Server Version: v715-dev2

- Platform: standalone + browser(chrome)

- Database type: sqlite

**Comment by lache-melvin** [comment]
Closed by #4244

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC5, no issues found. Build test passed :) ✅
