### ISSUE TITLE
Turn off installer Codesigning SSL

### ISSUE THREAD

**Issue by raviSussol** [msupply-foundation/open-msupply#3887]
## Turn off installer Codesigning SSL

Our CodeSigning is old and we need a new one. 
@mark-prins has been chasing up the SSL authority, but this has taken longer than expected. And testers are being hold up testing latest RCs issues and their fixes.

We need Jenkins to work, so we will now build installers without SSL for now. 

We did for [mSupply](https://github.com/msupply-foundation/msupply/issues/14690). Time to do the same for the open-msupply too.

**Comment by roxy-dao** [comment]
PR closed.
