### ISSUE TITLE
The QR code doesn’t shows the correct Asset ID

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3889]
## What went wrong? 😲

The QR code doesn’t shows the correct Asset ID,

## Expected behaviour 🤔

The Asset id should match

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have Label Printer and cold chain setup
2. Go to Cold chain->Equipmets
3. Add a new asset and Print the QR of the asset
4. Note down the id of the Asset

![Screenshot 2024-05-14 at 14 33 46](https://github.com/msupply-foundation/open-msupply/assets/117138852/50c65e12-4149-44b9-97a7-1dfa6b286885)

5. Try to scan the code, but the scanning doesn't works as per comment by @AnushaUp : https://github.com/msupply-foundation/open-msupply/issues/3725#issuecomment-2109540800

QR code of asset:

![2024-05-14 14 46 00](https://github.com/msupply-foundation/open-msupply/assets/117138852/6d5b9948-1940-4b10-9001-80fb50c5ae50)

6. Now try to see the values by QR scanner
7. On scanning the above QR code you see following value `b34be4-65aa-45de-be40-011fba6dda17`
8. The asset id on step on window doesn’t match with the value of QR

Asset id in open mSupply window: `55b34be4-65aa-45de-be40-011fba6dda17`
Value seen form QR code: `b34be4-65aa-45de-be40-011fba6dda17`
(Values Mismatch)
First 2 characters has been lost.

## Your environment 🌱

- Open mSupply Version:v2.00-rc5
- Legacy mSupply Central Server Version:v7-15-00-dev5

- Platform:server, standalone

- Database type:Sqlite

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `2.00.0`


- [ ] Configure a label printer. This is in Admin > Devices > Label printer. IP address: 192.168.178.69 and other parameters are the default values
- [ ] Navigate to cold chain > equipment. Create an asset if you don't have any
- [ ] Print the QR code for the new asset (button is top right)
- [ ] Scan the QR - you can use a QR scanning app to check the value, or
- [ ] on a tablet, or desktop version, scan from the asset list view
- [ ] the full UUID should be the value of the QR code (8 digits-4 digits-4 digits-4 digits-12 digits) You can check this value against the ID using the network inspector

**Comment by AnushaUp** [comment]
After scanning it redirects to the detail page of asset👍
