### ISSUE TITLE
CCEI New asset modal: Catalogue Item search is funky

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3892]
## What went wrong? 😲
 
Investigate the cause of this odd search behaviour:

https://screenrec.com/share/2UbMZaidse

Raised by @nisha-dangol in [this comment](https://github.com/msupply-foundation/open-msupply/issues/3725#issuecomment-2107150112)

## Expected behaviour 🤔
Search should really be less odd

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Try to recreate using the steps in the screen capture.

## Your environment 🌱

- Open mSupply Version: v2.0.00 (RC)
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by adamdewey** [comment]
Maybe dupe of #3885 ?

**Comment by mark-prins** [comment]
weird is better than funky 🙏  @adamdewey
