### ISSUE TITLE
Username no longer being displayed in sidepanels

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3895]
## What went wrong? 😲
Usernames are no longer being displayed in the frontend even though the information is available

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Invoices migrating from mSupply don't seem to have a user_ID attached to them... also OG issue to force sync users https://github.com/msupply-foundation/msupply/pull/14538

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in V2.0.00-rc6


- [ ] Need an existing datafile
- [ ] Go to any invoice
- [ ] Open side panel
- [ ] If user is not known, dash should be shown

**Comment by AnushaUp** [comment]
@roxy-dao moving this to done as it couldn't be recreated 👍
