### ISSUE TITLE
Can create a patient without a patient code (but then can't find the patient again)

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#3900]
## What went wrong? 😲
 
I noticed when creating a patient that the patient code is not mandatory...so I tried creating a patient without a patient code. 
I can do this, but then I can't find the patient when I search for it. 

Am I doing something wrong?

## Expected behaviour 🤔

- Code should be mandatory (or if not mandatory, at least autopopulated) 
- I should be able to find the patient I made

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1.  Create a new patient 
2. Enter just the first name and last name, no code
3. Click create 
4. Click away from the patient (note, that message that shows up telling me I will lose any changes I have made seems misleading - I've made no changes?) 
5. Now we're back at the patient list. Look for the patient you just made - can't find it

https://github.com/msupply-foundation/open-msupply/assets/29744386/872150bc-de94-4ca3-9f80-69527eb035a5

## Your environment 🌱

- Open mSupply Version: V2.0.0 (not sure of RC) - on https://demo-open.msupply.org/login
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closing as code is required now and there is an extra step to creating the patient which isn't in the reproduction steps. 

Will need to redesign the UX for this in the near future.
