### ISSUE TITLE
No error trying to reduce stock line below available

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3903]
## What went wrong? 😲
 

If you create an inventory adjustment to reduce a stock line to below the available number of packs, you get a success snack! 

Note, the inventory is not adjusted, but you don't get any feedback as to why!

I want to reduce to 0:
![Screenshot 2024-05-15 at 12 35 05 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/51928673-e4ac-47a4-bae5-36702ee79ca6)

Oo look it worked! Oh no it didn't, new pack quantity has been reset to 30:
![Screenshot 2024-05-15 at 12 35 10 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/7767a2b5-15c7-4725-8e33-e54312092b51)

## Expected behaviour 🤔

An error snack (similar to stock takes) informing the user that some or all of this stock line is reserved for issuing, and cannot be reduced.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an Outbound Shipment
2. Add a item, and issue some stock from a stock line (note the stock line you use)
3. Go to 'View Stock'
4. Find that stock line
5. Open the `Adjust` tab of the stock line edit modal (or maybe stock will have its own page by this point hehe)
6. Adjust the number of packs to 0
7. Click save
8. BUG: see the `Inventory adjustment saved` success snack

## Your environment 🌱

- Open mSupply Version:  2.1.0
- Legacy mSupply Central Server Version: 

- Platform: Browser

- Database type:

**Comment by roxy-dao** [comment]
Closed in #4220
