### ISSUE TITLE
GAPS: Add 'Needs replacing' property

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3907]
Part of epic #3697 

## Acceptance criteria
* [x] Can designate an asset as `Needs replacing`

## Describe the solution you'd like 🎁

- Add a 'needs_replacing' property to an asset item
- Update diesel & service layer; update mutation and query
- Update UI to display checkbox for `Needs replacing`
- Able to update regardless of status of an asset

### Additional context 💌

| User story  | B.4.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to know the cold storage capacity that will be need to be replaced over the next 5 years
So that… | I have an idea of how much CCE will need to be replaced and can plan accordingly 

**Solution B.4.1**
The system will allow central users to track the number of CCE that need to be replaced over the next 5 years. 
This number will consist of: 
- Planned replacements (CCE that will reach their End-of-Life)
- Unplanned replacements (CCE that are broken and unserviceable)

| User story  | B.4.3 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | all facilities to provide me with information about any CCE that are unserviceable (permanently broken) 
So that… | we request replacements for these in our next CCEOP application 

**Solution B.4.3**
The system will provide a mechanism for facilities to flag any of their CCE as ‘Unserviceable’. 
This flag will be used for identifying ‘Unplanned replacements’ over the next 5 years. 

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by adamdewey** [comment]
I'm just wondering if we might need to separate the 'Needs replacing' flag from the functional status? 

I think it's a slightly different concept? 

Can't think of all the scenarios right now, but possibly there could be a situation where they need to be distinguishable. 

E.g. if a batch of fridges need to be recalled due to an environmental pollution risk but technically they are still keeping vaccines cold in the meantime while they wait for a replacement?

**Comment by adamdewey** [comment]
And maybe we could auto-tick the `Needs replacing` flag once a CCE reaches its End-of-Life value?

**Comment by mark-prins** [comment]
Ok, have updated the issue.
Automatically setting the property based on end of life value is nice but opens up a few complications:
- How is that set? We'd need a scheduled process to run regularly. 
- How do we let users know that this is automatically set? Can we distinguish between manually set and automatically?
- Should users be allowed to un-set if the asset is nearing end-of-life?

I think best not to set automatically, I think it brings in a few too many problems

**Comment by adamdewey** [comment]
Yeah fair points!

Ok sweet, like the idea of keeping it simple :)
