### ISSUE TITLE
GAPS: Create a lifespan property for catalogue items

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3908]
Part of epic #3697 

## Acceptance criteria
* [ ] Add a new default property for catalogue items
* [ ] Add to the import processing

## Describe the solution you'd like 🎁

Add a `lifespan` property to `asset_property` for all cold chain assets. Add this to the catalogue & asset imports. Default this value to 10 years for all asset catalogue items.

### Additional context 💌

| User story  | B.4.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to know the cold storage capacity that will be need to be replaced over the next 5 years
So that… | I have an idea of how much CCE will need to be replaced and can plan accordingly 

**Solution B.4.1**
The system will allow central users to track the number of CCE that need to be replaced over the next 5 years. 
This number will consist of: 
- Planned replacements (CCE that will reach their End-of-Life)
- Unplanned replacements (CCE that are broken and unserviceable)

| User story  | B.4.2 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify the nationally agreed expected lifespan for each type of CCE
So that… | the system can tell me when any CCE in the country are approaching the end of this lifespan and can request replacements for these in our next CCEOP application

**Solution B.4.2**
The expected lifespan for WHO PQS CCE is 10 years. 
However some countries wish to specify their own lifespan value for the CCE. 
The system will allow central users to specify a national ‘Lifespan’ value in years for each model of CCE in the Open mSupply Asset Catalogue (WHO PQS + non-WHO PQS CCE). 
This value will be used for identifying ‘Planned replacements’ over the next 5 years.

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by adamdewey** [comment]
@jmbrunskill - expectations: 

MVP: 
- A way for central users to do an initial import to set the value on the Catalogue item
- Able to re-import to edit via overwrite
- Default to 10 years if not specified during creation

Preferred: 
- A UI to be able to view/edit the value

**Comment by marthakeezy** [comment]
# 🧪 Testing

Tested as a part of V2.4.0 GAPS Feature Testing, but also testing now in `V2.4.0-RC6`: 

- [ ] Migrate an existing database with assets & asset catalogue
- [ ] Check that all existing assets get a 10 year lifespan property (in Details)
- [ ] Check that the example import shows the lifespan property
- [ ] Check that importing a record sets this lifespan correctly (You'll need to create this asset to see that.
- [ ] Not sure if updating is supported? If so be good to test that.

Build test passed - moving to Done ✅
