### ISSUE TITLE
Quantity value in Inbound cannot be updated after the stocked-in lines are touched

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3909]
## What went wrong? 😲
 
If I'm to compare the behavior with mSupply, this is definitely a big issue; but again it's oms : is it decided yet what should be the expected-behavior around modifying lines after the Inbound is delivered?

## Expected behaviour 🤔
As long as the inbound is not Verified (strictly not editable anymore), the values changed should reflect in the SoH despite the previous stocks being touched/issued out?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a inbound with a item
2. Put quantity sth like `1` and just confirm the status till `Delivered`. Your `1` stock is in which you can see under `Inventory>View Stocks`
3. Now go back to that same inbound and open the line.
4. This time, change that value to `2`.
5. See `Inventory>View Stocks`, the SoH has been updated to `2`
6. Now create a outbound with that same item-line and issue out `1` item. 
7. Confirm it as `Shipped` so that you can see the SoH now as `1` under `Inventory>View Stocks`
8. Go back to that same Inbound and try to edit the line again
9. This time, change the quan to sth like `3`. 
10. On clicking OK, it resets back to the previous value: if the value is not to be updated, maybe there should be alert or info like why the quan is not adjustable anymore suddenly

In mSupply normally, we're actually allowed to update the values in `cn` SI regardless of those stocks have been issued out or not (i.e., the change reflects the SoH as well accordingly; and obviously you can't reduce the issue-out lines from SI though). So should we expect the same in oms here? 

## Additional
[Here's the link to my database](https://drive.google.com/file/d/1M1SqTd99C6kpqAjS-2lA5RrGQ0mdmrfv/view?usp=drive_link): open the Inbound there and edit the quan and click OK; it resets to previous values everytime. 

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe + browser (chrome)

- Database type: sqlite

**Comment by mark-prins** [comment]
The API returns an error when changing the stock quantity in the inbound:

```
"updateInboundShipmentLines": [
                {
                    "id": "276b4739-0ecf-49c7-a6b3-daf4f4d36fdc",
                    "response": {
                        "__typename": "UpdateInboundShipmentLineError",
                        "error": {
                            "description": "Batch is already reserved/issued",
                            "__typename": "BatchIsReserved"
                        }
                    }
                }
            ],
```

but nothing is shown to the user.
We should show something! Given that the mutation is on save, the normal action would be a toast notification. I don't think that gives enough space, or time to read. I'd recommend a dialog - we'd have to parse the error, pick out the `__typename` and provide a translatable message

**Comment by andreievg** [comment]
@lache-melvin also wants to check the check (is it just not equals of stock line to inbound line quantity) ? so going up to 3 hours just in case

**Comment by AnushaUp** [comment]
# 🧪 Testing


Tested in `V2.3.1`
- [ ] Create a inbound with a item
- [ ] Set pack qty to 1 
- [ ] confirm the status to Delivered. 
- [ ] Now go back to that same inbound and open the line
- [ ]  change that pack qty to 2 (should save fine)
- [ ] Now create a outbound with that stock line and issue out 1 pack
- [ ] Go back to that same Inbound and try to edit the line again
- [ ] Change quantity to 3
- [ ] TEST: on save you should get an error snack saying batch is reserved

**Comment by AnushaUp** [comment]
PASSED✅
