### ISSUE TITLE
Post migration from desktop, previous 'sg' stocktakes have missing lines

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#3910]
## What went wrong? 😲
 
Post migration from desktop, previous `sg` stocktakes have missing lines

## Expected behaviour 🤔
The lines should appear as well

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. First on mSupply-OG remote-site, create two stocktakes: one `fn` and one `sg` with some lines and sync
2. Then convert to oms by resetting hardware ID & all
3. Reinitialise the new oms-site from scratch
4. In oms, the `fn` stocktakes appear with lines properly
5. Also revisit the `sg` stocktake
6. See error: The `sg` stocktake has no line at all. 

## Your environment 🌱

- Open mSupply Version: v2.0.0
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe + browser (chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
@nisha-dangol What type is the item?

**Comment by nisha-dangol** [comment]
> @nisha-dangol What type is the items? The stocktake lines can be missing because it's a type we don't handle

They were normal-type items. Rest assured, I used the same items in both `sg` and `fn` stocktakes. Problem is only for `sg` ones.

**Comment by roxy-dao** [comment]
I can't seem to reproduce it with my datafile. Can you upload yours to the drive?

**Comment by nisha-dangol** [comment]
> I can't seem to reproduce it with my datafile. Can you upload yours to the drive?

Done: https://drive.google.com/file/d/1jOYfKYs3J6N_B2kDVfv6ZPLJNlXxNDTc/view?usp=drive_link

**Comment by nisha-dangol** [comment]
> I can't seem to reproduce it with my datafile. Can you upload yours to the drive?

Here's the link to oms datafile: https://drive.google.com/file/d/1f9kWAOO3suQsRlrq3-nvl_GobfLQH5wK/view?usp=drive_link

**Comment by roxy-dao** [comment]
Sorry can I get the mSupply datafile? The item being used in the stocktake line is missing from the sqlite database, and I'm unsure why without seeing how it looks on mSupply

**Comment by nisha-dangol** [comment]
> Sorry can I get the mSupply datafile? The item being used in the stocktake line is missing from the sqlite database, and I'm unsure why without seeing how it looks on mSupply

Oh it's there on the same folder: [#3910](https://drive.google.com/drive/folders/1d5Avhp0lGg4AsEH79nvKMPHZg_CL6-2A)

**Comment by roxy-dao** [comment]
Are you sure this isn't just bad data? I checked both databases in OMS and OG and can't find the stock_line (item_line) for the item in the stocktake line

**Comment by nisha-dangol** [comment]
> I checked both databases in OMS and OG and can't find the stock_line (item_line) for the item in the stocktake line
>
There's item_line in the stocktake in the OG, which after converted/migrated to OMS now that item_line disappears in that same `sg` stocktake. 
<br>
> Are you sure this isn't just bad data?
>
I can try and replicate with a fresh/new datafile as well then will update you

**Comment by roxy-dao** [comment]
> > I checked both databases in OMS and OG and can't find the stock_line (item_line) for the item in the stocktake line
> 
> There's item_line in the stocktake in the OG, which after converted/migrated to OMS now that item_line disappears in that same `sg` stocktake.
> 
> > Are you sure this isn't just bad data?
> 
> I can try and replicate with a fresh/new datafile as well then will update you

I checked the record browser and the item_line isn't there

**Comment by nisha-dangol** [comment]
> I checked the record browser and the item_line isn't there
>
Not sure about the item_line field in record-browser>stocktake table, I'm referring to actual item lines in the stocktake.

I also created a new site & store again and the error still persists. I've also uploaded [the video-recording of the whole process](https://drive.google.com/file/d/1RLZVICMSd5wTT9AunlKpjY45sIym4fET/view?usp=drive_link) to the #3910-folder; the OG has the item lines in the stocktake, and after migration to oms, those item-lines are missing from the stocktake 
FYI, for this recording, the mSupply is in v7-14-06 and for oms, I used v2.0.2 server exe. 

**Extra note:** why is oms v2.0.2 showing version as v2.1.0?

**Comment by roxy-dao** [comment]
Okay~ found out what's happening. In mSupply, the new stock line doesn't get created until the stocktake is finalised, but in Open mSupply it gets created when the new line is added to stocktake since stock_line is a foreign constraint in stocktake_line. Will need discussion on how to solve this issue.

**Comment by andreievg** [comment]
Good to check, from memory we don't create stock line in omSupply until stocktake is finalised, i think the issues is with mSupply creating ids for the stock line that don't exist in stocktake line. We had similar issues with shipments, todo find the issue

**Comment by roxy-dao** [comment]
Closed #4554

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Have Store in mSupply
- [ ] Create stocktake with new batches
- [ ] Migrate Store to OMS site
- [ ] Integrate
- [ ] Stocktake should migrate without problem

**Comment by AnushaUp** [comment]
HI, @roxy-dao is this a bug? The date doesn't appear for the finalised one. 
![Screenshot 2024-09-04 at 2 29 49 pm](https://github.com/user-attachments/assets/fb549644-d9e2-4c83-a347-2d8cc7c6d0f5)

**Comment by mark-prins** [comment]
@AnushaUp Roxy is on holiday so I'll add my thoughts..

We don't update the finalised date because mSupply doesn't record that - so when the stocktake it transferred to omSupply we don't know what the date should be! I think that it would look better to have a wrong date than an empty one, how about we set the finalised date to be the 'New' date for those stocktakes that are finalised in mSupply?

**Comment by AnushaUp** [comment]
I guess that will be okay @mark-prins🤔

**Comment by AnushaUp** [comment]
There's no any missing line and further testing will be done [HERE](https://github.com/msupply-foundation/open-msupply/issues/4766)
