### ISSUE TITLE
GAPS: vaccine course back end: query

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3911]
Part of epic #3662 

A vaccine course briefly known as a Immunisation Program defines the relationship between a demographic and what items and schedules are due to be completed. Multiple vaccine courses can be defined within one program.

## Acceptance criteria
* [x] Table created
* [x] Service layer, diesel layer ( no filter, no sorting )
* [x] graphQL query to return list of programs

## Describe the solution you'd like 🎁

Create tables for the immunisation program and rows (IP)
Create the diesel and service layers for querying data. Default sort is by IP name, no sort or filter required. Return all columns in the service layer
Create graphQL query

```mermaid
erDiagram
    vaccine_course {
        TEXT id PK "NOT NULL"
        TEXT immunisation_program FK "REFERENCES program(id)"
        TEXT name "NOT NULL"
        TEXT demographic_indicator_id FK "NOT NULL"
        FLOAT coverage_rate "NOT NULL DEFAULT 100"
        BOOL is_active "NOT NULL DEFAULT true"
        FLOAT wastage_rate "NOT NULL DEFAULT 0"
        INT doses ""
    }
    vaccine_course_items {
        TEXT vaccine_course_id FK "NOT NULL REFERENCES vaccine_course(id)"
        TEXT item_link_id FK "NOT NULL REFERENCES item_link(id)"
    }
    vaccine_course_schedule {
        TEXT id PK "NOT NULL"
        TEXT vaccine_course_id FK "NOT NULL REFERENCES vaccine_course(id)"
        INT dose_number "NOT NULL"
        INT label "E.g. day 0, day 42, etc"
    }
    program {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"  
        TEXT master_list_id 
    }
vaccine_course ||--o{ program : ""
vaccine_course_items ||--o{ vaccine_course : ""
vaccine_course_schedule ||--o{ vaccine_course : ""
```

### Additional context 💌

| User story  | B.2.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to detail the key requirements of each individual immunization program
So that… |the cold storage demand for each immunization program can be tracked independently based on their unique set of requirements

**Solution B.2.1**

The system will provide a mechanism for central users to define an unlimited number of customisable immunization programs. 
These immunization programs will form the framework for determining estimated cold storage capacity demand. The contents of the framework are detailed in the following User Stories. 

| User story  | B.2.1.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to select which immunization programs should be included in demand calculations
So that… | I can easily run hypothetical gap analysis and compare what happens if I include a program or not in the calculations

**Solution B.2.1.1**

The system will provide a mechanism for central users to include, or not include, immunization programs when estimating cold storage capacity demand. 

| User story  | B.2.3 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify which demographic group each immunization program targets
So that… | our forecasting takes into account the number of people that require immunizing for each immunization program 

**Solution B.2.3**

The system will allow central users to associate demographic groups with immunization programs. 
Only 1 demographic group can be linked with each immunization program. 

| User story  | B.2.4 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify one or more vaccines which are required for each immunization program
So that… | our forecasting takes into account the type of vaccines involved for each immunization program

**Solution B.2.4**

The system will allow central users to associate one or multiple vaccines with each immunization program. 
The vaccines will be available to choose from the Master Data product catalogue. 
The same vaccine may be associated with more than one immunization program. 

| User story  | B.2.5 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify how many doses of each vaccine is required to fully immunize a person in the target demographic
So that… | our forecasting takes into account the total number of doses required for each immunization program

**Solution B.2.5**

The system will allow central users to specify the number of doses required to immunize the demographic group associated with each immunization program. 
This data is required to calculate the total cold storage capacity required per person per immunization program.

| User story  | B.2.6 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify a 'coverage' percentage rate for each immunization program
So that… | I can easily apply a modifier to each immunization program to reflect real-world adjustments

**Solution B.2.6**

The system will allow central users to specify a ‘coverage’ rate for each immunization program. 
The figure will default to 100% but may be modified by the central user as required to model real-world factors. 

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by adamdewey** [comment]
@mark-prins - how will we differentiate between the concepts of `Immunization programs` (e.g. 'Routine immunizations for children') and `Immunizations` (e.g. `BCG`, `HepB` etc?)

Do we need a new DB concept for `Immunizations` ?

**Comment by adamdewey** [comment]
i.e. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/a849aed0-bcbe-40be-b5dd-e722ea2bf7bc)

**Comment by jmbrunskill** [comment]
@mark-prins @adamdewey  do we need sync here or can we just limit it to central server only? Feels like a central admin task to me...

**Comment by mark-prins** [comment]
and available centrally too? as I understand it for GAPS we don't need remote facilities to even see immunisation programs - the purpose is forecasting only, right?

**Comment by adamdewey** [comment]
Yes, that's correct - intention is for planning and forecasting for GAPS

Intention for vaccination card is also for planning at the central level.
