### ISSUE TITLE
Accidentally resyncing all requisition and stock take lines in v2.0.0 migration

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3914]
## What went wrong? 😲

I haven't personally validated this, but looking at code...

The following two migrations add item_name to all stock take lines and requisition lines. This may make 10,000s of sync out records for modestly used OMS sites. We should avoid resyncing all these records (Legacy Central does the same migration, the records don't need to sync the update from remotes).

https://github.com/msupply-foundation/open-msupply/blob/main/server/repository/src/migrations/v2_00_00/requisition_line_add_item_name.rs

https://github.com/msupply-foundation/open-msupply/blob/main/server/repository/src/migrations/v2_00_00/stocktake_line_add_item_name.rs

## Expected behaviour 🤔

We don't resync all the line records if we don't need to.

We have a nice method used in 1.7.0 migration that can be used: `run_without_change_log_updates`

## How to Reproduce 🔨

1. Have a site with many many requisition lines or stocktake lines on <2.0.0
2. migrate to 2.0.0
3. All those lines are now bumped to be synced whoopsies

## Your environment 🌱
Hypothetically
- Open mSupply Version: v2.0.0
- Legacy mSupply Central Server Version: 7.14.4

- Platform: All

- Database type: Both

**Comment by adamdewey** [comment]
Seems like it maybe applies to cold chain data too?

I don't really have much requisition / stock line data but my remote site suddenly has 280,000 records to sync after upgrading to v2.0

**Comment by Chris-Petty** [comment]
> Seems like it maybe applies to cold chain data too?
> 
> I don't really have much requisition / stock line data but my remote site suddenly has 280,000 records to sync after upgrading to v2.0

That was originally looking for but didn't see anything suss....

**Comment by roxy-dao** [comment]
Closed in #3914

**Comment by AnushaUp** [comment]
@Chris-Petty While upgrading from 1.7 to 2.0.0.1 server got this view. Seems like there's no records to be sync but also values are there and once the sync button is clicked values are gone. This is seen before as well. 
Also UI seems little different from before 
<img width="956" alt="Screenshot 2024-05-23 at 1 44 55 pm" src="https://github.com/msupply-foundation/open-msupply/assets/115983430/08c681e8-c10c-4457-95c3-50519b0ca40c">
Expected
![Screenshot 2024-05-23 at 1 48 47 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/bfc8e8b4-2022-48d4-b6b2-18f0a68b0d90)

**Comment by Chris-Petty** [comment]
@AnushaUp this issue/PR hasn't touched UI at all, so if what your observing is generally the case then I'd open new issues. I wouldn't bother if navigating or reopening the window fixes it.

As for the pushed records - is the lower "expected" image the picture you took before running migration?

**Comment by AnushaUp** [comment]
@Chris-Petty The UI part was seen in tablet after upgrding from 1.7 to 2.0.0.1 bur couldn't recreate while updating from 1.7 to 2.0.0.2 but the numbers are shown for sync though.

**Comment by roxy-dao** [comment]
> @Chris-Petty The UI part was seen in tablet after upgrding from 1.7 to 2.0.0.1 bur couldn't recreate while updating from 1.7 to 2.0.0.2 but the numbers are shown for sync though.

That would be part of central server work... so should go into the central server issue that implemented this ;x
