### ISSUE TITLE
GAPS: vaccine course front end: edit

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3916]
Part of epic #3662 

## Acceptance criteria

* [ ] Coverage Rate (Numeric)
* [ ] Wastage Rate (Numeric)
* [ ] Number of doses (dose names and labels not required for this PR)

## Describe the solution you'd like 🎁
The 'create immunisation program' button is available top right. Required data must be completed before OK is enabled
After creating, show a success toast ( or an error toast on failure )
After creating, the list is refreshed
There's no delete action on the wireframe, make sure that one is added and then hooked up
the spec says 'one or more vaccines' so the wireframe needs work: likely use a datatable with the delete checkbox / action
Prompt to warn people before deleting a program

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/8ec89911-31a3-4616-ba2c-0610d69845d1)

### Additional context 💌

| User story  | B.2.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to detail the key requirements of each individual immunization program
So that… |the cold storage demand for each immunization program can be tracked independently based on their unique set of requirements

**Solution B.2.1**

The system will provide a mechanism for central users to define an unlimited number of customisable immunization programs. 
These immunization programs will form the framework for determining estimated cold storage capacity demand. The contents of the framework are detailed in the following User Stories. 

| User story  | B.2.1.1 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to select which immunization programs should be included in demand calculations
So that… | I can easily run hypothetical gap analysis and compare what happens if I include a program or not in the calculations

**Solution B.2.1.1**

The system will provide a mechanism for central users to include, or not include, immunization programs when estimating cold storage capacity demand. 

| User story  | B.2.3 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify which demographic group each immunization program targets
So that… | our forecasting takes into account the number of people that require immunizing for each immunization program 

**Solution B.2.3**

The system will allow central users to associate demographic groups with immunization programs. 
Only 1 demographic group can be linked with each immunization program. 

| User story  | B.2.4 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify one or more vaccines which are required for each immunization program
So that… | our forecasting takes into account the type of vaccines involved for each immunization program

**Solution B.2.4**

The system will allow central users to associate one or multiple vaccines with each immunization program. 
The vaccines will be available to choose from the Master Data product catalogue. 
The same vaccine may be associated with more than one immunization program. 

| User story  | B.2.5 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify how many doses of each vaccine is required to fully immunize a person in the target demographic
So that… | our forecasting takes into account the total number of doses required for each immunization program

**Solution B.2.5**

The system will allow central users to specify the number of doses required to immunize the demographic group associated with each immunization program. 
This data is required to calculate the total cold storage capacity required per person per immunization program.

| User story  | B.2.6 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to specify a 'coverage' percentage rate for each immunization program
So that… | I can easily apply a modifier to each immunization program to reflect real-world adjustments

**Solution B.2.6**

The system will allow central users to specify a ‘coverage’ rate for each immunization program. 
The figure will default to 100% but may be modified by the central user as required to model real-world factors. 

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by fergie-nz** [comment]
Add dose number label for schedule mini table (this already in database schema)

'label' field

**Comment by fergie-nz** [comment]
Also add wastage rate field defaulting to 0

Coverage default to 100
