### ISSUE TITLE
GAPS: Storage and query for demographic data

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3921]
Part of epic #3662 

## Acceptance criteria
* [ ] Able to query for available demographic indicators
* [ ] Able to query for demographic projection numbers

## Describe the solution you'd like 🎁

Not certain that we want a table for the projection numbers. This could be created as a plugin and the data stored as JSON in the plugin data table. 

Create tables
* diesel layer; default sort by name for demographic indicators - no other sort or filter required
* service layer
graphQL query for indicators
graphQL query for demographic projections

**Database diagram**
```mermaid
erDiagram
    demographic_indicator {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT base_year "NOT NULL"
        TEXT base_population "NOT NULL"
        FLOAT population_percentage "NOT NULL"
        FLOAT year_1_projection "NOT NULL"
        FLOAT year_2_projection "NOT NULL"
        FLOAT year_3_projection "NOT NULL"
        FLOAT year_4_projection "NOT NULL"
        FLOAT year_5_projection "NOT NULL"
    }
    demographic_projection {
        TEXT id PK "NOT NULL"
        TEXT base_year "NOT NULL"
        FLOAT year_1 "NOT NULL"
        FLOAT year_2 "NOT NULL"
        FLOAT year_3 "NOT NULL"
        FLOAT year_4 "NOT NULL"
        FLOAT year_5 "NOT NULL"
    }
```

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by fergie-nz** [comment]
I'm wondering about permissions and service layer checks for this.

I wonder do I need anything other than isServerAdmin? Given that this will only be available on central server.

Will other users have access to central server?

**Comment by adamdewey** [comment]
It might be an idea to put it behind a permission (not necessarily a GAPS-named one as demographics might be used by other functionality in the future)

Currently there would be regular users using the central server unless a dummy 'National' store is set up to segregate central config from regular CMS operational functionality. But there's no guarantee this would happen - in which case it would be nice to restrict which users are able to access it (the information isn't very sensitive but it would be annoying if someone edited the figures)
