### ISSUE TITLE
GAPS: Specify item variants that should be bundled with other item variants

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3923]
Part of epic #3662 

## Acceptance criteria
* [ ] Able to record items which should be bundled with a particular item variant

## Describe the solution you'd like 🎁
On central server, add another tab to the item detail page.
This lists all items which should be bundled with the current item.
Have the options to 
* add an item
* remove an item
* specify the quantity when adding a bundled item or editing an existing bundled item

### Additional context 💌

| User story  | B.2.9 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify that each type of vaccine should be 'bundled' with diluents and / or syringes in certain ratios
So that… | any additional cold storage requirements can be taken into account if the diluents need to be stored cold too (and any additional dry storage requirements for syringes can be known too) 

**Solution B.2.9**

The system will allow central users to specify ‘Bundling’ rates for vaccines in the Master Data product catalogue. 
An unlimited number of other products from the Master Data product catalogue may be ‘bundled’ with vaccines. 
For each ‘bundled’ product the central user will specify the ratio in which they are bundled. 
The default ratio will be 1:1

Note: we need to be clear that bundling is used for storage estimate needs and will not automatically update your shipments with bundled items. Can we add an info note on the page when editing bundled items please

### Moneyworks Jobcode 🧰
`CCEIDEV`

**Comment by adamdewey** [comment]
So here the quantity should be a ratio, which could be < or > than 1:1

Example 1

1 vial of `Vaccine B` should be bundled with 10 units of `Syringe 1` - **Ratio: 1:10**
(assuming base units of each are vial and unit respectively)

Example 2

1 vial of `Vaccine B` should be bundled with 0.5 bottles of `Diluent 1` - **Ratio = 2:1** 
(assuming base units of each are vial and bottle respectively)

The idea being that these ratios could be used for: 

- GAPS calculations
- Distribution (possibly)
- Procurement module (in the future)

**Comment by mark-prins** [comment]
Yes, I was thinking to have a decimal value, so you would enter `10` for the first example and `0.5` in the second.

Do you think entering as a ratio would be easier to understand though? Me, I'm mentally converting the ratio to a fraction / decimal.. so I find it easier to enter it as numbers, like you have in the initial part of the example:

**Vaccine B**
Bundled with
|    Item    |  Quantity  |   Unit   |
|----------|---------:|--------|
| Syringe 1 |      10      | Unit     |
| Diluent 1  |      0.5    | Bottle   |


would you rather something like this?

**Vaccine B**
Bundled with
|    Item    |  Ratio  |   Unit   |
|----------|---------:|--------|
| Syringe 1 |      1:10   | Unit     |
| Diluent 1  |      2:1    | Bottle   |

**Comment by adamdewey** [comment]
Ah, no I think your decimal idea is clearer! 

Just as long as they know they can enter decimals :)

**Comment by jmbrunskill** [comment]
@mark-prins is this one ready to go? Or more design needed?

**Comment by mark-prins** [comment]
I think it's ready to go - should be enough detail in here to begin.

**Comment by adamdewey** [comment]
I'm looking through the WHO PQS vaccines list and the bundling actually needs to occur at the item variant level..

See example: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/a1381b50-e690-443c-a62e-8b0a71499aa2)

So we would need to bundle item variants to item variants.

**Comment by mark-prins** [comment]
Refinement: we'll leave up to the implementing team to refine further and report back to the refinement team if there are decisions to confirm

**Comment by lache-melvin** [comment]
From Item > Variants, select +bundle:
![Image](https://github.com/user-attachments/assets/6e2571d3-003c-4781-9f5c-32ab7cbe9661)

Select the item to bundle with, and configure the ratio:
![Image](https://github.com/user-attachments/assets/47daf5ca-9cfe-46ab-8f13-ab0f8b71afc5)
![Image](https://github.com/user-attachments/assets/2633fdb4-1637-4797-99cb-39ab5cba6785)

No designs yet for _display_ of the bundled items, but understanding is:

- On Vaccine A, show list of bundled items and their ratios (ratio display TBC?) e.g.
  - Diluent A (0.5)
  - Syringe (1)
- On Diluent A - show "bundled with Vaccine A (2)" (or however we display this) & disable bundling (so we don't end up with nested bundled items)

**Comment by lache-melvin** [comment]
I think simplest option would be something like:

```mermaid
erDiagram
    item_variant {
        TEXT id PK "NOT NULL"
    }
    bundled_item {
        TEXT id PK "NOT NULL"
        TEXT primary_item_variant_id FK "NOT NULL REFERENCES item_variant(id)"
        TEXT secondary_item_variant_id FK "NOT NULL REFERENCES item_variant(id)"
        DOUBLE primary_item_ratio "NOT NULL"
        DOUBLE secondary_item_ratio "NOT NULL"
    }
   

bundled_item }o--o{ item_variant : ""
```

Possibly should also store item (link) ids? Maybe we can get away without it, would need to join on variant anyway and that would have the item id?

Thoughts @andreievg @jmbrunskill?

**Comment by jmbrunskill** [comment]
Do we need the `primary_item_ratio` I would have assumed it's a single ratio `Primary:Secondary`. Primary should always be 1?

So if you need 10 syringes per vaccine via, you'd have 10

This design means we need to create item_variants for all our bundled items even if we don't need/want variants.
I think that's ok, but might be annoying...

**Comment by jmbrunskill** [comment]
Suggested Naming improvements to clarify purpose
`principal_item_variant_id` and `bundled_item_variant_id`

**Comment by lache-melvin** [comment]
Updated the diagram, thanks 🙏
