### ISSUE TITLE
Scrollbar is not fixed in outbound & prescription window

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#3926]
## What went wrong? 😲
 
Scrollbar in outbound & prescription window looks very funny to me
Can I call this high-severity: really looks weird

## Expected behaviour 🤔
Scrollbar should be fixed at bottom always

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Either create a new outbound or a prescription
2. Add 1 item and some values
3. See error: the scrollbar is way up there
<img width="1184" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/a22013b1-aa01-45f7-8bcb-8afe3860f189">

Note: Android view looks good; I'm noticing only in browser(chrome) & desktop app

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe, browser (chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
Wouldn't call this high... it does look weird but it doesn't affect the workflow at all 👀

**Comment by marthakeezy** [comment]
Scroll bar does not seem to appear for tablet at all now - is this expected behaviour?

https://github.com/user-attachments/assets/83595e28-cbc3-4ed5-9d58-3c6c58960351

**Comment by roxy-dao** [comment]
Yes that's fine. The vertical scroll is browser behaviour

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC3, scroll works fine on browser in prescriptions & outbound shipments - moving to Done ✅
