### ISSUE TITLE
Equipment window always show equipment-ID rather than proper equipment-name on the first time

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#3928]
## What went wrong? 😲
 
I've seen this multiple times: in the equipment window, on first load, it always shows the equipment-ID instead of name. On opening again, the next time it loads the proper name. Every single time.

## Expected behaviour 🤔
it should always show the proper equipment name not its id

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to Coldchain>Equipments
2. Have some equipments created already
3. OPen say Equipment1.
4. See error: it'll show ID at first.
5. Go back and open same Equipment1 again.
6. This time, it shows proper name
7. Now logout the session or if in browser, just refresh the page
8. Do same as above; you'll see the equipment-ID everytime on the first load

## Recording reference

https://github.com/msupply-foundation/open-msupply/assets/59193490/bdcd5a4a-f4b7-4b04-8427-fb6a793f3bf6

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-02

- Platform: server exe , browser (chrome) , desktop-exe

- Database type: sqlite

**Comment by roxy-dao** [comment]
Shows equipment number on first load for me. Cannot reproduce
