### ISSUE TITLE
Item name is cut off in requisition line edit modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3934]
## What went wrong? 😲
 

Per comment in [this issue](https://github.com/msupply-foundation/open-msupply/issues/3540#issuecomment-2114865474)

Item name is cut off, with no tooltip to see the full name:
![image](https://github.com/msupply-foundation/open-msupply/assets/55115239/f2beeaf7-55b0-4ba5-bb03-42420c3e1e43)

## Expected behaviour 🤔

There is a tooltip for long item names

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Requisitions
2. Click on a requisition line with a long item name
3. See the name is cut off
4. You can't hover to see the full name

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform: browser/tablet

- Database type:

**Comment by roxy-dao** [comment]
Important for users to be able to see the full name of an item since sometimes they put the measurements in the item name 😆

**Comment by andreievg** [comment]
I added label needs design, then got tapped on a shoulder to ask why, then i realised that the issue suggests tooltip for now, which would work for the time being but we also need mobile friendly tooltip. I kind of still think this issue needs design, not sure tooltip would solve this issue for mobile.

I suggest we just display item name at the top of the modal, similar to other edit item modals

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `v2.1.0-rc1`


- [ ] Have an item with a very long item name
- [ ] From Store A: Create an Internal Order to Store B with that item
- [ ] Go to Store B: View Requisition
- [ ] Click on line
- [ ] Hover over item name
