### ISSUE TITLE
Pruned stocktake placeholder lines still update stock line info

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3935]
## What went wrong? 😲
 

Changing other fields on a placeholder stocktake line (where counted # packs is not entered) will edit the related stock line, even though that placeholder line is removed from the stocktake when finalised:

https://github.com/msupply-foundation/open-msupply/assets/55115239/5192612b-f8b4-434f-b3de-d956a9758e92

## Expected behaviour 🤔

EITHER:
- Once you make a change to a stock line (whether that's counted packs, or other stock line info), it goes from placeholder line (blue) to actual stocktake line (black), and is retained in the finalised stocktake.
- Changes to stock line data aren't made by lines that get removed from stocktake, i.e. unless counted # packs is set (though this could result in loss of entered info?)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add a stocktake
2. Add a line
3. Update some other stock line info but don't touch counted packs
4. Verify the stocktake
5. That stocktake line is removed from your stocktake
6. in View Stock page, see stock info has been updated

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
daily triage: A bit mixed about severity on this one, somewhere between 'normal' and 'high'. Not going to 'high' because even though the line disappears, the adjustment is made, and it should be recorded in log ? (@lache-melvin is it recorded in log ?).

**Comment by lache-melvin** [comment]
> (@lache-melvin is it recorded in log ?).

The activity log for the stock line? No, I actually don't think any of the changes from a stocktake are captured against the stock line 👀 Except for inventory adjustment, we can see that in ledger... separate issue?

**Comment by andreievg** [comment]
> Separate issue?

🙏

**Comment by lache-melvin** [comment]
> > Separate issue?
> 
> 🙏

For reference: #3947

**Comment by roxy-dao** [comment]
Triage: Stocktake should only be for stocktake, we now have inventory adjustments for changing stock line so should use that if user wants to change stock details

**Comment by lache-melvin** [comment]
Closed by #4276

**Comment by nisha-dangol** [comment]
## Testing
Tested in v2.1.0-rc6

- [x] Create a stocktake
- [x] Add a line for a given batch - change some batch info (batch name, expiry..) but DO NOT enter a counted # packs
- [x] Add some lines  counted packs for good measure?
- [x] Line with no counted packs shows in the blue/placeholder state in the list
- [x] Finalise the stocktake
- [x] The line has been removed
- [x] Go to view stock, find the stock line that you were updating
- [x] The updates have NOT been applied

Was tested as part of #3947 as well
