### ISSUE TITLE
You can finalise a stocktake with only placeholder lines

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3936]
## What went wrong? 😲
 

New stocktake, only generated placeholder lines: 
![Screenshot 2024-05-17 at 4 37 15 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/909bb402-d744-4295-bec4-c829a4dc1d6c)

Click finalise, you now have empty stocktake!
![Screenshot 2024-05-17 at 4 37 25 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/c66ab1ad-49af-4838-8249-bb85b12601a8)

## Expected behaviour 🤔

To be consistent with other areas of the app, you shouldn't be able to finalise to an empty stocktake. Should be an error/warning if only placeholder rows are present. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create new stocktake from a master list
2. Click finalise
3. Finalised stocktake is empty

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Low severity, since minor impact, leaving for fortnightly triage

**Comment by roxy-dao** [comment]
Triage: Check other areas as well

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC9 on Desktop, works as expected - moving to Done ✅
