### ISSUE TITLE
Remove central server indication on logo

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3941]
## Is your feature request related to a problem? Please describe 👀

This was a quick implementation and has not had good feedback:

![Screenshot 2024-05-17 at 12 35 41 PM](https://github.com/msupply-foundation/open-msupply/assets/9192912/925de8a2-28b3-440b-a21f-9c1e21c54bc9)

Even less popular is the collapsed-menu version:

![Screenshot 2024-05-17 at 12 35 47 PM](https://github.com/msupply-foundation/open-msupply/assets/9192912/7274999f-d786-46b9-b657-3c09db4d34d5)

## Describe the solution you'd like 🎁
Remove this - only the footer is needed

**Comment by santoshkhanal12** [comment]
Tested on `v2.1.00`

# 🧪 Testing



- [x] Run the site as central server and see if the drawer icon has the label
- [x] The other indicators remain (footer, login page, Admin page)

![Screenshot 2024-06-10 at 15 07 13](https://github.com/msupply-foundation/open-msupply/assets/117138852/da8e2127-9846-4604-ae42-96724d19bbc1)
