### ISSUE TITLE
Stock line changes from stocktake not captured in activity log

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3947]
## What went wrong? 😲

If you edit stock line info (e.g. expiry date, cost price...) from the `View Stock` page, editing the stock line directly, then each of those changes are captured in the log tab:

![Screenshot 2024-05-20 at 4 53 42 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/0a9842f5-16c8-49f9-9d96-337c4b9ab02e)

However, there is also the ability to edit this information during a stocktake. These are not recorded... 

I updated the batch name for this stock line via stocktake, no log:
![Screenshot 2024-05-20 at 5 03 11 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/39da63e5-ff0c-4e69-95e7-157ee4377a0d)

Note that when the stock level/number of packs is changed, we do have a trail of that from the ledger tab. This is just for changes to the additional stock line info. 

## Expected behaviour 🤔

Changes to stock line information are logged, regardless of where the changes are made.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new stocktake with at least one line
2. Click on that stocktake line to open the edit modal
3. Change some data for that stock line (e.g. change the batch name)
4. Click OK, then finalise the stocktake
5. In the `View stock` page, find the stock line you updated
6. The batch name should be updated
7. Go to the log tab for that stock line
8. BUG: there is no log for the change

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform: 

- Database type:

**Comment by roxy-dao** [comment]
Stocktake changes no longer update if line isn't counted #4276. Closing.

**Comment by roxy-dao** [comment]
Closed in #4328

**Comment by nisha-dangol** [comment]
## Tests
Tested in v2.1.0-rc6

- [x] Create a stocktake
- [x] Change the details of a stock line (must count stock as well)
- [x] Finalise
- [x] Go to Stock Log (Should see changes have been logged)

In case while changing the details of a stock, stocks are not counted (i.e., no difference from snapshot value), any details changed(like batch, price, expiry, etc) will not be affected, which is logically correct, so PASS
