### ISSUE TITLE
Issues with adding service charges with tax

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3949]
## Describe the bug 😲
Just noticed that trying to add tax in service-charges is not accepted directly 

## To Reproduce ⬇️
Steps to reproduce the behaviour:
1. Have some service items set up in your datafile
2. Create a outbound
3. Add some lines (good to have price values)
4. Now Add a service item and add amount first
5. Switch to `Tax` field and enter value like `1` and click OK
6. See error: it doesn't save at all
7. Delete that service-charge entry
8. Add same service-item again
9. Add amount and this time, don't put any value under `tax` field and save. It saves
10. Open that service-charge line again
11. This time, add your `1` value to the `tax` field. This time, it saves.

## Expected behaviour 🤔
service-charge entry should be smooth

## Screenshots 📸

https://github.com/msupply-foundation/msupply/assets/59193490/ff9e2a07-d0f2-41d2-adec-9a86a4203969

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe, apk
- Legacy mSupply Central Server Version: v7-14-6

- Platform: server exe + browser (chrome)

- Database type: sqlite

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.1 exe

- [x] Have some service items configured
- [x] Create an outbound shipment
- [x] Add some lines
- [x] In more details, add a service item
- [x] Enter amount and tax percentage
- [x] Click OK
- [x] TEST: the service charge saves as expected, you can see the updated value in Pricing section
I notice that in `Tax` field, you can only enter 2 digit (for decimals as well) which I won't call it a bug since it doesn't make sense to enter 3-digit values like `123` as tax percentage either. 

Just a small question @lache-melvin : Is it expected that we can enter the same service-item entry multiple times? 
<img width="874" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/f10e596e-1bbe-4790-bde4-c7e56c580612">

**Comment by lache-melvin** [comment]
> Just a small question @lache-melvin : Is it expected that we can enter the same service-item entry multiple times?

@nisha-dangol Yep that's expected at least for now, thanks Nisha! 🙏
