### ISSUE TITLE
Cannot backspace the value to 0 in tax-field of service-charges

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3950]
## What went wrong? 😲
When you try to backspace the value of `tax` field under service-charges, notice that you simply can't
Also try inputting numbers like 123, it looks weird.

## Expected behaviour 🤔
value should set to 0 (not 1) on full backspace

## How to Reproduce 🔨
Steps to reproduce the behaviour:

1. Have some service items set up
2. Create a outbound and add lines
3. Enter a service-charge
4. Add some values to `tax` field
5. Backspace it.
6. See error: it simply doesn't reset to 0 at all. Similar issue: #3834 

## Screenshots

https://github.com/msupply-foundation/open-msupply/assets/59193490/bb08e75e-1a80-4b25-bfa4-a101c2311b83

## Your environment 🌱

- Open mSupply Version: v2.0.0
- Legacy mSupply Central Server Version: v7-14-06

- Platform: browser (chrome), apk

- Database type: sqlite

**Comment by andreievg** [comment]
Setting time as 4hours, to go through other inputs

**Comment by lache-melvin** [comment]
Closed by #3962

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.1 exe

- [x] In an Inbound Shipment, add a service charge
- [x] Enter a value in tax field, then backspace, you should be able to reset to 0
- [x] In an Outbound Shipment, add a service charge
- [x] Enter a value in tax field, then backspace, you should be able to reset to 0
- [x] In inbound/outbound returns & shipments, and prescriptions, validate still can clear all inputs back to 0
