### ISSUE TITLE
Problem in openmSupply STANDALONE with certs

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3951]
## What went wrong? 😲

There's some problem oms STANDALONE like this similar issue https://github.com/msupply-foundation/open-msupply/issues/3395 but every time occuring in standalone application ONLY.
![Screenshot 2024-05-20 at 5 42 43 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/263a1996-9d6a-404f-b187-a36b9580c9fc)

Note: It's working fine for browser; the problem is ONLY for desktop

https://github.com/msupply-foundation/open-msupply/assets/115983430/fda91021-5b69-447e-8dae-06edea9477f2

And when we just close the desktop application then got this error message
![Screenshot 2024-05-20 at 12 46 54 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/e4d3941e-2561-4ca6-8cfa-90e3c7ffb35e)
and noticed the same error while cleaning the datas also the developer tools doesn't work
![Screenshot 2024-05-21 at 12 31 24 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/38489a7d-018e-4abd-a390-dd09eed3c1b3)

## Expected behaviour 🤔

application should run smoothly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Try installing stand alone 
2. Setup oms central or remote oms site
3. See error
4. It doesn't get server
## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
Hi @andreievg @roxy-dao I've updated the description on this issue.

**Comment by andreievg** [comment]
@marthakeezy can you please check this with the latest desktop? I'll also have a go at replicating today

**Comment by andreievg** [comment]
I just installed Open_mSupply_Standalone_v2.0.00-rc5-beta-without-codesign.exe, on a fresh cloud server, it works fine for me ¯\_(ツ)_/¯

**Comment by roxy-dao** [comment]
Closing as can't use Standalone for central OMS.
