### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3954]
## What went wrong? 😲
Documentation links are broken

## Expected behaviour 🤔
Should lead to the correct documentation pages

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #3954

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.1 exe
- [x] Go to dashboard, assets, monitoring, sensors and equipment and make sure they all lead to the right doc pages
- [x] Checked for others as well: they too look good to me
