### ISSUE TITLE
Tax Edit modal value is not updated if you edit tax percentage from service line edit modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3964]
## What went wrong? 😲

Tax Edit modal value does not get updated when we edit the tax percentage via the service line edit modal - only updates on refresh:

https://github.com/msupply-foundation/open-msupply/assets/55115239/6903b945-78e4-42ba-8663-1e2af8d8be66

Same for both inbound and outbound shipments.

## Expected behaviour 🤔

Tax Edit modal reflects latest tax percentage immediately.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an Outbound shipment
2. Add a service charge
3. Set a tax percentage
4. Then open tax edit modal
5. See error: tax percentage does not reflect what you entered in the service charge edit modal

## Your environment 🌱

- Open mSupply Version: 2.0.0
- Legacy mSupply Central Server Version: 7.14

- Platform: Browser

- Database type: PG

## Additional context

[TaxEdit](https://github.com/msupply-foundation/open-msupply/blob/main/client/packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx#L17) modal uses state, which is not updated/invalidated when we save the service charges. Easiest way is probably to only mount the tax edit modal (with the useState) when we click the open/edit button, so that the state is set with a fresh value. 

Might also be a nice chance to consolidate Inbound and Outbound TaxEdit modals to be shared... they are identical, and I can imagine us wanting to include service charges in returns at some point too? 👀

**Comment by andreievg** [comment]
daily triage: Normal severity because the tax is still updated (i.e. display vs logical bug)

**Comment by mark-prins** [comment]
reluctantly moving out of 2.2 even though it's a quick fix and is bad.
not many users currently using tax

**Comment by regotaina** [comment]
Looks like it's been fixed no RC6, at least I can save it now. I asked @AnushaUp to confirm.

**Comment by regotaina** [comment]
Tested on RC5
Desktop app

- [x] Have service item in master list
- [x] Go to an Outbound shipment
- [x] Add a service charge
- [x] Set a tax percentage
- [x] Then open tax edit modal

Passed the test 👍
