### ISSUE TITLE
The tax-value from mSupply is not mapped correctly to oms

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3965]
## What went wrong? 😲
The tax-value from mSupply is not mapped correctly to oms
..and also issues with mapping sub-total value from mSupply 

Severity depends on how frequent tax is actually used; setting to Normal for now

## Expected behaviour 🤔
Map the tax values from mSupply correctly? 

## How to Reproduce 🔨
Steps to reproduce the behaviour:

1. Do the minimum to enable tax in mSuppy store (Pref>General>Default tax rate values)
2. Create some CI (outbound); add lines and there will be tax values as per the tax rate entered in prefs
<img width="1076" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/eb9f75a3-d82c-49ad-9b1c-b691d6e04dec">

3. Sync
4. Now we decide to switch from mSupply to oms
5. Reset all hardware ID's & all for that above store's site
6. Initialise that site as oms-site
7. Login and open that same outbound
<img width="1488" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/6aa99043-8cc2-4a2d-a252-9c4ab35d7ee2">

8. See error: oms totally discards the tax value
9. And another error: After migration, the sub-total value from mSupply is showing incorrectly as `Foreign Currency Total` instead of `Grand total`
<img width="1485" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/23cf0685-ce4c-4739-aec0-699eb3bb8aee">

## Addtional
From https://github.com/msupply-foundation/open-msupply/issues/3018#issuecomment-2120010903

## Your environment 🌱

- Open mSupply Version: v2.0.0 exe
- Legacy mSupply Central Server Version: v7-14-06

- Platform: server exe, browser (chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
Closing in favour of #3957 since tax isn't the only value being mapped incorrectly
