### ISSUE TITLE
Issue with Desktop app - SSL error

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3966]
## What went wrong? 😲

Can access the server from browser, but on Desktop app it's coming up an SSL error. That's how it looks like from devtools:

<img width="997" alt="Screenshot 2024-05-21 at 4 35 30 PM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/60563420-b39c-47e3-ae52-e48fb666a7b0">

## Your environment 🌱

- Open mSupply Version: V2.0.0
- Legacy mSupply Central Server Version: V7.14.4

- Platform: Desktop app (windows)

**Comment by andreievg** [comment]
daily triage: it sounds like the same issue, when we have name cert on omSupply server and trying to access that server with omSupply client. It's kind of an edge case for now, we don't really expect to be connecting to name cert servers (cloud servers) with omSupply client, just with the browser.

During testing meeting this was raised, and there were some miscoms about how and where different omSupply apps should work, i added this issue to docs: https://github.com/msupply-foundation/msupply_docs/issues/42

**Comment by andreievg** [comment]
Will wait for main triage meeting to confirm my assumption about the named cert

**Comment by roxy-dao** [comment]
Only a use case for testers

**Comment by andreievg** [comment]
> Only a use case for testers

The docs should help clarify the use case for desktop client
