### ISSUE TITLE
Pricing tab of stocktake shows NaN for items with no stock

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3968]
## What went wrong? 😲

When creating a stocktake from a filter (i.e. from master list), placeholder lines for items with no stock on hand show pricing as `$NaN`:

![Screenshot 2024-05-21 at 5 58 22 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/a6f9c5de-680a-4554-a3ad-a7e88def41f1)

## Expected behaviour 🤔

Show `$0.00` (as is the case when you select the `Add Batch` button)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a stocktake from a master list
2. Click on a row where snapshot number of packs is 0
3. Go to pricing tab
4. See error: NaN instead of 0.00

## Your environment 🌱

- Open mSupply Version: 2.0.0
- Legacy mSupply Central Server Version: 7.14

- Platform: browser

- Database type: PG

**Comment by andreievg** [comment]
daily triage, i think this deserve a hot fix, looks like the system is somewhat broken, with NaN values

**Comment by roxy-dao** [comment]
But everything is still working even if it shows NaN, so I don't think it's that urgent to throw it into a hotfix?

**Comment by CarlosNZ** [comment]
> But everything is still working even if it shows NaN, so I don't think it's that urgent to throw it into a hotfix?

One liner: #3975 ;)

**Comment by roxy-dao** [comment]
Can you check that #3981 is fixed with this as well @CarlosNZ?

**Comment by CarlosNZ** [comment]
> Can you check that #3981 is fixed with this as well @CarlosNZ?

@roxy-dao I did, it's not ☹️ 

Different component I think, but should still be quite simple to fix.

**Comment by lache-melvin** [comment]
Closed by #3975

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.0.02`
- Start a new stocktake from a master list (all items probably)
- Find a stock line that has a "Snapshot Packs" value of 0
- Open it, go to pricing tab
- Should display `$0.00` for both prices
