### ISSUE TITLE
Refactor Asset Catalogue Properties, to work like Asset Properties

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#3971]
## The suggestion

Asset Catalogue Properties were created with two tables, one to record the Available properties, and one to store the data associated with the property. However after further discussions we decided to store the data for assets in a JSON field on the actual asset itself. This simplifies sync and is less maintenance overhead.

For consistency we should refactor Asset Catalogue Properties to work the same way.

### Why should we invest time in this?

Having two different patterns in the code base 

### Are there any risks associated with this change?

This is new functionality so no customers are using this yet.

### How much effort is required?

 Around 1 day of effort including testing

### Agreed Solution

- [x] No Migration of old data (as no customers using it yet, and all existing data can be re-created in the new format)
- [x] Migration to add `properties` to `asset_catalogue_item`
- [x] Drop asset_catalogue_item properties
- [x] Handle sync changes
- [x] Update Frontend code to use new fields

**Comment by adamdewey** [comment]
@jmbrunskill Just checking - will this allow users to set these properties for non-catalogue assets too?

For example, they would need to be able to set the same properties for a non-catalogue asset of Category `Refrigerators and freezers` as would be captured for a catalogue asset of the same Category. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/06aef15e-6feb-44ed-b8b7-774e41c2d67f)

**Comment by jmbrunskill** [comment]
> @jmbrunskill Just checking - will this allow users to set these properties for non-catalogue assets too?
> 
> For example, they would need to be able to set the same properties for a non-catalogue asset of Category `Refrigerators and freezers` as would be captured for a catalogue asset of the same Category.

Yes that's one the reasons to change how we did this...

**Comment by adamdewey** [comment]
Awesome :)
