### ISSUE TITLE
Add `on_hold` checks for Outbound Shipment

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3978]
Similar to https://github.com/msupply-foundation/open-msupply/pull/3977, add on_hold checks for outbound shipments.

- [ ] backend checks
- [ ] frontend checks

## How to Reproduce 🔨
- Create outbound shipment + lines
- Set it to be on hold
- Should not be possible to insert/update lines

## Your environment 🌱

- Open mSupply Version: 2.0.0

**Comment by andreievg** [comment]
@roxy-dao, I think this is expected behaviour ? I think when in doubt it's good to check mSupply functionality, or docs: https://docs.msupply.foundation/docs/distribution/outbound-shipments/#hold-checkbox

I propose closing issue

**Comment by clemens-msupply** [comment]
After discussion with @roxy-dao and @mark-prins, we want to keep editing an invoice. On hold just prevent others from doing status changes.

**Comment by roxy-dao** [comment]
> @roxy-dao, I think this is expected behaviour ? I think when in doubt it's good to check mSupply functionality, or docs: https://docs.msupply.foundation/docs/distribution/outbound-shipments/#hold-checkbox
> 
> I propose closing issue

There was conflicting statements XD
