### ISSUE TITLE
Store keeps getting switched to default store automatically when syncing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3980]
## What went wrong? 😲
If there are multiple stores in your oms-site, and you're currently logged in not-a-default store, then it automatically switches you to the-default-store when it syncs.

## Expected behaviour 🤔
shouldn't switch automatically unless user chooses to switch themselves

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure there are two stores in your site that you can login to
2. Login to store that is not your user's default-store
3. Do anything like create new transactions
4. Now open Sync window
5. Click on Sync button
6. See error: automatically switching to default-store
7. Try creating some records and leave for 5 mins (when sync runs on background, it automatically switches as well)

## Additional
Can I call this `severity:high` since that auto-switch looks nasty to me?

## Your environment 🌱

- Open mSupply Version: v2.0.0, v2.0.1
- Legacy mSupply Central Server Version: v7-14-06

- Platform: server exe, browser (chrome)

- Database type: sqlite

**Comment by CarlosNZ** [comment]
Duplicate of https://github.com/msupply-foundation/open-msupply/issues/3823 ?

**Comment by nisha-dangol** [comment]
> Duplicate of #3823 ?

oops.. closing this one
