### ISSUE TITLE
Can't edit `Delivered` Inbound Shipments

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3982]
## What went wrong? 😲
Change in #3808 has caused Inbound Shipments to not be editable when the status is Delivered.

## Expected behaviour 🤔
Should be able to edit an Inbound Shipment if the status is Delivered.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an Inbound Shipment
2. Add some lines
3. Change status to `Delivered`
4. See that you can't edit the Inbound Shipment anymore

## Your environment 🌱

- Open mSupply Version: 2.0.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed by #3983

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.3 exe:
- [x] Create an Inbound Shipment
- [x] Add some lines
- [x] Change status to Delivered
- [x] Now can edit the Inbound Shipment
