### ISSUE TITLE
Outbound shipment detail view column headers not fixed

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3989]
## What went wrong? 😲

Can scroll away from table headers:

https://github.com/msupply-foundation/open-msupply/assets/55115239/83db8be2-af4c-46fa-95a1-955ef04ee34a

I checked some other pages and they appear to be fine, but would be good to double check all of them 😅 

## Expected behaviour 🤔

Header row stays fixed at top of table

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Outbound shipment with lots of lines (e.g. add items from master list)
2. Scroll down
3. BUG: Table header doesn't stay!

## Your environment 🌱

- Open mSupply Version: 2.0.01
- Legacy mSupply Central Server Version:

- Platform: Browser

- Database type:

**Comment by roxy-dao** [comment]
Check other views that have tables if this is an issue there too.

**Comment by roxy-dao** [comment]
Can cherry pick into V2.0.3 if hot fixes come in

**Comment by roxy-dao** [comment]
Closed in #4033

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.3 exe
- [x] Go to `Outbound Shipments`
- [x] New shipment
- [x] Add from a large master list
- [x] Try scrolling
- [x] Header should be fixed
Looks good: PASS.

https://github.com/msupply-foundation/open-msupply/assets/59193490/8e134fd2-0fb8-447c-a8d5-a51d536860c6
