### ISSUE TITLE
Unable to see full description of a master list in `Item -> Master List` or in Master List page

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3992]
## What went wrong? 😲
Can't see the full description of a master list in Item -> Master list tab or in the Master List page (if screen is too small) if the description is long...

<img width="1548" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/05bf3941-fda4-446d-9d3b-955f71dcd000">

## Expected behaviour 🤔
Should be able to see full description. Use tooltips for now until the #3208 issue is scoped out

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a master list with a very long description (300char+)
2. Go to Item -> Master list tab
3. Description can't be fully read
4. Similarly go to Master list page
5. Make resolution small
6. Description can't be fully read 

## Your environment 🌱

- Open mSupply Version: v2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Seems like low priority, looks like it's linked to an issue, should be captured when that design is resolved =

**Comment by roxy-dao** [comment]
Do users store important information on the master list description? 🤔

**Comment by mark-prins** [comment]
CdI do - the master list names are long and packed. it's the comment (OG) / description (OM) that I have not seen used much, so if anything we should make the name column wider and shrink the description 🤷

**Comment by AnushaUp** [comment]
# 🧪 Testing
Open_mSupply desktop `v2.1.0-IA-test-2`


- [ ] Create master lists with really long name and description
- [ ] Should be able to long press (on mobile) or hover (on desktop) to see tooltip

**Comment by AnushaUp** [comment]
@roxy-dao I couldn't see tooltip while hovering 
https://github.com/msupply-foundation/open-msupply/assets/115983430/d8c98acd-b6e1-4346-855f-c42b5ac693ba

**Comment by roxy-dao** [comment]
> @roxy-dao I couldn't see tooltip while hovering https://github.com/msupply-foundation/open-msupply/assets/115983430/d8c98acd-b6e1-4346-855f-c42b5ac693ba

This change just got merged. It's not in v2.1.0-IA-test-2 XD

**Comment by AnushaUp** [comment]
@roxy-dao oops I didn't see that. Will come back to this later.

**Comment by AnushaUp** [comment]
PASSED✅
