### ISSUE TITLE
Can't see Supplier/Customer's full address

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3993]
## What went wrong? 😲
Can't view the supplier's or customer's full address. Maybe this should be like website and should expand to show full address instead of using a tooltip? 

<img width="743" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/d6a75133-2323-4e7f-a543-0d865397f50a">

## Expected behaviour 🤔
Should be able to see the customer or supplier's full address

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create/edit a customer/supplier with a long address
2. Sync
3. Go view that customer/supplier on OMS
4. Can't see full address

## Your environment 🌱

- Open mSupply Version: v2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Daily triage: setting to low as I assume this wouldn't really affect workflows (i.e. addresses would be printed correctly where they are needed?) Otherwise maybe should bump to normal

**Comment by roxy-dao** [comment]
Refinement: Move address to lower right and display multi-column to show full address

**Comment by mark-prins** [comment]
bumping priority slightly in the hope we get it done

**Comment by regotaina** [comment]
Tested on Rc5
Desktop app

# 🧪 Testing



- [x] Enter a really long address for a supplier or customer in OG
- [x] Go to either Supplier or Customer depending on which one you inputted
- [x] See that `Address` is now in bottom right
- [x] The user should be able to see the full address

PASSED THE TEST 👍 
![Image](https://github.com/user-attachments/assets/9214310f-32ba-4909-9c6b-c7c774a3e752)
