### ISSUE TITLE
Don't display foreign currency total if foreign currency id is the same as home currency

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3994]
## What went wrong? 😲
Foreign currency total is still being displayed even if it is the home currency

## Expected behaviour 🤔
Should only be displaying foreign currency total if the currency_id on invoice is actually a foreign currency

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create some invoices in OG
2. Move store to OMS
3. Initialise or Sync
4. Go to the invoices created
5. See the foreign currency total is there even if its home currency

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Daily triage - setting to low, it's not incorrect or affecting anything else. Might be nice to hide at some point 🤷‍♀️

**Comment by roxy-dao** [comment]
Refinement: Show a dash `-` in frontend if the currency_id is not a foreign currency

**Comment by roxy-dao** [comment]
Closed in #4274

**Comment by nisha-dangol** [comment]
## Tests
Tested in v2.1.0-rc6

- [x] Have issue in foreign currency store pref on
- [x] Create an invoice for an external customer/supplier
- [x] Add some lines with sell price
- [x] See - for foreign currency total
- [x] Change currency
- [x] See total
