### ISSUE TITLE
LANG_VERSION not compatible with electron

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#3995]
## What went wrong? 😲
Uncaught ReferenceError: LANG_VERSION is not defined

## Expected behaviour 🤔
Should be able to run electron locally

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. `Cargo run`
2. `yarn electron:start`

## Your environment 🌱

- Open mSupply Version: 2.1.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Needs to be fixed before 2.1 release

**Comment by AnushaUp** [comment]
Moving this to done as the desktop application connecting to server and is working properly👍
