### ISSUE TITLE
Repack `New Location` showing as old `Location` (new shows blank)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4010]
## What went wrong? 😲

When looking at a historic repack, it shows the updated location on the left with the "original data", and shows nothing for the "new location":

https://github.com/msupply-foundation/open-msupply/assets/55115239/8b52a08f-49b2-4f7b-931b-8331b6a5ebf2

i.e. Why are these different?

Editing:
![Screenshot 2024-05-28 at 9 53 31 AM](https://github.com/msupply-foundation/open-msupply/assets/55115239/211d2e83-9c9a-4bd3-bb8a-d3384946283d)

Saved:
![Screenshot 2024-05-28 at 9 53 39 AM](https://github.com/msupply-foundation/open-msupply/assets/55115239/6bb589ba-8909-4a0f-b4f3-cc8fe9e88ee9)

## Expected behaviour 🤔

Old location on the left, new location on the right
**Triage comment** not sure if we have the old location, or if it is easily attainable. Populate if it is available, but we are fine if only the new location is displayed on the right.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a stock line
2. Create a repack, and move that new stock to a new location
3. Save
4. View your repack line
5. BUG: See your inputted new location on the left, and empty `New location` field on the right

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform: Browser

- Database type:

**Comment by lache-melvin** [comment]
Daily triage: setting to normal - it's wrong, which isn't ideal, but just for display (not actually breaking any workflow)

**Comment by roxy-dao** [comment]
I think we did this on purpose 🤔 . The location on the repacks is correct... it doesn't have a new location cause it hasn't been moved again.

**Comment by mark-prins** [comment]
Looking at the vid - it does feel deliberate. the LHS shows the current location of the stock.
It would be confusing for me to have old and new locations populated.

So my view is that it isn't wrong at all. Possibly would be useful to have a mention in the log that the original stock was in location x and this is in location y, but not required atm.

my advice is to close the issue

**Comment by lache-melvin** [comment]
Ok... but LHS has old number of packs and pack size? Seems really weird to me to colocate that with the new location? 

Can understand maybe don't need the old location, but it would make more sense to me to leave the LHS location blank and the RHS one showing the updated location?

**Comment by mark-prins** [comment]
yes, I see that now. I was thinking of looking at the repack itself, not the historic repack on an existing stock line. agree - should change

**Comment by mark-prins** [comment]
**Refinement**
old location available.. add that in too please

**Comment by mark-prins** [comment]
moving out of 2.2 due to workload. it's not broken, just bad.

**Comment by regotaina** [comment]
Tested on RC5

Desktop app

# 🧪 Testing



- [ ] Have a stock line in a location
- [ ] Click on Stock -> Line -> Repack
- [ ] Change the location of the repack
- [ ] Click on the repack in the list view 
- [ ] See that old/new location are correctly displayed
