### ISSUE TITLE
Unable to import asset catalogue items with asset properties

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4012]
## What went wrong? 😲

<img width="840" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/8287373/27ad2a3f-1700-4253-98c5-1e5853380878">

## Expected behaviour 🤔

Import should work or at least return an error such as (duplicated code)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login to OMS Central Server
2. Click on Catalogue -> Assets
3. Click Import
4. Download example import
5. Try to import

## Your environment 🌱

- Open mSupply Version:2.1

**Comment by jmbrunskill** [comment]
FYI - This appears to be a papaparse bug.
Options for fixing this could be...

- Find some parameter in papaparse that fixes the issue?
- Move the import to the backend?

**Comment by lache-melvin** [comment]
Daily triage: setting as high severity, as with the default GAPS properties set, you can't import anything. Needs a solution before we can release GAPS

**Comment by mark-prins** [comment]
Refinement: Move to backend. could stage implementation, with error handling coming after the initial import process.
To do after the initial release of GAPS though, we don't want to hold up the release.
Can strip the properties for now in order to resolve the issue

**Comment by mark-prins** [comment]
@jmbrunskill do you have an import which reproduces?
I tried with this line:
```
General,66728ed8,Refrigerator,Haier,Cool Boy 3,Cold chain equipment,Refrigerators and freezers,3x5x5,45,4,3,2,1,4,5,6,7,78,Integrated,Integrated,9,9
```

and that imports fine
