### ISSUE TITLE
You can query patient data without `View Patients` permission (via name query)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4014]
## What went wrong? 😲

I have a user with no `View Patients` permission... but via API I can use the `name` query with a `type = PATIENT` filter and I get some patients back!

(FYI Patient list in omSupply won't work without view patients permission, but data shouldn't be accessible via names API either!)

## Expected behaviour 🤔

If no view patients permissions, I should not be able to see any patients!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure user has no `view patients` permissions in mSupply
2. Use something like Hasura to create a name query for patients (see below) 
3. Use a store_id that patients are visible for
4. You still get back some patients!

```gql
query Patients() {
  names(
    storeId: "STORE_ID_HERE"
    filter: {type: {equalAny: [PATIENT]}}
  ) {
    ... on NameConnector {
      totalCount
      nodes {
        type
        code    
        name
        dateOfBirth
        email
        address1
      }
    }
  }
}
```

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version: 7.14

- Platform: browser

- Database type: PG

**Comment by mark-prins** [comment]
**Refinement** Patients are fetched using a different endpoint - recommend excluding patients from the `name` GQL 
Patient query uses permisson

**Comment by roxy-dao** [comment]
Taking it out of testers board since it's not obvious that this is happening and would need some api manipulation
