### ISSUE TITLE
Empty rows in Location and Facilities

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4019]
## What went wrong? 😲
From #3998 change possibly from integration tests? 
![Screenshot 2024-05-29 at 2 14 54 PM](https://github.com/msupply-foundation/open-msupply/assets/61820074/41597744-6e20-4c91-857c-4c7272e5ffd7)
![Screenshot 2024-05-29 at 2 14 44 PM](https://github.com/msupply-foundation/open-msupply/assets/61820074/da47f30e-ed86-4800-8dba-ce6fb5c09f4d)

## Expected behaviour 🤔
Extra data that doesn't exist shouldn't be populating tables

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Locations or Facilities
2. See blank rows

## Your environment 🌱

- Open mSupply Version: v2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Daily triage: #3998 won't have changed anything for locations, it just added the facilities page. 

(I don't have any blank location records, not sure where you're getting those from? But I do have some blank names thanks to integration tests...)

Setting priority to low, as I think this only affects development. I don't _think_ we should need to handle blank records at runtime, if they're only the result of integration tests. But maybe a clean up script would be nice?

**Comment by lache-melvin** [comment]
If there are other use cases that create blank records, then this should go up in priority - I don't know what these would be though? I've just check with a clean demo data file and I have no blank lines

**Comment by roxy-dao** [comment]
I'm not running any integration tests... I'll test again with another datafile soon

**Comment by andreievg** [comment]
@roxy-dao if we can't duplicate it i think we can close issue

**Comment by roxy-dao** [comment]
Triage: Empty row doesn't look nice for UI. Fix before 2.1 release (:

**Comment by roxy-dao** [comment]
Tested with a different data file... doesn't seem to be a problem anymore? Not sure will close for now and can reopen if it is an issue.
