### ISSUE TITLE
Sell price from supplying store's Outbound Shipment not carried over to "sell price" in receiving store's Inbound Shipment

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#4020]
## What went wrong? 😲

the `sell price` data from the supplying store's outbound shipment is not carried over the related receiving store's inbound shipment (only for cost price)

Outbound Shipment: 
![Screenshot 2024-05-30 at 3 11 29 PM](https://github.com/msupply-foundation/open-msupply/assets/74992958/73c6dbbf-e48d-4e0b-b0e0-3a92f6da0769)

Inbound Shipment: 
![Screenshot 2024-05-30 at 3 11 57 PM (2)](https://github.com/msupply-foundation/open-msupply/assets/74992958/48509b9d-dfc0-4687-bc91-633c4e8c41cf)

@mark-prins said this: 

<img width="469" alt="Screenshot 2024-05-30 at 3 18 44 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/02051448-fcc8-4a79-b68a-1d634611257a">

## Expected behaviour 🤔

"The sell price should be populate same value as the (sending store) stock line sell price." (quoting @JonnaQuismundo)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a Outbound Shipment
1. Add an item (with sell price data)
1. Confirm as Shipped
2. Check the related Inbound Shipment's stockline

## Your environment 🌱

- Open mSupply Version: 1.6.03
- Legacy mSupply Central Server Version: 7.12.04

- Platform: browser (Chrome)

- Database type:

**Comment by lache-melvin** [comment]
I think this is correct? The `sell price` for the outbound store will be the `cost price` for the inbound store.

Per the Inbound Shipment docs: `Pack Sell Price: The selling unit price of the item (default value is 0)`

i.e. if the receiving store were to on-sell the goods, they would sell them for the `sell price`

Are you requesting that sell price defaults to cost price?

**Comment by richardmoizeau** [comment]
> Are you requesting that sell price defaults to cost price?

Yes that's it. @JonnaQuismundo and @craigdrown confirmed that this should be the expected behaviour.

**Comment by richardmoizeau** [comment]
@Cyrilbrites, once this issue is finalised, we should update Djibouti server and potentially each Open mSupply client (?) in Djibouti

**Comment by lache-melvin** [comment]
Daily triage: severity normal - there's a workaround, you can just enter the sell price, but we should match what happens in mSupply 🚀

**Comment by JonnaQuismundo** [comment]
> > Are you requesting that sell price defaults to cost price?
> 
> Yes that's it. @JonnaQuismundo and @craigdrown confirmed that this should be the expected behaviour.

Just to be clear 
SI `trans_line.cost_price` = CI `trans_line.sell_price`
SI `trans_line.sell_price` = CI `trans_line.itemLine.sell_price`

**Comment by lache-melvin** [comment]
Closed by #4247

**Comment by nisha-dangol** [comment]
## Tests
Tested in v2.1.0-rc6

- [x] Create outbound shipment to another oms store
- [x] Add a line which has a sell price
- [x] Set to at least picked
- [x] Switch to receiving store
- [x] Go to the corresponding inbound shipment
- [x] The sell price has been mapped through 🎉
