### ISSUE TITLE
Update assets to assignable to a Name (not just a store)

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4022]
## Is your feature request related to a problem? Please describe 👀

For GAPS work we ideally need to be able to assign assets to a name (not a store).
If we don't allow names, we'll need to create stores for every asset location, rather than just names.

## Describe the solution you'd like 🎁

- Allow both a store_id and name_id to be defined on an asset.
- When creating an asset on central server instead of assigning a asset to a store, it will be assigned to a name.
- The store_id can stay as the store_id of the central OMS store for now?
- When creating on a remote site, the current store will be used as per current state and name from the store assigned. 

### Describe alternatives you've considered 💭

Create stores for all locations that need assets

### Moneyworks Jobcode 🧰
CCEIDEV

**Comment by adamdewey** [comment]
@jmbrunskill - ah, can you remind me, why did we decide not to create Stores for all facilities?

Wouldn't it be easier to transition from a centralised model to a distributed if the Stores already existed?

**Comment by jmbrunskill** [comment]
@adamdewey We can import names in mSupply but have to manually setup stores. We're thinking we could potentially import the names in open-mSupply as well, where as creating stores might need a bit more setup than a simple import?
Up for discussion still though.

**Comment by mark-prins** [comment]
Is this issue still required?

**Comment by adamdewey** [comment]
Not needed for GAPS.

Possibly there are other use cases for general asset management that I haven't considered - but maybe we can cross that bridge later if needed?

**Comment by jmbrunskill** [comment]
I think we close it @mark-prins
