### ISSUE TITLE
Some stock lines aren't included in search results

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4024]
## What went wrong? 😲

I have some `Salbutamol` stock lines, as introduced via Inbound Shipment from another store, where `Salbutamol` is visible:
![Screenshot 2024-05-31 at 5 32 17 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/ea35dee0-4b25-4be7-8ac0-dfab0520627b)

But when I use the search:

![Screenshot 2024-05-31 at 5 32 25 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/9fcd0b90-8a72-4d4c-8d96-d67dae136a4b)

Similarly... I can't issue it anywhere?

![Screenshot 2024-05-31 at 5 34 38 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/30b7eb46-e63d-4e2d-951e-8edc81004710)

Also can't add it to a stocktake? (Unless you create the stocktake with the `Items with stock` filter - then it appears)

## Expected behaviour 🤔

I should be able to search across all my stock lines 👀 

Actually not sure what the intended behaviour is if you get sent an item that isn't visible for you? Probably wouldn't happen too often because you would get what you requested, but still...

Maybe you shouldn't receive that inbound line at all??

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. From one store, create an outbound shipment to another store
2. Add an item to the shipment that is visible in your store, but not visible in the receiving store
3. Set to shipped
4. Switch to receiving store and set the inbound shipment to delivered
5. In view stock page: new stock line is added, for item you shouldn't be able to see
6. Search for the item - you can't see it

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

## Context

For the stock list view at least, it would appear this is the problem: we apply item visibility filtering only if `item_name_or_code` filter is set? I think it should either happen all or none of the time? Though feels if we care about item visibility we shouldn't be able to receive that stock line at all...

https://github.com/msupply-foundation/open-msupply/blob/30f80f49a32beddda2b28fdddfc17643ec22118d/server/repository/src/db_diesel/stock_line.rs#L227-L248

## Agreed solution

Similar to how visibility by master lists works, another view that checks if any item lines with stock exist, and join it to item and use as filter

**Comment by lache-melvin** [comment]
Sounds like it might be related to what Jonna mentioned at stand up this week - the master list visibility control fix that went into mSupply...

**Comment by andreievg** [comment]
Triage, need to figure out how exactly to do this, but agree it's important to get right, hopefully in 2.1

**Comment by andreievg** [comment]
Similar to how visibility by master lists works, another view that checks if any item lines with stock exist, and join it to item and use as filter

**Comment by lache-melvin** [comment]
> Similar to how visibility by master lists works, another view that checks if any item lines with stock exist, and join it to item and use as filter

@andreievg Hi, is this to be used everywhere?

- View Stock: should be able to see all the stock you have on hand
- Stocktake: should include all stock you have on hand
 - Outbound shipment/prescription/outbound return:  should be able to distribute the stock you have
 - Item list: should be able to see all items that are visible for you.. plus items you have stock on hand for?
 - Inbound shipment/return: maybe not here? shouldn't be able to receive items that aren't visible to you?

**Comment by lache-melvin** [comment]
closed by #4275

**Comment by nisha-dangol** [comment]
## Test
Testing in v2.1.0-rc6
- [x] Have two stores using two different master lists, with some different items in those master lists
- [x] From one store, make an Outbound Shipment to the other store, including an item that is not in the master list for that other store (i.e. not visible in the other store)
- [x] Receive that Inbound Shipment of the invisible item in the receiving store
- [x] Item List: you can now see that item
- [x] View stock: you can now see that stock line - also test that you can still see that item when you use the `item name or code` search! (this was the original bug)
- [x] Outbound shipment: you can issue the item
- [x] Prescription: you can issue the item
- [x] Outbound return: you can return the item
- [x] Stocktake: you can add this item in your stocktakes
- [ ] internal order: you cannot request this item
- [x] Inbound return: you cannot add this item to an inbound return
- [x] Inbound shipment: you cannot add this item to an inbound shipment

>  [ ] internal order: you cannot request this item
>
Is this strictly necessary? 'cuz I CAN request this item in the Internal Order. @lache-melvin

**Comment by mark-prins** [comment]
I think it's ok to leave the internal order. Ideally yes, we'd not show items which are not visible in the supplying store

**Comment by nisha-dangol** [comment]
> - [x] Item List: you can now see that item

Hi @mark-prins, just a note: being able to see invisible item means I can see the item details but `Master list` tab shows `nothing here` . Expected, right (since that master-list ain't visible to the store)? 
<img width="1121" alt="SCR-20240705-fu4" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/291734be-8631-428a-a441-ab003fc35aa8">
<img width="1192" alt="SCR-20240705-ftx" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/5615bf11-3cdf-42fd-be78-880bce10e4f1">

**Comment by mark-prins** [comment]
yes - good point! it is expected, though perhaps we could have a slightly more helpful message here.
I'll see if we can add something 🙏
