### ISSUE TITLE
Can no longer find duplicate patients because code is required on creation modal

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4028]
## What went wrong? 😲
Can no longer find duplicate patients because code is required on creation modal. We should only make code required on the creation page so that the user can search for duplicate patients

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some duplicate patients
2. Create a new patient with same details as already existing patient (apart from code)
3. Go to search step
4. See no duplicates show up

## Your environment 🌱

- Open mSupply Version: v2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by lache-melvin** [comment]
Ok update: @roxy-dao to talk to @clemens-msupply about this tomorrow...

If we can just remove code from the duplicate search, this sounds like a fairly quick fix we should get out in 2.0.3. If we need to separate the json forms schemas for the modal and page, that's a bit more work - probably 2.1 unless required for upgrade sooner?

**Comment by lache-melvin** [comment]
> Ok update: @roxy-dao to talk to @clemens-msupply about this tomorrow...
> 
> If we can just remove code from the duplicate search, this sounds like a fairly quick fix we should get out in 2.0.3. If we need to separate the json forms schemas for the modal and page, that's a bit more work - probably 2.1 unless required for upgrade sooner?

(Putting back to 2.0.3 for now unless decided otherwise)

**Comment by clemens-msupply** [comment]
Think this was caused by https://github.com/msupply-foundation/open-msupply/pull/3710

**Comment by roxy-dao** [comment]
Closed with #4037

**Comment by nisha-dangol** [comment]
Tried replicating original issue steps in v2.0.3
1. Have duplicate (I've a patient named `jolt jolteon` in other mSupply dispensary-site)
2. In oms-site, prompt to add new patient
3. In patient-creation modal, I notice BOTH `first-name` & `last-name` are required to proceed. 
Are we not going with EITHER `first-name` OR `last-name` is only required? Can anyone confirm? @roxy-dao or @clemens-msupply ?
<img width="425" alt="SCR-20240606-iyj" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/5be06fb2-8e44-47af-82bf-7646ab78383b">

4. I put in seach term (`jolt jolt`) and proceed
5. I still see `NUIC` column in search-results. Note: This is NOT a programs-configured datafile. I thought `NUIC` is now replaced by `Code2` everywhere else?  Another minor UI bug? @clemens-msupply 
<img width="748" alt="SCR-20240606-iyd" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/8b89e428-67e0-4b54-bbda-b14c5c400bde">

**Comment by nisha-dangol** [comment]
Will move this to Done since the above-mentioned issue seems to be known one: #2185

**Comment by clemens-msupply** [comment]
>     3. In patient-creation modal, I notice BOTH `first-name` & `last-name` are required to proceed.
>        Are we not going with EITHER `first-name` OR `last-name` is only required? Can anyone confirm? @roxy-dao or @clemens-msupply ?

Yes at the moment is first AND last name. Could relax this but this was the previous behaviour we agreed on...
