### ISSUE TITLE
Use UUIDv7 instead of v4

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#4038]
## The suggestion

Since uuid7 produces time sortable ids, using uuid7 as primary key should result in better DB performance. For example, it's much more likely that all stocktake lines of a newly created stocktake are in consecutive blocks on disk while with uuid v4 rows are scattered all over the disk...

Please see https://uuid7.com/ for details.

@jmbrunskill 

We already abstract over the used uuid method. So very easy to change.

**Comment by roxy-dao** [comment]
Remove from list of updates #2882 when done

**Comment by clemens-msupply** [comment]
> Remove from list of updates #2882 when done

Just to clarify, this is not the Rust crate version but the version of the uuid specs

**Comment by roxy-dao** [comment]
Can we update the crate at the same time? To slowly get things moving on that end? 👀

**Comment by andreievg** [comment]
@clemens-msupply does this apply to postgres and sqlite, was wondering if there is online resources showing performance gains ? 

Triage, looks like a small change, if the benefits are practical then a should have

**Comment by clemens-msupply** [comment]
I found this (postgres):
https://www.2ndquadrant.com/en/blog/sequential-uuid-generators/

Snowflake is a uuid similar to uuid v7, and also confirms that ordered reads are faster:
https://dev.to/josethz00/benchmark-snowflake-vs-uuidv4-2h80

I also did some toy benchmarking for sqlite and can at least confirm the write speedup for larger datasets...
