### ISSUE TITLE
Add translation file prop to useColumns or Table component

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4043]
## Is your feature request related to a problem? Please describe 👀

It would be nice to be able to pass specific translation files into our tables rather than having all table related translated strings in the common.json file

## Describe the solution you'd like 🎁

Add a prop where specific files could be passed

**Comment by mark-prins** [comment]
Note - just the name of the translation namespace needs to be passed to the `DataTable`, and, if provided, the `useTranslation` call in the table components can use that ns

**Comment by andreievg** [comment]
We talked about another option of adding a way to overwrite header name (rather then doing locale key, specify an actual string) and maybe the string comes from userTranslation within useColumns

**Comment by mark-prins** [comment]
A few options here:
* pass the namespace to the `DataTable` and use this for all translations ( which then falls back to `common`, so behaves as it does now for the majority of translations )
* Update the `Column` interface, and add a property which provides the label text, such as `getLabel: () => string` which allows the column definer to specify an empty string for `label` and then a getter for `getLabel` which does the translation using a local namespace
* Change the `label` prop to be a string. All consumers then are changed to use this approach and locally translate the column labels. Rationalise the translation files - lifting all header labels out of `common.json` that don't need to be there ( are only used in a single, local, translation namespace )

I would prefer the last option, as it is a consistent approach ( we don't have label/getLabel ) and allows the consumer to handle the translating. It's a big job though, and not necessary - things work as they are now. 

Thoughts?

**Comment by andreievg** [comment]
Refinement, there is overall issue about translation that potentially solves it

**Comment by Chris-Petty** [comment]
Refinement: part of table performance theme, closing for now in favour of consolidating investigation #4744
