### ISSUE TITLE
CCEI: Rename `Status Logs` tab to `Status History`

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4045]
## Is your feature request related to a problem? Please describe 👀

I find it a bit confusing to have tabs for both `Status Logs` and `Logs`

Could we rename this tab to `Status History` ?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/456aa620-2a48-40c8-8288-1e4b2f2cad2b)

### Additional context 💌

Currently the main historical information captured is changes to Functional Status. 

But the future plans for the CCEI are to capture scheduled preventative maintenance events too - and it would likely make sense to display them in chronological order along with changes to functional status. 

Additionally it might be nice to be able to see temperature alarms chronologically too (depending on how noisy it makes things)

**Comment by andreievg** [comment]
triage: Technically priority is low, not impacting existing users, and if it was impacting them then very low

**Comment by andreievg** [comment]
Can of course be done quite quickly, just need to agree on it. Also Mark mentioned it can be done in translations (so no code changes)

**Comment by andreievg** [comment]
Still needs agreement

**Comment by adamdewey** [comment]
Had a meeting with @mariyamsupply just now. 

Consensus was either leave it as Status Logs or change to Status History for now and then review when the scheduled maintenance functionality comes it (likely to change to Maintenance or similar)

**Comment by roxy-dao** [comment]
Can we close this issue if it was agreed to keep `Status Log`? Or would you like it to be changed to `Status History`?

**Comment by adamdewey** [comment]
@roxy-dao Can we just change it to `Status History` to make it more easily distinguished from the `Log` tab?

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC6, and Status Logs are now renamed into Status History :) Build test passed ✅

**Comment by AnushaUp** [comment]
Thanks @marthakeezy👍
