### ISSUE TITLE
GAPS: Demographics miss calculate when editing general population

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4054]
## What went wrong? 😲

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/483eaa5d-519f-48ce-9c9f-d1843072f769)

## Expected behaviour 🤔

The first year population in the screenshot above should be `20200` not `20220`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Catalogue -> Demograhics`
2. Enter a general population 
3.  Check the 2025 population, it should be 1.01* the population (by default)

## Your environment 🌱

- Open mSupply Version: develop

**Comment by mark-prins** [comment]
tested against develop and cannot reproduce. @jmbrunskill can you have another look?

**Comment by jmbrunskill** [comment]
Can't reproduce now on latest develop
