### ISSUE TITLE
GAPS: Demographics - Population Growth is not saved

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4055]
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Catalogue->Demographics`
2. Enter a Population and growth rates
3. Click save
4. Exit the page and re-open
5. See % Growth on previous year fields have been reset to their original values (before saving)

## Your environment 🌱

- Open mSupply Version: `develop`

**Comment by mark-prins** [comment]
it's working for me on develop: @jmbrunskill can you retry?

**Comment by jmbrunskill** [comment]
> it's working for me on develop: @jmbrunskill can you retry?

It's the %ages that aren't saving...
The actual population numbers are but then out of sync with the values at the top of the page.

**Comment by lache-melvin** [comment]
Just adding that the projections aren't just out of sync - they can get overwritten if you make further changes to projections:
https://github.com/msupply-foundation/open-msupply/assets/55115239/d1d06fe6-d4a7-4645-b563-756e7f178e7d
