### ISSUE TITLE
SQL error on migration from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4056]
## What went wrong? 😲

Tried updating my develop branch (haven't done so for a while)

Went from 2.0.0 to 2.1.0 and received this error message: 

![telegram-cloud-photo-size-1-5120765391512120320-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/c0ac131e-187b-469a-b4d2-7fd1bd204fd2)

Datafile here: 
[omsupply-database.sqlite.zip](https://github.com/user-attachments/files/15602273/omsupply-database.sqlite.zip)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.0.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type: SQlite

**Comment by roxy-dao** [comment]
![photo_2024-06-07 09 21 39](https://github.com/msupply-foundation/open-msupply/assets/61820074/f48c057a-f5aa-4051-9967-0044ca134e23)
Another migration error when upgrading

**Comment by clemens-msupply** [comment]
Regarding the initial problem. I looks like the initial DB was initialized with a temp version from develop...

```
#[cfg(test)]
#[actix_rt::test]
async fn migration_2_01_00_from_2_00_00() {
    use v2_00_00::V2_00_00;

    use crate::migrations::*;
    use crate::mock::MockDataInserts;
    use crate::test_db::*;

    let version = V2_00_00.version();

    // Migrate to 2.0.0 with data
    let SetupResult { connection, .. } = setup_test(SetupOption {
        db_name: "migration_2_01_00_from_2_00_00",
        version: Some(version.clone()),
        inserts: MockDataInserts::all(),
        ..Default::default()
    })
    .await;

    V2_01_00.migrate(&connection).unwrap();
}
```

I tried this test and it all works fine...
