### ISSUE TITLE
Organise translation namespaces

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4060]
## The suggestion

The current organisation of translation namespaces might not be entirely fit for purpose and it would be good to review how it is working and if we can improve.

The original intention was to divide translation strings into functional areas, so that the app would only need to download strings for the area that the user is working in, reducing the overall download size. 
I would still strongly recommend splitting the strings into namespaces, and I also prefer having the translation keys prefixed in a way to divide them e.g. `button.save` `settings.label-printing`

However.. given that the JSON files are cached, perhaps the huge initial download isn't critical? In which case we could split across tasks e.g.

`buttons.json`
`errors.json`

even though this would require editing multiple translation files while working on a feature.

Here are the current namespaces:

| namespace | description |
| ------------| ----------- |
| app | Application-wide strings such as menu items and keyboard shortcuts |
| common | Strings which are used in more that one area and strings which are called from the `common` package by shared components |
| dashboard | Dashboard-specific strings  |
| distribution | Anything used solely in  the distribution area: Outbound shipments, Requisitions &c. |
| inventory | Inventory only strings  |
| replenishment | Replenishment only strings  |
| catalogue | Catalogue only strings  |
| dispensary | Dispensary only strings  |
| programs | Programs specific: the HIV program work for PNG  |
| coldchain | All things coldchain, including the assets module now  |
| plugin | A separate space for plugin specific strings  |
| manage | The new central server-only administration aspects; for centrally managed things e.g. `name`s for GAPS |

### Why should we invest time in this?

There's possibly a small overhead in developer time with the current split. I have heard complaints, though nothing tangible enough to flesh out this issue. There may also be a small improvement in app responsiveness if we get the split perfect, and conversely, a decrease in performance if we prioritise developer's needs.

A concern would be having a single file, as this would increase the incidence of development conflicts. Splitting by functional areas is a sensible way to remove this risk.

### Are there any risks associated with this change?
* There is a small risk we decrease performance
* a risk we confuse developers with the change
* a possible increase in development conflicts

### How much effort is required?
Probably not much 🤷 
The development change is minor, perhaps half a day to move strings around.
Deciding what to do, that will take days.

**Comment by jmbrunskill** [comment]
One problem I have with the breaking down of things into `buttons.add-name` and `label.add-name` is that I feel like we get a lot of duplication. Maybe we should have a difference between a button text and label text, I currently don't feel clear on it.
I do support this refactor though. Would be nice if we could think about other things too when we're re-doing it, such as duplication for translation.

**Comment by mark-prins** [comment]
to check: does caddy gzip by default? If the JSON files are gz then they'll be much smaller. 
they're cached too, so the bundle size isn't a big deal.

**Comment by andreievg** [comment]
Triage, maybe the refinement can determine when this is done ? We've had conversation about this area a few times, maybe that should be reflected in the priority

**Comment by jmbrunskill** [comment]
> to check: does caddy gzip by default? If the JSON files are gz then they'll be much smaller. they're cached too, so the bundle size isn't a big deal.

Caddy doesn't gzip by default but Actix already does compression.
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/13858ece-ff31-4364-b0d4-f95ca912dc25)
7.58KB for current `common.json`
Potentially we'll get better compression % for a bigger file?

(Compression can be turned on via Caddy is needed, but it should just pass through this compression)

**Comment by mark-prins** [comment]
Duplicate of #1266 - and both issues have useful info. Keeping both open for now until we decide on an approach.
Just looking at potential file size we currently have a 1,512 translations, so a single file is possible though a little cumbersome. 

namespace | translations
-- | --
app | 142
catalogue | 66
coldchain | 183
common | 547
dashboard | 35
dispensary | 99
distribution | 150
inventory | 119
manage | 1
plugin | 2
programs | 14
replenishment | 154
  | 1512

Note that we have a few scripts to check for unused and missed translations. Perhaps a 'duplicates' script is possible too?

* `i18n-unused-display`
* `i18n-unused-remove`
* `i18n-missing": "i18n-unused display-missed`

So - to summarise:

Approach | Pro | Con
----------|-----|----
Single file | `LocaleKey` type includes all translation keys, it isn't possible to try and translate using `namespace a` when the translation exists in `namespace b` | Potential for development conflicts
|  | Possible to find duplicates easily if you sort all entries by key | GitHub doesn't like displaying large diffs
|  |  | large single file for clients to download / not possible to split translations by usage area
Reorganise namespaces | Some people find the current grouping not very logical | Potential to increase conflicts
| | | Might have to update large number of translation files when working on a single feature

**Comment by andreievg** [comment]
There is also this one: https://github.com/msupply-foundation/open-msupply/issues/4673

**Comment by mark-prins** [comment]
Refinement: we'll go with a single namespace file.
When implementing, remove all calls to `useTranslation` which refer to a specific namespace
We also discussed 
* the possibility of creating a client-specific override namespace, which could override the keys in the general ns file with values provided by the server (centrally administered?) e.g. the column names in the R&R form
* adding a commit hook to order the rows in the JSON file ( side thought: do we have prettier formatting of the weblate files? )

**Comment by marthakeezy** [comment]
QA needs to be done by individuals who speak the languages omSupply is translated into, and Ferg has created separate issues for each language. Moving this one to Done ✅
