### ISSUE TITLE
Stock details: if you make changes and discard them, the form doesn't clear

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4066]
## What went wrong? 😲

If you make a change on the stock line, like adding a new 'cost price', but discard the changes, the form still displays the change made. The video below illustrates the bug:

https://github.com/msupply-foundation/open-msupply/assets/132425096/5c670fcf-7584-4648-b553-f684edea1f89

However the system doesn't save the changes made. 👍🏾 

## Expected behaviour 🤔

The form should ignore the changes, otherwise it gives the impression the new information has been accepted/saved.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to '.Inventory> View stock'
2. Click on any item line
3. Make changes on the details, like setting up a new expiry date
4. The 'cancel' button is enabled. Press it and confirm you wanna lose the information entered
5. The form still displays the information typed

## Your environment 🌱

- Open mSupply Version: v2.1.0-IA-test-2
- Legacy mSupply Central Server Version: V7.16

- Platform: Desktop app

**Comment by CarlosNZ** [comment]
Duplicate? 
I think this is the same problem described in this issue: https://github.com/msupply-foundation/open-msupply/issues/3959

**Comment by regotaina** [comment]
> Duplicate? I think this is the same problem described in this issue: #3959

True, it only happens with currency.
