### ISSUE TITLE
View stock: 'Cancel/Close' button disabled 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4067]
## What went wrong? 😲

On 'View stock' > 'Details'  the 'Cancel/close' button is disabled, unless you try to make a change.
It can be confusing for users, you shouldn't have to make a change to then cancel and close a window.

![Screenshot 2024-06-07 at 12 56 24 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/fcbf3af7-90df-4763-88e2-f607a7aeeb33)

On other parts of the system this button is always enabled. 

## Expected behaviour 🤔

The button should be enabled all the time, this way users can go back to the list without going back to the navigation bar.
This is how it already works on other parts of OMs like Outbound shipments, Inbound shipments, etc..

## Your environment 🌱

- Open mSupply Version: v2.1.0-IA-test-2
- Legacy mSupply Central Server Version: V7.16

- Platform: Desktop app

**Comment by andreievg** [comment]
Triage, as per PO suggestion, just close button, if no changes just close, if changes prompt

**Comment by andreievg** [comment]
Triage, adding milestone because new feature is being brought in

**Comment by roxy-dao** [comment]
> For clarity... this isn't really a bug - it is implemented as a `Cancel` button just to clear the form, rather than a `Close` button to go back to the list view.
> 
> Though given the confusion, perhaps it's best that it is changed to a close button regardless! (Or we have both??)

This is different behaviour from other `Cancel` buttons and needs re-thinking

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/open-msupply/issues/3959

**Comment by roxy-dao** [comment]
Closed in #4257

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC6, the button is enabled and now says 'Close', build test passed ✅
