### ISSUE TITLE
KeepAwake not available on initial load

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4069]
## What went wrong? 😲

Screen goes to sleep during intialisation, requiring `Retry`.

#4048 raised an issue where the Initialisation screen couldn't be typed in on android, because the KeepAwake plugin throwing a "not available" error. 

Workaround hotfix was introduced in #4050, catching/swallowing the error and moving on. However, we shouldn't have this problem in the first place! 

(See #4048 & #4050 for more details)

It's working fine in 2.0, but in 2.1 the error arises. This needs investigation - I did a little, and couldn't find any of our code changes in that vicinity recently, but needed to get a working build going so didn't spend too much time.

Now the screen goes to sleep during initialisation again, which stops the process & shows an error (you have to press Retry and it continues)  - not a great regression 😭 

## Expected behaviour 🤔

KeepAwake works without errors on initial load of the initialisation screen.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run debug version of APK
2. Start initialising
3. Screen will go to sleep
4. You have to click `Retry` for it to continue

OR for original issue 

1. Back out changes or use previous commit than #4050
1. Run debug version of APK
1. On app start, select run in server mode
1. You can't type in the input fields, and `Initialise` button says `Retry`

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform: Android

- Database type:

**Comment by lache-melvin** [comment]
![image](https://github.com/msupply-foundation/open-msupply/assets/55115239/14e4f008-a34b-4cae-a794-51725135dcfc)

This is the error that @regotaina is getting sometimes, when the tablet goes to sleep. I think it's related? Hopefully this looks familiar to anyone who was around before the KeepAwake was introduced? 🙏

**Comment by mark-prins** [comment]
That doesn't look familiar sorry - though it seems logical that this is due to the app sleeping and closing all connections

**Comment by andreievg** [comment]
Triage, potential candidate for hotfix, would recommend high priority for 2.2, I think it would still be ok as initialisation should still happen in the background so even though it's likely, it's not critical, with work around

**Comment by kahn-msupply** [comment]
@regotaina made me aware of this issue - one thing we can do is change MeMDM settings for timeout of the display - maybe just for the initialisation stage. Tested with @regotaina's tablet and the screen stays on.

**Comment by mark-prins** [comment]
Would like to investigate in 2.2 and see if we can get a fix in place. 
am currently updating the capacitor packages, including keepawake, so possibly this is already resolved

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Build the debug apk and deploy
- [ ] set the display timeout to the minimum (15s on samsung)
- [ ] clear storage and initialise
- [ ] the tablet shouldn't sleep while syncing
- [ ] log in, view a stock line: should have the barcode scanner available
- [ ] re-deploy and test while already initialised
