### ISSUE TITLE
Stocktake: snapshot/current # packs mismatch error is confusing

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4070]
## What went wrong? 😲

@CarlosNZ  and I noticed that when finalising the stocktake after reducing it to 0 brough this error message below:

![Screenshot 2024-06-07 at 1 05 50 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/c8639c70-3cdf-4a53-91f5-518bbf7ab505)

However it's hard to understand what it is reffering to. If the stock line is already allocated somewhere, the message should specify that.

## Expected behaviour 🤔
Error message more clear about why the stocktake cannot be finalised? 
Open to suggestions here.

## Your environment 🌱

- Open mSupply Version: v2.1.0-IA-test-2
- Legacy mSupply Central Server Version: V7.16

- Platform: Desktop app

**Comment by regotaina** [comment]
Some units were allocated in a prescription.

I was able to delete the line, then search for the item line again and the count was updated.
Similar to the work around mentioned on #3820

**Comment by nisha-dangol** [comment]
Just fyi, I get the proper reason/error-message when stocks are reserved in Outbounds
<img width="1366" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/859edefb-52bf-4a9c-ac20-8a6c4c3ea5e8">
<br>
Looks like when stocks are picked in prescription-only, then the above mentioned original alert appears.

**Comment by andreievg** [comment]
Hmm, we had a few discussions about this in various places, there is also this discussion: https://github.com/msupply-foundation/open-msupply/discussions/3820, i'll add this issue there, will leave for normal triage to figure out if we need to keep this issue as placeholder or close it and reference in discussion

**Comment by mark-prins** [comment]
two quick things to fix which would improve the process
* check for allocation to prescriptions and display a message similar to the outbounds one
* remove the double red border on the cell - should only show the outer border

and as for the wider problem, we'll leave that for the result of the discussion which Andrei linked above

**Comment by marthakeezy** [comment]
V2.3.0 is out so moving to Done ✅
