### ISSUE TITLE
Add 'Invoice Number' column to Ledger View

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4072]
## Is your feature request related to a problem? Please describe 👀

If I'm looking at some stocks (let's say wondering where some of the allocated/reserved stocks are stuck), way is to check its ledger. But if there's huge record of ledger (let's say hundred of lines), it'll be very tiresome to manually check each of the transaction in that long list.

## Describe the solution you'd like 🎁
A simple `Invoice Number` tab would help me heaps in this situation; (maybe some other situations as well?)

**Comment by andreievg** [comment]
Triage, agree this would be great to get in, but not sure when we have the capacity for it as it's very low impact

**Comment by mark-prins** [comment]
Is a quick one to implement - have removed from v2.2 due to workload. would like to pick up again when we have the time.

**Comment by marthakeezy** [comment]
Tested in `V2.3.0-RC1`

The column appears under Inventory -> View Stock -> Ledger, build test passed :)

P.S. agree the Invoice Number column should be sortable, but as Carl mentioned, there already is a discussion ^
