### ISSUE TITLE
GAPS: Demographics UI tweaks

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4075]
## What went wrong? 😲

Few tweaks: 

- [x] Change column order to: `Name`, `Percentage`, `Population`
- [x] Add `%` sign after values in `Percentage` column
- [x] Right align values in Growth columns
- [x] Change label to `Growth on previous year` (i.e. drop the %)
- [x] Add `%` sign after values in Growth columns
- [x] Right align `Growth on previous year` 
- [x] Change label from `Population` to `Current population`
- [x] Make table full width

## Expected behaviour 🤔

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/45249f92-8a13-45ea-a20f-7941086f2190)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

8. Click on '....'
9. Scroll down to '....'
10. See error

## Your environment 🌱

- Open mSupply Version: Develop 2.1.0
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Can this plz also make the table full width 🥲

**Comment by lache-melvin** [comment]
Also I think we should be using the NumberCell & NumberInputCell (or at least NumericTextInput) so we can get formatting on the big numbers, decimal handling etc?

**Comment by lache-melvin** [comment]
Note: while cleaning up demographics page, would be great to remove the `as Type` usage - if we're needing it then we're doing something wrong with the types, and should fix that instead!
