### ISSUE TITLE
GAPS: Demographic percentage field doesn't accept decimals

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4076]
## What went wrong? 😲

The `Percentage` column doesn't currently accept decimal values but it needs to. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/f1a80e7d-e2e0-424b-8f83-000ea587031d)

## Expected behaviour 🤔

User can enter up to 2 decimal places

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: Develop 2.1.0
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

**Comment by jmbrunskill** [comment]
Done
