### ISSUE TITLE
GAPS: Change nav menu item to `Immunizations`

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4077]
## What went wrong? 😲

Default US / UK debate rages on, but in the meantime we need to be consistent so should change this to US spelling to match elsewhere in the product: 

 
![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/c5c09c96-5bcd-4898-8cbc-92b20d0ed902)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: Develop 2.1.0
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Fixed in #4091
