### ISSUE TITLE
GAPS: Non-stores are showing in `Facilities`

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4079]
## What went wrong? 😲

Non-store names are showing in `Facilities` whereas I think it should only be showing Stores?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/4a71b57f-b74e-4e3a-afc4-32cfe17877cf)

## Expected behaviour 🤔

Only Stores show in the list.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: Develop 2.1.0
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Hi @adamdewey @mark-prins - just wanting to double check on this one... At the time it was intended to be stores & non-store facilities, so you could also edit/account for capacity in facilities that weren't using mSupply... has that changed since the "let's put assets against stores" decision?

**Comment by adamdewey** [comment]
> Hi @adamdewey @mark-prins - just wanting to double check on this one... At the time it was intended to be stores & non-store facilities, so you could also edit/account for capacity in facilities that weren't using mSupply... has that changed since the "let's put assets against stores" decision?

HEy @fergie-nz - ah, so my thinking was that all facilities would be using mSupply if the country is using GAPS (but they won't necessarily be using it for stock management or even have it installed locally)

But I think best to consider they are all using it, even if it means they are just occasionally logging into their Store via the web interface from the central server
