### ISSUE TITLE
Cannot edit stocktake lines with reasons already set after reasons are disabled

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4083]
## What went wrong? 😲

First raised by @AnushaUp [here](https://github.com/msupply-foundation/open-msupply/issues/3567#issuecomment-2154005340)

This is a stocktake line that was created while some reasons were active. Then all reasons were set to inactive (meaning a reason is no longer required.) Now trying to edit that line, becuase you DO have a reason set, you get an error, but the input is disabled and you can't change it!
![image](https://github.com/msupply-foundation/open-msupply/assets/55115239/61250c99-9266-4736-88e8-f7cb92ed3b1c)

Also, the error message "Adjustment reason does not match adjustment direction" is misleading. The check is actually more broad, for whether the selected reason is valid. One of the ways it could be invalid is if you chose a positive reason for a negative adjustment, but in this case, the selected reason is invalid because it is no longer active.

Seems fairly low probability though, and there is a workaround (you can delete the stocktake line and recreate) 

## Expected behaviour 🤔

If a reason is no longer required, you shouldn't get a reason error! Either clear the reason from the line, or ignore it. Or at a minimum, the user should be able to clear the value... decision needed here?

Error message should also accurately reflect the problem

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some inventory adjustment reasons defined in mSupply
2. Create a new stocktake
3. Add an item, reduce stock line value and provide a reason
4. In mSupply, set all reasons to inactive
5. Sync & refresh page update cached reasons
6. Go back to your stocktake and attempt to edit the line
7. Click OK
8. See error - reason does not match direction

Additional bug:

You get the same error if you:
- Have multiple neg reasons active
- Assign one to a neg stocktake adjustment
- Disable ONLY that reason
- Sync/refresh and try to edit line
- Same error message - however in this case, because other reasons are still active, you can select a new reason from the dropdown and continue

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version: 7.16

- Platform:

- Database type:

**Comment by andreievg** [comment]
Triage, high impact but quite unlikely, leaving for fortnight triage in low severity

**Comment by andreievg** [comment]
Potentially related to: https://github.com/msupply-foundation/open-msupply/issues/3696

**Comment by andreievg** [comment]
Triage: Seems like the probability is very low, suggesting to close for now, until we can think of a use case where this is a problem
