### ISSUE TITLE
GAPS: Populate Store custom fields via spreadsheet import

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4085]
## Is your feature request related to a problem? Please describe 👀

#3862 added functionality to store supplementary custom data against Stores. 

The central user needs to be able to populate this data for all Stores via a spreadsheet import. 

| User story  | B.2.16 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to bulk upload data for facilities from Excel
So that… | I don't need to update each facility manually

**Solution B.2.16**
The system will permit a bulk import of facility data to aid the central users in the scenario that the system is not distributed and therefore cannot leverage facility users to enter their own data.

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by mark-prins** [comment]
Triage: Adam says do it and we agree

**Comment by fergie-nz** [comment]
I'm wondering does this also mean we want to be able to create new stores? Or just update existing stores created in legacy?

**Comment by adamdewey** [comment]
> 
I'm wondering does this also mean we want to be able to create new stores? Or just update existing stores created in legacy?

How hard would it be to create Stores via OMS import?

The less we get them to use OG the better, but I suspect they'll still need to use it for setting up Items and Users

**Comment by marthakeezy** [comment]
No testing steps in the issue - tried importing, passed in `V2.4.0`, moving to Done ✅
