### ISSUE TITLE
GAPS: Populate Asset custom properties via spreadsheet import

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4086]
## Is your feature request related to a problem? Please describe 👀

#3868 added functionality to store supplementary custom data against Assets. 

The central user needs to be able to populate this data for all Assets via a spreadsheet import. 

| User story  | B.2.16 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to be able to bulk upload data for facilities from Excel
So that… | I don't need to update each facility manually

**Solution B.2.16**
The system will permit a bulk import of facility data to aid the central users in the scenario that the system is not distributed and therefore cannot leverage facility users to enter their own data.

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by mark-prins** [comment]
Triage: Adam says do it and we agree

**Comment by jmbrunskill** [comment]
This one should be a matter of copying the properties assignment logic similar to the Catalogue Item Import?

**Comment by marthakeezy** [comment]
There is another issue I raised and testing at the moment (#5481), so moving this one to Done ✅
