### ISSUE TITLE
Ledger table: change name 'Quantity' to 'Units'

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4089]
## What went wrong? 😲

On the ledger tab the column 'quantity' means number of Units.

Without any specification it can be confusing as to whether means 'Packs' or 'Units'.

![telegram-cloud-photo-size-1-5132363654342225164-y](https://github.com/msupply-foundation/open-msupply/assets/132425096/227e3318-0c63-4470-9cc3-b1f8bd6b3e0d)

## Your environment 🌱

Desktop app v2.1.0-IA-test-2

**Comment by andreievg** [comment]
Triage, small change, but should be recorded

I had a look label.quantity is also used in returns. Should align with inbound/outbound shipments (Unit Qty and {UnitType} Quantity, i.e Table Quantity)

Putting as normal priority, it's quick fix

**Comment by roxy-dao** [comment]
Closed in #4902

**Comment by marthakeezy** [comment]
Tested in V2.3.1-RC1, no issues -> moving to Done ✅
