### ISSUE TITLE
🌱  V2.1.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4097]
# V2.1.0 Release Testing

> [!NOTE]
> **Test Scripts** are available [here](https://github.com/msupply-foundation/open-msupply/wiki/Test-scripts), they are updated as the new features are coming out ✍🏼

## v2.1.0 NEW FEATURES/IMPROVEMENTS
- [x] #4138 - @nisha-dangol 
- [x] #4139  - @nisha-dangol 
- [x] #4141 - @santoshkhanal12 
- [x] #4144 - @marthakeezy + @AnushaUp 
     - [x] #4166 @AnushaUp 
     - [x] #4200 @marthakeezy 
     - [x] #4201 @marthakeezy 
     - [x] #4202 @marthakeezy 
    
## WORKFLOWS
These can be either one-store or multiple-store setup; depending on the workflow. 
Priority is to make sure the stock movement is functioning 

### STOCK MOVEMENT WORKFLOWS - Maria + Anusha
- [x] #4036
- [x] #4279
- [x] #4260
- [x] #4289
- [x] #4291
- [x] #4295
- [x] #4296

### NORMAL ORDERING WORKFLOWS - Tainá
- [x] #4298
- [x] #4300
- [x] #4337
- [x] #4338

## GENERAL MODULES
These can be tested in a single-store environment since they're more focused on UI 
Priority is to check/test if no buttons/modules are broken

### DISTRIBUTION - Anusha
- [x] #4311
- [x] #4317
- [x] #4318
- [x] #4319

### REPLENISHMENT
- [x] #4339
- [x] #4340
- [x] #4341
- [x] #4342

### CATALOGUE
- [x] #4155
- [x] #4307 

### INVENTORY
- [x] #4321
- [x] #4322
- [x] #4323

### DISPENSARY
- [x] https://github.com/msupply-foundation/open-msupply/issues/4312
- [x] #4320

### SETTINGS
- [x] #4301

### SYNCHRONISATION
- [x] https://github.com/msupply-foundation/open-msupply/issues/4313
- [x] https://github.com/msupply-foundation/open-msupply/issues/4314

### COLD CHAIN - Maria
- [x] #4248
- [x] #4252
- [x] #4253

### PATIENT PROGRAMS - Nisha
- [x] https://github.com/msupply-foundation/open-msupply/issues/4315

### PROGRAM REQUISITIONS - Nisha
- [x] https://github.com/msupply-foundation/open-msupply/issues/4309

### REMOTE AUTHORISATION - Santosh

- [x] https://github.com/msupply-foundation/open-msupply/issues/4353

## Testing Environment (for General Modules)
Version: v2.1.0-rc4
PC: GHM Server
[Details here!](https://docs.google.com/spreadsheets/d/1NhuMlQWVum_4XZezR0siu6ahV0RigVHMU4JDcJCN1Yg/edit?gid=88872578#gid=88872578)

**Comment by marthakeezy** [comment]
Closing as V2.1.0 is out! :)
