### ISSUE TITLE
Add soft delete for vaccine course items and vaccine schedule items in back end

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4105]
## Describe the solution you'd like 🎁

- [ ]  Add vaccine course item soft delete in backend up to graphql
- [ ] Add vaccine schedule item soft delete in backend up to graphql

**Comment by jmbrunskill** [comment]
This isn't a priority for @adamdewey more useful for testing and playing around than for real end user use cases.

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.0-build-test-2`

- [ ] On central server, go to Programs > Immunizations
- [ ] Open the detail view of a program
- [ ] Create some vaccine courses
- [ ] Use the select column to select some courses
- [ ] Select delete action, and confirm
- [ ] Your courses are deleted
