### ISSUE TITLE
Modal for linking a contact trace to a patient flickers when typing

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#4106]
## What went wrong? 😲

The model for linking a contact is flickering when typing as can be seen in the docs:

https://docs.msupply.foundation/docs/programs/program-module/#linking-a-contact-to-a-patient

## Expected behaviour 🤔

Stable modal

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.1.00`

- [ ] Setup patient programs...
- [ ] Enter a name in the Family /partner information
- [ ] Click the link button to open the modal
- [ ] The previously entered name should now be prepopulated (this was broken as well)
- [ ] When typing in the filter input the Modal should not flicker
- [ ] You should also not lose focus on the current input field

**Comment by AnushaUp** [comment]
Blocked testing by https://github.com/msupply-foundation/open-msupply/issues/4380. Will test later after the issue is fixed.

**Comment by AnushaUp** [comment]
Tested and PASSED👍
