### ISSUE TITLE
Inbound Shipment -> weird message pops up when deleting an item from Inbound Shipment

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4108]
## What went wrong? 😲

When deleting an item from a 'Delivered' Inbound Shipment, a weird message pops up #3961 

![photo_2024-06-11 15 12 03](https://github.com/msupply-foundation/open-msupply/assets/153777484/65d8f585-4814-4d21-9c4a-4a94e3a7e96e)

## Expected behaviour 🤔

A more user-friendly message should be displayed, maybe 'Item was successfully deleted' or something similar. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Inbound Shipment
2. Create a new Inbound Shipment -> add multiple items/batches
3. Confirm the Inbound Shipment as 'Delivered'
4. Try removing an item -> see the message pop up
5. Error!

## Your environment 🌱

- Open mSupply Version: v2.1.0-IA-test-2

- Platform: Android Galaxy Tab A8

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Also has this error always looked so unfriendly?

![Screenshot 2024-06-11 at 3 33 48 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/fb527042-2452-49fa-b25f-a76b061444dd)

**Comment by roxy-dao** [comment]
> Also has this error always looked so unfriendly?
> 
> ![Screenshot 2024-06-11 at 3 33 48 PM](https://private-user-images.githubusercontent.com/55115239/338424604-fb527042-2452-49fa-b25f-a76b061444dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzgxMTAsIm5iZiI6MTcxODA3NzgxMCwicGF0aCI6Ii81NTExNTIzOS8zMzg0MjQ2MDQtZmI1MjcwNDItMjQ1Mi00OWZhLWIyNWYtYTc2YjA2MTQ0NGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAzNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzY2MDUxYzE5NDlhYjEzZjFjNjY5YWEzZDU5ZWJjNDEyODc4YzY1YWRmM2Q4Nzc0OTA1ZjIzNWI3NmM5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WzMACI-CBRPiF5HqqjNYyBl1wkg3TeoNdRbsuhmei7s)

yes lol

**Comment by nisha-dangol** [comment]
Fyi, this weird message is also in v2.0.03. Will need patch fix? 🤔

**Comment by roxy-dao** [comment]
Don't think anyone will be using 2.0.3 since it does need Open mSupply central server set up, so alright to put it off

**Comment by andreievg** [comment]
Triage, not high impact but very likely, so bumping to high severity so it's more likely to be picked up in 2.2

**Comment by roxy-dao** [comment]
Tested on 2.1. Don't see the message.

**Comment by roxy-dao** [comment]
Closing as cannot replicate

**Comment by regotaina** [comment]
Tested on RC5
Desktop app

Delete works as expected, moving this to 'done' column
