### ISSUE TITLE
Amendments to vaccine course detail view

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4109]
## What went wrong? 😲

- [x] Change wording of 'Include in demand calculations' (Adam to confirm new text)
- [x] Line up 'dose #' with 'schedule' (no longer relevant with temporary removal of table)
- [ ] Change the number of doses line to be smaller
- [x] Capitalise table headers (no longer relevant with temporary removal of table)

**Comment by fergie-nz** [comment]
> @adamdewey a reminder to confirm value for this text:
> 
> ![Image 11-06-2024 at 15 18](https://private-user-images.githubusercontent.com/90807420/340842942-4abb79e0-edbd-4230-b895-b0d9381e46f5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NTE0NTEsIm5iZiI6MTcxODc1MTE1MSwicGF0aCI6Ii85MDgwNzQyMC8zNDA4NDI5NDItNGFiYjc5ZTAtZWRiZC00MjMwLWI4OTUtYjBkOTM4MWU0NmY1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQyMjUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzg3ZmE2YmYyMTdkMDI3MDQyYzBiNGVjYTM3YjlhYTIzNGE4ZWNkMzFiMjg1NjBhMWE2ZTQ4YWU0MTM1ODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-TjGG5r5Nv59dtIEOu2ogVmHqPD69f2G0ojEvV66t50)

Agreed in meeting to change to 'Enabled'

**Comment by adamdewey** [comment]
Oops, sorry missed the tag. 

I think `Active` is our standard wording for this kind of thing? 

But also I think we'll need to differentiate between a vaccine course being used for GAPS or for the vaccination card. 

So I would go with `Include in GAPS calculations` 

P.s. we should change name from `Immunization name` to `Vaccine course name`
