### ISSUE TITLE
Remove replace_into SQLite upsert implementation

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4110]
## The suggestion

Merge the SQLite and Postgres `upsert_one` implementations - diesel 2.0 appears to include on_conflict support for sqlite!

Discovered this in [this PR](https://github.com/msupply-foundation/open-msupply/pull/4065#issuecomment-2156926282), editing some fields on the `name` table via two different DSLs, found that the SQLite `upsert` implementation caused issues doing a complete replace (REPLACE INTO) of the row, rather than updating just the fields on the specified DSL.

## Example use case

In all our row repositories, we have this code:

```rust
    #[cfg(feature = "postgres")]
    fn _upsert_one(&self, name_row: &NameRow) -> Result<(), RepositoryError> {
        diesel::insert_into(name)
            .values(name_row)
            .on_conflict(id)
            .do_update()
            .set(name_row)
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    #[cfg(not(feature = "postgres"))]
    fn _upsert_one(&self, name_row: &NameRow) -> Result<(), RepositoryError> {
        diesel::replace_into(name)
            .values(name_row)
            .execute(self.connection.lock().connection())?;
        Ok(())
    }

    pub fn upsert_one(&self, row: &NameRow) -> Result<(), RepositoryError> {
        self._upsert_one(row)?;
        self.insert_changelog(...bla...)
    }
```

Now we could just have:

```rust
    pub fn upsert_one(&self, row: &NameRow) -> Result<(), RepositoryError> {
         diesel::insert_into(name)
            .values(name_row)
            .on_conflict(id)
            .do_update()
            .set(name_row)
            .execute(self.connection.lock().connection())?;

        self.insert_changelog(...bla...)
    }
```

### Why should we invest time in this?

- In moving away from mSupply Central management, it's possible we'll end up with more situations like we had for `name` ... (an existing table, originally from mSupply Central, but we want to add new columns to it which are only stored in open mSupply Central). We would need the "insert or update on conflict" rather than "replace" implementation to do this.
- Reduces code branching between PG and SQLite, which is always a good thing
- Slightly less boilerplate in the `Repository` implementations which will be nice

### Are there any risks associated with this change?

I think fairly low risk - if there is any divergence in how our `upsert`s work across PG and SQLite, that's probably a bug in the first place?

### How much effort is required?

An hour or two? Basically just gotta delete some code 👀

**Comment by andreievg** [comment]
Triage, needs refinement issue
