### ISSUE TITLE
Returns naming

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4113]
## Is your feature request related to a problem? Please describe 👀

There has been much confusion with the naming of Returns. 
Having a `Outbound Returns` under `Replenishment` causes some cognitive load (what is Outbound in this situation?) and appears not to belong with Inbound shipments.

While the naming of Outbound Returns is logical - it requires the user to know that the stock is outbound in this situation, relative to their store. In user testing to date, no one has made this understanding themselves. In the interest of having an intuitive system, we should rename the Returns. I find the In/Outbound logical, now that I understand the logic, so may struggle with the change proposed. I think we should give it a try though.

While we're here: Outbound returns has a `Reference` input, Inbounds have `Customer Ref`. There is plenty of space on the screen, and `Reference` is more informative. Please change to `Customer Reference`

At the same time, change the Outbound shipment detail view, which is likely where this came from.

## Describe the solution you'd like 🎁
Rename the following:
- [ ] `Inbound Return` to `Customer Return` 
- [ ] `Outbound Return` to `Supplier Return`
- [ ] `Customer Ref` to `Customer Reference`

**Comment by andreievg** [comment]
Triage, the po has spoken, i think we should respect that decision (plus user feedback).
Something to keep in mind is the renaming of underlying things in code

**Comment by andreievg** [comment]
another related issue: https://github.com/msupply-foundation/open-msupply/issues/3188

**Comment by marthakeezy** [comment]
Moving to Done as passed by Tainá :)
