### ISSUE TITLE
Catalogue Items List is querying twice for each render

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4116]
## What went wrong? 😲

Catalogue Items list queries twice on each render

Only occurs if user first clicks into detail view, and then clicks back to list view.

Maybe a global issue?

https://github.com/msupply-foundation/open-msupply/assets/90807420/e63ed903-9830-4394-a383-3540c3a8c73b

**Comment by andreievg** [comment]
@fergie-nz nice catch, btw the graphql network extension for chrome will tell you which query is being executed (not just graphql).

Triage, not ideal, but pretty low priority, very interesting (high chance of someone wanting to pick this up, let them)

**Comment by CarlosNZ** [comment]
Closing as per [this comment](https://github.com/msupply-foundation/open-msupply/pull/4669#issuecomment-2319718938)
