### ISSUE TITLE
Pack Qty is not invalidated/updated after repack

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4126]
## What went wrong? 😲

Pack Qty is not being invalidated after repack, so old quantity still shows on view stock detail page until refresh:

https://github.com/msupply-foundation/open-msupply/assets/55115239/f0faca28-bd3a-4806-86e6-251a00a4cf70

## Expected behaviour 🤔

Pack qty updates correctly after repack

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to stock line detail view
2. Note pack quantity
3. Repack some of that batch
4. Close repack modal
5. BUG: form still shows old pack quantity
6. Refresh page - now pack qty is accurate

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Also a question what should happen when stock line is fully repacked ? (go to new line ?)

Triage, small fix, would be great to sort out asap, since it looks broken

**Comment by andreievg** [comment]
> Also a question what should happen when stock line is fully repacked ? (go to new line ?)

Prompt to show new stock-line when all is repacked

**Comment by mark-prins** [comment]
prompt would be something like:
`All stock has been repacked and this stock line will no longer show in the list. Click OK to be taken to the new stock line.`

**Comment by lache-melvin** [comment]
Ledger tab also needs to be invalidated  - new repack log(s) don't appear until page refresh

**Comment by roxy-dao** [comment]
Closed with #4212

**Comment by nisha-dangol** [comment]
## Tests
Tested in v2.1.0-rc6

- [x] Make a repack from a Stock page. 
- [x] After closing the modal, the "Pack Qty" field should show the new (reduced) value.
