### ISSUE TITLE
GAPS: UI tweaks

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4136]
## Is your feature request related to a problem? Please describe 👀
I've noticed some UI issues with the GAPS work that I think should be tidied up:
**Summary**
- [x] Width of `Name` column in Immunisation list view
- [x] Rename `Name` column in Immunisation list view
- [x] Immunisation icon not showing
- [x] Width of name input
- [x] Store edit button
- [x] Creating a new immunisation program should take you to the new program, not leave you on the list

**Items**
* The column width of the Immunisation list view: the `Name` column - I'm not seeing my 'National immunisation register' programs very well:

<img width="284" alt="Screenshot 2024-06-12 at 5 09 18 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/e613a930-a400-4899-8e35-d1e186108b83">

* A request from Adam to name the name column `Program name` rather than `Name`

* The icon isn't showing in the breadcrumb for immunisations:

<img width="278" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/73973817-19da-4c42-9a7b-a8121735d215">

* The full width input for the immunisation program name looks odd.. can this be constrained please?

<img width="1682" alt="Screenshot 2024-06-12 at 4 02 03 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/d7c70029-94b3-4b4a-b7c6-d5a0b50db916">

* I missed the discussion about the store edit button.. and I have issues.

<img width="236" alt="Screenshot 2024-06-12 at 4 01 41 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/ce4cde7b-7964-4ef6-8f90-094bbc7ea27f">

The gear icon + `Edit` should be a button and should have a cursor change when you hover, to indicate it is clickable. 

Personally - I don't like the extra edit button. it's isolated, between store and user, while looking like both of them it behaves differently to them. it's not clear which it relates to, or if it stands alone.

what about clicking the store name opens the modal - and there you can edit the current store, and have a way of selecting a different store?
or just an edit icon (pencil). perhaps between the store icon and name.
or vertical separators, to show that the edit relates to the store

separators:
<img width="415" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/6bcd3dec-fd51-4662-bbcb-72dd984ca831">

and with the edit icon, rather than the settings icon:

<img width="411" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/fed3c60b-8f4a-4c80-b6dc-f77509ef183f">

**Comment by adamdewey** [comment]
The separators and pencil icon make it look much better!

Although I do wonder about the term `Edit` too because it's sort of not really an edit..

It's just a way to access the supplementary data section for facilities 🤔

**Comment by mark-prins** [comment]
another issue: the Edit 'button' doesn't work on DuckDuckGo
