### ISSUE TITLE
V2.1.0 Release Testing: Decimal Packsizes

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#4141]
### Basic Setup

- [x] Create a item with decimal Packsize
- [x] The items should be in Master List visible to mSupply and Open-mSupply Sites
- [x] Make items visible to Open-mSupply sites
- [x] See the items in Open-mSupply sites
- [x] The items should have decimal packsize 

#### Stock Transfer from mSupply sites to Open-mSupply sites

- [x] Create Customer Invoice with decimal Packsize and send it to Open-mSupply stores
- [x] In Open-mSupply sites, receive the items by Inbound shipments
- [x] The items in Open-mSupply should have decimal packsize as same as in CI in mSupply

#### Customer Credit (mSupply)/ Inbound Returns (Open-mSupply)

- [x] Create Customer Credit in mSupply to the Customer that is in Open-mSupply with items of decimal packsize
- [x] Finalise
- [x] Open Open-mSupply store you will see the Inbound Returns
- [x] Open related Inbound Returns
- [x] The items should have decimal pack-size as in Custome Credit

The Quantity only supports up to 2 decimal places only

![Screenshot 2024-06-18 at 16 47 35](https://github.com/msupply-foundation/open-msupply/assets/117138852/034f06e5-8733-43f2-bc7d-5e5aa14be72c)

#### Internal Orders (From mSupply to open-mSupply)

- [x] Create Internal order in Supply with to the Open-mSupply stores
- [x] Enter the items packsize to be decimal
- [x] Finalise the IO
- [x] Login to Open-mSupply store
- [x] Open the Customer Requisition list
- [x] Open the related CR
- [x] The item should have decimal packsize as created in mSupply store

### Stocktakes

- [x] Go to Inventory tab
- [x] Click on stocktakes
- [x] Click on new Stocktakes
- [x] Put the values of `Counted Packs` as decimal
- [x] It should accept the decimal

### Outbound shipments

- [x] Create a item with decimal pack size in mSupply Server
- [x] Recieve items with decimal packsize and send stocks to the OMS store
- [x] Open Inbound shipments in OMS store and Recieve the Stocks in decimal without altering the values
- [x] Now create OutBound Shipments and enter the values
- [x] Try to enter the decimal values there and you should able to enter the decimal values.

**Comment by nisha-dangol** [comment]
Just was checking shipments and some questions/bugs around decimals:
1. #4176 
2. #4175

**Comment by roxy-dao** [comment]
The changes to decimals is only for display purposes only in frontend for now. This was done mostly for migration so that invoices/requisitions don't fail to integrate...

**Comment by santoshkhanal12** [comment]
@roxy-dao 

The decimal packsize has been fixed for requistion lines as per issue: https://github.com/msupply-foundation/open-msupply/issues/3939 but the issue has not been fixed for requistion lines. Additionally, the issue still persists for 

1. CR doesn’t matches the Approved decimal value in remote authorisation
2. Returns (Inbound/Outbound)
3. Internal Orders

Issue has been made here: https://github.com/msupply-foundation/open-msupply/issues/4179

**Comment by nisha-dangol** [comment]
test-comment

**Comment by santoshkhanal12** [comment]
@roxy-dao Not an critical issue. Found decimal values would get too long: https://github.com/msupply-foundation/open-msupply/issues/4365

**Comment by santoshkhanal12** [comment]
Overall the Decimal pack sizes seems to working fine in `v2.1-00-RC6`. So, closing this.
