### ISSUE TITLE
GAPS: Demographics must be linked to year.

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4147]
## What went wrong? 😲

Because we have decided to records demographic against a `baseYear` to avoid confusion about when population growth is applied too, we now only have the option of creating demographic records against a particular year.

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/7ae00699-ec0d-4b36-8517-b0ee362033cb)

## Expected behaviour 🤔

When selecting a demographic in an immunisation program, it should be independant of the year.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login to Central OMS (with module:vaccine enabled)
2. Click on Demographics
3. Create a new demographic indicator
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/a1d53966-544b-4db1-8b40-807f4cfbf318)

4. Click on Program -> Immunisation
5. Create a Program, and Vaccine Course
6. Try to select a demographic (see the year is included)

## Your environment 🌱

- Open mSupply Version: Develop

## Agreed solution

- [ ] Create two tables, one for demographic (independent of year) and one for demographic projection (which does include the baseYear)
- [ ] Update the Vaccine Course component to select the demographic (not the projection) record.
- [ ] Automatically create both the demographic and projection on save in the Demographics Edit page.

**Comment by mark-prins** [comment]
Refinement: we'll leave up to the implementing team to refine further and report back to the refinement team if there are decisions to confirm

**Comment by lache-melvin** [comment]
Closed by #5126

**Comment by marthakeezy** [comment]
Tested in V2.3.1-RC1, all working as expected :) Done ✅
