### ISSUE TITLE
Date Inputs do not show titles or text unless interacted with

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4152]
## What went wrong? 😲

In a few areas of Open mSupply, date inputs do not have/show titles or text unless interacted with.

For example, `Inventory -> View Stock` looks like this when the filter is first applied -> 

<img width="1364" alt="Screenshot 2024-06-14 at 9 34 28 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/453f63da-d329-46ba-9bd6-318e0fa95d19">

`Replenishment -> Inbound Shipment`

<img width="1367" alt="Screenshot 2024-06-14 at 9 39 40 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/b6e7bcf8-48b0-4cf8-871c-57d1f24db256">

`Patients -> Date of Birth`

<img width="1364" alt="Screenshot 2024-06-14 at 9 46 45 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/7b644c57-11cd-4657-b7e3-3404a1e20400">

`Cold Chain -> Equipment -> Installation Date and Replacement Due`

<img width="1362" alt="Screenshot 2024-06-14 at 9 48 58 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/4c7febf2-96d7-4419-9ed4-8af4f5e7a7b5">

## Expected behaviour 🤔

Field titles and text should be showing at all times, not just when interacted with fields :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to any of the admin areas outlined above
2. Add the filter if not shown by default
3. See the error

## Your environment 🌱

- Open mSupply Version: `V2.1.0-IA-test-2`
- Legacy mSupply Central Server Version: `V7.15.00`

- Platform: Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Keeping as low severity - not breaking any workflows, though would be nice to fix as ambiguous grey boxes are a bit confusing lol

**Comment by roxy-dao** [comment]
Closed in #4225

**Comment by marthakeezy** [comment]
Checked in V2.1.0-RC5, everything is showing beautifully!! Build test passed ✅
