### ISSUE TITLE
Dose Label looses focus after each character is typed

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4159]
## What went wrong? 😲
Dose Label loses focus causing random navigation...

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Edit a vaccine course (Under Immunisation -> Programs -> Vaccine Course)
2. Try to type in to the dose label field

https://github.com/msupply-foundation/open-msupply/assets/8287373/a4cc1cd0-188f-442f-8d64-3731732db9a8

## Your environment 🌱

- Open mSupply Version: Develop

**Comment by jmbrunskill** [comment]
If there's not quick fix, I suggest we just stop rendering the table entirely as not essential for 2.1

**Comment by fergie-nz** [comment]
Not a super quick fix so will comment out the table for this release.

@lache-melvin mentioned refactoring to have table row number drive the doses number rather than the reverse which might make this safer and easier to manage.
