### ISSUE TITLE
Supply Interval Missing from GAPS Setup data

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4160]
## What went wrong? 😲

For dashboard calculations, we need to know the supply interval, and safety buffer stock for each facility.

## Expected behaviour 🤔

Should be visible in the store property configuration

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/0900b499-77d9-4927-a06b-c3972801f662)

## How to Reproduce 🔨

Setup

Configure GAPS properties under Settings on OMS Central Server

Steps to reproduce the behaviour:

1. Open a store under Mange -> Facilites
2. See if you can populate `Supply Interval` and `Buffer Stock`

## Your environment 🌱

- Open mSupply Version: Develop

**Comment by adamdewey** [comment]
Nice James - these fields should be editable on the remote site

Can we also add a unit of `months` too (or an info icon that explains it)
