### ISSUE TITLE
Hardcode filtering out of patients from names query

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4161]
NOTE: maybe this is a bug - the `type` property on the NameFilterInput now doesn't work, it gets overwritten in the service layer by a `type != PATIENT` filter... haven't _seen_ any other issues in the actual UI from it though 🤷‍♀️

## The suggestion

Context: #4146

Issue introduced by #4023

We have a `names` query endpoint, and a different one for `patients`. We only use the `names` one for non-patient related things, so we should hard code the filtering out of patients into the repository layer. 

We should then also remove the `NameNodeType::Patient` and `isPatient` options from the NameFilterInput, to make it clear its not possible to query patients via the name endpoint

### Why should we invest time in this?

Our API inputs should accurately reflect what you are able to get back!

Finish off the teasing apart of store/facility and patient, so we don't need to constantly consider this filtering while devving.

### Are there any risks associated with this change?

Just checking all the queries still work as expected?

### How much effort is required?

Couple hours?

**Comment by andreievg** [comment]
Please check that filters in front for name still work (not sure if all of it is type safe?)

**Comment by roxy-dao** [comment]
relocate: GenderInput from Name to Patient in graphql

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Make sure suppliers/customers are still loaded correctly
- [ ] Make sure that prescriptions can still be created
- [ ] (dev) Call name API with graphql. Patients shouldn't show at all even without filtering.

**Comment by AnushaUp** [comment]
> [ ] Changing patient gender should still work

@andreievg @roxy-dao Changing patient gender not saved in omsupply.

**Comment by AnushaUp** [comment]
Seems like some problem with datafile. Moving this issue to done.✅
