### ISSUE TITLE
Remove the `as Type` usage in the demographics pages

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4171]
Note: while cleaning up demographics page, would be great to remove the `as Type` usage - if we're needing it then we're doing something wrong with the types, and should fix that instead!

_Originally posted by @lache-melvin in https://github.com/msupply-foundation/open-msupply/issues/4075#issuecomment-2171928330_

**Comment by mark-prins** [comment]
Unsure at this stage if removal is a go, I'd settle for reduced usage at this stage

**Comment by lache-melvin** [comment]
closed by #4216

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.1.00`


- [ ] Create some new demographic indicators
- [ ] Mess with the Growth percentages
- [ ] Everything still behaving as expected

**Comment by AnushaUp** [comment]
Calculations looks good👍
