### ISSUE TITLE
Can't enter exact decimal value under 'Pack Qty Issued' column in item-line in Outbounds

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4175]
## What went wrong? 😲
Can't enter exact decimal value under `'Pack Qty Issued'` column in item-line in Outbounds

## Expected behaviour 🤔
should input the exact value as long as I enter the quan <= available quan

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Have some decimals packs available for at least an item in your store
2. Open an Outbound and add that item 
3. Issue out any quantity. It'll use existing item lines
4. Now under particular batch line (with decimals packs available), try to type in some decimals. For eg: type `1.1`
5. See error: system automatically changes it to available quan. Eg: Let's say you have `5.5` packs available, on typing `1.1`, it automatically changes to `5.5`

In Android, it simply won't enter the decimal at all. 
In browser, it takes in the decimal-point (.), but automatically updates it to available-quan

## Your environment 🌱

- Open mSupply Version: v2.1.0-decimal-testing exe
- Legacy mSupply Central Server Version: v7-15-03

- Platform: server exe + browser(chrome) 

- Database type: sqlite

**Comment by andreievg** [comment]
Triage, needs refinement (want to discuss with wider team how to solve this), severity high and RC milestone to look at it asap

**Comment by andreievg** [comment]
Refinement: Can do decimal on individual line, not on the top left issue box.

Follow up, look at this issue: https://github.com/msupply-foundation/open-msupply/issues/3252

**Comment by roxy-dao** [comment]
Only backend changes were made for decimals. Can this be moved to 2.2 with the Epic since it will require a lot of areas to be changed?

**Comment by roxy-dao** [comment]
Closed in #4258

**Comment by santoshkhanal12** [comment]
Tested on `v2.1.00-rc6`

# 🧪 Testing



- [x] Have some item with fractional packs
- [x] Create `Outbound Shipment` with this item
- [x] Enter some decimals

It allows the decimal. But when you put the decimal packsize really weird. It displays long zeros of quantities.

![Screenshot 2024-07-04 at 11 04 31 AM](https://github.com/msupply-foundation/open-msupply/assets/117138852/4518517c-b64f-4a0b-aaad-1924a8af597e)
