### ISSUE TITLE
Customer Requistion doesn’t accepts the decimal Values that came form mSupply sites via Internal Orders and remote auth

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#4180]
## What went wrong? 😲

![Screenshot 2024-06-18 at 16 55 03](https://github.com/msupply-foundation/open-msupply/assets/117138852/ce8f6b5c-ffaa-48b6-9353-9ad459d38850)

![Screenshot 2024-06-18 at 15 37 26](https://github.com/msupply-foundation/open-msupply/assets/117138852/af8a641e-94dd-4d92-863a-94551efbe0e5)

## Expected behaviour 🤔

The decimal values in Customer Requisition should also synced.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. mSupply and Open mSupply Setup
2. Make sure items are visible on both mSupply Store and Open mSupply Store
3. Create IO form mSupply store for Open mSupply Store
4. Enter the Requested quantities in decimal
5. Finalize the IO
6. SYNC
7. See the related CR on Open mSupply Store
8. See the decimal Values not synced (BUG)
9. Same issue for by remote auth (BUG)

## Your environment 🌱

- Open mSupply Version: v2.1-decimal
- Legacy mSupply Central Server Version: v7-16-00-dev10
- Platform: Browser
- Database type: SQLite

**Comment by andreievg** [comment]
Triage, needs refinement (want to discuss with wider team how to solve this), severity high and rc milestone to look at it asap

**Comment by roxy-dao** [comment]
Do requisitions deal in pack size of 1? What does it mean to order 1.5323 of something?

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Have two sites (one OMS and one OG)
- [ ] Create an Internal Order in OG to send to OMS
- [ ] Enter some decimal in requested (e.g. 1.224131)
- [ ] Sync
- [ ] Go to OMS -> Requisitions
- [ ] Requested amount in requisition should be in decimals
