### ISSUE TITLE
Can't increase stock by decimal pack less than 1.0

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4194]
## What went wrong? 😲

Trying to increase by 0.5 packs, get pack size less than one error:

![Screenshot 2024-06-19 at 2 08 53 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/d72b1e1a-9a05-42ff-917a-80afba3157e8)

Thinking this is a conflict issue between StockIn refactor and decimal packs work?

## Expected behaviour 🤔

Seeing as you _can_ increase by 1.5 packs, you should be able to increase by 0.5!

Other parts of the UI, you can't enter decimal # packs, not sure why you can here?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Stocktakes
2. Create a new stocktake
3. Add a stock line
4. Increase # packs by <1.0 (e.g. 0.5 packs increase)
5. Finalise stocktake 
6. See error 

## Your environment 🌱

- Open mSupply Version: 2.1 
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Added high sev, because if we allow decimal adjustments then this needs to be resolved, but going by other areas of the app I think decision needed on what should be possible here?

**Comment by andreievg** [comment]
Triage, needs refinement (want to discuss with wider team how to solve this), severity high and rc milestone to look at it asap

**Comment by jmbrunskill** [comment]
Refinement: This looks like it was working in previous version, so looks like an introduced bug...

**Comment by lache-melvin** [comment]
Closed by #4223

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC5, was able to save without any errors. Build test passed ✅
