### ISSUE TITLE
CCEI: Remove `Voltage stabilizer` from PQS category E004 (Insulated containers)

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4203]
## What went wrong? 😲

Insulated containers don't have any power and so would never have a voltage stabilizer so we should remove this field: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/24049f35-500f-4350-935b-de4247a0609b)

## Expected behaviour 🤔

No `Voltage stabilizer` field for category E004

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.1.0

**Comment by lache-melvin** [comment]
Closed by #4211

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC2 and the field is no longer there :) Moving to Done ✅ 

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/dce66c4b-b7cb-4308-94d4-41a46012cdd4)
