### ISSUE TITLE
GAPS: Change wording of `Enabled` in Vaccine Course

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4205]
## What went wrong? 😲

There is a checkbox `Enabled` which controls whether the vaccine course will be included in GAPS calculations. 

However the vaccine course will also be used for the patient vaccination card and so it's not clear to the user what the `Enabled` box refers to - GAPS functionality or vaccination card functionality, or both?

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/fa21f1f4-b115-46f8-ac3f-58f457e683d6)

## Expected behaviour 🤔

It would be better to be explicit and name it `Include in GAPS calculations`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.1.0

**Comment by lache-melvin** [comment]
Closed by #4208
