### ISSUE TITLE
GAPS: Add `%` unit to `Coverage rate` and `Wastage rate` for vaccine courses

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4219]
To make it clear to the user we should add the units for `Coverage rate` and `Wastage rate` fields in the vaccine courses. 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/d9b88274-4933-4dc2-8e6c-970ab9564ef3)

## Describe the solution you'd like 🎁

Units are `%`

**Comment by lache-melvin** [comment]
Should they also allow decimal inputs? If so to what precision?

**Comment by adamdewey** [comment]
Hmm, I think it would be nice to allow them 1 decimal place?

Can't imagine they'll ever get to that accuracy, but it could be frustrating if they wanted to and couldn't

**Comment by roxy-dao** [comment]
Closed in #4243
