### ISSUE TITLE
iSC/GAPS/Cold Chain: Cold chain -> Equipment -> Asset with no store assigned cannot be updated/saved after editing due to an error

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4229]
## What went wrong? 😲

Cold chain -> Equipment -> Asset with no store assigned cannot be updated/saved after editing due to an error. An error 'LocationDoesNotBelongToStore' pops up anytime I try to save an asset.

Other findings: once you create an asset with no store assigned, and go in to assign it to a store to resolve the problem, the error still prevents you from doing so. 

![photo_2024-06-21 15 13 13](https://github.com/msupply-foundation/open-msupply/assets/153777484/e11a0a97-6c7f-4c97-b62a-fc4a2c0d340e)

## Expected behaviour 🤔

Updates can be saved successfully, without an error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment
2. Try and create an asset but don't assign a store (it should be created with no issues)
3. Go to the same asset and edit a small detail -> press Save -> encounter error

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC1 (Central Server)
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closed by #4236
