### ISSUE TITLE
iSC/GAPS/Cold Chain: Cold chain -> Equipment -> Asset: when closing the window with unsaved changes, the alert window looks different to the rest of Open mSupply alert windows/interface

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4230]
## What went wrong? 😲

Low priority - iSC/GAPS/Cold Chain: Cold chain -> Equipment -> Asset: when closing the window with unsaved changes, the alert window looks different to the rest of Open mSupply alert windows/interface. 

![photo_2024-06-21 15 38 07](https://github.com/msupply-foundation/open-msupply/assets/153777484/a71df0dc-35f8-4650-a86e-6e19cab88abe)

## Expected behaviour 🤔

Should look something like this: 

![photo_2024-06-21 15 39 40](https://github.com/msupply-foundation/open-msupply/assets/153777484/b273ae39-1ddd-4166-973c-b417a6a78bb0)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment -> Asset, and create a new Asset
2. Start editing it and press the 'X' button to cancel any unsaved changed
3. See the alert window

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC1
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

**Comment by mark-prins** [comment]
that's a browser dialog - and we are unable to change the style of it.
( side note: react router used to have support which would allow us to capture the event and modify the alert but that was dropped in the major version bump. it was possibly going to come back but hadn't yet )

so.. we are unable to change the style of that prompt
