### ISSUE TITLE
iSC/GAPS/Cold Chain: Manage -> Facilities -> Gas Availability has a typo (Not Availability)

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4231]
## What went wrong? 😲

Manage -> Facilities -> Gas Availability has a typo - `Not Availability` instead of `No Availability`

![photo_2024-06-21 15 47 40](https://github.com/msupply-foundation/open-msupply/assets/153777484/609ac902-5905-4b23-b8c5-e99e5b11cec7)

## Expected behaviour 🤔

Should say `No Availability`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Manage -> Facilities -> select a Facility and try editing it
2. Go to Gas Availability -> see typo

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC1
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

**Comment by CarlosNZ** [comment]
Someone could almost just chuck this in as part of any other PR they're doing this week?

**Comment by lache-melvin** [comment]
Closed by #4245

**Comment by marthakeezy** [comment]
@lache-melvin just FYI, the bug came back with V2.3.0-RC1 

<img width="709" alt="Screenshot 2024-09-26 at 4 27 07 PM" src="https://github.com/user-attachments/assets/f5d7e98b-de3d-47d6-a1ab-4bc017f15bea">

**Comment by lache-melvin** [comment]
Closed (again 😁) by https://github.com/msupply-foundation/open-msupply/pull/4962

**Comment by marthakeezy** [comment]
No typo in V2.3.0, moving to Done ✅
