### ISSUE TITLE
Layout bug with multi-item filters

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#4233]
## What went wrong? 😲

I *think* this is only a problem with multi-element filters (like Date range).

If you add a single filter after a "Range" filter (like Date), the order gets messed up when you change focus.

For example, the "Code or Name" filter jumps to the beginning after clicking in one of the Date filters:

![2024-06-21 15 55 10](https://github.com/msupply-foundation/open-msupply/assets/5456533/cd98cf5d-ff95-4ffb-8053-591255c7720a)

## Expected behaviour 🤔

Filter order should persist during interaction.

## How to Reproduce 🔨

1. On "View Stock" list page, add an "Expiry" filter
2. Add a "Code or Name" filter -- it should appear after the two date inputs
3. Click in one of the Date inputs. Then click elsewhere on the page
4. the "Code or Name" filter jumps to the start of the filter line. 😢

## Your environment 🌱

- v2.1.0-rc1
- Desktop
- Firefox browser

**Comment by CarlosNZ** [comment]
I suspect that the multi-item filter is sometimes getting treated as a single array element (it's nested as a single item in Filter Definitions), and other times as two elements, which causes a discrepancy.

**Comment by CarlosNZ** [comment]
Not high priority, but also should be a fairly easy fix.

**Comment by mark-prins** [comment]
Here's another instance, from @marthakeezy 


https://github.com/msupply-foundation/open-msupply/assets/9192912/465e9656-321f-41c4-83cd-e91401131130

**Comment by andreievg** [comment]
Triage, normal priority, doesn't break workflow, but needs looking into at some stage

**Comment by marthakeezy** [comment]
Looks like the filters are fixed when played around with on the same page, but seem to change order when jumping between tabs?

https://github.com/user-attachments/assets/fa1a250d-0e15-44fd-8d5c-c72ca77c765b

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC1

This issue is build test passed, so moving to Done ✅ 

However, as per conversation with @CarlosNZ, raised #4889 for a slightly different issue :)
