### ISSUE TITLE
Coldchain Equipment list shows equipment for all active stores on remote site

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4235]
## What went wrong? 😲

Have a remote site with 2 stores: Opua and Kawakawa

On central, create an asset for Kawakawa:

![image](https://github.com/msupply-foundation/open-msupply/assets/55115239/bbc67dc2-1650-4709-94fd-26225ad9aedd)

On remote, logged into Opua, can see Kawakawa asset?

![Screenshot 2024-06-21 at 4 29 16 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/adacd2bb-98da-4e59-8ab1-80d94f1fc5df)

## Expected behaviour 🤔

I only see my store's assets when looking at my store...

If clients aren't really doing multi-store this is probably low priority though 😅 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Follow steps above 🙈 

## Your environment 🌱

- Open mSupply Version: 2.1 RC 1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by adamdewey** [comment]
Good catch Laché!

**Comment by lache-melvin** [comment]
Closed by #4316

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in OMS V2.1.00-rc6


- [ ] Have a remote site with at least two stores (both with vaccine module enabled)
- [ ] On one store, add some cold chain assets
- [ ] log in to the other store 
- [ ] You CANNOT see the assets from the first store
- [ ] Log into central
- [ ] You can still see the assets for all stores
