### ISSUE TITLE
Status set as cancelled but pop up for save encountered as visited appears

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4250]
## What went wrong? 😲

Unsure if this is bug or expected behaviour.

![Screenshot 2024-06-24 at 2 54 49 PM](https://github.com/msupply-foundation/open-msupply/assets/143057869/6e35b4a1-ae7b-447a-8871-05c8d81d8c1f)

When Encounters status is saved as "Cancelled" and you click save, a pop up appears and asks if you would like to save encounter as visited. Feels like it would be easy to make the mistake of selecting "Save as visited" which changes the status from cancelled to visited.

## Expected behaviour 🤔

If the status is selected as "Cancelled" wonder if it should just prompt as "Save encounter as cancelled" and then you select either "save" or "cancelled" and not have the third option of "save as visited".

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

open msupply, programs hiv module

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC9 on a Desktop, the pop-up is not appearing anymore and the status can be saved as Cancelled. Moving to Done ✅
