### ISSUE TITLE
Cant login issue

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4254]
## What went wrong? 😲

Cannot log in to remote sites

## Expected behaviour 🤔

Should be able to log in

## How to Reproduce 🔨

Use this test data file: 
[simple sync site 2.4DD.zip](https://github.com/user-attachments/files/15950276/simple.sync.site.2.4DD.zip)

You can use username 'config' to do the registration etc.. (in og mSupply)

Initialise central omSupply site, with 'central'/'pass', log in with 'test'/'pass', go do admin, then configuration and 'initialise', make changes to 'test' facility data.

Now try to initialise remote site with 'test'/'pass', log in with 'tests'/'pass', should see error

## Problem and suggested fix

I think the issue is with having record_id unique in sync_buffer and om_name_fields together with name table having the same record_id (name arrives from og central, added to sync buffer, and then om_name_fields arrive from om central, and overwrite og central name in sync_buffer, then store is unable to integrate due to FK constraint).

Suggest to add table_name to record_id in sync buffer here: 

https://github.com/msupply-foundation/open-msupply/blob/1027722f6c47dd3187f6892207c300ef10b096de/server/service/src/sync/api/common_records.rs#L90-L91

## Your environment 🌱

2.1.0-RC2, both in dev env

**Comment by roxy-dao** [comment]
Closed in #4256

**Comment by marthakeezy** [comment]
Both Adam and I can login now, so build test passed ✅
