### ISSUE TITLE
iSC/GAPS/Cold Chain: 'Edit' button does not appear for Remote Sites after initialising GAPS

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4262]
## What went wrong? 😲

After initialising GAPS on Central Server, I noticed the 'Edit' button did not appear for my Remote Site after synchronising. It only appeared after closing the app and logging out and in again. 

## Expected behaviour 🤔

The button should appear for Remote Sites straight after synchronisation, not after logging out and in again. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have your Central Server set up and a Remote Site to test
2. Initialise GAPS on Central Server
3. Go to your Remote Site -> make sure you are logged in prior to testing -> synchronise
4. See the issue - the 'Edit' button does not appear
5. Log out and in again
6. See the 'Edit' button appear now

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows (Central Server) & Galaxy A8 Tablet app (Remote Site)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Going to close this one - its similar to the discussion in #3696, but I think even more edge case...

When remote syncs, we don't invalidate any data (though we are working towards this design eventually) - so the footer doesn't immediately know to update. 

However, you don't even need to log out and in again, just navigating to another page seems to do it for me. Given it's a one time set up, I don't see this being an issue, and may be resolved in future with some kind of post-sync invalidation step
