### ISSUE TITLE
iSC/GAPS/Cold Chain: funky Demographic Growth number behaviour

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4264]
## What went wrong? 😲

I am unsure of how to describe this behaviour, but it looks like when saving growth percentage, the numbers don't immediately reflect the change? For example: 

* Growth is set to be 10%, but the population numbers stay the same
* After navigating away and returning, the growth number reverts back to 0%
* After setting growth to be 10% again, changes took effect
* After navigating away and returning, the growth number again reverts back to 0% but the population numbers show accurately

https://github.com/msupply-foundation/open-msupply/assets/153777484/5e7f6bb5-d424-476f-ae29-4aaa2e38c859

## Expected behaviour 🤔

If growth % is entered, it should be saved and remain the same regardless if you navigate away from the page or not. Similarly, population numbers should increase by the right number - if it's 10% growth from a million people, the new number should be 1,100,000. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Manage -> Demographics
2. Set your population to a certain number (mine was 1,000,000)
3. Play around with the growth percentage fields - set them to 10%, 0%, negative amount
4. Navigate out and back to the Demographics page to see the changes in-between
5. Note the inconsistencies 

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closed by #4277
