### ISSUE TITLE
iSC/GAPS/Cold Chain: inconsistent House Icon 🏠 display under 'Facilities'

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4270]
## What went wrong? 😲

When changing the number of facilities shown per page, the house icon 🏠 is shown inconsistently. 

Error captured on [this video](https://drive.google.com/file/d/1E-KxeA6OnxmL2lm2CWMli8qW7xiIo_Dl/view?usp=drive_link) :)

## Expected behaviour 🤔

I am not sure we need to have a house icon all together - the list only shows stores, right? If we decide to keep it, it should be displayed consistently

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Manage -> Facilities
2. Change the number of rows displayed per page from 20 to 50 to 500 (play around)
3. See inconsistency

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite 3

**Comment by andreievg** [comment]
Triage, very small fix to just remove the column because they are all stores. Squeeze into 2.1

**Comment by marthakeezy** [comment]
No more houses!! Build test passed ✅
