### ISSUE TITLE
customer-credit from OG should not be mapped as outbound-return

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4271]
## What went wrong? 😲
Existing returns to oms-stores are mapped incorrectly after migration

## Expected behaviour 🤔
customer-credit from OG should not be mapped as outbound-return

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have two setups in sync: one oms-storeA and one OG desktop-storeB
2. From oms-storeA, create a outbound-return(supplier-credit) to desktop-storeB. Confirm `shipped` and sync
3. In desktop-storeB, receive that as customer-credit(inbound-return).
4. Do nothing. Don't finalise
5. Just make sure, till this point desktop is all synced.
6. Now migrate desktop-storeB to oms, i.e., reset hardware ID's from cloud and re-initialise storeB completely
7. Login to newly migrated oms-storeB
8. Check Inbound returns(customer-credits)
9. See error: the return is missing
10. Check Outbound returns(customer-credits); see another error: cc is showing as outbound-return
11. Why not also check the original outbound-return from oms-storeA to realise both there oms-stores have only outbound-returns here.

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc3
- Legacy mSupply Central Server Version: v7-15-06

- Platform: apk

- Database type: sqlite

**Comment by andreievg** [comment]
Triage, needs to investigate and fix in 2.1 if possible or early 2.2

**Comment by roxy-dao** [comment]
Possible OG problem when creating transfer... om_type is `OutboundReturn`?

**Comment by roxy-dao** [comment]
#4331

**Comment by nisha-dangol** [comment]
Tested in v2.1.0-rc6. cc are mapped correctly now - PASS
