### ISSUE TITLE
Line totals are not migrated properly

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4273]
## What went wrong? 😲
Line totals are not migrated properly

## Expected behaviour 🤔
Totals should be mapped correctly

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Have a OG desktop site with line totals
2. Migrate it to oms; i.e., reset hardware ID and reinitialise
3. Login to oms
4. Revisit those previous transacts with line totals
5. See error: line totals is 0 despite the value. Also, notice that Foreign currency total. Looks weird to me.

![image](https://github.com/msupply-foundation/open-msupply/assets/59193490/6006797e-02b7-480f-a5be-471850959532)

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc3
- Legacy mSupply Central Server Version: v7-15-06

- Platform:apk, browser(chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
Currency total issue #3994

**Comment by nisha-dangol** [comment]
> Currency total issue #3994. The totals are coming over just fine for me... can you give me the datafile you're using?

Sure, [here's the link](https://drive.google.com/drive/folders/147a8Aca6CvJ1b3sqq-F_5LiQCoU5pU9N?usp=drive_link) to the datafile. Credentials for test303 store-user: user: test3, pass:1234

**Comment by roxy-dao** [comment]
> > Currency total issue #3994. The totals are coming over just fine for me... can you give me the datafile you're using?
> 

Can see it in the datafile you provided... did you do anything else?

I created a fresh datafile and created invoices with totals in OG then transferred to OMS site and totals are there 👀

**Comment by nisha-dangol** [comment]
> Can see it in the datafile you provided... did you do anything else?
> 
Nothing any specific, I was adding some tax values and multiple currencies previously. But in recent transactions, I was creating just normal transactions

> I created a fresh datafile and created invoices with totals in OG then transferred to OMS site and totals are there 👀
>
Ok, will retry with new datafile in rc4 and check

**Comment by nisha-dangol** [comment]
> Ok, will retry with new datafile in rc4 and check

Tried with the new datafile (used Example datafile this time) and I still see the same results.
Totals from OG is not migrated properly when the same store is migrated to oms.

**Comment by roxy-dao** [comment]
Closed in #4346

**Comment by nisha-dangol** [comment]
Tested in v2.1.0-rc6. Totals looks good now - PASS
