### ISSUE TITLE
Tax displays incorrectly on totals below $1 in outbound shipments

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4280]
## What went wrong? 😲

Seems fairly edge case (maybe less so for service charges?) but still a bit random...

If sub-total is less that $1, the tax percentage display gets confused - seems to show the whatever the tax value as a percentage, rather than the tax percentage?

In this case, I set tax to 50% for both the service charge and the items, which you can see the totals are calculated correctly, but the percentages are then 40% and 10%:

<img width="288" alt="Screenshot 2024-06-26 at 12 02 11 PM" src="https://github.com/msupply-foundation/open-msupply/assets/55115239/8d342ae9-7088-4160-a19b-bffba20b38eb">

When you open the tax edit modal, it correctly shows `50` before refreshing the page, then it shows incorrectly (e.g. 10).

## Expected behaviour 🤔

Tax percentage displays the tax percentage 👀 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Outbound Shipment
2. Adds some items and/or service charges where total adds to less than a dollar
3. Add tax percentage
4. See tax percentage displayed is not the tax percentage you entered

## Your environment 🌱

- Open mSupply Version: 2.1 RC
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Triage, if it's just a front end bug then we can get it into 2.1, but if large problem then can be carried over to 2.2

**Comment by andreievg** [comment]
Related: https://github.com/msupply-foundation/open-msupply/issues/4281

**Comment by roxy-dao** [comment]
Closed in #4330

**Comment by regotaina** [comment]
# 🧪 Testing



- [ ] Create an outbound shipment
- [ ] Add lines with sell price less than $1
- [ ] Add tax
- [ ] Should calculate tax correctly

- [ ] Have service line in master list for store
- [ ] Add multiple service charges with different tax percentages
- [ ] Tax percentage and total should calculate correctly

**Comment by regotaina** [comment]
Passed the test 🥇 

![Image](https://github.com/msupply-foundation/open-msupply/assets/132425096/e2b280cd-d038-47d6-b349-6276f53b5e5f)
