### ISSUE TITLE
Inbound shipment: tax percentage is being displayed as the tax value

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4281]
## What went wrong? 😲

When tax is 10%, it shows as $10:

<img width="300" alt="Screenshot 2024-06-26 at 1 53 10 PM" src="https://github.com/msupply-foundation/open-msupply/assets/55115239/6e91796f-24a0-45ec-89a8-312c9ab7fda3">

## Expected behaviour 🤔

should show $30, not $10!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. create an Inbound shipment
2. Add a line with a cost price per pack, so you end up with a stock total
3. add tax to total
4. See tax total is the percentage number, not the calculated amount of tax to pay!

## Your environment 🌱

- Open mSupply Version: 2.1 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Triage, same as https://github.com/msupply-foundation/open-msupply/issues/4280:

**Comment by mark-prins** [comment]
While looking at the inbound tax - would it be possible to add a `%` end adornment to the percentage input please?
I added a service charge and it isn't clear that the tax is a percentage in this modal:

<img width="1063" alt="Screenshot 2024-06-27 at 1 05 24 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/db2d4cb4-197c-4116-ac6c-29fb5743ae15">

This one could do with a `%` as well:

<img width="589" alt="Screenshot 2024-06-27 at 1 05 11 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/6c585df2-14da-4f88-8d06-c943ef769cb5">

**Comment by roxy-dao** [comment]
Closed in #4329

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC5, no issues found - build test passed! ✅ 

![Image](https://github.com/msupply-foundation/open-msupply/assets/153777484/7783ca8c-ed29-4f1e-ad15-c1f91045b2f5)
