### ISSUE TITLE
iSC/Cold Chain: when importing a list of Cold chain equipment, the template does not match an exported list

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4284]
## What went wrong? 😲

Me and @AnushaUp noticed, that when you export a list of Cold Chain Equipment under `Cold chain -> Equipment -> Export`, the file template is not the same we need for import. When importing that same file, we run into the following error: 

![photo_2024-06-26 16 35 59](https://github.com/msupply-foundation/open-msupply/assets/153777484/220849b4-33a8-4caf-9bf0-2725638d5ba2)

Seems like **Store** and **Catalogue** columns are removed while exporting the lists.

## Expected behaviour 🤔

It would be helpful to have the export and import in identical formats :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment -> Export
2. Save the file
3. Go to Cold chain -> Equipment -> Import
4. Try importing the file you just saved without changing anything
5. See error

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop app for Windows

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closed by #4302

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.1.0 `


- [ ] Coldchain -> equipment -> import
- [ ] click download template
- [ ] reupload that template
- [ ] it works (albeit dates won't parse)
- [ ] on list view, click export
- [ ] try to import that
- [ ] you can view the data in the table (though import will fail on duplicate asset numbers)

**Comment by AnushaUp** [comment]
> [ ] it works (albeit dates won't parse)

@lache-melvin Hi, why is this happening? 

![Screenshot 2024-07-26 at 3 05 43 pm](https://github.com/user-attachments/assets/03461182-b754-4dbb-bb65-587612776ec2)

**Comment by AnushaUp** [comment]
@lache-melvin it was due to the time entry. Works fine otherwise 👍✅

**Comment by lache-melvin** [comment]
> Hi, why is this happening?

@AnushaUp Yep, due to trying to import blank date/time fields 🙏
