### ISSUE TITLE
iSC/Cold Chain: remove checkboxes if no actions can be performed

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4286]
## What went wrong? 😲

Catalogue -> Assets cannot be removed on Remote Site, however the checkboxes to select them are still there. Actions cannot be performed so for cleaner design, checkboxes should be removed all together :)

![screenshot-1719378352354](https://github.com/msupply-foundation/open-msupply/assets/153777484/99c62e18-2864-4287-9d80-91cc9d2573bd)

## Expected behaviour 🤔

Actions cannot be performed so for cleaner design, checkboxes should be removed all together :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Assets on your **Remote Site**
2. Scroll to the right and note the checkboxes
3. They can be ticked & unticked, however no actions can be performed since assets cannot be edited on a remote site, only on Central Server
4. The checkboxes should not be there :)

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Android Galaxy A8 Tab 

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closed by #4288

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in mSupply `V2.1.0`


- [ ] On central server, catalogue > assets, you can see the select column
- [ ] On remote site, catalogue > assets, you CANNOT see the select column

**Comment by AnushaUp** [comment]
Since this issue is not valid anymore, Moving this to done.
