### ISSUE TITLE
Rename the necessary dropdown fields into 'Actions' instead of 'Select'

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4287]
## What went wrong? 😲

In some areas of omSupply, 'Actions' dropdown appears as 'Select. Areas spotted: 

- Distribution -> Inbound Returns
- Replenishment -> Outbound Returns

Correct: 
![photo_2024-06-26 17 38 29](https://github.com/msupply-foundation/open-msupply/assets/153777484/11901427-b1b5-4033-bb4b-fa46e9489fae)

Incorrect:
![photo_2024-06-26 17 38 32](https://github.com/msupply-foundation/open-msupply/assets/153777484/e20640c3-6c99-471a-b3a8-e931662b12c2)

## Expected behaviour 🤔

We should rename those into 'Actions' :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Distribution -> Inbound Returns
2. See inconsistency 
3. Go to Replenishment -> Outbound Returns
4. See inconsistency

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop app for Windows and omSupply for Galaxy A8 Tablet

- Database type: SQLite3

**Comment by andreievg** [comment]
Triage, should be quick fix, thus setting higher priority so that it's quickly done

**Comment by roxy-dao** [comment]
Closed in #4304

**Comment by marthakeezy** [comment]
Checked in V2.1.0-RC5, no issues found. Build test passed ✅
