### ISSUE TITLE
V2.1.0 Release Testing • Stock Movement Workflow: Repacks

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4291]
# Repacks

**Repack all packs from 1 specific item line**
- [x] Go to 'stock' and choose a stock line to be tested. Take notes of the batch.
- [x] Click on the stock line and on the button 'repack'
- [x] Choose to repack all available packs
- [x] Double the package size. If pack size =1, make it 2, for example.
- [x] Confirm the repack 
- [x] Automatically the ledger tab will have the total quantity repacked with a negative sign. If repacked 80 packs, it will show -80
- [x] Go back to item's stock view and use the filter to find the item you chose to test. New stock lines should have been created with the correct pack size.
- [x] You should not be able to see any lines containing the old pack size.
- [x] Check the ledger tab. The changes via repacks should have created a new ledger line

**Repack only a few packs from 1 specific item line**
- [x] Go to 'stock' and choose a stock line to be tested. Take notes of the batch.
- [x] Click on the stock line and on the button 'repack'
- [x] Choose to repack only half of the available packs
- [x] Double the package size. If pack size =1, make it 2, for example.
- [x] Confirm the repack 
- [x] Automatically the ledger tab will have the total quantity repacked with a negative sign. If repacked 20 packs, it will show -20
- [x] Go back to item's stock view and use the filter to find the item you chose to test. New stock lines should have been created with the correct pack size.
- [x] Go back to items view. The old pack size should be there, with the remaining packs you did not repack. 
- [x] Check the ledger tab. It should  have the total quantity repacked with a negative sign. If repacked 20 packs, it will show -20.

**Comment by marthakeezy** [comment]
Moving to Done :)
