### ISSUE TITLE
Lines missing in SI after mobile-migration

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4305]
## What went wrong? 😲
From [here](https://github.com/msupply-foundation/open-msupply/issues/4139#issuecomment-2177911790): Lines missing in SI after mobile-migration

## Expected behaviour 🤔
no lines should be missing in transaction after migration

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have two mobile stores setup.
2. Create CI from mobile-storeA to mobile-storeB
3. In mobile-storeB, receive SI, don't finalise yet
4. Make sure everything is synced till this point
5. Migrate storeB to oms. In Cloud, remove hardware, and reinitialise oms from scratch
6. Now oms-storeB; open that unfinalised SI
7. See error: no lines at all

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc4
- Legacy mSupply Central Server Version: v7-15-06

- Platform: apk, browser(chrome)

- Database type: sqlite

**Comment by andreievg** [comment]
Daily Triage, hot fix, if we are saying that 2.1 allow for migrations from mobile, this needs to be working

**Comment by roxy-dao** [comment]
Closed in #4347

**Comment by nisha-dangol** [comment]
Tested in v2.1.0-rc5. Lines are now appearing correctly, it's a PASS.
Just one minor thing; would have been good if the Inbound showed as `Shipped` rather than `New` since it was created from mSupply-store (mobile-OG) after all. 

<img width="1193" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/defcecf9-e7a8-4f0b-a9f3-236b77e50b92">

@andreievg  Is this worth fixing or we can just ignore?

**Comment by nisha-dangol** [comment]
> Tested in v2.1.0-rc5. Lines are now appearing correctly, it's a PASS. Just one minor thing; would have been good if the Inbound showed as `Shipped` rather than `New` since it was created from mSupply-store (mobile-OG) after all.
> 
> <img alt="image" width="1193" src="https://private-user-images.githubusercontent.com/59193490/345289321-defcecf9-e7a8-4f0b-a9f3-236b77e50b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTQxMjIsIm5iZiI6MTcyMTI5MzgyMiwicGF0aCI6Ii81OTE5MzQ5MC8zNDUyODkzMjEtZGVmY2VjZjktZTdhOC00ZjBiLWE5ZjMtMjM2Yjc3ZTUwYjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5MTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDg4NTQwYjkxY2Y4N2NiZGY4ODBjYTJjZjJhMjEzMDFkNzdmYWMwMWMzMmIwZWNmODQzNWUwMzI3ODBhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U77V3rfO35CqAIeNTObHQodAdhRyZ8STqNrY3Mn_ZUY">
> @andreievg @roxy-dao Is this worth fixing or we can just ignore?

Submitted issue for that: #4438
