### ISSUE TITLE
Can't process the previous requisition from mobile if requestor was oms-store

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4306]
## What went wrong? 😲
From [here](https://github.com/msupply-foundation/open-msupply/issues/4139#issuecomment-2177911790): Can't process the previous requisition from mobile if requestor was oms-store

## Expected behaviour 🤔
previous requisition should be allowed to proceed in normal manner

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a oms-storeA and mobile-storeB
2. Create a IO from oms-storeA to mobile-storeB
3. In mobile-storeB, there's a customer-requisition received. Don't process it yet
4. Make sure everything is synced till this point
5. Migrate storeB to oms. In Cloud, remove hardware, and reinitialise oms from scratch
6. Now oms-storeB; open that previous customer-requisition
7. See error: the status is Sent and thus you can't proceed further
Note: when IO was from mobile-store(requestor), that requisition can be processed just fine after migration. Problem is only when IO was made by oms-store

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc4
- Legacy mSupply Central Server Version: v7-15-06

- Platform: apk, browser(chrome)

- Database type: sqlite

**Comment by andreievg** [comment]
Daily Triage, leaving for weekly triage, we need to know what the expectation is for migrations in this case. 

> Note: when IO was from mobile-store(requestor), that requisition can be processed just fine after migration. Problem is only when IO was made by oms-store

This I find very weird, it shouldn't make any difference.

Would be great for dev or tester in PR or next issue like this to provide the actual data of the requisition on mSupply central (a data file or json version of the record etc..), since it's quite a bit to set up

**Comment by nisha-dangol** [comment]
> Would be great for dev or tester in PR or next issue like this to provide the actual data of the requisition on mSupply central (a data file or json version of the record etc..), since it's quite a bit to set up
>
Sorry, I missed to upload the datafile. I've uploaded the [datafile here](https://drive.google.com/file/d/1tb51jBnEnI7Z2pcyDXOxkilFnzr2Ej8L/view?usp=drive_link). 
FYI, I used stores: `oms-store`: `Victoria Falls(site 6: water-victoria)` and `mobile-store`: `Samsung Tablet (site 7:android)` (which is later migrated/converted to oms)

**Comment by andreievg** [comment]
While looking at this issue https://github.com/msupply-foundation/open-msupply/issues/4305, i've also checked this one, thus changed to hotfix as it can be solved in the same PR

**Comment by andreievg** [comment]
> Sorry, I missed to upload the datafile. I've uploaded the [datafile here](https://drive.google.com/file/d/1tb51jBnEnI7Z2pcyDXOxkilFnzr2Ej8L/view?usp=drive_link).

Thanks @nisha-dangol, i was able to replicate with my data file, thanks for catching this one !

**Comment by roxy-dao** [comment]
Closed in #4347

**Comment by nisha-dangol** [comment]
Tested in v2.1.0-rc5. Tried to replicate the original issue; this time can proceed with previous requisition from mobile. PASS
