### ISSUE TITLE
Sorting by Units doesn't work in Master List detail window

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4308]
## What went wrong? 😲
Sorting by Units doesn't work in Master List detail window

## Expected behaviour 🤔
sorting should work properly

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to Master list
2. Open one
3. Try to sort by units
4. See error: it's not sorting by units at all; it's sorting by name actually

## Recordings

https://github.com/msupply-foundation/open-msupply/assets/59193490/afbb2d55-8600-4ff4-abb5-c02d677dc266

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc4
- Legacy mSupply Central Server Version: v7-15-06

- Platform: browser(chrome)

- Database type: sqlite

**Comment by andreievg** [comment]
Daily Triage, low severity, small impact and probability

**Comment by marthakeezy** [comment]
Hi team, logged a duplicate yesterday - #4578. The issue is still happening in `V2.2.0-RC3` on both Desktop and .apk

**Comment by regotaina** [comment]
Tested on RC%
Desktop app

# 🧪 Testing



- [x] Go to master list page and try sort by unit (shouldn't be able to)

PASSED THE TEST 👍
