### ISSUE TITLE
V2.1 Release Testing: Sync Integrations

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4314]
# SYNC INTEGRATIONS
### Ordering and Inbound Shipment
- [x] OMS Internal order -> Desktop requisition generated and all lines show correctly
- [x] Desktop enter some values into requisition and create customer invoice. Allocate lines, confirm invoice
- [x] OMS generates inbound shipment with all lines and shows status is "Picked"
- [x] Desktop finalise shipment
- [x] OMS shows status "Shipped"

### Requisitions and Outbound Shipments
- [x] Desktop Internal Order -> OMS requisition generated with correct lines
- [x] OMS requisition enter in values and create shipment
- [x] OMS shipment "Confirm Allocated"
- [x] OMS shipment "Confirm Picked"
- [x] OMS shipment "Confirm Shipped"
- [x] Desktop supplier invoice confirm
- [x] OMS shipment "Delivered"
- [x] Desktop supplier invoice finalise
- [x] OMS shipment "Verified"
- [x] OMS requisition finalise

## Sync Integration: Open mSupply <-> Legacy mSupply Mobile
- [x] OMS Internal order -> Desktop requisition generated and all lines show correctly
- [x] Desktop enter some values into requisition and create customer invoice. Allocate lines, confirm invoice
- [x] OMS generates inbound shipment with all lines and shows status is "Picked"
- [x] Desktop finalise shipment
- [x] OMS shows status "Shipped"

### Requisitions and Outbound Shipments
- [x] Desktop Internal Order -> OMS requisition generated with correct lines
- [x] OMS requisition enter in values and create shipment
- [x] OMS shipment "Confirm Allocated"
- [x] OMS shipment "Confirm Picked"
- [x] OMS shipment "Confirm Shipped"
- [x] Desktop supplier invoice confirm
- [x] OMS shipment "Delivered"
- [x] Desktop supplier invoice finalise
- [x] OMS shipment "Verified"
- [x] OMS requisition finalise

## Sync Integration: Open mSupply <-> Open mSupply
- **I think this was covered during WORKFLOWS?** 
- [x] OMS_B Internal Order -> OMS_A requisition generated with correct lines
- [x] OMS_A requisition enter in values and create outbound shipment
- [x] OMS_B nothing (outbound shipment "New")
- [x] OMS_A outbound shipment press "Confirm Allocated"
- [x] OMS_B nothing
- [x] OMS_A outbound shipment press "Confirm Picked"
- [x] OMS_B inbound shipment "Picked"
- [x] OMS_A outbound shipment press "Confirm Shipped"
- [x] OMS_B inbound shipment "Shipped"
- [x] OMS_B inbound shipment press "Confirm Delivered"
- [x] OMS_B inbound shipment editable now!
- [x] OMS_A outbound shipment "Delivered"
- [x] OMS_B inbound shipment press "Confirm Verified"
- [x] OMS_A outbound shipment "Verified"
- [x] OMS_A requisition press "Confirm Finalise"
- [x] OMS_B internal order "Finalised

**Comment by marthakeezy** [comment]
Can't see any issues, so build test passed ✅
