### ISSUE TITLE
V2.1 Release Testing: Patient Programs

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4315]
# Open mSupply Patient Programs

## Setups
Make sure to have the below setup/configurations on CLoud Server as they're a must for the oms-programs to work

### Document Registry Config:
Note: This is currently hidden in the "mSupply internal admin window" [to be moved to Special Menu in v7.13]
- [x] First, check that the oms-store should have the pref `omSupply: uses program module` ON
- [x] Also make sure there is proper master-list created and `it is a program` is checked
- [x] For HIV, master-list require the name to be exact. So make sure the name is exactly as in the config.json file mentioned below

Currently, there are two ways for this: (choose one of the below)
1. Through Footrunner code that will populate the om_document_registry table with proper schemas for program-enrolments & corresponding encounters
- [x] checkout https://github.com/openmsupply/programschemas
- [x] run `yarn && ./build_all.sh`. 
- [x] Execute the footrunner code: z_programs_config pointing to the ../schemas folder. Example could be sth like `z_programs_config("E:\\schemas")`

2. Manually adding the schemas of the desired programs & encounters
- [ ] Access the om document registry window.
- [ ] To add/edit, user-permission `Access server administration` will be needed, so give that as well 
- [ ] Start adding the program & encounters following the config.json in the schemas folder [here](https://github.com/msupply-foundation/programschemas/blob/main/png/schemas/config.json)

### Central server config:
After the om_document_registry is loaded to the datafile, now you can decide which users will have access to the chosen programs
### Permissions
![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/f69f7246-4884-4b24-9613-cd3eeed5bb5c)
- [x] Shows current permissions for a user
- [x] Edited permissions are propagated to open mSupply, e.g. removing permissions causes a program to stop working

## Patient Registration
- [x] Go to the “Patients” menu and click the “New Patient” button in the right top corner.

### Entering of basic patient information such as name or date of birth
- [x] A patient window open with the following fields
   - [x] National ID (NID)
   - [x] NUIC
   - [x] First Name
   - [x] Last Name
   - [x] DoB
   - [x] Gender
   - [x] Address
   - [x] Phone
- [x] The National ID number needs to be equal to 10 character long (there is no sign of checking for duplicates) 

### Search for existing similar patients to avoid duplicated patient entries
- [ ] The `Ok&Next` button gets enabled only after you enter mandatory values: First name & Last name - FAIL: #4334 
- [x] If any existing patient matches the info as entered while creating, it should show up in the `Search results` 
- [x] For patients found that belong to homestore(logged-in store), see the home icon
- [x] For patients found that belong to other store(other than logged-in store), see the download icon
   - [x] On downloading the patient, it'll download/fetch patient details from the server

### Entering full patient information and finalising the patient
- [x] In case of no any existing patients found, opt to `Ok&Next` to proceed
- [ ] Only after mandatory fields (NID, NUIC, name?) are entered, the `Create` button is enabled which lets us save the patient - FAIL?
 
## Patient List
- [x] Click on each column header to test the sorting
   - [x] Sorting is ascendent or descendent.
- [x] Test the filter fields
   - [x] Search by First name - Find patients that have the string combination you put in their first name
   - [x] Search by Last name - Find patients that have the string combination you put in their last name
   - [x] Search by id - Find patients that have the string combination you put in the National ID or NUIC 
   - [x] Try multiple fields search, each value you put in a field should combine to reduce your selection     
 - [x] Double click on a patient to see it's information
     - [x] You should see it's information
     - [x] You are able to edit the patient details.
     - [x] When clicking Ok the details are saved.

## Patient Details View
- [x] Selecting a patient from the patient list will open the patient details view
- [x] There are four tabs:
   - [x] “Details” shows the general patient information 
   - [x] “Programs” shows a list of program enrolments for the selected patient
   - [x] “Encounters” shows a list of encounters for the selected patient
   - [x] "Contact tracing" shows a list of any contact tracing entries made for the patient

## Patient Program Enrolment
- [x] To enrol a patient into a program select the “Add Program” button in the top right corner of the patient details view.
- [x] This will open a dialog with a list of available patient programs
- [x] Already enrolled programs are greyed out and can’t be selected
- [x] To enrol a patient into a program select the desired program from the list
- [x] This opens the program enrolment document where program specific information can be entered
Note: The content of the program enrolment document is program specific, i.e., depends on the schema you loaded while running the FC code during setup

## Patient Program Encounters
- [x] Only after a patient is enrolled in a program, an encounter for this program can be created
- [x] To do so select “Add Encounter” through the drop-down menu in the right top corner
- [x] This will open a dialog to create an encounter
- [x] First, the type of encounter needs to be selected, i.e. which program enrolment the encounter is associated with.
- [x] Secondly, the encounter date must be selected.
- [x] The encounter date can be in the past, e.g. for entering finished encounter, or in the future, e.g. to schedule an encounter (aka appointment).
- [x] Once an encounter is created, the full encounter document will open to enter encounter details
- [x] Every encounter has an encounter header where common encounter details can be updated, e.g. the clinician who handles the encounter or the encounter status
Note: The content of the encounter document is program specific and depends on the schema contents at the time of setup.

### Encounter Details
- [x] An encounter can have three statuses:
- “Pending” (depending on the current date this could mean the encounter is scheduled, or the encounter has been missed)
- “Visited” 
- “Cancelled”
- [x] The “More” button in the right top of the encounter detail view opens a column with additional encounter information such as a summary of previous encounters and the option to add an encounter note
- [x] Beside the Status, there is delete icon to delete the encounter

### Example: HIV Program/Encounters
In this test-suite, details for the specific HIV programs and encounters are given: [the contents can vary for different programs/encounters]
For this, there are currently two HIV programs available: 

a. HIV Testing Program
- [x] When enrolling the patient to HIV Testing Program, it will opt you to enter Enrolment date as expected
- [x] Additionally, there's also option to add patient notes if wanted
- [x] After enrolling to program, you can now create an encounter for this through the drop-down menu in the right top corner
- [x] On creating new encounter, there is additional field to add notes and save
- [x] The HIV Testing & Counselling encounter is divided into the following sections:
   - [x] General
   - [x] Risk Behaviour
   - [x] Other Services Received
   - [x] Informed Consent
   - [x] HIV Testing

b. HIV Care & Treatment
- [x] When enrolling the patient to HIV Care & Treatment, it will opt you to enter Enrolment date as expected
- [x] Additionally, there are also other fields like Program ID, which you can generate and add patient status history and other fields related to the HIV factors, like test types, risk groups, mother details, treatment supporter, referral details and patient notes
- [x] After enrolling to program, you can now create an encounter for this through the drop-down menu in the right top corner
- [x] On creating new encounter, there is additional fied to add notes and save
- [x] The HIV Care & Treatment is divided into the following sections:
   - [x] Visit Type
   - [x] Physical Exam
   - [x] ARV/Medication
   - [x] Pregnancy
   - [x] GBV
   - [x] Viral Load
   - [x] Biochemistry
   - [x] Haematology
   - [x] Tuberculosis
   - [x] Index Testing
   - [x] HCV/CrAg
   - [x] Risk Behaviour
   - [x] Referrals

### Contact tracing
- [x] Contact tracing is available for HIV programs
- [x] To do so, select “Add Contact” through the drop-down menu in the right top corner in patients detail window
- [ ] This will open a dialog to choose type of contact, in this case, HIV Partner Testing, and click OK - CRASHING
- [ ] Contact tracing for HIV Partner Testing includes the following:
   - [ ] Index Client Information
   - [ ] Family/Partner Information
   - [ ] Tracking Outcome
   - [ ] Post PNS IPV Screening
- [ ] On the top right is the button to Link to patient
- [ ] Clicking the button will open a dialog where you can search for patient using firstname, lastname & ID
- [ ] The search filter works
- [ ] Clicking OK links the selected patient, and it appears as highlighted in the Linked Patient window.
- [ ] After linking, there is also button to unlink the patient 

## Viral Load logic
- [x] The status of the Viral Load test is seen in the **encounter list** under the `Additional info` column
- [x] If Viral Load is not Done, the `Additional info` column shows either empty or nothing regarding the VL results
- [x] If Viral Load is Done, the `Additional info` column can have two additional statuses:
    - [x] “**Pending VL Results**”: The viral load test has been done, but no results have been entered yet
    - [x] “**VL Results**”: VL results have been received, and the results have been entered in the viral load section

## Lost to Follow up (LTFU)
- [ ] The current patient LTFU status will show up in the **program enrolment list** in the `Additional Info` column
- [ ] When a patient runs out of ARV medication pills (see ARV medication section in the encounter) the patient receives the following lost to follow up statues:
   - [ ] “**Missed appointment**”: is the patient’s status when reaching the “End of Supply” date 
   - [ ] “**Early LTFU**”: 28 days after the end of supply date
   - [ ] “**LTFU**”: 90 days after the end of supply date

**Comment by marthakeezy** [comment]
Closing as V2.1.0 is out :)
