### ISSUE TITLE
Error when navigating back to patients list via breadcrumb

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4324]
## What went wrong? 😲

From App Drawer, patient list has `sort=code` query param set. However, when you click the breadcrumb from detail back to patient list, it adds the default created datetime filter and gives an error:

https://github.com/msupply-foundation/open-msupply/assets/55115239/6bee3449-1577-4b0f-9501-9bc014884647

## Expected behaviour 🤔

Doesn't error, probably still sorted by code 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to patients 
2. click on a patient
3. use the breadcrumb to navigate back to the list view
4. see error

## Your environment 🌱

- Open mSupply Version: 2.1 RC4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Quick fix will get into 2.1. Should be created datetime

**Comment by roxy-dao** [comment]
Closed in #4333

**Comment by marthakeezy** [comment]
Tested in V2.1.0-RC6, no issues found. Build test passed! ✅
