### ISSUE TITLE
Add activity logs for demographics mutations

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4343]
## Is your feature request related to a problem? Please describe 👀

Demographics backend was implemented without adding in `ActivityLog` entries.

We've got a few of these lying around now:

https://github.com/msupply-foundation/open-msupply/blob/8b222383c736f64fc5a4b9873bb82dfb30639c49/server/service/src/demographic/insert_demographic_indicator.rs#L47

## Describe the solution you'd like 🎁

Changes to demographics indicators and projections should be logged

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.3`

- [ ] On Central Server, go to Manage -> Demographics
- [ ] Insert Demographic indicator
- [ ] Update Demographic indicator
- [ ] Edit the "Growth on previous year" values at the top (that's the Demographic Projection)
- [ ] Check that correct activity_log entries are added for each of the above operations (will need to manually inspect database)
