### ISSUE TITLE
Replenishment -> Inbound Shipment: Locations are not shown properly when the view is grouped by item

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4349]
## What went wrong? 😲

When navigating to `Replenishment -> Inbound Shipment`, and entering a new Inbound Shipment, you can toggle the 'Group by Item' option. When toggled, and the list is expanded to view the details, the locations are not shown properly and instead say [Option Option] as shown below

<img width="1238" alt="Screenshot 2024-07-02 at 3 36 34 PM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/20f38e76-fdbe-4431-806c-bafd00d43eb3">

## Expected behaviour 🤔

The locations should show up properly, as names and not strings

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Inbound Shipments
2. Create a new Inbound Shipment
3. Add 2 batches of the same item -> for example, I added Tea Towels 2 times, but different batches
4. Toggle the 'Group by Item' option
5. Expand the view -> see the locations show as [Option Option]

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC4
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App for Windows and Galaxy A8 Tablet

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Closed in #4529

**Comment by marthakeezy** [comment]
Fixed -> moving to Done :) ✅ 

![Image](https://github.com/user-attachments/assets/e9f05056-96ae-41ab-834e-80e4f17fe502)
