### ISSUE TITLE
Refactor Stocktake in service layer

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4351]
## The suggestion
The stocktake insert/update files are getting really big and would be nice if some of the functions can be moved out into their own validate/generate files like in the rest of the repo.

### Why should we invest time in this?

Nicer to read! And way easier to navigate through~

### Are there any risks associated with this change?

Shouldn't be any risks? 

### How much effort is required?

Might take a few hours to move things out and make sure nothing has broken~

**Comment by mark-prins** [comment]
Refinement: let's do it! in discussion we decided that the existing patterns should be clear enough as a template for the work required here, i.e. we trust your judgement on this one 😉

**Comment by marthakeezy** [comment]
Tested Stocktakes in V2.4.0 and V2.5.0, they are working as intended and all relevant bugs have been raised in the most recent release testing cycle. Moving this issue to Done ✅
