### ISSUE TITLE
v2.2.0 (21st August)

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4355]
# Key aims
* R&R forms
* Backups for central server
* Basic built in reports (part 1/2)

# Deadlines (in NZT)

Date started: Thur 04 July, 20204
PR deadline: Wed 31 July, 2024
PRs merged: Wed 07 August 2024
Release: Wed 21 August 2024

**Comment by lache-melvin** [comment]
v2.2.0 [released](https://github.com/msupply-foundation/open-msupply/releases/tag/v2.2.0-release)!
