### ISSUE TITLE
GAPS: Capture cold storage temperature range per item variant

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4368]
### Additional context 💌

| User story  | B.2.8 |
| :------------- | :------------- |
As a… | National EPI manager
I want… | to specify the cold storage temperature requirements for each type of vaccine variant and also other products
So that… | the cold storage requirements can be broken down by temperature range

**Solution B.2.8**

The system will allow central users to specify the cold storage temperature requirements for vaccine variants in the Master Data product catalogue.

3 options of cold storage temperature range will be available:

- +5 °C
- -20 °C
- -70 °C

Additionally the system will allow central users to specify a cold storage temperature range for non-vaccine item variants (such as diluents).

### Moneyworks Jobcode 🧰

`CCEIDEV`

**Comment by mark-prins** [comment]
Refinement: we'll leave up to the implementing team to refine further and report back to the refinement team if there are decisions to confirm

**Comment by marthakeezy** [comment]
# 🧪 Testing

Tested in V2.4.0-RC2 and as a part of feature release testing :)

- [ ] Login to your central OMS
- [ ] Edit item variants
- [ ] Check you can select a cold storage location type (I'm assuming you have them too!) 
- [ ] Make sure changing/updating works correctly
- [ ] Everything displays right

**Comment by marthakeezy** [comment]
Passed!
