### ISSUE TITLE
Can't use barcode scanner for Outbound Shipments or update item details (Android)

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4373]
## What went wrong? 😲

While using V2.1.RC6 .apk,  @louisaw123 and I noticed the barcode scanning buttons are not available at:

- Outbound shipments: 'scan' button to add item lines
- Stock > View Stock: 'scan' icon to add batch and expiry date are not working

It is available on V2.1, which prob leads us to think it disappeared somewhere in between these versions.

- Open mSupply Version: V2.1.RC6
- Platform: Android

**Comment by roxy-dao** [comment]
Closed in #4377

**Comment by nisha-dangol** [comment]
Checked the below in v2.1.0:
- [x] Outbound shipments: 'scan' button to add item lines : working for me
- [x] Stock > View Stock: 'scan' icon to add batch: also working fine
