### ISSUE TITLE
GAPS: vaccine courses do not show in list

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4375]
## What went wrong? 😲

This is happening:

<img width="1194" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/3a4fd31e-37e1-4b58-98c6-39478f125190">

## Expected behaviour 🤔
You should see the list of vaccine courses in the 'Vaccine Courses' column

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `/programs/immunisations`

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by nisha-dangol** [comment]
## Testing
- [x] have a look at the immunisations list view: should see something in the vaccine courses column
but I still some problems here: like I reduce some vaccines from the program, now I see those old vaccines values still there.
Also, i thought this was supposed to fix/show `target demographics` in the list as well? 
Detailed in issue: #4381
