### ISSUE TITLE
Saved Enrollment date does not appear in enrollment form

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4379]
## What went wrong? 😲
Saved Enrollment date does not appear in any enrollment form; I enrolled patient to 2 programs, same result every time

## Expected behaviour 🤔
Previous saved value should be there on the form

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Setup patient programs
2. Enroll the patient to a program
3. Choose enrollment data and save.
4. When you see that patient>Programs tab, you can see the enrolment date
5. Open that enrolled program
6. See error: the enrolment date shows empty. It is understandable that enrolment date is editable, but previous date should be there
<img width="1241" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/517d69b7-f78f-41a6-9ed7-6dc1a91b6f9e">

## Your environment 🌱

- Open mSupply Version: v2.1.0-rc6
- Legacy mSupply Central Server Version: v7-15-09

- Platform: browser(chrome)

- Database type: sqlite

## Additional notes
Found while release-testing: #4315

**Comment by andreievg** [comment]
Daily Triage, bumping up priority slightly. Leaving for weekly triage as we need to allocate time and budget for program module fixes

**Comment by roxy-dao** [comment]
Fixed in #4721
