### ISSUE TITLE
Crashes on adding contact

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4380]
## What went wrong? 😲
When trying to add contact, it crashes. 

## Expected behaviour 🤔
should not crash whatsoever

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Setup patient programs
2. have some patients
3. Add contact
4. See error: crash

## Your environment 🌱

- Open mSupply Version: v2.1.0
- Legacy mSupply Central Server Version: v7-15-09

- Platform: browser(chrome) + apk

- Database type: sqlite

**Comment by andreievg** [comment]
Daily Triage, agree this would be high priority, leaving for weekly triage as we need to allocate time and budget for program module fixes

**Comment by AnushaUp** [comment]
On oms  Desktop(Browser) Type of contact list appears and it crashes after choosing the type of contact but in mobile
![Screenshot 2024-07-31 at 12 50 00 pm](https://github.com/user-attachments/assets/537d1307-b03e-458d-89ce-4b31e2bf94b6)
But in tablet the list doesn't appears 
https://github.com/user-attachments/assets/0526cc74-21eb-470e-b626-142419fb6618

**Comment by lache-melvin** [comment]
Closed by #4618

**Comment by santoshkhanal12** [comment]
Tested on `v2.2.01`

# 🧪 Testing



- [x] Have patient programs set up
- [x] Create contact trace
- [x] You get redirected to contact trace page, it renders fine, no crash

No crashing was seen


https://github.com/user-attachments/assets/8435fe7e-7a73-4665-b23f-f8a3325f9c44
