### ISSUE TITLE
user permissions not working for inventory adjustment and repack

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4382]
https://github.com/msupply-foundation/open-msupply/assets/143057869/aad4a037-566f-435e-b4e4-7801e142bae5

## What went wrong? 😲

adjusted permissions for repack and inventory adjustment to prevent performing these actions, synced, and logged out/in. can still do these actions on oms.

i did test other permissions to see if this was a oms permission issue or just those specifically - tested location permissions and this one is denied (Seen in vid). also tested for turning off customer invoices permission and this works too.
 
## Expected behaviour 🤔
when I don't give permission for something I should not be able to perform the action.

## How to Reproduce 🔨

legacy > turn off those permissions for repack and inventory adjustment.
sync / log out and in of oms
log back in to oms > attempt to repack and inventory adjust. lets you do it

## Your environment 🌱
demo datafile
oms 2.1.00-rc4 desktop
legacy 7.15.09
local

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
The permission for create repack is Create Repacks or Split Stock which you have ticked (we don't have a way to edit repacks in OMS since it goes draft -> finalised)

And for Inventory Adjustments, can you check the 2nd permission tab? If you have `Finalise Inventory Adjustments` ticked, if you do then you can still edit adjustments XD

https://docs.msupply.foundation/docs/administration/permissions/ list of permissions here (:

**Comment by louisaw123** [comment]
page not found haha. i cant remember, did that page have on it what permissions are meant to be on for those to have effect? there are like 3 pages of permissions to go through on msupply admin - wondering if there should be a column on the table for what to set otherwise doing it on own for users, it may not always be very obvious to the average human eye 😆

**Comment by mark-prins** [comment]
the [permissions page](https://docs.msupply.foundation/docs/settings/permissions/) is now under 'settings' 😉

**Comment by roxy-dao** [comment]
Convo with @mark-prins: simplify it down then - and just use the 'create' permissions. so for inventory adjustments, we use 'enter' as the only permission; in the same way that we have for repacks

**Comment by regotaina** [comment]
Tested on RC5

Desktop app

# 🧪 Testing



- [x] Try turning the `Edit`/`Finalised` permissions for Inventory Adjustments off
- [x] Try to do an inventory adjustment (Stock -> Click on a line -> Adjust stock)
- [x] Shouldn't be able to

Passed the test.
Just a caveat that:

- if you click on stock line and try to adjust, it prevents you from entering any information.
- if you click on 'New stocl' it does allow you to input informaion, but when you click 'SAVE' it does come up an error message saying 'permission denied'

However on the bottom there's a s success message. Which is not a biggie, but can be confusing, as per screenshot:
@roxy-dao more an FYI


![Image](https://github.com/user-attachments/assets/a245e015-fd8f-45df-8916-e7400885dd4f)

**Comment by roxy-dao** [comment]
Sorry I've adjusted the test

- [ ] Try turning the `Edit`/`Finalised` permissions for Inventory Adjustments off and `Enter`
- [ ] Try to do an inventory adjustment (Stock -> Click on a line -> Adjust stock)
- [ ] Shouldn't be able to
- [ ] Enable `Enter Inventory Adjustments`
- [ ] Do adjustment

This is only for adjustments and you can't adjust stock you are introducing. Above looks like a bug~
https://github.com/user-attachments/assets/847c1c5b-535d-4bb6-9cda-98f87cabe129
