### ISSUE TITLE
Unable to run android

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4383]
## What went wrong? 😲

I tried to test #4069 now that #4377 has been implemented, and android doesn't run for me if I build and deploy the apk to a tablet. I get an infinite loader when running the 2.1 release branch.

Looking at the console I'm getting

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/d5550044-bd8a-42a0-b78a-e09e4ab36a0d)

when loading. Reverting the changes in #4377 and the app loads.
However, if I re-initialise then I'm still having issues

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Preliminary test, tried 2.1 release from release page on emulator, seems to work. Tried it on Lenovo, also works. 
Next step is to try to build a release

**Comment by mark-prins** [comment]
yeah - the release build worked when I tried that on the samsung. 
it was the debug apk which reliably doesn't work on the tablet. strange, right?

**Comment by andreievg** [comment]
I tried on develop with Lenovo and Emulator both with debug and release build, also tried debug build on 2.1, seems to work fine. I have to try with samsung tablet. Btw debug build tested with both android studio run button and with android:build:debug
