### ISSUE TITLE
Hide program related columns in Requisition

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4386]
## Is your feature request related to a problem? Please describe 👀
We currently show the program requisition columns in the Requisition page.

## Describe the solution you'd like 🎁
Hide it if program requisitions isn't being used for the store just like how we hide it from the `New Order` modal

### Describe alternatives you've considered 💭
Just leave it 🤷🏻 not harming anyone

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Don't have programs set up
- [ ] Go to requisition/internal order
- [ ] Shouldn't see program related columns
- [ ] Set up programs
- [ ] Go to internal order -> See program related columns
- [ ] Send internal order
- [ ] Go to supplier store -> requisition
- [ ] See program related columns

**Comment by AnushaUp** [comment]
> [ ] Go to internal order -> See program related columns

![Screenshot 2024-09-17 at 3 14 42 pm](https://github.com/user-attachments/assets/96a5f44e-ef2a-4ece-9294-5b110e9792f9)
program related colums can be seen in R&R form. Moving this issue to done.
