### ISSUE TITLE
view service charges in more detail such as the types of service charged

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4394]
## Is your feature request related to a problem? Please describe 👀

<img width="1218" alt="Screenshot 2024-07-10 at 9 25 29 AM" src="https://github.com/msupply-foundation/open-msupply/assets/143057869/7b5bdc31-7498-4008-aba6-4ce52bbe7989">

<img width="938" alt="Screenshot 2024-07-10 at 9 26 05 AM" src="https://github.com/msupply-foundation/open-msupply/assets/143057869/f05c8dbd-ca4c-46e5-aee3-8f1fe0de2eee">

not sure if this is a completed feature but cannot see detail about what service is being charged. can only see subtotal. there is no information area to view more details about these service charges

## Describe the solution you'd like 🎁
would be useful to have the service item charge showing in the invoice highlighted in a different colour too like in legacy after adding a type of service charge to make it more visible to users what is charged as service.

**Comment by roxy-dao** [comment]
Related or possible dup? #https://github.com/msupply-foundation/open-msupply/issues/3554

**Comment by louisaw123** [comment]
sort of related... except i think each type of service charge should be visible because there could be different item handling fees, and I wonder if it should be more apparent to purchasers what the costs of individual services are on oms (so having a description somewhere) , rather than just seeing it as a subtotal cost of service
 
<img width="938" alt="Screenshot 2024-07-10 at 9 36 36 AM" src="https://github.com/msupply-foundation/open-msupply/assets/143057869/8844e475-9937-48d7-97a2-8c1c5d448a8e">

**Comment by mark-prins** [comment]
I guess we could list the charges in the more info panel, would that work?

personally I like having the service charges over there, and not in the main item list; which means having a separate colour isn't required. that was a bit of a workaround in OG: to distinguish service charges from items, as both were shown in the list / table.

**Comment by roxy-dao** [comment]
Closed in #4552

**Comment by AnushaUp** [comment]
@mark-prins @roxy-dao The service item appears there but there's no any price added in the total. Here's [Screenshots](https://drive.google.com/drive/folders/1UxCppJILD1k_ww56-DQePQoZQpkQjVkf).

**Comment by mark-prins** [comment]
Thanks @AnushaUp! have made #4784

**Comment by AnushaUp** [comment]
Thanks @mark-prins will do further testing there.

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in OMS `V2.4.3` mSupply `V8.0-dev27`


- [ ] Create a customer invoice, add a service charge with a price value
- [ ] Migrate the store to oms
- [ ] View the outbound shipment

2.
- [ ] Create a supplier invoice, add a service charge with a cost price
- [ ] Migrate store to OMS
- [ ] View inbound shipment

**Comment by AnushaUp** [comment]
PASSED✅
