### ISSUE TITLE
Asset Import doesn't save Replacement Date

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4399]
## What went wrong? 😲

Noticed that the import seems to validate the replacement due date ok

![telegram-cloud-photo-size-1-4934212593657163008-y](https://github.com/msupply-foundation/open-msupply/assets/8287373/06f608f4-08ca-43dd-873e-a752bd6e61c6)

but when I look at the asset there is no actual date populated

![telegram-cloud-photo-size-1-4934212593657163009-y](https://github.com/msupply-foundation/open-msupply/assets/8287373/68f55702-efae-4c8c-ad21-79f41ba142a5)

## Expected behaviour 🤔

Date should save correctly

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Equipment
2. Import an asset with with replacement date
3. Check if replacement due shows up

## Your environment 🌱

- Open mSupply Version: 2.1

**Comment by mark-prins** [comment]
The replacement date isn't being sent as part of the mutation:

![image](https://github.com/msupply-foundation/open-msupply/assets/9192912/dc8a6726-a6e2-4bac-8da7-7c5b0903bfb6)
