### ISSUE TITLE
Sync Periods and Schedules from Legacy

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4410]
We need to create an R&R form for each period configured in mSupply, so we need to sync these!

They do not need to be edited/managed from Open mSupply.

**Comment by andreievg** [comment]
@roxy-dao is so fast, she already did it: https://github.com/msupply-foundation/open-msupply/pull/1515

**Comment by lache-melvin** [comment]
> @roxy-dao is so fast, she already did it: #1515

Woah thanks Roxy 🔥

**Comment by lache-melvin** [comment]
> > @roxy-dao is so fast, she already did it: #1515
> 
> Woah thanks Roxy 🔥

And thanks for spotting @andreievg 🙏
