### ISSUE TITLE
CIV 2.5: Item Ledger

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4413]
The ledger is currently being shown in `View Stock` -> `Stockline` -> `Ledger`. We want to show the item ledger on the item itself as well. Bring in additional columns shown in OG. Can be broken down into two PRs or two separate issues for backend and frontend.

### Backend
Implement the following columns in the ledger view:
- status
- expiry
- batch
- pack_size
- balance 
	- previous balance + adjustment from invoice line
- cost_price (per pack)
- sell_price (per pack)
- local_currency_total (total_price_before_tax in local currency)

Frontend implementation:
- New tab in the `Item` detail view
- Tab should show ledger with pagination
- Add an on-click on the line that takes you to the relevant transaction

### Moneyworks Jobcode 🧰
OMS:CIDV

**Comment by lache-melvin** [comment]
R&R form has been implemented using existing stock evolution functionality. However Item ledger would still be a super helpful feature, both for upcoming client requirements and for testing.

We would most likely want a running total on item ledger. Currently we only calculate historic stock on hand via backwards calculations, subtracting transactions from stock on hand now... 

@jmbrunskill if we had item ledger with historic running total, that might help resolve #4472 ?

**Comment by jmbrunskill** [comment]
True good point!

**Comment by alainsussol** [comment]
Will be tested as part of the [2.5 CIV release testing](https://github.com/msupply-foundation/open-msupply/issues/5932)
