### ISSUE TITLE
Create adjustments on R&R form submit 

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4418]
If R&R form final quantity doesn't match ledger value, we need to create an adjustment.

This should create an Outbound Shipment for reductions and an Inbound Shipment for increases. Use the Inventory Adjustments customer. 

We are using shipments so consumption is affected!

Invoices should be created when the R&R form is finalised. Said invoices should then be automatically finalised, as at the closing date of the period.

EDIT: pending decision on one adjustment vs 3 (for inbounds/outbounds/adjustments)

**Comment by lache-melvin** [comment]
Blocked pending understanding of necessity of this for now - these adjustments would be historic transactions, which are on the roadmap but not yet implemented...

If we can delay R&R forms changing stock levels until historic transactions & their implications have been ironed out, that would be ideal 👀

**Comment by mark-prins** [comment]
Parking this one for now. Please revive if required

**Comment by marthakeezy** [comment]
No testing required, so moving to Done ✅
