### ISSUE TITLE
Add update filter to report detail view

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4420]
## Is your feature request related to a problem? Please describe 👀

Filter can be updated in report detail view

## Describe the solution you'd like 🎁

Update Filter button in report detail view, that opens report argument modal, current arguments will be pre-filled, report will be re-generated when modal is confirmed. Would need loading indicator.

### Describe alternatives you've considered 💭

In the design filters are updated in the info panel that slides from the right side. To speed up feature release we would use existing ReportArgumentModal for the first iteration

**Comment by roxy-dao** [comment]
Closed in #4440
