### ISSUE TITLE
Add additional R&R report values

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4421]
Some calculated values to be shown too. 
They will need to be sent with the R&R form, so will need to be recorded and be enterable / editable.

<img width="836" alt="Screenshot 2024-07-15 at 5 14 58 PM" src="https://github.com/user-attachments/assets/d4630452-f9c1-4b78-bce5-cde8ca62a99c">

Top two = number of items of that category, which had any days where SOH was 0
Bottom two = number of items of that category, which had 15+ days where SOH was 0

Needs to be included in requisition! 

Where to capture? Side menu, prompt if not entered?

**Comment by jmbrunskill** [comment]
@mark-prins  and I discussed this, and we think this can just be calculated based on other data entry. I don't think we need to make it user enterable.  A future requirement to create custom additional datapoints to capture on an R&R form, but for now we just just make this a calc in the dashboard or in Central Server even...

**Comment by lache-melvin** [comment]
Double checking this is only wanted on the governance end? Stores filling out the R&R forms won't want/need to see this anywhere in the UI?

**Comment by mark-prins** [comment]
that's my understanding, though I'm not sure - will ask

**Comment by mark-prins** [comment]
We're looking at adding to the dashboard. See [419](https://github.com/msupply-foundation/msupply-dashboard-clients/issues/419)

**Comment by mark-prins** [comment]
to be part of the dashboard report, no change required here.
