### ISSUE TITLE
Remove column sorting on ledger

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4429]
## What went wrong? 😲

Low pri, maybe not really a bug, but it confused me for a sec...

Had accidentally clicked the `Quantity` column - only noticed when I realised the dates were out of order:
![Screenshot 2024-07-16 at 3 05 28 PM](https://github.com/user-attachments/assets/9b8497ca-dee8-4669-b8ab-0b9aa4938bc3)

Can't really think of a use case where you would want to sort the ledger? Just seems like a cause for confusion?

Possibly you're searching for a specific event/type, but that seems like it should be a filter, rather than sort...

## Expected behaviour 🤔

Ledger should always be in order of events, same as log.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory > View stock > Some stock line > Ledger
2. Click a column other than the date
3. See the ledger lines reorder

## Your environment 🌱

- Open mSupply Version: 2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
Agree - let's take the sort out 🙏

**Comment by CarlosNZ** [comment]
> Can't really think of a use case where you would want to sort the ledger? Just seems like a cause for confusion?

Hmm, I'm way late to this party, but it seems like being able to toggle the default Date/Time sorting to either descending or ascending could be useful?

Also, now that we've got the "Invoice number" column in there (PR #4671), that might be another useful column to sort by, especially when you consider the use case that prompted that change:

> If I'm looking at some stocks (let's say wondering where some of the allocated/reserved stocks are stuck), way is to check its ledger. But if there's huge record of ledger (let's say hundred of lines), it'll be very tiresome to manually check each of the transaction in that long list. https://github.com/msupply-foundation/open-msupply/issues/4072#issue-2339812910

Maybe consider this if/when we implement filtering?

> Possibly you're searching for a specific event/type, but that seems like it should be a filter, rather than sort...

**Comment by marthakeezy** [comment]
Moving this issue to Done since it passed the test, however logged a new issue (#4885) to carry over Carl's comment and the conversation 🙏🏼
