### ISSUE TITLE
Whole page reloads when navigating to sub menu

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4434]
## Expected behaviour 🤔

Make sure only the page area that needs the loading state, shows the loading state (rather then the whole page).

## Suggested Solution

Add another suspense, currently lazy loads: https://github.com/msupply-foundation/open-msupply/blob/fa22d29835933b131d6a00ed938651a9cc6d5c94/client/packages/host/src/routers/DistributionRouter.tsx#L6 are fallen back to top level suspense https://github.com/msupply-foundation/open-msupply/blob/fa22d29835933b131d6a00ed938651a9cc6d5c94/client/packages/host/src/Host.tsx#L78, causing the whole app to reload.

I think we need a more strategic and thorough think about how we handle supporting non locally served front end, to avoid issues like this (where we tried to optimise the bundle and the front end speed for non locally server front end but ended up making the whole app reload, including graphql queries like isCentralServer, me, etc..), maybe have a way to test this and having a requirements about what we want to support, accepted speed etc (I think it would have been simpler and arguably better user experience if there is just one delay, the first time you load the app, rather then delays throughout the app)

## How to Reproduce 🔨

Add throttling (in browser dev tools,  network), try to go to sub menu (inbound shipments etc..), see whole page needing to refresh

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
triage: popped in to v2.2 as it would be good to change this behaviour!

**Comment by marthakeezy** [comment]
V2.3.0 is out so moving to Done ✅
