### ISSUE TITLE
🌱 V2.2.0 Release Testing

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4436]
# V2.2.0 Release Testing

> [!NOTE]
> **Test Scripts** are available [here](https://github.com/msupply-foundation/open-msupply/wiki/Test-scripts), they are updated as the new features are coming out ✍🏼

> [!NOTE]
> Please follow [this document](https://docs.google.com/document/d/1aLQ7QwohBhr53U4jmXnYG0FrBqFDQPxPkO45-YFiLvQ/edit) for the most up-to-date QA practices :)

## V2.2.0 NEW FEATURES/IMPROVEMENTS
- [x] #4525 - @regotaina @marthakeezy 
- [x] #4582 @lache-melvin 
- [x] #4526 - @AnushaUp 
- [ ] RnR (tablet) - @andreievg 
    
## WORKFLOWS
These can be either one-store or multiple-store setup; depending on the workflow. 
Priority is to make sure the stock movement is functioning 

### STOCK MOVEMENT WORKFLOWS
- [ ] All of them - @fergie-nz 
- [ ] #4535
- [x] #4542
- [x] #4547
- [x] https://github.com/msupply-foundation/open-msupply/issues/4540
- [x] https://github.com/msupply-foundation/open-msupply/issues/4558
- [x] https://github.com/msupply-foundation/open-msupply/issues/4539

### NORMAL ORDERING WORKFLOWS
- @Chris-Petty 
- [x] https://github.com/msupply-foundation/open-msupply/issues/4527
    - [x] Creating/Placing Internal Orders
    - [x] Receiving Customer Requisitions
    - [x] Supplying through Outbounds
    - [x] Receiving through Inbounds

### SYNCHRONISATION: CENTRAL DATA SYNC & SYNC INTEGRATION
- @Chris-Petty 
- [x] https://github.com/msupply-foundation/open-msupply/issues/4524
    - [x] Central Data Synchronisation
    - [x] Sync Integration with Legacy mSupply
       

## GENERAL MODULES
These can be tested in a single-store environment since they're more focused on UI 
Priority is to check/test if no buttons/modules are broken

### DISTRIBUTION
- [x] #4548
- [x] Requisitions : Tested on #4548 
- [x] #4569
- [x] #4571

### REPLENISHMENT
- [x] #4620
- [x] #4621
- [x] #4623
- [x] #4622

### CATALOGUE
- [x] #4566
- [x] #4575
- [x] #4576

### INVENTORY
- [x] #4560 
- [x] #4562 
- [x] #4563 

### DISPENSARY
- [x] #4572
- [x] #4580 

### SETTINGS
- @CarlosNZ 
- [ ] Display settings
- [ ] Sync
- [ ] Support
- [ ] Devices

### SYNCHRONISATION
- [x] https://github.com/msupply-foundation/open-msupply/issues/4553
    - [x] Installation
    - [x] Initialisation
    - [x] Synchronisation
    - [x] Reinitialisations
    - [x] Version-updates

### COLD CHAIN - SKIPPING this release ⏩
🚫 Monitoring
🚫 Sensors
🚫 Equipment

### IMMUNIZATIONS - PRIORITISE this maybe?
- [x] #4633
- [x] #4634

### PATIENT PROGRAMS - I think LOW PRIORITY for now
- [ ] Patient Registration
- [ ] Patient List
- [ ] Patient Details View
- [ ] Patient Program Enrolment
- [ ] Patient Program Encounters
- [ ] Viral Load logic
- [ ] Lost to Follow up (LTFU)

### PROGRAM REQUISITIONS
- [x] #4598 
    - [x] Setups
    - [x] Creating a Program Internal Order
    - [x] Program IO window
    - [x] Requisitions - already tested above as well

### REMOTE AUTHORISATION
 - [x] #4635
    - [ ] Creating Internal Order
    - [ ] Approving Internal Order
    - [ ] Supplier Requisition

### **TEST ENVIRONMENT**
oms Version: `v2.2.00-RC?` 
mSupply Cloud-Server: `v7-16-04`
oms app-mode: choose:- `oms-server`+`browser(chrome, firefox, etc)`,`oms-desktop`;`apk`; `oms-standalone`
oms db: choose:- `sqlite` OR `postgres`

[See this for datafile details](https://docs.google.com/spreadsheets/d/1NhuMlQWVum_4XZezR0siu6ahV0RigVHMU4JDcJCN1Yg/edit?gid=88872578#gid=88872578)

**Comment by lache-melvin** [comment]
Closing as V2.2.0 has been released 🎉
