### ISSUE TITLE
Add some helpful message under 'Master List' tab of item details window for invisible items

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4437]
## What went wrong? 😲
Add some helpful message instead of `Nothing here` text under 'Master List' tab of item details for the invisible items

## Expected behaviour 🤔
Show show helpful message there maybe?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have some invisible items (i.e., item not visible to the store). One way to do this is create stock-transfer with item from other-oms store to your oms-store and receive it as at least `Delivered` in the Inbound received
2. Catalogue>Items.
3. Open that item details and head to `Master List` tab
4. See error: `Nothing here` text. Add some helpful message maybe instead of that?
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/7c101180-95e2-40ff-a6d8-2728ea4baf18">

## Your environment 🌱

- Open mSupply Version: v2.1.0
- Legacy mSupply Central Server Version: v7-16-00

- Platform: browser(chrome)

- Database type: sqlite

**Comment by mark-prins** [comment]
Suggested message:
`This item is not assigned to a master list and so cannot be ordered, please contact your administrator if this is an error. Note that an item could be visible if there is stock on hand, even if the item isn't on a master list.`

**Comment by roxy-dao** [comment]
Closed in #4626

**Comment by AnushaUp** [comment]
Tested and Passed ✅
![Screenshot 2024-09-10 at 5 00 11 pm](https://github.com/user-attachments/assets/ec9d23af-b1e0-4df7-aca1-e4bec6cb3ec9)
