### ISSUE TITLE
Equipment list not showing properly when reloading the page in browser

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4471]
## What went wrong? 😲

Equipment list is not showing constantly in the browser while reloading. 
Recording [HERE](https://drive.google.com/drive/folders/1wm7AkKA4OnDFsUjkb20TgxqoZmcJF60P)

## Expected behaviour 🤔
Should show a list properly. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Coldchain > Equipment tab
2. Make some equipment with different store
3. Reload the page 
4. See the error (Equipment list will show the equipment of current active store only)
5. Click again in the tab and works fine

## Your environment 🌱

- Open mSupply Version: V2.1.00-rc6 (OMS central server)
- Legacy mSupply Central Server Version: V7.16.04

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #4599

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.02-RC1`


- [ ] Initialise OMS central server
- [ ] Create some equipments in different stores
- [ ] Go to equipment list view -> see all equipment regardless of store
- [ ] Press refresh button -> should still see all equipment regardless of store

**Comment by AnushaUp** [comment]
Tested and PASSED✅
