### ISSUE TITLE
Show R&R items grouped by category

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4475]
## Is your feature request related to a problem? Please describe 👀

Items in the R&R form should be grouped by category.

## Describe the solution you'd like 🎁

- map item category from legacy mSupply
- sync this out to remote sites too!
- rnr_form lines should be returned to frontend as a list of categories, each containing a list of items
- Add colspans to R&R form for each category heading

**Comment by lache-melvin** [comment]
Awaiting decision on whether this is needed/which categories to map!

**Comment by lache-melvin** [comment]
Should also resolve this: https://github.com/msupply-foundation/open-msupply/blob/8068f6525cd37a630d1acc1bfe6d8a681658ee80/client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx#L49-L50

**Comment by mark-prins** [comment]
I'm just going to close this for now, have had no confirmation that it's needed

**Comment by marthakeezy** [comment]
No testing required, so moving to Done ✅
