### ISSUE TITLE
Display settings not updated when cleared

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4485]
## What went wrong? 😲

If the custom display settings (theme and/or logo) are set and then cleared - only the browser which clears the settings will see the cleared version.

## Expected behaviour 🤔
Changing or clearing should update for all users.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

using browser (a)
1. login, navigate to settings
2. set the theme and/or logo

using browser (b)
1. login, you'll see the display changes

using browser (a)
1. clear the custom display settings
2. now logout and login and refresh the page. you'll keep the cleared settings

using browser (b)
1. logout and login: the custom settings are shown
2. refresh page: still custom settings
3. go to settings > display settings and clear: the custom settings are cleared

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in OMS `2.2.02-RC1`


- [ ] set settings in one browser, login in another, clear in first browser, return to second. you will likely need to reload page to get the changes to show (not ideal but better than it was!)

**Comment by AnushaUp** [comment]
@mark-prins Needed logout and login for the changes.✅
