### ISSUE TITLE
Stock status report UI review

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4494]
## What went wrong? 😲

A couple of UI improvements to the expiring items report please

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/9504f936-5816-4073-b93d-06eddfbe22c9">

* The breadcrumb doesn't need to have an ID in it. I'd recommend having `Reports / Expiring items` where the reports links to the  reports list view (currently, clicking 'expiring items' takes me to 'Reports' which is misleading)
* Add some padding to the status chips - the text and dot are hard against the edges
* remove the border on the iframe
* The font size of the report is smaller than our usual which looks a little out of place. I think it's probably ok, but worth checking how it looks slightly larger

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Do you have the steps to reproduce? 👀  Mine doesn't have link or ID in breadcrumb

![Screenshot 2024-08-05 at 7 38 16 AM](https://github.com/user-attachments/assets/e40d6260-994d-4ea7-af98-3df96cb6f378)

**Comment by andreievg** [comment]
Sounds like this one is good to do in 2.2, next RC

**Comment by roxy-dao** [comment]
Add some padding to the status chips - the text and dot are hard against the edges and The font size of the report is smaller than our usual which looks a little out of place. I think it's probably ok, but worth checking how it looks slightly larger
 are already done (:

**Comment by roxy-dao** [comment]
Closed #4556
