### ISSUE TITLE
Reports args vanish

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4496]
## What went wrong? 😲

From https://github.com/msupply-foundation/open-msupply/pull/4483... Reports args aren't being retained and if you click okay twice then you get error below

![Screenshot 2024-08-05 at 8 43 02 AM](https://github.com/user-attachments/assets/975e5f8d-a2f3-41df-a1f7-d9b4bc604810)
![Screenshot 2024-08-05 at 8 40 07 AM](https://github.com/user-attachments/assets/c4b173a9-8c33-4e6e-9a52-b3293ecc1fac)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upsert reports from reports report with StockAndItems or Expiring
2. Generate report
3. Go to `filter`
4. Click `ok`
5. Go back to `filter`
6. See args are gone

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Closed by #4501
