### ISSUE TITLE
Expiring items report UI review

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4499]
## What went wrong? 😲

Had a look at the expiring items report, and I have some UI requests please

<img width="621" alt="image" src="https://github.com/user-attachments/assets/e8ed5961-620f-472c-8f1f-d838d859d24e">

In the report arguments modal:
* can you make the label column a little wider, so that the labels aren't wrapping (in English, at least). Just making the modal width `600` would be better
* The numeric inputs look strange being not as wide as the other inputs, and right aligned. 
* The 'item code or name' input isn't as wide as the expiry date - can they be the same please
* there's more vertical space around the disabled numeric inputs - could the vertical spacing be consistent?
* It would be helpful to have a little introductory text e.g. "You can customise what is shown in the report, by specifying some of the optional details below. Click OK to view the report" is that possible? What does 'expiry date' do?

this is with width of `500` but a little tweaking of layout:

<img width="569" alt="image" src="https://github.com/user-attachments/assets/b3ea7eab-9559-4fc6-85be-aa9acf548130">

And some general items, most of which are noted in #4494

<img width="955" alt="image" src="https://github.com/user-attachments/assets/a1eb906c-3a79-4a8d-8240-b24f061e4bcb">

* Remove border around iframe
* Add padding to 'expiring in' chip
* Fix breadcrumb ( should show `Reports / Expiring items` with reports linking to list view )
* Add a CMD+K shortcut for reports

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
The arguments modal UI change don't seem to be breaking anything, and there is already issue to fix breadcrumb and potentially the expiring chip, in here: https://github.com/msupply-foundation/open-msupply/issues/4494, will just remove the needs daily triage label for now, and we can consider if it goes to 2.2 or 2.3 in weekly triage

**Comment by andreievg** [comment]
Report arguments -> report filter

**Comment by mark-prins** [comment]
Have removed triage label too - we discussed but I don't think we came to a conclusion. 
I'm going to assign 2.2 on the basis that it's a minor UI tweak, and I'd find the CMD+K helpful.

**Comment by roxy-dao** [comment]
Closed in #4581

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] Have expiring reports set up (https://github.com/msupply-foundation/open-msupply-reports/pull/83)
- [ ] Click on it 
- [ ] Argument modal should look pretty now
