### ISSUE TITLE
Reports page is blank if the reports aren't configured

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4506]
## What went wrong? 😲

The empty sections render while the page is loading, and then once it realises I don't have reports configured, it goes completely blank?

https://github.com/user-attachments/assets/a9c0a054-8b40-48fd-a17b-6cd21b2a7f93

## Expected behaviour 🤔

Would be nice to see the sections still, or the nothing here component, or something...

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Ensure you don't have any reports with the `Report` context in your DB
2. Go to reports page
3. Sections load for half a second, then blank

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
Good catch! thanks @lache-melvin!
We could show the nothing-here-sad-face, with a suitable message about configuring reports

**Comment by andreievg** [comment]
Would be great to fix in upcoming RC

**Comment by roxy-dao** [comment]
Closed in #4530

**Comment by regotaina** [comment]
Tested on RC5
Desktop app

# 🧪 Testing



- [x] Don't have any reports set up (not even program reports)
- [x] Go to report page
- [x] See message

screenshot:
![Image](https://github.com/user-attachments/assets/95e22c8b-18d6-4b31-9bab-b5b570fb1a50)
