### ISSUE TITLE
V2.2.0 Release Testing: Basic Reports 

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4525]
- [x] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1506" alt="Screenshot 2024-08-09 at 2 45 56 PM" src="https://github.com/user-attachments/assets/f099890c-2f59-400b-8881-d349cf110d4b">

- [x] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [ ] Download reports from report repository, upload them to OG with subcontext: StockAndItems or Expiring. Sync. The reports should now show up on the report page.

- [x] Click on one of the reports on the report page and ensure that it shows the correct report

- [x] Try using the filters (Note: There is a bug if you type to fast when filtering, will be looked at)

- [x] For item usage, generate report base analysis on whatever months you have your lookback_months set to

- [x] Check the print button is working

- [x] Check the export button downloads and opens in excel

**Comment by marthakeezy** [comment]
Tested Stock Status - pass ✅

**Comment by regotaina** [comment]
As @marthakeezy asked, I am taking over reports.

Will start from where she finished

**Comment by lache-melvin** [comment]
Hi - I can't see any script for Basic Reports testing in the wiki yet so have just copied the text above to my duplicate testing issue...

It looks like this is just from the Epic, have you added any more fleshed out testing steps? Or where should I add to as I go? 🙏

**Comment by marthakeezy** [comment]
Yes, the script hasn't been added to the wiki yet - feel free to update the wiki and this issue as you go!

**Comment by regotaina** [comment]
Followed the steps from our Feature release meeting to set up reports correctly.

- Testing on V2.2RC2
- Desktop App

- [ ] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1506" alt="Screenshot 2024-08-09 at 2 45 56 PM" src="https://github.com/user-attachments/assets/f099890c-2f59-400b-8881-d349cf110d4b">

- [ ] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [ ] Download reports from report repository, upload them to OG with subcontext: StockAndItems or Expiring. Sync. The reports should now show up on the report page.

- [ ] Click on one of the reports on the report page and ensure that it shows the correct report

- [ ] Try using the filters (Note: There is a bug if you type to fast when filtering, will be looked at)

- [ ] For item usage, generate report base analysis on whatever months you have your lookback_months set to

- [ ] Check the print button is working

- [ ] Check the export button downloads and opens in excel
