### ISSUE TITLE
V2.2.0 Release Testing: Report and Requisition (R&R) forms

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4526]
### Overview           
This issue covers all the testing related to Report and Requisition (R&R) forms and make sure that all the information related to item usage and request stock from the suppliers are correct and shown according to the configuration.
Epic issue [HERE](https://github.com/msupply-foundation/open-msupply/issues/4405)

### **TEST ENVIRONMENT**
oms Version: `v2.2.00-RC1` 
mSupply Cloud-Server: `v7-16-08`
oms app-mode: `oms-server` + `browser(chrome)`
oms db: `sqlite`

### Tests

SETUP
1. You'll need to enable the `Open mSupply: Uses program module` store pref in mSupply
2. You'll need at least one master list configured to be visible in your store, which is a program master list
3. You'll need at least one period schedule with some periods configured - and the period schedule to the master list under the `Program settings` tab
4. In Open mSupply UI, go to Replenishment > R&R Forms
5.  Ensure there has been some activity for the items in your master list during the period you are creating the R&R form for
  a. Have transactions on the days bordering the start/end of the period to confirm values are captured correctly!
6. Add the [R&R Form report](https://github.com/msupply-foundation/open-msupply-reports/tree/main/clients/East-Timor/r-and-r-form) into mSupply (or upsert into omSupply using the new script)

TEST:
- [x] Go to `Replenishment` > `R&R Forms` to view the list of R&R forms.
- [x] There is a list of R&R forms available (this will be empty the first time)
- [x] It is possible to sort the R&R list view (Sort done, filter TODO)
- [x] It is possible to export the list as a excel sheet file ( csv file TODO)
- [x] You can create a form. Clicking the create modal opens a modal:
  - [x] If you only have one program, it should be auto-selected. If you have more than one, nothing is preselected.
  - [x] Once program is selected
    - [x] If you only have one schedule for that program, it is auto-selected. If you have more than one, nothing is preselected.
    - [x] You can select any period in that schedule (but only for periods that are in the past)
  - [x] Supplier is not pre-selected
- [x] Click create
- [x] You are redirected to a detail view, which is an editable table
- [x] The form is pre-populated with values from Open mSupply: this is for values of Initial Balance, Received, Consumed, Adjustments, days out of stock, expiry (the expiry date of the oldest expiring batch of that item)
- [x] Adjusted consumption is correctly calculated based on number of days out of stock `Consumed x Days in period / Days in stock` (e.g. for period of 1 month (30 days) consumption was 20 units, but stock out was 10 days, so adjusted consumption would be 30 units)
- [x] Losses/adjustments made for this item during the period. Can be positive or negative. Populated by data from Stocktakes or Inventory Adjustments
- [x] Stock out duration: Number of days in the period where stock on hand for the item was 0
- [x] Final balance: Stock on hand for the item at the end of the period. Calculation is Initial balance + Received - Consumed + Adjustments
- [x] AMC correctly calculated as average of the adjusted monthly consumption for the last 3 periods
- [x] Maximum = 2*AMC
- [x] Expiry: Expiry date of the earliest expiring available batch of this item
- [x] Requested: Quantity to be requested in the requisition [ Calculated as Maximum - Final balance], but you can edit this value.
- [x] Low Stock: This sign is showing when stock is low. ![Screenshot 2024-08-16 at 11 57 47 am](https://github.com/user-attachments/assets/0369b832-94da-427f-a370-1355e27c1c5a)
- [x] Comment: You can add any comments to the line as needed
- [x] Confirmed: Use this column can be use to keep track of which lines are complete. Acts as the save button for changes to a line.
- [x] Approved Quantity: The quantity approved to be order from the remote authorization
  - [x] setup remote authorization
  - [x] Approve the quantities and check it is syncing back to oms site.
![Screenshot 2024-08-21 at 12 26 46 pm](https://github.com/user-attachments/assets/cf6f128f-2a6b-4f2b-9fc2-09d7aa79cec6)
- [x] You can edit the white cells
  - [x] You can refresh the page to reset your changes
  - [x] You can click the `confirm` check box to save you changes to a line
  - [x] You can't finalise the form until all lines are confirmed
- [x] Once all lines are confirmed, you can finalise the form
  - [x] You can no longer edit the form
  - [x] An Internal Order has been created for the lines that you requested quantities for
  - [x] The Response Requisition was created in the supplying store
- [x] It is possible to print the R&R form
- [x] It is possible to export the R&R form as an excel file
- [x] Creating further R&R forms... click the create button on the list view
  - [x] The program/schedule/supplier from the previous form are selected automatically, along with the next period in the schedule
  - [x] If you didn't finalise the previous form, here is a warning that you need to finalise the previous form
  - [x] After finalising the previous form, you can create the next one
  - [x] You can only select the next period in the sequence
  - [x] You can't select a previous period
  - [x] After finalising the form for the last period available, you get a message that no more periods are available
- [x] Also please ensure that you can: 
  - [x] Create R&R forms for the same period schedule/period across different programs
  - [x] Create R&R forms for the same period schedule/period and program in another store

**Comment by AnushaUp** [comment]
> 4\. In Open mSupply UI, go to Programs > R&R Forms

@lache-melvin  Has the user interface changed?
![Screenshot 2024-08-09 at 11 17 52 am](https://github.com/user-attachments/assets/212f5d59-495d-4609-b1cb-df38e8374f23)

**Comment by lache-melvin** [comment]
Yes in RC2 it has moved - thanks for noticing, I updated the epic but didn't check this issue sorry!

**Comment by AnushaUp** [comment]
@lache-melvin The language is changing when exporting and printing. Is this expected??🧐

**Comment by AnushaUp** [comment]
@lache-melvin How's this approved quantity's value going to
![Screenshot 2024-08-16 at 11 53 33 am](https://github.com/user-attachments/assets/6eece6e3-ed7d-48ed-920e-6cc736fbcf77)
 appear here?

**Comment by lache-melvin** [comment]
> @lache-melvin How's this approved quantity's value going to appear here?

Ah great question - Finalising the R&R form will create Internal Order. You'll need remote authorisation workflow set up - once the response requisition is approved, then the approved quantities should show here in the R&R form! 🙏

**Comment by roxy-dao** [comment]
Closed as testing seems completed
