### ISSUE TITLE
JavaScript error when trying to run omSupply client (V2.2.0-RC1) after upgrading

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4531]
## What went wrong? 😲

Seeing the following error when trying to run omSupply client (V2.2.0-RC1) after upgrading both the server and the client. 

![photo_2024-08-08 12 27 41](https://github.com/user-attachments/assets/93f12eef-286a-4592-9d2e-aa62f8a1b272)

## Expected behaviour 🤔

The client should run as expected, with no errors occurring

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upgrade your current omSupply version to V2.2.0-RC1 (both server and client)
2. Make sure your server is running
3. Try to run the client -> see the error

## Your environment 🌱

- Open mSupply Version: `V2.2.0-RC1`
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Remote Windows (desktop)

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Closed in #4551

**Comment by regotaina** [comment]
Tested on RC4 and RC5

No javascript error

Passed the test 👍🏾
