### ISSUE TITLE
R&R forms additional columns

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4534]
## Is your feature request related to a problem? Please describe 👀
We ran a demo of the R&R and one of the issues notes is that there are columns on the sample spreadsheet which weren't implemented. These are

* Alarm
* Approved quantity

## Describe the solution you'd like 🎁
I think that the approved quantity is best handled in a different way - as the approval process is outside of the facility level R&R process, it happens with the internal order.

In which case, we just need to add an `alarm` column.
Looking at the example excel, this has the formula

`=IF((L50<N50/4),"!!", IF((L50<N50/2),"!",""))`

i.e. 
* final balance < (maximum quantity / 4) => `!!`
* final balance < (maximum quantity / 2) => `!`

though I wonder if we can do something more elegant, perhaps the warning icon in orange & red

![image](https://github.com/user-attachments/assets/054a2fce-62c2-4439-8155-3a1be489d5f1)

If we do though, this would be for on-page display only, when printing that would need to be the exclamation mark in order to show correctly in excel

### Moneyworks Jobcode 🧰

`DFAT:TDEV`

**Comment by lache-melvin** [comment]
Sorry - part 2 still coming!

**Comment by lache-melvin** [comment]
Closed by #4570

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] You'll need the authorisation module enabled
  - [ ] Configure your user as an authoriser for your master list
  - [ ] Add use authorisation module preference in supplying store, and include requisitions in suppliers remote authorisation processes in requesting store
- [ ] Create and finalise R&R form
  - [ ] At this time, approved quantities should show as 0
- [ ] Sync (probably twice)
- [ ] Open the remote authorisation web app
- [ ] New requisition should be there, change some approved quantities and approve
- [ ] Back in omSupply, sync again
- [ ] View your R&R form - approved quantities should be there

**Comment by AnushaUp** [comment]
Tested and PASSED✅
