### ISSUE TITLE
Cannot create Stocktakes from Master Lists or for Items with Stock

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4536]
## What went wrong? 😲

We are not able to create Stocktakes that pull items from the Master Lists or that are for Items with Stock. Seems like any interaction with the items causes the app to crash. If you try to create a blank stocktake, it works as expected

**Master Lists:** 

https://github.com/user-attachments/assets/661c1dc9-b5a9-4d83-939c-936caee20812

**Items with Stock:** 

https://github.com/user-attachments/assets/e51a4fc3-3f07-48d6-b0a5-acdae3b41521

## Expected behaviour 🤔

Stocktake should be produced as expected, without crashes. Anusha shared a similar issue from a while ago - #2743, but there the app was crashing when the list of items was 5000+. Here, I am trying to pull <500 records, not 5000+. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Stocktakes
2. Create a New Stocktake -> try to add items from a Master List OR tick the 'Items with Stock' checkbox
3. See error occur. If you exit to Dashboard or log out and log in again, the stocktake entry will be there, however if you click on it, the app will crash again. So the entry gets created, but you cannot interact with it. 

## Your environment 🌱

- Open mSupply Version: `V2.2.0-RC1`
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Remote Desktop (Windows)

- Database type: SQLite3

**Comment by regotaina** [comment]
Adding to the issue: I was able to repro with a masterlist of 4 items only. Not sure if the item quantity is the issue..

**Comment by regotaina** [comment]
Error also appears if you select the checkbox:  "Itens with stock'

**Comment by AnushaUp** [comment]
Crashing occurs even when the current stocktake is opened.

**Comment by regotaina** [comment]
Tested on RC5
desktop app

it's working as expected now.
