### ISSUE TITLE
Cannot add a new patient

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4546]
## What went wrong? 😲

Besides having the permissions to add a new patient, the user cannot create a new one in OMS>Dispensary>PAtients.

Clicking the button doesn't trigger any response or alert message:

https://github.com/user-attachments/assets/bec2551f-648d-4a61-92cf-f76eec2a48ca

The button does not work on Desktop and Browser.

## Expected behaviour 🤔

If the permissions are correct, when click in the button 'New patient' a new window comes up for the user to add details .
If the permissions are not correct, an error message should come up saying 'you don't have permissions to create a new patient'

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Dispensary'
2. Click on 'New patient'
3. See error

## Your environment 🌱

- Open mSupply Version: V2.2.0RC1
- Legacy mSupply Central Server Version: V7.16

- Platform: Desktop app

**Comment by nishaDangol-Sussol** [comment]
Weird, I can create patients easily in my setup in RC1

**Comment by roxy-dao** [comment]
I can create them locally too 👀

**Comment by regotaina** [comment]
Selected a different datafile to test and I was able to create it.
If there's no permission, an alert pops up saying " You don't have permissions to access it'.

Sounds like it was a localised bug with a specific datafile. I will close it as I cannot reproduce it with another datafile.
