### ISSUE TITLE
v2.2.0 Release Testing: Synchronisations

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4553]
### **TEST ENVIRONMENT**
oms Version: `v2.2.00-RC2` 
mSupply Cloud-Server: `v7-16-04`
oms app-mode: `oms-server` + `browser(chrome)` + `apk` ;  still issues in `desktop`+`standalone`
oms db: `sqlite`

# Synchronisation Tests
### Installation Android
- [x] Install app. Starts.
- [x] Welcome screen with buttons to choose either "Client" or "Server"
- [x] Choose "Server"

### Installation Other: me installing oms-server exe with browser(chrome)
- [x] Just install! ;-) 
    - [x] Shouldn't crash whatsoever

## Initialisation
- [x] Enter "asdf" as url, site name and password and press enter. Get "Invalid url" error
- [x] Enter valid url and press enter. Site name note found
- [x] Enter a valid site name. Incorrect password
- [x] Enter valid password. Starts initialising!
- [x] Pulls central... pulls remote... integration... Done. Note: The integration count would ideally be the sum of the first 2, but many records sent to OMS are not supported in OMS.
- [x] Login screen. Login!

## Synchronisation UI
- [x] After login there are usually 1 or 2 pending logs to sync. These should show on the sync icon badge at the bottom left of navigation drawer.
- [x] Badge shows correctly whether or not the drawer is expanded to full width.
- [x] Pressing the "Sync" button in navigation takes you the Sync page
- [x] If OMS hasn't already synced your logs, it should say however many to push. Otherwise the progress will likely show about "2/2" under "Push" if already synced.
- [x] Create an outbound shipment with 1 line. The badge on "Sync" should update promptly. 
- [x] On Primary Server make a new master list and add 3 items. On omSupply sync. Should get "Pull Central" 4/4. (Should be at least 4, don't fret if something extra snuck, but not 50 extra.).
- [x] On Primary make a CI with 3 lines to the OMS store. Should get "Pull remote" 4/4, and "Number of records to push" up to 4-5. This for the transfer/inbound shipment made on OMS needing to be sent back to the central server on the next sync cycle.

## Reinitialise
- [x] Get an idea in your head of what data you had, perhaps from all your testing above
- [x] Clear app data and restart app
- [x] Reinitialise the app
- [x] The data from before reinitialising the app appear to still be there

## Version-updates
- [x] Set up a remote site in previous oms version : I used v1.7.0
- [x] Sync
- [x] Now get the latest release-version for oms : to v2.2.0-RC2
- [x] Upgrade it
- [x] Login
- [x] Logins should be smooth. No errors after version-upgrade
- [x] All the previous data is all maintained well

**Comment by nishaDangol-Sussol** [comment]
> - [ ] "Integrate" should also say 4/4. 
>

I'm not really sure about this one. I'm guessing these test-cases are old ones and may not have been updated for v2.2 as well.
@roxy-dao maybe you could confirm this for me: Does pulling records from Primary STRCITLY needs the records to be integrated as well in oms? 
As per the test-case above, 
- On Primary make a CI with 3 lines to the OMS store. 
- Should get "Pull remote" 4/4, and "Number of records to push" up to 4-5. This for the transfer/inbound shipment made on OMS needing to be sent back to the central server on the next sync cycle.
- "Integrate" should also say 4/4. - **is this one a NECESSARY here?**

**Comment by roxy-dao** [comment]
Sometimes if you have too little records it can be over really fast, so you might not see the integration numbers

**Comment by nishaDangol-Sussol** [comment]
> Sometimes if you have too little records it can be over really fast, so you might not see the integration numbers

If it was matter of speed, wouldn't the records number show anyways after the sync has completed, like in this particular case below: 
<img width="758" alt="image" src="https://github.com/user-attachments/assets/b8446eed-f4a6-4a66-b3ad-5b96aafa0819">

**Comment by roxy-dao** [comment]
@andreievg ? ^

**Comment by nishaDangol-Sussol** [comment]
will update test-scripts accordingly
