### ISSUE TITLE
Diesel deserialisation error on Internal Orders page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4555]
## What went wrong? 😲

I get this error when I open the Internal Order list view:
![Screenshot 2024-08-09 at 4 28 01 PM](https://github.com/user-attachments/assets/492638e4-099c-4f2b-a2ef-ea1e218b5b96)

It's from the programSettings query - querying the requisitions_by_period view, which hasn't been updated to handle nullable orderType values (Internal Orders generated from R&R forms don't have an order type)

## Expected behaviour 🤔

No error

Not sure whether the better to update the view, or set R&R form requisitions to Normal ordering type?

But in the `requisition` table `order_type` is nullable, so the view should probably expect the same type?!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have programs configured
2. Create and finalise an R&R form
3. View the Internal Orders pages
4. See the error

## Your environment 🌱

- Open mSupply Version: 2.2 RC1
- Legacy mSupply Central Server Version:

- Platform:

- Database type: Postgres

**Comment by andreievg** [comment]
I think we should change the view to enforce not null (add 'where' clause).

> or set R&R form requisitions to Normal ordering type

Ideally our configurations for RnR would be the same as normal program requisitions, and would use the modal (which actually relies on name_tag). We can discuss this on Thursday

**Comment by andreievg** [comment]
Daily triage: Hot Fix

**Comment by roxy-dao** [comment]
Closed in #4573
