### ISSUE TITLE
Total/Available  SoH number looks wrong after stocktake for existing lines whose packsize is greater than 1

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4559]
## What went wrong? 😲
If you do stocktake of existing lines (with pack size greater than 1), after that stocktake, the SoH number is messed up.

## Expected behaviour 🤔
SoH should be correct as per the stocktake taken

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a item stock whose pack-size is greater than 1. (You can repack existing ones to do so). In my case, I've 1 pack `apple` item, whose pack-size=2; thus SoH=2
2. Create new stocktake
3. Select that item
4. Existing batch of packsize-2 appears with `snapshot packs`=1
5. Change `counted packs` to 5. As per this, now new SoH should be 2*5=10
6. Finalise stocktake and View stocks
7. See 1st error: `apple` item's pack-size is 1 (despite that I changed existing lines whose pack-size was 2 and fixed)
8. See 2nd error: SoH shows 9: wrong value here

## Your environment 🌱

- Open mSupply Version: v2.2.00-RC2
- Legacy mSupply Central Server Version: v7-16-04

- Platform: oms-server, browser(chrome)

- Database type: sqlite

**Comment by andreievg** [comment]
I was able to replicate, sounds pretty bad. Replicate as per the video sent on telegram:
* Store with pack to one enabled
* Add a batch of pack size 2 number of pack 1 (stocktake)
* Batch should be adjusted to pack size 1 number of packs 2
* Repack that batch to pack size 2 number of pack 1
* Add new stocktake with that pack, set number of packs to 5, then finalise
* You will 9 as SOH in stock view, but ledger will show 8

**Comment by andreievg** [comment]
Daily triage, recommend as hot fix

**Comment by santoshkhanal12** [comment]
Tested on `v2.2.1`

# 🧪 Testing



- [ ] Add stock with pack size greater than 1
- [ ] Do stocktake with that stock and add more stock
- [ ] Finalise stocktake
- [ ] Go back to stock view and make sure numbers are correct
