### ISSUE TITLE
On-hold filter for locations looks incorrect

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4561]
## What went wrong? 😲
If you see toggl filters, the common belief is to expect values as per the toggle is ON or OFF. For locations, `on-hold` filter, on-hold locations appear on both instances, when the toggl is ON and OFF

## Expected behaviour 🤔
Result should display as per the toggl result?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have some locations, with both on-hold and normal ones
2. Locations list> Filter. Select `On Hold` option
3. The `On Hold` toggl appear
4. ON it: you'll see on-hold locations : good
5. OFF it: See error; on-hold locations are still appearing among the NOT on-hold locations

## Recordings

https://github.com/user-attachments/assets/fec163da-48fc-43b6-b17f-e563c845606b

## Your environment 🌱

- Open mSupply Version: v2.2.00-RC2
- Legacy mSupply Central Server Version: v7-16-04

- Platform: oms-server + browser(chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
This is expected behaviour for all the switches in filters 🤔  if switch is off = show all records

**Comment by nishaDangol-Sussol** [comment]
> This is expected behaviour for all the switches in filters 🤔 if switch is off = show all records

If that is how it's documented as well, then can be closed
