### ISSUE TITLE
Unable to remove/delete Cold chain sensors

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4565]
## What went wrong? 😲

We need a way to remove/delete Cold chain sensors so they don't appear in the UI of omSupply anymore. For example, if the sensors are transferred between the facilities or lost or simply disconnected, there is no way to stop them from appearing. The sensors below have been disconnected since mid-May - even deactivating them in mSupply does not remove them from the interface. 

<img width="1511" alt="Screenshot 2024-08-13 at 10 43 15 AM" src="https://github.com/user-attachments/assets/218bfff4-1c95-40e8-bcf8-f38e4d3c80ad">

<img width="368" alt="Log an issue" src="https://github.com/user-attachments/assets/62cb2447-ea65-4fd7-8676-b1fb8284e95a">

## Expected behaviour 🤔

Should be able to remove sensors that are not connected to the device anymore.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Since there is no way to directly connect the sensors to OMS, you will need to connect them to CCA first
2. Sync your CCA with a Remote Site
3. Note once connected, there is no way to remove the sensors
4. Go to OG mSupply -> deactivate the sensors
5. Note this does not resolve the issue -> the sensors still appear in the UI

## Your environment 🌱

- Open mSupply Version: V2.2.0-RC2
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Desktop App for Windows

- Database type: SQLite3

**Comment by andreievg** [comment]
Daily triage, not a hot fix candidate so leaving for weekly triage

**Comment by mark-prins** [comment]
Closing in favour of #3207
