### ISSUE TITLE
Catalogue -> Assets -> the count does not update when deleting assets

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4567]
## What went wrong? 😲

When deleting assets, the total count does not update :)

- the count does update when importing an asset
- from Laché: this is due to the query filtering out rows with a `deleted_datetime`, but the count call does not!

https://github.com/user-attachments/assets/6dfa66f9-5d68-483a-b61a-b74043acb3ad

## Expected behaviour 🤔

The count should update when removing an asset

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Assets
2. Note the total number of assets (if using the standard WHO list, you should have 168 unless you deleted some previously)
3. Remove an asset or multiple assets
4. Note the total number does not change
5. Try logging out, logging in again, syncing, navigating to another page - the issue persists

## Your environment 🌱

- Open mSupply Version: V2.2.0-RC2
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Desktop App for Windows

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Closed in #4625
