### ISSUE TITLE
R&R Forms perfomance

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4568]
## What went wrong? 😲

When you have a number of rows in an R&R form the performance degrades

## Expected behaviour 🤔
Editing a single line should be pretty snappy

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an R&R form using a master list with 50+ rows
2. Edit a row on a tablet, or
3. add a `console.info` to the RnRFormLine component

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
We had a small chat yesterday with @lache-melvin, and decided that loading indicator on 'confirm' would actually deal with immediate issue atm. 

In terms of looking at the core issue, i think it's ok to spend like 1 hours max to see if it can be fixed, since we still need to discuss our strategy for doing RnR forms, which may require some re-work, so probably not worth spending too much time on it at the moment

**Comment by AnushaUp** [comment]
Hi @mark-prins  Tried making R&R forms with masterlist having 83 items and got this result it takes times even when scrolling after form is loaded. Video [HERE](https://drive.google.com/drive/folders/1O2Ly4yJOanQ6k7Lc5dv3xNKFeRcB1T0q?usp=sharing)

**Comment by lache-melvin** [comment]
Hey @AnushaUp - can you confirm that the slowness is only when scrolling, editing the lines is ok?

Also, how fast is the UI in other areas of the app?

**Comment by mark-prins** [comment]
I've had a look at the desktop version - running through remote desktop it's pretty slow to redraw the table when you scroll. If I connect directly it's ok I think : screen recording in [this folder](https://drive.google.com/open?id=1sbPz68EzE9yXhp7HdhwC4twzKgMklga9&usp=drive_fs)

**Comment by AnushaUp** [comment]
@lache-melvin @mark-prins takes time in loading mostly and seems like slower in mobile version. Will the speed improve?

**Comment by AnushaUp** [comment]
Since this will be left as is, I'm moving this to done.
