### ISSUE TITLE
No need to show 0 lines (deleted lines + issued-out lines) in exported list under View Stocks

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4574]
## What went wrong? 😲
If there are any stock lines that you deleted/adjusted and now are no longer part of the stocks, those deleted lines shouldn't appear even in export list

## Expected behaviour 🤔
see above
## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have some stock lines or create them
2. Delete some of the lines through invads
3. Also try issuing out the whole line as well
4. Now in that `View stocks` list, click `Export` button at top-right
5. See error: the exported list shows the deleted + issued-out lines as well

## Screenshots
`View stocks` list:
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/1bcd238b-a2dc-4269-b694-b56d87fbb70b">

Exported List:
<img width="951" alt="image" src="https://github.com/user-attachments/assets/61e1cbf3-e758-402f-a667-56d031f4c5ff">

## Additional
The difference is too big for me to tag it as normal-severity, but again it is a test-datafile though. I'll let you guys decide the severity here

## Your environment 🌱

- Open mSupply Version: v2.2.00-RC2
- Legacy mSupply Central Server Version: v7-16-04

- Platform: oms-server + browser(chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment]
Filter `useExportStockList` by `has_packs_in_store`

**Comment by roxy-dao** [comment]
Closed in #4613

**Comment by AnushaUp** [comment]
Tested and works as expected✅
