### ISSUE TITLE
Catalogue -> Master List Lines: Code sorting does not work

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4578]
## What went wrong? 😲

When navigating to Catalogue -> Master Lists, and trying to sort by 'Code' column, the sorting does not work and seems to be sorting by items' names instead. 

## Expected behaviour 🤔

Code sorting should be separate from Name sorting and should sort alphabetically as expected

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Master Lists
2. Click on 'Code' column to attempt and sort by codes
3. See codes appearing out of order and the results instead being sorted by items' names

## Your environment 🌱

- Open mSupply Version: V2.2.0-RC2
- Legacy mSupply Central Server Version: V7.16.08

- Platform: Desktop Application for Windows and .apk on the tablet (Galaxy A8 Tab)

- Database type: SQLite3

**Comment by roxy-dao** [comment]
RE: Click on a master list to go view master list lines and try sort by code

**Comment by marthakeezy** [comment]
Sorry, I think I might have logged a duplicate of... #4308?

**Comment by roxy-dao** [comment]
It is not a duplicate. Unit is no longer sortable in Master list line this is a new bug.

**Comment by roxy-dao** [comment]
Closed in #4624

**Comment by santoshkhanal12** [comment]
Tested on `2.2.1`

# 🧪 Testing



- [x] Click on Master List
- [x] Click on a line
- [x] Try sort by code


https://github.com/user-attachments/assets/ce3dfb40-8e80-42bf-8a21-2232e20f288b
