### ISSUE TITLE
V2.2.0 Release Testing: Basic Reports (tablet)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4582]
Followed the steps from our Feature release meeting to set up reports correctly.

- Testing on V2.2RC3 APK

- [x] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1506" alt="Screenshot 2024-08-09 at 2 45 56 PM" src="https://github.com/user-attachments/assets/f099890c-2f59-400b-8881-d349cf110d4b">

- [ ] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [x] Download reports from report repository, upload them to OG with subcontext: StockAndItems or Expiring. Sync. The reports should now show up on the report page.

- [x] Click on one of the reports on the report page and ensure that it shows the correct report

## ITEM USAGE
- [ ] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK STATUS
- [ ] Try using the filters
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK DETAILS
- [ ] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## EXPIRING STOCK
- [ ] Try using the filters
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

**Comment by roxy-dao** [comment]
Closing as done~
