### ISSUE TITLE
Stock Detail report not excluding batches when SOH=0

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4585]
## What went wrong? 😲

The Stock Detail report is including some ghost stock lines that have 0 SOH.
I cannot seem to find them under inventory.

<img width="661" alt="Screenshot 2024-08-14 at 12 33 07 PM" src="https://github.com/user-attachments/assets/e95c04f4-329c-4042-a98d-3b159bc17826">

## Expected behaviour 🤔

The deport should include only batches with SOH>0

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inventory'
2. Click on 'Inventory adjustment' and record that all items from that batch have been lost
3. Now go to 'Reports' > Stock Details
4. See the stock line you have just deleted in your report.

## Your environment 🌱

- Open mSupply Version: V2.2.RC2
- Legacy mSupply Central Server Version: V.7.16

- Platform: Desktop app

**Comment by AnushaUp** [comment]
Couldn't recreate this in stock details Report 
![Screenshot 2024-09-13 at 9 40 15 am](https://github.com/user-attachments/assets/e5e03db5-af5c-4c42-93f9-7e78637a79d5)
