### ISSUE TITLE
Basic Reports error shows eternal loading indicator

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4587]
## What went wrong? 😲

If something goes wrong generating the report, you get the error snack, and then the loading indicator for the rest of time:

![image](https://github.com/user-attachments/assets/d811ffd1-6ac7-4b5e-9a60-2ba942d2c484)

## Expected behaviour 🤔

Nothing here component? Something went wrong? Some way to indicator that we tried and failed, but we aren't still trying 🤷‍♀️ 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Bang something up with your report config (or in my case, don't have the right permissions on for the report query hehe)
2. Generate the report
3. Its a disaster, you get an error
4. Circles of doom

## Your environment 🌱

- Open mSupply Version: V2.2.0 RC3
- Legacy mSupply Central Server Version: 7.16

- Platform: Android, also verified in browser

- Database type: sqlite

**Comment by roxy-dao** [comment]
Closed #4594

**Comment by regotaina** [comment]
Tested on RC5

Desktop app

# 🧪 Testing



- [x] Remove view item permissions in OG
- [x] Load stock status report 
- [x] Sync OMS 
- [x] Try to view stock status report
- [ ] Should show Nothing here page with no permission message

@roxy-dao I tested 2 scenarios:

1) If I follow exactly the same steps above, it still allows me to view the report.
2) If I remove the view Reports permissions in OG, I cannot see the report.

Sounds like the visibility is not tied to items, but to reports.

**Comment by roxy-dao** [comment]
> Tested on RC5
> 
> Desktop app
> 
> # 🧪 Testing
> * [x]  Remove view item permissions in OG
> * [x]  Load stock status report
> * [x]  Sync OMS
> * [x]  Try to view stock status report
> * [ ]  Should show Nothing here page with no permission message
> 
> @roxy-dao I tested 2 scenarios:
> 
> 1. If I follow exactly the same steps above, it still allows me to view the report.
> 2. If I remove the view Reports permissions in OG, I cannot see the report.
> 
> Sounds like the visibility is not tied to items, but to reports.

It's tied to both, but item usage is only tied to reports since it's calling database directly (there is an issue to fix this)

**Comment by regotaina** [comment]
> 
> It's tied to both, but item usage is only tied to reports since it's calling database directly (there is an issue to fix this). So if you load expiring items report and remove stock permissions then you shouldn't be able to view report

for some reason I can view the report despite not having 'vie items' permission. :(

**Comment by roxy-dao** [comment]
Items can be viewed without permission XD

**Comment by lache-melvin** [comment]
> for some reason I can view the report despite not having 'view items' permission. :(

Yep, this is expected (sorry I didn't make the testing steps clearer, with exactly which permissions) - expiring items actually uses the stock lines query, so would be affected by the view stock permission! But also as Roxy said, the data queries for some of the reports aren't currently checking permissions (they are querying the database directly) so only controlled by if you have the view reports permission 🙏
