### ISSUE TITLE
Basic Reports only capture first 100 lines

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4588]
## What went wrong? 😲

Only the first hundred lines are being returned in any of the reports! I can't see anywhere to enter pagination preferences...

## Expected behaviour 🤔

All lines are included in the report (or a way to select the range)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have more than 100 stock lines
2. Create stock status detail report
3. Only the first 100 are included in the report!

(Same issue for all reports) 

## Your environment 🌱

- Open mSupply Version: v2.2.0 RC3
- Legacy mSupply Central Server Version: 

- Platform: browser

- Database type:

**Comment by AnushaUp** [comment]
Tried with more than 500 items and looks good✅
