### ISSUE TITLE
Clearer reason why report could not be generated

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4589]
## What went wrong? 😲

I didn't have the right permissions... would have expected that to give me a permission denied error? But just got this, which wasn't very helpful to try to troubleshoot:
![Screenshot 2024-08-14 at 4 49 59 PM](https://github.com/user-attachments/assets/a2153ae5-416a-4bd9-ad08-22df99a09086)

## Expected behaviour 🤔

Looks like we could pull out the forbidden response? 
![Screenshot 2024-08-14 at 4 48 46 PM](https://github.com/user-attachments/assets/bc71f7b7-7a7b-4e6a-a8a1-77185d8a9c10)

Would love to see the typical not authorised popup, or at least translate the structured error... not sure if there are other structured/expected errors as well?

`Unable to generate report` should mean there's nothing the user can do, unexpected error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have wrong permissions (i.e. can't view stock)
2. Generate stock details report
3. See `Unable to generate report`

## Your environment 🌱

- Open mSupply Version: v2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #4594

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.02-RC1`


- [ ] Remove view item permissions in OG
- [ ] Load stock status report 
- [ ] Sync OMS 
- [ ] Try to view stock status report
- [ ] Should show Nothing here page with no permission message

**Comment by AnushaUp** [comment]
@roxy-dao @lache-melvin These item view permission doesn't make any difference in viewing the report
![Screenshot 2024-09-13 at 11 37 37 am](https://github.com/user-attachments/assets/9069a1b4-b9bb-4b66-9315-f4a595f508dd)

**Comment by lache-melvin** [comment]
Hey @AnushaUp, the `view items` permission actually doesn't do anything in Open mSupply currently! (It's just based on store access) - I think the stock status and item usage reports are only affected by the report permission. The other two (stock detail and expiring items) should be affected by the view stock permission. So I think this is expected behaviour 🙏
