### ISSUE TITLE
Incorrect reference columns in R&R form

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4596]
## What went wrong? 😲

- `rnr_form` table has column `requisition_id`, which references `requisition`. R&R forms are synced to COMS, but Requisitions are synced to COGS. So requisition reference would break after sync from ROMS to COMS. Need to remove reference constraint.
- Same deal for `rnr_form_line.requisition_line_id`
- `rnr_form_line` has `item_id`. This needs to be changed to `item_link_id`, to support item merging

## Expected behaviour 🤔

- Can merge items and R&R forms still work
- Can sync remote R&R form to central OMS

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. On remote site, create & finalise an R&R form
2. Sync
3. On central server, see integration error: `ForeignKeyViolation("\"insert or update on table \\\"rnr_form_line\\\" violates foreign key constraint \\\"rnr_form_line_requisition_line_id_fkey\\\"\"")`
4. AND merge an item and watch as your R&R form gets confuzzed

## Your environment 🌱

- Open mSupply Version: 2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #4612

**Comment by regotaina** [comment]
# 🧪 Testing

Tested on V2.2.0
mSupply version: V7.16
Client/server
Browser: Chrome



- [ ] Sync remote R&R form to central - no error
- [ ] Merge an item - still see item details

**Comment by regotaina** [comment]
testing blocked due to [issue with merging items](https://github.com/msupply-foundation/msupply/issues/15280)

**Comment by regotaina** [comment]
Now the [blocker](https://github.com/msupply-foundation/msupply/issues/15280) has been closed,  I can finally go back to testing this one.
