### ISSUE TITLE
R&R form headers should be sticky at top of page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4597]
## What went wrong? 😲

What column is what 😱 
![Screenshot 2024-08-15 at 2 51 51 PM](https://github.com/user-attachments/assets/73015750-30e2-4312-9268-ef450db25530)

## Expected behaviour 🤔

Header row stays fixed always visible at top of page

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to R&R form, with enough rows
2. Scroll down
3. Header disappears

## Your environment 🌱

- Open mSupply Version: V2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
@lache-melvin Those two sticky columns may also required enhancement, does't looks good when scrolling sideward.

https://github.com/user-attachments/assets/8ac0b641-9434-4495-8122-3616f4147891

**Comment by mark-prins** [comment]
Fixed with #4568 ( and @lache-melvin has found a fix for the columns sideways scroll looking bad too! )

**Comment by regotaina** [comment]
# 🧪 Testing

Tested on V2.2.0
mSupply version: V7.16
Client/server
Browser: Chrome/ apk and App


Check if headers are fixed on top of page
- [x] Headers are fixed

PASSED the test 👍🏾
