### ISSUE TITLE
Expiry dates are not readable in the issue stock window

### ISSUE THREAD

**Issue by craigdrown** [msupply-foundation/open-msupply#4601]
## What went wrong? 😲

![CleanShot 2024-08-16 at 15 17 07](https://github.com/user-attachments/assets/6d22c442-678e-4408-af19-80082b2075f6)

## Expected behaviour 🤔
need to be able to see the year.

## How to Reproduce 🔨
On current https://demo-open.msupply.org/ as of 16 August 2024 - 15:20

## Your environment 🌱
https://demo-open.msupply.org/
- Open mSupply Version: 2.1.0

**Comment by andreievg** [comment]
Daily triage, hot fix

**Comment by roxy-dao** [comment]
Closed in #4637

**Comment by regotaina** [comment]
Tested on V2.2.0 
Desktop app

it looks great!! 🥇 

![Image](https://github.com/user-attachments/assets/fcd47675-6c90-4c07-8e8e-49d9e45030c0)
