### ISSUE TITLE
R&R AMC calculation and rounding

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4602]
## Is your feature request related to a problem? Please describe 👀
Request in from client:

- If there is no data for the last two months, AMC must be the same as adjusted consumption.  if the adjs. consumption is 200 the AMC is 200 too.
- If we have data previous for 3 months recently, some time the result can have decimal points, ex  677.42 or 677.66
 if it is possible the Quantity can be rounded up automatically?   from  677,.42 automatically will show  677 tabs. 

The rounding will have to apply to AMC, Maximum & Requested values. 
Will need to happen in the report too.

If it doesn't adversely affect performance, add a tooltip for the more accurate value.
For the AMC calculation - stick with concurrent periods; i.e. don't look for a previous form while skipping intervening, uncompleted periods. Look back until you reach an uncompleted form, up to a maximum of the 3 months.

**Comment by AnushaUp** [comment]
PASSED✅
