### ISSUE TITLE
R&R forms are not re-initialised for remote sites

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4604]
## What went wrong? 😲

Created some R&R forms and reinitialised remote site - R&R forms list was empty! They are in the central DB though.

## Expected behaviour 🤔

R&R forms should be present in re-initialised DB!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. In remote site, create R&R form
2. Reinitialise remote site
3. R&R form ain't there 😱 

## Your environment 🌱

- Open mSupply Version: v2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.01`


- [ ] on remote site, create r&r
- [ ] sync
- [ ] wipe and reinitialise
- [ ] your form has returned!

**Comment by regotaina** [comment]
Passed the test 👍🏾
