### ISSUE TITLE
Intermittent test failure: approved quantity transfer

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4608]
## What went wrong? 😲

There's some kind of race condition/dependency in the tests - is it an actual bug?

## Expected behaviour 🤔

Tests consistently passss

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run backend tests
2. Maybe run many time?
3. Requisition transfer test will fail, approved quantity didn't get transferred?

## Your environment 🌱

- Open mSupply Version: V2.2.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
There has been some fixes for this in this PR, but that was for postgres, do we have issues with sqlite ?

https://github.com/msupply-foundation/open-msupply/pull/3904

**Comment by lache-melvin** [comment]
This is now fairly consistently failing our CI build - what changed? Can we bump severity here, I think being able to rely on CI checks should be an important part of our workflow?

**Comment by lache-melvin** [comment]
Related: #3624

**Comment by Chris-Petty** [comment]
Halp

```
---- processors::transfer::requisition::test::requisition_transfer stdout ----
thread 'tokio-runtime-worker' panicked at service/src/processors/transfer/requisition/test.rs:548:5:
assertion `left == right` failed
  left: 42.0
 right: 0.0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'processors::transfer::requisition::test::requisition_transfer' panicked at service/src/processors/test_helpers.rs:20:16:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(383), ...)
```

**Comment by Chris-Petty** [comment]
Nvm I was on `main` 🙄
