### ISSUE TITLE
Refreshing page results in components going everywhere??

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4616]
## What went wrong? 😲

The UI has lost all understanding of space and time...

![Screenshot 2024-08-19 at 12 17 58 PM](https://github.com/user-attachments/assets/06f5e8c8-8994-4281-b316-f73b358d654b)

I've tracked the cause down to the addition of the useTranslation hook in the ReportArgumentsModal? But why??

https://github.com/msupply-foundation/open-msupply/blob/aa482282bbf125029b4aa19edec8117ae005189d/client/packages/system/src/Report/components/ReportArgumentsModal.tsx#L23

## Expected behaviour 🤔

Rendering as per usual

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Internal Orders/Requisition detail view, or stocktake detail (these seem to be the worst affected?)
2. Refresh the page

## Your environment 🌱

- Open mSupply Version: v2.2.0 RC4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by regotaina** [comment]
# 🧪 Testing

Tested on V2.2.0
mSupply version: V7.16
Client/server
Browser: Chrome


Check the following pages, navigate to them and refresh: should look ok
- [ ] R&R forms detail view
- [ ] Requisition detail view
- [ ] Internal order detail view
- [ ] Stocktake detail view
