### ISSUE TITLE
V2.2.0 Release Testing: Outbound Returns

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4623]
Tested on `V2.2RC5`

# Outbound Returns

**New Outbound Return from a Shipment**
- [x] Go to 'Inbound shipment' and choose a shipment
- [x] Select a stock line from this shipment to be tested. Take notes of the batch.
- [x] Click on the checkbox on the right side and after selection, click on the drop down menu and select 'Return selected lines'
- [x] A new window will come up for you to add the 'quantity to return' 
- [x] Click in the button 'Next step' and a new screen will come up for you to add a Reason (if you have this set up) and a Comment.
- [x] Reason is a drop down field, while Comment is free text 
- [x] Click in the button 'OK'
- [x] A new Outbound Return window will come up
- [x] The item and quantity should match what you selected in the Outbound shipment 
- [x] You can add an item by clicking in the button 'Add Item'
- [x] The button 'More' will show you the user who created the shipment and in the related comment the reference of the Inbound shipment this return came from
- [x] You can change the colour of this return and add a new comment
- [x] The 'Delete button' is available and if you click it will ask if you want to delete this return
- [x] You can select the box 'Hold' to prevent the status of this return from being updated
- [x] You can delete item lines by selecting the checkbox on the right side and choosing the option 'Delete selected lines' in the drop down menu
- [x] Click 'Confirm Picked' and status should change to 'Picked'
- [x] Click 'Confirm Shipped' and the items will be moved to your stock
- [x] Go back to 'stock' 
- [x] The stock Quantity should be decreased via Outbound Return and new stockline should be created on by stating that and Type should have 'Outbound Return' in the ledger tab
- [x] Quantity should be correct as stated by the 

**Create new Outbound Return manually**
- [x] Go to 'Replenishment' > 'Outbound Returns'
- [x] Click on button `New Return` and select Supplier
- [x] New outbound Return will be created
- [x] You can add item and it will show all the available batches of that item
- [x] Select one of the batch and Enter the quantity to return and press `Next Step`
- [x] Enter Reason (If available) and comment and press `OK`
- [x] Update the status Confirm Picked and Shipped
- [x] Go back to 'stock' 
- [x] The increase via Inbound Return should have created a new stock line. If you check the ledger tab it should say 'inbound return'

**Comment by roxy-dao** [comment]
Closed as completed

**Comment by AnushaUp** [comment]
Build Test Passed in Desktop✅
