### ISSUE TITLE
Layout of date picker on tablet is ugly

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4628]
## What went wrong? 😲

The layout of the date-picker doesn't look finished, e.g. the time is large and off-center compared to the date: 

![telegram-cloud-photo-size-1-5051257534874234274-y](https://github.com/user-attachments/assets/3e04a775-aaad-4d3e-aeee-d92e4dfe31e7)

## Expected behaviour 🤔

It should look nicely formatted / deliberate

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain > Monitoring
2. Open the date picker

## Your environment 🌱

- Open mSupply Version: 2.2.00-RC3

**Comment by mark-prins** [comment]
Note that this is the default material UI datepicker formatting. 
here's how [their demo](https://mui.com/x/react-date-pickers/date-time-picker/) looks

![image](https://github.com/user-attachments/assets/6a8d51f6-c025-4ff3-a023-64482e5bd2f6)

**Comment by adamdewey** [comment]
Interesting. 

I would say that we probably don't need seconds in our date picker - that could give us some real estate back if we limit only to minutes?

**Comment by andreievg** [comment]
> I would say that we probably don't need seconds in our date picker - that could give us some real estate back if we limit only to minutes?

I don't think we have an option to adjust ? An alternative is to use: https://capawesome.io/plugins/datetime-picker/ for android or to write picked ourselves (we did it for Conforma, so could take that and re-style + add time picker). Mui date picker is actually pretty chunky (bundle size wise), so maybe worth considering, but doubt we have time for it

**Comment by andreievg** [comment]
Daily triage, not a hot fix candidate so leaving for weekly triage

**Comment by adamdewey** [comment]
> I don't think we have an option to adjust ?

Oh, I was assuming there was some config option because in their screenshot it doesn't show seconds?

**Comment by mark-prins** [comment]
yep, it's config - we are deliberately showing seconds 🙄 

how do you like them apples?

<img width="585" alt="image" src="https://github.com/user-attachments/assets/d8d17d65-72c5-4f9f-a8ea-38718ed6e1f0">

**Comment by adamdewey** [comment]
I like them apples heaps better!

**Comment by Chris-Petty** [comment]
Noticed this elsewhere: Monitoring > some fridge > pick date range

![Screenshot_20241004_123651_Open mSupply](https://github.com/user-attachments/assets/d6fa2c64-155c-4b15-8c3c-6b3873aba915)

- The different fonts sizes and general lack of alignment of year month and date are jarring
- When using the time picker and dragging it around, the width of the modal jumps about because of the changing length of the time. This is unpleasant 😀 .

Do we need seconds on the date picker range for temperature logs?

**Comment by Chris-Petty** [comment]
Reopening because I realised it is the same area. I guess this regressed? Or someone wanted seconds back?

**Comment by andreievg** [comment]
Triage, sounds like a regression, and this was fixed, implementor to try and see why

**Comment by mark-prins** [comment]
I've just tested on develop and I get this:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/5884f86c-a1c3-437b-841a-a498838bbc5c">

@marthakeezy are you able to check in the RC version on a tablet please?

**Comment by marthakeezy** [comment]
Looks fine in `V2.3.0-RC8`

<img width="817" alt="1" src="https://github.com/user-attachments/assets/d94668d4-cfa4-4284-8c0e-f7b2c3e9465f">

But I think the seconds are missing? E.g. the format is now HH.MM not HH.MM.SS?

**Comment by roxy-dao** [comment]
> Looks fine in `V2.3.0-RC8`
> But I think the seconds are missing? E.g. the format is now HH.MM not HH.MM.SS?

Yes that is on purpose, the linking PR #4630 removes secconds

**Comment by marthakeezy** [comment]
Nice, looks good on my end

**Comment by Chris-Petty** [comment]
Hmm well I can't confirm what version I was on sorry. I think it was 2.3.0-RC5 but there is a chance it was 2.2.0X. Anywho, sorry if false positive!
