### ISSUE TITLE
v2.3.00 (16th October)

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4629]
# Key aims
* Backdating prescriptions
* #4642
* Basic built in reports (part 2/3)
* ~~Backend plugins~~ -> 2.4

# Deadlines (in NZT)

Date started: Thur 22 August, 2024
PR deadline: Wed  18 September 2024
PRs merged: Wed 25 September 2024
Release: Wed 16 October 2024

**Comment by lache-melvin** [comment]
🎉
