### ISSUE TITLE
R&R sent date is not set on internal order

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4641]
## What went wrong? 😲

when creating and then finalising an R&R form, an internal order is created with the status is set to `Sent`. On checking the footer, the timeline of status changes only has `Draft`

<img width="340" alt="image" src="https://github.com/user-attachments/assets/afdae33a-59c9-4611-9576-35a56b69c5d4">

## Expected behaviour 🤔
Should set the `sent_datetime` timestamp as well as the `created_datetime`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to R&R forms
2. Create a form, and finalise
3. Check the list of internal orders, click on the most recent one

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in OMS version `V2.2.01`


- [ ] create an R&R form and finalise. View the internal order : the sent date should be the same as the created date
