### ISSUE TITLE
GAPS: Store Properties are saved but doesn't show up

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4647]
## What went wrong? 😲
Own store properties are saved but doesn't appear when trying to edit.

Details [HERE](https://github.com/msupply-foundation/open-msupply/issues/4633#issuecomment-2301148639)
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Setup for GAPS
2. Goto Settings > Configuration and initialise store properties for GAPS
3. Add some properties for the active store in the oms cloud server and save it
4. The properties are saved but doesn't seems to be appear in the Edit field.
![Screenshot 2024-08-21 at 1 37 58 pm](https://github.com/user-attachments/assets/b51ab4f3-d5eb-4218-80b8-9eb455fcd88a)

## Your environment 🌱

- Open mSupply Version: v2.2.00-RC5
- Legacy mSupply Central Server Version: V7.16.08

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Initial load on clicking edit button is undefined

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC1, the info is saved and shows up if you change properties of a Central Server from Central Server, and also of a store from Central Server (so both scenarios are working fine). Moving to Done :)
