### ISSUE TITLE
Mark programs as Immunisation programs

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4652]
Currently immunisation programs are a separate kind of program, only stored in OMS Central. We need to change this to creating a program in legacy mSupply, then marking that program as an immunisation in Open mSupply. This will allow us to use existing patient program functionality.

STEPS:
- [x] mSupply change - move is_immunisation flag to mSupply
- [x] Update translation to map in this new flag
- [x] bump sync versions
- [x] UI changes - remove Immunisation program create button - list should already contain all immunisation programs
- [x] Remove delete immunisation programs... they would be deleted in mSupply - ensure this is a soft delete though? if there is patient data they need to be soft deleted
- [ ] Remove immunisation program context?

**Comment by lache-melvin** [comment]
> * [ ]  mSupply change - move is_immunisation flag to mSupply


https://github.com/msupply-foundation/msupply/pull/15168

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
