### ISSUE TITLE
Add dose schedule to Vaccine Course edit modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4653]
Replace the `Number of doses` field:

![Screenshot 2024-08-22 at 10 28 16 AM](https://github.com/user-attachments/assets/b60044ec-6908-4bef-bcad-502a770a9bc8)

With the dose schedule table:

![Screenshot 2024-08-22 at 10 28 01 AM](https://github.com/user-attachments/assets/2185f2f2-739d-436d-851f-54466a216487)

Number of doses can be calculated based on number of rows.

Per existing VaccineCourseSchedule - just add dose number and label for now, additional fields in separate issue

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
