### ISSUE TITLE
Add minimum_interval and minimum_age to vaccine course schedules

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4654]
We need to capture the min number of days between doses, and when a patient should be able to receive the dose:

![Screenshot 2024-08-22 at 10 42 02 AM](https://github.com/user-attachments/assets/68d2707e-7aa6-40cc-a3c1-971ea42b7589)

- new `Int` field on vaccine_course_schedule: `min_interval_days`
  - Min interval input should be visible/enterable for all doses except the last one 
  - Can default to 0 for the last dose
- Period input is now age (minimum age to receive the dose)
  - Measured in months, just a number input for now (may move to days/months/years selector at some point)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
