### ISSUE TITLE
Create program_age_ranges

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4655]
Each program needs to specific the different age range milestones that are relevant to the program:

![Screenshot 2024-08-22 at 10 46 06 AM](https://github.com/user-attachments/assets/21fdf513-5d2b-4d01-b491-4c1878aef9ea)

- [ ] New program_age_ranges table
- [ ] Needs to sync via v6 as central data
- [ ] Add age range milestones input to immunisation program edit UI (label and to/from in days/months/years)
- [ ] Prevent overlap in age ranges so they can be ordered sequentially

**Comment by lache-melvin** [comment]
Scope reduction - we will just define a minimum age on individual doses

**Comment by lache-melvin** [comment]
This has been brought back into scope for 2.3

**Comment by lache-melvin** [comment]
Closing again - we can deduce these from the ranges defined against each dose if needed

**Comment by marthakeezy** [comment]
No testing required - moving to Done ✅
