### ISSUE TITLE
Add maximum age to a dose

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4656]
UPDATED: SEE COMMENT BELOW!

When editing a vaccine course, I should be able to assign one or more age ranges to each dose in the vaccine course schedule. ~~The age range options should be the age ranges defined for the program.~~

**Comment by lache-melvin** [comment]
Scope reduction - will just define an age on each dose

**Comment by adamdewey** [comment]
Got to be a bit careful with suggested date - need to factor in minimum
interval between doses too

**Comment by lache-melvin** [comment]
Ok, no more age range drop downs, we'll capture a range against each dose.

- Add `max_age_months` to vaccine_course_dose table
- Capture this in the UI
- UI should allow to enter years and months, rather than just months. But we'll store as months - translate years x12 when going to/from the backend
- The "late" status work will be done in #4805

This is my very rudimentary dev tool mock up of what was discussed, let it be nicer than this 😁 

![Screenshot 2024-09-18 at 9 58 36 AM](https://github.com/user-attachments/assets/6d63554a-7b5e-4c9b-9f1b-1dddbdaab7b4)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
