### ISSUE TITLE
Persist/soft delete vaccine course doses

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4657]
Currently, every time a vaccine course is edited, each vaccine_course_dose is deleted and recreated.

However, we need to implement soft deletes for vaccine_course_dose, which means the delete all and recreate will no longer suit. Instead, we should receive the current list of vaccine_course_dose from the frontend, and compare that with all the vaccine_course_dose that we have for that vaccine_course.

Any that aren't in the current list should be soft deleted - all others can be upserted. 

It should be noted (in the code) that we are soft-deleting so as not to break references for patients that have already received that dose.

- [ ] Implement soft delete of vaccine_course_dose (for when a user explicitly deletes a dose)
- [ ] Upsert remaining vaccine_course_doses provided by the frontend

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
