### ISSUE TITLE
Add Immunisation Schedules tab to Patient view

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4661]
Add a tab under Patient view, for immunisation schedules/vaccines cards (naming?)

List all enrolled immunisation programs.

Clicking a row should take you to the vaccine card view for that program

Like this, but new tab, as `Programs` tab is already used to manage enrolments information:
![Screenshot 2024-08-22 at 5 31 16 PM](https://github.com/user-attachments/assets/f6749a36-bfa7-4ca6-a598-4f9246deb305)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
