### ISSUE TITLE
Vaccination card (read only) UI

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4663]
List all doses for all vaccine courses in the immunisation program. Order by age range, then by suggested date:

Suggested date should be the date patient reaches the age range milestone, or the date once min interval since last dose has past (whichever is later). Suggested date should only be provided for the next dose of each vaccine course. This should be a value calculated on backend and just displayed in UI.

(ignore the progress bar for now)
![Screenshot 2024-08-22 at 5 32 06 PM](https://github.com/user-attachments/assets/3a602ca5-9cf7-477d-8d69-675f5dcc79e8)

(Joining on vaccinations to show the given doses can come later)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
