### ISSUE TITLE
Create vaccinations table

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4675]
During an immunisation program encounter, each vaccination event needs to be captured.

This should be a new table `vaccination`:

id: String
encounter_id: String
user_id: String (user making the entry)
created_datetime: NaiveDateTime (time of entry)
vaccination_date: NaiveDate (user entered date of vaccination)
vaccine_course_schedule_id: String
vaccine_item_id: Option<String>
stock_line_id: Option<String> (item and stock line are optional 
clinician_link_id: Option<String> (healthcare professional administering the dose)
vaccine_given: bool
reason: Option<String> (customisable? REFUSAL/OUT OF STOCK/NO REASON)
comment: Option<String>

TODO: do we think date and clinician can be from the encounter level or needed for each individual vaccination?

Needs to sync via v6 as remote data

stock lines/items etc. references shouldn't break when synced to different sites! So no ref constraints

**Comment by adamdewey** [comment]
> TODO: do we think date and clinician can be from the encounter level or needed for each individual vaccination?

Don't think these can be from encounter as the user may enter historical vaccination events for the patient during an encounter

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
