### ISSUE TITLE
Add translations to user service provider

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4677]
Add all translation files to service provider.

Trait is for testability at the graphql layer
And possibly also extending functionality with plugins

 For our translations, we can just add a structure with methods to provide translations, and we can save that on the service provider.

For testability in future, a common string that won’t change should be fine. Can add testability for future.

Part of epic https://github.com/msupply-foundation/open-msupply/issues/4682

**Comment by marthakeezy** [comment]
Anusha is smashing it in #4899, moving to Done ✅
