### ISSUE TITLE
Add translation files to Tera context

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4678]
Or add service layer functionality to tera context:

https://keats.github.io/tera/docs/#functions

Part of epic https://github.com/msupply-foundation/open-msupply/issues/4682
## Is your feature request related to a problem? Please describe 👀

Add translation files to Tera context

**Comment by marthakeezy** [comment]
Anusha is smashing it in #4899, moving to Done ✅
