### ISSUE TITLE
Change existing reports to use translations

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4679]
## Is your feature request related to a problem? Please describe 👀

Use preferred language and if not use english and if not add fallback in Tera to prevent failed renders.

Only add translations to core reports - don't need to worry about client specific reports at this stage.

Also remove reports.json (this won't be added to weblate).

In stead all of these will be added to common.json with the label of "report.x" rather than "label.x" to differentiate if required.

Part of epic https://github.com/msupply-foundation/open-msupply/issues/4682

**Comment by fergie-nz** [comment]
We also have the future option of adding standard reports into the omSupply repo.

This has not been included in this issue however as needs more discussion

**Comment by marthakeezy** [comment]
Anusha is smashing it in #4899, moving to Done ✅
