### ISSUE TITLE
Make method to make translation in tera easier to read

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4680]
## Is your feature request related to a problem? Please describe 👀

ie: {{ t(app.some_string, “Some String” }}

Part of epic https://github.com/msupply-foundation/open-msupply/issues/4682

**Comment by fergie-nz** [comment]
Closing this as we can make a translation function alias in tera with https://keats.github.io/tera/docs/#functions

**Comment by marthakeezy** [comment]
Anusha is smashing it in #4899, moving to Done ✅
