### ISSUE TITLE
Add feature flag for locales files location

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4681]
## Is your feature request related to a problem? Please describe 👀

Add feature flag to pull translation files from right location depending on if in production or dev environment.

Also good to add testing here for translations to ensure it is working correctly.
These can be static translations which we assume will not change.

Part of epic https://github.com/msupply-foundation/open-msupply/issues/4682

**Comment by fergie-nz** [comment]
Closing as no longer required. Pulling translation files always directly from client side

**Comment by marthakeezy** [comment]
Anusha is smashing it in #4899, moving to Done ✅
