### ISSUE TITLE
Can change the other party (supplier) of automatic supplier returns

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4684]
## What went wrong? 😲

Supplier return created from Inbound shipment - supplier input is enabled and I can change the supplier: 

![Screenshot 2024-08-23 at 6 58 42 PM](https://github.com/user-attachments/assets/45b4e1fc-9c3e-458b-8a96-f6f76a947b16)

## Expected behaviour 🤔

You should be able to change the other party of manual returns, but automatic ones (Supplier Returns created from an Inbound Shipment) should have their supplier fixed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inbound shipment
2. Return some lines
3. You are redirected to new Supplier return
4. BUG: you can edit the supplier

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
V2.3.0 is out so moving to Done ✅
