### ISSUE TITLE
Requisitions: number of shipments sort actually sorts by requisition num

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4685]
## What went wrong? 😲

Clicked the shipments column. They ordered by requisition number?

<img width="821" alt="Screenshot 2024-08-23 at 7 04 47 PM" src="https://github.com/user-attachments/assets/7f8f0981-2a02-4b54-8e92-bec6e82b6643">

## Expected behaviour 🤔

Probably just not a sortable column? OR actually sort by num of created shipments lol

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to requisitions
2. Click on Shipments column to sort by number of shipments
3. Bug: requisitions are sorted by requisition number

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
# 🧪 Testing

- [ ] Go to requisitions
- [ ] Try sort by `Shipments`
- [ ] Shouldn't be able to sort

Tested in V2.4.0-test1, build test passed ✅
