### ISSUE TITLE
Error message when exporting Report to excel

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4686]
## What went wrong? 😲

When exporting the report to excel, an error message pops up on. the app and it crashes, despite having a successful export as per video below:

https://github.com/user-attachments/assets/192b5214-606c-4e25-be3e-39f9429807cd

obs: used dummy data to populate the records.
obs2: Tested with 'local.yarn' = 'Debug' and 'Info'

Found while testing: [#4514 ](https://github.com/msupply-foundation/open-msupply/issues/4514)
## Expected behaviour 🤔

Export works and no error message pops up on desktop app.
The app doesn't crash after export. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Desktop app> Reports'
2. Click on 'Export'
3. See error

## Your environment 🌱

- Open mSupply Version: V2.2.0 Release 
- Legacy mSupply Central Server Version:  V7.16.11

- Platform: Desktop app

**Comment by lache-melvin** [comment]
Closed by #4693

**Comment by regotaina** [comment]
# 🧪 Testing

V2.2.1
browser (Chrome)

Tried to export 'Stock status' report and got this message on browser

![Screenshot 2024-09-18 at 2 32 47 PM](https://github.com/user-attachments/assets/c05220da-5dc6-4daf-92e1-76443a9f599e)

@lache-melvin the report was exported regardless, I could see on my downloads.

**Comment by marthakeezy** [comment]
Tested in `V2.2.01` (Desktop, Central Server) -> exported Stock Status, opened the file, returned to the app afterwards and no issues found! Passed ✅
