### ISSUE TITLE
Add store_ids to existing rnr_form changelogs

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4687]
```
Sadly, we have already gone live with the bug! (#4604) Do we need a migration code to update any existing change_log records to have correct store_id set? I've got a live data set where changelogs for the rnr_forms don't have the store_id set.
```

_Originally posted by @Chris-Petty in https://github.com/msupply-foundation/open-msupply/issues/4611#issuecomment-2309091952_
            
Add a patch migration to update changelogs for `rnr_form` and `rnr_form_line` tables to have a store_id.

Only really needs to run on central server, but I think no harm in it running on all sites whenever they upgrade.

**Comment by lache-melvin** [comment]
Closed by #4689

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.2.02-RC1`


There is a test in the migrations

- [ ] Install 2.2 RC5 and create at least one R&R form, OR against main, create an R&R form and then edit DB to delete store_id from the changelog entries
- [ ] Switch to this branch, run the migrations
- [ ] Check DB - you should now have store_id in the changelogs
- [ ] Reinitialise remote site that created the R&R form
- [ ] R&R forms come back

**Comment by lache-melvin** [comment]
Hi @AnushaUp, updated test instructions for this one here:

- [ ] Install 2.2-RC5 on for OMS Central Server and OMS Remote site
- [ ] Create an R&R form on the remote site & sync
- [ ] Reinitialise remote site - R&R form will disappear
- [ ] Upgrade OMS Central server to 2.2.1 (or 2.2.2 RC 😁)
- [ ] Reinitialise remote site again
- [ ] R&R form comes back

Hope this helps!
