### ISSUE TITLE
Accept gzip in sync

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4694]
We decided this is very low risk and high impact especially in current deployment in a low internet bandwidth context

## Is your feature request related to a problem? Please describe 👀

While researching connection issues with sync, summarise here: https://github.com/msupply-foundation/open-msupply/issues/4658#issuecomment-2309107827, found that we are not setting accept gzip header (as per doc below, validated with my benchmark, I didn't actually check traffic though) 

https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.gzip

## Describe the solution you'd like 🎁

Add gzip feature, this should speed up sync in low bandwidth country.

**Comment by lache-melvin** [comment]
Closed by #4695
