### ISSUE TITLE
Standard report sorting

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4702]
## Is your feature request related to a problem? Please describe 👀

Add report arguments for column sorting in standard reports, `expiring-items`, `stock-status`, `stock-details`, `item-usage`. Will require this PR as pre-requisite https://github.com/msupply-foundation/open-msupply/issues/4701

**Comment by roxy-dao** [comment]
Do in JS

**Comment by fergie-nz** [comment]
I notice there is an unused variable `PrintReportSort` which takes a param from generate report queries and adds this to database queries rather than sorting with wasm functions.

I just wanted to clarify do we want to use wasm functions for sorting? Or add in this variable?

**Comment by fergie-nz** [comment]
> I notice there is an unused variable `PrintReportSort` which takes a param from generate report queries and adds this to database queries rather than sorting with wasm functions.
> 
> I just wanted to clarify do we want to use wasm functions for sorting? Or add in this variable?

You can see this in reports/src/print.rs line 182 where a None is passed through rather than the optional sort

**Comment by andreievg** [comment]
As per our convo yesterday `PrintReportSort` is used by graphql queries, it's kind of hard coded for print to respect the sorting done with front end for stocktakes, invoices and requisitions. 

It would be a bit harder to try and pass one the input of json form sort as PrintReportSort (to be later used by convert_data method).

My conclusion is we keep PrintReportSort and add new sort through filter arguments for now
