### ISSUE TITLE
Administer dose modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4710]
From encounter view of vaccine card, clicking the row should open a modal like this:

![Screenshot 2024-08-30 at 10 59 15 AM](https://github.com/user-attachments/assets/bc60fa52-97c0-42aa-a245-2ccae7982e7a)

Should be able to select one of the vaccine items configured for the related vaccine course.

Batch (`Lot`) opens another modal - separate issue

**Comment by adamdewey** [comment]
Hey @lache-melvin and @mariyamsupply - I'm thinking that it doesn't make much sense to choose the item and batch until after the user has selected 'vaccine given' so perhaps those options should be at the top of the page before the item and batch dropdowns?

**Comment by adamdewey** [comment]
Or, rather, it should be:

- Facility
- Health professional 
- Vaccine given or not
- Item
- Batch

**Comment by mariyamsupply** [comment]
<img width="1024" alt="Modal 111" src="https://github.com/user-attachments/assets/439ca3b3-8257-4b36-bbad-4bc9fe4ca01d">
<img width="1024" alt="Modal 222" src="https://github.com/user-attachments/assets/a29b282f-cb27-4751-aabd-14e71ffffedc">

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
