### ISSUE TITLE
Select batch to administer

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4711]
When administering vaccination, clicking the batch (Lot) button:

![Screenshot 2024-08-30 at 11 56 42 AM](https://github.com/user-attachments/assets/660a278f-b431-4e6c-82e5-7d5654dbf6f8)

opens a new modal, where I can select the batch to issue from:
![Screenshot 2024-08-30 at 11 56 27 AM](https://github.com/user-attachments/assets/778893e5-5f17-42c8-9f8d-90884fbc875e)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
