### ISSUE TITLE
Prevent dose skipping

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4713]
In the encounter view of the vaccine card, lines should be disabled while:

- Previous dose in that course has not been administered
- ~~Minimum interval has been passed~~

i.e. only enable row click if the previous dose status is `Given`

Minimum interval informs suggested date (maybe we put a warning in the modal if you open it before the suggested date?) but we shouldn't _prevent_ this dose from being administered, we'll leave that to the clinician's discretion

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
