### ISSUE TITLE
Edit vaccinations

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4714]
Implement edit of vaccinations

If batch or item changes, we will need to create a Inventory Addition to reverse the Prescription, and create a new Prescription.

If change from given to not given, need to create the Inventory Addition to reverse the Prescription.

If change from not given to given, create the prescription like in create vaccination

**Comment by lache-melvin** [comment]
- Inventory adjustment name_link should be to the patient, so we can see their reversed prescriptions
- If changed to given later (i.e. vaccination date is now in the past) we don't need to create a historical transaction
  - show message in UI - explaining why batch/dose picker aren't available... or maybe a toggle?

We need to keep consistency in that all sequential doses are given. So:
- You can only mark the most recent dose as not_given
  - OR all subsequent doses also need to be not_given (i.e. you've given 3 doses: you can mark dose 3 as not_given, then dose 2, then dose 1... if you needed to for some reason)
- You can only set a vaccination to given if the previous dose(s) are also given
- You can only delete the most recent vaccination (this is a seperate issue though)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
