### ISSUE TITLE
Program enrolment date not populated in edit modal

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4721]
## What went wrong? 😲

Enrolment date doesn't populate when editing the enrolment form:

![Screenshot 2024-09-02 at 10 44 07 AM](https://github.com/user-attachments/assets/4d5efdbe-e745-4d30-b5c3-d7f448f511c7)

## Expected behaviour 🤔

Enrolment date is set, so it should display

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a patient
2. Enrol them in a program
3. Re open the enrolment modal - date field is blank again

## Your environment 🌱

- Open mSupply Version: v2.2.01
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Setting as normal - it really should be displayed, but at least the system is capturing the data, leaving for weekly triage

**Comment by andreievg** [comment]
Since this looks like a very small change, thought to just assign to Piwakawaka for this release

**Comment by marthakeezy** [comment]
V2.3.0 is out so moving to Done ✅
