### ISSUE TITLE
Add Reference to R&R

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4726]
## Is your feature request related to a problem? Please describe 👀
Request from client to have a reference on the R&R detail view, such as the one on internal orders:

![image](https://github.com/user-attachments/assets/f100c81f-87ad-4d2f-8508-420d8da6889e)

This would typically go into the toolbar area. We've had space issues using the forms on tablets though, so I would add to the RH more info panel.

which means creating a more info panel. You could implement #4727 first 😉 

When creating the internal order from the R&R, copy the reference over.

## Describe the solution you'd like 🎁
Add the reference field and pass it through to the internal order.

### Moneyworks Jobcode 🧰

`DFAT:TDEV`

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.3.01-RC1`


- [ ] Create/open R&R form
- [ ] Open side panel
- [ ] Add comment & reference
- [ ] Close/open the side panel / refresh - your inputs are persisted
- [ ] Finalise the R&R form
- [ ] You can't edit the fields anymore
- [ ] Reference has been applied to the generated Internal Order
