### ISSUE TITLE
Add more info panel to R&R Detail page

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4727]
## Is your feature request related to a problem? Please describe 👀

when creating #4726 I realised that we didn't add the detail panel to the R&R form. we had discussed adding the program and period details to the page, and this would be a good place to add this additional info. If not too much effort, it would also be good to have a comment available for the R&R form.

## Describe the solution you'd like 🎁
Create the more info / detail / right hand panel. 
Add into it
* Comment
* Period (read only)
* Program name (read only)

### Moneyworks Jobcode 🧰

`DFAT:TDEV`

**Comment by andreievg** [comment]
Grouping RnR work together at some point, not setting priority yet as RnR label should make this easy to find when we decide it's time for RnR

**Comment by lache-melvin** [comment]
Closed by #5140

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Create an R&R form
- [ ] See More button in top right **-PASS-**
- [ ] Clicking it opens the more detail panel - info is correct
    - [ ] Comment **-PASS-**
      - [ ] Empty on creation **-PASS-**
      - [ ] Comment stays on closing/opening **-PASS-**
    - [ ] Period (read only)  **-PASS-**
    - [ ] Program name (read only) **-PASS-**
- [ ]  Copy to clipboard works **-PASS-**
 - [ ] Data is correct **-PASS-**
