### ISSUE TITLE
Sync out vaccine_course/vaccine_course_dose

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4729]
## Is your feature request related to a problem? Please describe 👀

These tables were added on central server but now need to be available on remote sites

## Describe the solution you'd like 🎁

add to v6 sync as central data

### Moneyworks Jobcode 🧰

[DJIGVCDV]

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
