### ISSUE TITLE
View Vaccination details

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4737]
When viewing a patient's vaccine card, clicking a line that has been administered should open the modal, with the vaccination details populated:

![Screenshot 2024-09-04 at 5 40 29 PM](https://github.com/user-attachments/assets/14d94140-5d39-4873-be71-c2edb8700832)

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
