### ISSUE TITLE
Error when I run the expiring items report with no parameters

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#4741]
## What went wrong? 😲

If I run the expiring item report without entering in any parameters: 
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/05ad61c5-308c-43de-8405-13dc6f1d80d2">

 I then get this error: 
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/08763dc5-cddf-4c30-998b-05931d5ac96b">

## Expected behaviour 🤔
I would like....no error 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports > Expiring Item 
2. Click on OK in the modal that comes up, without editing anything 
3. See error

## Your environment 🌱

- Open mSupply Version: 2.2.01
- Browser, demo-open.msupply.org

**Comment by mark-prins** [comment]
fixed - the report definition needs to be copied manually and I'd screwed that up when setting up the demo server report
