### ISSUE TITLE
Returns: error when creating

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4747]
## What went wrong? 😲

I tried to create an inbound or outbound return on the demo server and it gives two error toasts and a notification that permission is denied

<img width="722" alt="Screenshot 2024-09-05 at 12 36 29 PM" src="https://github.com/user-attachments/assets/a1488d30-a0ab-4498-8a53-de6add0e4757">

<img width="691" alt="Screenshot 2024-09-05 at 12 36 40 PM" src="https://github.com/user-attachments/assets/5616d082-fbab-4faa-9288-e22800654181">

## Expected behaviour 🤔
Should just say that permission is denied.

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Ensure that you don't have permission for returns, then:

1. Go to inbound (or outbound) returns
2. Click on create, select a facility
3. See error

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Setting to normal - not friendly to look at, but at least we do get the permission denied 🤷‍♀️ 

Whoever looks into this should find out what's going wrong that it's reading __typename of undefined, are there other error scenarios that return an undefined that could trigger the same error? 

But thinking it's another case of this one? #4191

**Comment by roxy-dao** [comment]
I'm not seeing this in latest dev... 👀

**Comment by mark-prins** [comment]
yep - working for me in develop 🙏  @roxy-dao
