### ISSUE TITLE
GAPS: Register new asset by scanning 2D DataMatrix

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4757]
## Is your feature request related to a problem? Please describe 👀
Note: we've been asked to implement a standard format for the DataMatrix - but the standard doesn't exist yet. To meet the requirement, we'll define the standard and implement against that. Code changes later as a result of standard (re)definition will be costed additionally.

Description: to look up an individual asset scanning a QR code

1. Navigation: Asset Register: List View > Scan QR Code button
   Navigation: CCE Inventory: List View > Scan QR Code button
2. User clicks on the Scan QR code button
3. For mobile device: system opens the camera 
4. If a matching record is found in the registry, user is redirected to the Asset Register: Detailed View of the asset / CCE Inventory: Detailed View of the CCE
5. If no matching record is found, the user should be re-directed to the asset creation form, any fields available from the 2D scan should be pre-populated in the form, to minimise the work required entering the data.

**User Story A.7.2**

| As a… | Health Care Worker (HCW) or warehouse worker |
|:--- |:--- |
| I want… |  To be able to scan our custom QR barcode that has been attached to the CCE |
| So that… | I can quickly navigate to the CCE’s details in the CCEI register |

**Solution A.7.2**
The system will allow users to scan the unique QR code printed in User Story A.7.1 by using the device’s camera or a dedicated barcode scanning device. 
Once scanned, the system will navigate the user to the detailed view for that particular CCE. 

## Describe the solution you'd like 🎁
* Define a standard for the datamatrix ( delimeters / field identifiers )
* API to lookup items by code
* UI for scanning and redirection

#### 4.1.2 Required barcode 2D Datamatrix information
Information included in the barcode 2D Datamatrix must include the following in the listed order, as defined in the GS1 General Specifications (GS1 code in parentheses):

* Global Trade Item Number (GTIN) containing the allocated company prefix and item reference (i.e. manufacturer and model) using Application Identifier (01)
* Production date using Application Identifier (11) followed by six numerals signifying year and month and day the appliance was produced. As specified in the GS1 General Specifications, if it is not necessary to specify the day, the field must be filled with two zeros (e.g. 11170300 for March 2017)
* The unique serial number for the individual appliance using Application Identifier (21)
* PQS number using Application Identifier (241) followed by seven alphanumeric characters (e.g. 241E003001 for the PQS product number 001 in PQS category E003). The AI (241) identifies a customer part number per the GS1 General Specifications. 
 
The following should be added as far as possible bearing in mind the 2335 alphanumeric characters limitation of 2D Datamatrix codes and should follow the PQS product sheet descriptions and abbreviations.
* Title (Type)
* Energy source
* Vaccine storage capacity (litre) plus 5
* Vaccine storage capacity (litre) minus 15
* External dimensions cm (WxDxH)
* Waterpack storage capacity (Kg)
* Waterpack freezing capacity per 24h (Kg)
* Energy consumption (stable running, continuous power) KWh/24 h
* Energy consumption during freezing (KWh/24 h)
* Hold over time (hours)
* Climate zone
* Freeze protection (Y/N)
* Refrigerant type
* Temp monitoring device included (Y/N)
* Voltage stabilizer included (Y/N)
* Warranty period (start-end date)

Further links to:
* PQS Specification sheet
* Manufacturer’s Operating Manual
* Manufacturer’s Warranty
* Manufacturer’s Maintenance Instructions

**Comment by adamdewey** [comment]
So UNICEF actually gave us a document that they wanted us to use to base the standard on (or it was like a quasi standard anyway) 

See here: https://drive.google.com/drive/folders/1qTEG8hofvf0gLO8pdXbadVT0RN1HtNdO

**Comment by mark-prins** [comment]
thanks! I'm unsure how to parse the additional fields (in red) which have been added. the others have delimiters specified but not those ones. It gives us something to work with though

**Comment by adamdewey** [comment]
Hmm yes, it's a bit vague eh!

But I guess we can sort of try to define it ourselves inside those constraints hopefully. 

They do say this: "The following should be added as far as possible bearing in mind the 2335 alphanumeric
characters limitation of 2D Datamatrix codes and should follow the PQS product sheet
descriptions and abbreviations."

And these are the PQS product sheets they're referring to: https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/categorypage.aspx?id_cat=17

**Comment by jmbrunskill** [comment]
GS1: Kick start...

GS1 defined a number of attributes which are represented by numbers, often represented with brackets.
https://github.com/gs1/gs1-syntax-dictionary/blob/2024-06-10/gs1-syntax-dictionary.txt

So for example a string like `(01)09526000134367`

The (01) means the next string is the GTIN for the product (this has information in itself including product & manufacturer information, but is not human readable)

From what I can gather about GS1 Barcodes 2D Matrix barcodes, they are different to QR Codes and can't be scanned with the default QR Code reader on my phone.

The GS1 Standard allows for 2 formats for 2D barcode.
https://www.gs1.org/standards/barcodes/2d

1. Is the 2d Data Matrix (which seems to be what we need to do here)
This contains a string with the gs1 code elements defined between brackets `(01)SOMETHING`
2. Is a QR Code with a URL in it that defined both a URL and parsable data.
https://www.gs1.org/standards/gs1-digital-link

In the future I can imagine we might need to support both formats but for now we need to focus on 2d Datamatrix

This tool lets you see what the different formats look like with different data
https://gs1.github.io/2d-barcode-generator/


GS1 has defined formats for user defined data (or mutually agreed by users)

Proposed Spec/Format:

The barcode should start with the standard fields defined in GS1 & as suggested by the proposed asset identification document shared by adam

`(01){GTIN}(11){MANUFACTURE_DATE}(21){SERIAL_NUMBER}(241){PQS_PRODUCT_NUMBER}`

Note: GS1 Dates are in format `YYMMDD` (Just 2 digits for Year)

If included external dimensions should coded according to the existing GS1 Standard, using Meters:
Length https://ref.gs1.org/ai/3110
Width https://ref.gs1.org/ai/3120
Depth https://ref.gs1.org/ai/3130

> Note pretty specific how these field are encoded ad 3111 means the last digit of the int is a single decimal place in the representation

For the manufacturer's Model Number or Title Identifier we should use
[8013](https://ref.gs1.org/ai/8013)


We'll then use the `GS1 AI 90 : Information mutually agreed between trading partners` field to defined the version of this standard https://ref.gs1.org/ai/90

Field 90 should contain, the a 3 character version number followed by a `:` character then manufacturer's Name or Code for the device
SPEC_VERSION would be incremented to represent and changes to how we should interpret the `9*` fields in future.
```
const SPEC_VERSION = PQS001
```
Example:
`(90)PQS001`


The next 9 fields are for internal company data, so we can use these to define the rest of our standard.

<google-sheets-html-origin><style type="text/css"></style>
Field Number | Description | Datatype | Format
-- | -- | -- | --
90 | Spec Version | String | 001
91 | Refrigerant Type | String |  
92 | Storage Capacity | JSON | {"5c":CAPCITY_+5C_IN_LITRES, "-20c": CAPACITY_-20C_IN_LITRES, "-70c": CAPACITY_-70C_IN_LITRES}
93 | Warranty Period | String | YYMMDD-YYMMDD
94 | Reference URLs | JSON | {"url description":"url"}
95 | Energy | JSON | {"source":ENERGY_SOURCE, "stable":ENERGY_CONSUMPTION_STABLE_KWH_PER_24H, "freezing":ENERGY_CONSUMPTION_FREEZING_KWH_PER_24H}
96 | Hold Over Time | String | Time in hours as String
97 | Water Pack Capacity | String | {"storage":WATER_PACK_CAPCITY_KG, "freezing":WATER_PACK_FREEZING CAPCITY_KG_PER_24H"}
98 | Other Properties | JSON | {"f":FREEZE_PROTECTION, "cz": CLIMATE_ZONE, "tm": TEMPERATURE_MONITORING, "vs": VOLTAGE_STABILIZER"}





Possible Libraries
https://github.com/datalog/datamatrix-svg
https://github.com/zingl/2D-Barcode

**Comment by mark-prins** [comment]
There is a lot of data to fit in! Given the constraints, the use of JSON seems sensible to me.
Can't comment on the priority of elements - the request was to have all of them, so what you have is a great starting point

**Comment by lache-melvin** [comment]
Yeah agree! Thanks for this research James, this looks like a good approach to me 🙏

**Comment by adamdewey** [comment]
Thanks @jmbrunskill ! 

So UNICEF were saying they wanted to put most of the data in the WHO PQS catalogue into the 2D DataMatrix eventually. 

It does seem like a lot of info though, and I'd be surprised if that were possible. 

However, from a quick google it seems that 2D DataMatrixes support up to 2,335 alphanumeric characters, which would be ~ 4 x the total table that you have above I think?

**Comment by jmbrunskill** [comment]
> However, from a quick google it seems that 2D DataMatrixes support up to 2,335 alphanumeric characters, which would be ~ 4 x the total table that you have above I think?

Seems about right

**Comment by andreievg** [comment]
I thought that extra GS1 field are specifically for the varying properties of a products, like batch specific information (not fixed properties of a product), wouldn't there be a list of products (with GTINS) and their fixed properties, and only things like warranty date, batch, serial etc.. would be coded as extra GS1 fields

**Comment by jmbrunskill** [comment]
> I thought that extra GS1 field are specifically for the varying properties of a products, like batch specific information (not fixed properties of a product), wouldn't there be a list of products (with GTINS) and their fixed properties, and only things like warranty date, batch, serial etc.. would be coded as extra GS1 fields

Makes sense to me... This is what we were asked for, but agree it's not normal.
Maybe should just to the variable fields and then that's good enough for now? I think they're hoping that if there's a new product not in the catalogue, we could get a lot of data prepopulated from the barcode, but I think there's too much data for that to really work.

**Comment by adamdewey** [comment]
I agree - I think we should definitely capture the variable data for starters, and a reference to the WHO PQS catalogue so we can draw in static data from there. 

And then we can discuss with UNICEF about perhaps trying to include the static information later if they really insist

**Comment by andreievg** [comment]
> And then we can discuss with UNICEF about perhaps trying to include the static information later if they really insist

Hmm, should we help UNICEF in trying to understand the scope of GS1 barcodes ? Maybe there is a misunderstanding on their end about how they can/should be used (or on our end)

**Comment by adamdewey** [comment]
> Hmm, should we help UNICEF in trying to understand the scope of GS1 barcodes ? Maybe there is a misunderstanding on their end about how they can/should be used (or on our end)

I think they are wanting to include some of the extra fixed information because they don't trust that all future systems will have that information available to cross reference, and even don't trust that WHO PQS will maintain a good database. 

But I think we can come up with a suggested format for what best makes sense to us and following UNICEF's proposal as close as possible, and then present that to UNICEF as our plan. 

E.g. `(variable_data1)(variable_data2)(variable_data3)...(fixed_data1)(fixed_data2)(fixed_data3)...` 

And then in terms of reading the DataMatrix, we can also do what we think best, e.g. we could disregard the fixed data and use our own reference data instead. Or we could overrule our own reference data with the fixed data 🤷

**Comment by jmbrunskill** [comment]
Ok given we're not sure what the final format is going to be, and Andrei's feedback.
For now, lets just go with all the standard GS1 fields as I described above.

Then for the additional fields, let's just do the warranty period (which I believe is the only variable data portion) and reference urls which should allow the user to find all the other data needed for the asset via the websites (in theory)

Field Number | Description | Datatype | Format |  
-- | -- | -- | -- | --
90 | Spec Version | String | 001 |  
91 | Warranty Period | String | YYMMDD-YYMMDD | StartDate-EndDate
92 | Reference URLs | JSON | {"url description":"url"} | Can be used for "• PQS Specification sheet• Manufacturer’s Operating Manual• Manufacturer’s Warranty• Manufacturer’s Maintenance Instructions
93 |   |   |   |  
94 |   |   |   |  
95 |   |   |   |  
96 |   |   |   |  
97 |   |   |   |  
98 |   |   |   |  
99 |   |   |   |  

We can update and improve this with collaboration with WHO as they update their spec.

**Comment by jmbrunskill** [comment]
`(01)00012345600012(11)241007(21)S12345678(241)E003/002(3121)82(3131)67(3111)63(8013)HBD 116(90)001(91)241007-310101(92){"pqs":"https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/LinkPDF.aspx?UniqueID=3bf9439f-3316-49b4-845e-d50360f8280f&TipoDoc=DataSheet&ID=0"}`

Here's an example which should translate.
The main thing to extract would be the serial number `S12345678` and the Warranty Date: 2024-10-07 -> 2031-01-01

**Comment by jmbrunskill** [comment]
@adamdewey can you clarify the requirements here.

It sounds like we just need to look up an asset already registered in our database using the Serial Number in this Barcode?
Is there anything else we need to do to complete this ?

**Comment by adamdewey** [comment]
@jmbrunskill - sorry, the user story needs updating!

It's emerged that the main requirement is actually to register assets in the first place - so, firstly, checking if there is an asset with that serial number in the system. 

If the serial number doesn't exist then using the PQS identifier in the barcode to create a new asset for that type of PQS with the variable information populated (serial number, warranty etc)

**Comment by jmbrunskill** [comment]
@adamdewey makes sense, seems a bit useless just looking up the serial number....

**Comment by CarlosNZ** [comment]
To break into separate issues, each needs a bit more fleshing out:

- [ ] Parse incoming text stream (not sure if back-end or front-end)
- [ ] Implement search by serial_number
- [ ] Create new asset if no match (probably need a UI confirmation)

**Comment by marthakeezy** [comment]
Tested as a part of Release Testing in #5397, moving to Done ✅
