### ISSUE TITLE
GAPS: Unserviceable status

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4759]
## Is your feature request related to a problem? Please describe 👀
**User Story B.4.3**

| As a… | National EPI manager |
|:--- |:--- |
| I want… |  all facilities to provide me with information about any CCE that are unserviceable (permanently broken) |
| So that… | we request replacements for these in our next CCEOP application |

**Solution B.4.3**
The system will provide a mechanism for facilities to flag any of their CCE as ‘Unserviceable’. 
This flag will be used for identifying ‘Unplanned replacements’ over the next 5 years. 

## Describe the solution you'd like 🎁
Add the 'Unserviceable' status option to asset `StatusType` enum

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-test1`

- [ ] Can change the status of an existing piece of "Equipment" (`/cold-chain/equipment/<itemId>`)
- [ ] Can filter by "Unserviceable" status: `cold-chain/equipment`
