### ISSUE TITLE
Bundle size diff GH action is incorrect

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4761]
## What went wrong? 😲

![Screenshot 2024-09-10 at 8 48 20 AM](https://github.com/user-attachments/assets/a1cdaef4-e33f-4eee-abff-5dfb90493dac)

![Screenshot 2024-09-10 at 8 47 55 AM](https://github.com/user-attachments/assets/6c56ea86-be63-4ca2-9440-2dad0f1f8fa8)

We should update to v4 as recommended

## Expected behaviour 🤔

Actions run fine

## How to Reproduce 🔨

Create a PR that touches the frontend - this action will fail

**Comment by roxy-dao** [comment]
Reopening.. It's not failing per-say, but the comparisons don't seem right

![photo_2024-10-11 10 31 00](https://github.com/user-attachments/assets/5be6c413-1d40-468f-9ee8-e1cc03df367f)
