### ISSUE TITLE
Outbound Shipment: Unit Price incorrect, when multiple lines are grouped

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4765]
## What went wrong? 😲

![image](https://github.com/user-attachments/assets/824d52ee-59eb-4204-a56c-3409b3eaa125)

![image](https://github.com/user-attachments/assets/ebf0bd88-d896-41ec-8e81-34b72ec2316e)

## Expected behaviour 🤔

Unit Price should either say `Multiple` if there is more than one price attached, or should be calculated as an average cost?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create outbound shipment
2. Select stock from two stock lines
3. click Group By Item button
4. Check if the Unit Price is correct

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Setting as normal, seeing as its only a display issue, but it's pretty confusing, and shouldn't be hard to fix. Also, when grouped by item, Pack Qty column shouldn't be 0!

Have left needs triage label, but think we should try to clean these things up for 2.2.2 patch!

**Comment by roxy-dao** [comment]
Dup of #4591 
The pricing uses a number component.. which wouldn't allow for 'multiple' text

**Comment by alainsussol** [comment]
Tested on v2.4.0-test1

# 🧪 Testing



- [ ] Have stock lines with different prices maybe different pack sizes as well (3 lines with 2 with same pack size and same sell price and 1 with a different pack size and a different sell price but which after calculation would be the same unit price
- [ ] Add them to outbound shipment
  - [ ] 3 lines with 2 with same pack size and same sell price and 1 with a different pack size and a different sell price but which after calculation would be the same unit price for the 3 lines
    - [ ] Calculate unit price to see that it matches with sell price per pack/unit per pack (and that the logic is correct lul) **-PASS-**
    - [ ] Pack qty total should be sum of packs **-PASS-** 
    - [ ] Pack size should show multiple **-PASS-** 
  - [ ]  3 lines with 2 with same pack size and same sell price and 1 with a different pack size and a different sell price but which after calculation would be not the same unit price for the 3 lines
    - [ ] Calculate unit price to see that it matches with sell price per pack/unit per pack (and that the logic is correct lul) **-PASS-**
    - [ ] Pack qty total should be sum of packs **-PASS-** 
    - [ ] Pack size should show multiple **-PASS-** 
  - [ ]  3 lines with same pack size and same sell price.
     - [ ] Calculate unit price to see that it matches with sell price per pack/unit per pack (and that the logic is correct lul)  **-PASS-**
     - [ ] Pack qty total should be sum of packs **-PASS-** 
     - [ ] Pack size should show the pack size **-PASS-** 

Not grouped by item
![Image](https://github.com/user-attachments/assets/661cac1f-1d77-4978-b9d3-dfeb0b935d4e)


Group by item
![Image](https://github.com/user-attachments/assets/eed66fd5-ac22-4ee0-98dd-0b965d62719f)
