### ISSUE TITLE
Full screen R&R entry

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4768]
## Is your feature request related to a problem? Please describe 👀
It's been requested to have the edit table able to be viewed / used in a full screen mode to make the most use of the limited screen size available on tablets.

## Describe the solution you'd like 🎁
Here are some mock ups:

![image](https://github.com/user-attachments/assets/a0750dca-ad29-42a9-9cfc-1fdf54c76dfa)

![image](https://github.com/user-attachments/assets/84dea033-ac1d-4cdc-9365-060851dcba8a)

![image](https://github.com/user-attachments/assets/44fc6f1d-08b1-4a93-955d-1e82eef1c5f6)

Additionally, could we have `escape` also close the full screen mode; this is an established pattern.
If doing so, a hint on entering full screen would be good to include, such as this version from chrome:

![Screenshot 2024-09-10 at 1 01 29 PM](https://github.com/user-attachments/assets/6ec75c93-d4a9-4f53-8bee-3a1dbb0edd6f)

We could use an info snackbar to show the 'press esc' message in order to reuse existing functionality.

**Comment by mark-prins** [comment]
will need to experiment a little to see what's possible here: hopefully this would be a quick one to implement.
If you start and find that it's taking a lot of time, then stop and discuss - I don't see this as a high priority

**Comment by lache-melvin** [comment]
Closed by #5163

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.3.1-RC1`


- [ ] Full screen yourself in and out
- [ ] Test the `esc` key binding
- [ ] Try her on android!
- [ ] Generally just try to break it please hehe

**Comment by AnushaUp** [comment]
PASSED✅
