### ISSUE TITLE
name_link_id and item_link_id should not be used outside of repository layer

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4769]
## The suggestion

We shouldn't be used name_link_id and item_link_id outside of repository layer, access to item_id and name_id should be done through a join to name_link and item_link in repo. 

What to do for upserts ? And name_link_id and item_link_id field on 'row' data types ?

**Comment by andreievg** [comment]
Refinement, need to check if this is actually a problem, what are the use case ? 
Defs can't use name_link_id in graphql layer, but maybe still ok in repo ?
Priority goes does, since we had a look in refinement

**Comment by roxy-dao** [comment]
Dupliecate of #2937
