### ISSUE TITLE
Reports: freeze headers

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4771]
## Is your feature request related to a problem? Please describe 👀
when scrolling through the reports, the header is lost:
![telegram-cloud-photo-size-1-5116478464394898908-y](https://github.com/user-attachments/assets/6752a547-5369-49b0-b6cc-bed9c283e3c5)

## Describe the solution you'd like 🎁
If we are continuing to use the iframe and not implement as a standard table - could we add a `position: sticky` to the header row?

**Comment by andreievg** [comment]
Investigate a low effort solution maybe 'sticky' css (make sure print still works ok)

**Comment by andreievg** [comment]
Still usable but would help a lot to have headers visible, especially since we've opened up a way for generated reports to be displayed and used, pm request

**Comment by mark-prins** [comment]
adding this style to the iframe document will sort things out:

```
.container, body, .container > table {
    margin-top: 0;
    padding-top: 0;
}

.container > table > thead {
    position: sticky;
    top: 0px;
    background: white;
    height: 40px;
}

tr.heading > td {
    padding-top: 12px;
}
```

I'm not entirely sold on the drop shadow, but I think the header needs some definition

<img width="1601" alt="Screenshot 2024-09-12 at 3 34 49 PM" src="https://github.com/user-attachments/assets/804122f9-152e-49fc-a133-4539f2dab81e">

**Comment by AnushaUp** [comment]
Tested [HERE](https://github.com/msupply-foundation/open-msupply/issues/5411)
