### ISSUE TITLE
Backlog prescription entry: Backdated stock available stock function

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4774]
## Is your feature request related to a problem? Please describe 👀

To achieve #3672 backdated prescriptions, we need to be able to calculate what stock was available at that time, and adjust for any of that stock that's already been allocated in the future.
 
## Describe the solution you'd like 🎁
The stock availability table should only show batches that were available at the time specified
Available packs should be the amount of stock available for that batch at the time, minus anything allocated from that batch since (until now)

### Additional context 💌

Part of #3672

**Comment by marthakeezy** [comment]
Tested in #4895 - moving to Done ✅
