### ISSUE TITLE
More user friendly header for the report window & better filters please

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#4776]
## Is your feature request related to a problem? Please describe 👀
1. I find this very tech-y: 
<img width="605" alt="image" src="https://github.com/user-attachments/assets/3483a377-f7d4-4d12-9b41-871d317ce0ed">

2. The filters that are irrelevant (AMC Lookback Period:,Target MOS:,Reorder threshold MOS:, Expiring item period:) should be hidden, not just disabled, else the users are confus-ed
3. The date field should default to today, not null
4. The item search field should only do a "starts with" not a contains by default (fancy: support a wildcard to turn it into a "contains"). e.g. if I just want to report on an item "beds" there is no way to exclude "flabbeds" and "sandbeds" (very common requirement y'know!) thanks!

## Describe the solution you'd like 🎁

Have it read "Filter report" or "Report Filters"

**Comment by mark-prins** [comment]
Can you clarify for me please? Is it the intro paragraph which you find techy?
If so - are you suggesting replacing it all with 'Filter report'? I wanted to convey that entering stuff here is optional and also to see the report you have to click ok. I wouldn't want to drop those aspects if the text is changed.

**Comment by DhanyaHerath** [comment]
Ah no sorry @mark-prins I shouldn't have rushed! The "Report arguments" header part only

**Comment by mark-prins** [comment]
Oooh. Right. didn't even notice that!
Looking at it I see that this is hard coded text too, so definitely needs changing!

```
      title="Report arguments"
```

Yes - in that case, totally agree

**Comment by mark-prins** [comment]
Title is updated with https://github.com/msupply-foundation/open-msupply/pull/4807

The read-only inputs would make more sense if the filters were in the RH panel as originally intended. They should be in a separate 'info' section, and I think should remain.

The 'contains' / 'starts with' I think needs to be addressed globally. have raised a new issue for that: 4897
