### ISSUE TITLE
After migration the price on service charges does not show

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4784]
## What went wrong? 😲

Coming from [this comment](https://github.com/msupply-foundation/open-msupply/issues/4394#issuecomment-2340131407)

this 
![image](https://github.com/user-attachments/assets/e6fc8ae9-d9ba-411c-9778-ffd15f05308e)

becomes
![image](https://github.com/user-attachments/assets/054f0eeb-f684-466f-9dcd-1d6fb58bcb15)

Cost and sell price are in the database.. but don't display!

## Expected behaviour 🤔
Should display the price

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a customer invoice, add a service charge with a price value
2. Migrate the store to oms
3. View the outbound shipment

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in OMS `V2.4.3` mSupply `V8.0-dev27`


- [x] Create a customer invoice, add a service charge with a price value
- [x] Migrate the store to oms
- [x] View the outbound shipment

2.
- [x] Create a supplier invoice, add a service charge with a cost price
- [x] Migrate store to OMS
- [x] View inbound shipment

**Comment by AnushaUp** [comment]
PASSED✅
