### ISSUE TITLE
Reports do not run

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4786]
## What went wrong? 😲

Clicking on any report results in this:

![Screenshot 2024-09-13 at 7 03 39 PM](https://github.com/user-attachments/assets/479fcd73-f871-4478-91f0-76365b09ec13)

## Expected behaviour 🤔
No error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports
2. Click on a report

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
fixed with https://github.com/msupply-foundation/open-msupply/pull/4787

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅
