### ISSUE TITLE
Add facility to vaccination

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4796]
## Is your feature request related to a problem? Please describe 👀

I want to know where the vaccination I am recording has occurred. For now, default to this facility, or if desired, switch a free text field. In future, users will be able to select other facilities as well:

## Describe the solution you'd like 🎁

Add facility field to vaccination modal: 

<img width="719" alt="Screenshot 2024-09-16 at 11 48 28 AM" src="https://github.com/user-attachments/assets/d7adf2eb-27a6-4e46-9052-23174729c966">

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
