### ISSUE TITLE
Add vaccination card to encounter

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4797]
## Is your feature request related to a problem? Please describe 👀

Vaccination card (read only mode) exists from the patient view. I want to access the edit view from an encounter.

## Describe the solution you'd like 🎁

Add the vaccination card table to the encounter view, opening the modal on row click

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
