### ISSUE TITLE
Report-versioning: Make standard reports appear by default in open-mSupply

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4799]
## Is your feature request related to a problem? Please describe 👀

Need to include standard reports in OMS installations.

Maybe via bundling? 
Need some discussion and planning for how we bundle and select compatible reports + manage avoiding excess sync traffic where we update local omsupply installations.

Also need standard reports to be compiled as one large json inclusive all variables - and also upsertable via CLI with one file argument.
This makes the solution consumer focussed to support so that they can easily update 

## Describe the solution you'd like 🎁

We create a new Central Server Build for open-mSupply.
This version will register itself in windows as open-mSupply-Central (or similar)

Only the oms Central server install will come with standard reports
These will be synced out to remote sites (assuming they are on a new enough version to check for report updates)

For now ALL report version will go to ALL sites. Each site will select the latest version that's compatible.

Filtering in Sync could be done in future issues?

Bundled reports will be bundled using `rust embed` similar to frontend code.
The bundled reports will be inspected at startup, and inserted into the reports table if new.

### Describe alternatives you've considered 💭

1. Standard Reports are bundled into every OMS version
This has the challenge that because OMS Central has the bundled reports it will still try to sync everywhere anyway.
Not clear how to avoid this problem if we do want to be able to update bundled reports via sync...

2. Standard Reports are locked to OMS version
This greatly simplifies the versioning question at the cost of flexibility.
A new installation would be required to update standard reports.
Versioning is likely to be needed for custom reports anyway, so would probably just as much work...

**Comment by marthakeezy** [comment]
Standard reports appear since V2.3.0, so moving to Done ✅
