### ISSUE TITLE
Historic vaccinations should not create a prescription

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4801]
## Is your feature request related to a problem? Please describe 👀

If a vaccination is being entered for a past date, do not capture item/stock line details, just that the patient has received this dose. Therefore no prescription should be created.

## Describe the solution you'd like 🎁

Design:

<img width="713" alt="Screenshot 2024-09-16 at 2 38 45 PM" src="https://github.com/user-attachments/assets/ea4c5286-df51-4719-b92b-0e41161c0eb4">

### Describe alternatives you've considered 💭

While doing this, would probably be good to handle the case where no items are defined for the vaccine course, and also allow no prescription/no item required in that case!

And hiding the item select for when a different facility is chosen!

**Comment by jmbrunskill** [comment]
@lache-melvin FYI I'm currently working on backdating prescriptions if that helps this situation?
https://github.com/msupply-foundation/open-msupply/issues/3672

**Comment by lache-melvin** [comment]
> FYI I'm currently working on backdating prescriptions if that helps this situation?

Yeah it may at some point - for now though it seems sufficient to be capturing vaccinations just for informational purposes 🙏

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
