### ISSUE TITLE
Create vaccine card status values in backend

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4805]
## Is your feature request related to a problem? Please describe 👀

Currently we are calculating this on frontend, but should be calculated on backend and included in card data to the frontend, as an enum that we can match on and render the correct chip:

Statuses: Given, not given, pending, late.

![Screenshot 2024-09-18 at 8 50 44 AM](https://github.com/user-attachments/assets/56454e94-2c61-4e92-ac25-93a59ca4faa5)

![Screenshot 2024-09-18 at 8 51 41 AM](https://github.com/user-attachments/assets/feab9a3a-8cff-4c49-91f1-04e19a48c4e9)

## Describe the solution you'd like 🎁

- Given: vaccination.given = true
- Not Given: vaccination.given = false
- Pending: No vaccination yet, but the patient is younger than max age for dose
- Late: No vaccination yet, and the patient is older than max age for dose
- Otherwise, no status

**Comment by lache-melvin** [comment]
While doing this, can we also add the red shading to the not-given rows, much like the green on the given rows 🙏

**Comment by lache-melvin** [comment]
Closed by #4881

**Comment by marthakeezy** [comment]
Tested in V2.6.0-build-test-3 - given vaccines are green, not given and overdue are red and pending are blue! Moving to Done ✅
