### ISSUE TITLE
Update login error component

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4808]
## Is your feature request related to a problem? Please describe 👀

The login error message doesn't look good and hides extra detail behind a tooltip, which is hard to use on android.
I realise that this is similar to #2654 and #3815 and #1917 and #1770 and #2945
This issue though is about updating the style of the message only. Those issues are more about the content of the error displayed.

## Describe the solution you'd like 🎁
Can you update the login error style to look like this please:

![telegram-cloud-photo-size-1-5138705203619540305-y](https://github.com/user-attachments/assets/ba63649f-36b5-4f14-bb9b-8fe87f7038fd)

and if there's more details, show them with an expanding panel:

![telegram-cloud-photo-size-1-5140915754567314880-y](https://github.com/user-attachments/assets/1304bb91-cd11-496b-a2cf-7d02b826ca48)

![telegram-cloud-photo-size-1-5140915754567314881-y](https://github.com/user-attachments/assets/b4180c08-8a57-4392-bf09-3f30eb350900)

**Comment by andreievg** [comment]
Triage, should be reasonably easy and quite satisfying (for users and devs alike), there is another design being uploaded (showing the link for error msgs)

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Prompt some kind of error in login page (by disconnecting server or entering wrong password 3 times)
- [ ] See new error component
- [ ] Click `More information`

**Comment by alainsussol** [comment]
@jmbrunskill 
Hi James,

I assume that the new style is only on the login screen and not on the initialising screen yet.
![Image](https://github.com/user-attachments/assets/ee19c716-bddb-4b96-ae55-78a6791bd456)

**Comment by roxy-dao** [comment]
> @jmbrunskill Hi James,
> 
> I assume that the new style is only on the login screen and not on the initialising screen yet. 

Hi Alain!

Yup this new error component is only for the login page
