### ISSUE TITLE
R&R Forms changes

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4810]
## Is your feature request related to a problem? Please describe 👀

Some requests from the client re the R&R forms.

## Describe the solution you'd like 🎁
I don't want the very specific column name requests to be applied to all users, would it be possible to find a solution which makes the column names customisable in some way? 
Similarly, I'm not certain that all users would require the additional columns. Could these be bespoke?

### Rename columns
* Consumed should be changed to Consumed/Distributed
* Adjusted Consumption should be changed to Adjusted
* AMC (Average Monthly Consumption) should be changed to AMC/AMD (Average Monthly Distribution).

### New columns ( proposed )
* LOSSES Column: Introduce a column for LOSSES, representing quantities removed from the warehouse/system due to issues like expiration, breakage, or damage. This column should be placed before the Adjustment column
* Minimum Quantity Column: Add a Minimum Quantity column positioned just before the Maximum Quantity column. The formula for Minimum Quantity is: Minimum Quantity=AMC/AMD x Minimum Stock Level
* Adjustment Definition: Ensure the definition of adjustments is clearly highlighted to ensure consistent understanding among users.

### System enhancements
- [ ] #5062

**Comment by mark-prins** [comment]
If #4060 is done - perhaps we can use a server-delivered custom namespace which has the override column name translations?

**Comment by jmbrunskill** [comment]
Custom translations Issue - #5061

**Comment by lache-melvin** [comment]
Capturing some Telegram decisions here:

- Adding a `losses` column, but leaving the `adjustments +/-` column (i.e. not separating to something like `additions`)
- Don't need to calculate a value for this field, just set as 0 (also 0 for historical forms)

**Comment by lache-melvin** [comment]
Closed by #5180

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.3.1-rc1`


- [ ] Migrate with existing R&R forms - this is fine
- [ ] Minimum and maximum quantities accurately reflect AMC * min mos/max mos store preferences
- [ ] Losses are included correctly in the final balance

**Comment by AnushaUp** [comment]
@lache-melvin here the value of Maximum and Minimum seems like 1 is added in each one for eg here for minimum 113*3 = 339 but here 340 is shown and same for the maximum 
![Screenshot 2024-10-24 at 3 07 36 pm](https://github.com/user-attachments/assets/3fe01bee-58fa-4d26-8d1c-b961d218cb94)

**Comment by lache-melvin** [comment]
@AnushaUp I am wondering if you hover/press on those fields so the tooltips show, are they actually decimals that are getting rounded? e.g. 113.2 * 3 = 339.6, which would get rounded to 340 👀

**Comment by AnushaUp** [comment]
@lache-melvin Make sense. Thanks! I was a little confused with the first point. Migration from oms?

**Comment by lache-melvin** [comment]
> Migration from oms?

Ah sorry great question! I meant upgrade - have some R&R forms in 2.3.0, upgrade to 2.3.1, no errors

**Comment by marthakeezy** [comment]
Gave this a test, migration look good and don't seem to affect R&R forms. Logged a few bugs (#5274, #5279), otherwise looks good. Moving to Done ✅
