### ISSUE TITLE
Add from master list string missing

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4811]
## What went wrong? 😲

On my develop branch i seem to get the following, when adding internal order from master list (same on demo server)

![Screenshot 2024-09-18 at 12 47 41 PM](https://github.com/user-attachments/assets/c8f3a572-b53d-4210-a545-b38d307f8426)

Hmm how did it sneak through testing ?
Also how did we make this code change without noticing/testing and how to we avoid this in the future ?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
the string `messages.confirm-add-from-master-list` is in the `distibution.json`
but this one is using `replenishment.json`

I'd suggest moving to `common` and updating the usages

**Comment by andreievg** [comment]
Would be great to fix this up in the next path release, the impact of this is not that severe but since we have a release coming up and it's a small change, would be great to get it in

**Comment by lache-melvin** [comment]
Closed by #4821

**Comment by AnushaUp** [comment]
# 🧪 Testing



- [ ] You can check this by going to internal orders and adding from master list
