### ISSUE TITLE
'Encounter missed' warning doesn't disappear until refresh

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4819]
## What went wrong? 😲

I mark the encounter as visited, but it still says `Encounter missed`, until I refresh:

https://github.com/user-attachments/assets/64301de6-f8ab-4385-9cec-f17fb83b433a

## Expected behaviour 🤔

Once the encounter is marked as visited, the warning goes away

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an encounter for date in the past
2. See the `Encounter Missed` warning
3. Mark as visited
4. It is still there, until you refresh the page

## Your environment 🌱

- Open mSupply Version: v2.2.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
Passed in `V2.6.0-build-test-3`! ✅
