### ISSUE TITLE
Discounted prices should be applied when distributing to facilities

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4825]
## What went wrong? 😲

When dispensing to patients, the discounts are removed correctly. However, the discount is also being removed when distributing to other facilities (creating Outbound Shipment)

## Expected behaviour 🤔

Discounts should continue to be applied to eligible products when distributing to another facility.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Distribute an eligible item to a customer store from an OMS dispensary store
2. See price - it is the full price instead of discounted

## Your environment 🌱

- Open mSupply Version: v2.2.2-RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `mSupplyV7-17-08` and `omsV2.2.02 RC4`


- [ ] Setup for discount lists in mSupply
- [ ] Edit at least one other masterlist to sync to open-mSupply
- [ ] Check that the discount is still applied even though there's masterlists with 0.0% discount now

**Comment by Chris-Petty** [comment]
Fixed in 2.2.2

**Comment by fergie-nz** [comment]
closed in 2.2.2 🎸

**Comment by roxy-dao** [comment]
Closed in #4829

**Comment by Chris-Petty** [comment]
Completed in 2024
