### ISSUE TITLE
Cold chain equipment module 'store' to show store name too instead of only store code

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4826]
## What went wrong? 😲
![IMAGE 2024-09-20 12:49:50](https://github.com/user-attachments/assets/50daff93-6930-41b8-a0ff-b2054d32bc57)

On the Cold chain Equipment module - when you add a new CCE, the header "store" only shows store code which can be difficult for user to know who to assign asset to.

Suggestion of having both:

![Screenshot 2024-09-20 at 12 36 01 PM](https://github.com/user-attachments/assets/44950800-4628-48a5-89f7-0fc9468e4e0f)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
Hi team, the window is not wide enough to show the full name of the stores - see an example [here](https://drive.google.com/drive/folders/1x3PBB7nuL8cKtXFXzc5W90vsEcGFn-Gv)

Tested in V2.4.0-test1, in Desktop Browser (Google)

**Comment by roxy-dao** [comment]
This is true for all searches that have long names.. as seen below
![Screenshot 2024-11-05 at 12 30 27 PM](https://github.com/user-attachments/assets/dae6f81e-f187-4270-ba4a-586197e3547b)

Please create a separate issue to consolidate this. Closing this one since the store name does show
