### ISSUE TITLE
Add age label to dose

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4831]
## Is your feature request related to a problem? Please describe 👀
Now that we don't have periods, the label which groups vaccine doses is not configurable by the user.
We'd like the ability to change the words shown in column one here:

![image](https://github.com/user-attachments/assets/7400559b-b5ac-47d7-91a4-4c5522841384)

e.g. `Naissance` rather than `0 months`

## Describe the solution you'd like 🎁
When editing a dose, add a text input where you can enter a label.
So the dose edit would have
* label (for the dose)
* start age (in months)
* end age (in months)
* age label
* minimum interval

I'm wondering about the feasibility of using an autocomplete with chips, like this:

![image](https://github.com/user-attachments/assets/1231a9b0-66e0-4c55-8a71-7d0103fb16f1)

where the input is limited to a single entry being selected - or a free text.
Behaving in the same way that the tag input behaves in OG. 
This would allow for existing labels to have a consistent spelling, and for the entry of new labels.

### Describe alternatives you've considered 💭
We currently generate the label based on the age. Would prefer to have them customisable.

**Comment by lache-melvin** [comment]
![Image](https://github.com/user-attachments/assets/bc9a6b21-13f2-4b7c-8453-daa55f705d52)

If no age label, fix the default age label to show in years and months

**Comment by lache-melvin** [comment]
Closed by #4961

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅
