### ISSUE TITLE
Autoselect single batch

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4832]
## Is your feature request related to a problem? Please describe 👀
If there is only a single batch available, can we select it by default please

## Describe the solution you'd like 🎁
If there is only one batch, no need to have the batch selection modal or the onclick. simply select that batch.

**Comment by lache-melvin** [comment]
Can this issue also please include:

 - Separate batch select modal -> dropdown in the same modal
 - Some kind of warning message if there are no available batches, but still allow the user to save the vaccination

**Comment by lache-melvin** [comment]
Some kind of check for this too?

https://github.com/msupply-foundation/open-msupply/pull/4845#pullrequestreview-2326545686

**Comment by lache-melvin** [comment]
Closed by #4905

**Comment by marthakeezy** [comment]
Hi team - @lache-melvin & @mark-prins 

Was just testing this one and noticed that if a vaccination is saved when no batch is selected, the user cannot see which item was given in a vaccination when clicking on the field again? Seems a bit odd... Wondering if it's a bug

https://github.com/user-attachments/assets/2efde359-d83f-48c2-92a5-b358ab52d37d

**Comment by lache-melvin** [comment]
Hi @marthakeezy yep this is currently expected, if no batch is selected the we aren't recording anything about the stock that was administered.

Agree it's a bit strange though, to select and item, reopen and its cleared. Could raise a request 👀

**Comment by mark-prins** [comment]
I'm ok with current behaviour - agree there's a bit of weird, but I think it's ok - thanks!

**Comment by marthakeezy** [comment]
Nice, thanks for the confirmation! All passed then - moving to Done ✅
