### ISSUE TITLE
Group vaccine card rows by age

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4834]
## Is your feature request related to a problem? Please describe 👀

Currently the age shows on every row in the card, rather that just once (so as to group all the rows by age) - it should look like this:

![image](https://github.com/user-attachments/assets/f553c3f0-adaf-4d5d-9fa1-698096ea816b)

## Describe the solution you'd like 🎁

The merging cells might be harder given our current styling, but this would be a good start:

![image](https://github.com/user-attachments/assets/6ec8021d-ed35-4a5a-bdb4-3c78a002285f)

**Comment by adamdewey** [comment]
Wondering what it would look like without the green background, and instead grouping the ages by alternating colours (e.g. white / light grey) ?

**Comment by adamdewey** [comment]
That's just if there's no solution possible for merging the cells in the age column

**Comment by CarlosNZ** [comment]
> That's just if there's no solution possible for merging the cells in the age column (as it's a bit hard to intuitively understand at the moment)

I think we have a way (in theory anyway) :)

**Comment by lache-melvin** [comment]
Closed by #4906

**Comment by marthakeezy** [comment]
hey @AnushaUp i just gave this a quick test since i was in the area :)

works in `V2.6.1-RC1`, moving to done ✅
