### ISSUE TITLE
Add batch and facility to vaccine card

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4835]
## Is your feature request related to a problem? Please describe 👀

Per designs, we should have these two additional columns, batch (french: Lot) and facility, for lines where there has been a vaccination event:

![image](https://github.com/user-attachments/assets/51502289-b3d9-452b-85cd-bd2c0a557900)

## Describe the solution you'd like 🎁

add the extra two columns to the vaccination_card view, and bring through to the frontend

**Comment by marthakeezy** [comment]
Tested by Tainá in #4642 - moving to Done ✅
