### ISSUE TITLE
Add sql and graphql query passing in upsert of standard reports

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4843]
Could also include all standard reports to OMS repo in this PR, as will be useful for testing.

We need BuildArgs passed in upserting standard reports to be flexible to all types of standard reports. Most can just have graphql query names standardised, but we will also need to read all sql queries and create a vec which can be passed with build args for some reports (see item-usage for example).

Part of epic #4800

**Comment by fergie-nz** [comment]
Easiest way to do this is as @andreievg initially suggested with query files listed in manifest.json!

**Comment by fergie-nz** [comment]
Closing as adding manifest file structure in #4842

**Comment by marthakeezy** [comment]
No testing needed, moving to Done ✅
