### ISSUE TITLE
User friendly errors for trying to give/"un-give" doses in the wrong order

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4852]
## What went wrong? 😲

The user can access the edit modal after a vaccination has been given. Let's say we have given 3 doses. Then I go to dose 1 and try to change to not given. 

The system does not allow this (they should change dose 3 to not given - and adjust other vaccination dates if needed - because they user is actually trying to say that the patient has only received 2 doses).

However, seeing as this is a valid error the user can cause, this should be a structured error, with a translatable error message, rather than this:

![Screenshot 2024-09-24 at 3 27 34 PM](https://github.com/user-attachments/assets/b9f42c9d-8c40-4a27-ac1a-5971f9c76b29)

Also sometimes getting the double snack, would be great to fix here too!

## Expected behaviour 🤔

Add structured error for NotMostRecentGivenDose and translate on frontend.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Follow steps above

## Your environment 🌱

- Open mSupply Version: v2.3.0 develop
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #4878

**Comment by alainsussol** [comment]
Tested with version 2.3.1RC2 on 2024/10/30
Store: Dispensary on omSupply central server site

# 🧪 Testing



- [ ] Set up vaccinations
- [ ] Enrol patient into program and create encounter
- [ ] Give 3 doses of some vaccine
- [ ] Change first dose to 'Vaccine not given`
- [ ] Click ok. See a friendly user message **-PASS-**
- [ ] Change second dose  to 'Vaccine not given`
- [ ] Click ok. See a friendly user message **-PASS-**
- [ ] Remove the 3rd vaccination dose, click OK no error message **-PASS-**
- [ ] The vaccine is set as "Not Given" **-PASS-**
- [ ] If revert was on Transaction, the stock should be adjusted: +1 dose available **-PASS-**
- [ ] Sync
- [ ] Check if the vaccination revert as been created on the mSupply Server as a customer credit  **-PASS-**
