### ISSUE TITLE
Failed to parse JSON file "index.ts"

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4856]
## What went wrong? 😲
```
[2024-09-24T05:38:08Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
[2024-09-24T05:38:09Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
```

## Expected behaviour 🤔

No errors should be created

## Agreed Solution
SHould check the file ends with `.json` before trying to parse it?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. run tests with     `util::init_logger(util::LogLevel::Warn);`
## Your environment 🌱

- Open mSupply Version: 2.3.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Daily triage: setting low priority... not blocking anything, but would be nice to clean up 😁

**Comment by jmbrunskill** [comment]
Pretty sure we can solve this by adding `#[include = "*.json"]` to `EmeddedLocalistions` in `localisations.rs`

Something like this...

```
#[derive(RustEmbed)]
#[include = "*.json"]
// Relative to server/Cargo.toml
#[folder = "../../client/packages/common/src/intl/locales"]
pub struct EmbeddedLocalisations;
```

See docs here:
https://crates.io/crates/rust-embed
