### ISSUE TITLE
No error displayed when changing dispensing date, and no stock available.

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4872]
## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #4876

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅
