### ISSUE TITLE
Refactor/improve the year/month table cell component

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#4874]
## The suggestion

For vaccinations we implemented #4848 to create a general multi-unit input component, in this case for years/months. However, this is just a first iteration and it could do with some improvements. It suffers from some of the same limitations the NumericTextInput component used to (and this component is in fact just a wrapper around that).

Here is a list of things that need to be improved (keep updated):

- [ ] When there is a minimum value set, can't backspace to a value that would (temporarily) be less than the minimum (e.g minimum of 10, can't backspace 13 to get 1 in order to type 12)
- [ ] The `rowData` value seems to be stale. The rowData value seems to only get updated on dismount/remount
- [ ] Currrently it enforces min/max just by constraining the final value, which causes (partially, at least) the above problems. Ideally, it'd be good if each individual cell had its own min/max values, but deducing what these should be from the global max/min and the current input state is very complicated. It's arguable whether this would be worth it, but it's worth having a bit of a look to see.

**Comment by andreievg** [comment]
Refinement, a lot of use case to think through and quite a lot of assumptions on behalf of the user, since it's currently working ok and we are going to change to just a drop down and an input we are closing this

**Comment by marthakeezy** [comment]
Nothing to test, moving to Done ✅
