### ISSUE TITLE
Server installer is not built

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4879]
## What went wrong? 😲

Jenkins is not producing the server installer

## Expected behaviour 🤔
Jenkins should produce the server installer

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Tag with `v[something` and push to remote

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
All builds were built to my knowledge, so moving to Done ✅
