### ISSUE TITLE
Update stocktake price column headers

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4891]
## What went wrong? 😲

In French, the headers have 'cost price' and 'sell price' and don't indicate whether this is a pack or unit price.
English is better, though we should improve 'cost' too:

<img width="551" alt="image" src="https://github.com/user-attachments/assets/3f2ae7ed-06a7-46d1-b756-1479848152db">

![telegram-cloud-photo-size-1-5165869931168902409-y](https://github.com/user-attachments/assets/6de97d13-728e-4158-9ee1-d999ffcecbaa)

## Expected behaviour 🤔
* Change fr to 'pack sell price' and 'pack cost price' or equivalent
* Change en to 'pack cost price'

**Update**
Have pushed the updated translation. For this issue though:

* add a new translation key for `label.pack-cost-price` for the `Pack cost price` and update the `costPricePerPack` to use this
* rename `label.sell` to be `label.pack-sell-price`
* update the inbound shipment detail view `useExpansionColumns` function to use `label.cost` - there isn't much space in the expansion area, and cost/pack relationship is clear in this case:

<img width="305" alt="image" src="https://github.com/user-attachments/assets/d7777a9d-567f-4c77-8b8f-41e62263fecf">

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Note that if the translation string key is `label.cost` or something generic, we would want to check the same label isn't used somewhere else that we _do_ mean unit cost!

**Comment by mark-prins** [comment]
It is in fact using `label.cost` but this is the only instance of it.
```
  costPricePerPack: {
    label: 'label.cost',
    key: 'costPricePerPack',
    width: 50,
    align: ColumnAlign.Right,
    Cell: CurrencyCell,
    format: ColumnFormat.Currency,
  },
```

I'll update the translation directly - would like the label to be more specific as well though. have updated the description.

**Comment by roxy-dao** [comment]
Closed in #5019

**Comment by roxy-dao** [comment]
The cost + sell price for above is for the pack size

**Comment by roxy-dao** [comment]
Can do... though to me the stock page implies 'price per pack' maybe not obvious enough? @mark-prins what do you think?

**Comment by mark-prins** [comment]
Thanks @roxy-dao, I'm happy to leave it implied for the stock line. I'd rather have the label simple on the stock modal, it makes it a bit cleaner. Even though it might be not as clear as saying 'Cost price per pack'

**Comment by marthakeezy** [comment]
Moving to done - build test passed ✅
