### ISSUE TITLE
Improve server discovery on Windows with poor internet

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4894]
## Is your feature request related to a problem? Please describe 👀

In locations with poor internet (particularly) discovery can be challenging.

![image](https://github.com/user-attachments/assets/023a57ef-b4c8-49f4-b097-074740853dc8)

## Describe the solution you'd like 🎁

Not sure yet, but should investigate what can be done to improve things.

Investigate if there's an alternative to the look back adaptor solution in windows?

What if we simply always check if a localhost connection can be made and make that an option, rather than relying on discovery...

I'm thinking, especially given #4893 and machine name length limitations we should probably provide a mechanism to configure desktop without relying on discovery...

**Comment by andreievg** [comment]
I would propose solving this with manual connect to url which by default is https://127.0.0.1:8000, which would also solve other issues that have been raised #5080

**Comment by marthakeezy** [comment]
No QA required here, moving to Done and will be tested in later issues that are still open at the moment
