### ISSUE TITLE
Encounter - cannot add a Comment/ Notes when creating a new vaccination 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4898]
## What went wrong? 😲

in Encounters > Programs, if you create a new vaccination by clicking on a row, you cannot input a comment in the comment box

![Screenshot 2024-09-27 at 5 34 33 PM](https://github.com/user-attachments/assets/102b5be0-6157-4a14-bc9c-eb68f40666be)

and when creating a new encounter, cannot add 'Notes' .

![Screenshot 2024-09-27 at 5 39 39 PM](https://github.com/user-attachments/assets/d54cd626-ed78-473a-823e-c280acf0e751)

After closing the app, restarting the sever, I can type into those field. Not sure why ?

## Expected behaviour 🤔

When you type a comment/note, it is displayed and saved.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Patients' > Add Program > Add Encounter
2. Click on 'Notes', type a word. See error
3. Save. now in Encounter, click in a row to create a new vaccination
4. Try to add a comment, type a word. See error

## Your environment 🌱

- Open mSupply Version: V2.3 RC2
- Legacy mSupply Central Server Version: V7.17

- Platform: Desktop app (windows)

**Comment by regotaina** [comment]
I thought I'd add here:

Tried to type a Facility name and nothing shows up. Maybe all these fields issues are related.

![Screenshot 2024-09-27 at 5 39 39 PM](https://github.com/user-attachments/assets/d54cd626-ed78-473a-823e-c280acf0e751)

**Comment by regotaina** [comment]
Restarted the server, now I can type, but the text is floating, not aligned. At least I can type! a bit weird.
not sure if easily reproduced

![Screenshot 2024-09-27 at 6 08 32 PM](https://github.com/user-attachments/assets/efddca4f-2372-4d24-bb95-e0630456866f)

**Comment by lache-melvin** [comment]
Not sure why the inputs were disabled, would be interested if we can reproduce!

In the meantime... wondering why the input fields aren't grey in the desktop app 👀

**Comment by lache-melvin** [comment]
Leaving off milestone/severity until we can reproduce! @mark-prins / @mariyamsupply is the textboxes not being grey on desktop worth a separate issue?

**Comment by mark-prins** [comment]
yes, worthy of a separate issue 🙏 
The app isn't very usable like this

**Comment by lache-melvin** [comment]
#4923 created!
