### ISSUE TITLE
V2.3.0 Release Testing: Basic built in reports (part 2/3)

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4899]
Followed the steps from our Feature release meeting to set up reports correctly.
Epic Issue [HERE](https://github.com/msupply-foundation/open-msupply/issues/4668)
- Testing on `V2.3.0RC2` APK and Server(Desktop and Browser)

- [x] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1506" alt="Screenshot 2024-08-09 at 2 45 56 PM" src="https://github.com/user-attachments/assets/f099890c-2f59-400b-8881-d349cf110d4b">

- [x] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [x] You will be presented with a list of reports that you can generate. The reports listed below are the standard reports and will already be set up for you.
- [x] Click on one of the reports on the report page and ensure that it shows the correct report
- [x] The reports should be generated based on preferences which are set up in the mSupply central server

## ITEM USAGE
- [x] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK STATUS
- [x] Try using the filters
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK DETAILS
- [x] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [x] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## EXPIRING STOCK
- [x] Try using the filters
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

**Comment by marthakeezy** [comment]
Picking up from Anusha and testing in `V2.3.0-RC6` on a tablet :) Also updating the testing suite as I go ~

- [x] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1508" alt="Screenshot 2024-10-08 at 12 14 05 PM" src="https://github.com/user-attachments/assets/abb606e4-6566-4432-8d0d-48364dc17287">

- [x] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [x] You will be presented with a list of reports that you can generate. The reports listed below are the standard reports and will already be set up for you.
- [x] Click on one of the reports on the report page and ensure that it shows the correct report
- [x] The reports should be generated based on preferences which are set up in the mSupply central server

## ITEM USAGE
- [x] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK STATUS
- [x] Try using the filters
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## STOCK DETAILS
- [x] Try using the filters 
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [x] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

## EXPIRING STOCK
- [x] Try using the filters
- [ ] generate report base analysis on whatever months you have your lookback_months set to
- [ ] Review report readme for how columns should calculate - will test accordingly
- [x] Check the print button is working
- [x] Check the export button downloads and opens in excel

**Comment by marthakeezy** [comment]
Apart from those two bugs: 

#5036 and #4990

It's looking good :) Build test passed, moving to Done ✅
