### ISSUE TITLE
Homepage Dashboard > Add a "Show" or "Display" button for each transactions

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#490]
In addition a to button to create a new record, it would be useful to have another button to simply display records of related transactions. Eg. For the Inbound Shipments column, have a button to display them (Show Inbound Shipments).

**Comment by DhanyaHerath** [comment]
Does the links on the headers address this @richardmoizeau 
<img width="311" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/29744386/b5d473bd-2354-42c4-9e4f-68fda317119e">
