### ISSUE TITLE
Backdate prescriptions - stock numbers are strange

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4900]
## What went wrong? 😲

When you change the date on the prescription, then the stock numbers (available & in store) show values from the start of the date selected. This is problematic when the date is today, as any transactions made today aren't included.

This was compounded by an existing weirdness, which is that the 'in store' total is reduced by the quantity issued on the current prescription, but the 'available' is not. Thus you can have less stock in store than is available:

![image](https://github.com/user-attachments/assets/d4ae9415-1b88-45cd-b912-84d054e84885)

## Expected behaviour 🤔
Two changes would make things clearer:

* Change the time to 23:59 for the selected date
* Adjust the displayed value for the stock in store to be stock + quantity allocated to this prescription

The second item is how the available stock column behaves; we need to have both stock columns behave consistently

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add some stock for item a
2. Create a prescription
3. Add item a
4. see that the stock which you've just added is not available: the full total shows in the 'in store' total but is not in the 'available' total

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #4911, #4914

**Comment by marthakeezy** [comment]
Tested in V2.3.0 as a part of backdating prescriptions epic, moving to Done ✅
