### ISSUE TITLE
Can't delete Customer Return lines

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4901]
## What went wrong? 😲
Can't delete customer return lines because of invalid hook call

## Expected behaviour 🤔
Should be able to delete lines if they were added by mistake

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a customer return
2. Add a line
3. Select the line
4. Actions -> Delete
5. See error

## Your environment 🌱

- Open mSupply Version: 2.3.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #4927

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
