### ISSUE TITLE
Add support for KMF as a currency

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4910]
## Is your feature request related to a problem? Please describe 👀
As per the title - we need to support `KMF` as a currency; please add to `Currencies` and `currencyOptions` in `currency.ts`

## Describe the solution you'd like 🎁
When the system currency is 'kmf' then we should see this as the currency symbol

### Describe alternatives you've considered 💭
No alternatives

**Comment by lache-melvin** [comment]
Closed by #4920

**Comment by marthakeezy** [comment]
Build test passed ✅
