### ISSUE TITLE
'Line Already Exists' error when entering Prescription

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4915]
## What went wrong? 😲

A little hard to recreate! I've seen it twice, and they occurred when there was an action (e.g. adding a new item to a prescription), and the system was a bit slow to update, causing the screen to freeze, and when I clicked the `Save` button again to try and save the changes, the error showed up

<img width="557" alt="Screenshot 2024-09-30 at 5 16 04 PM" src="https://github.com/user-attachments/assets/3ea3995c-7338-45c6-b38d-91d3f1b57507">

Hard to run into, so marking as `Low Severity`

## Expected behaviour 🤔

Error should not be there

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions
2. Add a new prescription or edit an existing one
3. Use dev tools to throttle network speed
4. Add item
5. Click `OK` multiple times in quick succession
6. See error

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC3
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite 3

**Comment by lache-melvin** [comment]
Given the low likelihood, and low impact, agree severity is low, but we should be using loading buttons on any actions that might take time, so the button is disabled while the prescription is being created 👀

**Comment by andreievg** [comment]
Moving priority to normal because of the solution proposed by Lache about loading state

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.5.0`

- [ ]  Go to Dispensary -> Prescriptions
- [ ] Add a new prescription or edit an existing one
- [ ] Use dev tools to throttle network speed
- [ ] Add item
- [ ] Ensure the OK button cannot be clicked more than once

**Comment by marthakeezy** [comment]
Hi team, 

I can see from the PR the solution was to implement a loading button, but actually it seems like the buttons disappear entirely once the item is added? Just checking if this is intended behaviour?

@aimee-mcneil-melville @lache-melvin 

Video attached ->>> [here](https://drive.google.com/drive/folders/1qe0GOWW5MNyJm026oVr3dMR9joGD11TT)

**Comment by lache-melvin** [comment]
Ohh funky! Looks like this bug fix actually got overwritten by the new prescription UI - but the buttons should stay visible (in that loading state) while the save is happening! Given it's a bug with the new UI, would you mind raising as a new issue? Curious if this only happens in prescriptions or also in the internal order/requisitions?

**Comment by marthakeezy** [comment]
Raised #6271
