### ISSUE TITLE
Vaccination card transactions aren't rounding correctly

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4916]
## What went wrong? 😲

For vaccines where doses per unit is more than one, after creating a few vaccination transactions, we end up with this:

![Screenshot 2024-09-30 at 5 20 52 PM](https://github.com/user-attachments/assets/ae4ec0db-a112-478e-b4f3-7587f9f48aa0)

Also, the batch select (in the vax card) is rounding the decimals, so if you end up with and almost-zero stock line, it shows there as 0. Doses should always be an integer, shouldn't need the rounding!

![Image](https://github.com/user-attachments/assets/bfa1ced5-da48-43f8-8c74-e1e9e8907d7c)

## Expected behaviour 🤔

Decimal reductions in stock from vaccinations add up to whole units. None of this 0.00000000000001 business.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a vaccine item with many doses per unit. Bonus points for something like 7 per unit 😱 
2. Give some vaccinations
3. View stock levels

## Your environment 🌱

- Open mSupply Version: v2.3.0 RC3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Expectation is that most of the time, either:

- System will be set up that the base unit is a dose (so one dose per unit)
- Or, usually a nice divisible number per vial (e.g. 10, 20..)

There may be times there is e.g. 6 doses per vial, but this is probably not too common that we need to worry about it, at least for now.

If it does happen, should be resolved via inventory adjustment, rather than any magic by us behind the scenes. Perhaps could implement a special kind of stocktake in future for this?

In the meantime, change vaccination modal UI to show <1 dose, and disable this line (as can't dispense less than a dose), to indicate to the user that inventory adjustment is required

**Comment by lache-melvin** [comment]
Closed by #5011

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.7.0-RC8`

- [ ] Have less than a dose worth of a vaccination left (set something like 3 doses per vial (0.3333 units each vaccination, so end up with 0.000000001 units after 3 vaccinations)
- [ ] Try to give another dose of that vaccine item
- [ ] That batch should be disabled, and show <1
