### ISSUE TITLE
Location disappears when i enter cost and press save

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4917]
## What went wrong? 😲
on oms tablet version 2.2.01 - I had item and locations in but didn't have costs..

i added costs and pressed save and my location then disappears (note it only disappears after I press save but it is still there before I press save when I am editing)

<img width="1104" alt="Screenshot 2024-10-01 at 8 41 54 AM" src="https://github.com/user-attachments/assets/4adc65b2-fd48-4fcc-b44e-413f36193dca">

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Hey @louisaw123 - could you confirm which part of the app you noticed this in? 🙏

**Comment by lache-melvin** [comment]
Oh strange - it's happening somewhat intermittently for me 👀 Haven't looked into when it does/doesn't clear the location but something is definitely up!

**Comment by marthakeezy** [comment]
# 🧪 Testing



V2.4.0-RC6

- [ ] Go to Inventory -> View Stock and click on an item
- [ ] If the item doesn't have a location, set one, save, then exit back to the list
- [ ] Go back to the same item, change some other values (e.g. costs)
- [ ] Save, and ensure the "Location" is kept as-is
- [ ] Maybe check the behaviour in some other places where user can set `null` values and ensure no regressions

**Comment by marthakeezy** [comment]
Hey team, minor issue but now Location takes some time to show up - even when other fields are edited and saved, they still show up immediately. But location (regardless if it was changed or not), takes a few moments to show up. 

https://github.com/user-attachments/assets/82475255-8841-4e3c-a189-8686de3c0ccd

**Comment by lache-melvin** [comment]
Closing this one as main issue is resolved - the reloading issue already tracked here #5442
