### ISSUE TITLE
Report and Requisition (R&R) forms II

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4922]
## Is your feature request related to a problem? Please describe 👀
An epic to collate the planned changes for R&R forms. 
As discussed, we'll look at renaming columns by adding a translation override facility to the central oms server. The additional columns requested will be hacked in quickly, pending a rework to implement using plugins at a later date.

To be implemented
- [x] #4810 
- [x] #4768 
- [x] #4726 

And these ones which we had as future possibilities. Some closed due to lack of interest, to be revived if needed:
- [x] #4418 (implement with backdated transactions?)
- [x] #4421 (these can just happen as a dashboard for now)
- [x] #4475 (pending decision)

And to be checked
- Is the number of AMC lookback months taken from the store preference? I'd like the lookback number to be configurable

**Comment by mark-prins** [comment]
To answer my question: It's not. 
The number of periods is hard coded in `get_previous_monthly_consumption`
Let's not change the functionality now though. 
We could use the store pref `monthly_consumption_lookback_period` though this is specified in months and the R&R period  length is necessarily a month. 

Leave the functionality as it is - if an R&R implementation does want to configure the lookback periods, we'll create a facility property or store preference for this at that stage.

**Comment by AnushaUp** [comment]
Tested and PASSED✅
