### ISSUE TITLE
Inputs have no background colour on Desktop

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4923]
## What went wrong? 😲

Screenshots from Taina, testing desktop - this is how all inputs are rendering:

![Screenshot 2024-09-27 at 6 08 32 PM](https://github.com/user-attachments/assets/efddca4f-2372-4d24-bb95-e0630456866f)

Hard to tell what is enabled/disabled. The note looks like its floating in the middle of nowhere - you can't tell its a multi-line input.

## Expected behaviour 🤔

Should render the same as the do in browser/android:

![Screenshot 2024-09-27 at 6 37 26 PM](https://github.com/user-attachments/assets/b11c833b-7fcc-43ef-ba8a-be230aae64e2)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. View a form with the desktop app

## Your environment 🌱

- Open mSupply Version: v2.3 RC2
- Legacy mSupply Central Server Version:

- Platform: Desktop

- Database type:

**Comment by marthakeezy** [comment]
Tested in `V2.3.0-RC8` and appears fine for me

<img width="746" alt="Screenshot 2024-10-11 at 11 51 28 AM" src="https://github.com/user-attachments/assets/c12cab5a-49e2-44c5-9f3a-4397c809068c">

**Comment by lache-melvin** [comment]
Ok great, will close this one for now! @regotaina Imagine this one is probably a computer setting somewhere, maybe we can investigate one day 🙏
