### ISSUE TITLE
Deleting a vaccine course doesn't remove the course doses from the vaccine card

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4924]
## What went wrong? 😲

Vaccine course doses aren't being marked deleted when the vaccine course is deleted. The view only checks if the dose is deleted before rendering, so we end up with this:

![Screenshot 2024-10-01 at 10 01 08 AM](https://github.com/user-attachments/assets/f99d3cb1-263d-4f35-b343-6c60100d35eb)

## Expected behaviour 🤔

If a course has been deleted, and the patient hasn't already received the doses from that course, those doses should not show in the card.

Could check both the course and the doses in the view, but I think more correct to update the vaccine course delete logic to also mark the doses as deleted

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create vaccine course
2. add some doses
3. delete the course
4. view the vaccine card
5. the doses are still there!

## Your environment 🌱

- Open mSupply Version: v2.3.0 rc3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
closed by #4976

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.0-build-test-3`

- [ ] Create a vaccine course with doses
- [ ] See doses in vax card
- [ ] Delete the vaccine course
- [ ] Check vax card - doses should not be there
- [ ] (Note - doses where vaccination has already be recorded will continue to show in the card, just can't administer new ones!)
