### ISSUE TITLE
Sync stopped with no error in the log

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4925]
## What went wrong? 😲

Sync stopped after a couple of connection errors (not clear if it's related)

![image](https://github.com/user-attachments/assets/e4feb4e1-9e77-4289-97d7-21f35713a146)

## Expected behaviour 🤔

Should either have some kind of timeout for sync to restart (if sync is hanging waiting for a connection perhaps?)
There should be an error if the whole sync process ends?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Not sure how to reproduce yet!

## Your environment 🌱

- Open mSupply Version: 2.2.2
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Adam has run into this again - no connection errors in the log this time so that is probably unrelated. Restarted the app to get sync going again... but still not sure of reproduction steps 👀 Setting severity high as I think needs to be investigated?

**Comment by andreievg** [comment]
Looking into logging into the server today to check

**Comment by andreievg** [comment]
We've set the logging level to Info, will report when this issue appears again

**Comment by andreievg** [comment]
Triage, closing, log level should be info by default, next time this appears we can get a better indication of the problem
