### ISSUE TITLE
Item ledger - Column named 'Number' confuses users

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4935]
## What went wrong? 😲

In the Item ledger view, there is a new column called 'Number' (not in the docs yet)

@lache-melvin solved the mystery and said it's the Invoice Number! But for users, 'Number' can be confusing with 'Quantity' or 'Unit'. 

## Expected behaviour 🤔

Can we please have the column named 'Invoice Number' ?

## Your environment 🌱

- Open mSupply Version: V2.3 RC3
- Legacy mSupply Central Server Version: V7.17

- Platform: Android

**Comment by DhanyaHerath** [comment]
triage: can be renamed, suggest it could also be named "Invoice" if the full thing too long

**Comment by roxy-dao** [comment]
Closed in #5393

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-RC2`

- [ ] View Stock -> detail view -> ledger tab
- [ ] number column now says `Invoice no.`
