### ISSUE TITLE
Available can be bigger then total in outbound line edit 

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4936]
## What went wrong? 😲

Available can show higher then total in picked outbound shipment line edit

## Expected behaviour 🤔

Total should never be lower then available.

## How to Reproduce 🔨

Create new outbound, issue some stock, change status to picked, see that total is lower then available in outbound line edit.

## Agreed solution

Adjust total + number of packs issued for picked outbound lines.

Related:
https://github.com/msupply-foundation/open-msupply/pull/4911
https://github.com/msupply-foundation/open-msupply/issues/3252

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Daily triage: setting as high - the system's numbers aren't incorrect, so that's good, but they look pretty incorrect to a user 👀

**Comment by lache-melvin** [comment]
Closed by #5040

**Comment by marthakeezy** [comment]
Tested in V2.3.0 alongside backdating prescriptions changes, moving to Done ✅
