### ISSUE TITLE
Inbound Shipment: app crashes when changing status from 'Delivered' to 'Verified'

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4941]
## What went wrong? 😲

After receiving an Inbound Shipment, I made no changes and set status to 'Delivered'.
Then changed the quantity received, from 30 to 29, considering for example that 1 vial was damaged during shipping.

App crashes straight away when changed status to from 'Delivered' to Verified'.

## Expected behaviour 🤔

App does not crash and stock is updated.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inbound Shipment'
2. Choose a shipment that status = 'Shipped'
3. Change status to 'Delivered' 
4. Adjust the quantity of your first item line and reduce 1 unit.
5. Change status to 'Verified'.
6. See error.

## Your environment 🌱

- Open mSupply Version: V2.3RC3
- Legacy mSupply Central Server Version: V7.17

- Platform: Browser

**Comment by regotaina** [comment]
I was able to reproduce the error twice, repeating the steps above.

I will explore more scenarios, but it's worth investigating this one.

**Comment by AnushaUp** [comment]
Can be recreated in all the scenarios🥲

**Comment by lache-melvin** [comment]
Closed by #4942

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅
