### ISSUE TITLE
V2.3.0 Release Testing: Inbound and Outbound Returns

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4944]
**Change via Customer Return**
- [x] Go to stock and choose a stock line to be tested. Take notes of the batch.
- [x] Go to Outbound shipments and create a new Customer return
- [x] Add 2 units of the item you chose to be tested 
- [x] Confirm the status as 'verified'
- [x] Go back to 'stock' 
- [x] The increase via Customer Return should have created a new stock line. If you check the ledger tab it should say 'Customer return'

**Change via Supplier Return**
- [x] Go to stock and choose a stock line to be tested. Take notes of the batch.
- [x] Go to Inbound shipments and create a new Supplier return
- [x] Add 2 units of the item you chose to be tested 
- [x] Confirm the status as 'verified'
- [x] Go back to 'stock' 
- [x] The decrease via Supplier Return will appear in the existing stock line. If you check the ledger tab it should say 'Supplier return'

**Comment by regotaina** [comment]
No issues found. Closing this one

**Comment by marthakeezy** [comment]
Bug found: #5121

**Comment by regotaina** [comment]
> #5121

I thought it only accepts decimal if decimal = 100% of packs available

otherwise it won't accept. 

'Decimal inputs' issues are still open and do not seem to have been implemented in V2.3RC8 yet. Devs can confirm which milestones will be attributed to

**Comment by marthakeezy** [comment]
The bug is mostly about not being able to delete a number in the cell ^
