### ISSUE TITLE
Error when printing default report

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#4947]
## What went wrong? 😲
Getting this error when printing out an inbound shipment 

![Screenshot 2024-10-02 at 12 28 34 PM](https://github.com/user-attachments/assets/6d8b2a3f-c61c-445e-b0a4-1039ee63c360)

## Expected behaviour 🤔

No error

## How to Reproduce 🔨

Initialise omSupply site

Create new user in mSupply and use that user to create customer invoice for the omSupply site

Try to print Inbound Shipment that was created from the customer invoice (make sure to not edit anything in inbound shipment before printing)

See error

## Suggested Fix

If user is not found in the system, graphql will return 'null' for that user, and configured report will try to access that user in tera template and fail. For now the fix should default to empty string if user is not found. For future we need to think about syncing all users to omSupply (which happens only during initialisation). You can force sync user to stores they have logging rights to (when logged in as special user in mSupply at the bottom of 'login rights' tab there is check box, but that will only sync user to places where they have login rights).

Another fix would be to return an empty user node in graphql

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by regotaina** [comment]
I got this error today (currently don't have the report set up).

Is it possible to make the message be a bit more clear that it needs to be configured first?

<img width="1403" alt="Screenshot 2024-10-15 at 9 35 21 AM" src="https://github.com/user-attachments/assets/3d138f27-bcc6-4f92-9cdd-6e7f58bac7ee">

**Comment by andreievg** [comment]
@regotaina I think this is wrong report setup. Although you mentioned that it's not the case, maybe it did sneak through the configurations ?

**Comment by regotaina** [comment]
> @regotaina I think this is wrong report setup. Although you mentioned that it's not the case, maybe it did sneak through the configurations ?

I was using the only Internal Order report we have available in the repo, in a client folder, but Lache instructed me to use the standard Replenishment one instead. It worked.

**Comment by alainsussol** [comment]
Tested as part of Release testing 2.5.0
