### ISSUE TITLE
Message in automatic Customer Return doesn't update when status has been changed to Delivered

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4952]
## What went wrong? 😲
Updating status to delivered in Customer Returns doesn't update the message in the toolbar. This doesn't block anything, but can potentially cause confusion if message contradicts what you can do 🤷🏻 

![photo_2024-10-02 14 09 55](https://github.com/user-attachments/assets/754c7b90-90e6-4c54-9309-fa9c5411c2db)

## Expected behaviour 🤔
Message should update.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a Supplier Return to OMS supplier A
2. Set status to Shipped
3. Go to OMS supplier A store -> Customer Return
4. Click on newly generated return
5. Change status to Delivered
6. See that message still says you can't edit the details until status is changed to Delivered
-- Correct message below--
7. Refresh
8. See actual message

## Your environment 🌱

- Open mSupply Version: 2.3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.5.0`

- [ ]  Create and ship a supplier return 
- [ ] Go to the supplier store
- [ ] Update the customer return status from Shipped to Delivered
- [ ] The message banner should update

**Comment by marthakeezy** [comment]
Hey @aimee-mcneil-melville & @lache-melvin 

Can I just confirm - when syncing, and after a successful sync the message still does not update - you have to manually refresh the page to see the updated statuses. While in browser, refreshing is easy but slightly concerned for Android

Is this to b expected?

**Comment by lache-melvin** [comment]
Hi Maria - yeah this is an issue in 2.5 with the sync being moved to a modal, but already addressed in 2.6, we now have a "refresh after sync" feature #6201 👍

**Comment by marthakeezy** [comment]
Oh cool! Cheers

Moving to Done ✅
