### ISSUE TITLE
Question regarding demographic permissions

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4963]
## What went wrong? 😲
If I have edit central data ticked, and now `View Assets`... I can add indicator but it doesn't show up on my list and the permission toast doesn't give much information about what permission the user doesn't have. 

A bit confused about whether the demographics needs the view assets permission? 

Also getting a `Cannot read properties of undefined (reading '__typename')` error

https://github.com/user-attachments/assets/b75809e2-d1f8-4fdd-8fa4-27c7abca5e1a

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Tick edit central data permission and untick view asset permission
2. Go to demographics
3. Try add new indicator

## Your environment 🌱

- Open mSupply Version: 2.3
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
A few issues here!

1. Firstly the __typename error

2. If you don't have `view assets` permission, you get a permission denied popup trying to edit a vaccine course:
![Screenshot 2024-10-03 at 11 15 30 AM](https://github.com/user-attachments/assets/8224df56-ce35-4372-9952-27dae4ffa6a6)

3. No store_id check, so you _can_ view demographics, even if `view assets` is off for your store, as long as it is on for _any_ store the user has access to... even stores not on this site!
https://github.com/msupply-foundation/open-msupply/blob/ef7d01f61170e5d56a712dab9c5b1c11b16a3ab0/server/graphql/demographic/src/lib.rs#L36-L49

4. Also, `view assets` doesn't seem a particularly intuitive permission for this feature, and isn't mentioned in the docs 👀 

I think 1 & 2 should probably go into 2.3, maybe 3 and 4 can be solved later... but will let triage team decide here 🙏

**Comment by andreievg** [comment]
Triage, if 3 and 4 is not too much extra work i would suggest doing as part of this issue.

And we agree to other suggestions by Lache

**Comment by andreievg** [comment]
> If you don't have view assets permission, you get a permission denied popup trying to edit a vaccine course:

Target demographic renders no option instead of permission denied

**Comment by roxy-dao** [comment]
Also don't think view assets is the best permission for demographics...

**Comment by lache-melvin** [comment]
Whoever does this issue, can they please check demographic indicators aren't used anywhere else? Hoping `view assets` was just put in in a rush before the `edit central data` permission existed, and not because demographics need to be queried by non-central admin users?

**Comment by roxy-dao** [comment]
Closed in #4988

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅

**Comment by AnushaUp** [comment]
# 🧪 Testing



- [ ] Be an OMS central 
- [ ] Go to demographics
- [ ] Should be able to view demographics without permission

**Comment by AnushaUp** [comment]
@roxy-dao Is there any specific permissions for adding an indicator except user permission to modify central data, store pref for vaccine module and Initialise store properties for GAPS? Because I've turn them all and still not letting me to add indicator. 
https://github.com/user-attachments/assets/ca5b4869-c15d-48f5-8a2d-2b2f6e6878a7

**Comment by roxy-dao** [comment]
> @roxy-dao Is there any specific permissions for adding an indicator except user permission to modify central data, store pref for vaccine module and Initialise store properties for GAPS? Because I've turn them all and still not letting me to add indicator. [user-attachments/assets/ca5b4869-c15d-48f5-8a2d-2b2f6e6878a7](https://github.com/user-attachments/assets/ca5b4869-c15d-48f5-8a2d-2b2f6e6878a7)

It should just be the Edit Central Data permission... can I have your data file to see?

**Comment by AnushaUp** [comment]
I've tried reinitialising as well but not happening [HERE](https://www.dropbox.com/scl/fi/h1wxrq3xnkey43byuch1p/Test-StoreV7-18.zip?rlkey=zfifbmomsj61fhucchwlh8js9&st=c2rlgrxp&dl=0) is the datafile I've been using.

**Comment by roxy-dao** [comment]
> I've tried reinitialising as well but not happening [HERE](https://www.dropbox.com/scl/fi/h1wxrq3xnkey43byuch1p/Test-StoreV7-18.zip?rlkey=zfifbmomsj61fhucchwlh8js9&st=c2rlgrxp&dl=0) is the datafile I've been using.

Your `central user` didn't have `Can modify central data` ticked for central oms store...

**Comment by AnushaUp** [comment]
@roxy-dao sorry, my bad. Build test Passed✅
