### ISSUE TITLE
Can no longer do OMS central server things if OG central is off and turned back on again

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4973]
## What went wrong? 😲
Can no longer edit or see OMS central server features if I turn off OG central server for a while and turn back on. Have to re-initialise to get central OMS features back.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Initialise as central
2. Login 
3. Turn off OG central
4. Wait awhile (10 mins?)
5. Turn OG central back on
6. See OMS central features gone.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
> Had my OG central off for 20 min, couldn't reproduce... have you been able to repeat this? 👀

Yah often. I just turn off OG, then go do some coding. Turn back on... login to OMS -> get normal UI instead of OMS central UI

**Comment by lache-melvin** [comment]
FYI my `central` features go away while OG is off, but restarting OMS server brings them back 👀 Will also keep an eye out!
