### ISSUE TITLE
Pages rendering currency input crash in Spanish

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4977]
## What went wrong? 😲

View stock page crashed with this error:

![Screenshot 2024-10-03 at 2 44 42 PM](https://github.com/user-attachments/assets/a49a7c82-1f16-4c4b-9cca-21cbfa6cef1a)

![Screenshot 2024-10-03 at 2 44 47 PM](https://github.com/user-attachments/assets/daf45230-f6b0-47c7-9870-c48c257bfe7e)

Same with tax input - I think any currency input

## Expected behaviour 🤔

App does not crash 🙈 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set app to Spanish
2. Go to view stock page for a stock line

## Your environment 🌱

- Open mSupply Version: v2.2.01
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
No active users in Spanish. But need to fix for any Spanish demos, so will put fix in 2.3

**Comment by lache-melvin** [comment]
Closed by #4983

**Comment by marthakeezy** [comment]
V2.3.0 Released, so moving to Done ✅
