### ISSUE TITLE
When backdating an invoice to `today` the dates aren't correct

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#4979]
If backdated time is after created_datetime, it's sort of considered not a backdated invoice, although the field is populated in the db which could cause some confusion in reporting (if that was to happen) e.g. # of backdated invoiced could be incorrect if people set it to today a lot...

_Originally posted by @jmbrunskill in https://github.com/msupply-foundation/open-msupply/pull/4914#discussion_r1780383673_

**Comment by jmbrunskill** [comment]
Possible Solution: Just unset the backdated_datetime if it's set to something > `created_datetime`

**Comment by andreievg** [comment]
Triage, restrict date to be only settable before prescription date, probably need to refine this together with general issue on how to set backdate date

**Comment by lache-melvin** [comment]
Closed by #5168

**Comment by marthakeezy** [comment]
Passed the test! Moving to Done ✅

**Comment by marthakeezy** [comment]
@jmbrunskill the issue came back with `V2.3.2-RC1`

<img width="1252" alt="Screenshot 2024-11-08 at 12 18 17 PM" src="https://github.com/user-attachments/assets/308c73ec-4930-4bfc-ba60-e2862271a455">
