### ISSUE TITLE
Invoice line is not deleted when it's zeroed out in Outbound Line Edit modal

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4984]
## What went wrong? 😲

When setting previously issue line to zero, it is not deleted but appears with 0 quantity

https://github.com/user-attachments/assets/fd7f57bb-383e-4f36-8c96-b2886508f534

## Expected behaviour 🤔

Invoice line should be deleted when zeroed out

I am reluctant to make any changes to the front end logic, would like most of the logic in the modal to be relocated to backend (similar to how supplier/customer returns were done), following this issue: https://github.com/msupply-foundation/open-msupply/issues/3252

## How to Reproduce 🔨

Add some stock to outbound shipment
Go back to the outbound edit modal, zero out stock
As per screen recording you will see zero quantity invoice line

## Your environment 🌱

This is on main branch (2.2.03)

**Comment by lache-melvin** [comment]
Only in `New` status - once allocated, 0 quantity lines are removed. Makes me wonder if it was intentional? But seeing as you have to delete all `0` lines before you can change to Allocated, would be nice if the system helped you out with that 🙏

**Comment by andreievg** [comment]
Closing for now, the outbound line edit description issue will cover this for a discussion
