### ISSUE TITLE
App crashes if you refresh or change language on reports page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4990]
## What went wrong? 😲

https://github.com/user-attachments/assets/d81cdd32-9427-4766-b3a7-9efece0de986

Recording is on browser, APK also crashes with `File not found`
 
<img width="1280" alt="Screenshot 2024-10-04 at 11 38 25 AM" src="https://github.com/user-attachments/assets/caf6bbc9-1e2e-48d0-b19d-92763ae58e07">

Probably low likelihood for user to change language, but we don't love app crashes 😁 

## Expected behaviour 🤔

App does not crash - maybe just redirects you back to base reports page??

At the VERY LEAST we should fail to the error boundary, not this not found page!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports
2. Generate a report
3. Change the language
4. App crashes

## Your environment 🌱

- Open mSupply Version: v2.3.0-RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
just realised the app also crashes when you refresh on report page! even if not changing the language 😓

**Comment by lache-melvin** [comment]
Closed by #5020

**Comment by marthakeezy** [comment]
Was fixed in 2.3.0, moving to Done ✅
