### ISSUE TITLE
Expiring items report is not translated

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4992]
## What went wrong? 😲

The Expiring items report is not being translated, this should be in French:

![Screenshot 2024-10-04 at 11 59 35 AM](https://github.com/user-attachments/assets/8506402a-6407-4f33-b580-074435753a8e)

Expiring Items report - no translation keys:
https://github.com/msupply-foundation/open-msupply/blob/bc198972c9bd8fd6c69e0d504e0bd48907997c64/server/reports/expiring-items/2_3_0/src/template.html#L6-L14

## Expected behaviour 🤔

The columns we have translations for should translate

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports
2. Switch to french/other language
3. Generate expiring items
4. See column headers - all in English

## Your environment 🌱

- Open mSupply Version: 2.3.0 RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Stock status doesn't seem to be translated as well

**Comment by lache-melvin** [comment]
Months not translated:

https://github.com/msupply-foundation/open-msupply/blob/bc198972c9bd8fd6c69e0d504e0bd48907997c64/server/reports/stock-status/2_3_0/src/template.html#L12-L14

**Comment by lache-melvin** [comment]
while we're HERE some translation strings are missing closing parentheses:

![Screenshot 2024-10-04 at 1 07 44 PM](https://github.com/user-attachments/assets/261e413f-0c47-4670-90ea-9d5a7232f1f5)

**Comment by lache-melvin** [comment]
> while we're HERE some translation strings are missing closing parentheses (for item usage report):
> 
> ![Screenshot 2024-10-04 at 1 07 44 PM](https://private-user-images.githubusercontent.com/55115239/373448847-261e413f-0c47-4670-90ea-9d5a7232f1f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMDA3OTgsIm5iZiI6MTcyODAwMDQ5OCwicGF0aCI6Ii81NTExNTIzOS8zNzM0NDg4NDctMjYxZTQxM2YtMGM0Ny00NjcwLTkwZWEtOWQ1YTcyMzJmMWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDAwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDVjOGRhZWRhZjQ5YzQ0MjgzYjZhNmIyMjA2M2IzOWY1YTkxYjU4YzgzZGQ4Yjc1ZjkzYzlhMTM3MWZlODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8KHccEPb3erKlEDM3It5FwpIb_eoV9flsmazSmNaNlU)

**Comment by roxy-dao** [comment]
Closed in #5013

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
