### ISSUE TITLE
Status chips wrap and look ugly

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4995]
## What went wrong? 😲

Not particularly important but it is particularly displeasing:
![Screenshot 2024-10-04 at 12 37 44 PM](https://github.com/user-attachments/assets/f9734a4d-6f62-466e-aaff-2aa7dc206fc1)

## Expected behaviour 🤔

Either apply `no-wrap`, or the background of the chip should be around all of the text, rather than highlighting each line

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Generate report with status chip e.g. expiring items
2. Use smaller screen e.g. tablet
3. See chips are wrapped

## Your environment 🌱

- Open mSupply Version: v2.3.0 RC5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
Tested in V2.4.1-RC3, on a tablet and with small browser screen - no wrapped labels anymore :) Moving to Done! ✅
