### ISSUE TITLE
Inventory adjustment modal height does not adjust with keyboard

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4996]
## What went wrong? 😲

View stock - inventory adjustment modal:

![image](https://github.com/user-attachments/assets/2fa4ca25-154f-4e26-81f8-0d2abc6e9862)

Height does not adjust, and cannot scroll to see rest of the modal

## Expected behaviour 🤔

Height adjusts for keyboard, modal is scrollable.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to View stock
2. Click adjust
3. Tap one of the input fields to open the keyboard
4. Height does not adjust. Try scroll to see top or bottom of modal

## Your environment 🌱

- Open mSupply Version: v2.3.0 RC5 APK

**Comment by andreievg** [comment]
Not usable, should fix with useKeyboardHeight hook. 

This is reoccurring issue, should fix at the root at some point, would suggest creating another issue from this one to go into refactor week as high priority

**Comment by lache-melvin** [comment]
Closed by #5010

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
