### ISSUE TITLE
Notification prefs wording fix

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4997]
## What went wrong? 😲

![Screenshot 2024-10-04 at 12 54 54 PM](https://github.com/user-attachments/assets/86c74d5b-0673-4f2b-bd44-1f89e1482823)

## Expected behaviour 🤔

Should be: "less than 3, or more than 6 months of stock"

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports
2. Click the More button

## Your environment 🌱

- Open mSupply Version: v2.3.0 RC5

**Comment by andreievg** [comment]
Quick to fix so lessgo

**Comment by roxy-dao** [comment]
Closed in #5008

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
