### ISSUE TITLE
Can't initialise because of missing VaccineCourseItem

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4999]
## What went wrong? 😲
I added some vaccine courses in an OMS central server and tried to initialised a remote site, but get this error message.
![photo_2024-10-04 14 33 47](https://github.com/user-attachments/assets/a698a78c-931a-4f8c-978a-3e043460254f)

## Expected behaviour 🤔
Should be able to initialise with correct data

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.3.0-RC5
- Legacy mSupply Central Server Version:

- Platform: browser central and android remote

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5012

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.6.1-RC5`



- [X] Create a vaccine course, with at least one vaccine item - save
- [X] Reopen vaccine course, remove the vaccine item - save
- [X] Initialise a remote site
- [X] Should initialise fine 🚀 

Just reinitialised my remote site after adding a few vaccine courses - initialises fine! Moving to Done ✅
