### ISSUE TITLE
Can enter meaningless time intervals between doses in vaccine card

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5001]
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to immunisation programs > vaccine card
2. Select multiple doses
3. Choose a high number of days for time interval between doses

![Screenshot 2024-10-04 at 4 15 49 PM](https://github.com/user-attachments/assets/ab282265-0192-4c57-876f-7180a0b53de9)

## Your environment 🌱

- Open mSupply Version: 2.3.00-RC5 - Central Server
- Legacy mSupply Central Server Version: 

- Platform: On samsung 2.3.00-RC5, but no different to desktop

- Database type:

**Comment by lache-melvin** [comment]
Recommending to triage team to close this one - yep you can enter wild intervals, but I think worse to set some kind of limit (some vaccines might have really long time between doses?)

These inputs are only available on Central, configured once, I think we can trust them to enter valid intervals

**Comment by andreievg** [comment]
Triage agrees
