### ISSUE TITLE
Alternate colours in reports as it is hard to read the rows

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#5006]
## Is your feature request related to a problem? Please describe 👀
<img width="1392" alt="Screenshot 2024-10-07 at 8 23 54 AM" src="https://github.com/user-attachments/assets/ae40ea2a-bab8-4704-a02f-886d7d719809">

alternate colours of each row so that it is easier and quicker to visually read what each row is without having to use a ruler do some kind of sorcery to differentiate

by each row I mean like this
<img width="618" alt="Screenshot 2024-10-07 at 8 25 05 AM" src="https://github.com/user-attachments/assets/3243a88a-d677-4ed3-a88a-caab9e07dbbc">

**Comment by mark-prins** [comment]
The designs have row borders / dividers:

![image](https://github.com/user-attachments/assets/6dbac557-be43-4b89-9db2-974e8886f048)

can these be implemented please - could be at the same time at #4771 

The original intention was for reports to use the standard table components which would have given us the alternating row colours. Now that we have the interim solution using an iframe we need to consider styling

**Comment by AnushaUp** [comment]
Tested [HERE](https://github.com/msupply-foundation/open-msupply/issues/5411). PASSED
