### ISSUE TITLE
Improve sort order for stock details report

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#5007]
## What went wrong? 😲
<img width="1411" alt="Screenshot 2024-10-07 at 8 29 26 AM" src="https://github.com/user-attachments/assets/e8dd121e-e28c-429e-93ae-705219d5182d">

not sure how this is sorted. would have thought usually by AZ item?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
There was an update to reports which has caused reports to fail to update. The changes in this issue are there, but you will probably have to wait until actual 2.4 RC to test them. Please put any report issues in the backlog until then

**Comment by AnushaUp** [comment]
Looks good in `V2.4.0-RC2`
