### ISSUE TITLE
Can give wrong vaccinations if patient has been fetched from another facility

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5014]
## What went wrong? 😲

I have a patient with a vax card in this state:
![Screenshot 2024-10-07 at 10 53 13 AM](https://github.com/user-attachments/assets/7e294e46-3f89-468d-b7e0-a11ce2f983a7)

Then in another store, another site, I fetch that patient. 

In that store - vax card looks like this:
![Screenshot 2024-10-07 at 10 53 40 AM](https://github.com/user-attachments/assets/d1139588-4a4f-4869-b4ca-2e127c6e0c54)

## Expected behaviour 🤔

This is to be expected, in that fetching/syncing of vaccination records between stores is out of scope for 2.3.

However, user at store 2 could now unknowingly give a second round of all the doses to the patient, and that would be bad.

We should somehow disable the card for the second store, until syncing around of vaccination records is in place.

## How to Reproduce 🔨

See above

## Your environment 🌱

- Open mSupply Version: v2.3 rc5
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by regotaina** [comment]
@lache-melvin this may happen with prescriptions too... Would minimum interval between vaccines be 'enough time' for the other store to sync?

I wonder if last Sync time displayed could be useful, but I guess it doesn't show up in other menus... it can be confusing.

**Comment by lache-melvin** [comment]
Closed by #5027

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.1-RC5`

- [ ] You'll need the [latest enrolment JSON schema](https://github.com/msupply-foundation/programschemas/blob/immunisation-programs/immunisation_program/generated/immunisation_program.json)
- [ ] Enrol a patient in the immunisation program
- [ ] Fetch that patient from another site
- [ ] Ensure that in the first store, you can see the vax card
- [ ] In the second store, vax card is hidden
