### ISSUE TITLE
Add a dose wording strange on vaccine card modal

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5016]
## What went wrong? 😲

Maybe subjective but I think the "add a dose" wording is unnecessary at best and confusing at worst!
I feel like clicking the text should either do the same as the button, or it shouldn't be there.

![add a dose wording strange](https://github.com/user-attachments/assets/5999f7f1-f566-4aa1-9df0-f3fc6664b53b)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to immunisation programs and open edit vaccine course modal
2. See text

## Your environment 🌱

- Open mSupply Version: 2.3.0

**Comment by roxy-dao** [comment]
Can say "There are currently no doses for this vaccine course. Click `+ Dose` to add a dose" Or something similar ~

**Comment by lache-melvin** [comment]
quick fix along with #5003

**Comment by lache-melvin** [comment]
Closed by #5039

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
