### ISSUE TITLE
Encounter status not matching vaccine given status

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5017]
## What went wrong? 😲

Some confusion for me about encounter status vs vaccine given status.

When a patient has an encounter and are given vaccines, the status of the encounter does not change by default and remains as pending. This means that even if a patient is given all of their vaccines, they will still show as 'encounter missed' in the list view unless changed manually.

Maybe this is the desired workflow, but I found confusing when I was testing!

See patient who made their appointment and was given some vaccines but still showing encounter missed:
![Screenshot_20241007_121746_Open mSupply](https://github.com/user-attachments/assets/e2c6b185-88fa-4761-afdb-d1181a2bfdf8)
![Screenshot_20241007_121757_Open mSupply](https://github.com/user-attachments/assets/03655afa-35ad-4ed2-8a16-c2cc21691bff)

This is the same even if all vaccines in their program are given:
![Screenshot_20241007_122304_Open mSupply](https://github.com/user-attachments/assets/68d90a79-3b55-4c8c-a06f-20f67d1b12f1)

![Screenshot_20241007_122313_Open mSupply](https://github.com/user-attachments/assets/f396c242-6a05-472a-bb2b-ecf7164bf230)

## Expected behaviour 🤔

Show encounter as attended if vaccines are given? Or some way to avoid manual updating encounter in this case.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Encounters
2. Add an encounter and record all vaccines as given
3. Go back to list view and see encounter still missed

## Your environment 🌱

- Open mSupply Version: 2.3.0

**Comment by regotaina** [comment]
I thought there were no triggers to change the status, as you can flag vaccines that were given in the past or out of the current store

@fergie-nz agree it can be confusing.

**Comment by adamdewey** [comment]
I think ok to have encounter and vaccine status non-aligned. 

Encounter status should be more a 'near-sighted' focus and centered on whether the patient is reliably turning up to scheduled visits (not just for vaccines)

Vaccine status should be a 'long-sighted' focus centered on the patient over their lifetime

Could potentially do some streamlining to help the facility to maintain their encounter list, but priority should be given to maintaining the patient's lifetime vaccine record I think.

**Comment by lache-melvin** [comment]
Closing per Adam's comment above, the two statuses are serving different purposes. Thanks for raising Ferg 🙏
