### ISSUE TITLE
Create Ledger Issue of Available Stock with backdated Prescription

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5022]
## What went wrong? 😲

I can't quite work out if the UX problem above is related to a bug that breaks my ledger. I think the backend is getting different updates to what is ultimately on the frontend, and "available" stock is getting updated incorrectly and irrecoverably through UI. On a **back dated** prescription (if it's current dated it seems fine. What if it's just an __older__ prescription? Should that be treated as essentially the same as a back dated prescription? Hmmm) when you modify quantities on a line that already had a quantity, it appears to adjust the stock line's available quantity down irrecoverably. Even setting issued to 0, it will not return to the baseline available. Doing it repeatedly will trend available further downward. The second line in the video I have churned lot - the available quantity should 458, not 88! Likewise the top line should have returned to 292, but is at 269. Changing the date does not fix this. Nor does deleting the line or even the whole prescription, so this is certainly the stock line irrecoverably adjusted:

https://github.com/user-attachments/assets/2bf42f58-2216-49cf-915a-e2c9b2300004

![Screenshot_20241007_144316_Open mSupply](https://github.com/user-attachments/assets/3008c329-885b-4b9f-b929-5fac71ca8071)

![image](https://github.com/user-attachments/assets/8bdb24f1-084c-4e07-90c1-f133a92a4975)

![image](https://github.com/user-attachments/assets/5242d21a-f0ea-49ab-8e09-f1e089ed811e)

![image](https://github.com/user-attachments/assets/220e41c6-6357-4a66-b039-8c1d79922049)

If I could guess, I'd guess these bugs are from 2 footguns in react:
1. not using prev state when updating state
2. useEffect race conditions making lots of rerenders and state jumping around.

Also, if the F/E is handling updating of available then I think that is wrong - the backend should be responsible at least for the final numbers. 

## Expected behaviour 🤔

There should be no ledger problems created by updating the quantities issued on any prescription, current or backdated.

## How to Reproduce 🔨

1. Have a back dated prescription and a stock line with some good history data. Ideally with days between adjustments and an adjustment today adding some amount, say 50. (In my datafile I have multiple stock lines however IDK if having multiple stock lines for the item is a prerequisite, consider it if you can't reproduce)
2. In the back dated prescription add that line and set the quantity to available and OK
3. Edit the same line and reduce it and press OK
4. Again but increase it some amount and press OK
5. Repeat 3 and 4 chaotically until the available amount starts decreasing erratically
6. Check ledger back on OG to confirm damage.

## Your environment 🌱

- Open mSupply Version: 2.3.0-RC5 apk on Samsung Tab A8 SM-X200
- Legacy mSupply Central Server Version: `master` on 7.17.15.
- OMS Central: `develop` on 2.3.0-RCX

- Database type: sqlite

**Comment by lache-melvin** [comment]
`an adjustment for today` appears to be the kicker 👀 I think this is pretty critical to resolve before release!

**Comment by roxy-dao** [comment]
Closed in #5116

**Comment by marthakeezy** [comment]
V2.3.0 has been released so moving to Done ✅
