### ISSUE TITLE
Hidden items are appearing in item usage and stock details reports

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#5025]
## What went wrong? 😲

Hidden items are appearing in item usage and stock details reports. 
<img width="1024" alt="Screenshot 2024-10-07 at 10 09 02 PM" src="https://github.com/user-attachments/assets/fea8b1b5-febf-4efb-93e5-5b92a5b75f7e">

## Expected behaviour 🤔
If item is hidden it is probably not meant to be ordered etc. Would expect it to not be showing.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Triage, need to double check and validate. Items in screenshot looks like they were created in integration tests

**Comment by richardmoizeau** [comment]
Hello - just had the same issue on a customer's demo server - I could see all items in the reports, including invisible ones. Expect to see only the items visible to the store.

**Comment by roxy-dao** [comment]
Closed in #5730
