### ISSUE TITLE
The issued stock value on a Requisition gets adjusted before the Outbound Shipment is confirmed

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5033]
## What went wrong? 😲

Scenario: my store receives a `Requisition` for an item I do not have in Stock

What's happening: I create an `Outbound Shipment` for this out-of-stock item and the Issued stock value on a Requisition gets adjusted even though we are not issuing anything. The Requisition can also be finalised after that.

## Expected behaviour 🤔

Requires further discussion :) At the moment, it is misleading

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have 2 stores to recreate the environment: one is a **Supplier** and one is a **Customer**
2. From a **Supplier** store, create an `Internal Order` for the **Customer store** for an item Customer store does not have in stock
3. Customer store receives the `Requisition`
4. Create an `Outbound Shipment` from this Requisition -> this will bring you to another window
5. Revisit your Requisition -> see Issued adjusted even though we do not have the item in stock. Error!

## Your environment 🌱

- Open mSupply Version: `V2.3.0-RC6`
- Legacy mSupply Central Server Version: `V7.17.10`

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by andreievg** [comment]
Triage, update docs to reflect behaviour in the doc description: `The quantity that has already been issued in Outbound Shipments`

**Comment by mark-prins** [comment]
Discussed briefly at triage - I think this is a problem of nomenclature. we thought that it is behaving correctly, but we need to tell the user that the stock isn't issued per se, it's recorded on an invoice.

**Comment by marthakeezy** [comment]
Confirmed the issue is parked for now... Moving to Done to clear out the QA board, however should be pretty easy to find if testing is needed! ✅
