### ISSUE TITLE
Hardware id to be fetched from memory

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#5053]
## Is your feature request related to a problem? Please describe 👀

We had an issue on a server that caused service to quit and then fail to start, this is the log file.

https://drive.google.com/drive/u/1/folders/15L6VLXbC6SCWUbL-qKy4ZcZGAhrhia4d

In the log file it look like panic around app data (when fetching hardware id), which happens on startup and in synchroniser (a bit puzzled why so many logs for the synchroniser, that doesn't cause the app to quit, if it's protected from panic since it's on it's own thread that makes sense, but why does the service quit in the end), on startup it makes sense as there is a sync operation in main thread.

After app data file is deleted, service manage to start (new app data file is created as expected)

## Describe the solution you'd like 🎁

Fetch hardware id from memory, look it up on startup

**Comment by lache-melvin** [comment]
Closed by #5054

**Comment by marthakeezy** [comment]
Passed the test ✅  Moving to Done
