### ISSUE TITLE
Report descriptions

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5056]
## Is your feature request related to a problem? Please describe 👀
There is currently no way to see what the data in the individual reports are for and what the columns mean.

## Describe the solution you'd like 🎁
Add `How to read { report name } report? >` link that expands in the `App Bar` (see screenshots below and login error for implementation). This should show the column descriptions on expansion see [expiring items README](https://github.com/msupply-foundation/open-msupply-reports/blob/main/standard-reports/expiring-items/README.md), [item usage README](https://github.com/msupply-foundation/open-msupply-reports/blob/main/standard-reports/item-usage/README.md) and [stock status README](https://github.com/msupply-foundation/open-msupply-reports/blob/main/standard-reports/stock-status/README.md) for descriptions.

![photo_2024-10-10 08 25 18](https://github.com/user-attachments/assets/5136278c-65c4-45ab-a5e0-01299f478802)
![photo_2024-10-10 07 44 33](https://github.com/user-attachments/assets/4b06c2bb-f854-4737-8cc2-3d7889e240b2)

### Moneyworks Jobcode 🧰
OMS:REPT

**Comment by marthakeezy** [comment]
Tested in V2.4.0-test1, descriptions appear :) Build test passed ✅
