### ISSUE TITLE
Can enter meaningless numbers in Distribution -> Requisitions

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5063]
## What went wrong? 😲

When entering quantities to supply under Requisitions, users seem to be able to enter meaningless numbers that are higher than their Stock on Hand figures. Is being able to issue a Requisition with numbers higher than what you have in stock intentional? What are some real-life examples where this feature would be useful?

Also, in Supply column, you cannot see the full number although I'd argue anyone will ever issue millions of one specific item. 

<img width="801" alt="1" src="https://github.com/user-attachments/assets/68a0d3f5-43d7-493f-9077-01b9da0b732f">

## Expected behaviour 🤔

I think the quantity to supply cannot be higher than what a facility has in stock -> therefore users should be limited in their number input.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have 2 stores -> a Supplier Store and a Receiver Store
2. Create an Internal order from your Supplier Store to your Receiver Store. Make sure it's for an item that has stock.
3. Receiver Store now has a Requisition. Try issuing quantity that is way higher than what you have in stock.
4. The system allows that - unclear why?

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC6
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (Android)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Based on Dhanya's comment in Telegram earlier this week:

```
You are saying how much you would plan to supply once you have stock.
```

i.e. supplying store might be waiting for an inbound of their own to arrive, don't have the stock on hand yet but they will

So am going to close this one 🙏
