### ISSUE TITLE
Translations for report print not working

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5064]
## Is your feature request related to a problem? Please describe 👀
Currently, we have report [translations for UI](https://github.com/msupply-foundation/open-msupply/issues/4677), but no translations when the user prints or exports to a PDF or excel. 

## Describe the solution you'd like 🎁
Make sure print report translations are working

### Moneyworks Jobcode 🧰
OMS:REPT

**Comment by AnushaUp** [comment]
Tested [HERE](https://github.com/msupply-foundation/open-msupply/issues/5411). PASSED
