### ISSUE TITLE
Default log level on windows service should be `Info`

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5070]
## Is your feature request related to a problem? Please describe 👀

It looks like our installations are going out with a default Log Level of `Warn` I'm not sure if this is in the installer?

## Describe the solution you'd like 🎁

We should be logging a `info` level as a default. This means we'll see things like running migrations in the logs rather then nothing when the server starts up.

**Comment by marthakeezy** [comment]
Tested by Kahn -> moving to Done :)
