### ISSUE TITLE
The footer says that I have store properties but when I edit there are none

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5074]
## What went wrong? 😲

There's this in the footer:
![image](https://github.com/user-attachments/assets/8d2236c6-e876-45d2-94cb-21fb47f84c94)

which brings up this:
![Screenshot 2024-10-10 at 5 30 01 PM](https://github.com/user-attachments/assets/01d09dbe-bd77-48b9-b56f-ac8fe3730403)

Now, the footer should only have the edit icon when I have properties to edit.
If I log in to central and edit the same store, I see this:

![Screenshot 2024-10-10 at 5 30 06 PM](https://github.com/user-attachments/assets/a5b4b617-50bb-4370-88a1-ef593ea65ec5)

## Expected behaviour 🤔
The edit button should give me properties to edit

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to the demo server
2. Click on the edit button in the footer

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
I wonder if related to this? #4651 Needs to be done for GAPS requirements 👀

**Comment by lache-melvin** [comment]
I think this might actually be completed/a duplicate of #4647 -- confirming and then will close

**Comment by mark-prins** [comment]
confirmed! working now

**Comment by marthakeezy** [comment]
Tested in #4647 - moving to Done ✅
