### ISSUE TITLE
Outbound shipment: Can issue the expired stock

### ISSUE THREAD

**Issue by bijaySussol** [msupply-foundation/open-msupply#5078]
## What went wrong? 😲

Can issue the expired stock, the control works perfectly on Issue field but not from the stock line. could be expected behaviour but seeing 2 functionality for the same stock line is odd while issuing out the stock aka outbound.

## Expected behaviour 🤔

TBD, but both functionality should be behaving similar.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Prepare the stock line that is already expired
2. Create new outbound (Customer invoice)
3. Select that line
4. Use Issue field > says "stock line with expired cannot be issued", perfect
5. Select the qty from the batch line, it allow to issue the stock

Is open msupply trying to mimic [this](https://docs.msupply.org.nz/preferences:invoices#disallow_issue_of_goods_with_short_expiry) preference from desktop with batch line?

## Your environment 🌱

Open msupply demo

- Open mSupply Version: 2.2.01
- Legacy mSupply Central Server Version: Not sure
- Platform: Desktop, Google chrome
- Database type: Not sure

NOTE: Why is open mSupply allows to enter expiry date of the stock line that on past date when cannot be issued out?
Saying hello to all through this.

**Comment by lache-melvin** [comment]
My assumption was that we don't auto-allocate expired stock, but you could issue it explicitly, if you felt so inspired. Will leave for triage team for decision though 🙏

**Comment by andreievg** [comment]
Product discussion suggested it's within the norm of expected behaviour, closing for now. @bijaySussol thanks for the catch though : )
