### ISSUE TITLE
New Requisition line fields

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5088]
## Is your feature request related to a problem? Please describe 👀
Manual requisitions will need new fields which currently don't exist

## Describe the solution you'd like 🎁
1. Add the following fields to the Requisition line table: 
Note: All fields should be optional

| Column | Description | mSupply column |
| -- | -- | -- | 
| initial_stock_on_hand_units | Stock on hand on the date of the start of the program | Cust_prev_stock_balance |
| incoming_units | - | Cust_stock_received | 
| outgoing_units | - | Cust_stock_issued | 
| loss_in_units | Inventory Adjustment | stockLosses |
| addition_in_units | Inventory Adjustment | stockAdditions | 
| available_units | F = initial stock on hand + incoming stock + IA - outgoing stock. NOT EDITABLE | Available |
| expiring_units | sum of available stock for the item which has an expiry date after date of program | stockExpiring |
| days_out_of_stock | calculation target (Target MOS (months max stock + monthly lead time) * AMC) - available stock | days_out_or_new_demand |
| months_of_stock | - | MOS | 
| option_id | FK option table | optionID |

2. Update service + graphql requisition line endpoints with these new fields
3. Sync new fields

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by Chris-Petty** [comment]
@roxy-dao on the theme of differentiating pack or unit count for quantities, I reckon good to capture in the field names much like other areas of OMS we tried to do better than OG?

I'm pretty sure all of these are in units yea?

**Comment by roxy-dao** [comment]
> @roxy-dao on the theme of differentiating pack or unit count for quantities, I reckon good to capture in the field names much like other areas of OMS we tried to do better than OG?
> 
> I'm pretty sure all of these are in units yea?

long column names ok? I don't believe we've done this in backend, only in frontend translations

**Comment by Chris-Petty** [comment]
Ya we do, it's just usually "per_pack" or "number_of_packs"
https://github.com/msupply-foundation/open-msupply/blob/46efc9a10ed036d22798f188cc59474d718c3c9d/server/repository/src/db_diesel/invoice_line_row.rs#L68-L93

Where as here we're talking "unit", much like:

https://github.com/msupply-foundation/open-msupply/blob/46efc9a10ed036d22798f188cc59474d718c3c9d/server/repository/src/db_diesel/master_list_line_row.rs#L30-L31

soooo basically suggestion one or the other of

```
units_initial_stock_on_hand
units_incoming_stock  
units_outgoing_stock  
units_lost
units_added  
units_available_stock  
units_expiring  
days_out_of_stock  
months_of_stock  
option_id

initial_stock_on_hand_units
incoming_stock_units
outgoing_stock_units
lost_units
added_units
available_stock_units
expiring_units
days_out_of_stock  
months_of_stock  
option_id
```

**Comment by roxy-dao** [comment]
AndreI: If we want to rename columns now, make a refactor issue for this to rename existing columns too or else we will have 3 different patterns.

**Comment by Chris-Petty** [comment]
ya KNOW what - I understand what you meant now @roxy-dao ye the rest of the columns in `requisition_line` are assumed unit quantity, so fair to assume additional fields are in unit quantity too!

**Comment by roxy-dao** [comment]
> ya KNOW what - I understand what you meant now @roxy-dao ye the rest of the columns in `requisition_line` are assumed unit quantity, so fair to assume additional fields are in unit quantity too!

I've updated, thoughts?

**Comment by mark-prins** [comment]
I prefer the column_name_{units/packs} format - an order of priority of uniqueness with the most valuable info first

**Comment by Chris-Petty** [comment]
Me too and prefer plural

**Comment by roxy-dao** [comment]
Done and done.
