### ISSUE TITLE
Quitting report filter givings eternal loading on top of existing loaded report

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5090]
## What went wrong? 😲
Could possibly be from #4991 change. 

https://github.com/user-attachments/assets/04040454-634b-4ca8-8b4e-ed4bda0abf41

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a report
2. Click on the filter button
3. cancel
4. See loading

## Your environment 🌱

- Open mSupply Version: 2.3-RC8
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5097

**Comment by marthakeezy** [comment]
Tested in V2.3.0-RC9 - passed ✅
