### ISSUE TITLE
Import GAPS data

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5100]
## Is your feature request related to a problem? Please describe 👀
"something extra I think we need to do for GAPS to be a success is to create a standard PQS vaccine item variant catalogue that can easily be loaded into the system at the central level and that has all the necessary data there ready for use in the calculations - e.g. volume per dose, temperature range etc.

I think it would be a tall order to expect the central level to gather all the information they need so would be good to smooth the path for them

There is a tab in the WHO IGA spreadsheet with all the information already there, hopefully there's a way we can it bundle along with the Open mSupply installer?"

Agree that this would be useful -  though there's no funding for the change. Raising an issue so that we can discuss with the triage team.

**Comment by craigdrown** [comment]
Hello Hello. It's Craig the broken record.
The OG table "barcode" has fields "barcode" (surprise!), itemID, manfacuturerID, packSize, parentID (another variant that is the outer pack for this variant).
By adding something like "tradeName" & etc we have a variants table- just concerned we'll create a new table and it will be effectively a duplicate. Thank you and good bye.

**Comment by lache-melvin** [comment]
Hey @craigdrown - @andreievg and I caught up about this yesterday, we were a bit concerned about conflating barcode and item_variant at this stage, given the understanding that "Item Variants" might also be used at a higher level i.e. just variant of pack size, where barcode/manufacturer aren't really applicable?

**Comment by craigdrown** [comment]
@lache-melvin you'd have to explain that to me in person- thanks!

**Comment by lache-melvin** [comment]
Can this also serve as the issue for broader OMS side of GAPS setup script 🙏

**Comment by lache-melvin** [comment]
Keeping open until actual import of data is done 😅

**Comment by lache-melvin** [comment]
closed by #5450
