### ISSUE TITLE
Inbound shipments: there is no 'Transport details' field on manual inbounds

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#5103]
## What went wrong? 😲

In Inbound Shipments, if you are using .APK and click on 'More' on the right side, you will not have the option to add Transport details, as per picture below:

![Screenshot 2024-10-14 at 3 15 03 PM](https://github.com/user-attachments/assets/3e020522-34f3-42c1-b931-861358250e0b)

If you are in the browser and click on 'More' on the right side, you will have the option to add Transport details, as per picture below:
![Screenshot 2024-10-14 at 3 13 29 PM](https://github.com/user-attachments/assets/cf99045a-ccd5-4fc3-a56f-fc64c861001c)

## Expected behaviour 🤔

Transport Details should be available in .APK

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inbound Shipments'
2. Click on 'More'
3. Scroll down to 'Transport Details'
4. See error - the option is not there

## Your environment 🌱

- Open mSupply Version: V2.3RC8
- Legacy mSupply Central Server Version:

- Platform: Android

**Comment by mark-prins** [comment]
I've just tested on v2.2.02 and the details show in the apk. 
Could it be that the tablet is on an older version @regotaina ?

**Comment by lache-melvin** [comment]
I have transport details on RC8 APK.. 👀 However, you only see transport reference on an Inbound Shipment if it was created via transfer from another store, manual inbounds don't have it - is that what happened here? 🙏

**Comment by regotaina** [comment]
@mark-prins I think Lache is right, it doesn't show up if it's manually created. But in theory this may still be recorded, right? Not sure if it's only valuable for the supplier store, not the customer one.
Def using RC8 here :) 
> I have transport details on RC8 APK.. 👀 However, you only see transport reference on an Inbound Shipment if it was created via transfer from another store, manual inbounds don't have it - is that what happened here? 🙏

**Comment by lache-melvin** [comment]
Will leave with triage team, if we want to show transport details section on manual inbound shipments

**Comment by andreievg** [comment]
This is expected for now, will update docs: https://github.com/msupply-foundation/msupply_docs/issues/114

For future we might want to add transport details to manual
