### ISSUE TITLE
Android: Instead of being logged out after time out,  'Authentication error' appeared on the screen

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#5104]
## What went wrong? 😲

After minutes of inactivity, instead of being properly kicked out of the system, the message 'Authentication error' kept coming back.
Could not click on any other areas, despite having all permissions on.

Sync was still working, I got a video below:

https://github.com/user-attachments/assets/ec5d284f-9273-4eed-96ed-c0b4b064f761

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Login on tablet
2. Wait for 10 minutes 
3. Go back to tablet and try to click on any menus
4. An error message will pop up on the screen saying "Authentication error'.

## Your environment 🌱

- Open mSupply Version: 2.3.0 RC8
- Legacy mSupply Central Server Version: V7.17

- Platform: client/Android

**Comment by marthakeezy** [comment]
Also #3967

**Comment by lache-melvin** [comment]
Ah thanks Maria! Will close this one as a dupe 🙏
