### ISSUE TITLE
V2.3.0 Release Testing: R&R Forms

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#5117]
# 🧪 Testing

OMS version: V2.3RC8
mSupply version: V7.17
Platform: Desktop app/android

# R&R Forms
SETUP: 
1. You'll need to enable the `Open mSupply: Uses program module` store pref in mSupply
2. You'll need at least one master list configured to be visible in your store, which is a program master list
3. You'll need at least one period schedule with some periods configured - and the period schedule to the master list under the `Program settings` tab
4. In Open mSupply UI, go to Replenishment > R&R Forms
5.  Ensure there has been some activity for the items in your master list during the period you are creating the R&R form for
  a. Have transactions on the days bordering the start/end of the period to confirm values are captured correctly!
6. Add the [R&R Form report](https://github.com/msupply-foundation/open-msupply-reports/tree/main/clients/East-Timor/r-and-r-form) into mSupply (or upsert into omSupply using the new script)

TEST:
- [x] Go to `Replenishment` > `R&R Forms` to view the list of R&R forms.
- [x] There is a list of R&R forms available (this will be empty the first time)
- [x] It is possible to sort the R&R list view (Sort done, filter TODO)
- [ ] It is possible to export the list as a excel sheet file ( csv file TODO)
- [x] You can create a form. Clicking the create modal opens a modal:
  - [x] If you only have one program, it should be auto-selected. If you have more than one, nothing is preselected.
  - [x] Once program is selected
    - [x] If you only have one schedule for that program, it is auto-selected. If you have more than one, nothing is preselected.
    - [x] You can select any period in that schedule (but only for periods that are in the past)
  - [x] Supplier is not pre-selected
- [x] Click create
- [x] You are redirected to a detail view, which is an editable table
- [x] The form is pre-populated with values from Open mSupply: this is for values of Initial Balance, Received, Consumed, Adjustments, days out of stock, expiry (the expiry date of the oldest expiring batch of that item)
- [x] Adjusted consumption is correctly calculated based on number of days out of stock `Consumed x Days in period / Days in stock` (e.g. for period of 1 month (30 days) consumption was 20 units, but stock out was 10 days, so adjusted consumption would be 30 units)
- [x] Losses/adjustments made for this item during the period. Can be positive or negative. Populated by data from Stocktakes or Inventory Adjustments
- [ ] Stock out duration: Number of days in the period where stock on hand for the item was 0
- [x] Final balance: Stock on hand for the item at the end of the period. Calculation is Initial balance + Received - Consumed + Adjustments
- [x] AMC correctly calculated as average of the adjusted monthly consumption for the last 3 periods
- [x] Maximum = 2*AMC
- [ ] Expiry: Expiry date of the earliest expiring available batch of this item
- [ ] Requested: Quantity to be requested in the requisition [ Calculated as Maximum - Final balance], but you can edit this value.
- [ ] Low Stock: This sign is showing when stock is low. ![Screenshot 2024-08-16 at 11 57 47 am](https://github.com/user-attachments/assets/0369b832-94da-427f-a370-1355e27c1c5a)
- [ ] Comment: You can add any comments to the line as needed
- [ ] Confirmed: Use this column can be use to keep track of which lines are complete. Acts as the save button for changes to a line.
- [ ] Approved Quantity: The quantity approved to be order from the remote authorization
  - [ ] setup remote authorization
  - [ ] Approve the quantities and check it is syncing back to oms site.
![Screenshot 2024-08-21 at 12 26 46 pm](https://github.com/user-attachments/assets/cf6f128f-2a6b-4f2b-9fc2-09d7aa79cec6)
- [ ] You can edit the white cells
  - [ ] You can refresh the page to reset your changes
  - [ ] You can click the `confirm` check box to save you changes to a line
  - [ ] You can't finalise the form until all lines are confirmed
- [ ] Once all lines are confirmed, you can finalise the form
  - [ ] You can no longer edit the form
  - [ ] An Internal Order has been created for the lines that you requested quantities for
  - [ ] The Response Requisition was created in the supplying store
- [ ] It is possible to print the R&R form
- [ ] It is possible to export the R&R form as an excel file
- [ ] Creating further R&R forms... click the create button on the list view
  - [ ] The program/schedule/supplier from the previous form are selected automatically, along with the next period in the schedule
  - [ ] If you didn't finalise the previous form, here is a warning that you need to finalise the previous form
  - [ ] After finalising the previous form, you can create the next one
  - [ ] You can only select the next period in the sequence
  - [ ] You can't select a previous period
  - [ ] After finalising the form for the last period available, you get a message that no more periods are available
- [ ] Also please ensure that you can: 
  - [ ] Create R&R forms for the same period schedule/period across different programs
  - [ ] Create R&R forms for the same period schedule/period and program in another store

**Comment by marthakeezy** [comment]
Closing & moving to Done due to capacity and releasing today ✅
