### ISSUE TITLE
Allow user to create manual requisitions

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5119]
Needs #5118 implementation done first. Link the api calls in frontend and allow users to create a manual requisition:

Step 1. Add a button to the requisition page to allow users to create new requisitions

![Screenshot 2024-10-15 at 8 16 53 AM](https://github.com/user-attachments/assets/ade9737b-2475-4841-a1c4-025067043243)

Step 2. Clicking the button should show up with the option to *Select Customer* 

### Moneyworks Jobcode 🧰
OMS:CIMDV

**Comment by andreievg** [comment]
Would need to look at program req modal to figure out how much extra work it is, estimate for now is for basic ui of adding requisition

**Comment by roxy-dao** [comment]
Broken program out in #5177

**Comment by alainsussol** [comment]
Tested as part of Epic testing See result [here ](https://github.com/msupply-foundation/open-msupply/issues/5089#issuecomment-2479340537)
