### ISSUE TITLE
Cannot delete lines - error message could be clearer

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#5128]
## What went wrong? 😲

found accidentally while testing remote authorisation.

In Requisitions received from a store, you cannot delete any lines. Expected behaviour. 
However message is currently "deleted response lines not yet implemented in API" which can be confusing for users.

<img width="360" alt="Screenshot 2024-10-15 at 2 24 11 PM" src="https://github.com/user-attachments/assets/40dc8975-3153-47b0-ba2d-d8b3a7f0763e">

## Expected behaviour 🤔

Possible alternative text like " you cannot delete lines of this requisition"

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create IO from Store A  to supplying Store B
2. Confirm sent
3. Login to Store B
4. Go to Requisitions
5. Try to delete any line from the requisition received form Store A
6. See error message

## Your environment 🌱

- Open mSupply Version: V2.3.0RC8
- Legacy mSupply Central Server Version: V7.17

- Platform: browser

**Comment by lache-melvin** [comment]
If deleting response requisition lines isn't supported yet, shouldn't we just remove the `delete selected lines` action from the UI?

**Comment by roxy-dao** [comment]
> If deleting response requisition lines isn't supported yet, shouldn't we just remove the `delete selected lines` action from the UI?

Should be implemented for manual requisitions though... in case someone does add a wrong line?

**Comment by lache-melvin** [comment]
> Should be implemented for manual requisitions though... in case someone does add a wrong line?

Ah great point! Maybe this one can be resolved as part of manual requisition work 🙏

**Comment by andreievg** [comment]
We shouldn't be able to delete lines in transfer requisition, so should hide that option. But yeah that option should be available in manual requisition, I think we can solve as part of manual requisition work

**Comment by alainsussol** [comment]
Will be tested as part of Epic testing. See Results [here ](https://github.com/msupply-foundation/open-msupply/issues/5089#issuecomment-2479340537)
