### ISSUE TITLE
Requisition line edit + UI updates to line columns

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5137]
The new fields implemented in #5088 need to be shown in the UI.

1. Hook up endpoint in #5190

1. Add columns as uneditable in the detail view - mockups due to change
<img width="677" alt="Screenshot 2024-10-16 at 7 25 35 AM" src="https://github.com/user-attachments/assets/a10ce463-3a7e-4682-b861-2eb41d115a26">

2. Add an Add Item button next to Supply Requested button

3. Add editable fields to the modal (screenshot below for new page)
![Screenshot 2024-10-22 at 10 20 32 AM](https://github.com/user-attachments/assets/a3d58899-29f7-423e-a079-ef8632a0835f)

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by alainsussol** [comment]
See Results of testing amidst the epic testing [here](https://github.com/msupply-foundation/open-msupply/issues/5089#issuecomment-2479340537)
