### ISSUE TITLE
Database changes for Item Variants (GAPS)

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5141]
## Is your feature request related to a problem? Please describe 👀

GAPS requires some item_variant features, completing this issue should implement the database changes needed for GAPS from this `item_variant` design.

There are several aspects of the GAPS work which require item variant capabilities
For reference this is the full [item variant PRD](https://docs.google.com/document/d/1fRZslRohRGaZnUo13a2eKZjfO0DGWwXtIFsbEah7A4Y/edit#heading=h.hyld495fuxe5)

We won't need all aspects of that; but we will need the ability to create and edit and sync item variants.

The variants will need to have these properties for the GAPS work:

| Name | Type   | Reference |
|:------ |:------ |:---- |
| Volume for different packaging levels | float | #3917 |
| Bundle items | reference to n item variants | #3923 |
| Temperature range | enum | #4368 |

See parent issue for more details...
https://github.com/msupply-foundation/open-msupply/issues/4789

## Describe the solution you'd like 🎁

2 new tables
```
    item_variant {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT temperature_range "ENUM(+5, -20, -70)"  
        FLOAT doses_per_unit 
        TEXT manufacturer_id
        DATETIME deleted_datetime
    }
    packaging_variant {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        INT packaging_level "used to distingush tertiary, primary, etc"
        FLOAT pack_size
        FLOAT volume_per_unit
        DATETIME deleted_datetime
    }
```

Add `item_variant_id` but not `packaging_variant_id` (YET) to open-mSupply`stock_line`, and `invoice_line`.

A separate issue  will be created to add `oms_item_variant_id` to legacy `stock_line`, and `invoice_line`.

How might this look in an example?

![image](https://github.com/user-attachments/assets/983bb065-e96e-416b-9533-40e090085bbd)

```mermaid
erDiagram
    item_link {
        TEXT id PK "NOT NULL"
    }
    item_variant {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT temperature_range "ENUM(+5, -20, -70)"  
        FLOAT doses_per_unit 
        TEXT manufacturer_id
        DATETIME deleted_datetime
    }
    packaging_variant {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT item_variant_id "REFERENCES item_variant(id) FUTURE"
        TEXT internal_packaging_variant_id FK "REFERENCES packaging_variant(id) FUTURE"
        INT pack_type "Box, Carton, Etc FUTURE"
        INT packaging_level "used to distingush tertiary, primary, etc"
        FLOAT pack_size
        FLOAT volume_per_unit
        DATETIME deleted_datetime
    }
    barcode {
        TEXT id FK "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
        TEXT packaging_variant FK "REFERENCES packaging_variant(id) FUTURE"
        TEXT barcode "UNIQUE"
        TEXT universal_code 
    }
    stock_line {
        TEXT id PK "NOT NULL"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
        TEXT packaging_variant FK "REFERENCES packaging_variant(id) FUTURE"
    }
    invoice_line {
        TEXT id PK "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
        TEXT packaging_variant FK "REFERENCES packaging_variant(id) FUTURE"
    }
item_link ||--o{ item_variant : ""
item_variant ||--o{ packaging_variant :""
packaging_variant ||--o{ packaging_variant : "internal_variant"
barcode ||--o{ item_variant : ""
barcode ||--o{ item_link :""
stock_line ||--o{ item_link : ""
stock_line ||--o{ item_variant : ""
invoice_line ||--o{ item_link : ""
invoice_line ||--o{ item_variant : ""
```

### Describe alternatives you've considered 💭

** Single Item Variants Table with packaging details **

After taking on board various feedback, and trying to design for future goals not just GAPS.
This issue suggests a item_variant table closer to the original design in the PRD.

**Item Variant**
```
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT internal_item_variant_id FK "REFERENCES item_variant(id) NOT NEEDED FOR GAPS"
        TEXT temperature_range "ENUM(+5, -20, -70)"
        INT packaging_level "used to distinguish tertiary, primary, etc"
        INT pack_type "Box, Carton, Etc NOT NEEDED FOR GAPS"
        INT num_units
        FLOAT doses_per_unit 
        FLOAT volume_per_pack
        FLOAT weight_per_pack "NOT NEEDED FOR GAPS" 
        TEXT manufacturer_id
```

How might this look in an example?

![image](https://github.com/user-attachments/assets/983bb065-e96e-416b-9533-40e090085bbd)

NOTE: In the gaps master data we have 7 different level 1 item_variants for BCG, once you include the secondard and tertiary packaging there'll be 21 rows of item variants for a BCG vaccine, which is a consideration I think...

You can see that doses_per_unit needs to be duplicated on every row but otherwise it looks relatively clean to me.

One issue I found creating this example is that existing GAPS master data has a volume per unit stored against secondary, tertiary etc. I might not have looked hard enough though...

My design has a volume per pack, as I was assuming that would be easier to get and deal with as a end user.
However maybe we store a `volume_per_unit` but allow users to enter the packsize and total volume to calculate this they want?

```mermaid
erDiagram
    item_link {
        TEXT id PK "NOT NULL"
    }
    item_variant {
        TEXT id PK "NOT NULL"
        TEXT name "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT internal_item_variant_id FK "REFERENCES item_variant(id) NOT NEEDED FOR GAPS"
        TEXT temperature_range "ENUM(+5, -20, -70)"
        INT packaging_level "used to distingush tertiary, primary, etc"
        INT pack_type "Box, Carton, Etc NOT NEEDED FOR GAPS"
        INT num_units
        FLOAT doses_per_unit 
        FLOAT volume_per_unit
        TEXT manufacturer_id

    }
    barcode {
        TEXT id FK "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
        TEXT barcode "UNIQUE"
        TEXT universal_code 
    }
    stock_line {
        TEXT id PK "NOT NULL"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
    }
    invoice_line {
        TEXT id PK "NOT NULL"
        TEXT item_link_id FK "REFERENCES item_link(id)"
        TEXT item_variant_id FK "REFERENCES item_variant(id)"
    }
item_link ||--o{ item_variant : ""
item_variant ||--o{ item_variant : "internal_variant"
barcode ||--o{ item_variant : ""
barcode ||--o{ item_link :""
stock_line ||--o{ item_link : ""
stock_line ||--o{ item_variant : ""
invoice_line ||--o{ item_link : ""
invoice_line ||--o{ item_variant : ""
```

**Add temperature ranges rather than enum?**
An enum is easy for gaps work, e.g. `-20` is separated out, but to make the system more flexible, and to potentially allow for more specific ranges for item variants we could replace it with `min_temperature`, `max_temperature` or potentially have both?

**Add code for item variants?**
Looks like there could be a number of variants for an item, would a code be helpful rather than a big long name?

**Store item variants in the barcode table**
I think logically this may well  make sense in the future, when all manufacturers have barcodes on items, and we have good support for 
However here's my arguments for not doing that now.

1. Having records in a barcode table with no barcode seems nonsensical!
2. Renaming barcode table to item_variant would have hard to understand consequences 
3. There's a lot of changes we'd like to make to barcode table which would be more difficult to manage with 4d & rust in the picture
4. There's potential for both a mSupply assigned and manufacturer assigned barcode for the same item. So having a 1 - many for this slight chance feels potentially helpful?

**Separate out packaging variants from item variant**
This was essentially allowing us to have one `item_variant` for say Pfizer Covid-19 Vaccine, which would then have different packaging options like `Container`, `Crate`, `Box`, `Tray`, etc.
I think the the addition of the `internal_variant` in the design we can achieve a similar goal without having the additional table involved adding additional complex it.
By adding the packaging_level to item variant, you can still query the table to find appropriate options at the facility level if defined (e.g. for gaps)

**item_variant proposed in original issue**
This records things like `volume_per_secondary_packaging` against an item variant.
While it might serve for gaps, doesn't cover off the use cases for item_variant in the [PRD](https://docs.google.com/document/d/1fRZslRohRGaZnUo13a2eKZjfO0DGWwXtIFsbEah7A4Y/edit#heading=h.hyld495fuxe5)
Such as being able to receipt into a store `45 Cartons` and the system would calculate the number of units etc automatically.

I think a little bit more work on now will pay off in the future!

### Additional context 💌

`num_units` is essentially `pack_size` I think?
I feel like this is more descriptive, especially if you're thinking of how many units is in a container or something, `pack_size` would be easier to miss-understand, like its it the how many boxes are in the carton or how many units are there?
Potentially `pack_size` would be correct for our environment though?

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by jmbrunskill** [comment]
FWIW, after doing that example, and seeing the current data available for GAPS, I'm thinking storing `volume_per_unit` is probably a good idea and we can how the total weight to users by multiplying. Slightly worried about calculation errors such as 20KG box showing as 20.002 but we can probably live with that?

**Comment by jmbrunskill** [comment]
I think `requisition` would have something like a `preferred_variant_id` or something when ordering??
I'm not quite sure what the design for that side should be, should the internal order say I want Pfizer Cartons? I assume it's ok for the supplier to substitute an alternative? but this part is a long way from what we're currently trying to solve so figure out of scope for now.

**Comment by adamdewey** [comment]
>This records things like volume_per_secondary_packaging against an item variant.
While it might serve for gaps, doesn't cover off the use cases for item_variant in the [PRD](https://docs.google.com/document/d/1fRZslRohRGaZnUo13a2eKZjfO0DGWwXtIFsbEah7A4Y/edit#heading=h.hyld495fuxe5)

We actually need volume per unit (primary packaging), secondary packaging and tertiary packaging for GAPS

**Comment by jmbrunskill** [comment]
@adamdewey in this scenario, we have all the different packaging levels as different variants.
This allows stock management to see the `Box of Vials` or `Outer Packaging` rather than having to receipt in 330 vials, they can receipt in 3 boxes instead.

I think it still works for GAPS too as we can query based on the packaging level to get the right `volume per unit` for the item and the store's primary packaging level. We can either take max, min or avg in our calculations to account for the variation.

This does mean more rows in the db though as you have all the packaging levels as different rows

**Comment by adamdewey** [comment]
@jmbrunskill   Ah ok..

Hmm, so we're sort of conflating item variants and packaging variant into the one row?

I thiiiink that's ok - can't quite think through the implications. 

FWIW the industry sometimes conflates them and sometimes separates, for example with GTIN barcoding: 

![image](https://github.com/user-attachments/assets/330b622c-9f13-4328-8943-151852a65b3d)

**Comment by andreievg** [comment]
I did a bit more research into barcoding and packaging, would like to have a chat about this. Would like to make a proposal, I think this diagram would help:

![item variant, packaging and barcodes](https://raw.githubusercontent.com/msupply-foundation/open-msupply/7c8224b756652e59f075b6ccbc092ec9c64e5b77/item-variant.drawio.svg)

Some other background:

GS-128 (the matrix style barcode) and GTIN-13/14 will have a GTIN which would be unique for lot, there is also identification about manufacturer. GTIN 14 should also have some identifier for packaging level (but we can't deduce pack size or packaging level from it really), whereas GS-128 might have another section for pack-size (quantity, section 37). There could also be multiple barcodes/matrix on the packaging, one from manufacturer and another from distributer. 

I think that barcodes is a separate table, and we can records manufacturer (company id), item, batch etc on the barcode and match it against a stock_line. Stock_line can be linked to a variant, but since it can have varying pack_size it shouldn't be linked to a packaging variant.

The barcoding stuff would require more explanation and discussion, for this piece of work thought I think we should use two more tables (item_variant and item_variant_packaging). doses_per_unit don't change for different packaging_variants and like i was saying pack_size can be user specific for stock and invoice line so good to keep them separate. 

Why not barcode links to packaging variant ? I think the pack size in the barcode is actually identifiable through the barcode itself (in GS-128 there is section 37, and from the docs it looks like), i haven't found examples of GTIN for secondary or tertiary packaging, but if it's deducible from the extra digit in GTIN14 that's great, otherwise we can add pack size on the barcode table when we can).

Conclusion, very similar to @jmbrunskill schema, except there is item_variant_packaging table, and stock_line, invoice_line is linked to item_variant vs item_variant_packaging.

**Comment by jmbrunskill** [comment]
Thanks @andreievg great to have these thoughts, would be good to chat in person/online. Don't need to reply here but capturing few thoughts.

I'm definitely open to a packaging variant table, was trying to simplify a bit with my approach, but maybe was too much.

> I think that barcodes is a separate table, and we can records manufacturer (company id), item, batch etc on the barcode and match it against a stock_line. 

Are you saying adding barcode_id to stockline? I don't see that in your diagram...

> Stock_line can be linked to a variant, but since it can have varying pack_size it shouldn't be linked to a packaging variant.
I thought a stock_line was linked to a pack size? Are you saying the associations between a pack variant and a stockline or stock movement can be made by assuming the packsize matches?
A stockline can only have one packsize right, so wouldn't it make sense to make sure that matches?
I would have thought we'd record the `Packaging Variant`on the stock line?

**Comment by mark-prins** [comment]
yes, thanks @andreievg! likewise - I'm just jotting thoughts after reading through. we can discuss in person

Similar question to James, I think - re the pack_size being in two tables. 

I'm not sure that having a `pack_size` on the packaging variant is helpful and it's a little inflexible when compared with entering a pack size when receiving stock. The PQS list of vaccines we have doesn't have pack size, just a doses count, and a volume for the three levels. For the GAPS calculations they use the level assigned to the facility to indicate the pack volume.

**Comment by craigdrown** [comment]
Thanks everyone- I'll try and stay out of it, but a couple of hopefully clarifying comments
1. barcodes would need to be at the packaging variant level AFAICT
2. requisitions shouldn't be specifying a variant - should be up to supplying store to choose (usually)
3. Some consideration of how our schema fits w universal codes would be good
4. presume "units" is an item property, and all variants use the same units (It is now).
  a. "doses_per_unit" is quite specific to vaccines - wonder if there is a more generic term - "subunits_per_unit" and "subunits" field that is "doses" for vaccines, but could be "grams" for creams (where the "units" is a tube)

**Comment by adamdewey** [comment]
> a. "doses_per_unit" is quite specific to vaccines - wonder if there is a more generic term - "subunits_per_unit" and "subunits" field that is "doses" for vaccines, but could be "grams" for creams (where the "units" is a tube)

Isn't that the same for vaccines though - as you could talk about `ml` but they simplify to `dose` ?

**Comment by adamdewey** [comment]
> barcodes would need to be at the packaging variant level AFAICT

Nice summary of barcodes and packaging here: https://tritonstore.co.nz/barcodes-for-different-levels-of-packaging/

**Comment by andreievg** [comment]
There is also this: https://www.gs1uk.org/knowledge-hub/product-identification/how-do-i-identify-packaging-levels

But I am struggling to find any examples of barcodes at packaging level, does anyone have examples of these (struggled to find through the google search too)

**Comment by jmbrunskill** [comment]
>"doses_per_unit" is quite specific to vaccines

I personally think this is fine, the place where we are interested in using the field is all vaccine related so it's nice if the columns in the database align with what you see in the UI. If a use case for subUnits Per Unit comes up. I'd prefer to cross that bridge when we come to it!

**Comment by jmbrunskill** [comment]
@andreievg DB Design & example is updated. Let me know if I've missed something.

**Comment by marthakeezy** [comment]
Checked the original issue and no testing required yet, so moving to Done ✅
