### ISSUE TITLE
Capture item variant on all incoming stock

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5145]
## Is your feature request related to a problem? Please describe 👀

- Add extra column with a dropdown input (before batch) anywhere stock comes in/changes:
  - Inbound Shipment
  - Customer Return
  - Stocktake
  - View stock detail
  - Inventory adjustment
  - Repack
- Add item_variant_id to stock_line, and probably invoice_line (mSupply change!) & sync

![Screenshot 2024-10-16 at 2 12 36 PM](https://github.com/user-attachments/assets/044698f5-8a31-45e3-a7c8-aa7f2676c275)

### Additional context 💌

At this point, we're just capturing the variant on the stock line to calculate current storage capacity used. i.e. we don't need to change anything with regards to distribution based on # packs per variant at this stage

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by marthakeezy** [comment]
# 🧪 Testing

Tested in V2.4.0-RC2 and as a feature testing

- [ ] Have some item variants configured for an item

For each of the below, try add and remove item variants:

- [ ] Create & edit customer return
- [ ] Create inbound shipment
- [ ] Create new stock line from View Stock
- [ ] Edit stock line from view stock

PASSED! ✅
