### ISSUE TITLE
Cannot backdate prescriptions - "stock not available" when it should be

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5146]
## What went wrong? 😲

Video attached -> [here](https://drive.google.com/drive/folders/1vVZi9r26J4W4NIYqGNyWa30mAjvphiHt). It's long and hefty but captures at least 3 errors?

- Stock of 878 should be available for today and yesterday. And it is! But requires a bit of a workaround, as on the Ledger you will be able to see 877 issued in a prescription. However the system returns errors when trying to issue that quantity.
- When there is an error, it should show up once and not have duplicates occurring at the same time
- Available quantity showed as double (timestamp 2:28)

What concerns me is if you set a smaller value (5 instead of 878), it works fine both ways. It’s only if you set a higher number issues occur both ways. 877 or 828 causes issues too. Only one stock line for the item I was testing (e.g. only one batch). 

Database files attached ->>> [here](https://mega.nz/fm/NEw0lBCT)

## Expected behaviour 🤔

Able to backdate prescriptions without random errors occuring.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Select an item that had some stock movement in the past, create an Outbound Shipment or a Prescription for this item for today.
2. Create a second prescription with that same item -> try to backdate it -> see if you run into same errors.
3. Might be quite hard to recreate so attaching my database above and in the video you can see an item I was testing. 

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC9
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Setting to Hotfix as IMHO this needs to be fixed before release?

**Comment by marthakeezy** [comment]
@jmbrunskill just played around with that item more, and the issue seems to occur when you enter values bigger than 465. Does that help? If I enter 464, it works fine, but as soon as it's 465+, all sorts of funky things start happening

**Comment by lache-melvin** [comment]
Haven't been able to replicate with demo data, though video is a bit confusing, maybe there are transactions missing from the ledger?? @jmbrunskill is looking into this from a copy of Maria's DB. Will put release on pause until he reports back with findings 🙏

**Comment by marthakeezy** [comment]
The video is a bit hefty, but basically the scenario is: 

Item had Inventory Adjustment yesterday, a few more transactions, and in total 878 items should be available to backdate or issue in a prescription. Smaller numbers (until 465) work fine, but as soon as it's 465-878, the errors start occurring. Not sure if it's helpful but I idendified the exact number when issues start occurring :)

Thanks James for looking into this one!

**Comment by marthakeezy** [comment]
Duplicating here after testing: 

1. Re-entering datetime picker after backdating the prescription prompts an error (the stock should be and is available)
2. I seem to be able to issue prescription with a batch that is on-hold

Prescription was created before the item was on-hold, e.g. I made changed to the item when the prescription was already picked but not yet verified

Along the same lines, if I change the batch's expiration date, the changes do not get reflected in the prescription

Not sure if this is expected behaviour!
3. Sometimes, you have to double-click on a specific date to select it.

**Comment by lache-melvin** [comment]
Closed by #5161

**Comment by marthakeezy** [comment]
V2.3.0 Released so moving to Done ✅
