### ISSUE TITLE
Prevent changing prescription date, once lines are allocated

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5153]
## What went wrong? 😲

If we change the date of a prescription, it's hard to correctly account for stock movements as the stocklines have already been modified be the invoice, so if we allow changing of prescription date we need to somehow undo the stockline changes, but also correctly account for the stock movements which might or might not be in the date range for the new invoice date.

## Expected behaviour 🤔

If a user tries to change the invoice date for a prescription after it's had lines added, they will get a prompt

Changing the prescription date will remove all lines in this prescription, do you want to continue?

If they select yes, all lines will be deleted and the date changed.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a prescription
2. Add a line
3. Try to change the date
4. See prompt
5. Check Yes, and No both work as expected.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5161

**Comment by marthakeezy** [comment]
V2.3.0 Released so moving to Done ✅
