### ISSUE TITLE
Indicators UI

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5162]
#5134 must be implemented first. 

- Designs for the detail view tab coming -

![Image](https://github.com/user-attachments/assets/a6aef977-6b46-45f0-8a3f-fa24325c0d9c)

HIV indicators open up in a new page for editing
![Screenshot 2024-10-24 at 11 30 07 AM](https://github.com/user-attachments/assets/5bd4cf78-cc1a-488b-932d-212f9d0e0fe0)

- [ ] customer manual program requisition
  - [x] Add Indicator tab
  - [ ] Indicator tab only if other party is store and the program has indicators
  - [ ] (Program) Indicator table component
  - [ ] Indicator tab shows indicator table for each `programIndicator`
  - [ ] Clicking a row navigates to URL including `:indicatorLineId`, programIndicator editing page
  - [ ] Program indicator page replicates the `ResponseEditPage`/`ResponseLineEdit`
  - [ ] `IndicatorLineEdit` needs to be dynamic according to the `IndicatorColumns` defined
- [ ] internal order
  - [ ] Add Indicator tab
  - [ ] Indicator tab only if other party is store
  - [ ] (Program) Indicator table component
  - [ ] Indicator tab shows indicator table for each `programIndicator`
  - [ ] Clicking a row navigates to URL including `:indicatorLineId`, programIndicator editing page
  - [ ] Program indicator page replicates the `ResponseEditPage`/`ResponseLineEdit`
  - [ ] `IndicatorLineEdit` needs to be dynamic according to the `IndicatorColumns` defined

OMS:CIMDV

**Comment by roxy-dao** [comment]
Fixed in #5523

**Comment by alainsussol** [comment]
Tested only for Manual requisitions as indicator for internal orders is not ready yet

See results [here](https://github.com/msupply-foundation/open-msupply/issues/5089#issuecomment-2504691006)
