### ISSUE TITLE
Clicking on a datetime picker in Prescriptions shows the warning straight away, warning appears again after clicking anywhere on the screen

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5164]
## What went wrong? 😲

**Issue 1** - the warning the lines will be removed appears straight away, without giving users a chance to even see the datetime picker. Should the flow be `user clicking on the datetime picker -> seeing the window -> clicking on the past date -> clicking Ok to confirm -> then only seeing the warning`? 

Or if the warning should appear before any actions are taken by users, then it shouldn't overlrap the datetime picker -> they should appear one by one. 

**Issue 2** - after cancelling out of the warning and clicking anywhere on the screen, the warning appears again

The video of the behaviour can be found ->>> [here](https://drive.google.com/drive/folders/1chwrPRBjIUMlbce6h2jpYFIsFNpJBbDo)

## Expected behaviour 🤔

**Issue 1** - user clicking on the datetime picker -> seeing the window -> clicking on the past date -> clicking Ok to confirm -> then only seeing the warning

**Issue 2** - the warning should not appear twice if you cancel out of it earlier

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Dispensary -> Prescriptions`
2. Create a new prescription and add an item to it
3. Click on the datetime picker to see the first issue
4. Click Ok or Cancel and then click anywhere else on the screen to see the second issue

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC10
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Checked in with @mark-prins - agree not ideal, but should affect a fairly small circle (only if you try to change the date after adding items, which is not the recommended workflow)

We can fix for 2.4 🙏

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-RC6`

- [ ] If using Desktop browser, open DevTools and switch to a mobile layout (the DatePicker will be different)
- [ ] Open a Prescription and click on date
- [ ] Should *not* get any item deletion confirmation modal
- [ ] Change the date and submit
- [ ] Should get the confirmation modal
- [ ] Also test in normal browser to confirm existing behaviour is unchanged
