### ISSUE TITLE
Backdating the prescription and reverting it back to today's date results in the future time (23:59PM)

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5172]
## What went wrong? 😲

- I create a prescription today -> the system registers current time and date
- I backdate to yesterday -> it's 16/10 23:59
- But then I change it back to today and it automatically sets it to 23:59 even though today's 23:59 hasn't happened yet

Setting as Low priority as confirmed by Laché it does not break any future transactions

## Expected behaviour 🤔

If the prescription is reverted back to today's date, the time should show up according to the time it is now, and not 23:59PM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Prescriptions
2. Create a prescription and add an item
3. Backdate it to yesterday and then revert it back to today's date
4. Go to Stock -> View Stock and select the item from the prescription
5. See in the Ledger the time for today shows as 23:59PM

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC10
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closing this as duplicate: #4979
