### ISSUE TITLE
Allow user to create PROGRAM manual requisitions

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5177]
Extend #5119 to allow users to create program requisitions. Will need #5171 backend changes first

Step 1. Clicking the `New Requisition` button should show up with the option to *Select Customer* or enable the *Select Program* if the store uses programs.

For programs, the user should be able to create requisitions for BOTH `PERIODIC` and `URGENT` order types

<img width="541" alt="Screenshot 2024-10-17 at 2 48 29 PM" src="https://github.com/user-attachments/assets/2dae7c2e-9b58-4172-acba-ffeb8cc1e761">

Step 2. Display program info in the info panel

![Screenshot 2024-10-15 at 11 43 58 AM](https://github.com/user-attachments/assets/3ff354cb-2890-497e-a063-ef59705a56c6)

NOTE: After creation, the requisition should follow the same workflow as an automatically created requisition

See implementation in `Internal Orders` for an example of this already implemented

### Moneyworks Jobcode 🧰
OMS:CIMDV

**Comment by alainsussol** [comment]
Tested in Epic testing. See results [here](https://github.com/msupply-foundation/open-msupply/issues/5089#issuecomment-2479340537)
