### ISSUE TITLE
Item Variant & Packaging Variant Sync

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5206]
## Describe the solution you'd like 🎁

`item_variant` and `packaging_variant` should sync to OMS Central server (editiable only as central data)

**Comment by AnushaUp** [comment]
# 🧪 Testing



- [ ] Create item variants on your central server (without setting a cold storage type)
- [ ] Re-initialise a site, check that variants show up when doing inbound shipment/or similar
- [ ] Try updating a item variant
- [ ] Check that its updated after syncing remote site
- [ ] Try adding a new item variant
- [ ] Check that it's available after syncing remote site
- [ ] Try stopping your remote server then
- [ ] Add a new item on the Central mSupply
- [ ] Add a new item variant to the new item in OMS Central
- [ ] Turn your remote server on again and check the item and item_variant synced correctly together
- [ ] Try assigning an item variant to an inbound shipment line
- [ ] Then try re-initialising, this will check that the inbound shipment line is translated correctly from mSupply

**Comment by AnushaUp** [comment]
Bug found issue [HERE](https://github.com/msupply-foundation/open-msupply/issues/7414) 

> * Re-initialise a site, check that variants show up when doing inbound shipment/or similar
