### ISSUE TITLE
Compress report wasm functions and/or move convert data out of JSON

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5207]
## Is your feature request related to a problem? Please describe 👀

The generated standard reports json is large already (5mb), and performance on tablets could be a concern (https://github.com/msupply-foundation/open-msupply/pull/5165#pullrequestreview-2390432720)

Having large reports synced from central server is an issue.
Can we compress wasm functions?

## Describe the solution you'd like 🎁

Either cache function or move out of standard reports json

### Additional context 💌

Part of #4668 yet untriaged

### Moneyworks Jobcode 🧰

OMS:REPT

**Comment by roxy-dao** [comment]
Do you mean move it out of the manifest json?

**Comment by fergie-nz** [comment]
Closing as futher use of wasm functions under question
