### ISSUE TITLE
Indicators: indicator_attribute GQL

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5216]
## Is your feature request related to a problem? Please describe 👀

Requires: [#5211](https://github.com/msupply-foundation/open-msupply/issues/5212)

Add GQL layer code for fetching indicator_attribute. Probably discuss with someone first 😉

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by fergie-nz** [comment]
Is the attribute the lines / columns?

This will be fixed by #5304
