### ISSUE TITLE
Indicators: indicator_value GQL

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5217]
## Is your feature request related to a problem? Please describe 👀

Requires: [#5211](https://github.com/msupply-foundation/open-msupply/issues/5213)

Add GQL layer code for fetching indicator_value. Probably discuss with someone first 😉

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by fergie-nz** [comment]
Note that partially fixed by #5310 which adds value loader
