### ISSUE TITLE
Age is showing as 0 for patients younger than 1 year old

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5218]
## What went wrong? 😲

When clicking on a specific patient, if they are < 1 year old, the age display is inconsistent (e.g. one area shows actual age, another area shows 0)

<img width="1250" alt="Screenshot 2024-10-24 at 12 47 07 PM" src="https://github.com/user-attachments/assets/b47783f5-7535-4dcb-b3d9-8197f0d721a7">

<img width="1250" alt="Screenshot 2024-10-24 at 12 50 49 PM" src="https://github.com/user-attachments/assets/8e12887e-89c5-4594-acf9-ff5212ba31e9">

## Expected behaviour 🤔

Would be nice to display months and days at the top and not just 0

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Create a new patient and set the date of birth to a date within the last year
3. Finalise the creation process (e.g. add code etc)
4. At the end, see the top showing 0 and the middle showing the actual age, just like on the screenshots

## Your environment 🌱

- Open mSupply Version: `V2.3.1-RC1`
- Legacy mSupply Central Server Version: `V7.18.06`

- Platform: `Browser (Google)`

- Database type: `SQLite3`

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.5.0-reports`



- [ ] Open patients tab
- [ ] Create or edit patient
- [ ] Add DOB
- [ ] Check DOB for more than 1 year old, less than 1 year old, less than 1 month old
- [ ] Check that dates display in days and months

**Comment by marthakeezy** [comment]
Hey @noel-yeldos can you please confirm one line updating but not the other is expected behaviour? Doesn't seem right to me

https://github.com/user-attachments/assets/669e0808-5684-407a-ac26-46cd2391ec1b

**Comment by noel-yeldos** [comment]
> Hey @noel-yeldos can you please confirm one line updating but not the other is expected behaviour? Doesn't seem right to me
> 
>  Screen.Recording.2024-12-20.at.11.20.07.AM.mov

Hey @marthakeezy I believe that is expected behaviour. The details in the toolbar only change on save. @lache-melvin is that correct?

**Comment by lache-melvin** [comment]
Yep, that looks correct, updating on save!

**Comment by marthakeezy** [comment]
Nice! Thanks - build test passed ✅
