### ISSUE TITLE
Delete Item Variants

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5225]
## Is your feature request related to a problem? Please describe 👀

Implement the delete button/mutation for item variants

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by marthakeezy** [comment]
# 🧪 Testing

Tested as a part of V2.4.0 Release Testing, also in `V2.4.0-RC6`

- [ ] On OMS central
- [ ] Create an item variant
- [ ] Delete it
- [ ] You get a confirmation modal, then the variant is deleted
