### ISSUE TITLE
Add item_variant_id to stock_line/invoice_line

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5228]
## Is your feature request related to a problem? Please describe 👀

Need to capture item_variant_id on all incoming stock for GAPS (optional). Should be added to both stock_line and invoice_line.

Will need to go be added in mSupply, the translated and synced.

**Comment by marthakeezy** [comment]
Note from Laché: 

ah yeah - i think QA of this would be something to the tune of add item variant on an inbound shipment, and a stock line... saves/syncs/reinitialises fine? May well be covered by other testing 🙏

Was covered as a part of V2.4.0 Release testing in #5397, can give it another thorough test post V2.5.0 release but seems to be working fine for now :)
