### ISSUE TITLE
Not syncing return reasons

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5230]
## What went wrong? 😲

Was just in the the invoice translation code, and saw this:

https://github.com/msupply-foundation/open-msupply/blob/a6f8ff3890aaf50515c795c7e2a957b849850ecf/server/service/src/sync/translations/invoice_line.rs#L268

I would assume this means return reasons are not being synced/saved!

OG only has the `optionID` field, so might have been pending some kind of decision on how we map the different reason id fields in OMS to OG?

## Expected behaviour 🤔

Return reasons sync

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create return
2. Sync to another site
3. No reason?

## Your environment 🌱

- Open mSupply Version: v2.3.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Re initialisation test or integration test (that covers this use case) should have caught this

**Comment by roxy-dao** [comment]
Closed in #5613

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Have reasons for IA and return 
- [ ] Make a Supplier Return with reason 
- [ ] Make a stocktake with reason
- [ ] Sync
- [ ] Check on OG that reasons chosen have synced **-PASS-**
- [ ] Re-initialise
- [ ] Make sure the data is still there **-PASS-**
