### ISSUE TITLE
Date filters (general) + patient birth date on creation displays the incorrect date (date before)

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5247]
## What went wrong? 😲
Reported by @alainsussol & @kahn-msupply 

When they filter by date (in stock and patient) the date selection jumps to the date before and the same thing happens when entering a patient's birth date on creation.

Possible timezone problem.

https://github.com/user-attachments/assets/5155487a-3949-4a9e-a2a2-41c429baa798

https://github.com/user-attachments/assets/2db382bd-ca6c-46b4-91a8-3324e1933c72

![photo_2024-10-30 09 06 15](https://github.com/user-attachments/assets/6532de7d-04aa-4299-b5ea-023d7dd69210)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a date filter (stock expiry date or patient DOB)
2. Click on a date, see that it changes to the date before

## Your environment 🌱

- Open mSupply Version: 2.3.1
- Legacy mSupply Central Server Version:

- Platform: Android & Desktop

- Database type:

**Comment by lache-melvin** [comment]
Setting as high - perhaps should be `normal` (not actively blocking) but dates are quite a critical component of the app and users should be able to trust them!

**Comment by andreievg** [comment]
Assigning to 2.3.2 since we have a release in the works for a client 2.3.1, hopefully can add to that release

**Comment by CarlosNZ** [comment]
Closed by #5276

**Comment by marthakeezy** [comment]
Spotted #5280

**Comment by marthakeezy** [comment]
Apart from above, build test passed -> moving to Done ✅
