### ISSUE TITLE
GAPS: Manufacturer List

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5248]
## Is your feature request related to a problem? Please describe 👀

Item Variants currently allow you to select a manufacturer, but manufacturers aren't available in the system so suppliers have been temporarily substituted.

## Describe the solution you'd like 🎁

Item Variant drop down should show a list of manufacturers as configured in mSupply.

If sync or db changes are neccesary they should be done in this issue

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.5.1`


- [ ] Edit item variants on your central OMS server
- [ ] Check that you can only select names marked as manufacturers in mSupply
