### ISSUE TITLE
GAPS: Add Cold Storage Type to Item Variants

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5249]
## Describe the solution you'd like 🎁

Add Cold Storage Type to Item Variants as a drop down/auto complete list?

**Comment by CarlosNZ** [comment]
Will also require new "coldStorageType" GraphQL node, so we can get the list, which is also required for [this](https://github.com/msupply-foundation/open-msupply/issues/4367#issuecomment-2445470647)

**Comment by lache-melvin** [comment]
Duplicate of #4368

**Comment by marthakeezy** [comment]
As this is a duplicate, testing will be done under #4368 

Moving to Done ✅
