### ISSUE TITLE
GAPS: Improve validation on Packaging/Item Variants

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5250]
## Describe the solution you'd like 🎁

Appropriate validations are added to API requests
Tests for validation rules are added...

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.0-build-test-3`

- [ ] Create and edit item_variants (OMS Central Server)
- [ ] Try doing thing you think you should be allowed too like duplicate names

**Comment by marthakeezy** [comment]
hey @jmbrunskill - quick q, do we do any casing validation at all? 

<img width="482" alt="Image" src="https://github.com/user-attachments/assets/62863fb9-c5da-4858-8f0b-c58d44a57281" />

**Comment by jmbrunskill** [comment]
> hey [@jmbrunskill](https://github.com/jmbrunskill) - quick q, do we do any case validation at all?
> 
> <img alt="Image" width="482" src="https://private-user-images.githubusercontent.com/153777484/410722457-62863fb9-c5da-4858-8f0b-c58d44a57281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkxNTMxNjAsIm5iZiI6MTczOTE1Mjg2MCwicGF0aCI6Ii8xNTM3Nzc0ODQvNDEwNzIyNDU3LTYyODYzZmI5LWM1ZGEtNDg1OC04ZjBiLWM1OGQ0NGE1NzI4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMFQwMjAxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODkwZmM4ZjZiMDVhMmIxNzhjYWQ4MmQ3OTJlY2U1MDI3MzFhMjE2OTA4M2RlMzBkNjVkZDhhOWYxOWVjZDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3Pjtx7jSLcnE0ZS0V4D0-1Hl5B-6WjFgjWeuHZn_6cg">

I think we do sometimes, but in general I'm not too worried about this kind of bug as the use can come in an fix it themselves. That said they are able to delete it to fix right?

**Comment by marthakeezy** [comment]
Yep deletion works! Oki, if not too worried about case validation, everything else works so moving to Done ✅
