### ISSUE TITLE
New stock line default pack size is 0

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5253]
## What went wrong? 😲

Sorry I missed this one in review!

View stock -> new stock -> select item -> pack size is 0, used to default to 1:

![Screenshot 2024-10-30 at 12 55 02 PM](https://github.com/user-attachments/assets/5907f11f-6205-45bc-845b-038331c8135f)

## Expected behaviour 🤔

Should default to 1... or maybe item default pack size like we have in inbound shipment?

## How to Reproduce 🔨

Steps above

## Your environment 🌱

- Open mSupply Version: v2.4 develop
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Should be item default packsize

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Navigate to Inventory --> View Stock
- [ ] Create new stock item
- [ ] Select item 
- [ ] Pack size is now item default pack size **-PASS-**
- [ ] Change the default price in OG
- [ ] Sync
- [ ] Navigate to Inventory --> View Stock
- [ ] Create new stock item
- [ ] Select item 
- [ ] Pack size is now the new item default pack size **-PASS-**
