### ISSUE TITLE
Patient look up not working on dispensing module when adding new patients

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#5258]
## What went wrong? 😲
patient look up through central is not working on live server and also if the patient is already on the tablet when u try and add patient again it cannot find the patient and will let you create duplicate

## Expected behaviour 🤔
Search patients already existing in system or on central server

## How to Reproduce 🔨
v2.3 tablet oms
Add new patient - patient is added
Add new patient again (same name, code, dob etc) - patient cannot be found

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Setting to normal (sounds like workaround is to not put a code until after the central lookup?) but depending on urgency perhaps should adjust severity 🙏

**Comment by andreievg** [comment]
Closing as there is another issue with hotfix

**Comment by AnushaUp** [comment]
Will be fixed and tested [HERE](https://github.com/msupply-foundation/open-msupply/issues/5268)
