### ISSUE TITLE
Dispensing from Programs (Reproductive Health Module)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5262]
## Is your feature request related to a problem? Please describe 👀

For a Reproductive Health Module, we need a way to dispense (create prescriptions) from within an Encounter.

- [ ] Item Categories
  - [x] #5330
  - [x] #5331
  - [x] #5332
  - [x] #5333
  - [ ] #5334
  - [x] #5335 
- [x] #5264
  - [x] #5265
  - [x] #5266
  - [ ] Validate prescription on save (no half-completed data)
  - [x] #5267
- [ ] Allowance for custom JSON forms!

### Moneyworks Jobcode 🧰

DJIFPCDV

**Comment by marthakeezy** [comment]
Tested as a part of #5676 - moving to Done ✅
