### ISSUE TITLE
Create JSON Form prescription renderer 

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5264]
Create a new JSON forms renderer.

Input will be item_category_id. Item dropdown should be filtered by this category.

On item select, show available batches (much like the vaccination modal).

User should then be able to enter desired # packs to dispense. 

Will confirm - I think only need to be able to dispense from one batch here?

**Comment by lache-melvin** [comment]
Closed by #5581

**Comment by marthakeezy** [comment]
No specific testing steps -> tested as a part of #5676, moving to Done ✅
