### ISSUE TITLE
On form re-open, show a prescription created message/view prescription link

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5267]
Prescription JSON form component should check whether the prescription has already been created. If so, instead of showing item picker etc, show an info box that a prescription has been created, with a link to it, much like vaccination:

![Screenshot 2024-10-30 at 5 08 32 PM](https://github.com/user-attachments/assets/fd86852c-dcd2-487c-9757-7d2208027b25)

**Comment by lache-melvin** [comment]
Closed by #5581

**Comment by marthakeezy** [comment]
Tested as a part of #5676, moving to Done ✅
