### ISSUE TITLE
Buggy scrolling in R&R Forms

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5273]
## What went wrong? 😲

When scrolling up and down in R&R forms, there appears to be lots of white space. When scrolling back up, the page sends you back down and/or displays white space that wasn't previously there.

Video posted ->> [here](https://drive.google.com/drive/folders/1LkpsgUepNt6R_G4B9gXkxrdqJIiTynFi)

## Expected behaviour 🤔

Non-buggy scroll, no white space

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> R&R Forms
2. Create a new form
3. Select a program -> see the form populate
4. Scroll up and down - see buggy behaviour

## Your environment 🌱

- Open mSupply Version: V2.3.0
- Legacy mSupply Central Server Version: V7.16.8

- Platform: Tablet (Samsung Galaxy)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
This is a result of virtualising the table - there are too many inputs to render, and it was taking >30s to load the page for big master lists! However it's not very performant, especially on tablet.

Closing this issue and adding to table performance issue
