### ISSUE TITLE
Using the back button with unsaved changes does not trigger `confirm on leaving`

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5274]
## What went wrong? 😲

When using R&R Forms, if you change the value of the cell and don't save it, the users should get a warning, letting them know any unsaved data will not be kept. 

For example, when using navigation panel to exit the R&R form, the users see [the following](https://drive.google.com/drive/folders/1leTTuauq7yRWGtM62C2HSqvQUft0TvYZ) ✅ 

However, when using the back button on the android tablet, the users don't get the warning (like shown [here](https://drive.google.com/drive/folders/1leTTuauq7yRWGtM62C2HSqvQUft0TvYZ)). Raising after checking in with @lache-melvin 

## Expected behaviour 🤔

Warnings should be same regardless of how the user navigates out of the R&R forms

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> R&R Forms
2. Create a new R&R Form
3. Add some items -> change the value of a cell (but don't save it)
4. Navigate out of the R&R form using nav panel -> see warning ✅ 
5. Navigate out of the R&R form using the back button on a tablet -> no warning 🚫 

## Your environment 🌱

- Open mSupply Version: V2.3.0
- Legacy mSupply Central Server Version: V7.18.6

- Platform: Samsung Galaxy Tab A8 Tablet (Android)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Confirming same behaviour in browser too, not just android 🥲

**Comment by marthakeezy** [comment]
I am kind of tempted to change the severity to High because imagine the user making heaps of changes and then accidentally navigating away, and there is no prompt to stop that -> they lose all the data

I definitely accidentally navigate back when using the trackpad at least a few times a day, if not more often

**Comment by lache-melvin** [comment]
Setting to high 2.3.2 - affecting all platforms and all areas using useConfirmOnLeaving. Needs a little investigation, looks like it is only triggering the confirmation on `navigator.push` - I assume back button does something like `navigator.back`/`.go`?

**Comment by CarlosNZ** [comment]
Seems to be a problem everywhere, not just R & R forms, so maybe we don't catch back navigation at all currently?

**Comment by mark-prins** [comment]
ooh! we can 😁 

the issue is that the back button doesn't unload the page, so the `beforeunload` event won't fire.
however.. `useBlocker` is now available in react router! We can implement that ( I have a working version if anyone wants )

**Comment by lache-melvin** [comment]
Closed by #5281

**Comment by marthakeezy** [comment]
If you press the back button on Android multiple times very fast, there is a different prompt: 

[Linked here](https://drive.google.com/file/d/1kHM8kdeFhhr9ArA3hwiAPiIHOYmy8-T1/view?usp=drive_link)

- If you click 'Stay on this Page', it logs you out regardless -> when logging back in, it does not take you to the page you were previously viewing
- If you don't click anything and press the back button again, the page freezes and you cannot click the nav panel or back button again

**Comment by marthakeezy** [comment]
Is it an easy one to ask someone to list all areas of omSupply affected by this change?

I just tried changing item's details under `Inventory` -> `View Stock` -> `Item X` -> used the `back button` on Android to navigate back with unsaved changes and didn't get a prompt. Struggling to understand where to expect this message to appear. 

Thanks! 🙏🏼

**Comment by marthakeezy** [comment]
- [ ] Cold chain equipment detail view
- [ ] Coldchain > monitoring ( if you are uploading a fridge tag it will prompt when in progress )
- [ ] Inbound shipment > detail view ( when editing a line )
- [ ] Outbound shipment > detail view ( when editing a line )
- [ ] Prescription > detail view ( when editing a line )
- [ ] JSON forms ( so that's encounters and patient details )
- [ ] Patient details ( if you edit a patient and try to change tabs )
- [ ] R&R form > detail view

**Comment by marthakeezy** [comment]
Build test passed! ✅

**Comment by marthakeezy** [comment]
Reopening as no prompts when navigating away in browser or on a tablet in `V2.4.0-test1`

@CarlosNZ

**Comment by lache-melvin** [comment]
Hi @marthakeezy - 2.4 test1 build was created before the 2.3.1 patch went it, so the fix won't be in there! I think this one is okay 🙏

**Comment by marthakeezy** [comment]
Oh! Oki - closing back 🙏🏼
