### ISSUE TITLE
Initalising from export might be incorrect

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5282]
@roxy-dao  I'm facing an issue when i try to login into the app. The issue is this : "Your account does not have access to any stores on this site". I'm using the Admin credentials from the Users.txt file.

_Originally posted by @myspace20 in https://github.com/msupply-foundation/open-msupply/issues/5219#issuecomment-2448820091_
        

Needs investigation as to why...

**Comment by myspace20** [comment]
@jmbrunskill please is there a solution to this ? I'm pretty new to the project and this issue is getting in my way kind of.

**Comment by jmbrunskill** [comment]
@myspace20 Thanks for your patience, I'm going to look into this problem this week! We've all been busy getting ready for our next release.

**Comment by jmbrunskill** [comment]
@myspace20 Please see my PR #5301 if you delete your database, apply those changes then initialise, you should be good to go!

Thanks for letting us know about the issue.

**Comment by myspace20** [comment]
Thank you @jmbrunskill I will try later in the day.
