### ISSUE TITLE
Improve confirm on leaving alert

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5285]
## Is your feature request related to a problem? Please describe 👀
Following on from #5274 - this is an opportunity to update the modal style.
When prompting we are using the browser `confirm` method, giving:

<img width="580" alt="image" src="https://github.com/user-attachments/assets/c0721f8b-2249-4a82-816a-201ad30f35c0">

## Describe the solution you'd like 🎁
It would be nicer to use the confirmation modal and prompt using a react element rather than the browser default.

**Comment by marthakeezy** [comment]
Waiting for #5274 to be fixed

**Comment by marthakeezy** [comment]
Tested in V2.4.0-RC4, build test passed ✅
