### ISSUE TITLE
Cannot clear item selection in Inbound Shipments

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5289]
## What went wrong? 😲

Cannot clear item selection when adding an item to an Inbound Shipment

Video of the behaviour ->>> [here](https://drive.google.com/drive/folders/1Z9ynv3aD8WNoJlcDr03rP6LqeRu2MoG5)

## Expected behaviour 🤔

Able to clear item selection

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Inbound Shipments
2. Create a new Inbound Shipment
3. Try to add an item -> when adding, attempt clearing your selection

## Your environment 🌱

- Open mSupply Version: V2.3.1-RC3
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Browser (Google), Galaxy Tablet A8 (Android)

- Database type: SQLite3

**Comment by CarlosNZ** [comment]
Closed by #5291

**Comment by marthakeezy** [comment]
Tested in V2.3.1-RC4, passed the build test ✅ 

However, another bug logged here -> # (unable to backspace item entries). Let Carl & James know :)
