### ISSUE TITLE
Inconsistent UI in Edit Location modal

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5290]
## What went wrong? 😲

From [this comment](https://github.com/msupply-foundation/open-msupply/pull/5287#issue-2628056241):

The Edit Location modal looks like this: 

![Screenshot 2024-11-01 at 1 14 23 PM](https://github.com/user-attachments/assets/b9b7df1b-85ea-462d-bfeb-4620b241b9e8)

However, every other modal/detail view uses the Label/Input UI, like this:

![Screenshot 2024-11-01 at 1 17 38 PM](https://github.com/user-attachments/assets/128f6fb6-b214-44d4-917c-33ce54fbb697)

It wasn't really a problem, but now that we have a drop-down on that modal, the label doesn't work properly when there is nothing in the input yet. Here it is after input:

![Screenshot 2024-11-01 at 1 14 40 PM](https://github.com/user-attachments/assets/9a2486d1-2201-49a0-9e2a-9f48f4c6ad10)

To fiddle around with the CSS to make this label behave like the text input label (I did something similar once for the Filters -- it wasn't pretty) is probably a waste of time -- we'd be better to just change the modal to follow the same layout UI used everywhere else.

## Expected behaviour 🤔

UI should look consistent with other modals/detail pages

## How to Reproduce 🔨

View "Inventory" -> "Locations" -> Click an item

**Comment by lache-melvin** [comment]
FWIW, what I've seen of Mariya's future-state designs, the inputs actually look more like the location one:

<img width="399" alt="Screenshot 2024-11-04 at 3 18 36 PM" src="https://github.com/user-attachments/assets/f4c2e6d7-d0c6-4202-a1b5-632a1705aac3">
<img width="352" alt="Screenshot 2024-11-04 at 3 19 28 PM" src="https://github.com/user-attachments/assets/e01919b5-95c5-45e6-ac2d-655af7bb2b2a">

Depending on which UI changes are scheduled for, maybe worth fixing only once 👀

**Comment by mark-prins** [comment]
triage: agree w @lache-melvin we can resolve when we change styles across the board

**Comment by alainsussol** [comment]
@mark-prins Not to be tested

**Comment by mark-prins** [comment]
no, thanks @alainsussol . nothing to test yet 🙏
