### ISSUE TITLE
Item Bundling validation

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5300]
## Is your feature request related to a problem? Please describe 👀

Adds the item bundling validation logic from #5292

## Describe the solution you'd like 🎁

Only valid item bundles can be created

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by marthakeezy** [comment]
No specific QA testing steps in the PR, language suggests dev testing, moving to Done ✅
