### ISSUE TITLE
Bundled Item UI

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5302]
## Is your feature request related to a problem? Please describe 👀

See designs here: https://github.com/msupply-foundation/open-msupply/issues/3923#issuecomment-2418134318

## Describe the solution you'd like 🎁

UI to add/edit and remove bundled variants from other item variants.

It should also prevent the user from creating nested bundles

### Moneyworks Jobcode 🧰

CCEIDEV

**Comment by AnushaUp** [comment]
PASSED✅
