### ISSUE TITLE
Program Indicator Mutations

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5305]
## Is your feature request related to a problem? Please describe 👀

Adds mutations and service layer mapping for program indicators. Builds upon #5304, but adds mutations.

## Describe the solution you'd like 🎁

Mutation structure:
done by manipulating individual values

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by roxy-dao** [comment]
Closed in #5347
