### ISSUE TITLE
Add graphql loader for indicator values for program_indicator queries

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5310]
## Is your feature request related to a problem? Please describe 👀

Builds on #5215
Adds loader to add values to program_indicator nodes

## Describe the solution you'd like 🎁

Adds a simple loader
Loader doesn't include more complex hash including period_id, supplier_id, customer_id. 
This means with multiple queries for indicators where those values differ might cause mixing from the loader, but we can iterate on this later.

### Describe alternatives you've considered 💭

Could query indicator values from service layer also

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by roxy-dao** [comment]
Closed in #5327
