### ISSUE TITLE
Rename Program Status to Patient Status

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5311]
## What went wrong? 😲

It would be great to rename Program Status column into Patient Status as I don't find the naming intuitive - `Program Status: Died` does not make sense. Especially when you click to see more details and it says Patient Status History. 

<img width="1252" alt="Screenshot 2024-11-05 at 2 08 14 PM" src="https://github.com/user-attachments/assets/4e8e6dff-778c-49a2-a008-6bc9a4e2b30c">

<img width="583" alt="Screenshot 2024-11-05 at 2 08 23 PM" src="https://github.com/user-attachments/assets/015f6dca-9477-4a20-a2bf-dac77a1ebb90">

## Expected behaviour 🤔

Should be Patient Status

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Click on an existing patient or create a new one
3. Tap on Programs tab -> see columns
4. Column Program Status is confusing

## Your environment 🌱

- Open mSupply Version: V2.4.0-test1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Browser (Google) on a Desktop

- Database type: SQLite3

**Comment by andreievg** [comment]
Triage: Needs to be consolidated in a general program fix issue, so that we can reduce issue count and look at all of the issues at once

**Comment by roxy-dao** [comment]
The status can be a list of things... so don't think it should be renamed to Patient Status

**Comment by mark-prins** [comment]
thanks @roxy-dao : that's right. it can be a list, so the current name is valid.
