### ISSUE TITLE
Unable to run Item usage report

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5312]
## What went wrong? 😲

Running the item usage report results in this:

<img width="548" alt="Screenshot 2024-11-05 at 12 14 12 PM" src="https://github.com/user-attachments/assets/ae16f45c-41ff-4f04-bad6-af145f045d59">

![image](https://github.com/user-attachments/assets/7daa3620-529b-4063-9243-ac8875c4b796)

## Expected behaviour 🤔
Report should display correctly.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Using this version of item usage will cause a problem:
[item-usage.json](https://github.com/user-attachments/files/17625487/item-usage.json)

Taking the generated version from the reports repo is fine though - so there's an issue with the report JSON.
The questions is - can we display an error message, that the report has a problem? that would be more useful than the above error.

Issue raised by @marthakeezy : I have a copy of the sqlite datafile if you are unable to repro using the above JSON

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by marthakeezy** [comment]
#5298 sorry mark!

**Comment by andreievg** [comment]
We are meant to introduce versioning as a transition to the new reports (and actually not use existing ones, which would mean a little bit of admin work on omSupply central server for upgraded sites to work), this is still in the works for 2.4.

Basically existing reports will be wiped, replaced by omSuppy central reports (and bundled reports), all existing custom reports will be uploaded to omSupply central (via cli), I'll outline this a bit more in the Report issue, and I've already talked about this a bit to support. I think this would be a non issue.

But agree we do need some better logging, or at least capture the unwrap in a safer manner, adding a comment to the report issue

**Comment by roxy-dao** [comment]
Fixed in #5482

**Comment by marthakeezy** [comment]
`In V2.4.0-RC2`

![Image](https://github.com/user-attachments/assets/f46cdf1a-14c4-4016-943e-608f6c912e92)

**Comment by roxy-dao** [comment]
@marthakeezy  Can you test if this is happening in RC4? The reports should be updated on start up, so I think this might have been solved.

**Comment by marthakeezy** [comment]
Heyyy, so now I am having this issue on Item Usage Report and Stock Status Report (thats in browser)

**Item Usage:**

<img width="1498" alt="Screenshot 2024-11-28 at 9 54 52 AM" src="https://github.com/user-attachments/assets/7c3b8caf-9dec-4f3c-a2f5-f667302eed66">

**Stock Status:** 

<img width="1509" alt="Screenshot 2024-11-28 at 9 55 04 AM" src="https://github.com/user-attachments/assets/9ebc6afc-a5c8-4384-b764-b5b80012d44d">

On Android, if you run Item Usage or Stock Status report, the app crashes and exits, also getting this prompt when omSupply crashes on Android: 

![image](https://github.com/user-attachments/assets/55e697c8-4fc2-4cb1-9f8b-5900d485598f)

**Comment by andreievg** [comment]
After a long time in a rabbit hole, no results, but lodge an issue with js-pdk https://github.com/extism/js-pdk/issues/107, this should work fine with rust-pdk (rust wasm plugin), worst case we re-write or remove sorting and revert back to wasmless

**Comment by roxy-dao** [comment]
Closed in #5654

**Comment by marthakeezy** [comment]
Passed in `V2.4.0-RC6` - moving to Done ✅
