### ISSUE TITLE
Disable actions if no rows are added to be deleted

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5315]
## What went wrong? 😲

Logging a general issue for areas of omSupply where Actions are enabled and clickable even if there is nothing to remove/delete

**Instance 1:** adding vaccine courses to an immunisation program

<img width="1250" alt="Screenshot 2024-11-05 at 3 14 01 PM" src="https://github.com/user-attachments/assets/02bcc126-43e2-4834-8566-159ff3923bd7">

Instance 2: Customer Retutns

<img width="1252" alt="Screenshot 2024-11-05 at 3 17 36 PM" src="https://github.com/user-attachments/assets/eda7a133-750f-466f-86d5-a6f54368b6d1">

Instance 3: Inventory -> Locations

<img width="1251" alt="Screenshot 2024-11-05 at 3 18 47 PM" src="https://github.com/user-attachments/assets/27dcbdf8-fad2-42c5-8807-8f441ada32ed">

## Expected behaviour 🤔

Actions dropdown should be disabled if no rows have been added

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Programs -> Immunizations
2. Click on an Immunization program that has nothing added
3. If no such program, create a new one from scratch to replicate the issue
4. Note the Actions dropdown is clickable

## Your environment 🌱

- Open mSupply Version: V2.4.0-test1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome browser on laptop

- Database type: SQLite3

**Comment by mark-prins** [comment]
There's a plan to change how the actions work, coming as part of the GEDSI work, which would render this one obsolete 
apart from that.. thanks! and I agree 🙏
