### ISSUE TITLE
Limited search results when adding a new CCE asset

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5316]
## What went wrong? 😲

When adding a new CCE asset, I am trying to look for my Remote Store that I have setup on a tablet. I am unable to find the store, as it starts with the letter `N` and the search is getting cut off after letter `L` as shown on the example video - briefly spoke to Mark and we think it's hitting the limit of search results being displayed, hence can only see up to a certain point.

Searching for a specific store also does not work, as search is looking up the store within existing results that are already displaying, not searching among _all_ stores. 

Video of the behaviour ->>> [here](https://drive.google.com/drive/folders/19FLxavoeQQ7Rk0yfvt9h_GkJMtQzO-kG)

## Expected behaviour 🤔

Results should show all stores available, without cutting them off. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a datafile with many stores available
2. Go to Cold chain -> Equipment
3. Click New Asset and click on a store selection dropdown
4. Note it gets cut off after a certain point and if you look for a store that starts with a letter after the cut-off point, the results do not show
5. Error!

## Your environment 🌱

- Open mSupply Version: `V2.4.0-test1`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Google Chrome on desktop, Galaxy A8 Tab (Android)

- Database type: `SQLite3`

**Comment by marthakeezy** [comment]
Setting as `Normal` as there is still a workaround of adding an asset from a remote site rather than the central server

**Comment by andreievg** [comment]
Maybe can be fixed on front end as good first issue ? In this cased to be done asap

**Comment by lache-melvin** [comment]
Looks like stores query accepts pagination input, but we aren't passing anything in, so using [default of 100](https://github.com/msupply-foundation/open-msupply/blob/v2.4.0/server/repository/src/db_diesel/filter_sort_pagination.rs#L329)

Quick fix would be to pass in a huge pagination limit (i.e. 5000, like we have in other places.) I think better solution to change the StoreSearchInput to use AutocompleteWithPagination, shouldn't take too long 🙏

**Comment by lache-melvin** [comment]
Closed by #5524

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-RC6`

- [ ] Have a datafile with many stores available (over 100, less than 500). You should be on the Central Server
- [ ] See what the names of the last few stores are in your data
- [ ] Go to Cold chain -> Equipment
- [ ] Click New Asset and click on a store selection dropdown
- [ ] You should see all of the stores available in alphabetical order to the end of your list

Tested on Central Server, used the search field - working as expected. Moving to Done ✅
