### ISSUE TITLE
GAPS: Tweak issue

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#5318]
## What went wrong? 😲

This is a hold-all issue to capture minor tweaks to the UI etc

The idea is to tackle low-hanging fruit to improve the UX

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
@adamdewey can re - open this issue when there are UI tweak requests : )

**Comment by marthakeezy** [comment]
Going to pop this into 'Not Ready to Test' column for now, will remove later if no updates to the issue

**Comment by marthakeezy** [comment]
Checked with Adam - the chances this issue will be reopened/populated are pretty low. When we have actual pilots with countries, we can open more recent epics/issues so happy to move this one to done! ✅
