### ISSUE TITLE
Translate item categories

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5331]
Item categories exist in OG mSupply, we need to translate these into our new categories schema.

Should be translated to known id (mSupply Categorisation or similar) as the category group, then the categories translated into the category table.

**Comment by lache-melvin** [comment]
Closed by #5428

**Comment by marthakeezy** [comment]
# 🧪 Testing



`Tested in V2.4.1.-RC3`

- [ ] Create item categories (in OG: Item > Item categories > Show Category 1)
- [ ] Assign a category to an item
- [ ] Sync to OMS
- [ ] No translation errors
- [ ] Should be category entries in the category table
- [ ] Should be a join table entry for the item
- [ ] Change the category for an item, sync again
- [ ] old join should have deleted_datetime, new join entry should exist

PASSED - moving to Done ✅
