### ISSUE TITLE
Manual reqs: Stock on hand value overwritten

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5345]
## What went wrong? 😲

The stock on hand value is overwritten when you enter a value for another input.

Side quest: can you focus the stock on hand input when the page loads please

Here's the issue:

https://github.com/user-attachments/assets/fc33ad80-3433-4a1c-966d-d8c037d339c1

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an item line in a manual requisition
2. enter a value into stock on hand
3. press TAB
4. enter a value into Stock arriving
5. press TAB
6. the stock on hand is changed to 0

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by CarlosNZ** [comment]
Sounds like a similar problem I just fixed elsewhere: https://github.com/msupply-foundation/open-msupply/pull/5309

Have made an issue to refactor this at some point so these bugs don't keep popping up: https://github.com/msupply-foundation/open-msupply/issues/5342

**Comment by alainsussol** [comment]
# 🧪 Testing
Tested with v2.4.0 on tablet Android 4


- [x] Add some lines to a general manual requisition
- [x] Go to line
- [x] Enter value in stock on hand -> TAB enter value -> TAB enter value
- [x] Stock on hand shouldn't change to 0 **-PASS-**
