### ISSUE TITLE
Sync bundled items

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5348]
## Is your feature request related to a problem? Please describe 👀

The `bundled_item` table is creating changelog entries, but isn't being synced out to remote sites.

This wasn't a requirement for GAPS (they're only needed on central) but if we want to use item bundling on remote sites in future, they will need to be synced.

## Describe the solution you'd like 🎁

Sync the bundled_item table

### Describe alternatives you've considered 💭

Remove changelog creation for now? At least that way it is clear from all angles that this table is not synced, and we don't have pointless changelog records. Or is it easier to leave them there, so we know the changelog records exist whenever we do implement syncing??

### Additional context 💌

Assuming that they will need to be synced at some point, item bundling was on the original vaccine card spec so may well come up again? Though may be a bit down the pipeline!

**Comment by andreievg** [comment]
I think we shouldn't sync bundled_items for now and it's ok to keep changelog records, so not sure if there is anything to be done atm.

Going to close for now, @DhanyaHerath suggested we should have a discussion page for some carry over or 'closed' issues/topic for a particular area, I think this issue would be a great candidate for this sort of discussion
