### ISSUE TITLE
Hide Item Variant column if none are configured

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5362]
## Is your feature request related to a problem? Please describe 👀

GAPS feature includes `item variants`. As part of this, we needed to track what variant each batch we have on hand is, so we can calculate how much storage is used.

Therefore, there is a way to set item variant on all incoming stock:

![Screenshot 2024-11-08 at 5 23 35 PM](https://github.com/user-attachments/assets/ab4e9fdc-7900-4ed2-a9f7-787cf8c634e0)

However, most OMS deployments aren't using GAPS, and it's probably quite confusing to see this extra column, where the dropdown would always be empty.

## Describe the solution you'd like 🎁

Hide the column if no item variants are configured.

When rendering this column, first query and see if the `item_variants` table is empty. If so, just don't show the column.

### Describe alternatives you've considered 💭

Or maybe based on whether or not GAPS store properties are on?

Also not sure if it should be hidden per item (if the selected item doesn't have variants) or if _no_ items have variants?

**Comment by CarlosNZ** [comment]
> When rendering this column, first query and see if the `item_variants` table is empty. If so, just don't show the column.

Rather than do this for every item, could we just do this once on application load and keep it around as a global value, like `isCentralServer`?

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.5.0`

- [ ] Have no item variants configured (for any items)
  - [ ] There is no item variant column in:
    - [ ] Inbound shipment
    - [ ] Customer return
    - [ ] Stock detail view
- [ ] Configure an item variant
  - [ ] There is now an item variant column in:
    - [ ] Inbound shipment
    - [ ] Customer return
    - [ ] Stock detail view
