### ISSUE TITLE
GAPS 2D scanner -- parse text stream on server

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5364]
Suggested implementation:

- Front end current sends asset ID (`assetById` query). Planning to change this to a new Gql endpoint which just sends the raw scanned data as parameter. The data could be either an ID (from QR code) *or* a GS1-formatted string
- Server decides which type of input it is handles accordingly:
  - If an ID, return Structured error if it doesn't exist, and returns the asset data as normal if it does
  - If it's a GS1 string, server will parse the text into the correct fields. It will then perform a search by serial number. If that serial number exists, it'll return the asset data as normal. If it doesn't exist, it will return the *parsed* asset data, with an extra field `assetExists` set to `false`
- If the front end gets a returned object with `assetExists === false`, it will then ask the user (via confirmation dialog) whether they want to create the asset.
- If the confirm "Yes", the asset will be created using the standard `insertAsset` GraphQL node, using the previously returned data as the input patch.

**Comment by andreievg** [comment]
Great. I think we can use enum to specify if it's id or GS1 string being passed as the first input. 

 > assetExists === false
 
 I think it's better as a union result variant (one variant for found one variant for not found).

**Comment by marthakeezy** [comment]
# 🧪 Testing

This was tested as a part of GAPS Feature Testing in V2.4.0 but also tested in V2.4.0-RC6 just now

- [ ] Using either Android (with camera), or Desktop (with 2d Barcode Scanner)
- [ ] Open the cold chain equipment section, and click the `Scan` button (this doesn't show on web)
- [ ] Scan one of the barcodes below
- [ ] You should be prompted to create a new asset
- [ ] If you accept, it should show a new asset with the serial number, asset type, and Warenty date populated
- [ ] The Installation date should default to today
- [ ] Scanning the same barcode again, should navigate you to the right asset (once it has been created)

> NOTE, scanning these 2d Matrixes in github `dark mode` or with a black background doesn't work well...

2d Matrix examples:

Here's an example raw string you can use to create new QR Code using https://barcode.tec-it.com/en/DataMatrix

`(01)00012345600012(11)241007(21)S12345678(241)E003/002(3121)82(3131)67(3111)63(8013)HBD 116(90)001(91)241007-310101(92){"pqs":"https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/LinkPDF.aspx?UniqueID=3bf9439f-3316-49b4-845e-d50360f8280f&TipoDoc=DataSheet&ID=0”}`

PQS Asset Type: E003/002
Serial Number: S1
![barcode (1)](https://github.com/user-attachments/assets/2e9e2a9a-fe98-4da1-ad97-ec8e7fdd1025)

PQS Asset Type: E003/002
Serial Number: S2
![barcode (2)](https://github.com/user-attachments/assets/455f6d7c-8715-4927-b978-4fcb1a10bfda)

PQS Asset Type: E004/055
Serial Number S1
![barcode (4)](https://github.com/user-attachments/assets/4ca5259c-738a-4343-82db-d0a2b1344f3c)

PASSED! Moving to Done ✅
