### ISSUE TITLE
 GAPS 2D scanner -- create new asset if no match

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5366]
As initially specified [here](https://github.com/msupply-foundation/open-msupply/issues/4757#issuecomment-2463749261)

If the searched serial number has no match, then a NEW asset with the scanned details should be created.

UI should inform user, who must confirm with "OK" in order to proceed and create the asset

**Comment by marthakeezy** [comment]
Tested as a part of V2.4.0 GAPS Release Testing, and also in `V2.4.0-RC6` just now. 

Passed! Moving to Done ✅
