### ISSUE TITLE
No unit grouping symbol in the Difference column of stocktakes

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5372]
## What went wrong? 😲

All columns in the stocktake window (and all other windows I saw) use a digit grouping symbol based, I believe, on the Regional format you have. The Difference column doesn't seem to use any digit grouping symbol. I think that it should to ensure consistency in how we display numbers throughout omSupply.  

## Expected behaviour 🤔
The Stocktake Difference column should use a digit grouping symbol based on the user regional settings. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory > Stocktakes
2. Add a new stocktacke ("New Stocktake" button on the top right of your screen) 
3. Add a new item ("New Item" button on the top menu)  or open an already listed item
4. In the # of counted pack field, add a number equal or greater than a thousand than the Snapshot Packs number . Click OK
6. See error. The Number of counted packs has a digit grouping symbol but the number of the Difference Column don't 

## Your environment 🌱

- Open mSupply Version: 2.4.0test-1
- Legacy mSupply Central Server Version: v19-0RC28

- Platform: openmSupply desktop or Browser version

- Database type: SQLlite

**Comment by andreievg** [comment]
Just for clarification digital grouping in this case is a comma separating thousands from millions etc..

**Comment by alainsussol** [comment]
@andreievg  
I thought I put a screenshot. I must have forgot.

Anyway in English it is a comma
![image](https://github.com/user-attachments/assets/1d6a93a4-6ac1-42cd-9c3a-95a5cb041a13)

In french, it is a space
![image](https://github.com/user-attachments/assets/0477b90c-e18d-4380-b782-7c5e1a36e7a9)

**Comment by aimee-mcneil-melville** [comment]
Mentioned by Andrei to use null in the difference column if the counted packs is null for consistency. Was showing that the difference is 0 if nothing has been counted.

- If snapshot and counted are equal, difference is 0
- If counted is null, then difference is null

**Comment by roxy-dao** [comment]
> Mentioned by Andrei to use null in the difference column if the counted packs is null for consistency. Was showing that the difference is 0 if nothing has been counted.
> 
> * If snapshot and counted are equal, difference is 0
> * If counted is null, then difference is null

If counted is null, then can you display difference with `-`?

**Comment by aimee-mcneil-melville** [comment]
> > Mentioned by Andrei to use null in the difference column if the counted packs is null for consistency. Was showing that the difference is 0 if nothing has been counted.
> > 
> > * If snapshot and counted are equal, difference is 0
> > * If counted is null, then difference is null
> 
> If counted is null, then can you display difference with `-`?

Yes, I will use '-' for these in line with the formatting for null counted

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Go to Inventory > Stocktakes
- [ ] Add a new stocktacke ("New Stocktake" button on the top right of your screen)
- [ ] Add a new item ("New Item" button on the top menu) or open an already listed item - one of the stocklines will need at least 1,000 units available
- [ ] In the # of counted pack field, add a number for each of:
     - [ ] equal or greater than a thousand than the Snapshot Packs number. Difference show with digit grouping **-PASS-** 
     - [ ] equal or greater than a thousand but  *less* than the Snapshot Packs number. Difference show with digit grouping **-PASS-** 
     - [ ] Different than the snapshot quantity and less than 1000.  Difference show with no digit grouping symbol **-PASS-** 
     - [ ] equal to the Snapshot Packs number . Show 0  **-PASS-** 
     - [ ] No counted packs (-). Difference show (-) **-PASS-**
