### ISSUE TITLE
Unable to come back to my original omSupply server once I connected to another omSupply server 

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5376]
## What went wrong? 😲

Working from a tablet, I am connected to the omsupply server running on the tablet. If I then connect to another omSupply server running on my computer located on the same local network, the "pen" icon letting me see the other servers running, is not visible and I can't change back to my original server.

![image](https://github.com/user-attachments/assets/6adf8201-8115-4100-9e02-ef9ee19651ec)

But it works if I do it the other way around ie from omSupply Desktop running on my computer  

tablet app from omSupply Server running on tablet toward omSupply server running on computer. I can't change back to my local server.
https://drive.google.com/file/d/1RwjaNhtkSWcSX1zVQ0JfCnIqffcUdIe7/view?usp=sharing

omSupply desktop from omSupply Server on computer toward omSupply server on tablet and back
https://drive.google.com/file/d/1JjM6IPixOKc5Xg1x4sgfecaaYCOkV5tQ/view?usp=sharing

## Expected behaviour 🤔

I believe I should be able to change back to the server running on the local device after I connected to the omSupply server running on another device.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. install omSupply server on your computer
2. install omSupply server on your tablet and connect to it through the app
3. From the app on the tablet, click on the "pen" at the bottom right to change server
4. Select the server running on your computer
5. See error. After you have connected to the omSupply server on the computer see that the "pen" icon is no longer visible and therefore I can't go back to my local server

## Your environment 🌱

- Open mSupply Version: 2.4.00-test1
- Legacy mSupply Central Server Version: v19-00RC28

- Platform: Tablet
 
- Database type: SQLite3

**Comment by andreievg** [comment]
> I believe I should be able to change back to the server running on the local device after I connected to the omSupply server running on another device.

I agree

There is a work around for this for now, can clear app data (for client app this should be low impact). 

Should be a quick fix, so putting severity as high

**Comment by andreievg** [comment]
Since there is a work around and actually quite a lot of high severity issues atm, lowering priority

**Comment by lache-melvin** [comment]
#5466 might make this more urgent, scan button not showing on android in client mode 👀
