### ISSUE TITLE
Issues with Open mSupply v2.3.02 on Android 12

### ISSUE THREAD

**Issue by kahn-msupply** [msupply-foundation/open-msupply#5383]
## What went wrong? 😲

When opening Open mSupply v2.3.02 on Android 12, we have a 'Loading' loop. When pressing the back button once, The orange man Open mSupply logo appears and is stuck on the screen. Pressing the back button one more time takes us to the server connection page, but shows no IP address in the bottom right-hand corner, and can't seem to choose client mode.

The apk was reinstalled and data was clearer, with the same issues occurring.

After upgrading the tablets to Android 13, the issue is now resolved.

![image](https://github.com/user-attachments/assets/98b4d39d-468a-45a4-b828-23f07f89ec42)
![image](https://github.com/user-attachments/assets/3b972824-b9e2-4c56-8845-a591fc993de3)
![photo_2024-11-12_16-03-32](https://github.com/user-attachments/assets/cb24e68c-2bf8-4cd5-9fc3-0ae7c24d3ff2)

## Expected behaviour 🤔

Hopefully to have Open mSupply working on Android 10+, or specific requirements updated so the support team can check if an upgrade is possible.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. New Samsung tablet with Android 12 installed
2. Install Open mSupply
3. See error
4. Upgrade to Android OS 13
5. See error is resolved

## Your environment 🌱

- Open mSupply Version: 2.3.02
- Legacy mSupply Central Server Version: N/A
- Platform: Android
- Database type: N/A

**Comment by jmbrunskill** [comment]
I'm proposing hotfix/2.4 release for this, as we have existing clients keen to upgrade who are on versions. `Android 10, 11, 12 and 13`

**Comment by marthakeezy** [comment]
Hey James, I don't think Android 11 works either... Just tested on Zach's tablet, I get infinite loading spin when trying to launch the app

**Comment by andreievg** [comment]
Until we fix the docs it might be good to update docs to say Android 12

**Comment by marthakeezy** [comment]
Spoke to James irl :)

1. When initialising for the first time, the screen is visible however the site is not initialising
2. After restarting the app, initialisation moves to Pull Central but gets stuck after a few seconds
3. Killing the app does not stop initialisation, so need to delete and install afresh to continue QA

**Comment by roxy-dao** [comment]
Closed with #5426

**Comment by marthakeezy** [comment]
Tested V2.3.3 with James on Android 11, 12 and 14 and it initialises, syncs and re-launches fine. Moving to Done ✅
