### ISSUE TITLE
`astro_dnssd` registration crash

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5389]
## What went wrong? 😲

DNS registration is intermittently panicking:

<img width="1800" alt="Screenshot 2024-11-13 at 11 13 49 AM" src="https://github.com/user-attachments/assets/e2ea110a-18e1-4c6f-8cbb-99ba16747993">

Codewise, it looks like we're only using `astro_dnssd` for discovery, which we only start once (on server start). However, this crash can occur on app start up, or after any sync. Not sure it's used under the hood somewhere else, or if I'm missing something.

Intermittent makes me wonder if something is not waiting long enough, or if there is a race condition somewhere 🤷‍♀️ 

Unconfirmed, but appears to be causing crash for people using Rust 1.82.0, but a non-crashing panic is logged with lower Rust versions 👀 

Haven't heard any crash reports in deployment, but definitely want to investigate to confirm this is a dev only issue! 

## Expected behaviour 🤔

Backend not crashing!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Apologies, it is intermittent, though regularly reported:

1. Probably most likely with rust 1.82.0
2. Start the backend `cargo run`

## Your environment 🌱

- Open mSupply Version: v2.4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Duplicate of #5018?

**Comment by lache-melvin** [comment]
Ah yes same issue, though definitely only have one instance, will close and add to that issue
