### ISSUE TITLE
Correctly handle GS1 2D data matrix format

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5390]
## What went wrong? 😲

We have created a GS1 Barcode format interpreter based on some miss guided assumptions.

I assumed that the GS1 barcode would contain the data elements separated by `(` characters `)` as it is shown for display purposes.

However, the actual data format is more complicated, for example...

```
2.2.1 Function 1 Symbol Character (FNC1)
By definition in ISO/IEC 16022 GS1 DataMatrix uses a special start sequence to differentiate GS1
DataMatrix from other ISO/IEC Data Matrix symbols. This is achieved by using the Function 1
Symbol Character (FNC1) in the first position of the data encoded. It enables scanners to process
the information according to the GS1 System Rules.
The FNC1 (codeword 232) has two separate uses in GS1 DataMatrix:
■ Start character.
■ Separator character to separate element strings that are not in the predefined list (see
Table 2-3).


2.2.2 Concatenation
Using GS1 DataMatrix, it is possible to concatenate (chain together) discrete element strings
(Application Identifiers (AIs) and their data) into a single symbol. When the element string is of
predefined length, no separator character is required when another element string is added to it.
When the element string is not of predefined length, it must be followed by a separator character
when concatenating more element strings. The separator character may be FNC1 or the control
character <GS> (ASCII value 29 (decimal), 1D (hexadecimal)). FNC1 is the character that has the
codeword value 232. When either FNC1 or <GS> is used as a separator character, the scanner must
transfer the character value as control character <GS>.
A separator character is never required after the last element string encoded in the symbol.
```

A flow diagram for interpreting these barcodes, as well as the field length look up table etc are available here:
https://www.gs1.org/docs/barcodes/GS1_DataMatrix_Guideline.pdf (Page 15)

It turns out we already `knew` some of this and are using a front end library to pull out information such as batch number
`const batch = gs1?.parsedCodeItems?.find(item => item.ai === '10')`
https://www.npmjs.com/package/gs1-barcode-parser-mod

So with could either take the output of that library, perhaps convert to JSON? then send to backend (avoiding the need to do any complex logic in rust (Probalby the easiest option)

Alternatively we could, find or build a rust library to interpret the data.
From a quick look, similar to what I found before, there doesn't appear to be a reasonably full featured rust implementation yet...

## Expected behaviour 🤔

We should be able to handle correctly formatted GS1 Data Matrix format

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Scan a GS1 formatted Data Matrix here (Note: or create our own for testing)

PQS Asset Type: E003/002
Serial Number: S12345678
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S12345678(241)E003/002(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101
![image](https://github.com/user-attachments/assets/052ffa95-9f59-49c9-8cd1-9fcef881ca8d)

PQS Asset Type: E004/055
Serial Number: S1
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S1(241)E004/055(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101

![image](https://github.com/user-attachments/assets/37fe3908-2a34-4faf-80ea-0d222bf4eb4e)

PQS Asset Type: E004/055
Serial Number S2
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S1(241)E004/055(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101

![image](https://github.com/user-attachments/assets/472d3862-f77a-473c-89c0-317d5ead6174)

## Your environment 🌱

- Open mSupply Version: 2.4-RC1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5401

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-RC2`

- [ ] Using either Android (with camera), or Desktop (with 2d Barcode Scanner)
- [ ] Open the cold chain equipment section, and click the `Scan` button (this doesn't show on web)
- [ ] Scan one of the barcodes below
- [ ] You should be prompted to create a new asset
- [ ] If you accept, it should show a new asset with the serial number, asset type, and Warenty date populated
- [ ] The Installation date should default to today
- [ ] Scanning the same barcode again, should navigate you to the right asset (once it has been created)

> NOTE, scanning these 2d Matrixes in github `dark mode` or with a black background doesn't work well...
> NOTE: in general scanning 2d Matrixes seems much less reliable than QR Codes, need to have camera straight on for example

Scan a GS1 formatted Data Matrix here (Note: or create your own for testing)

**PQS Asset Type: E003/002**
Serial Number: S12345678
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S12345678(241)E003/002(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101
![image](https://github.com/user-attachments/assets/052ffa95-9f59-49c9-8cd1-9fcef881ca8d)

**PQS Asset Type: E004/055**
Serial Number: S1
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S1(241)E004/055(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101

![image](https://github.com/user-attachments/assets/37fe3908-2a34-4faf-80ea-0d222bf4eb4e)

**PQS Asset Type: E004/055**
Serial Number S2
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)09506000134352(11)241007(21)S1(241)E004/055(3121)820000(3131)670000(3111)630000(90)001(91)241007-310101

![image](https://github.com/user-attachments/assets/472d3862-f77a-473c-89c0-317d5ead6174)

**Comment by marthakeezy** [comment]
Also tested this as a part of #5464, build test passed ✅  Will reopen if I run into any further issues with scanning assets
