### ISSUE TITLE
Allow user to enter an asset number when creating an asset via 2d Matrix Barcode Scan

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5392]
## Is your feature request related to a problem? Please describe 👀

When importing a cold chain equipment asset via a 2d Data Matrix, the user doesn't get an opportunity to enter an asset number (serial number is used instead)

## Describe the solution you'd like 🎁

User should get a prompt to enter an asset number when confirming they want to create the asset.

### Describe alternatives you've considered 💭

Could allow asset number editing? Might be a better solution?

Should also consider consolidating the saving logic between the new asset modal and the scan button.
Potentially logic such as adding the first functional status on creation should be moved to the backend???

**Comment by adamdewey** [comment]
It would be good to allow users to edit the asset number, especially as we don't perform any checks for duplicate asset numbers across the country system currently.

**Comment by lache-melvin** [comment]
Further request for asset number to be editable: https://github.com/msupply-foundation/open-msupply/issues/5469

**Comment by CarlosNZ** [comment]
Clarifying -- are we doing:
- making asset number editable in Asset detail view
- allowing asset number input on scan
- both?

And if the first one, assume we'd just put the number in the main form and make it a field along with everything else?

**Comment by adamdewey** [comment]
> Clarifying -- are we doing:
> - making asset number editable in Asset detail view
> - allowing asset number input on scan
> - both?

For CCE, I can HCW getting confused if they don't know what the asset number should be, so for scanning I think we should default the asset number to the serial number but allow it to editable?

> And if the first one, assume we'd just put the number in the main form and make it a field along with everything else?

Sounds good to me..

**Comment by jmbrunskill** [comment]
Moved to 2.4.1 as @CarlosNZ is still in progress with this, and 2.4.1 is releasing soon enough...

**Comment by CarlosNZ** [comment]
Closed by #5651

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.4.1`

- [ ] Go to an Asset detail page
- [ ] Can edit the Asset Number
- [ ] Can save, and Asset number is updated in the Breadcrumb title at the top of the page

Build test passed - moving to Done ✅
