### ISSUE TITLE
iSC/GAPS/Cold chain: Can enter meaningless negative numbers when editing GAPS Store Properties

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5400]
## What went wrong? 😲

I don't think any of those fields supposed to allow negative value input yet the users are able to enter & save them

<img width="693" alt="Screenshot 2024-11-14 at 12 18 04 PM" src="https://github.com/user-attachments/assets/5531b9a9-c040-4737-9e4f-48c92eb7094a">

## Expected behaviour 🤔

No negative values allowed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Settings -> Configuration -> Initialise GAPS
2. Click on the edit button next to your store at the bottom
3. See new window pop up: enter negative numbers & click Save
4. The action is allowed

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome browser

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Same thing in Equipment -> Lifespan: user is able to enter negative values

<img width="842" alt="Screenshot 2024-11-14 at 3 32 02 PM" src="https://github.com/user-attachments/assets/234c60ca-6cff-44ea-8cab-a749254e78d6">

**Comment by andreievg** [comment]
Setting severity as high, should be quick fix, and seems like easy to restrict to positive numbers

**Comment by lache-melvin** [comment]
Closed by #5452

**Comment by marthakeezy** [comment]
Tested in V2.4.0-RC2, cannot enter negative numbers anymore so moving to Done ✅
