### ISSUE TITLE
iSC/GAPS/Cold chain: Cold chain -> Equipment: Category filter field dropdown is not pre-populated

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5404]
## What went wrong? 😲

Category filter field dropdown is not pre-populated (e.g. empty)

<img width="1254" alt="Screenshot 2024-11-14 at 4 37 41 PM" src="https://github.com/user-attachments/assets/bd3f46ec-1570-4aeb-83d9-51b19f05c591">

## Expected behaviour 🤔

Should be pre-populated for the users to select from, as you cannot type in the field

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Cold chain -> Equipment`
2. Click on the Equipment field dropdown
3. See empty output

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC1`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Google Chrome (browser on Mac) and Galaxy Tab A8 (Android)

- Database type: `SQLite3`

**Comment by lache-melvin** [comment]
Closed by #5453

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.4.0-RC2`

- [ ] Go to equipment list
- [ ] See category filter options - there should be 3!
- [ ] Select a category
- [ ] Add `Type` filter, and view the filter options
- [ ] Change the category filter
- [ ] Type filter options should update

**Comment by marthakeezy** [comment]
Build test passed, moving to Done ✅
