### ISSUE TITLE
iSC/Cold chain/GAPS: temperature range in Locations can be confusing if the temperature is negative

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5408]
## What went wrong? 😲

Spotted this when assigning temperatures to a location: 

<img width="927" alt="Screenshot 2024-11-14 at 5 21 01 PM" src="https://github.com/user-attachments/assets/8d0eb9c9-b8ba-457d-ac31-2fe2fa127bad">

It's not immediately readable what's going on here, is there a better formatting for temperature ranges? For example, instead of `-` can we use `to`? E.g. not `-25 - -30` but `-25 to -30`

## Expected behaviour 🤔

For example, instead of `-` can we use `to`? E.g. not `-25 - -30` but `-25 to -30`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Locations
2. Ensure you have the needed setup for GAPS testing from V2.4.0 Features Demo
3. Ensure you have a temperate range with both negative values for testing
4. Assign a temperature to a location
5. If negative temperature is chosen, see how it's not immediately readable - confusing!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac) + Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Closed in #5502

**Comment by marthakeezy** [comment]
Passed in V2.4.0-RC4, moving to Done ✅
