### ISSUE TITLE
iSC/Cold Chain/GAPS: Temperature selections should have ranges visible

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5410]
## What went wrong? 😲

When editing Inventory -> Locations and setting a temperature, the selection should have ranges visible - at the moment the user cannot see the range they are choosing until they click on it (it only appears afterwards). The names won't always make sense, so it would be helpful for the user to see the ranges straight away

<img width="546" alt="Screenshot 2024-11-14 at 8 09 53 PM" src="https://github.com/user-attachments/assets/7582e027-46d5-4f22-a925-4397c441ab9a">

## Expected behaviour 🤔

Ranges should be visible :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Locations
2. Choose an existing Location or create a new one
3. Click on the temperature field dropdown and see only names appear and not the ranges

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac) and Samsung Galaxy Tab8 (Android)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Closed by #5495

**Comment by marthakeezy** [comment]
## 🧪 Testing

`V2.4.0-RC3`

- [ ] Go to Inventory -> Locations
- [ ] Choose an existing Location or create a new one
- [ ] Click on the temperature field dropdown and see names appear with the temperature ranges
- [ ] Repeat for Catalogue -> Items -> Detail -> Variants

**Comment by marthakeezy** [comment]
Hey Aimee, 

Under Inventory -> View Stock -> Detail -> Item Variants, the temperature shows when selecting however cannot see it when saving the selection. Could this please be looked at? 🙏🏼 

![Image](https://github.com/user-attachments/assets/fb0ceb40-e9b5-4081-91ae-f02c85532dad)

![Image](https://github.com/user-attachments/assets/083920d9-4fe3-46c6-8546-734a2f445540)

**Comment by aimee-mcneil-melville** [comment]
Hi @marthakeezy,

Thanks for picking that up! 
A fix is now in for this and the temperature range should now be visible after saving a variant 😀

**Comment by marthakeezy** [comment]
Lovely, thanks Aimee! Just checking it'll be in RC4 or 5?

**Comment by lache-melvin** [comment]
Closing as completed by #5565

**Comment by lache-melvin** [comment]
Should come out with RC4 Maria!

**Comment by marthakeezy** [comment]
Tested in V2.4.0-RC4, all fixed ✅ Moving to Done!
