### ISSUE TITLE
2.4.0 Release Testing: Reports Phase 3

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#5411]
# 🧪 Testing

This issue addresses the whole testing of phase 3 enhancements to the Report module.
Epic Issue [HERE](https://github.com/msupply-foundation/open-msupply/issues/4668)

Documentation: [HERE](https://docs-staging.msupply.foundation/docs/getting_started/report/)

## Your environment 🌱

- Open mSupply Version: V2.4.00-RC1
- Legacy mSupply Central Server Version: V7.19

- Platform: Desktop app/ Browser

- Database type:

**Comment by AnushaUp** [comment]
- [ ] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):

<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">

<img width="1508" alt="Screenshot 2024-10-08 at 12 14 05 PM" src="https://github.com/user-attachments/assets/abb606e4-6566-4432-8d0d-48364dc17287">

- [ ] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

- [ ] You will be presented with a list of reports that you can generate. The reports listed below are the standard reports and will already be set up for you.
- [ ] Click on one of the reports on the report page and ensure that it shows the correct report
- [ ] The reports should be generated based on preferences which are set up in the mSupply central server

## ITEM USAGE
- [ ] We need to make sure the numbers we see in a report are accurate. The easiest way is to select an item that had absolutely zero changes to it in the last 24 months (ideally), so either create a new item or find one that is a blank canvas for QA purposes. 
- [ ] Run a report and make sure the numbers are accurate. You can check the numbers against various areas of omSupply:
     - [ ] `In Stock` = `Available Stock` under `Catalogue -> Items`
     - [ ] `Stock on Order` = Sum of quantity in Internal Orders minus any linked Inbound Shipments (so create an Internal Order and an Inbound Shipment and see if the number matches)
     - [ ] `AMC 12 Months` = create a bunch of transactions and divide by 12
     - [ ] `AMC 24 Months` = create a bunch of transactions and divide by 24
     - [ ] `Months Cover` = `Months of Stock` under `Catalogue -> Items`
     - [ ] `Monthly Usage (last month)` = `Inventory -> View Stock` -> compare the Ledger transactions
     - [ ] `Expiring in 6 months` = `Inventory -> View Stock` -> make sure to check all the batches for expiry
     - [ ] `Expiring in 12 months` = `Inventory -> View Stock` -> make sure to check all the batches for expiry
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## STOCK DETAIL
- [ ] Run a report and make sure the numbers are accurate. You can check the numbers against various areas of omSupply:
     - [ ] `Code` = check `Code` under `Catalogue -> Items` or `Inventory -> View Stock`
     - [ ] `Name` = check `Name` under `Catalogue -> Items` or `Inventory -> View Stock`
     - [ ] `Batch` = check `Batch/es` under `Inventory -> View Stock` (batches will show up as different lines)
     - [ ] The rest can be checked on the same page under `Inventory -> View Stock`
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## STOCK STATUS
- [ ] The first step is to run the report and make sure the `Status` columns show up correctly against the item. E.g. `Overstocked` items are indeed overstocked and `Out of Stock` items are indeed Out of Stock. Definitions below: 
     - [ ] `Understocked` = Months of Stock < than Min months of stock (mSupply store preference: threshold for understock)
     - [ ] `Overstocked` = Months of Stock > than Max months of stock (mSupply store preference: threshold for overstock)
     - [ ] `Out of Stock` = Stock on Hand and AMC are both 0
     - [ ] `Well Stocked` = Months of Stock is between Min and Max months of Stock
     - [ ] `No Consumption` = AMC is 0
- [ ] Then check the numbers you are seeing are accurate according to what you see under `Catalogue -> Items`. E.g. SOH, AMC and MOS should be matching.
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## EXPIRING STOCK
- [ ] Firstly, we need to check the calculations:
     - [ ] `Expiring in (days)` = Number of days left until batch expires. **Yellow**: Batches below the expiring item period (mSupply store preference: expiring items period). **Green**: Anything above the expiring items period. **Red**: Expired items.
     - [ ] `Expected Usage` = Average monthly consumption of the item multiplied by the number of months left until expiry.
     - [ ] `Stock at Risk` = Quantity of stock that will likely expire before it is used. Calculated by: **SOH - Expected usage**. If the stock is expired, then this should show all SOH for that stock line.
- [ ] Then check the numbers you are seeing are accurate according to what you see under `Catalogue -> Items`. E.g. Stock on hand should be matching.
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

Something to keep in mind: as you are testing the Reports, it is also good to make sure the reports get updated as you manipulate the items. For example, if you create an Outbound Shipment, stock on hand for that item should go down and the reports should reflect that. So don't forget to check the integrity of data!

**Comment by AnushaUp** [comment]
This error can be seen while loading reports in both omSupply android and browser.
<img width="670" alt="Screenshot 2024-11-18 at 11 22 02 pm" src="https://github.com/user-attachments/assets/d7d11fd1-bbcc-43f0-878f-d28cb73f1115">

**Comment by mark-prins** [comment]
@AnushaUp possibly the same as #5312 ?

**Comment by AnushaUp** [comment]
@mark-prins Yeah, Thankyou!

**Comment by AnushaUp** [comment]
Got this while changing the pref 
![Screenshot 2024-11-19 at 9 41 42 am](https://github.com/user-attachments/assets/30a516d0-4cce-4fa5-8ac2-c6457560b0c4)

![Screenshot 2024-11-19 at 9 40 04 am](https://github.com/user-attachments/assets/aeb20636-1b8a-4a3f-9386-3f414a03fcfd)

**Comment by AnushaUp** [comment]
## 🧪 Testing(Steps from Epic will be covered HERE)
Tested again in ` V2.4.00-RC2`
- [x] The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page (`you can find the preferences by going to mSupply -> Special tab -> Stores -> then your specific store -> Preferences tab`):
<img width="951" alt="Screenshot 2024-08-09 at 2 44 46 PM" src="https://github.com/user-attachments/assets/c18fd1de-ec53-4c0f-9191-f5d439e82619">
<img width="1508" alt="Screenshot 2024-10-08 at 12 14 05 PM" src="https://github.com/user-attachments/assets/abb606e4-6566-4432-8d0d-48364dc17287">

- [ ] When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)
- [x] You will be presented with a list of reports that you can generate. The reports listed below are the standard reports and will already be set up for you.
- [x] Click on one of the reports on the report page and ensure that it shows the correct report
- [ ] The reports should be generated based on preferences which are set up in the mSupply central server

## ITEM USAGE
- [ ] We need to make sure the numbers we see in a report are accurate. The easiest way is to select an item that had absolutely zero changes to it in the last 24 months (ideally), so either create a new item or find one that is a blank canvas for QA purposes. 
- [ ] Run a report and make sure the numbers are accurate. You can check the numbers against various areas of omSupply:
     - [ ] `In Stock` = `Available Stock` under `Catalogue -> Items`
     - [ ] `Stock on Order` = Sum of quantity in Internal Orders minus any linked Inbound Shipments (so create an Internal Order and an Inbound Shipment and see if the number matches)
     - [ ] `AMC 12 Months` = create a bunch of transactions and divide by 12
     - [ ] `AMC 24 Months` = create a bunch of transactions and divide by 24
     - [ ] `Months Cover` = `Months of Stock` under `Catalogue -> Items`
     - [ ] `Monthly Usage (last month)` = `Inventory -> View Stock` -> compare the Ledger transactions
     - [ ] `Expiring in 6 months` = `Inventory -> View Stock` -> make sure to check all the batches for expiry
     - [ ] `Expiring in 12 months` = `Inventory -> View Stock` -> make sure to check all the batches for expiry
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## STOCK DETAIL
- [ ] Run a report and make sure the numbers are accurate. You can check the numbers against various areas of omSupply:
     - [ ] `Code` = check `Code` under `Catalogue -> Items` or `Inventory -> View Stock`
     - [ ] `Name` = check `Name` under `Catalogue -> Items` or `Inventory -> View Stock`
     - [ ] `Batch` = check `Batch/es` under `Inventory -> View Stock` (batches will show up as different lines)
     - [ ] The rest can be checked on the same page under `Inventory -> View Stock`
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## STOCK STATUS
- [ ] The first step is to run the report and make sure the `Status` columns show up correctly against the item. E.g. `Overstocked` items are indeed overstocked and `Out of Stock` items are indeed Out of Stock. Definitions below: 
     - [ ] `Understocked` = Months of Stock < than Min months of stock (mSupply store preference: threshold for understock)
     - [ ] `Overstocked` = Months of Stock > than Max months of stock (mSupply store preference: threshold for overstock)
     - [ ] `Out of Stock` = Stock on Hand and AMC are both 0
     - [ ] `Well Stocked` = Months of Stock is between Min and Max months of Stock
     - [ ] `No Consumption` = AMC is 0
- [ ] Then check the numbers you are seeing are accurate according to what you see under `Catalogue -> Items`. E.g. SOH, AMC and MOS should be matching.
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

## EXPIRING STOCK
- [ ] Firstly, we need to check the calculations:
     - [ ] `Expiring in (days)` = Number of days left until batch expires. **Yellow**: Batches below the expiring item period (mSupply store preference: expiring items period). **Green**: Anything above the expiring items period. **Red**: Expired items.
     - [ ] `Expected Usage` = Average monthly consumption of the item multiplied by the number of months left until expiry.
     - [ ] `Stock at Risk` = Quantity of stock that will likely expire before it is used. Calculated by: **SOH - Expected usage**. If the stock is expired, then this should show all SOH for that stock line.
- [ ] Then check the numbers you are seeing are accurate according to what you see under `Catalogue -> Items`. E.g. Stock on hand should be matching.
- [ ] The filters should work correctly, e.g. only pulling the information you are looking for. The `Print` button should redirect you to a PDF of the report which you can print out. `Export` button is only enabled on browser/desktop app.
- [ ] Reports can also be translated -> when switching languages, make sure the page is translated in a respective language. `More` section of the menu should also be translated (and make sure to check each language!).

Something to keep in mind: as you are testing the Reports, it is also good to make sure the reports get updated as you manipulate the items. For example, if you create an Outbound Shipment, stock on hand for that item should go down and the reports should reflect that. So don't forget to check the integrity of data!

**Comment by roxy-dao** [comment]
> This translation is not functioning correctly (Tried for Portugues)

If there is no translation available then it defaults to English. The reports probably haven't been translated in Portuguese yet and the filter modal doesn't have translated implemented right now~

**Comment by AnushaUp** [comment]
> * `Stock on Order` = Sum of quantity in Internal Orders minus any linked Inbound Shipments (so create an Internal Order and an Inbound Shipment and see if the number matches)
Cannot calculate the Stock on order value.

**Comment by AnushaUp** [comment]
Closing this as Completed✅
