### ISSUE TITLE
iSC/Cold chain/GAPS: sorting by Storage Type results in infinite loading spinner

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5413]
## What went wrong? 😲

`Inventory -> Locations`: sorting by newly added Storage Type results in infinite loading spinner

https://github.com/user-attachments/assets/f5a8b66c-cb53-4b6a-8ba5-f7a0ee4a587c

## Expected behaviour 🤔

Should be able to sort as per normal

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Inventory -> Locations`
2. Create a new Location or edit an existing one
3. Assign Temperature ranges to the one you are testing
4. Go back to the main screen and attempt to sort by Storage Type
5. See infinite loading spinner - error!

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC1`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Google Chrome (browser on Mac) and Galaxy Tab A8 (Android)

- Database type: `SQLite3`

**Comment by lache-melvin** [comment]
Closed by #5454

**Comment by marthakeezy** [comment]
Tested in V2.4.0-RC2, sorting it not available anymore -> build test passed ✅
