### ISSUE TITLE
iSC/Cold chain/GAPS: buggy Cold Storage Location selection in Equipment

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5415]
## What went wrong? 😲

Quite hard to describe, but I suspect (!) what the issue might be is when one asset is assigned to a location, the location selection disappears from the dropdown for other equipment entries? 

Also, when a location is removed for an asset, you cannot add it back in. For context, I have 4 different locations, none of them are on hold, each location has been used before for testing with equipment etc. 

Captured the bugs [in this video](https://drive.google.com/drive/folders/1FomYcW13X3xZeklPu8tCfgaNI_szHnrj)

## Expected behaviour 🤔

When we edit equipment, when one location is removed, it should still be in a selection even after removal -> when the location is selected, the number should go down to three, but then back to four if it's unassigned. Also more than one equipment can be assigned to a single location, so the option should not disappear for other entries. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Unclear! But what I've done while playing around: 
2. Go to Cold chain -> Equipment and assign a Cold storage location to an equipment you are testing
3. Go to another equipment and see if that same location is available to be assigned
4. When editing equipment, assign location -> save -> unassign it -> click on the dropdown again -> see that same location is not available to be selected again
5. Buggy behaviour!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
> Also more than one equipment can be assigned to a single location, so the option should not disappear for other entries.

My understanding was the opposite - for GAPS, the location maps to only one equipment, so we can associate stock in that location with the storage capacity of that asset. Assets might have multiple locations (e.g. fridge-freezer has a fridge location and a freezer location), but those locations only belong to that one asset - can you confirm @adamdewey? 🙏

**Comment by adamdewey** [comment]
Yes, agree with @lache-melvin

`Locations` are not the location where the `CCE` is stored, they are "stock storage locations" and indicate where stock is stored. 

So 1 or more `Locations` can be mapped to a `CCE`, but only 1 `CCE` can be mapped to a `Location`

We will use the `Store` GPS coordinates to track the physical locations of CCE.

**Comment by marthakeezy** [comment]
Ohhh my bad, should have clarified the difference between the fields as I assumed Location is literally a physical location of the asset. Thanks 🙏🏼 

The other bug is still valid though, correct? -> When a location is removed from an asset -> changes saved -> if you click on the field, the recently removed location does not appear again

**Comment by marthakeezy** [comment]
No specific testing steps - just played around with the selection like I did in the original video. 

Added 6 locations to the store, some on-hold, some with no temperature ranges associated - possibly a bug incoming from that, but the original issue of deleting a location is fixed so moving to Done ✅ 

`V2.6.0-build-test-2`
