### ISSUE TITLE
Add dependency install of wasm functions for standard reports

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5417]
## Is your feature request related to a problem? Please describe 👀

Add dependency for wasm function generation.

Remove the need to manually install dependencies without which can have issues with report generation such as:

https://github.com/msupply-foundation/open-msupply/issues/5312

## Describe the solution you'd like 🎁

Install dependencies so that reports are generated appropriately by default.

**Comment by alainsussol** [comment]
Build Tested as part of #5885
