### ISSUE TITLE
iSC/Cold chain/GAPS: add Storage Type to filter selection

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5419]
## What went wrong? 😲

Checked-in with @adamdewey and it would be good to have Storage Type as a filter selection in Locations

![photo_2024-11-15 12 26 15](https://github.com/user-attachments/assets/3ca83d0b-6013-4d47-9317-5395f675dc13)

## Expected behaviour 🤔

Users should be able to filter by Storage Type if needed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Locations
2. See Storage Type is available as a column but missing from the filter selection

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: all

- Database type: SQLite3

**Comment by andreievg** [comment]
Wouldn't have many locations and very low prioirity issue that we are not likely to every fix
