### ISSUE TITLE
iSC/Cold chain/GAPS: unable to download CCE template on Android

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5423]
## What went wrong? 😲

Unable to download CCE template on Android

https://github.com/user-attachments/assets/ef19b6f0-3de9-4219-97fb-43bb5d86158f

## Expected behaviour 🤔

Should be able to download & fill out the CCE template on your tablet

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment
2. In the top right corner, click Import
3. Attempt to download the template -> nothing happens

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by lache-melvin** [comment]
Export like this isn't actually available on Android right now, but we should disable/prompt with that information!

**Comment by lache-melvin** [comment]
closed by #5455

**Comment by marthakeezy** [comment]
Hi Laché, just checking if the grammar makes sense here?

![Image](https://github.com/user-attachments/assets/e794f1c2-ad57-42b5-b471-f2101dd380a6)

Also would it make sense to remove the prompt all together rather than have it available for the user to download and then run into the prompt anyway?

**Comment by lache-melvin** [comment]
> Hi Laché, just checking if the grammar makes sense here?

I think so?

> Also would it make sense to remove the prompt all together rather than have it available for the user to download and then run into the prompt anyway?

Typical UX pattern we have followed is to keep things available, and show explanation of why that action can't be executed (rather than disable/hide) 🙏

**Comment by adamdewey** [comment]
I think the text should be: 

`File cannot be downloaded on this device`

**Comment by lache-melvin** [comment]
oh lol yep i can read 🤣

**Comment by lache-melvin** [comment]
will fix in another PR 🙏

**Comment by marthakeezy** [comment]
Thanks!

**Comment by lache-melvin** [comment]
Will be in RC4 🙏

**Comment by marthakeezy** [comment]
Passed in `V2.4.0-RC4` ✅
