### ISSUE TITLE
iSC/Cold chain/GAPS: Location under Inventory -> View Stock does not have helpful information

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5427]
## What went wrong? 😲

Might need further input from @adamdewey but I don't find the Location display under Inventory -> View Stock particularly helpful.

When looking at the page, the user can only read the first few syllables, before the line getting cut off: 

<img width="394" alt="Screenshot 2024-11-15 at 5 46 31 PM" src="https://github.com/user-attachments/assets/4d89fe8c-b9bc-4df3-bcc4-1d5e6e16da0e">

When clicking on the field dropdown, I find location names and codes useless if I can't remember their temperature range. In the same location, you can also have multiple temperatures - e.g. Shelf 1, Shelf 2, Shelf 3 which will have different ranges.

<img width="417" alt="Screenshot 2024-11-15 at 5 46 41 PM" src="https://github.com/user-attachments/assets/4017a8db-c5b4-45a8-ad6b-16cc8d4817d3">

## Expected behaviour 🤔

It would be really useful to see temperature ranges associated with locations. Maybe something can be sacrificed in that favour - e.g. do we need to show both location name and location code? What if we show Location Name -> Location Type -> temperature associated with it?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock
2. Click on any stockline to see further details
3. Click on a Location dropdown field -> see the temperature ranges don't show

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac) + Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by adamdewey** [comment]
The users should hopefully be able to identify the location from the code, but maybe we could make the dropdown a bit wider?

I imagine common locations in a warehouse would look something like this: 

Code = `A1-03-01`
Name = `Column A - Rack 03 - Shelf 01`
Type = `Room temperature`

So you would end up with `A1-03-01 - Column A - Rack 03 - Shelf 01 (Room temperature)`

In a small pharmacy they might look like this: 

Code = `Fridge`
Name = `Pharmacy fridge`
Type = `Cold storage`

So you would end up with `Fridge - Pharmacy Fridge (Cold storage)`

**Comment by marthakeezy** [comment]
Would they need to see the temperature though at the same time? Are users expected to know off by heart that Cold Storage is 2 - 8 degrees? Because that was my main concern - temperature not showing

**Comment by adamdewey** [comment]
I think that's ok, because my understanding is that they can rename those labels, so if they want they can name them to be `2 - 8 °C` instead of `Cold storage` (although they should understand that Cold storage = 2-8 °C anyway)

**Comment by Chris-Petty** [comment]
Showing the actual data sounds more robust to me @adamdewey - just inviting a location named 2-8 that's configured for -20C to -10C haha

**Comment by adamdewey** [comment]
> Showing the actual data sounds more robust to me @adamdewey - just inviting a location named 2-8 that's configured for -20C to -10C haha

Good point!

Would be nice if we could show the actual range, I agree

It does get a bit confusing between the name and location type and temperature range with it all concatenated, but better to have correct info there

**Comment by marthakeezy** [comment]
I do find it a bit cluttered - is it as important to show the code of the location as the name/temperature range?

**Comment by andreievg** [comment]
Triage, from what we've seen it's the 'code' and very short description that is used in the wild, so not likely to be a problem, closing as we think we won't have time to ever address this
