### ISSUE TITLE
iSC/Cold chain/GAPS: Location Types and Temperature Ranges are not showing when repacking an item

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5429]
## What went wrong? 😲

Location Types and Temperature Ranges are not showing up when repacking an item

![photo_2024-11-15 18 19 32](https://github.com/user-attachments/assets/38a80a11-b514-4c78-b546-e752562c1c4b)

## Expected behaviour 🤔

Location Types and Temperatures should show for consistency with the rest of the platform :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock
2. Click on a specific stock line and then to Repack at the top
3. Once the Repack window pops up, you can see the Location Types and Temperature are not showing

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac) + Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by andreievg** [comment]
Triage, concluded that only show location name in repack
