### ISSUE TITLE
Many Documentation pages are not available in French while navigating through the omSupply app

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5430]
## What went wrong? 😲

Manage Facilities, Dispensary > patients, Dispensary > prescriptions, Catalog > Assets, Inbound > Supplier Credits, Outbound > Customer Credits, 
![image](https://github.com/user-attachments/assets/a6b465b0-a46b-4106-9206-05d151e38167)

## Expected behaviour 🤔
I think that documentation should be available.

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Set omSupply language to french
1. Go to any of the section listed in the description
2. Click on The Doc Icon, the first one at the top of the 4 buttons at the bottom of the menu bar on the left side of the screen.
4. See Page not found error.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version: v19-0dev27

- Platform: omSupply desktop, Chrome Version 131.0.6778.70 (Official Build) (64-bit)
 
- Database type: SQLite3

**Comment by roxy-dao** [comment]
These pages don't have a french translation yet. Can @Rajajajaja or @Cyrilbrites translate these pages?

**Comment by andreievg** [comment]
Closing will organise setup for @Rajajajaja

**Comment by roxy-dao** [comment]
Cyril has kindly translated/updated patients, prescriptions, outbound returns, remote authorisation, suppliers, internal orders and inbound shipments (:

**Comment by alainsussol** [comment]
Translations seems to have not be done yet so I am leaving this issue in the needs build testing so that I can check from time to time.

**Comment by marthakeezy** [comment]
@msupply-foundation/french-translators

**Comment by Rajajajaja** [comment]
Linking the Trello page: https://trello.com/c/Qt2FuZ8N 

@marthakeezy feel free to add yourself to the card and amend what is needed
