### ISSUE TITLE
Patient age off by one day in date picker compared to summary toolbar display

### ISSUE THREAD

**Issue by noel-yeldos** [msupply-foundation/open-msupply#5438]
Discovered while investigating #5218 

## What went wrong? 😲
Patient age in the date picker (in the patient form) is one day less than what is displayed in the patient summary in the toolbar. The issue seems to be with the date picker as selecting today's date and yesterday's date still returns an age of 0 days. 

Explanation from Laché:
"It is incorrectly using getDateOrNull, which is adding the +13 hours for NZT... so the patients age in days will only increase after 1pm"

## Expected behaviour 🤔
Date picker age in days should match the toolbar age in days. When selecting yesterday's day the age should be 1 day and selecting today's date age should be 0.

## How to Reproduce 🔨

Needs to be done before 1pm to see the bug

Steps to reproduce the behaviour:

1. Go to patients tab
2. Click on create/edit patient
3. Add a DOB using date picker that sets the age to be displayed in days
4. Save the changes
5. See the discrepancy between ages in the date picker and the toolbar

## Your environment 🌱

- Open mSupply Version: 2.4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
See #5470 (dupe) for more

**Comment by marthakeezy** [comment]
Still happening in `V2.5.0-reports` 

Also ran into #5859 while testing

<img width="1252" alt="Image" src="https://github.com/user-attachments/assets/ce53a22e-eaca-4516-ad9c-a7a32a378629" />

**Comment by noel-yeldos** [comment]
@marthakeezy nice catch! I think we can close this issue as patient age being different has been fixed. We can fix the actual date of birth being off by one day here #5869

**Comment by marthakeezy** [comment]
Got confirmation from Laché and Noel: 

The original issue of age showing differently is now fixed, however the date picker is now different. 

It is covered in #5869 so closing this one and moving to Done ✅
