### ISSUE TITLE
Unable to run Expiring Items report

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5443]
## What went wrong? 😲

Running an Expiring Items report results in this: 

https://github.com/user-attachments/assets/4c17eeba-f8ef-40c4-95d3-f5cfb81f2787

Error: 

<img width="1437" alt="Screenshot 2024-11-18 at 2 27 58 PM" src="https://github.com/user-attachments/assets/6cffda7d-a982-4d84-bc09-bb4ab1f8b265">

## Expected behaviour 🤔

Should be able to run the report

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports -> Expiring Items
2. Attempt to run it
3. Run into the error

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser on Mac)

- Database type: SQLite3

**Comment by myspace20** [comment]
I'm working to resolve it

**Comment by roxy-dao** [comment]
Fixed in #5482
