### ISSUE TITLE
iSC/Cold Chain/GAPS: Equipment Installation Date follows a different format to the rest of the dates in omSupply

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5447]
## What went wrong? 😲

Cold chain -> Equipment: the installation dates follow a different format to the rest of the dates in omSupply - could we please standardise the appearance?

How it looks now: **YYYY-MM-DD**

<img width="723" alt="2" src="https://github.com/user-attachments/assets/6d6cddc1-39bb-4d2e-b05f-ec91719a5ac9">

How it should look: **DD-MM-YYYY**

<img width="440" alt="1" src="https://github.com/user-attachments/assets/26f13bc2-1095-4a34-ac23-354a3397290e">

## Expected behaviour 🤔

Should be `DD-MM-YYYY`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment
2. Create a new asset or modify an existing one
3. Under Installation Date, select a Date (note - at that moment, the date appears normally)
4. Navigate back to the overall view of all assets - see column Installation Date now shows the date as YYYY-MM-DD
5. Inconsistency!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser on Mac) + Samsung Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
<img width="1427" alt="Screenshot 2024-11-20 at 11 04 21 AM" src="https://github.com/user-attachments/assets/c8fc0422-72e4-4765-be23-3f5f11bc84d0">

Same spotted when importing cold chain assets into omSupply

**Comment by noel-yeldos** [comment]
@marthakeezy I have a PR to fix first issue! Could you please give me steps to recreate the import related issue?

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.4.0-RC3`

- [ ] Go to Cold chain -> Equipment
- [ ] Create a new asset or modify an existing one
- [ ] Under Installation Date, select a Date
- [ ] Navigate back to the list view of all assets - column Installation Date now shows the date as DD/MM/YYYY

**Comment by marthakeezy** [comment]
Hey Noel, do you think you could please take a look at this? 

In V2.4.1-RC2, Warranty Start & End dates follow a different format

<img width="1474" alt="Dates" src="https://github.com/user-attachments/assets/5886946b-a6e1-4e9f-9fb9-318f5712a11d">

Thanks! :)

**Comment by andreievg** [comment]
@marthakeezy can you open new issue please (and close this one), this looks like a different area (similar problem though) and the PR that @noel-yeldos made resolves original issue

**Comment by marthakeezy** [comment]
Oki!
