### ISSUE TITLE
Navigating back from editing requisition line goes back to requisition list rather than to the requisition being modified

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5448]
## What went wrong? 😲

When editing a requisition line, pressing back in browser goes back to the requisition list rather than the requisition page that you were previously on.

https://github.com/user-attachments/assets/73763605-4ccb-4ad6-8901-f8e2f08b4421

## Expected behaviour 🤔

When editing a line, going back in the browser should take you back to the requisition you were editing.

## How to Reproduce 🔨

1. Edit a requisition (I was testing customer / response requisitions)
2. Edit a line in the new UI
3. Press back
4. It has gone all the way back to the requisitions list

## Your environment 🌱

- Open mSupply Version: 2.4.0 in dev
- Legacy mSupply Central Server Version: 7.18 dev

- Platform: firefox

- Database type: pg

**Comment by roxy-dao** [comment]
Closed in #5451

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.4.00-RC2`


- [ ] Create new requisition -> Click back. Should be previous page
- [ ] Go to a requisition line
- [ ] Navigate to a different line -> Click back. Should be previous item

**Comment by AnushaUp** [comment]
Tested and PASSED
