### ISSUE TITLE
Suggested quantity is not calculated for Manual requisitions in omSupply

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5458]
## What went wrong? 😲

The Suggested quantity seems to be always 0. 

https://drive.google.com/file/d/1sRNEtT-pSOdXn2BTx8cdqmrSrtOgUWLZ/view?usp=sharing

@roxy-dao is saying that Suggested quantity is not calculated yet for Manual Requisitions and that an issue should be opened

It doesn`t seem to be calculated either when you are doing a manual Requisition on mSupply OG.  When creating an internal order on mSupply OG in the IC context , the calculation seems to be the following

Suggested Quantity= [(Max MOS + Months lead time) * AMC] - Stock available
https://drive.google.com/file/d/1gbknIX3q3EyDFxE6m1h5402vvBPMgCRm/view?usp=sharing
 

## Expected behaviour 🤔
I am not sure. I suppose it depends on the requirements to know if it needs to be calculated or not considering that some of this data needs to be available and some of what is used is entered manually like the AMC

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new program requisition
2. Tap on a line and values  to initial SOH, Stock arriving , outgoing, Losses, Additions and AMC
3. Check Suggested quantity
4. See error. The Suggested quantity is still 0

## Your environment 🌱

- Open mSupply Version: 2.4.0RC1
- Legacy mSupply Central Server Version: v19-0RC27

- Platform: Android 14

- Database type: SQLite

**Comment by mark-prins** [comment]
While EXF18 is for internal orders, EXF08 & EXF19 are for customer requisitions. In that there is the comment about calculated quantities:

<img width="640" alt="image" src="https://github.com/user-attachments/assets/987c0e5e-6eaa-4d35-b0e3-166ec4471700">

And then under the heading **EXF01 Bis, EXF06 Bis, EXF08 Bis -  Manual Customer requisition**
there is the line "All stock data columns must be editable except for the ones that are the result of a calculation (available stock, AMC, suggested quantities)"

So while mSupply doesn't calculate - there is something of an implicit expectation that there will be a suggested quantity value which is useful when comparing to the ordered quantity. Currently it would only compare to `0` for each item.

**Comment by alainsussol** [comment]
@roxy-dao @andreievg 
I have looked at the code for Manual requisition and it is not calculated. We put 0 for all all lines so whatever requested quantity you put, you will have to put a reason. I am not sure if that was the original requirement or not. 

![image](https://github.com/user-attachments/assets/4f0d521a-9633-49f3-94f1-3229a59ab745)

It doesn`t mean that we can`t do it though as stated by @mark-prins in the previous [comment](https://github.com/msupply-foundation/open-msupply/issues/5458#issuecomment-2484692594)

**Comment by alainsussol** [comment]
@mark-prins @roxy-dao @andreievg 

My mistake but the suggested quantity is calculated for manual program requisition of stores that have mSupply. The customer I was testing with before even though it has a name like a store, it was in fact an external customer so that was why the Suggested quantity and AMC was probably not calculated. 

https://drive.google.com/file/d/18nlKI04K-vwYtR2PElGiqyhmWTfApkJ_/view?usp=sharing

I think we can close this...

**Comment by roxy-dao** [comment]
> @mark-prins @roxy-dao @andreievg
> 
> My mistake but the suggested quantity is calculated for manual program requisition of stores that have mSupply. The customer I was testing with before even though it has a name like a store, it was in fact an external customer so that was why the Suggested quantity and AMC was probably not calculated.
> 
> [drive.google.com/file/d/18nlKI04K-vwYtR2PElGiqyhmWTfApkJ_/view?usp=sharing](https://drive.google.com/file/d/18nlKI04K-vwYtR2PElGiqyhmWTfApkJ_/view?usp=sharing)
> 
> I think we can close this...

Adding on: this is only for program requisitions

**Comment by mark-prins** [comment]
Taking @alainsussol's suggestion 😉
