### ISSUE TITLE
iSC/Cold chain/GAPS: asset installation date is wrong

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5459]
## What went wrong? 😲

Added 3 assets on `19/11/2024`, Installation date is showing `18/11/2024`

<img width="1367" alt="Screenshot 2024-11-19 at 10 23 31 AM" src="https://github.com/user-attachments/assets/d5da087c-fe71-4b62-ab91-3ce6eee90248">

## Expected behaviour 🤔

Should be showing an up-to-date installation date

## How to Reproduce 🔨

Steps to reproduce the behaviour:

I am a bit unsure! Yesterday (18/11/2024), when I was adding assets, the installation date was correct. However, today, I deleted all three and re-added them to test a scenario, and installation date appeared as yesterday. Can it be that if an asset was once added to the store, and then removed, installation date gets stored somewhere and even if the asset is re-added later, installation date will show up as the original one?

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Setting as `High` as there is no workaround to correct the installation date... Apart from not deleting an asset

**Comment by roxy-dao** [comment]
Installation date is saved as a date instead of datetime, so can't offset date with local date

**Comment by Chris-Petty** [comment]
@roxy-dao if deleting the asset then adding it again, I'd have thought the installation date would have still moved to today though? It appears that there is [soft deletion for assets](https://github.com/msupply-foundation/open-msupply/blob/0ce078c3816ee15750c209495236a280466c70bf/server/repository/src/db_diesel/assets/asset_row.rs#L30), so it could be as @marthakeezy is sniffing out - adding the same asset just revives the old record with the old installation date.

@jmbrunskill might know off the top of his head - I can't tell from the repo layer, conflict resolution there is on the primary key which I assume is a new generated UUID when adding the same asset again. Could be service or f/e layer tricks to resurrection though?

**Comment by lache-melvin** [comment]
@marthakeezy can you check the assets again now - is the date showing correctly now that it is the afternoon? Suspect Roxy is right - timezones getting banged up until we cross over midnight UTC?

**Comment by marthakeezy** [comment]
Still there at 4:17PM

<img width="1369" alt="Screenshot 2024-11-19 at 4 17 52 PM" src="https://github.com/user-attachments/assets/2016dfe1-f3c9-4829-8091-0b45e6073441">

**Comment by lache-melvin** [comment]
Ah ok great to know - so you can confirm this is only for adding back deleted assets? New assets are fine?

**Comment by marthakeezy** [comment]
Yep! Just scanned a new one and the date shows as `19/11/2024`

**Comment by andreievg** [comment]
Very rare use case, going to close (will re open if customer identifies this as a problem), good catch though
