### ISSUE TITLE
Item Variants: Deleting a variant that is bundled with item doesn't soft delete bundled item

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5461]
## What went wrong? 😲
Deleting a variant that is bundled with an item and then deleting that variant doesn't soft delete the bundle and still allows it to show up on the linking item's 'bundled on' list

## Expected behaviour 🤔
The bundled_item should be soft deleted if the variant has been deleted.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create Item A variant 
2. Create Item B variant bundle with Item A
3. Go to Item A and see that Item B shows up as being bundled on Item A
4. Delete Item B variant
5. Go back to Item A - see that Bundled on shows `-` for item variant

## Your environment 🌱

- Open mSupply Version: 2.4.0-RC1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5478

**Comment by marthakeezy** [comment]
<img width="1234" alt="Screenshot 2024-11-22 at 10 49 37 AM" src="https://github.com/user-attachments/assets/74b1dc3a-4c11-4b9f-88d4-ec5fc39d90b4">

Is this the same issue you were seeing Roxy?

**Comment by roxy-dao** [comment]
Possible? 

Is that a deleted bundled (deleted from the variant itself)?

**Comment by marthakeezy** [comment]
Ahhh... Yes? I think so

**Comment by marthakeezy** [comment]
I had an item (needle) with a variant 1
That variant is bundled with another item's (Vaccine) variant 2
Then I deleted variant 1, and under variant 2 I can see undefined - undefined

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in `V2.5.1`


- [ ] Define two items with item variants
- [ ] On item A variant 1 - bundle item B variant 1
- [ ] Go to item B and delete variant 1
- [ ] Go back to item A - no item B variant 1 in the bundled item table (and no blank row where it "should" be)
- [ ] Test this in both directions (no lingering deleted variants as the "base" or the "bundled" item!)
