### ISSUE TITLE
Manual requisitions some UI improvements to consider

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5463]
## What went wrong? 😲

1. If you change directions while navigating using the Previous and Next buttons, both buttons are highlighted blue

https://drive.google.com/file/d/1AmPTNf7vATgDiEfnjViMwOe354WVAaQ0/view?usp=sharing

2. When using the Next and Previous button to navigate the list on the left stay static rather than following navigation movement when going lower than what is visible on the page.
https://drive.google.com/file/d/1t-gFSN6GVKnb09mruWjaDCMpQ0rCv-ig/view?usp=sharing

3.  Some french letters like "É"  seems to be difficult to manage but the icon seems strangely fit the item name :). It is the same in mSupply OG 

![image](https://github.com/user-attachments/assets/66928453-a5e5-4c69-828b-cf61ecc0a90a)

![image](https://github.com/user-attachments/assets/e68732de-d032-4b89-8713-f7ac46bda936)

 

## Expected behaviour 🤔
It would be nice...

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Setup for program requisition (see video https://drive.google.com/drive/u/1/folders/1lHLFThoBkbWwB2BSP9fRT6STN4j0YzWS)
1. Go to Distribution > Requisition
5. Click on 'New Requisition'
6. Create a program requisition
7. See error

## Your environment 🌱

- Open mSupply Version: 2.4.0RC1
- Legacy mSupply Central Server Version: v19dev27

- Platform: Android 14

- Database type: SQLLite3

**Comment by Chris-Petty** [comment]
The blue thing isn't great, but I'd say low/normal. The focused row in the list being way off screen is fairly unpleasant though!

**Comment by roxy-dao** [comment]
Closed in #5587

**Comment by alainsussol** [comment]
# 🧪 Testing
Tested on v2.4.0RC6


- [ ] Create a manual requisition (can be program too) with lots of item lines 
- [ ] Use previous/next to scroll through items
- [ ] Current item in list view should stay in view **-PASS-**
