### ISSUE TITLE
iSC/Cold chain/GAPS: error when trying to scan an asset

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5464]
## What went wrong? 😲

Borrowed Noel's tablet for testing purposes, however ran into this error when attempting to scan an asset.

![Error1](https://github.com/user-attachments/assets/76a3fd15-51b5-438b-a02e-d499de690b83)

![Error2](https://github.com/user-attachments/assets/16c34cf8-2244-4637-9abe-28ec81f1841c)

## Expected behaviour 🤔

No errors - able to scan the asset

## How to Reproduce 🔨

Steps to reproduce the behaviour:

I cannot reproduce on my tablet, however was able to recreate this error a few times on Noel's tablet: 

1. Go to Cold chain -> Equipment (on Android)
2. Scan an item, use the barcodes from #5397 testing steps
3. Run into the error

Some things I thought to check: 
1. Noel's tablet runs V2.4.0-RC1
2. Admin user has the right permissions (e.g. the user can add/edit assets etc for the store we were working on)
3. Adding an asset manually worked, however scanning didn't

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Galaxy Tab A8 (Android)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Setting as High until I can find someone else who can recreate the issue

**Comment by jmbrunskill** [comment]
@marthakeezy I think these barcodes are the old style ones. I'll update the test issue with the correct barcodes...

We found out we hadn't originally formatted the 2d DataMatrix properly so have updated to the correct format in this PR
https://github.com/msupply-foundation/open-msupply/pull/5401

But we missed updating the barcodes in the testing instructions! Sorry!

I've updated the test issue: https://github.com/msupply-foundation/open-msupply/issues/5397

@marthakeezy  Can you please re-test with the correct barcodes, and if it's working close this issue?

**Comment by marthakeezy** [comment]
Hmm will test once I am back to my tablet, but the thing is... The old barcodes worked on my tablet, but not Noel's (e.g. I was able to use the ones from the old instructions). Will give it another go on mine and Noel's and see how it goes though!

**Comment by lache-melvin** [comment]
Would be good to also check the version on Noel's tablet! I know some people had test versions installed instead of the RC1 build yesterday? This error looks like an alert from a test build...

> ![Error1](https://github.com/user-attachments/assets/76a3fd15-51b5-438b-a02e-d499de690b83)

**Comment by marthakeezy** [comment]
I've upgraded to V2.4.0-RC1 on both tablets (mine and Noel's) and scanned the new barcodes, and it worked! Not sure if it was a problem with RC or with the QR codes, but in any case happy to close the issue and reopen if I run into the same error :)
