### ISSUE TITLE
iSC/Cold chain/GAPS: Rows per page does not get updated/save when importing cold chain equipment

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5465]
## What went wrong? 😲

Rows per page selection does not get updated/save when importing cold chain equipment!

https://github.com/user-attachments/assets/31cf3cd8-e9a9-4c76-8dc8-d7dd57d8482e

At first, I thought maybe it doesn't work because there are less than 20 entries, but here is an expected behaviour where I have 8 entries but still able to change how many are displayed on the page

https://github.com/user-attachments/assets/6f1b8eab-e5d7-4fdc-8891-c112bc02a30a

## Expected behaviour 🤔

Should be able to save the selection

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to cold chain -> Equipment
2. Import -> select a file (if you don't have a sample, you can export the assets you have and then import the same file for ease of testing)
3. Should see a modal with items imported -> try changing how many you see per page
4. See error!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Setting as `Normal` as you can still click between pages and see information

**Comment by marthakeezy** [comment]
Hey James! Just imported 24 assets, on the modal where the user is importing, the rows per page does not work. However, once imported and on the overview page of all assets in the store, rows per page work as expected :)

Attached the video ->>> [here](https://drive.google.com/drive/folders/10JQBHgKNGbpRMgXMsxfdw9tg3K00hqs2)

**Comment by jmbrunskill** [comment]
Thanks @marthakeezy does clicking on page 2 work?

**Comment by jmbrunskill** [comment]
Thank you, I think we can leave as normal then...

**Comment by andreievg** [comment]
Looks like a problem but we have very limited capacity for this and next release, so not assigning milestone -> hopefully get's picked up by new devs

**Comment by marthakeezy** [comment]
Heyo! 

The bug is still present in V2.4.0, reopening the issue :)

https://github.com/user-attachments/assets/e77c46d2-cb49-487c-9a01-23a982d9bb1e

**Comment by aimee-mcneil-melville** [comment]
Hey Maria,

This went into develop instead of v2.4.0, will be fixed for v2.5

Thanks!

**Comment by marthakeezy** [comment]
Cheers!

**Comment by marthakeezy** [comment]
Tested in V2.5.0-RC5, works :) Moving to Done! ✅
