### ISSUE TITLE
Can only scan Equipment on server

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5466]
## What went wrong? 😲
I can't scan equipment when I'm running as a client.

## Expected behaviour 🤔
Should be able to run regardless of client or server?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run as client
2. Go to Equipment
3. See that `Scan` button is missing

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version: v2.4.0-RC1

- Platform: Android

- Database type:

**Comment by marthakeezy** [comment]
#5464 possibly related as Noel was running a client and not server + client?

**Comment by marthakeezy** [comment]
Actually I think it's the same issue

**Comment by roxy-dao** [comment]
There's no scan button at all when you run as Client, so you can't scan

**Comment by Chris-Petty** [comment]
Suuurely needed. Is this regardless of Android or Windows?

Many places operate with a windows server in an inaccessible location and desktop clients throughout the facility. So they'll definitely want it to work from clients!

**Comment by lache-melvin** [comment]
Have investigated a little, actually looks like the same issue as this: #5376

**Comment by lache-melvin** [comment]
P.S. works fine on emulator but can reproduce on tablet 😱

**Comment by roxy-dao** [comment]
> P.S. works fine on emulator but can reproduce on tablet 😱

Think it's fine to close it as a dup of #5376 for now and can reopen if it is actually an issue and not because of the connectedServer
