### ISSUE TITLE
Requisition's supply quantity is incorrect

### ISSUE THREAD

**Issue by zachariah-at-msupply** [msupply-foundation/open-msupply#5471]
## What went wrong? 😲

In the requisitions tab, after entering quantity to supply, the wrong supply quantity was shown. 5000 was entered but in the list view it was shown as 10,000. However, in the detail view it was shown correctly, and the remaining quantity field was also correct.

## Expected behaviour 🤔

The quantity to supply entered when supplying a requisition should be shown by the supply column in the list view.

## How to Reproduce 🔨

Go to requisitions tab, click supply requisition
Steps to reproduce the behaviour:

1. Go to requisitions
2. Select a requisition
3. Click on a line
4. Enter a quantity in the 'quantity to supply' field
5. Click close
6. See that the quantity in the supply column is different from the quantity you entered in the 'quantity to supply' field

## Your environment 🌱

- Open mSupply Version: 2.4.00-RC1, android 11
- Legacy mSupply Central Server Version: 7.18.16 desktop (macOS) running from Github mSupply master branch
- Database type: SQLite3

https://github.com/user-attachments/assets/e8fdf5cb-4f84-4440-95f6-58436c954ab0

**Comment by zachariah-at-msupply** [comment]
Bonjour Alain!

I am very happy to meet you again! I remember our fine trip to Cote d'Ivoire! And as a result of that trip, there is now an office there. Brilliant.

How are you?

Zachariah

**Comment by roxy-dao** [comment]
Closed in #5477

**Comment by alainsussol** [comment]
# 🧪 Testing



- [ ] Edit supply quantity in a requisition
- [ ] Go back to detail view
- [ ] See that supply quantity in table matches supply quantity in page
