### ISSUE TITLE
iSC/Cold chain/GAPS: export time shows in UTC when exporting cold chain assets

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5479]
## What went wrong? 😲

When exporting cold chain assets, any time shows in UTC instead of local time, for example: 

`Asset showing in omSupply:`

<img width="486" alt="Screenshot 2024-11-19 at 4 58 40 PM" src="https://github.com/user-attachments/assets/d9954812-e9bb-4ea9-ac9b-007fc9345fe9">

`Same asset in the export list:` 

<img width="797" alt="Screenshot 2024-11-19 at 4 58 09 PM" src="https://github.com/user-attachments/assets/eb298e95-948c-450d-b390-e8c44f625a3a">

## Expected behaviour 🤔

Time should be same, so export should show local time instead of UTC

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to cold chain -> equipment
2. Create a new asset - when clicking on it, note under Log created date and time
3. Go back to the equipment list and export the equipment
4. Find your newly created asset in the spreadsheet and note the created date/time
5. It's different :)

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser on Mac)

- Database type: SQLite3

**Comment by Chris-Petty** [comment]
Times and computers are the devil! @marthakeezy this depends on the desire of the export. If you export with the intent of showing to stakeholders, yea I agree with you. If you export with the intent of importing into another system... generally the UTC time is a safer bet. Not that this is a truly UTC formatted string so it's not 100% good for that either I think.

**Comment by andreievg** [comment]
Please update the header to indicate that's it's UTC or GMT
