### ISSUE TITLE
Unable to delete lines from a stocktake

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5492]
## What went wrong? 😲

Unable to delete stock lines from a stocktake (but only on newly created ones). If you navigate away and back, and attempt to delete again, it works just fine!

Video of the bug is attached ->>> [here](https://drive.google.com/drive/folders/1StzJm0qnNxHrDr94l9xigjR9et2WigET)

## Expected behaviour 🤔

Should be able to remove lines even if the stocktake is freshly created

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> Stocktakes
2. Create a new stocktake and add some items to it
3. Add counted lines as well as placeholder lines (not yet counted) for testing purposes
4. Attempt to delete either, should run into an error
5. Navigate away and then back -> should be able to delete the rows just fine 

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC2
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Not sure if this is `High` or `Hotfix`, there is a workaround of navigating away and removing the stocklines, but not sure how obvious it is to the user

**Comment by roxy-dao** [comment]
Merged in #5608

**Comment by marthakeezy** [comment]
# 🧪 Testing

`Tested in V2.4.0-RC6`

- [ ] Create a new stocktake
- [ ] Add an item to the stocktake
- [ ] Try to delete the stocktake lines
- [ ] Note: Shouldn't refresh or navigate away from the stocktake when doing this

Also tested on an old stocktake that had items already and on an old stocktake with newly added items, and everything seems to work! Moving to Done ✅
