### ISSUE TITLE
Sort doesn't work on some reports

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5505]
## What went wrong? 😲
Some of the sort filters don't seem to be working and some sort but then sort incorrectly down the line (example below)
![Screenshot 2024-11-22 at 8 00 30 AM](https://github.com/user-attachments/assets/a9dff5cd-3f2a-4e17-a3bb-601c97d4c3dc)

Check all reports to see if they are sorting properly

Also sort seems to be by casing as well. It first sorts capitals before lowercase... Is this something we want? Imo sorting should ignore casing? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: v2.4.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by alainsussol** [comment]
Testing Results [here ](https://github.com/msupply-foundation/open-msupply/issues/5885#issue-2754890720)
