### ISSUE TITLE
Initial SOH column is not label as Stock on Hand for response requisitions transferred from Internal Orders 

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5507]
## What went wrong? 😲

If I understand correctly from the test below. The Initial Stock on hand label should become Stock on Hand when response requisition are created from the transfer of a customer Internal order

> - [x] For requisitions transferred from Internal Orders: 
>    - [ ] Initial stock on hand should change to stock on hand in the line edit page 

But in fact it is not. 
See requisition Initial SOH column
https://drive.google.com/file/d/1AWpEfKUZs2Js0BNmN_Ud8GSnJDGOP3ci/view?usp=sharing

Same thing for the corresponding field in the line edit page
https://drive.google.com/file/d/1deObD8oICbiBsE6DyASfOeHN4d3le7ir/view?usp=sharing

## Expected behaviour 🤔
Label Initial SOH should become Stock on hand

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an Internal order in a customer store and SYNC 
2. On omSupply sync to receive the request requisition
3. Open the requisition
4. See error. Wrong column label Initial SOH instead of Stock on hand
5. Open a requisition line
6. See error. Wrong Field label Initial SOH instead of Stock on hand

## Your environment 🌱

- Open mSupply Version: omSupply 2.4.0
- Legacy mSupply Central Server Version: v19.0dev27

- Platform: Android 14

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Can you try test this again Alain? In column view should be `Their SOH` and in line page edit should be `Stock on Hand`

**Comment by alainsussol** [comment]
@roxy-dao 

Hi Roxy, 

It is working so I am closing this.
