### ISSUE TITLE
iSC/Cold chain/GAPS: item variant ratio display is confusing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5510]
## What went wrong? 😲

Was playing around with item variants and found the ratio is display is confusing - e.g. it takes me a while to figure out the formula and understand what relates to what in the ratio. Further comment from @adamdewey: 

`It would be nice if we could do the sentence thing - e.g. "1 vial bundled with 25 syringes"`

Screenshots of 2 variants are attached ->>> [here](https://drive.google.com/drive/folders/1SLjZOXU0a88gbQwTmJaGCZyjlwiVhzqf)

## Expected behaviour 🤔

It would be nice to include the sentence explanation, e.g. X of this item to Y of this item

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Items
2. Select an item for testing and go to Variants
3. Create a variant and bundle this variant with another variant
4. Specify the ratio - see the ratio show up under one variant, and the reverse of the ratio show up under the bundled one
5. Confusing relation between the two!

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC2
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser on Mac)

- Database type: SQLite3

**Comment by andreievg** [comment]
Putting as low priority, tempting to close, these configurations should be done on central server and should be part of training to explain the ratio.

**Comment by andreievg** [comment]
Maybe just a ration as a fraction

**Comment by adamdewey** [comment]
Ok to close for now, although I think likely bundling might become part of stock management in the future - e.g. procurement, ordering, distribution

Would probably be nice to make it clear to users what is going on and why certain things happen for those use cases

**Comment by mark-prins** [comment]
Taking Adam at his word and closing for now 🙏
