### ISSUE TITLE
Capitalise Repack in View Stock -> Ledger

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5511]
## What went wrong? 😲

Minor request - can Repack please be capitalised to match the rest of UI under `View Stock -> Ledger`

<img width="1199" alt="Screenshot 2024-11-22 at 11 33 17 AM" src="https://github.com/user-attachments/assets/de03813e-df6a-45ea-9598-0ef0bb15606e">

## Expected behaviour 🤔

Should be `Repack` not `repack`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to `Inventory -> View Stock`
2. Select an item and Repack it
3. Go to Ledger -> see it showing as `repack`

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC2
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by andreievg** [comment]
Should be a very small change for translations mapping

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.5.0-reports`



- [ ] Navigate to Inventory -> View Stock
- [ ] Click on an item to open detail view
- [ ] Click ledger
- [ ] Ensure there is a repack or inventory adjustment event
- [ ] See that repack is now Repack
- [ ] Change language and check that name values are translated
