### ISSUE TITLE
Remove dose from the item variant

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5512]
## Is your feature request related to a problem? Please describe 👀

Part of https://github.com/msupply-foundation/open-msupply/issues/5432

Current vaccine variants define a number of doses that can be different from the item.
However this field isn't used when dispensing or vaccine cards, so it creates confusion for users as to the purpose.

## Describe the solution you'd like 🎁

Remove the field from the UI and database

### Describe alternatives you've considered 💭

Could remove just from the UI, but that could create other confusion in future.

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.6.1-RC5`

- [ ] Create, and edit item_variants
- [ ] Make sure they all work as expected.

Just played around with item variants, they seem to be all working okay, including bundling and packaging. Moving to done, and can raise individual bugs/issues if anything is wrong during V2.7 release testing
