### ISSUE TITLE
Allow setting item_variant during stocktake

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5515]
Part of https://github.com/msupply-foundation/open-msupply/issues/5432

## Is your feature request related to a problem? Please describe 👀

During stock take, there's no way to set an item_variant on a stock_line
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/09971a59-6d64-4f3a-a78b-1fdddd21d633">

## Describe the solution you'd like 🎁

The same item_variant selector we have added to inbound shipment

**Comment by jmbrunskill** [comment]
Consideration needs to be made if there's any space constraints on tablets that might affect usability of stocktakes when adding this.

**Comment by jmbrunskill** [comment]
Note: As a work around Item Variant can be set on stock lines from the View Stock view after a stocktake
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/ff46f3d3-f367-4408-8695-86ddbfc9d75c">

**Comment by lache-melvin** [comment]
Closed by #5552

**Comment by AnushaUp** [comment]
Tested in V2.7RC4. Working as expected ✅
