### ISSUE TITLE
Shouldn't check for requested != suggested if store preferences for requisition extra fields is off

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5538]
## What went wrong? 😲

Show extra fields on requisitions not set causes error when Suggested quantity differs from requested quantity.

In back end, we should only throw an error on differs IF show extra fields store preference is set.

**Comment by roxy-dao** [comment]
Closed in #5539

**Comment by alainsussol** [comment]
# 🧪 Testing
tested in v2.4.0RC4


- [ ] Set show extra response requisition fields to false 
- [ ] create a response requisition
- [ ] set requested != suggested on a line
- [ ] confirm finalised
- [ ] See that status change works **-PASS-**
- [ ] open an existing response requisition
- [ ] set requested != suggested on a line
- [ ] confirm finalised
- [ ] See that status change works **-PASS-**
- [ ] Set show extra response requisition fields to true
- [ ] Create a new response requisition 
- [ ] Set requested != suggested
- [ ] Confirm finalised should fail **-PASS-**
