### ISSUE TITLE
Make period, unit and comment sort properly in Internal Order list view

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5548]
## What went wrong? 😲

Sorting in Internal Orders can be improved: 

1. Period sorts alphabetically, but if a period name has date in it (e.g. 2023), it quickly stops making sense

For example, I am seeing: 

May 2023
May 2024
November 2022
November 2023
October 2023
September 2023

<img width="450" alt="Screenshot 2024-11-25 at 3 03 52 PM" src="https://github.com/user-attachments/assets/7ef1c2a2-ac99-4bd4-814b-879b3dbe2ba5">

2. Comment sorting does not seem to be sorting alphabetically?

<img width="474" alt="Screenshot 2024-11-25 at 3 04 14 PM" src="https://github.com/user-attachments/assets/ffe276ba-308c-40e0-b83b-0e77b7bb61d2">

3. When adding items to an Internal Order, Unit sorting also does not appear to be working

https://github.com/user-attachments/assets/efd5358b-0ca5-451f-bc3d-f509f334d7c1

## Expected behaviour 🤔

Laché suggested sorting for these columns could be disabled, or at least it should be making sense - e.g. period can be sorted by date, and comments can be sorted alphabetically.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Internal Orders
2. If you have a blank screen, create a few for the testing purposes
3. Click on Comment & Period columns to see sorting
5. See confusing behaviour

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC3
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Galaxy Tab A8 (Android 14)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Hi team, 

Just want to make sure number 3 is also addressed as the title excludes it :)

**Comment by DhanyaHerath** [comment]
Would say that sorting by period would be a common request, but ideally would sort by start date. Fine to exclude sorting by unit and comment though if tricky - and stop that happening.

**Comment by DhanyaHerath** [comment]
Good first issue to investigate, might not be a good first issue to do :) but to be seen once investigated + results commented here

**Comment by mark-prins** [comment]
The comment is sorting by createdDate

<img width="278" alt="image" src="https://github.com/user-attachments/assets/7e9702c7-6bb5-4df1-85f7-f5badceaf9ba">

this is because the `toSortField` method is doing this:

![image](https://github.com/user-attachments/assets/d58f3a1e-504d-4022-8a7d-5d8b6d88edd9)

if the api supports the sort by comment, then fine to change. otherwise just prevent sort on comment 🙏

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.5.0-reports2`



- [ ] Navigate to the Internal orders page
- [ ] Review that `comment` button or column shouldn't be clickable therefore no sorting happens
- [ ] Review that `period` button/column should be clickable and is sorting via the start date
- [ ] Open an order
- [ ] Review that `unit` button or column shouldn't be clickable therefore no sorting happens
