### ISSUE TITLE
Adding an item to an existing manual requisition results in a blank page

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5562]
## What went wrong? 😲

When adding an item to a manual requisition (General, not Programs), the screen first appears blank and then when navigated away and back to the item, the detailed view appears

Video of the bug ->>> [here](https://drive.google.com/drive/folders/1XMzU62c-tqC-aSUZC52PdeD1UKPRXTAZ)

## Expected behaviour 🤔

The detailed view should be shown straight away

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Distribution -> Requisitions
2. Create a new manual requisition (important - navigate away from it, don't add the item straight away)
3. When back -> and prompted with choice between Program & General, choose General
5. Add an item -> see blank screen appear like in the video
6. Navigate away and back to the item you just added
7. Detailed view should now appear

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC3`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Google Chrome (browser on Mac)

- Database type: `SQLite3`

**Comment by roxy-dao** [comment]
To test: throttle network. Probably need to await before navigating away

**Comment by roxy-dao** [comment]
Closed in #5566

**Comment by marthakeezy** [comment]
Hi Roxy, 

I now see an infinite loading spinner :0 

[Video here](https://drive.google.com/file/d/19UYYhtibh7nxvcpUebTrPQTfGGssmulO/view?usp=drive_link)

**Comment by marthakeezy** [comment]
@npendergrast just suggested a test - because my server is in Amsterdam, and I am running it through the browser in New Zealand, he thought it might be a latency issue (which we have confirmed)

I just tried creating a requisition from the browser from my test server (so Amsterdam to Amsterdam), and the item loaded immediately! And he says it might be a problem since a lot of clients can have their server running from the cloud. 

Leaving this in the hands of developers :)

**Comment by npendergrast** [comment]
Hi @roxy-dao, not sure if this is a problem in the short term, as the OmSupply central might not be used for too much at this stage. But longer term it seems likely that we will have users in countries like Timor/PNG/Fiji etc who are connecting to OmSupply Central from a browser in their country. So latency issues might become more of a problem

Are there a lot of calls and responses to the server for this action?

**Comment by andreievg** [comment]
We were hoping to postpone dealing with very low latency for web app, since we have sync system. I don't think we will be able to make the web app work when connection is very bad, but we should support our cloud server in Holland (slow, but no infinite loaders)
