### ISSUE TITLE
Program customer selection don't take name tag into consideration and will show if customer is using master list 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5568]
## What went wrong? 😲
Program customer selection don't take name tag into consideration and will show if customer is using master list 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a program master list 
2. Have a customer use the master list but don't assign the tag to customer
3. Go to OMS and click Requisition
4. Try add new program requisition
5. See that you can select customer even if they don't have tag

## Your environment 🌱

- Open mSupply Version: 2.4.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #5580

**Comment by alainsussol** [comment]
# 🧪 Testing
with v2.4.02



- [ ] Have multiple customers
- [ ] Set up some program master lists 
- [ ] Have customers use program master list
- [ ] Add the tags to the customers (make sure to have some customers use a program master list without the associated tag)
- [ ] Go to OMS requisition
- [ ] Click `New Requisition`
- [ ] Customer selection for the program master lists should match with customers who you have assigned the name tags to **-PASS-**
