### ISSUE TITLE
New programs UI icons

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5584]
Start moving UI to be closer to the latest designs:

![Screenshot 2024-11-27 at 12 39 22 PM](https://github.com/user-attachments/assets/58a8f789-a2b4-49c6-89b1-c0bbaf3458ae)

Here is the icon pack for the new icons:

[Family planning.zip](https://github.com/user-attachments/files/17926814/Family.planning.zip)

**Comment by jmbrunskill** [comment]
@CarlosNZ As discussed this morning, If we have time it would be good to get the new icons into 2.4.1

**Comment by CarlosNZ** [comment]
Closed by #5657

**Comment by marthakeezy** [comment]
New icons visible in `V2.4.1-RC3`! Moving to Done ✅
