### ISSUE TITLE
Unable to view full Target Quantity for some items in Internal Orders

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5588]
## What went wrong? 😲

When adding an item to an Internal Order, there is a graph and a chart showing Target Quantity, Consumption History and Stock Evolution. I noticed that for some items, you are unable to view full Target Quantity and it simply gets cut off. 

For example, this is what it looks like normally: 

<img width="1063" alt="Screenshot 2024-11-27 at 3 14 14 PM" src="https://github.com/user-attachments/assets/7b145b7b-0dd2-42da-99e4-9172d4b40eec">

And this is the cut off one: 

<img width="1074" alt="Screenshot 2024-11-27 at 3 14 03 PM" src="https://github.com/user-attachments/assets/1d9474bf-2dbe-49fb-bbb3-682aaf1a9160">

Full screenshots uploaded ->>>>> [here](https://drive.google.com/drive/folders/1Y3mFzn4ktOMN4DX74taoyrOpnVbJzcEh)

## Expected behaviour 🤔

Should be visible fully!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Replenishment -> Internal Orders
2. Create a new General Internal Order or modify an existing one
3. Add an item - my suspicion is if that's an item that has huge numbers in stock etc, then the number gets cut off
4. Attempt to add a few items until you run into the issue

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC3`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: `Galaxy Tab A8 (Android 14)`

- Database type: `SQLite3`

**Comment by marthakeezy** [comment]
Actually maybe it's `High` priority... Unsure!

**Comment by marthakeezy** [comment]
Can't see it on the supplier's store either once it turns into a requisition!

<img width="503" alt="Screenshot 2024-11-27 at 3 31 29 PM" src="https://github.com/user-attachments/assets/63cb1f57-4d19-4da8-8972-713ce8fa52e0">

**Comment by roxy-dao** [comment]
This happens because the stock on hand is a really high number while the target quantity is a really low number, which means the % it takes compared to the high number bar is low. Probably low likelihood of happening live(??)

**Comment by DhanyaHerath** [comment]
triage: likely to be changed with internal orders changing to be aligned with the customer requisition changes coming into V2.5
