### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5591]
## What went wrong? 😲

![image](https://github.com/user-attachments/assets/6f97345f-1715-462d-aa93-4fcb53b417ae)
## Expected behaviour 🤔

Integration tests should at least compile!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run `cargo test --features=integration_test`

## Your environment 🌱

- Open mSupply Version:2.4.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment]
Before release we should make sure integration tests are passing

**Comment by marthakeezy** [comment]
Checked with James, this one has been dev tested :) Moving to Done ✅
