### ISSUE TITLE
Rename `Settings` page to `Help`

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5598]
- [ ] Rename `Settings` page to `Help`
- [ ] Change the icon from the cog to a [question mark](https://feathericons.com/?query=help)
- [ ] Update the AppRoute to say `/help` instead of `/settings`
- [ ] Breadcrumb should say Help and show the new `?` icon (managed in SectionIcon) 

Areas to update:

![Image](https://github.com/user-attachments/assets/ef2e89ae-8a09-4914-87e2-4153608aa8f2)

New App Drawer link should look like:

<img width="278" alt="Screenshot 2024-11-27 at 7 47 58 PM" src="https://github.com/user-attachments/assets/c766c771-74ce-4c2e-ac1b-27f1341e2151">

**Comment by mark-prins** [comment]
@lache-melvin Help! it should be the `docs` that has the label change
 
`Rename the Docs link to Help, create a new page which this links to.`

and there should be a new page too - I couldn't see an issue created specifically for that, though the other aspects are there (adding the offline docs etc)

🙏

**Comment by lache-melvin** [comment]
Whoooops - thanks @mark-prins - sorry I misunderstood!

So this issue will add a new `Help` link to the app drawer, and create a new page. That new page will then get the docs moved into it, along with the `Contact us` form 🙏

**Comment by mark-prins** [comment]
yep, and remove the current (external) docs from the nav, and add a link to the external docs on the new page.
don't know who wrote those requirements! 🙄 just not clear enough..

**Comment by noel-yeldos** [comment]
Thank you both! I've reverted earlier changes and have commited the new changes :)

**Comment by alainsussol** [comment]
Will be tested as part of the GEDSI feature testing
