### ISSUE TITLE
Adjust permissions for the Settings page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5599]
Currently the settings section ~~(now `Help`)~~ is restricted to only users with server admin permission. However, we now wish to open up the settings to users so that they can edit display settings.

- [ ] Make the ~~`Help`~~ `Settings` link in the AppDrawer visible to all
- [ ] Make these accordion sections hidden, unless you have the ServerAdmin permission 
  - [ ] Synchronisation
  - [ ] Support
  - [ ] Devices
  - [ ] Configuration
- [ ] The `Display Settings` section should always be visible, but hide these elements for non-ServerAdmins 
  - [ ] Custom theme
  - [ ] Custom logo

![Image](https://github.com/user-attachments/assets/f2ff61f2-1c96-40db-a4d0-d2a1934081be)

**Comment by lache-melvin** [comment]
Hi - apologies I misunderstood - this will actually remain the `Settings` page, `Help` page will be separate. Have updated issue above (shouldn't really have an impact on this work 🙏 )

**Comment by alainsussol** [comment]
Will be tested as part of the GEDSI feature testing
