### ISSUE TITLE
Move link to online docs to the `Help` page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5600]
Currently, the link to the docs is in our App Drawer. It takes up valuable room - we'll move it to the Help page! The name `Docs` is also a bit technical - User Guide would be better.

EDIT: not a settings accordion section but a new page! see below:

~~Add a new accordion section to the Help page, like this one, called `User Guide`:~~

Inside it, add a section for `Online User Guide (requires internet connection)`, which links to https://docs.muspply.foundation/introduction/introduction

**Comment by lache-melvin** [comment]
Sorry, I misunderstood! #5598 will add a new `Help` page (will be blank), which we should add a section called `User Guide` to. 

Then we can remove `Docs` from the app drawer.

![Image](https://github.com/user-attachments/assets/3ac1f440-3ef1-4910-8712-f058873f0cf3)

**Comment by alainsussol** [comment]
Will be tested as part of the GEDSI feature testing
