### ISSUE TITLE
Add feedback form inputs to the Help page

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5601]
Add a form to the Help page for a user be able to share feedback with us.

This PR should:
- [ ] Add a new section to the help page accordian, accessible to all users, called `Contact us`
- [ ] Inside it, we should have a subheader `Feedback form` and then the two inputs for `email` and `message`
- [ ] Add a `useFeedbackForm` hook, which manages the draft state for the feedback form
- [ ] Add a `Send` button (can use [mail](https://feathericons.com/?query=mail) icon) which `console.log`s the feedback form, and shows a `success` snack that the feedback form has been saved

The radio buttons can be ignored for now, we are just adding feedback form, support request can come later:

![Image](https://github.com/user-attachments/assets/d10ea62d-688b-4b2f-84c3-36e930f08030)

**Comment by alainsussol** [comment]
Will be tested as part of GEDSI Feature testing
