### ISSUE TITLE
Add service layer to create feedback form

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5603]
Implement service layer logic to save a feedback form.

Add a new `contact_form` service, with an `insert_contact_form` function.

Should accept an input with the following properties:

Key | Type
-- | --
id | String
type | ContactFormType
reply_email | String
body | String

`ContactFormType` enum: `Feedback` | `Support`

Validation should include:
- Feedback form with that ID doesn't already exist
- Body is not empty
- Email is valid format

Other fields on feedback_form_row: 
- `created_datetime` should be set to `Utc::now()`
- `site_id` should come from the `site_info_service`

**Comment by alainsussol** [comment]
Will be tested as part of GEDSI feature testing
