### ISSUE TITLE
JSON Forms Prescription inputs -- validate quantities

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5609]
From follow-up summary: https://github.com/msupply-foundation/open-msupply/issues/5571

**Comment by CarlosNZ** [comment]
Closed by #5611

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.4.1`

- [ ] Prepare Family Planning forms as per previous PRs (#5581 #5570)
- [ ] Start creating a prescription in Reproductive Health encounter -- confirm that prescribed quantities can't exceed the available amounts
