### ISSUE TITLE
Infinite loading loop when navigating from an indicator to the indicators page using the header navigation bar

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5610]
## What went wrong? 😲

Try to get back to the indicators page using the header navigation bar after fillling your indicators values triggers a loading page loop that doesn`t seem to finish. If you click on the requisition number instead you come back to the requisition page and can go to the indicators  page normally

https://github.com/user-attachments/assets/86556a6d-5ea8-41bc-b85d-15c31a73f957

Also note that if you click on REGIMEN, you have a blank page

## Expected behaviour 🤔
See the Regimen+ icon without too much loading

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Setup for program requisitions and add regimen indicators  
1. on msupply create a manual program requisitions
2. Go to the indicator page
3. Click on '+ Regimens'
4. Add values for each of your regimens
5. From the navigation bar at the top of your page, click on Indicators
6. See error. Loading page seems infinite.

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version: v2.4.0RC4

- Platform: Android

- Database type: SQLite

**Comment by roxy-dao** [comment]
Closed in #5615

**Comment by alainsussol** [comment]
# 🧪 Testing
Tested with v2.4.0RC6



- [ ] Have indicators set up for your program
- [ ] Sync
- [ ] Create a new program Requisition
- [ ] Go to indicator tab and click on one of the buttons
- [ ] Only the Requisition and requisition number in the breadcrumb should be enabled **-PASS-**
