### ISSUE TITLE
Customer's Inbound Shipment status changes do not get updated in Supplier's Outbound Shipment

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5617]
## What went wrong? 😲

Scenario: I have a Supplier store on my omSupply Central Server and my Customer store on Remote Site. Central Server is Google Chrome browser on Mac, Remote Site is Galaxy Tab A8 on Android 14. 

When supplier sends the outbound shipment, it becomes an inbound shipment in the customer's store. I went ahead and updated the shipment to Delivered and then Verified, synced many times both sites, restarted the app and the status changes have not synced/updated on Central Server for my Supplier store. 

Outbound Shipment screenshot: 

[here](https://drive.google.com/file/d/1UMEZotPIw012XjZRCsV1bf7S88WE578X/view?usp=drive_link)

Inbound Shipment screenshot: 

[here](https://drive.google.com/file/d/1OqP-eCruZj1I8P1-6bHxJgTOFUbhEPhj/view?usp=drive_link)

Datafile shared via [this link](https://mega.nz/folder/NUBkHRZC#iun85zeqSy42LusGe8nHLw)

## Expected behaviour 🤔

Statuses should update accordingly without any delays/inconsistencies

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a Supplier store setup on your Central Server
2. Have a Customer store setup on your Remote Site
3. I had a process of creating Internal Order -> Requisition -> Outbound Shipment -> Inbound Shipment, but for the testing purposes, you can probably start with creating an Outbound Shipment manually and selecting your Customer store as a receiver
4. Once Inbound is received, go through the steps of marking it as Delivered and Verified
5. Sync both sites many times just in case
6. See on the Supplier store, the Outbound Shipment's status does not get updated

## Your environment 🌱

- Open mSupply Version: `V2.4.0-RC4`
- Legacy mSupply Central Server Version: `V7.18.11`

- Platform: Central Server: `Google Chrome on Mac; Remote Site: Galaxy Tab A8 (Android 14)`

- Database type: `SQLite3`

**Comment by marthakeezy** [comment]
Marking as `Normal` as the stock for the supplier changes as 'Shipped' and not 'Delivered' or 'Verified' so don't think it's much impact apart from the fact you are not able to change it manually on the supplier's store

**Comment by marthakeezy** [comment]
Had a chat to @alainsussol and tested something else: 

I re-initialised my Remote Site on a tablet to see if it was related to #5098 (on V2.4.0-RC4), and then upgraded to V2.4.0-RC5, and the status still is not updated on my Central Server (supplier store), so possibly unrelated!

**Comment by andreievg** [comment]
Triage, bumped priority and asked to be check in this PR: https://github.com/msupply-foundation/open-msupply/pull/5703

**Comment by jmbrunskill** [comment]
@marthakeezy I've pulled down that database, and It looks like the inbound invoices stop at number 239, but the affected one is 240. Do you have an updated database you can share?

**Comment by marthakeezy** [comment]
Hey @jmbrunskill sorry about this!

Shared to your email, but also here is the link: https://mega.nz/fm/9d4SjDQJ

**Comment by jmbrunskill** [comment]
Fixed with #5703
<img width="694" alt="image" src="https://github.com/user-attachments/assets/dc54e964-47c0-401e-b531-cb6c6a8ceec0">

**Comment by andreievg** [comment]
Closing, fixed with PR mentioned above

**Comment by marthakeezy** [comment]
Just gave it a quick test in `V2.5.0-RC6`, it is now fixed :) Moving to Done ✅
