### ISSUE TITLE
Indicators should show indicator line name

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5619]
## What went wrong? 😲

Indicator configuration and OMS UI are not consistent. In short, it's intuitive that the "Name" of an indicator line is the survey question being asked, where as the "Code" is a short hand code for the indicator, or a variation of the question (as seemingly the case for HIV indicators config). Here is how it is configured in OG and displayed:

![image](https://github.com/user-attachments/assets/a9bba13e-32c0-424c-bab9-a2a8516d3e55)

![image](https://github.com/user-attachments/assets/0f79546a-e786-47fc-a5f0-74b1209e1778)

But in OMS, we decided to only show the code. Perhaps this was in consideration of standard HIV configuration in OG having duplicate names. Unfortunately this can be confusing for regular indicators configured by the user in the "Regimen" section:

![image](https://github.com/user-attachments/assets/94c7ee90-1a4f-4fa2-aa2d-d905c00ff2f4)

For HIV it may not be clear what the actual question is that the code is pertaining to other than hoping the users memorise it from elsewhere

![image](https://github.com/user-attachments/assets/545a81d1-cb8c-4be8-aa19-09bff99fd228)

## Expected behaviour 🤔

OMS should show both the code and the name of an indicator as per the OG spec.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.4.0-rc4 dev
- Legacy mSupply Central Server Version: 7.18 dev

- Platform: m3

- Database type: pg

**Comment by roxy-dao** [comment]
Putting as high. UI should show the user the question instead of expecting the user to remember the codes XD

**Comment by roxy-dao** [comment]
Close in #5637
