### ISSUE TITLE
Move program_indicator filtering from FE to BE and filter inactive records on generation

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#5624]
## Is your feature request related to a problem? Please describe 👀

As a rough solution to a half cooked feature I put some filtering of program indicators in the frontend rather than backend. This is bad because the same filtering would be required for internal orders when we do that, and it's very easy to forget all the places you need to do it in the FE (or at least FE should be refactored to do it a different way than I have 😉).

## Describe the solution you'd like 🎁

The more I looked at it, the more confused I was about the correct way to do it in the backend, hence the frontend kludge.

There are several things to consider when filtering program_indicators and the related tables:

- [ ] When creating a program requisition we should 
  - [x] exclude inactive program indicators [(we do this here currently, but might be problematic)](https://github.com/msupply-foundation/open-msupply/blob/b0f700726a298317e4466a8fca9bd46187680dae/server/repository/src/db_diesel/program_indicator.rs#L56)
  - [x] exclude inactive indicator_lines (we don't do this, and need to take care to not filter inactive for _past_ requisitions querying for display in FE)
- [ ] When creating API response for program indicators display on a requisition
  - [ ] Ignore any `is_active` fields - we need the representation of indicators from the time that period is relevant to, so what was generated at the time the requisition was made.
  - [ ] We should include only program_indicators and relating tables if the relevant period **period** has any indicator values
  - [ ] We should include only the indicator_lines that have at least 1 related indicator_value

Both the generation and the gql API use the program_indicators service, which means care needs to be taken when implementing filtering to make sure that it effects each appropriately. Perhaps they should not use the same service, and the repo layer should allow overriding the default filtering out of program_indicators. GLHF.

### Describe alternatives you've considered 💭

It's logically a bit messy. I might be cooked. Above is a guide, but could be a better approach!

**Comment by fergie-nz** [comment]
` exclude inactive indicator_lines (we don't do this, and need to take care to not filter inactive for past requisitions querying for display in FE)`
Not worrying about this - not important

**Comment by fergie-nz** [comment]
MVP filtering components to move to back end is indicator.code === HIV and indicator.code === regimine

**Comment by fergie-nz** [comment]
Leaving filtering on front end for when value doesn't exist as infeasible to add in back end with loader implementation.
