### ISSUE TITLE
When no indicators are configured for a program, the indicator tab still shows with a blank page

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5634]
## What went wrong? 😲

Test suite mentions that the Indicators tab should not show if no Regimen have been configured  or that it is not a HIV program (HIV program box is not ticked). In this case, the Indicators tab is showing even though no regimen has been configured and the HIV program box is not ticked.

![image](https://github.com/user-attachments/assets/d375b9c8-b99d-4093-bd42-548d96daebbb)

![image](https://github.com/user-attachments/assets/20f72bd3-4d6b-4628-9f00-0f9c3d96c929)

   

## Expected behaviour 🤔
As the testing suite mention ie Indicators tab should not show in the above scenario

## How to Reproduce 🔨

Steps to reproduce the behaviour:
On OG central server in master list, create a program with no Regimen and don't tick the HIV program box. Make that master list visible to the supplier store and the customer. Don't forget to add the tags to the stores involved     
1. On omSupply go to Distribution > Requisition 
2. Click on Add a new Requisition
3. Choose the program you have created and the customer who has access to that program and a period. Click create
4. See error. The Indicators tab is visible 

## Your environment 🌱

- Open mSupply Version: 2.4.0RC4
- Legacy mSupply Central Server Version: v7.18.10

- Platform: Android 14

- Database type: SQLLite3

**Comment by roxy-dao** [comment]
Closed in #5638

**Comment by alainsussol** [comment]
# TESTING
- [ ] Have program without indicators 
- [ ] Create program requisition
- [ ] Shouldn't see indicators tab **-PASS-**
- [ ] Add indicators to the program and Sync
- [ ] Create program requisition 
- [ ] should see indicator tab  **-PASS-**

**Comment by alainsussol** [comment]
@roxy-dao @Chris-Petty 

Hi Roxy and Chris, 

I have tested this on Friday and I have 2 questions:

1) If you have a program without indicators, the indicator tab will not be visible. If you then add indicators, the indicator tab will appear for the new requisition as well as the regimen button. However the requisition created before adding these new regimens will also show the indicators tab but without the Regimen tab. What do you think ? Is it the right behaviour ? 

2) Also maybe because it is not implemented yet but indicators of request requisition created from internal order are not migrated. Should I open an issue ?

3) To my great surprise, I also realised that on OG you can now delete regimen but it doesn't seem to affect anything when I create new requisitions on omSupply even after syncing they are still visible but I have an error message popping out. In OG the deleted indicator does not appear. I don`t think we should be able to delete an indicator line. I'll check with @JonnaQuismundo 

 
Happy to have a chat if needed...

**Comment by Chris-Petty** [comment]
@alainsussol 
>     1. If you have a program without indicators, the indicator tab will not be visible. If you then add indicators, the indicator tab will appear for the new requisition as well as the regimen button. However the requisition created before adding these new regimens will also show the indicators tab but without the Regimen tab. What do you think ? Is it the right behaviour ?
> 

Hmm so you click the "Indicators" tab and it says "nothing here"? Not sure if big enough a problem to warrant changing, though I suppose it'd be more consistent to just hide the tab at that point.

>     2. Also maybe because it is not implemented yet but indicators of request requisition created from internal order are not migrated. Should I open an issue ?
> 

Nah I'd wait to request requisitions are implemented. To be clear when you say migration you just mean made visible i.e. not moving a store from OG to OMS? On that note you may know how OG behaves, if you have an internal order from one store to another store on another **remote** site, do the indicators show for that other site? I don't believe the transfer logic duplicates the indicators (which would be wrong!), but not sure what mechanism would cause them to sync to the other site.

>     3. To my great surprise, I also realised that on OG you can now delete regimen but it doesn't seem to affect anything when I create new requisitions on omSupply even after syncing they are still visible but I have an error message popping out. In OG the deleted indicator does not appear. I don`t think we should be able to delete an indicator line. I'll check with @JonnaQuismundo
> 

Hmm I think this aligns with what you're saying, my understanding in OG is if you (soft) delete an indicator line from the regimen section, that line will no longer show for new requisitions but any past requisitions where that line had indicator_values generated would show. That said in OMS indeed we aren't checking for whether or not the lines have been soft deleted, there is an issue touching on implementing this here https://github.com/msupply-foundation/open-msupply/issues/5624
