### ISSUE TITLE
When emptying an HIV indicator from it's default value, it is replaced by a strange text value and you can't change it easily to a valid value

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5635]
## What went wrong? 😲
Doing backspace put the value NAN :) but I cannot put any value to replace it unless I navigate to another item and come back

https://github.com/user-attachments/assets/bd795861-7552-48ae-86c8-4ef82c506d26

## Expected behaviour 🤔
We should probably be able to change that value to a valid one without having to navigate away. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Have a HIV program setup
1. Go to Distribution  > Requisition
2. Create a new requisition
3. Go to the indicator page. Press on the HIV button
4. Select a value and press backspace
5. See error. The NAN text appear and there is no way to change it unless navigating away and come back

## Your environment 🌱

- Open mSupply Version: 2.4.0RC4
- Legacy mSupply Central Server Version: 7.18.10

- Platform: Android 14

- Database type: SQLite3

**Comment by roxy-dao** [comment]
Closed in #5638

**Comment by alainsussol** [comment]
# 🧪 Testing
Tested with v2.4.0RC6



- [ ] Have number input indicator 
- [ ] Go to that indicator and backspace
- [ ] Should still be able to enter number and shouldn't say NaN **-PASS-**

Next:
- [ ] Have program without indicators 
- [ ] Create program requisition
- [ ] Shouldn't see indicators tab
