### ISSUE TITLE
Global Pref: `show direction entry in dispensary mode`

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5647]
<img width="541" alt="image" src="https://github.com/user-attachments/assets/530c352d-2571-4e71-9579-834892e29ae7">

Relies on https://github.com/msupply-foundation/open-msupply/issues/5644

Acceptance Criteria
- [ ] This global pref is available via graphql to allow the frontend to use it
- [ ] The mSupply pref syncs to OMS or (if agreeded) the new pref is available to be set and synced from OMS Central

**Comment by jmbrunskill** [comment]
@mark-prins it's been floated that we might not need this pref? If not using directions it would be easy to just skip over in the new design. Any thoughts? Want to keep the pref?

**Comment by mark-prins** [comment]
we didn't discuss removing it - I agree though.. let's just run with always showing directions and allowing people to skip over 🙏

**Comment by jmbrunskill** [comment]
Thanks mark, Will close this one then!
