### ISSUE TITLE
CIV 2.5: New columns display for Internal Orders

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5661]
New columns to display if `Use consumption and clients stock data in Internal Orders` pref is on: 
- Months of stock
- Initial stock on hand
- Incoming stock
- Outgoing stock
- Losses
- Additions
- Available stock
- Days out of stock
- Reasons
- Area AMC

### Moneyworks Jobcode 🧰
OMS:CIDV

**Comment by alainsussol** [comment]
Will be built tested in Feature release testing [here](https://github.com/msupply-foundation/open-msupply/issues/5932)
