### ISSUE TITLE
Asset export columns don't line up

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5671]
## What went wrong? 😲

Export asset list is a couple columns off - was pretty confused for minute there 😁 
<img width="690" alt="Screenshot 2024-12-02 at 5 19 56 PM" src="https://github.com/user-attachments/assets/c7d657ef-4dec-469b-87e5-1220ab37c3f0">

I think this came about from #5553 and #5546 not merge correctly!

Also, status is not translating in the import template (should say `Functioning`, or be translated to your language):

<img width="179" alt="Screenshot 2024-12-02 at 5 22 21 PM" src="https://github.com/user-attachments/assets/1c63339b-2468-41b6-95c4-5c286f375ca5">

## Expected behaviour 🤔

The right data maps to the right column!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have some assets
2. Export
3. Test on both central and remote OMS
4. Also download the import template to see the functional status not translated

## Your environment 🌱

- Open mSupply Version: v2.4.0
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Fix `assetsToCSV` to replace the non-UTC datetime column headers with the UTC column headers

 https://github.com/msupply-foundation/open-msupply/blob/develop/client/packages/coldchain/src/Equipment/utils.ts#L25

**Comment by marthakeezy** [comment]
They line up and the status has been translated! Moving to Done ✅ 

`Tested in V2.5.0-RC7`
