### ISSUE TITLE
You can change the value of an indicator after the requisition has been finalised

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#5674]
## What went wrong? 😲

As title. See video [here](https://drive.google.com/file/d/1p4nptM3nD4KdQyo2ovu_cYAI8LblZzTp/view?usp=sharing)

And Sorry, I should have seen this way earlier ):

## Expected behaviour 🤔
You should not be able to modify the value of an indicator once the requisition has been finalised

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Have program setup and Regimen inidcators setup
1. Go to Distribution > Requisition and create a new program requisition
2. Click on Indicator tab and + Regimen button, add a value
3. Finalise your requisition 
4. Click back the requisition and go the indicator tab and change the value of the regimen you added a value
5. Change that value
6. See error. You should not be able to as the requisition has been finalised

## Your environment 🌱

- Open mSupply Version: v2.4.0
- Legacy mSupply Central Server Version: v7.19RC19

- Platform:

- Database type: SQLlite3

**Comment by roxy-dao** [comment]
1 hour for discussion

**Comment by roxy-dao** [comment]
Disable for now, but will need to add the indicators into a table view so the user can view the indicators without having to go into the page

**Comment by alainsussol** [comment]
# 🧪 Testing



- [x] Create a program requisition for a store name
- [x] Finalise Requisition
- [x] Go to edit indicator
- [x] Inputs should be disabled **-PASS-**
