### ISSUE TITLE
Show price in “View stock” page

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5688]
## Is your feature request related to a problem? Please describe 👀
Raised by @louisaw123 in the [DTAC feedback doc](https://docs.google.com/document/d/1zhyefSpHQuEb1D8EcQYo0IfYYg7XQBCUwc5MChHysr0/edit?tab=t.0)

## Describe the solution you'd like 🎁

Add two new columns to the Stock > ListView page: `Cost Price per Pack` and `Total Value`.

Total value calculation would be cost price per pack * pack qty.

![Image](https://github.com/user-attachments/assets/f824a05d-c5c5-4107-865b-e878dd712a5a)

**Comment by lache-melvin** [comment]
@mark-prins cost or sell price? Or both?

**Comment by mark-prins** [comment]
Unsure.. I asked @louisaw123 in the doc.
The comment has 'This would be similar to Legacy mSupply having the ability to show the cost/sell price and total value:'
but my question was whether the 'price per pack' is ok. Will see what Louisa says 😄

**Comment by louisaw123** [comment]
It would definitely need the total value per stockline and ideally the cost price per pack.

**Comment by lache-melvin** [comment]
Hi @mark-prins - also see that Louisa's request was for including the total price in the expiring items report...

Can you confirm this issue is just for adding to the view stock page? Or actually to the report? Or we need both?

**Comment by mark-prins** [comment]
thanks! yes, this issue is for the stock page only.
I raised [this one](https://github.com/msupply-foundation/open-msupply/issues/5687) for the expiring items report - which turned out to be a duplicate of [that one](https://github.com/msupply-foundation/open-msupply-reports/issues/91) so I've closed mine with a comment on Louisa's issue.

**Comment by marthakeezy** [comment]
# 🧪 Testing

`V2.5.0`

- [ ] Go to Inventory -> View Stock
- [ ] Add a new stockline, include a cost price and have multiple packs on hand
- [ ] See the new columns for 'Pack cost price' with the cost you specified, and 'Total' with the cost*pack quantity

Changes have been applied, moving to Done ✅
