### ISSUE TITLE
Programs Module: the user is able to change patients in a prescription

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5692]
## What went wrong? 😲

I am trying to understand the use cases for someone being able to change patients once the prescription is created. If a prescription was created by mistake, I'd assume the user's first thought would be deleting the prescription instead of re-assigning it to another patient. 

The problem I am seeing is now that there is family planning/reproductive health module, the user is able to issue contraceptives and then change the patient to someone who is not enrolled into a program.

<img width="1508" alt="Screenshot 2024-12-04 at 1 35 31 PM" src="https://github.com/user-attachments/assets/58ec4d63-15c8-4371-ac26-28e856404477">

## Expected behaviour 🤔

When prescription is created from an encounter in family planning/reproductive health module, the patient field should be locked to prevent changes and issuing medication to someone who is not enrolled into a program. However, I'd argue to limit the patient change for all prescriptions, not just the ones created from an encounter. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have programs set up in your store
2. Have Family Planning/Reproductive Health configured in your store
3. Basically, have all the config done for testing purposes
4. Go to Dispensary -> Prescriptions and create a new prescription
5. See the patient can be changed
6. Go to a patient and create an encounter
7. Create a prescription from that encounter (under contraceptives)
8. See the patient can also be changed for that prescription
9. Inconsistency!

## Your environment 🌱

- Open mSupply Version: V2.4.1-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Setting as `Normal`, as technically this does not break anything, but I am worried about continuity and consistency of someone using this module, so tempted to set as `High`

**Comment by andreievg** [comment]
Triage, PO suggest there is a use case for this, and we don't think it's a common thing to do so it doesn't have big impact, closing. Nice catch though @marthakeezy

**Comment by CarlosNZ** [comment]
> PO suggest there is a use case for this

What is the use case? When is it desirable to change the recipient of a prescription after it's created?
