### ISSUE TITLE
Programs Module: prescription link disappears when changing contraceptive method

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5695]
## What went wrong? 😲

Lengthy title! But basically: there is a prescription created, that is associated with the encounter/contraception method. If you change that method (from DIU to PP and back, for example), the prescription does not show when the changes are reversed. 

https://github.com/user-attachments/assets/e050c9cd-5b29-484f-8f30-ce6389cd68d3

## Expected behaviour 🤔

If you change the contraception method and then change it back, the prescription should appear as it is already in the system. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have Programs & Family Planning/Reproductive Health module set up for your store
2. Create an encounter for your patient and create a prescription for an item in that encounter
3. Change the contraception method and then change it back -> see prescription disappear (like in the video)

## Your environment 🌱

- Open mSupply Version: V2.4.1-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by marthakeezy** [comment]
Comment from @lache-melvin: Bug should be that the prescription link disappears at all! If you change the method after already creating the prescription, the link should still show, they would have to go into the prescription and manually update 🙏

**Comment by CarlosNZ** [comment]
> Comment from @lache-melvin: Bug should be that the prescription link disappears at all! If you change the method after already creating the prescription, the link should still show, they would have to go into the prescription and manually update 

Agreed, and should be a fairly straightforward fix.

**Comment by CarlosNZ** [comment]
I (accidentally) pushed this directly to the 2.4.1 branch, but it's basically a one-liner if you want to check it: 5c04315245

It fixes this problem, plus an additional one (not logged) where the prescription selector would disappear after *first* selecting an Item category.

**Comment by marthakeezy** [comment]
Couldn't find any specific testing steps, but here is what I've done in `V2.4.1-RC3`: 

1. Edited an exiting encounter - removed all selection, added selection back - prescription reappears as expected
2. Deleted the prescription -> went back to the encounter -> was still able to create a prescription after that
3. New prescription is linked and reappears if any changes are made to the modal
4. Saved the encounter, changed some details, changed the status, went back to the contraception modal - prescription still there, able to be edited
5. Seems to be working fine!

Moving to Done ✅
