### ISSUE TITLE
Unable to edit or create new patient with custom JSON for patient details form

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#5701]
## What went wrong? 😲

When trying to edit a patient or create a new one, these 2 error message are displayed and user is unable to proceed with editing/creating patient

![IMAGE 2024-12-04 16:50:55](https://github.com/user-attachments/assets/8ff959d8-30b8-40b0-935b-2e102500eb7a)

## Expected behaviour 🤔

Should be able to edit or create patient using the custom JSON schema

## How to Reproduce 🔨

Steps to reproduce the behaviour:

https://demo-djibouti.msupply.org/
Store: "CSC Balbala 2 - VACCINATION"
JSON Schema: https://github.com/msupply-foundation/programschemas/blob/main/djibouti/ui_schemas/patient_ui_schema.json

1. Go to Dispensary > Patients
2. Click on an existing patient or try to create a new one
3. Click on Save and error messages should appear

## Your environment 🌱

- Open mSupply Version: 2.03.2
- Legacy mSupply Central Server Version: 

- Platform: browser (chrome)

- Database type:

**Comment by CarlosNZ** [comment]
@richardmoizeau -- I'll check the programs repo this morning and make sure we have a Patient schema that works properly and is consistent with the Patient create form. I'll send you the JSON schemas once they're good, can you install them on the server yourself or do you need a dev to do it?

**Comment by andreievg** [comment]
Triage, needs configuration check

**Comment by mark-prins** [comment]
Can we please also rename the enum `PatientDocumentRegistryDoesNotExit` - there needs to be an `s` in `Exist` 🙏

**Comment by CarlosNZ** [comment]
Was config issue in mSupply, "document_category" needed to be "Patient", but was "patient". Fixed on DJ Demo server now.
