### ISSUE TITLE
Programs Module: allow input validation to be dependent on other form values

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5705]
(Original issue title: **Programs Module: number logic does not make sense**)

## What went wrong? 😲

# Maternity History

1. Number of deliveries is allowed to be bigger than number of pregnancies

2. The total number of living children (lines 3 and 4) can be bigger than deliveries

3. Last delivery date is allowed to be in the future

4. All the fields with the exception of datetime picker can have meaningless numbers entered. For example, 1 million pregnancies or 5050505 children.

<img width="1098" alt="Screenshot 2024-12-04 at 3 28 29 PM" src="https://github.com/user-attachments/assets/6698bd3e-1d79-4ab1-ace7-e1ae8c08f563">

___

# Menstrual Cycle

1. Date of last menstrual cycle can be set in the future

2. Similarly to above, you can set meaningless numbers like 4384674 days since last period

<img width="886" alt="Screenshot 2024-12-04 at 6 42 28 PM" src="https://github.com/user-attachments/assets/dc407d9b-96fc-404d-9f07-a991dbbf0628">

___

# General Examination

1. Can enter meaningless numbers in weight and height fields of the modal

<img width="759" alt="Screenshot 2024-12-04 at 6 50 01 PM" src="https://github.com/user-attachments/assets/f0bc5c87-8227-4760-88ca-e0ad9e95d965">

## Expected behaviour 🤔

1. Deliveries should be equal or less than pregnancies
5. Living children summed up should equal to number of deliveries
6. Last delivery date should be today or earlier
7. Age can probably be capped at something reasonable like 100?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have Programs & Family Planning/Reproductive Health modules set up
3. Create an encounter for a patient and go to Details -> Maternity History
4. Play around with the fields and see some numbers don't make sense

## Your environment 🌱

- Open mSupply Version: V2.4.1-RC1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by mark-prins** [comment]
No - and I don't see this as enough of a problem to warrant bumping up the priority.
Fine to add in a date limit and max number, if those are possible with the schema. Otherwise I'd recommend closing the issue as a known problem, and one that we won't address now.

**Comment by andreievg** [comment]
Triage, not planning to do advanced validation like this at current stage.

**Comment by andreievg** [comment]
Refinement, closing until we have customer requirement backed by funding
