### ISSUE TITLE
Can't enter negative numbers on Samsung tablet

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5733]
## What went wrong? 😲

Can't enter negative numbers in R&R fields on tablet, even though the field accepts negative (i.e. on browser)

This is because Samsung numeric keyboard doesn't have a `-` key!!

## Expected behaviour 🤔

Can enter negative numbers

## How to Reproduce 🔨

Steps to reproduce the behaviour:

- On samsung tablet
- try to enter negative number in R&R form `Adjustments` columns
- Can't!

## Your environment 🌱

- Open mSupply Version: v.2.3.4
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by lache-melvin** [comment]
Closed by #5734

**Comment by AnushaUp** [comment]
Build Tested PASSED✅
