### ISSUE TITLE
Report fixes

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5735]
## What went wrong? 😲

Two quick things:
* The 'Months cover' help text for the Item Usage report isn't very helpful.
* The Stock Status report has the same colour for both understock and overstock, it's hard to know what's what

![telegram-cloud-photo-size-1-5098266162382351676-y](https://github.com/user-attachments/assets/6f59ba12-6a16-4458-ab25-9d7770f18e51)

## Expected behaviour 🤔

Update the help text 
`Months cover: Number of months the current stock is expected to last. The value is 'In stock' / 'AMC'. Note that AMC is calculated using the number of months given by the 'AMC lookback period' shown in the report filter which is configured with the 'monthly consumption lookback period' store preference.`

change the colour. The original design request was this:

![image](https://github.com/user-attachments/assets/84536c43-746b-4d25-b515-006db6b1be53)

which I think has the intention of saying that both under & over are bad, but not as bad as out of stock.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
5736

**Comment by marthakeezy** [comment]
Tested in V2.4.1-RC3, text shows up on both desktop & android, and the label for `Overstocked` is now purple

Moving to Done ✅

**Comment by marthakeezy** [comment]
Hey @mark-prins, I was wondering if we can get through a small tweak in wording here: 

No consumption - AMC is 0, but actually for No consumption to show up, AMC has to be 0 but SOH has to be > 0. Otherwise in Out of Stock scenario, AMC is also 0

Is this something worth clarifying? :)

![Image](https://github.com/user-attachments/assets/900d5897-b56a-4cb0-9817-d8710398cdd3)

**Comment by mark-prins** [comment]
Will do. I'm also wondering why AMC must be 0 for the item to be out of stock?

**Comment by marthakeezy** [comment]
Thank you!
