### ISSUE TITLE
Validate feedback form inputs in the frontend

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5737]
We should give the user fast feedback on why their contact form is invalid, rather than sending to the backend and suddenly getting an error.

Disable the `send` button while:
- email is empty
- message is empty
- email is not a valid email

After a slight delay from typing in the email, if not valid, show an error message, something like:

![Screenshot 2024-12-11 at 10 08 02 AM](https://github.com/user-attachments/assets/5db6b3c2-d1bc-431d-9c2b-193ffa77840f)

(See `error` and `helperText` props on `BasicTextInput`)

**Comment by alainsussol** [comment]
Will be tested as part of GEDSI Feature testing
