### ISSUE TITLE
Replace the `Actions` dropdown with an actions menu at the bottom of the screen

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5738]
![Screenshot 2024-12-11 at 10 12 14 AM](https://github.com/user-attachments/assets/e1a52768-2f37-48f7-9548-ee4d7af086b0)

- [ ] Remove the Actions dropdown from the Toolbar
- [ ] Define an `ActionsFooter`, with buttons for the same options that were in the dropdown
- [ ] When any of the rows are selected, replace the normal footer (the one with the statuses etc) with the ActionsFooter

This PR is to prove out the implementation. Just implement this in `Outbound Shipment` detail view. We can apply the pattern across other areas in a separate refactor PR.

**Comment by mark-prins** [comment]
This is awesome! 😀 
very nice to use, much more intuitive

Couple of minor things:
* can you check the height, the footer is taller than the current footer and it feels like it's using more space than necessary
* can you remove the shouty case on the buttons please

![image](https://github.com/user-attachments/assets/174eb199-d5c6-40fd-8201-c7115f80ae2e)

**Comment by GeronimoJohn** [comment]
Thanks for that Mark, I've applied the changes 😃

**Comment by lache-melvin** [comment]
Epic, I think we can capture this in a clean up issue for refactor fortnight 🔥

**Comment by alainsussol** [comment]
Will be tested as part of the testing of the GEDSI feature as a whole
