### ISSUE TITLE
Move logout button to Footer -> user

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5739]
![Screenshot 2024-12-11 at 10 18 59 AM](https://github.com/user-attachments/assets/6472ea64-a4ec-4a94-a6f1-d81b3a3a6cc0)

- [ ] Remove logout button from AppDrawer
- [ ] Add popup on click of username in footer, with the logout button
- [ ] Add user info above the logout button

Use footer store select/language select for how to show popup on click of the username.

**Comment by alainsussol** [comment]
Will be tested as part of the GEDSI whole feature testing
