### ISSUE TITLE
Remove site_id column from contact_form

### ISSUE THREAD

**Issue by GeronimoJohn** [msupply-foundation/open-msupply#5743]
EDIT: see updated solution below

Currently we've set up the site_id for Contact_Form to a String or a text. Depending on the context that it's in. 

The actual type that we get for site_id is `i32`. To be specific we get an optional `i32`. We need to update files that are relating to contact form and is using site_id in order to match the type that is given. 

Service layer `contact_form`
- current type is string which is to be converted to be a optional `i32`
- we need to support the case of this value being optional within this file

Repository layer `contact_form`
- current type is text which is to be converted to be `integer`

**Comment by lache-melvin** [comment]
Hi - I think easiest option actually is to remove site_id from contact form row. We already have store_id, which we will need to join to later to get extra info for email anyway. store_row has site_id already 🚀
