### ISSUE TITLE
Log and Ledger tabs broken when viewing stock detail in Portuguese 

### ISSUE THREAD

**Issue by noel-yeldos** [msupply-foundation/open-msupply#5748]
## What went wrong? 😲
Found while investigating #5511 

It appears that the log and ledger tabs in stock detail view, when viewed in Portuguese, display as one broken tab rather than two distinct tabs.

All other languages seem fine. Not sure if this issue is present in other parts of the app.

![image](https://github.com/user-attachments/assets/cce6666c-c119-428d-8eb9-8153a644934f)

## Expected behaviour 🤔

Log and Ledger should appear as distinct tabs and there should be no overlap of the two tabs.
![Screenshot 2024-12-11 at 1 10 46 PM](https://github.com/user-attachments/assets/c4f749ee-fc73-4459-9092-6c7e3ca632f5)
![Screenshot 2024-12-11 at 1 11 02 PM](https://github.com/user-attachments/assets/e2e5259f-d69a-4848-91e4-31e53a72b188)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inventory -> View Stock
2. Click on an item in List view to open detail view
3. Click on Log and Ledger tabs
4. Observe that they operate as separate tabs
5. Switch language to Portuguese
6. Click on Registro
7. See broken tabs

## Your environment 🌱

- Open mSupply Version: 2.5.00
- Legacy mSupply Central Server Version: 7.18.20

Issue occurs on both Chrome and Tablet (2.4.00-RC3)
- Platform:

- Database type: SQLite

**Comment by roxy-dao** [comment]
Set high as would be nice for demos even if we don't have any Portuguese users until first quarter 2025

**Comment by andreievg** [comment]
Assigned to Korimako, maybe because both tabs have the same name

**Comment by noel-yeldos** [comment]
@lache-melvin suspected the same. Do we need to check with Taina re:translations?

**Comment by lache-melvin** [comment]
@regotaina can you recommend a different translation for one of "Log" and "Ledger" for us here? vs "Registro"?

**Comment by regotaina** [comment]
> @regotaina can you recommend a different translation for one of "Log" and "Ledger" for us here? vs "Registro"?
sure! funny that both could be 'Registro'.

Let's stick with 

 Log = ' histórico' 
 
 Ledger = ' registro '
 
 will have to check other strings on Web server

**Comment by marthakeezy** [comment]
Tested in `V2.5.0-reports`, ledger appears to be working fine when switching language to Portuguese. Moving to done ✅
