### ISSUE TITLE
Server installer has incorrect icon

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5758]
## What went wrong? 😲

How did this happen??

![image](https://github.com/user-attachments/assets/a0a7513a-daa0-4145-85c8-4d241ac04ecf)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Run the server upgrader

## Your environment 🌱

- Open mSupply Version: 2.4.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by mark-prins** [comment]
<img width="993" alt="Screenshot 2024-12-12 at 11 41 27 AM" src="https://github.com/user-attachments/assets/7bdefabf-f7dd-4708-8b1a-ed80d9a40ffe" />

🤔

**Comment by mark-prins** [comment]
fixed by correcting the setup factory theme on jenkins

**Comment by alainsussol** [comment]
Tested with v2.5.0-reports2

![Image](https://github.com/user-attachments/assets/abc9fcf9-1671-443b-b412-684288c80b09)

I think it is the right one.
