### ISSUE TITLE
Print QR Code Purpose isn't clear

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5763]
## What went wrong? 😲

In Cold Chain Equipment Detail View we have a `Print QR Code` button
![image](https://github.com/user-attachments/assets/acc505ea-6b87-4c66-ae33-6995eda6e56d)

However, it actually prints an asset label containing a QR code.
Suggested change it to call it `Print Asset Label`

## Expected behaviour 🤔

Button says `Print Asset Label`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open Coldchain -> Equipment -> Select an Asset
2. See Print QR Code button

## Your environment 🌱

- Open mSupply Version: 2.4.1
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by jmbrunskill** [comment]
@mark-prins can you confirm if you're ok with this wording change?

Docs will also need updating based on this change.

**Comment by mark-prins** [comment]
sure - thanks @jmbrunskill, change sounds good.

**Comment by marthakeezy** [comment]
New wording is there, tested in `V2.5.0-RC7`

Moving to Done ✅
