### ISSUE TITLE
Item usage and Expiring items fix

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5783]
## What went wrong? 😲

Add item usage and expiring items fixes to v2.4.2 for Mali demo

## Expected behaviour 🤔

Item usage and expiring items reports needing various fixes:

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Can you link the issues that were fixed with this?

**Comment by roxy-dao** [comment]
Closed in https://github.com/msupply-foundation/open-msupply/pull/5784

**Comment by marthakeezy** [comment]
V2.4.2 got released, but there are still some issues - passing this issue and moving to done, however keeping this one open to revisit the reports: #5772
