### ISSUE TITLE
Foreign Currency: decimal points are not defaulting to 00 when using XOF/XAF

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5795]
## What went wrong? 😲

Coming from #5777 

When clicking on an item added to the Outbound Shipment, FC Sell Price is not set to 0 decimal points - also there seems to be an issue of showing 5+ decimal points - possibly need to be rounded and shown as 2-3dp? Or 0?

<img width="1062" alt="2" src="https://github.com/user-attachments/assets/6c452fba-17e3-41f4-8a99-0385b1015eb4" />

<img width="1035" alt="5" src="https://github.com/user-attachments/assets/d2b4d86e-33df-4941-aea4-941e0221f380" />

## Expected behaviour 🤔

As per above

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure the foreign currency preference is enabled for your store
2. Add XOF/XAF/CDF currencies to your datafile
3. Go to Distribution -> Outbound Shipments
4. Create a new outbound shipment to a customer that is not a store (important: if you create to a store, you won't be able to change foreign currency)
5. Click on the items you added - see FC Cost is not rounded to 00 decimal points

## Your environment 🌱

- Open mSupply Version: `V2.4.2-RC1`
- Legacy mSupply Central Server Version: `V7.19.00-RC5`

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by roxy-dao** [comment]
This isn't an issue. XOF doesn't have decimals, that's just their separator for large numbers
