### ISSUE TITLE
Item usage fix for postgres

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#5799]
## What went wrong? 😲

I item usage report fails on 2.4.2-RC1 on postgres with message about item.id should appear in group by clause

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by roxy-dao** [comment]
Closed in #5800
