### ISSUE TITLE
Family Planning/Reproductive Health module: nationality does not save in a new patient schema

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5817]
## What went wrong? 😲

@Rajajajaja @richardmoizeau 

Nationality does not save when using the new patient schema

Video uploaded ->>> [here](https://drive.google.com/drive/folders/1NxvIgPu0erGtxI_-8KvbiPhBm8r-f2FY)

## Expected behaviour 🤔

Nationality field should save

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have Programs and Family Planning enabled in your store
2. You will need to have the new patient JSON forms uploaded
3. Go to Dispensary -> Patients, create a new patient or modify an existing one
4. Choose their nationality -> save -> navigate away
5. Navigate back -> the field is not saved

## Your environment 🌱

- Open mSupply Version: `V2.4.1`
- Legacy mSupply Central Server Version: `V7.19.00`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `SQLite3`

**Comment by mark-prins** [comment]
Problem is in the program schema repo. Have added the fix to [this PR](https://github.com/msupply-foundation/programschemas/pull/12)

**Comment by mark-prins** [comment]
For reference, here are the updated JSON files
[patient_ui_schema.json](https://github.com/user-attachments/files/18271817/patient_ui_schema.json)
[patient.json](https://github.com/user-attachments/files/18271818/patient.json)

**Comment by marthakeezy** [comment]
Passed in V2.5.0-RC2 with the new patient schemas - moving to Done ✅
