### ISSUE TITLE
Unable to run reports

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5870]
## What went wrong? 😲

https://github.com/user-attachments/assets/124b45ac-a83a-41f2-9ef6-a03765336e37

## Expected behaviour 🤔

Able to run reports and view data

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Log into your store
2. Go to Reports -> run a few
3. See blank pages

## Your environment 🌱

- Open mSupply Version: `V2.5.0-reports`
- Legacy mSupply Central Server Version: `V7.19.00`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `SQLite3`

**Comment by alainsussol** [comment]
Tested in #5885
