### ISSUE TITLE
Changes to family planning module

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#5877]
## Is your feature request related to a problem? Please describe 👀

A few changes requested ahead of the final report for family planning. There are others in the program schema which will be addressed separately.

## Describe the solution you'd like 🎁

1. Rename  `Médecin` to `Praticien(ne)` in the toolbar
2. Rename `Montant` to `Quantité` in the encounter prescription stock table

![image](https://github.com/user-attachments/assets/4c851eab-b54b-456a-a95a-7cefc322da24)

![image](https://github.com/user-attachments/assets/d03f878f-299c-49ef-9b4e-c5028d25e9be)

**Comment by marthakeezy** [comment]
Passed in the newest JSON schemas - moving to done ✅
