### ISSUE TITLE
Duplicated SOH (Stock on Hand) cell under Inventory -> View Stock

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5900]
## What went wrong? 😲

I am not sure if this is a duplicated cell under SOH, or if one of the column headers is simply missing so one cell appears doubled. I think SOH cell is duplicated as there is nothing else for the item that has a quantity of 500.

<img width="1252" alt="Screenshot 2024-12-24 at 4 45 55 PM" src="https://github.com/user-attachments/assets/6f1ec92e-2e67-42a6-9c26-2f87d7b646cb" />

## Expected behaviour 🤔

Single cell showing the exact same information

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upgrade to V2.5.0-reports2 
2. Go to Inventory -> View Stock and click on any item
3. If your page is empty, you probably have no stock in your store so make sure to add some to any item and then revisit this item when testing
4. When viewing 'View Stock' page, note the SOH cell appears to be duplicated

## Your environment 🌱

- Open mSupply Version: V2.5.0-reports2
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Google Chrome (browser on Mac)

- Database type: PostgreSQL

**Comment by roxy-dao** [comment]
Closing as I can't see this in current develop in code or in UI. Can reopen if it is an actual issue
