### ISSUE TITLE
New action buttons are unclear

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5901]
## What went wrong? 😲

When selecting lines in an Outbound Shipment, the new wording for action buttons appearing at the bottom are confusing - why there are two buttons that have the exact same wording? Although they seem to generate different prompts when clicked on

Screenshot attached ->>> [here](https://drive.google.com/drive/folders/1cg4LkIyQ1tMBMFACuh5JcYQK2o4bFFTu)

## Expected behaviour 🤔

Buttons should have clearer definition of what they do, at least different wording

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Upgrade to V2.5.0-reports2
2. Go to Distribution -> Outbound Shipments
3. Create a new outbound shipment and add an item to it
4. Click on the checkbox to the left to select the item -> see action buttons appear at the bottom
5. See different buttons worded the same way - confusing!

## Your environment 🌱

- Open mSupply Version: V2.5.0-reports2
- Legacy mSupply Central Server Version: V7.19.03

- Platform: Google Chrome (browser)

- Database type: PostgreSQL

**Comment by roxy-dao** [comment]
Known issue. Should be fixed whilst all the other views are being overhauled
