### ISSUE TITLE
[ui]: 'Add Prescription/Encounter/Program' to change depending on the active tab

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#653]
Would it be possible to have the button change depending on the active tab ? Eg. If I'm looking at the tab "Programs" then button is "Add Program". 

You should always be able to change it though.

**Comment by clemens-msupply** [comment]
Also remove the prescription button...

**Comment by andreievg** [comment]
@richardmoizeau is this still relevant, and would this potentially be in the pipeline anytime soon (checking if we can close some issues)
