### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#705]
A potential client has raised the concern that there isn't any built in reporting. Leaving the dashboard aside, some basic reports are very useful in the field.

Suggestion: use the current tera templating / report printing to produce PDF reports, extend the types of report available, and introduce a `Report` page.

Realistically though, an excel report would be required. Investigate whether we could use a tera template for this, export to excel in the server and send the file ( as per PDF ), or implement f/e as the csv export is doing currently.

Perhaps replace the csv export with a server-side excel export?

See also the remaining items in #68

**Comment by craigdrown** [comment]
Q: if server sends Excel, what does client do on Android?
I kinda like server sending HTML and client making Excel if user wants it, but I know that has lots of technical issues (and I also worry about us blowing out the size of the JS we're sending to the F/E - maybe irrationally).
I've previously played with https://github.com/MathNya/umya-spreadsheet/ and liked it but was slow (I know, can't say Rust and slow, but it was - just checked and [PR #73](https://github.com/MathNya/umya-spreadsheet/pull/73) has most likely addressed it. ). It has the advantage over other crates that it is a reader and writer - don't have to add anything else later for digesting incoming Excel, which can only be a matter of time before it's needed.

**Comment by mark-prins** [comment]
yes, fair point. There are apps which can work with sheets, but that is difficult on a tablet. Better to have a selection and allow the client to request a format. I've used a very neat js excel package - and even though the bundle size is ok with caching - I'd prefer to have logic in the server for the data manipulation.

For the current reports - the client requests either HTML or PDF: the HTML option was introduced for android.

**Comment by andreievg** [comment]
There are a couple of other fresher issues, i wonder if we can close this one

**Comment by mark-prins** [comment]
Closing in favour of #2256 & #2059
