### ISSUE TITLE
Programs/Patient Registration Form: Drugs allergies

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#790]
Possibility to load the list of items visible to the store. However, if you have 3 or 4 different items for Paracetamol would that mean that you have to select all 4 items if a patient is allergic to it ? Any thought @craigdrown ? 

Combine with free in case the drug is not found in the list.

**Comment by mark-prins** [comment]
yes, a list of items would be tricky to use and potentially very long. We only have the items in the current store - I'm assuming that would be ok?
If they assign universal codes, then (in theory) we could instead show the common constituent instead

**Comment by richardmoizeau** [comment]
Yes I just saw that in Dhanya's presentation. I think that's what we should populate so that later, we can use that information to warn the prescriber about patient allergy. Would it be possible to populate the list of constituent instead of the items list ?

**Comment by mark-prins** [comment]
it would require adding the universal code to each item - and would need some changes to the universal codes API as well as some coding in omSupply. I think that it would be useful though, so would be good to do
