### ISSUE TITLE
Add `.sqlite` to generated sqlite database files

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#817]
Currently when I run omSupply in dev, it creates a file called `omsupply-database`. It'd be more convenient if this was named `omsupply-database.sqlite` as then when I open it, my OS (Mac) tries to use my preferred DB app rather than a text editor as it currently does. 

Shouldn't affect pg based dbs in anyway I'd think.

**Comment by clemens-msupply** [comment]
Your OS sucks because mine just handles it fine ;-) But yes think it's a good idea.

**Comment by CarlosNZ** [comment]
You can already set the database name in the .yaml config. So you can just set the name to "omsupply-database.sqlite" for your local config.

Is this enough?

**Comment by Chris-Petty** [comment]
@CarlosNZ oh duh. Yea probably enough. Though... could we change the default yaml to make the filename clearer by default?

**Comment by CarlosNZ** [comment]
> Though... could we change the default yaml to make the filename clearer by default?

By "clearer" do you mean put the "`.sqlite`" in the default config?

I think the reason that might not be a good idea is if you're using postgres, it doesn't make sense to have a .sqlite as part of the database name. 🤷‍♂️

**Comment by Chris-Petty** [comment]
I agree it wouldn't make sense for postgres - I had assumed that'd be a separate part of the yaml config given you should be configuring postgres on your machine and then specifying a database name, port, user etc. ? Fairly different to sqlite

**Comment by Chris-Petty** [comment]
For a random other example from directus that supports many many databases, their yaml https://docs.directus.io/self-hosted/config-options.html#database. Sqlite there is a specific option for `DB_FILENAME`, while all the database servers they support they use `DB_DATABASE` along with port username etc.

**Comment by mark-prins** [comment]
I like the `DB_FILENAME` concept - for us it might make things less good, as we'd have to have `database_name` and `database_file` as optional strings in the config schema. Currently we can validate the schema easily and panic if the database_name isn't specified. 

I would just add a comment in the yaml, and maybe update the example. If we add `.sqlite` when generating the files, then the name in config doesn't necessarily match (exactly) the filename

**Comment by Chris-Petty** [comment]
When installing omSupply on windows how do you select postgres or sqlite? Is it part of the installation steps, or separate installers? Otherwise I'm only aware of using feature flags for development.

FWIW directus style again, their yaml has a mandatory key `DB_CLIENT` which specifies which database client to use and naturally other things are mandatory based on that.

Definitely agree not to just chuck it on when generating the files!

Also this is definitely a low priority, delightful dev only issue at the moment so no rush on it. Easy work around already just doing it in local yaml. Wouldn't be offended if it was just closed as not doing/icebox.

**Comment by mark-prins** [comment]
It's part of the installation steps - requires a different binary, so we have both in the installer and just delete the unwanted one

**Comment by clemens-msupply** [comment]
This might do it already. In `repository/src/database_settings.rs`:

```rust
// feature sqlite
#[cfg(all(not(feature = "postgres"), not(feature = "memory")))]
impl DatabaseSettings {
    pub fn connection_string(&self) -> String {
        format!("{}.sqlite", self.database_name.clone())
    }
    ...
```

This should also work with Android but probably good to double check...

**Comment by Chris-Petty** [comment]
@clemens-msupply it seems you're suggesting it does this already but the code looks like this to me?

https://github.com/openmsupply/open-msupply/blob/7725ab2c57e251d45ecd41a78c7a61ac5ad2a749/server/repository/src/database_settings.rs#L47-L53

If suggesting that as a change, then I was agreeing with mark that it'd be better if it matched the yaml... but thinking about it again I'm not really fussed adding a file extension seems like it's not a big deal...

Bike shedding conclusion:

1. Do we want this feature change? If no just close the issue, this would be fine. It's mostly a dev issue. 
2. Add one or 2 properties in yaml to allow giving a name specifically for the sqlite database file. Mild complexity add.
3. Just add the extension to the file name from the existing yaml property. Trivial but mild mismatch.

Note: 2 and 3 need to make sure it doesn't break existing installations by losing the sqlite database file (because it looks for a file `"databaseName.sqlite"` rather than the original `"databaseName"`.

I'm... just going to close it unless someone wants to take it.

**Comment by Chris-Petty** [comment]
Tangent - if you're a tester trying to test a build on windows, is there an easy way to open omSupply with a different datafile? Or does it just have to match the path and filename of any existing datafile or edit env etc.?

**Comment by CarlosNZ** [comment]
> Do we want this feature change? If no just close the issue, this would be fine. It's mostly a niche dev issue (though for laymen users looking at their filesystem it might be a bit clearer if there was a file extension).

I'd say leave it open for now, as it'll be pretty simple to include with #2290.

I'll post a suggested config setup on that issue that takes this into account as well.

**Comment by CarlosNZ** [comment]
> I'll post a suggested config setup on that issue that takes this into account as well.

https://github.com/openmsupply/open-msupply/issues/2290#issuecomment-1749935303 :)

**Comment by clemens-msupply** [comment]
@CarlosNZ can't Finder/Spotlight really not be configured to detect the mime type and then associate this type with a DB browser?

@fergie-nz just appending `.sqlite` breaks loading existing database files. You could check if a file without extension exists and use this before appending `.sqlite`... We should test if this works on Android as well!

**Comment by CarlosNZ** [comment]
> @CarlosNZ can't Finder/Spotlight really not be configured to detect the mime type and then associate this type with a DB browser?

Yes, it can. Just `Cmd-I` on the file, then select your preferred app with the "Open With:" selector:
![Screenshot 2024-01-23 at 12 19 32 PM](https://github.com/msupply-foundation/open-msupply/assets/5456533/cb77704c-711c-4ecc-9b1f-0adb80cfd17a)

**Comment by clemens-msupply** [comment]
> Yes, it can. Just `Cmd-I` on the file, then select your preferred app with the "Open With:" selector: ![Screenshot 2024-01-23 

I meant, can't it figure out the `Kind: SQLDocument` without extension. For example, you can usually detect the file type by looking at the first couple of bytes in a file, think this is what my file browser is doing...

**Comment by CarlosNZ** [comment]
> I meant, can't it figure out the `Kind: SQLDocument` without extension. For example, you can usually detect the file type by looking at the first couple of bytes in a file, think this is what my file browser is doing...

It seems to do that for binary executables, but for everything else it relies on file extension. However, you can specify a default app on a case by case basis using the above method.

FWIW, there are very few files on Mac OS without an extension, mainly just the executables I think (a lot of them have the extension hidden, depending on user settings, but it's still there)

FYI -- the really old Macs (pre OS X) used to not have any file extension and utilise something like you're describing to associate files with applications, but this seems to have been changed somewhere along the line, presumably to be more in line with Windows, which (I think) exclusively uses file extensions to determine types.

**Comment by Chris-Petty** [comment]
You guys discussed and concluded what I had to say before I could...

Adding a new complaint - the vscode sqlite extension I use seems to filter by file extension too so I can't easily select "omsupply-database".

Tangentially, sorta funny that the test suites generate sqlite files with `.sqlite` as the file extension but the main app doesn't 😁. But at least easy enough to locate/inspect them with the vscode extension I use

**Comment by clemens-msupply** [comment]
Ok, I think the solution to go is:
1) if database_name ends with .sqlite just use it -> done
2) take database_name and check if database exists on disk (have to let connection_string(&self) return a `Result` to be able to fail on IO errors)
3) if database file exist use `database_name` as is
4) otherwise use `{database_name}.sqlite`
