### ISSUE TITLE
FE: Directory structure refactor

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#830]
## Problems
- `packages/system/src/Patient/JsonForms` is not just patient related but related to all programs related documents (move it up)
- Four locations for program apis. This is sometimes a bit confusing, especially when types are defined in two apis but used in the the same file. Merge theses apis?:
  - `packages/system/src/Patient/JsonForms/api`
  - `packages/system/src/Patient/api`
  - `packages/system/src/Program/api`
  - `packages/system/src/Encounter/api`
- `packages/system/src/Program` is quite empty and content could moved to where it is used
- Naming could be improved, e.g. `packages/system/src/Patient/Encounter/DetailModal.tsx` is about creating new encounters...
- There are `usePatientCreateStore`, `usePatientModalStore`, `usePatientStore` could they be unified? otherwise they need some documentation to make it clearer when they should be used

## Planned changes:
- have a program package containing:
  - [x] all JSONForms components (split by `common` and `programs` controls)
  - [ ] All programs related folders from the system package
  - [x] one `api` folder with all program apis
- [x] keep `Patient` in the system package
- [x] rename DetailModal to make clear its create related
- [ ] try to unify `usePatientCreateStore`, `usePatientModalStore`, `usePatientStore` where possible

**Comment by andreievg** [comment]
Can the issue be made from outstanding points and re priorities ?

**Comment by clemens-msupply** [comment]
I just close for now, if we feel the need for further refactoring we can create a new issue...
