### ISSUE TITLE
Response Requisition Modal Carry Over 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#852]
Graphs for the customer tab
![image](https://user-images.githubusercontent.com/61820074/203857323-3ca78f5d-8fc2-4bfb-997b-372a8e4208c7.png)

`Richard`: Another thing would be for the system to automatically calculate the quantity to allocate when there is not enough stock:

Requested Quantity: Customer A = 25, Customer B = 35, Customer C = 40 (Total = 100)
Supplier's Stock on Hand = 50
Customer's AMC: Customer A = 10, Customer B = 20, Customer C = 50
System would then allocate the 50 units based on the AMC of each store:
-- Customer A = 6
-- Customer B = 13
-- Customer C = 31
This way, we help user decide a fair way of distributing stock when there is not enough ! (Just an idea) System could suggest it the same way we are suggesting quantity to order (with a button ?).
Another thing you usually do is to define a minimum stock that you keep for yourself so you don't give away everything.

**Comment by andreievg** [comment]
I feel like this one might be very far up the track, since customer information might not be available because it lives on a different site, it's not trivia. As for auto allocation, this also feels like an optimisation that is in a very distant future. Feel free to re-open but will close for now
