### ISSUE TITLE
Programs: patients can qualify from a program to another

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#854]
Context: 
It has been decided to create 2 separate workflows (enrolment, encouters) for the national HIV program: HIV testing and HIV Care. We are considering create 2 additional programs for HIV Care for infants and HIV testing for target populations. 

Capability: patient may have to be enrolled consecutively in 2 different programs during their care. Example: a patient is enrolled into HIV testing. If during an encounter, he is tested positive for HIV, he will be enrolled into the HIV Care. We would like the system:
1. to automatically suggest to enrol the patient into the HIV care program (note that testing facility may be the same as the HIV care facility). Suggestion: if HIV test result = positive and when clicking on the encounter's button "Save", a pop-up asking if user would like to proceed with the enrolment of the patient in the HIV Care program. Should be fine if testing facility = care facility. But what if the care program is in another facility/store ? I think now user can only enrol patient in its own facility (the one it's logged into)
2. to carry over some data points over to the new program: Date confirmed HIV positive, Risk group(s)

Another case would be for infant when they reach the threshold age (I think 2 years old, 24 months) - if they are still positive when reaching the age of 2, they should qualify into the standard HIV care.

**Comment by clemens-msupply** [comment]
Not applicable anymore as described...
