### ISSUE TITLE
[prog][epic]: patient transfer to another faciltiy

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#855]
Context: 
A patient enrolled in a program in a facility can be transferred to another facility. 

Capability: user (with proper authorisation) should be able to initiate a transfer request and have it approved by the other facility. When approved/finalised, patient records (registration, enrolment and encounters details) are transferred to the new facility. Encounters made in the previous facility should show the previous facility name. 

Need to confirm with TWG if records should no longer be accessible by the previous facility (I don't think so) However, patient can remain registered and enrolment/program status should show "Transferred Out". Patient status is now 'active' in the new facility

Other case: we should also have a way to do transfers when the new facility is not using mSupply, basically same as above but records transfer. 

Related topics/discussions:
- should we also transfer "dispensing records" or at least the history ? (maybe the encounters data are enough) 
- are transferred to be done for all records (registration, enrolments and encounters) or just for enrolment and encounters?
- One of the program status is "Transferred Out" so I imagine that the status could be automatically updated when a transfer is approved. 
- when a patient is transferred from and in a facility using mSupply, system should be able to reconcile when aggregating data across facilities that if a patient is transferred out in one but still active in other then patient is active (at an aggregated level)
- Transfer in details (see screenshot below): transfers details should be captured in a new section of the patient's new facility enrolment form (Clinic transferred from, Previous clinic ID, Prior ART (regimen of the last encounter before transfer). Previous clinic ART start date) on top of the other enrolment data. No need to show them for a patient that has never been transferred. 

![Screen Shot 2022-11-25 at 2 19 52 PM](https://user-images.githubusercontent.com/74992958/203882033-bf182e08-498a-4b51-9185-fdbc72981c82.png)

tagging @andreievg for technical guidance.

**Comment by richardmoizeau** [comment]
Following discussion with @craigdrown, have decided that this feature is not a high priority. However we would need to have in the enrolment form, the transfer-in details. I will create a separate issue for this.

**Comment by DhanyaHerath** [comment]
@richardmoizeau do you think we should close all programs issues that we think won't be done in the next 6 months? We can always reopen them later, but until we get funding maybe good to filter them out for now?

**Comment by clemens-msupply** [comment]
Closing for now. We record transfer details for transfers to external facilities in the forms.

Furthermore, we can access mSupply patients on different sites.
