### ISSUE TITLE
[prog][ui xp] Patient encounter navigation

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#859]
It can be confusing that there is an encounters list for all patient and a list of encounters for a single patient.

- [ ] When on in a patient encounter change the breadcrumb to refer to the patient
- [ ] Add an patient icon on the patient screen

**Comment by clemens-msupply** [comment]
@mark-prins did we agree on the icon? or was it clear enough

**Comment by mark-prins** [comment]
we didn't 😉  but I thought to use the `user` icon from feather: https://feathericons.com/?query=user
