### ISSUE TITLE
Sync status integration progress

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#886]
![image](https://user-images.githubusercontent.com/7684221/204964804-2e994ad0-842e-4af5-befd-1822700acf41.png)

The last step here of `integration` could use a progress. The other steps say `n/total` records, integration surely could too! In my big data testing this is the slowest part... though perhaps I'm still getting loads of errors 😁.

**Comment by andreievg** [comment]
Should be pretty simple, we just pass the SyncLogger to integration and every X number of records log the progress.

**Comment by andreievg** [comment]
A nice to have is number of records that had errors, and some display for that (they are recorded in sync_buffer)

**Comment by andreievg** [comment]
Low priority as this is `nice to have`

**Comment by mark-prins** [comment]
as noted in [this comment](https://github.com/openmsupply/open-msupply/issues/924#issuecomment-1345643003) can you also handle a crash in the integration gracefully, and return an error so that we can display in the UI
