### ISSUE TITLE
[ui] Encounters: navigate from one section to another

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#891]
Add a "Ok and next" and "Previous" button to the encounter's sections ("Physical Exam", "ARV / Medication") on top of the "Save" button. 

This way, user could capture all the data in one without going back to the encounter interface. 

Another "nice to have": showing the title of the next or previous section. 

for the order let's keep it in order of appearances for now - but could change based on TWG's feedback.

**Comment by mark-prins** [comment]
@clemens-msupply this is tagged as low priority - should I remove from the sprint?

**Comment by clemens-msupply** [comment]
@richardmoizeau think its a good idea but will close for now. Can create a new issue if it becomes a problem...
