### ISSUE TITLE
Integration errors: Response requisitions don't support "sg" status

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#894]
Integration of legacy mSupply records throws errors on `response` requisitions with status "sg"

```jsonc
{
  "ID": "ECAAF0807B55DE4DB1EB63F7C46DDA66",
  "authorisationStatus": "none",
  "colour": 1,
  "comment": "From request requisition 27",
  "date_entered": "2020-03-06",
  "date_order_received": "2020-03-10",
  "date_required": "0000-00-00",
  "date_stock_take": "2020-03-06",
  "daysToSupply": 90,
  "isRemoteOrder": false,
  "is_emergency": false,
  "lastModifiedAt": 1583824233,
  "linked_purchase_order_ID": "",
  "linked_requisition_id": "018498E8DE690748A05284133CE90E4C",
  "name_ID": "A6FFF744750E0D41922B8FE2FAC93020",
  "nsh_custInv_ID": "",
  "om_colour": null,
  "om_created_datetime": null,
  "om_expected_delivery_date": null,
  "om_finalised_datetime": null,
  "om_max_months_of_stock": null,
  "om_sent_datetime": null,
  "om_status": null,
  "orderType": "",
  "periodID": "",
  "previous_csh_id": "",
  "programID": "",
  "requester_reference": "From request requisition 27",
  "requisition_category_ID": "",
  "serial_number": -1,
  "status": "sg", // THIS
  "store_ID": "6CFDCD1916B098478422A489625AB9E7",
  "thresholdMOS": 0,
  "type": "response", // COMBINED WITH THIS
  "user_ID": ""
}
```

This causes errors on integration: `"Unsupported requisition status: Sg"`

## Reproduction steps

1. initialise omSupply with a previously mSupply desktop store/site
2. Any old mobile/desktop response requisitions that haven't been processed yet (confirmed) from other stores to that omsupply site will fail to integrate

# Part 2

Interestingly this is only a problem with old response requisitions. You don't get the issue when you do:

1. Create a request requisition (internal order) in omSupply to a mSupply desktop site/store
2. (central server generates a "response" requisition for the other store. Duplicating the "request" record)
3. Sync
4. The response record is sent back and integrates fine, because omSupply has been tricked into thinking it's from another omSupply site as the duplication carried over the the omsupply values in the _request_.

This seems fine at first, until you consider what it means when you convert that mSupply site to omSupply:

1. StoreA/SiteA is on desktop, StoreB/siteB is omSupply
2. Send a request requisition from StoreB to StoreA
3. SiteA now has a response requisition with `om_status: "SENT"`
4. Desktop is so out of fashion... Initialise a new instance of omSupply with siteA
5. SiteA now has a bunch of response requisitions with `om_status: "SENT"` which were never processed...? These requisitions might have a legacy status of "fn" too if they were processed on legacy desktop...

What a response looks like in this case:

```json
{
  "ID": "C17A92A5B1D64CE68F4E7957063041E1",
  "authorisationStatus": "none",
  "colour": 1,
  "comment": "From request requisition1",
  "custom_data": null,
  "date_entered": "2022-12-02",
  "date_order_received": "2022-12-02",
  "date_required": "0000-00-00",
  "date_stock_take": "2022-12-02",
  "daysToSupply": 30,
  "isRemoteOrder": false,
  "is_emergency": false,
  "lastModifiedAt": 1669951572,
  "linked_purchase_order_ID": "",
  "linked_requisition_id": "4bcf514c-c35d-4666-8547-7968d8bc0a3d",
  "name_ID": "A6FFF744750E0D41922B8FE2FAC93020",
  "nsh_custInv_ID": "",
  "om_colour": null,
  "om_created_datetime": "2022-12-02T02:20:14.211921",
  "om_expected_delivery_date": "2022-12-16",
  "om_finalised_datetime": null,
  "om_max_months_of_stock": 1,
  "om_sent_datetime": "2022-12-02T03:18:45.871663",
  "om_status": "SENT", 
  "orderType": "",
  "periodID": "",
  "previous_csh_id": "",
  "programID": "",
  "requester_reference": "From request requisition1",
  "requisition_category_ID": "",
  "serial_number": 1260,
  "status": "sg",
  "store_ID": "6CFDCD1916B098478422A489625AB9E7",
  "thresholdMOS": 1,
  "type": "response",
  "user_ID": "15C12F0F986CDB46B47A71A7B55AFB6C"
}
```

# Agreed solution

TBD.

## Part 1

This code just maps `"sg"` to `None` here, so it throws a wobbly: 
https://github.com/openmsupply/open-msupply/blob/e6595e2f2ac2894f6085b0c8485283a7c4aeaff9/server/service/src/sync/translations/requisition.rs#L373-L393

Solution: I think it should map `sg` to `Draft`.

## Part 2

I think this is realistic enough, as we're set to install omSupply at many health posts on android, while their supplying stores remain on mSupply desktop _for now_.

Solution: Tweak central server to not copy the omSupply fields when generating the "response". It's a bit of a mess copying them over like this. Requires part 1 to be done so they actually get integrated properly after we do this.

**Comment by andreievg** [comment]
If we go with mapping `sg` to `Draft`, then we would allow existing mSupply, ongoing response requisitions to carry over being editable in omSupply, this would need to be thoroughly tested, making sure all existing and future assumption about editable omSupply response requisition record is fully backwards compatible with response requisition (existing and future) in mSupply. I think it's a bit too much overhead and too many use cases, would prefer if we ignore them or set them to `Finalised` status. (I think it's safe to ignore imo)

Btw code permalink is showing the `:Request` i think the issue is with response ?

`Part 2`, at a glance it's ok to ignore response requisition that is being sent back to request site

**Comment by Chris-Petty** [comment]
> If we go with mapping `sg` to `Draft`, then we would allow existing mSupply, ongoing response requisitions to carry over being editable in omSupply, this would need to be thoroughly tested, making sure all existing and future assumption about editable omSupply response requisition record is fully backwards compatible with response requisition (existing and future) in mSupply. I think it's a bit too much overhead and too many use cases, would prefer if we ignore them or set them to `Finalised` status. (I think it's safe to ignore imo)
> 

I agree that it opens the door for further testing. What I've been doing in so far is further testing and addressing the errors that integration throws (fix datetime deserialising -> reveal this new requisition error) - this will open new behaviours that require deeper functional testing of omSupply.

My understanding has been we're doing backwards compatible, so have been striving for it. If I was a user/deployer I'd assume that this works, and users will _definitely ask where their orders have gone_, they were there just before and now they can't fulfill what store X ordered earlier in the week. If not I think we need a KDD for each decision, detailing the consequences particularly around how consultants/trainers doing deployment in country will have to handle records that don't smoothly migrate over.

> Btw code permalink is showing the `:Request` i think the issue is with response ?

I linked the whole function that matches on `:Request` and `:Response` thought it might be useful - but have narrowed it down now.

> 
> `Part 2`, at a glance it's ok to ignore response requisition that is being sent back to request site

Ok but I think that's what updates "Finalised" Status here right?

![image](https://user-images.githubusercontent.com/7684221/205520236-a455b24e-b8dd-4e41-8378-57a85a73ff94.png)

We'd need clear docs to explain to consultants/users of what's going on here - it's not a big deal, but we need to make sure a solid answer is known. As I understand the code, this would affect all internal orders in omSupply to legacy mSupply sites, which will be happening for years to come.

**Comment by andreievg** [comment]
>  As I understand the code, this would affect all internal orders in omSupply to legacy mSupply sites, which will be happening for years to come.

As far as I understand, the only concern for omSupply -> mSupply order in this case: omSupply request requisition would not have the knowledge of the response requisition and wouldn't be able to auto update it's status. 

> My understanding has been we're doing backwards compatible

Yep, there might need to be a limit though ? Should consult a stakeholder, but I would assume that editing existing mSupply records in omSupply would be that limit ? 

> Ok but I think that's what updates "Finalised" Status here right?

Yep, but surely we can say that these new status updates only work for omSup <-> omSup orders/invoices ?

> We'd need clear docs to explain to consultants/users of what's going on here

I agree, we should have a doc specific to mSup <-> omSup sync and upgrade limitations.

> and users will definitely ask where their orders have gone, they were there just before and now they can't fulfill what store X ordered earlier in the week

The question for stakeholders, is it ok to communicate this to user before upgrade (and make sure they either fulfill these orders before upgrade or create placeholder invoice) ?

Last note, maybe it's OK to just integrate those requisitions as `draft`, I just not sure if we should be spending too much time validating this.

**Comment by Chris-Petty** [comment]
> > As I understand the code, this would affect all internal orders in omSupply to legacy mSupply sites, which will be happening for years to come.
> 
> As far as I understand, the only concern for omSupply -> mSupply order in this case: omSupply request requisition would not have the knowledge of the response requisition and wouldn't be able to auto update it's status.
> 

In fairness I think this can be addressed in a later version of omSupply if it is flagged as an issue. Just reprocess the sync_buffer records.

> > My understanding has been we're doing backwards compatible
> 
> Yep, there might need to be a limit though ? Should consult a stakeholder, but I would assume that editing existing mSupply records in omSupply would be that limit ?
> 

Generally it seems editing existing unfinalised records is already within scope? If a "cn" response requisition syncs it's integrated with om_status "New". So it is already expected for response requisitions to be processed that came from desktop. I presume we're testing that functionality, at which point I can't imagine it being too different including "sg" -> "Draft"?

> > Ok but I think that's what updates "Finalised" Status here right?
> 
> Yep, but surely we can say that these new status updates only work for omSup <-> omSup orders/invoices ?
> 
> > We'd need clear docs to explain to consultants/users of what's going on here
> 
> I agree, we should have a doc specific to mSup <-> omSup sync and upgrade limitations.
> 
> > and users will definitely ask where their orders have gone, they were there just before and now they can't fulfill what store X ordered earlier in the week
> 
> The question for stakeholders, is it ok to communicate this to user before upgrade (and make sure they either fulfill these orders before upgrade or create placeholder invoice) ?
> 
> Last note, maybe it's OK to just integrate those requisitions as `draft`, I just not sure if we should be spending too much time validating this.

I think mapping "sg" -> "Draft" is just the laziest solution, that's why I'm into it 😁. Less questions coming my way the better - but only on the presumption it doesn't break things!

Speaking of breakages:

1. Create an internal order from legacy siteA to legacy store/siteB
2. Initialise omSupply with siteB
3. The response requisition fails to integrate
4. The transfer processor has errors, fails to make a response requisition (which would be a duplicate) because it finds the request has a linked id already set. Relevant logs below:

```
2022-12-08 12:23:52.577392 ERROR service::processors - Error in requisition transfer processor (Problem getting upsert record Linked requisition not found Requisition { requisition_row: RequisitionRow { id: "D5C8A9E536F2430FA76E32089B0A987B", requisition_number: 1261, name_id: "42C3465E74A0D54781BE28A4EF962776", store_id: "6CFDCD1916B098478422A489625AB9E7", user_id: Some("15C12F0F986CDB46B47A71A7B55AFB6C"), type: Request, status: Sent, created_datetime: 2022-12-08T00:00:00, sent_datetime: Some(2022-12-07T23:14:32), finalised_datetime: None, expected_delivery_date: None, colour: None, comment: None, their_reference: None, max_months_of_stock: 3.0, min_months_of_stock: 0.0, linked_requisition_id: Some("3B6318B0FAB0412C862616D13BEC3447") }, name_row: NameRow { id: "42C3465E74A0D54781BE28A4EF962776", name: "REDACTED", code: "SAI", type: Store, is_customer: true, is_supplier: true, supplying_store_id: Some("6CFDCD1916B098478422A489625AB9E7"), first_name: None, last_name: None, gender: None, date_of_birth: None, phone: None, charge_code: Some("SAI"), comment: None, country: None, address1: None, address2: None, email: None, website: None, is_manufacturer: false, is_donor: false, on_hold: false, created_datetime: None }, store_row: StoreRow { id: "6CFDCD1916B098478422A489625AB9E7", name_id: "E5D7BB38571C1F428AF397240EEB285F", code: "SDL", site_id: 1 } })  service/src/processors/mod.rs:83
2022-12-08 12:23:52.699600 ERROR service::processors - Error in shipment transfer processor (Problem getting upsert operation Error while fetching shipment operation ChangelogRow { cursor: 3097, table_name: Invoice, record_id: "D44F77C1E71AC64DA3EF4BA5052FA4EC", row_action: Upsert, name_id: Some("42C3465E74A0D54781BE28A4EF962776"), store_id: Some("6CFDCD1916B098478422A489625AB9E7") } Requisition not found "A6777524B7833947A5A194FFE04FB93B")  service/src/processors/mod.rs:83
```

Then you have a request requisition from some customer that never gets processed, because it gets lost for the supplier. Could tell users/consultants to confirm all requisitions first... or kludge here might be for the central server to make all "sg" response requisitions for the initialising store to be "cn"... That'd be the same as just doing "sg" -> "New" rather than "sg" -> "Draft" in omSupply though lol. 

I know one customer who already gets understandably frustrated when their orders don't show up for their suppliers!

**Comment by andreievg** [comment]
Low priority, don't have any planned deployments that upgrade existing sites

**Comment by andreievg** [comment]
Priority bumped to normal via vote

**Comment by roxy-dao** [comment]
Status for Response `sg` was mapped to `New` in #1495 and related issue #1396 here. Can this be closed?

**Comment by Chris-Petty** [comment]
@roxy-dao if we're not getting the error `"Unsupported requisition status: Sg"` then yea! Looking at that issue seems you're on the money, thanks!
