### ISSUE TITLE
Show created date in the detail panel for Invoice, Requisition, Stocktake windows 

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#911]
The created date shows in the logs, but not in the detail panel on the side. It would be great to have that show in this main window! 
Felt confusing to have something show in the listbox, but not the invoice itself (at least on first glance): 

![image](https://user-images.githubusercontent.com/29744386/205794998-98890b07-3f02-4efc-ba94-743013b3288c.png)

**Comment by bijaySussol** [comment]
@mark-prins @DhanyaHerath : 

Could you please share where this issue stands?
Thanks

**Comment by DhanyaHerath** [comment]
Hey @bijaySussol thanks for checking! I think Mark P mentioned that this actually shouldn't be set as a good first issue, as it requires both backend and frontend work. The other one you referred to might be a better one to start with ([#1117](https://github.com/openmsupply/open-msupply/issues/1117), but I will let @mark-prins confirm

**Comment by bijaySussol** [comment]
Thanks @DhanyaHerath

**Comment by nisha-dangol** [comment]
# Testing
Tested in v2.0.0 exe

- [x] Go to these views: Outbound Shipment, Inbound Shipment, Requisition, Stocktake, Prescription
- [x] Go to side panel
- [x] See created datetime
