### ISSUE TITLE
Sync info is being called every second on Sync page

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#931]
-> Go to `Sync` Page 
-> See API call in network

**Comment by Chris-Petty** [comment]
This definitely is annoying! You'll see it in the initialisation page as well, it pollutes the log a whole lot. Basically, doing the query to poll for changes was the easiest way to get the feature done I think. Alternatives require the server to push to client - websocket or something. My understanding is this is relatively low priority though as functionally it's all good. To that end the `enhancement` label might be more appropriate than `bug`?

**Comment by andreievg** [comment]
I linked to original issue, closing as duplicate
