### ISSUE TITLE
Open mSupply testing

### ISSUE THREAD

**Issue by alainsussol** [msupply-foundation/open-msupply#984]
# Building test cases
#### On Client
**Customers list**
- [ ] Clicking on Distribution > Customers should list the clients visible to your store (default ordering is ascending)
- [ ] At the bottom of the list the number of displayed customers is shown "Show X-Y of Z" where X is the number of the 1st record showing on the page, Y is the number of the last record showing on the page and Z is the total number of records visible for that store(?).
- [ ] Order customers by descending order by clicking on the Name at the top. The new ordering is correct (descending)
- [ ] Re-order by ascending order by re-clicking on the Name at the top. The new ordering is correct (ascending)
- [ ] At the bottom of the list the number of displayed customers is shown "Show X-Y of Z" where X is the record of
- [ ] You cannot add customers from the Client.
- [ ] Click on a customer. A window will open with the details of the customer.
- [ ] The following informations are available to be displayed. Check that information is correct for each of these field
    - [ ] The name of the customer - at the top (Mandatory)
    - [ ] Code (Mandatory)
    - [ ] Charge Code (Mandatory)
    - [ ] Date created (Mandatory)
    - [ ] Country
    - [ ] Comment
    - [ ] Phone
    - [ ] Website
    - [ ] Manufacturer
    - [ ] Donor
    - [ ] Website
 - [ ] Change the visibility of some the customer on the server. Some made visible and others made not visible on that store. Sync. Make sure the changes show when refreshing/reloading the list. 

#### On server

**Comment by nisha-dangol** [comment]
@alainsussol @mark-prins 
I noticed that in the customers list, we can see the name of the store we're currently logged in as well. Created issue #986 
Also, I see no any facility names in open-msupply store. Is this expected (new change) behaviour here?

**Comment by nisha-dangol** [comment]
# Building test cases(contd.)
## Items
### Adding Items
- Not possible, only to be done from mSupply Cloud Server
- [ ] You cannot add Items from the Client.

### Items List
- [ ] In the Navigation Panel, Clicking on Catalogue > Items should list the items visible to your store (default ordering is ascending sorted by item-code)
- [ ] At the bottom of the list is the number of displayed items shown "Show X-Y of Z" where X is the number of the 1st record showing on the page, Y is the number of the last record showing on the page and Z is the total number of records visible for that store(?).
- [ ] Order items by descending order by clicking on the Name at the top. The new ordering is correct (descending)
- [ ] Re-order by ascending order by re-clicking on the Name at the top. The new ordering is correct (ascending)

### Item Details
- [ ] Click on an Item. A window will open with the details of the Item with two tabs: General & Master Lists.
- [ ] Under General tab, there are four sections, namely:
  - [ ] Details
    - [ ] Name - (Mandatory)
    - [ ] Code - (Mandatory)
    - [ ] Unit - (Mandatory)
    - [ ] Strength
    - [ ] Defined Daily Dose
    - [ ] Type
    - [ ] Doses
    - [ ] Vaccine
  - [ ] Packaging
    - [ ] Default pack size - (Mandatory)
    - [ ] Outer pack size - (Mandatory)
    - [ ] Volume per pack - (Mandatory)
    - [ ] Volume per outer pack - (Mandatory)
    - [ ] Weight - (Mandatory)
  - [ ] Categories
    - [ ] ATC Category
    - [ ] Universal name
    - [ ] Universal code
  - [ ] Pricing
    - [ ] Margin
- [ ] Under Master Lists tab, it shows the list of Master Lists the item belongs to.
- [ ] It displays the following information
  - [ ] Code
  - [ ] Name
  - [ ] Description
- [ ] Above the Item details is the graphical dashboard representation of the items showing:
  - [ ] Available Stock
  - [ ] AMC
  - [ ] Months of Stock

## Master Lists
### Master List
- [ ] In the Navigation Panel, Clicking on Catalogue > Master Lists should list the Master List used by your store (default ordering is ascending sorted by Name)
- [ ] At the bottom of the list is the number of displayed master lists shown "Show X-Y of Z" where X is the number of the 1st record showing on the page, Y is the number of the last record showing on the page and Z is the total number of records visible for that store(?).
- [ ] Order the list by descending order by clicking on the Name at the top. The new ordering is correct (descending)
- [ ] Re-order by ascending order by re-clicking on the Name at the top. The new ordering is correct (ascending)

### Master List Details
- [ ] Click on a Master List. A window will open showing the list of items belonging to that Master List
- [ ] It shows following information of the items belonging to that Master List
  - [ ] Code
  - [ ] Name
  - [ ] Unit
- [ ] There is a More button at the top-right which consists of:
  - [ ] Additional Info: 
    - [ ] Comment
  - [ ] Actions
    - [ ] Copy to Clipboard button

**Comment by mark-prins** [comment]
Hi @nisha-dangol, thanks for getting the test cases written up! Great to have the site tested thank you!!


>     **Is the Date field mandatory? I definitely don't see any value for it in my setup**: (have tried to hide the info, since I'm using IC data for testing!)

The created date is not mandatory in the database. The field should be populated but there are stores in my test datafile with empty values.. so it must be possible.

> I noticed that in the customers list, we can see the name of the store we're currently logged in as well. Created issue #986 Also, I see no any facility names in open-msupply store. Is this expected (new change) behaviour here?

I thought that we had excluded the current store.. I see that you've created #986 so I'll fix it with that. thanks 😄

**Comment by alainsussol** [comment]
### Testing for East Timor

- [ ] setting up 
  - [ ] Behaviour when wrong credentials
    - [ ] URL 
    - [ ] Site name 
    - [ ] password
  - [ ] With Right credentials. Should initialise and pull info from the cloud **-PASS-** 
  - [ ] On login
  - [ ] user with no permissions should still be able to login but will be told to what he has no permission to when it is not self-evident (see #1224)
  - [ ]  Should get in to the Dashboard view **-PASS-**
